### ISSUE TITLE
[🐛 Bug]: ts page class is imported as .js and failing test when updating the import

### ISSUE THREAD

**Issue by testSadab** [webdriverio/webdriverio#9539] opened 2023-01-05 13:35 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.0.13

### Node.js Version

18

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    browserName: 'chrome'
    browserVersion: 'latest',
    platform: 'macOS'
}
```

### What happened?

i am using typescript with webdriverio and page objects files are also in .ts
In actual test import for page are written as .js which should not be the case .

When I remove the file extension (same approach as v7) and run then i get error 

### What is your expected behavior?

page import statement should not have file extension or based on actual file and test should run successfully.

### How to reproduce the bug.

git clone https://github.com/testSadab/WebdriverIOMochaTS.git
git checkout import_issue
npm install
npm run wdio

### Relevant log output

```typescript
git link: https://github.com/testSadab/WebdriverIOMochaTS/tree/import_issue
logs: https://github.com/testSadab/WebdriverIOMochaTS/blob/import_issue/log.txt
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by testSadab** [comment] 2023-01-05 14:44
video link: https://youtu.be/2dmS35iZDVQ
time stamp: 0:40 to 2:50

**Comment by Jmcosel** [comment] 2023-01-11 20:59
The way you're resolving your ESM code is not correct. Make the following changes:
- In `tsconfig.json`, change `module: "ESNext"` to `target: "ESNext"`
- In `package.json`, remove `type: "module"`
- Wherever you import `page.js`, change it to just import `page`, as it's a `.ts` file.

This made your code work for me.

**Comment by testSadab** [comment] 2023-01-11 23:22
Thank you @Jmcosel  for the solution, i was using default tsconfig and package.json generated as part of initial setup. Solution provided worked for me and it will be good to have the same changes implemented in config so that we don't need to make this change manually. Thank you again for the guidance @Jmcosel

**Comment by christian-bromann** [comment] 2023-01-12 08:56
@testSadab which initial setup? If I run `wdio init ./` with TypeScript selected I get tests passing.

**Comment by testSadab** [comment] 2023-01-12 12:21
@christian-bromann  tests are passing as import statement has .js extension for page but in actual file extension are .ts

For e.g. have a look at import statement of  (line 3) https://github.com/testSadab/WebdriverIOMochaTS/blob/import_issue/test/pageobjects/login.page.ts and the actual file

if you keep your import as --> import Page from './page'; we get error and test doesn't run. You can also have a look at the video where i have explained the issue.

**Comment by Jmcosel** [comment] 2023-01-12 21:25
@christian-bromann He's correct, I just tried it myself and ended up with the following stacktrace:

```
SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module.m._compile (/Users/jcosel/Desktop/init/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/jcosel/Desktop/init/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
```

I did exactly these steps:
1. Ran `npx wdio init ./`, entered setup wizard
2. Said "yes" to confirm correct project location
3. Chose "local", "on my local machine", Mocha, TypeScript
4. Said "yes" to auto-generating test files, accepted the default location
5. Said "yes" to making page object files, accepted the default location
6. Kept "spec" reporter, skipped plugins, changed service from "chromedriver" to "selenium-standalone"
7. Kept the base url the default, and asked the setup wizard to run `npm install` for me
8. After the wizard completes, went into the project directory made at `./init` and ran `npx wdio run wdio.conf.ts`

**Comment by christian-bromann** [comment] 2023-01-15 10:38
@Jmcosel thanks for confirming, mind raising a PR with a fix to the template?

**Comment by Jmcosel** [comment] 2023-01-16 18:02
@christian-bromann Done, this was my first time doing this for the project so hopefully it looks correct and it requires your approval to run the workflow.

**Comment by christian-bromann** [comment] 2023-01-17 19:19
Thanks for raising the PR. Merged it and will release with the next version.

**Comment by testSadab** [comment] 2023-01-18 22:28
@Jmcosel did we miss to remove `type: "module"` from `package.json` !
If we leave same in package.json i still get error.

**Comment by Jmcosel** [comment] 2023-01-18 22:39
Nevermind, I think I see what happened - you triggered a different scenario with the config wizard than I did.

Just to confirm, can you give me the exact steps as to what you did to make your project? Did you use a pre-existing directory and add in WDIO packages? What command did you call to start the config wizard?

**Comment by christian-bromann** [comment] 2023-01-18 22:41
@Jmcosel gotcha, this is not released yet so please feel free to raise another PR.

**Comment by testSadab** [comment] 2023-01-18 22:52
@Jmcosel created from scratch as part youtube tutorial playlist: https://www.youtube.com/playlist?list=PLGk7ftfMz7jbF-vCLxaE0-zrW_gj6V9YG

I just followed https://webdriver.io/docs/gettingstarted

Command: `npm init wdio ./path/to/new/project`

Where should your tests be launched? => `local`
Where is your automation backend located? (Use arrow keys) => `On my local machine`
Which framework do you want to use? (Use arrow keys) => `Mocha`
Do you want to use a compiler? => `TypeScript`
Do you want WebdriverIO to autogenerate some test files? => `Yes`
Where should these files be located?  `Suggested path`
Do you want to use page objects => `Y`
Where are your page objects located? => `Suggested path`
 Which reporter do you want to use? => `spec`
Do you want to add a plugin to your test setup?  => `None`
Do you want to add a service to your test setup? => `chromedriver`
What is the base url? => `http://localhost`
Do you want me to run `npm install` => `Y`

**Comment by Jmcosel** [comment] 2023-01-18 23:00
@testSadab Perfect, thank you. There's a whole bunch of different conditionals/scenarios I'm noticing depending on if the project is set up or not, and how the command is called - I've had like three different things happen now with the configuration wizard that I didn't realize could happen now that I've looked into it more. I'll make sure I cover them all when I get a chance to fix it.

**Comment by Jmcosel** [comment] 2023-01-18 23:56
Okay, I went over this and I have a better understanding of what's going on. I've learned more about how ESM resolution occurs with TypeScript; I should have [read over this article](https://www.typescriptlang.org/docs/handbook/esm-node.html#type-in-packagejson-and-new-extensions) first. Me taking out `type: module` from `package.json` and `module: "ESNext"` from `tsconfig.json` was me basically letting Node.js resolve as CJS, which is obviously wrong.  However, [the original error](https://github.com/testSadab/WebdriverIOMochaTS/blob/import_issue/log.txt) actually originates from the way we're generating the imports in the sample `example.e2e.ts` file. This is incorrect in combination with ESM, as you _must_ specify the `.js` at the end, so I'll try to get that fixed.

Additionally, I noticed that you can run `wdio config` if you have `@wdio/cli` globally installed. This differs significantly to the other entry paths (`npm init wdio ./` and `npx wdio ./`) in that it does _not_ pre-make a `package.json`, so you go down a path where the config wizard will do it. As a result, you actually get the option to pick between which module system you want, CJS or ESM. I think the intention of only letting this path do it was not to set this for an existing project in case we break it. But since we have scenarios where we technically making the project "exist" before the config wizard runs, the config wizard is written in such a way where we're not getting a chance to ask this question and do something about it. CJS is assumed to be the answer for regular JS projects, and ESM is assumed to be the answer for TS projects (and this is the part I erroneously took out from `tsconfig.json` originally). So we'll also want to try to figure out if this property is not yet set so we can ask the question for these paths as well.

@christian-bromann One question for you: The command the OP reports, the one on the documentation (`npm init wdio ./`), is actually using `create-wdio` to generate a `package.json` _before_ the config wizard from `@wdio/cli` is even installed. And it looks like [it has hardcoded](https://github.com/webdriverio/create-wdio/blob/main/src/index.ts#L73) `type: module` into its template for whatever reason, without considering CJS vs ESM. I assume we want to remove that and let `@wdio/cli` make a determination about whether to add in that property. My actual question is, since this now goes cross-project, do you want me to raise a separate issue there for the PR needed, or link it back to this ticket?

**Comment by christian-bromann** [comment] 2023-01-19 00:39
> I assume we want to remove that and let `@wdio/cli` make a determination about whether to add in that property.

I believe my initial intention here was: all new projects should be from type `module` because that is where the ecosystem is heading. Not sure if adding an option whether to use CJS or ESM is a good approach, because afaik folks that pick CJS will later have to migrate to ESM anyway. What do you think?

**Comment by Jmcosel** [comment] 2023-01-19 17:16
@christian-bromann Well in that case, we'd be better off removing the ask for what module system to set and just force it to module. If we want to do that, then we'd want to add in something to set that when the entry path is `npx wdio ./`.

Personally I think CJS is going to stick around for a few more years at least as many libraries have yet to switch over and there's still a lot of backwards compatibility built in for it, but it probably doesn't hurt to force folks to start out using ESM if it's a brand new project we're making for them. I'll take out the choice between CJS/ESM in the `npm init wdio ./` entrypoint to ensure that. We do have to still check if it's CJS/ESM in case they made the `package.json` themself without the property or with `module: commonjs` so we generate the sample files correctly.

**Comment by christian-bromann** [comment] 2023-01-20 07:09
@

**Comment by vparlah** [comment] 2023-01-20 11:35
@christian-bromann 
It feels like you have missed removing that fix from the release notes

https://github.com/webdriverio/webdriverio/releases/tag/v8.2.0

**wdio-cli**
https://github.com/webdriverio/webdriverio/pull/9615 Remove 'module: ESNext' from config wizard's tsconfig.json template ([@Jmcosel](https://github.com/Jmcosel))

**Comment by christian-bromann** [comment] 2023-01-20 16:40
Thanks, removed the entry.

**Comment by christian-bromann** [comment] 2023-01-20 16:59
fyi: I just tested the wizard creating new projects for all 3 frameworks and the only TS issue I can see is that the `describe` method in Jasmine is not detected. So I am not really sure how to reproduce this. Can someone create a repository with their new project?

**Comment by vparlah** [comment] 2023-01-20 22:51
@christian-bromann I guess the main “problem”(confusion) is that you need to specify “.js” when importing “.ts” files with ESM. (VSCode by default does not import with extension)

But per @Jmcosel https://github.com/webdriverio/webdriverio/issues/9539#issuecomment-1396247694
it is the way it works.

PS: I have spent last few days trying to understand “why I need add that .js to imports ” until I found this conversation :) 
Might worth to add few notes into the doc.

**Comment by christian-bromann** [comment] 2023-01-20 23:22
Yeah, with ESM you will have to always add an extension. I wonder what would be the best place to document this.

**Comment by Jmcosel** [comment] 2023-01-20 23:35
@christian-bromann Sorry I got busy with my day job, so haven't worked on it yet. The only thing that commit I made did was make the auto-generated files when choosing TS work by making it use CJS. So in a way it was better than it not working at all, but I'll see if I can grab a moment to make the proper fix soon.

**Comment by vparlah** [comment] 2023-01-21 03:43
@christian-bromann I would add a new section CommonJS vs EMS under DOCS -> Configuration.

And put all details there with explanation why EMS is recommended way and the nuances like import/export and configuration(for TypeScript and JavaScript). 
Also I would add some comparison with old CommonJS setup.

This is not the first time I hear the confusion from people who started using the 8 version so it might help.

**Comment by christian-bromann** [comment] 2023-01-23 17:51
@vparlah I agree that there have been a lot of confusion around this topic. However it is not the job for WebdriverIO to document and provide information around it given there is plenty of that on the internet already. If someone likes to create a tutorial how to transform a WDIO project from CJS to ESM I am happy to integrate this into our docs.

> Also I would add some comparison with old CommonJS setup and maybe some tips how to setup vscode, webstorm to automatically import with extension.

Feel free to create PRs to our docs with such content. This would be awesome!

**Comment by DirkoOdendaal** [comment] 2023-02-02 15:49
@christian-bromann we are also running into some similar issues when upgrading from v7 to v8 in a CJS project.
Our problem there is that we have a massive monorepo and converting that to EMS would take some time.

So what I'm actually want to ask is if you can only use v8 in a EMS project?

So not on a new project, but an existing project. We run into these issues while trying to use the @wdio/cli Launcher to run our tests. If that's another bug to report, etc, then I'm happy to create it and look into it, but just first need to confirm that I have the right understanding.

**Comment by christian-bromann** [comment] 2023-02-02 17:57
> So what I'm actually want to ask is if you can only use v8 in a EMS project?

Yes, you can use WebdriverIO v8 in a CJS context. Note that your code base can be CJS but your WebdriverIO files are in ESM. There are certainly some interoperability issues we are working on fixing.

> If that's another bug to report, etc, then I'm happy to create it and look into it, but just first need to confirm that I have the right understanding.

Yes using the `@wdio/cli` can only be done in ESM, please raise an issue that asks to make the launcher compatible to CJS context.

**Comment by simonwilson1985** [comment] 2023-02-07 09:06
Hi,

I'm seeing something similar to this where if I create a new project and run npm init wdio . as stated then the first thing I see is 
```
A project named "webdriverio-tests" was detected at "C:\test", correct? (Y/n)
```
It appears that choosing either y/n does nothing and it fetches some of the package.json file details from older webdriverio projects I have on my PC (windows).

Going through the rest of the wizard *looks* ok 
```
Installing wdio packages:
- @wdio/local-runner@latest
- @wdio/mocha-framework@latest
- @wdio/spec-reporter@latest
- wdio-chromedriver-service
- ts-node
- typescript
- chromedriver
```
but then at the end it updates the wdio script in the package.json from 
```
"scripts": {
        "wdio": "wdio run wdio.conf.ts"
    }
```
to
```
"scripts": {
        "wdio": "wdio run wdio.conf.js"
    }
```

and my final package looks like this:

```
{
    "name": "webdriverio-tests",
    "version": "0.1.0",
    "description": "",
    "private": true,
    "keywords": [],
    "author": "",
    "license": "ISC",
    "devDependencies": {
        "@wdio/cli": "^8.3.3",
        "@wdio/local-runner": "^8.3.3",
        "@wdio/mocha-framework": "^8.3.0",
        "@wdio/spec-reporter": "^8.3.0",
        "chromedriver": "^109.0.0",
        "ts-node": "^10.9.1",
        "typescript": "^4.9.5",
        "wdio-chromedriver-service": "^8.0.1"
    },
    "scripts": {
        "wdio": "wdio run wdio.conf.js"
    }
}
```

Running it on a colleagues /clean/ machine works as expected.

If I update it back to .ts and run npx wdio run ./wdio.conf.ts it falls over 
```
ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///C:/auto/wdio.conf.ts: Unexpected token 'export'
```
(updating the tsconfig to use commonJS fixes this)

**Comment by Jmcosel** [comment] 2023-02-14 00:46
@christian-bromann I've finally gotten a chance to make progress on this, but I'm having trouble actually getting to test it within the Gitpod I made for myself (my first time using Gitpod)... but just wanted to let all the people watching this that I should have something soon, gonna just have to try setting up this project locally and test it that way... otherwise I'll schedule an office hours slot for further assistance.

**Closed** 2023-03-06 18:15 UTC
Labels: Bug 🐛, help wanted, good first pick
