### ISSUE TITLE
Exclude tests per browser not working

### ISSUE THREAD

**Issue by pi4r0n** [webdriverio/webdriverio#1067] opened 2016-02-02 09:08 UTC
I am running my server in grid mode (selenium-server-standalone-2.49.1) and notice that exclude test per browser is not handled at all :( Please note this applies to al browsers. Below I have attached Selenium log and WDIO config 

`17:16:25.585 INFO [1] org.openqa.grid.selenium.GridLauncher - Launching a Selenium Grid node
17:16:28.349 INFO [1] org.openqa.selenium.server.SeleniumServer - Writing debug logs to logs/mac_node_config.log
17:16:28.349 INFO [1] org.openqa.selenium.server.SeleniumServer - Java: Oracle Corporation 25.65-b01
17:16:28.349 INFO [1] org.openqa.selenium.server.SeleniumServer - OS: Mac OS X 10.11.3 x86_64
17:16:28.400 INFO [1] org.openqa.selenium.server.SeleniumServer - v2.49.1, with Core v2.49.1. Built from revision 7203e46
17:16:28.591 INFO [1] org.openqa.selenium.remote.server.DefaultDriverSessions - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform MAC
17:16:28.591 INFO [1] org.openqa.selenium.remote.server.DefaultDriverSessions - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform MAC
17:16:28.592 INFO [1] org.openqa.selenium.remote.server.DefaultDriverProvider - Driver class not found: com.opera.core.systems.OperaDriver
17:16:28.592 INFO [1] org.openqa.selenium.remote.server.DefaultDriverFactory - Driver provider com.opera.core.systems.OperaDriver is not registered
17:16:28.931 INFO [1] org.openqa.jetty.http.HttpServer - Version Jetty/5.1.x
17:16:28.946 INFO [1] org.openqa.jetty.util.Container - Started HttpContext[/selenium-server,/selenium-server]
17:16:29.009 INFO [1] org.openqa.jetty.util.Container - Started org.openqa.jetty.jetty.servlet.ServletHandler@dd3b207
17:16:29.009 INFO [1] org.openqa.jetty.util.Container - Started HttpContext[/wd,/wd]
17:16:29.009 INFO [1] org.openqa.jetty.util.Container - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
17:16:29.009 INFO [1] org.openqa.jetty.util.Container - Started HttpContext[/,/]
17:16:29.028 INFO [1] org.openqa.jetty.http.SocketListener - Started SocketListener on 0.0.0.0:4477
17:16:29.028 INFO [1] org.openqa.jetty.util.Container - Started org.openqa.jetty.jetty.Server@1877ab81
17:16:29.028 INFO [1] org.openqa.grid.selenium.GridLauncher - Selenium Grid node is up and ready to register to the hub
17:16:29.222 INFO [16] org.openqa.grid.internal.utils.SelfRegisteringRemote - Starting auto registration thread. Will try to register every 5000 ms.
17:16:29.222 INFO [16] org.openqa.grid.internal.utils.SelfRegisteringRemote - Registering the node to the hub: http://10.1.12.19:4444/grid/register
17:16:29.284 INFO [16] org.openqa.grid.internal.utils.SelfRegisteringRemote - The node is registered to the hub and ready to use
17:16:54.914 INFO [13] org.openqa.selenium.remote.server.DriverServlet - Executing: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@69531aa9, browserName=safari, javascriptEnabled=true, exclude=[Automation_Tests/suite_Logon/tst_LH_L_0006.js, Automation_Tests/suite_Logon/tst_LH_L_0007.js, Automation_Tests/suite_Logon/tst_LH_L_0008.js, Automation_Tests/suite_Logon/tst_LH_L_0009.js], handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=3.4.0, url=http://webdriver.io}}]])
17:16:55.026 INFO [21] org.openqa.selenium.remote.server.DefaultDriverProvider - Creating a new session for Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@69531aa9, browserName=safari, javascriptEnabled=true, exclude=[Automation_Tests/suite_Logon/tst_LH_L_0006.js, Automation_Tests/suite_Logon/tst_LH_L_0007.js, Automation_Tests/suite_Logon/tst_LH_L_0008.js, Automation_Tests/suite_Logon/tst_LH_L_0009.js], handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=3.4.0, url=http://webdriver.io}}]`

**WDIO CONFIG**

> 

    exports.config = {
    specs: [
        'Automation_Tests/suite_Logon/**',
    ],

    exclude: [
    ],

    capabilities: [
        {
            browserName: 'safari',
            exclude: [
                'Automation_Tests/suite_Logon/tst_LH_L_0006.js',
                'Automation_Tests/suite_Logon/tst_LH_L_0007.js',
                'Automation_Tests/suite_Logon/tst_LH_L_0008.js',
                'Automation_Tests/suite_Logon/tst_LH_L_0009.js'
            ]
        }
    ],

    logLevel: 'silent',
    
    coloredLogs: true,
    
    baseUrl: 'https://127.0.0.1',
    
    waitforTimeout: 1000,
    
    framework: 'mocha',
    
    reporter: 'spec',
    
    reporterOptions: {
            outputDir: './'
    },

    mochaOpts: {
        timeout: 60000,
    },

    onPrepare: function() {
        console.log('Automation started.');
    },

    before: function() {
        // do something
    },

    after: function() {
        // do something
    },

    onComplete: function() {
        console.log('Automation finished.');
    }
};

**Comment by christian-bromann** [comment] 2016-02-02 09:09
could you post your formatted wdio config?

**Comment by pi4r0n** [comment] 2016-02-02 09:31
Job done @christian-bromann

**Comment by jonyet** [comment] 2016-02-02 15:57
can confirm, i have the same issues. it appears that exclude is just not even being seen in the capabilities obj array. when you have exclude defined globally in the wdio config and point to non-existing files, you get a notification in your console log at the beginning of the testing - 'pattern ./test/one.js did not match any file' - no such log appears when you define your browser specific exclusions.

**Comment by christian-bromann** [comment] 2016-03-24 14:40
Could you update to v4 and try again?

**Comment by pi4r0n** [comment] 2016-03-29 13:18
Chris I have just realized that I am using gulp-webdriver (ver 1.0.1) to trigger my scripts. Would it be possible to port changes to https://github.com/webdriverio/gulp-webdriver

I can then test it ;)

**Comment by christian-bromann** [comment] 2016-04-06 23:19
> Would it be possible to port changes

What changes?

**Comment by pi4r0n** [comment] 2016-04-11 13:56
Sorry Chris I got confused earlier. **Please ignore my above comment:**( 

I have just tried to upgrade to v4, unfortunately I have issues with Mocha. **Couldn't initialise framework "wdio-mocha-framework".** therefore I am unable to confirm, maybe jonyet can confirm ?

**Comment by christian-bromann** [comment] 2016-04-11 14:03
@pi4r0n make sure you have installed `wdio-mocha-framework` locally if you use webdriverio locally and vise versa. Can you post the whole stack trace of that error message? Maybe I can tell you what's wrong.

**Comment by SamsonNelson** [comment] 2016-04-15 17:45
Im assuming this is a similar issue as @pi4r0n 

ERROR: Couldn't load "wdio-mocha-framework" framework. You need to install it with `$ npm install wdio-mocha-framework`!
Error: Cannot find module 'wdio-mocha-framework'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Runner.initialiseFramework (/Users/snelson/gravy/node_modules/webdriverio/build/lib/runner.js:323:24)
    at Runner.run$ (/Users/snelson/gravy/node_modules/webdriverio/build/lib/runner.js:59:47)
    at tryCatch (/Users/snelson/gravy/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:72:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/snelson/gravy/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:334:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/snelson/gravy/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:105:21)
    at tryCatch (/Users/snelson/gravy/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:72:40)
chrome.42_0.windows7
    at Runner.initialiseFramework (/Users/snelson/gravy/node_modules/webdriverio/build/lib/runner.js:329:23)
    at Runner.run$ (/Users/snelson/gravy/node_modules/webdriverio/build/lib/runner.js:59:47)
    at tryCatch (/Users/snelson/gravy/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:72:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/snelson/gravy/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:334:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/snelson/gravy/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:105:21)
    at tryCatch (/Users/snelson/gravy/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:72:40)
    at invoke (/Users/snelson/gravy/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:146:20)
    at /Users/snelson/gravy/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:191:11
    at new Promise (/Users/snelson/gravy/node_modules/webdriverio/node_modules/core-js/library/modules/es6.promise.js:197:7)
    at callInvokeWithMethodAndArg (/Users/snelson/gravy/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:190:16)

>> 
Warning: Task "webdriver:test" failed. Use --force to continue.

**Comment by SamsonNelson** [comment] 2016-04-15 17:53
Just like @christian-bromann said make sure to Install it locally first 
$ npm install wdio-mocha-framework -g

Then comes changing all of your test to be compatible with v4

**Comment by mcaruso85** [comment] 2016-04-15 19:48
This problem can be solved in the following way. Also specs per browser is not working due to the same defect. So you can find below how to solve both problems:

**# FILE : **
\webdriverio\lib\utils\ConfigParser.js

_**CURRENT:**_

ConfigParser.prototype.getSpecs = function(capSpecs, capExclude) {
    var specs = this.getFilePaths(this._config.specs),
        exclude = this.getFilePaths(this._config.exclude);

    if(Array.isArray(capSpecs)) {
        specs = specs.concat(capSpecs);
    }
    if(Array.isArray(capExclude)) {
        exclude = exclude.concat(capExclude);
    }
    return specs.filter(function(spec) {
        return exclude.indexOf(spec) < 0;
    });
};

_**`FIX:`**_

ConfigParser.prototype.getSpecs = function(capSpecs, capExclude) {
    var specs = this.getFilePaths(this._config.specs),
        exclude = this.getFilePaths(this._config.exclude);

    if(Array.isArray(capSpecs)) {
        //FIX
**        specs = specs.concat(this.getFilePaths(capSpecs));**
    }
    if(Array.isArray(capExclude)) {
**        //FIX 
        exclude = exclude.concat(this.getFilePaths(capExclude));**
    }
    return specs.filter(function(spec) {
        return exclude.indexOf(spec) < 0;
    });
};

**Comment by christian-bromann** [comment] 2016-04-15 20:10
@mcaruso85 feel free to create a PR with tests and all that 😉

**Comment by pi4r0n** [comment] 2016-04-20 11:10
@christian-bromann  I can confirm that exclude tests per browser working fine in latest v4

**Comment by christian-bromann** [comment] 2016-04-20 16:27
@pi4r0n thanks for confirming that. Closing then!

**Closed by christian-bromann** 2016-04-20 16:27 UTC
Labels: Not Reproducible, Question

**Comment by mcaruso85** [comment] 2016-04-20 17:03
Hi, 

The issue is only present in the version v3.4.1.
