### ISSUE TITLE
Multiremote config errors due to capabilities values - Illegal key values seen in w3c capabilities: [hostname, path, port, protocol]

### ISSUE THREAD

**Issue by amandaflagg** [webdriverio/webdriverio#6652] opened 2021-04-02 20:33 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.3.0
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.18.3
 - **NPM version:** 6.14.6
 - **Browser name and version:** Chrome 89.0.4389.114
 - **Platform name and version:** Mac OS Catalina 10.15.7
 - **Additional wdio packages used (if applicable):** 
 - @wdio/spec reporter, @wdio/selenium-standalone service, @wdio/mocha-framework, @wdio/sync, @wdio/local-runner

**Config of WebdriverIO**
```exports.config = {
    runner: 'local',
    specs: [
        './webdriver/tests/**.ts'
    ],
    exclude: [
        // 'path/to/excluded/files'
    ],
    autoCompileOpts: {
        autoCompile: true,
        // see https://github.com/TypeStrong/ts-node#cli-and-programmatic-options
        // for all available options
        tsNodeOpts: {
            transpileOnly: true,
            project: './webdriver/tsconfig.json'
        },
        // tsconfig-paths is only used if "tsConfigPathsOpts" are provided, if you
        // do please make sure "tsconfig-paths" is installed as dependency
        tsConfigPathsOpts: {
            baseUrl: './'
        }
    },
    maxInstances: 10,
    automationProtocol: 'webdriver',
    path: '/wd/hub',
    capabilities: 
    {
        chromeBrowser: {
            capabilities: {
                browserName: 'chrome'
            }
        },
        firefoxBrowser: {
            capabilities: {
                browserName: 'firefox'
            }
        }
    },
    logLevel: 'info',
    bail: 0,
    baseUrl: 'http://www.google.com/',
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: [
        ['selenium-standalone', { drivers: { firefox: '0.28.0', chrome: true, chromiumedge: 'latest' } }]
    ],
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    }
}
```

**Describe the bug**
When configured for multiremote and selenium-standalone, running the tests throws the error `ERROR webdriver: unknown error: Illegal key values seen in w3c capabilities: [hostname, path, port, protocol]`.  The session data is logged as follows:
```
[0-0] 2021-04-02T20:11:06.899Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2021-04-02T20:11:06.900Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2021-04-02T20:11:06.900Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      browserName: 'chrome',
      protocol: 'http',
      hostname: 'localhost',
      port: 4444,
      path: '/wd/hub'
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'chrome',
    protocol: 'http',
    hostname: 'localhost',
    port: 4444,
    path: '/wd/hub'
  }
}
```

If I run the tests without the multiremote configuration, they are successful. The session data is as follows:
```
[1-0] 2021-04-02T20:19:40.685Z INFO webdriver: Initiate new session using the WebDriver protocol
[1-0] 2021-04-02T20:19:40.686Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
[0-0] 2021-04-02T20:19:40.687Z INFO webdriver: Initiate new session using the WebDriver protocol
[1-0] 2021-04-02T20:19:40.686Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
}
[0-0] 2021-04-02T20:19:40.688Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
[0-0] 2021-04-02T20:19:40.688Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      browserName: 'firefox',
      acceptInsecureCerts: true,
      'moz:firefoxOptions': [Object]
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'firefox',
    acceptInsecureCerts: true,
    'moz:firefoxOptions': { args: [Array] }
  }
}
```

**To Reproduce**
**Update (04/08):**
pull the following and run `npx wdio run wdio.conf.js` from the `e2e-tests` directory:
https://github.com/amandaflagg/multiremote-bug

Original information:

1. Set the capabilities in wdio.conf.js to: 
```
capabilities:
{
        chromeBrowser: {
            capabilities: {
                browserName: 'chrome'
            }
        },
        firefoxBrowser: {
            capabilities: {
                browserName: 'firefox'
            }
        }
    },
```
2. Ensure services includes selenium-standalone:
```
services: [
        ['selenium-standalone', { drivers: { firefox: '0.28.0', chrome: true, chromiumedge: 'latest' } }]
    ],
```
3. Start test run

**Expected behavior**
Setting capabilities to enable multiremote in wdio.conf.js should run just as a non-multiremote config does. I'm unsure where the values are coming from that cause an error in capabilities when running multiremote.

**Log**
https://gist.github.com/amandaflagg/60f6326b5347f6d1e77b58cdc550a5dd

**Comment by erwinheitzman** [comment] 2021-04-04 19:36
Cannot reproduce using the example provided. I suggest generating a clean project using the CLI and to try using multi remote as described here https://webdriver.io/docs/multiremote/

**Comment by Amrkamel1** [comment] 2021-04-05 04:37
I think this one migh be related to similar issue with 
https://github.com/webdriverio/webdriverio/issues/6445

**Comment by matthew-johnston** [comment] 2021-04-05 06:24
I have the exact same issue you're seeing. I found a temporary workaround/hack you can use. 
Try setting an empty `sauce:options` object in your capabilities. Selenium standalone treats it as a cloud capability and doesn't run this line `Object.assign(c, DEFAULT_CONNECTION, { ...c })`. Very hacky, but it might unblock you until this is fixed.

`            if (!isCloudCapability(c) && hasCapsWithSupportedBrowser(c)) {
                Object.assign(c, DEFAULT_CONNECTION, { ...c })
            }`

https://github.com/webdriverio/webdriverio/blob/9d2220e89144b0ca69232737957ad5fc32ca1300/packages/wdio-selenium-standalone-service/src/launcher.ts#L87

https://github.com/webdriverio/webdriverio/blob/9d2220e89144b0ca69232737957ad5fc32ca1300/packages/wdio-config/src/utils.ts#L34

**Comment by christian-bromann** [comment] 2021-04-05 10:07
This should have been fixed with the latest version. @amandaflagg can you please provide a reproducible example?

**Comment by amandaflagg** [comment] 2021-04-06 21:26
> I have the exact same issue you're seeing. I found a temporary workaround/hack you can use.
> Try setting an empty `sauce:options` object in your capabilities. Selenium standalone treats it as a cloud capability and doesn't run this line `Object.assign(c, DEFAULT_CONNECTION, { ...c })`. Very hacky, but it might unblock you until this is fixed.

this did fix my issue. thank you @matthew-johnston! 

@christian-bromann i'll work on pulling out a copy of this onto github to provide a reproducible example in the next couple days. i had just freshly installed wdio in this project last week in order to dive on using multiremote for testing, so i do have 7.3.0 installed.

**Comment by amandaflagg** [comment] 2021-04-09 00:30
@christian-bromann i pushed a reproducible example here: https://github.com/amandaflagg/multiremote-bug

from the `e2e-tests` directory, run `npx wdio run wdio.conf.js` to reproduce the error.

in wdio.conf.js i have commented out the code suggested above to bypass this bug. if you uncomment the `sauce:options` objects in capabilities, the bug should no longer be reproducible.

**Comment by christian-bromann** [comment] 2021-04-09 07:41
Thanks for providing an reproducible example. I Was able to spot the problem and provide a fix. Let's continue convo in the PR.

**Closed by christian-bromann** 2021-04-09 07:41 UTC
Labels: Reproducible Example Missing
