### ISSUE TITLE
Calendar not visible when there is no physical monitor opened 

### ISSUE THREAD

**Issue by andreas-smith1995** [webdriverio/webdriverio#1228] opened 2016-04-05 14:25 UTC
## The problem

Task to perform: Click a field to open a calendar, and then click a date on it.
Run on:  Liunx VM of Amazon Web Service
Coding process: Click the field > check if the calender open > if open, click on a date, if not open, click the field again until it is open.

Problem: if there is on physical monitor to access the VM (i.e. from my local machine to access the VM and watch the test), the calendar will not visible until I access the VM from local. 
For example:
1. code setting:  set the maximum wait time is 5 minutes - if the calendar not visible in 5 min, then the test will be failed. 
2. Run test: Access the VM from my local, the tests were all successful
                   Not access the VM, the tests were failed - calendar not visible
3. Run test: Not access the VM, after 4 minutes, the log shows the calendar not visible. Then access the VM from the local. The calendar was displayed and the test passed.
 
## Environment

* WebdriverIO version:
* Node.js version:
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous or asnychronous tests:
* Additional wdio packages used (if applicable):

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

 _getDatePickerDisplayed(){
        let self = this;
        
        return this._waitUntil().then(function(){
            return self.browser.pause(5000).click('input.rui-date-picker-text');
        }).then(function(){
            return self.browser.pause(1000).isExisting('div.rui-date-picker--is-open')
        }).then(function(result){

            if(result===true){
                return Promise.resolve();
            } else {
                return self._getDatePickerDisplayed()
            }
        })
    }

    _waitUntil(){
        let self = this;
        return this.browser.waitForExist(this.selector.openDatePicker).then(function(boo){
            if(boo===true){
                return Promise.resolve();
            } else {
                return self._waitUntil();
            }
        })
    }

**Comment by christian-bromann** [comment] 2016-04-05 16:17
what is the problem here?

**Comment by andreas-smith1995** [comment] 2016-04-05 18:03
seems the calendar was displayed after clicking on the field, but
WebdriverIO not able to detect the calendar.

**Comment by andreas-smith1995** [comment] 2016-04-05 18:07
When I run the test with monitor opened, the test passes every single time.

But if I run the test on a remote virtue machine (without any physical
monitor), then the test would failed. The error message is: Element is not
currently visible.....

**Comment by andreas-smith1995** [comment] 2016-04-05 18:23
For debug,  I wrote an infinite loop trying to find the calendar. and set
the mochaOpts>timeout as 800000.

First, I ran the test on the remote VM, the test kept checking the calendar
and click the field for like 6 minutes. Then I access the VM from my local,
I could see the calendar displayed on the page. Once I access the VM, the
calendar got clicked, and test passed.

**Comment by christian-bromann** [comment] 2016-04-05 18:55
I am not sure how this is in any way related to WebdriverIO? I can't reproduce this issue and I also have no idea how to help you here as it seems to be pretty much environment depending. Sorry, closing.

**Closed by christian-bromann** 2016-04-05 18:55 UTC

**Comment by andreas-smith1995** [comment] 2016-04-05 20:05
Thanks Christian.

You are right, there are a lot of environment dependencies.
