### ISSUE TITLE
[🐛 Bug]: Unable to select visible text using selectByVisibleText

### ISSUE THREAD

**Issue by anilreddy** [webdriverio/webdriverio#8148] opened 2022-03-23 15:40 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### What happened?

Unable to select visible text using selectByVisibleText. I have a dropdown which has numbers in the list and i got following out put in the console instead of selecting the value.

`[0-0] 2022-03-23T15:31:11.975Z INFO webdriver: DATA {
[0-0]   using: 'xpath',
[0-0]   value: './option[. = "116"]|./option[normalize-space(text()) = "116"]|./optgroup/option[. = "116"]|./optgroup/op
tion[normalize-space(text()) = "116"]'
[0-0] }`

### What is your expected behavior?

value 116 should be selected from the dropdown.

### How to reproduce the bug.

```js
public get selectWeight () {
        return $('select[ng-model="RWCRData.wgt_in_lbs"]');
}

await this.selectWeight.selectByVisibleText('116');
```

### Relevant log output

```typescript
`[0-0] 2022-03-23T15:31:11.975Z INFO webdriver: DATA {
[0-0]   using: 'xpath',
[0-0]   value: './option[. = "116"]|./option[normalize-space(text()) = "116"]|./optgroup/option[. = "116"]|./optgroup/op
tion[normalize-space(text()) = "116"]'
[0-0] }`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

**Comment by christian-bromann** [comment] 2022-03-23 16:12
Can you provide a reproducible example, e.g. a little demo website with test script?

**Comment by christian-bromann** [comment] 2022-03-24 13:54
Thanks for providing the example. The next step is to verify the issue with this example provided. Then look into why the expected behavior doesn't happen. Any contributions are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by mayankshukla94** [comment] 2022-05-06 10:58
@christian-bromann I'll be picking this up!!

**Comment by mayankshukla94** [comment] 2022-05-18 15:43
I tried with the above mentioned code and it is working fine for me. Although I'm getting below info message:

```
using: 'xpath',
[0-0]   value: './option[. = "125"]|./option[normalize-space(text()) = "125"]|./optgroup/option[. = "125"]|./optgroup/option[normalize-space(text()) = "125"]'
[0-0] }
```

But I'm not getting any error message and value is getting selected.

**Comment by anilreddy** [comment] 2022-05-18 16:21
@mayankshukla94 I have tried just now but it is not selecting please check again carefully.

**Comment by mayankshukla94** [comment] 2022-05-18 16:22
Could you please share the capabilities and WebdriverIO version that you are using?

**Comment by mayankshukla94** [comment] 2022-05-24 06:54
@christian-bromann Can we close this issue now?

**Comment by anilreddy** [comment] 2022-05-24 06:58
@mayankshukla94 still issue is there

**Comment by christian-bromann** [comment] 2022-08-23 09:51
Closing due to inactivity. It would be helpful to get a minimal reproducible example otherwise it would be hard for anyone to understand what is going on.

Thank you @mayankshukla94 for investigating this.

**Closed by christian-bromann** 2022-08-23 09:51 UTC
Labels: Bug 🐛, Needs Investigation
