### ISSUE TITLE
[🐛 Bug]: Request failed with status 500 if using scrollIntoView()

### ISSUE THREAD

**Issue by Lara2409** [webdriverio/webdriverio#11272] opened 2023-09-29 15:25 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.16.16

### Node.js Version

20.5.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
      maxInstances: 1,
      browserName: 'chrome',
      'goog:chromeOptions': {
        args: process.env.CI
          ? ['--headless', '--disable-gpu', '--no-sandbox'] : ['--start-maximized'],
      },
    },
```

### What happened?

When I use method scrollIntoView(), I receive an error message `ERROR webdriver: Request failed with status 500 due to move target out of bounds: move target out of bounds` in console, although the method works as expected.

### What is your expected behavior?

Console without errors.

### How to reproduce the bug.

https://github.com/Lara2409/e2e - code example

### Relevant log output

```typescript
[0-0] 2023-09-29T15:02:06.175Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: move target out of bounds
[0-0]   (Session info: chrome=117.0.5938.92)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment] 2023-09-29 20:22
I've touched the scrollIntoView not to long ago so I'll try to reproduce this when I can

**Comment by christian-bromann** [comment] 2023-09-30 00:39
This is very likely connected to the application under test and often means  that an element you want to interact with moved out of viewport of the browser.

@Lara2409 is there any chance you can provide a reproducible example?

**Comment by Lara2409** [comment] 2023-09-30 06:28
@christian-bromann I provided reproducible example in `How to reproduce the bug section` (link to github code). You can see this log if you run test via run script.

**Comment by erwinheitzman** [comment] 2023-10-01 19:34
Thank you for reporting, this was a webdriver error that was caused by retrieving the element rect during the execution of the scrollIntoView command. Expanding the try/catch to include this, resolves this issue.

Currently waiting for the tests to pass and will merge when green: https://github.com/webdriverio/webdriverio/pull/11276

**Comment by Lara2409** [comment] 2023-10-02 06:52
Hi @erwinheitzman. Thanks for your quick response. I updated wdio version to 8.16.18 (with your fix), but unfortunately I still receive this error. `ERROR webdriver: Request failed with status 500 due to move target out of bounds: move target out of bounds` ( #https://github.com/Lara2409/e2e). Maybe do you have an idea why?

**Comment by erwinheitzman** [comment] 2023-10-02 07:26
@Lara2409 you are right, not sure why but the fix does not seem to be in the release for some reason. I'll do some investigation

**Comment by erwinheitzman** [comment] 2023-10-02 07:42
@Lara2409 I did some investigation and the code is in there but in my case it did not pull the latest webdriverio version for some strange reason, even though the package tells it to. I suggest to run `npm i webdriverio@latest` and it will pull the new change 👍

**Comment by erwinheitzman** [comment] 2023-10-02 07:44
And after testing with the latest I do still see the error as well, so I'll dive into that. Apologies, not sure why it's showing still after testing last night.

**Comment by erwinheitzman** [comment] 2023-10-02 08:08
@christian-bromann I tried catching this error in different layers but could not prevent it. Now the scroll is done correctly so I don't understand why the error shows up in the first place (scrollIntoView -> action perform -> base.ts -> performActions). Do you know of any way of handling this (if we even can?).

@Lara2409 though you get the error, the test should execute as expected as far as I can tell as webdriver errors er sometimes handled by webdriverio.

**Comment by Lara2409** [comment] 2023-10-02 08:53
@erwinheitzman you're right. The test executes as expected.

**Comment by erwinheitzman** [comment] 2023-10-03 21:16
Not from my side, I'm not sure if we can handle the error so let me say that the error you see it not a error that matters because as you have seen WebdriverIO handles it for you.

WebdriverIO does calls to webdriver and if it fails it handles this correctly. The logs do show all traffic so also any errors. These logs should be used for debugging and not so much for error catching of any kind so I feel like this doesn't have much of a priority to be honest.

**Comment by qaflorent** [comment] 2023-10-04 07:19
So should this log be displayed at debug level instead of Error ?

**Comment by udarrr** [comment] 2023-10-07 13:13
Look like it's not wdio, it's coming from chromedriver related to https://github.com/w3c/webdriver/issues/1635

**Comment by erwinheitzman** [comment] 2023-10-07 13:21
Thanks for sharing but we know @udarrr

**Comment by erwinheitzman** [comment] 2023-10-09 11:27
I am going to close this as the webdriver logs are meant to be used for debugging purposes only and there's no actual issue

**Closed** 2023-10-09 11:28 UTC
Labels: Bug 🐛
