### ISSUE TITLE
Throwing error for correct test script

### ISSUE THREAD

**Issue by Shirish2015** [webdriverio/webdriverio#595] opened 2015-06-30 17:20 UTC
[09:53:16] Using gulpfile ~/projects/reports/Gulpfile.js
[09:53:16] Starting 'selenium'...
[09:53:16] Finished 'selenium' after 3.75 ms
[09:53:16] Using gulpfile ~/projects/reports/Gulpfile.js
[09:53:16] Starting 'functest'...
Looking for testscripts in test/functional/jasmine-specs/ ...
1 valid testscripts found.
[09:53:16] Finished 'functest' after 1.11 ms
Could not find a running Selenium Server on Port 4445. Starting one now.

Running Test Script:testSuiteSpec.js

---------TEST RESULTS---------

A more indepth look at what is going on with Selenium and your tests is being written to the logs directory of this project.
Your last log has been renamed to ./logs/log-file.log.legacy. You can find it in the logs folder. Logs are saved for one run removed.
Ran Test script on chrome. The output was:
	
### Execution Started ### Running Test which opens the Upload Modal with no report selected
below upload model
[TypeError: Cannot read property 'log' of undefined]

my webdriverio tests - 24810 ms
    opens the Upload Modal with no report selected - 24809 ms

Failures:

  1) my webdriverio tests opens the Upload Modal with no report selected
   Message:
     timeout: timed out after 20000 msec waiting for spec to complete
   Stacktrace:
     undefined

Finished in 24.813 seconds
1 test, 2 assertions, 1 failure, 0 skipped

 
-------END TEST RESULTS-------

Ran 1 tests. Please review the console for test results. Preparing to shutdown Selenium now.

Closing Selenium....
Selenium has shut down.

May i know why it is throwing failure even though the script is correct?

**Comment by christian-bromann** [comment] 2015-06-30 17:22
@Shirish2015 what tool are you using here? Haven't seen that kind of logs

**Comment by Shirish2015** [comment] 2015-06-30 17:30
jasmine

**Comment by christian-bromann** [comment] 2015-06-30 18:13
yeah but what node module? According to the logs you are using gulp.

could you provide some code as well?

**Comment by Shirish2015** [comment] 2015-06-30 18:19
I can't reveal the code but I can explain you is it fine.

var Util = require('../../../node_modules/func-kit/test_lib/Util.js'),
    ct   = require('../../../node_modules/func-kit/test_lib/constants.js'),
    _    = require('../../../node_modules/lodash');

**Comment by Shirish2015** [comment] 2015-06-30 18:25
For another testcase When I use even handling it is throwing error. As follows

Failures:

  1) Delete Suite validating class attribue for select all link
   Message:
     timeout: timed out after 5000 msec waiting for spec to complete
   Stacktrace:
     undefined

Finished in 6.084 seconds
1 test, 2 assertions, 1 failure, 0 skipped

With out event handling it is working fine what may be the cause for this factor?Is it wrong with my machine configuration?

**Comment by christian-bromann** [comment] 2015-06-30 18:46
I still can't figure out what test setup you are using? It doesn't seem that it is WebdriverIO. Are you using any 3rd party library that uses WebdriverIO internally?

As far as I can tell from the errors you need to somehow increase the jasmine timeout. Also the error that says: `[TypeError: Cannot read property 'log' of undefined]` could be because you are using this in a wrong scope

**Comment by Shirish2015** [comment] 2015-07-01 20:47
fun-kit is my project name and I am testing first in private branch and I didn't under stand " could be because you are using this in a wrong scope" and thank you for replying me before.

**Comment by christian-bromann** [comment] 2015-07-01 20:50
> I didn't under stand " could be because you are using this in a wrong scope"

the error says `TypeError: Cannot read property 'log' of undefined` so seems that you are calling the `log` command with an undefined object

I will close the issue as it doesn't seem that the problem is related to WebdriverIO. Let me know if you still have questions.

**Closed by christian-bromann** 2015-07-01 20:50 UTC
