### ISSUE TITLE
[🐛 Bug]: wdio-vscode-service fails to download chrome driver for vscode version 1.86.0

### ISSUE THREAD

**Issue by petehale** [webdriverio/webdriverio#12167] opened 2024-02-05 13:53 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

18.18.2

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
        browserName: 'vscode',
        browserVersion: 'stable', // also possible: "insiders" or a specific version e.g. "1.80.0"
        'wdio:vscodeOptions': {
            // points to directory where extension package.json is located
            extensionPath: './',
            // optional VS Code settings
            userSettings: {
                "editor.fontSize": 14
            }
        }
    }],
```

### What happened?

Our wdio tests started failing when trying to download chrome drivers, errors with a 404. We are using vscode 1.85 and later.

As an experiment, I created a new wdio project for vscode using `npm create wdio@latest ./ ` After the project was initialized I ran `npm run wdio` which fails with 
```
SevereServiceError in "onPrepare"
SevereServiceError: 
A service failed in the 'onPrepare' hook
SevereServiceError: Couldn't set up Chromedriver Response code 404 (Not Found)
    at VSCodeServiceLauncher._setupChromedriver (file:///Users/peter.hale/git/wdio-foo/node_modules/wdio-vscode-service/dist/launcher.js:163:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
I stepped through the  `_fetchChromedriverVersion`  for vscode version `stable` and the version key for chrome was `118`.

Using the URI `https://chromedriver.storage.googleapis.com/LATEST_RELEASE_118` results in a key not found.

I found this [article](https://chromedriver.chromium.org/home) that states chrome driver version 116 and above have been moved to a new location.

### What is your expected behavior?

The correct chrome driver should be found regardless of its distribution location

### How to reproduce the bug.

[gist](https://gist.github.com/petehale/b4c5fec93bbbeec562416b8526345021)

### Relevant log output

```typescript
SevereServiceError in "onPrepare"
SevereServiceError: 
A service failed in the 'onPrepare' hook
SevereServiceError: Couldn't set up Chromedriver Response code 404 (Not Found)
    at VSCodeServiceLauncher._setupChromedriver (file:///Users/peter.hale/git/wdio-foo/node_modules/wdio-vscode-service/dist/launcher.js:163:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2024-02-05 15:08
Duplicate of https://github.com/webdriverio-community/wdio-vscode-service/pull/94

**Closed by christian-bromann** 2024-02-05 15:08 UTC
Labels: Bug 🐛, Needs Triaging ⏳
