### ISSUE TITLE
[🐛 Bug]: Method 'isDisplayed' works incorrectly in chrome for elements with zero opacity and not empty content

### ISSUE THREAD

**Issue by eGavr** [webdriverio/webdriverio#7708] opened 2021-11-17 08:08 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.8

### Node.js Version

v14.17.3

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
    browserName: 'chrome' // 'firefox'
}
```

### What happened?

Method `isDisplayed` returns different values in chrome and firefox for elements with zero opacity and not empty content:

```html
<div id="zeroOpacity" style="opacity: 0">hi</div>
```

`isDisplayed` returns `false` in chrome and `true` in firefox.

### What is your expected behavior?

`isDisplayed` should return the same value for both browsers and this value should be `true` (according to [spec](https://w3c.github.io/webdriver/#element-displayedness)), because element with zero opacity and not empty content affects layout (`getBoundingClientRect().height` for the element returns non zero value).

### How to reproduce the bug.

- firefox and chrome installed
- create file `index.html` and serve it with some static server on 9000 port:
```html
<div id="zeroOpacity" style="opacity: 0">hi</div>
```
- Run `selenium-standalone` on 4444 port
- Create file `index.js`:
```js
const webdriverio = require('webdriverio');

(async () => {
    const browser = await webdriverio.remote({
        prootcol: "http",
        hostname: "localhost",
        port: 4444,
        path: "/wd/hub",
        capabilities: {
            browserName: process.env.BROWSER_NAME || 'chrome'
        },
        baseUrl: "http://localhost:9000",
        logLevel: 'error'
    });

    await browser.url('/index.html');

    const elem = await browser.$("#zeroOpacity");
    console.log(await elem.isDisplayed());

    await browser.deleteSession();
})();
```
- Run in chrome:
```
BROWSER_NAME=chrome node index.js # logs `false`
```
- Run in firefox:
```
BROWSER_NAME=chrome node index.js # logs `true`
```

### Relevant log output

```typescript
false
```

in chrome

```typescript
true
```

in firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by eGavr** [comment] 2021-11-17 08:12
It seems that this bug can be fixed by adding the following conjunction condition [here](https://github.com/webdriverio/webdriverio/blob/dec6da76b0e218af935dbf39735ae3491d5edd8c/packages/webdriverio/src/scripts/isElementDisplayed.ts#L243):

```
&& e.innerText.length
```

**Comment by christian-bromann** [comment] 2021-11-17 09:49
@eGavr should we just check for `opacity === 0`?

**Comment by praveendvd** [comment] 2021-12-14 08:39
@christian-bromann  and @eGavr  , it works as expected with chromedriver 96. it looks like it was an chromedriver issue

```
const webdriverio = require('webdriverio');

(async () => {
    const browser = await webdriverio.remote({
        prootcol: "http",
        hostname: "localhost",
        port: 9515,
        path: "/",
        capabilities: {
            browserName: process.env.BROWSER_NAME || 'chrome'
        },
        baseUrl: "https://wdio.tiiny.site/",
        logLevel: 'error'
    });

    await browser.url('/');

    const elem = await browser.$("#zeroOpacity");
    console.log("vsiible",await elem.isDisplayed());
    console.log("Exist",await elem.isExisting());

    await browser.deleteSession();
})();


```

**Comment by christian-bromann** [comment] 2022-03-29 11:09
This doesn't seem reproducible anymore, therefor I will close the issue.

**Closed by christian-bromann** 2022-03-29 11:09 UTC
Labels: Bug 🐛, help wanted, good first pick
