### ISSUE TITLE
browser of browser.sharedStore is undefined when running tests against electron app

### ISSUE THREAD

**Issue by Hayk-S** [webdriverio/webdriverio#6024] opened 2020-10-22 19:09 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** [6.4.0]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [async]
 - **Node.js version:** [12.18.4]
 - **NPM version:** [6.14.8]
 - **Browser name and version:** [Chrome 86]
 - **Platform name and version:** [macOS Catalina 10.15.7]
 - **Additional wdio packages used (if applicable):** [@wdio/spec reporter, wdio-chromedriver-service, @wdio/sync, @wdio/mocha-framework, @wdio/local-runner, @wdio/junit-reporter, @wdio/dot-reporter, @wdio/shared-store-service]

**Config of WebdriverIO**
services: ['chromedriver', 'shared-store']

**Describe the bug**
I have 3 spec files that run consecutively as a single test suite. In before hook of 1st spec I store some data coming from api response such as `browser.sharedStore.set('accessToken', accessToken)` and in spec file 3 I am getting that data as
 `await browser.sharedStore.get('accessToken')`. The problem is that when I run my tests againt electron app (I use spectron `^9.0.0`) the browser becomes undefined since in case of electron app the client is not the browser and this causes error.

**To Reproduce**
1. Create 2 separate spec files
2. Make sure in 1st spec file you store some data in sharedStore
3. Make sure in 2nd spec file you get that data from sharedStore and use it
4. Make sure the tests are running against electron app via spectron library.
5. Confirm that code works and the browser is not `undefined`

**Expected behavior**
Tests run successfully with stored data.

**Log**
https://gist.github.com/Hayk-S/c911c7bcfa21b59db0d5fab424ce921a

**Comment by mgrybyk** [comment] 2020-10-22 19:17
Can you share a reproducible example in a repo? I can't understand what are you doing with electron.

**Comment by Hayk-S** [comment] 2020-10-22 19:21
@mgrybyk I am afraid I cannot expose the entire framework.  In regards to electron I am only running my tests against electron desktop application which is not a big deal. I am working with spectron  `https://www.electronjs.org/spectron` and here is where sharedStore does not work

**Comment by mgrybyk** [comment] 2020-10-22 19:23
Can you share minimum reproducible example? At this point I believe the issue is not related to webdriverio anyhow

**Comment by Hayk-S** [comment] 2020-10-22 19:24
@mgrybyk the issue is related to @wdio/shared-store-service package and not to WDIO itself

**Comment by mgrybyk** [comment] 2020-10-22 19:25
Closing for now but I'm ready to help once there is a reproducible example.

**Comment by Hayk-S** [comment] 2020-10-22 19:25
Will reopen when shareable code will be under hand

**Comment by mgrybyk** [comment] 2020-10-22 19:25
The shared store service suppose to work with webdriverio not any other framework

**Closed by mgrybyk** 2020-10-22 19:25 UTC
Labels: Reproducible Example Missing

**Comment by Hayk-S** [comment] 2020-10-22 19:27
In that case this sounds more like feature request than bug (just opened following advice )

**Comment by mgrybyk** [comment] 2020-10-22 19:31
You can fork wdio shared store service and make it work in any other framework. 
As I said, it suppose to work only with webdriverio.

Perhaps a reproducible example might help to understand what is actually going on
