### ISSUE TITLE
"is calling TIS/TSM in non-main thread environment, ERROR" repeated hundreds of times when running tests

### ISSUE THREAD

**Issue by jcollum-autodesk** [webdriverio/webdriverio#4650] opened 2019-10-17 23:35 UTC
**Is your feature request related to a problem? Please describe.**
I get 100s of lines of output like this on Mac OS X when I run many tests: 

```
2019-10-17 16:33:38.605 chromedriver[83751:1536943] pid(83751)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
2019-10-17 16:33:38.605 chromedriver[83751:1536943] pid(83751)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
2019-10-17 16:33:38.605 chromedriver[83751:1536943] pid(83751)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
2019-10-17 16:33:38.605 chromedriver[83751:1536943] pid(83751)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
2019-10-17 16:33:38.605 chromedriver[83751:1536943] pid(83751)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
2019-10-17 16:33:38.605 chromedriver[83751:1536943] pid(83751)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
2019-10-17 16:33:38.605 chromedriver[83751:1536943] pid(83751)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
2019-10-17 16:33:38.605 chromedriver[83751:1536943] pid(83751)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
```

**Describe the solution you'd like**
Directly filter it out until a better solution can be found, like this:  https://github.com/processing/processing/commit/f512457c6e6034a1230161a01080ede5f431eebb

**Describe alternatives you've considered**
🤷‍♂

**Comment by mgrybyk** [comment] 2019-10-18 06:11
What is tis tsm?

**Comment by jcollum-autodesk** [comment] 2019-10-20 21:09
It's related to the Chrome driver https://sqa.stackexchange.com/questions/37745/calling-tis-tsm-in-non-main-thread-environment

It sounds like it's related to logging

**Comment by christian-bromann** [comment] 2019-10-22 09:04
> It's related to the Chrome driver

Closing this then as I am not sure how to fix it on the WebdriverIO level. Thanks for investigating!

**Closed by christian-bromann** 2019-10-22 09:04 UTC
Labels: Reproducible Example Missing

**Comment by jcollum-autodesk** [comment] 2019-10-22 16:31
I gave you a solution that a different library used up above. Please re-open.

**Comment by christian-bromann** [comment] 2019-10-22 16:58
> I gave you a solution that a different library used up above. Please re-open.

We are not maintaining Chromedriver so please raise an issue in the Chromium project. Cheers!

**Comment by jcollum-autodesk** [comment] 2019-10-22 22:09
Yes, but you could filter it out of your logs, like that other library did. It creates a bunch of crap output that has nothing to do with the tests. 

I didn't have this problem in Testcafe BTW.

**Comment by christian-bromann** [comment] 2019-10-23 07:15
> Yes, but you could filter it out of your logs

Since I can't reproduce it would be really hard to implement a fix and assume how Chromedriver is behaving. If you could provide such a fix we would really appreciate that 🙏

**Comment by jcollum-autodesk** [comment] 2019-10-23 16:34
Sure, can you point me to the file that deals with logging to the terminal?

**Comment by christian-bromann** [comment] 2019-10-23 17:03
@jcollum-autodesk if you use one of the services to start Chromedriver I would look in there

**Comment by mikol** [comment] 2020-01-30 21:56
I can reproduce this issue with two specs that each contain `element.setValue(...)` calls. If they run in parallel (`maxInstances >= 2`), I see the above `TIS/TSM` log output (apparently one error per character?). The problem may be with Chromedriver, it might be the way that WebdriverIO is implementing `element.setValue()`, not sure. I haven’t tried the `selenium-standlaone` service to see if the issue can be mitigated by avoiding Chromedriver directly.

**Comment by mikol** [comment] 2020-01-30 21:56
See this Apple developer forum post: https://forums.developer.apple.com/thread/105244

**Comment by mikol** [comment] 2020-01-31 00:33
I also found the chromedriver issue, I believe: https://bugs.chromium.org/p/chromedriver/issues/detail?id=2909

**Comment by tonyrosario** [comment] 2020-02-06 20:02
Chiming in because we just came across this issue.

- confirmed [mikol's findings](https://github.com/webdriverio/webdriverio/issues/4650#issuecomment-580479837), where multiple setValues are running in parallel on mac.  
  - all it took was two tests calling .setValue in parallel (our login page)

> I haven’t tried the selenium-standlaone service to see if the issue can be mitigated by avoiding Chromedriver directly.
- error messages did not appear when running the tests against a local zalenium grid (which is using selenium-standalone service)

**Comment by icarus44-zer0** [comment] 2020-05-23 18:14
Was a solution to this issue ever found?
