### ISSUE TITLE
@wdio/browserstack-service returns 404

### ISSUE THREAD

**Issue by khause** [webdriverio/webdriverio#3837] opened 2019-04-10 15:24 UTC
**Environment:**
 - **WebdriverIO version:** 5.7.6
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** @wdio/sync
 - **Node.js version:** 11.13.0
 - **NPM version:** 6.7.0
 - **Platform name and version:** Mac 10.14.4
 - **Additional wdio packages used (if applicable):** [@wdio/browserstack-service 5.7.8, @wdio/cli, @wdio/jasmine-framework, @wdio/local-runner]

**Config of WebdriverIO**
```
runner: 'local',
logLevel: 'info',
baseUrl: '',
framework: 'jasmine',
services: ['browserstack'],
user: process.env.BS_USER,
key: process.env.BS_KEY
capabilities: [{
    ...caps[device]
}],
```

**Description**
`@wdio/sync` receives a 404 response from the `@wdio/browserstack-service`.
The service is requesting `https://api.browserstack.com/automate/sessions/${this.sessionId}.json` whereas the correct url should be `https://api.browserstack.com/app-automate/sessions/${this.sessionId}.json` as I am testing a mobile app.
Notice: '**app-**' in the 2nd url.

**To Reproduce**
Just simple test a mobile app using the `@wdio/browserstack-service`.

**Expected behavior**
I expect `@wdio/browserstack-service` to handle if a mobile app is being tested and to use the correct url.

**Log**
https://gist.github.com/khause/9f257946d53d6766fa01b2cc302b10c8

**Comment by christian-bromann** [comment] 2019-04-10 15:40
Duplicate of #3833

**Closed by christian-bromann** 2019-04-10 15:40 UTC
