### ISSUE TITLE
browser.closeWindow() closes all the windows and not only the current browsing context

### ISSUE THREAD

**Issue by raulcabero** [webdriverio/webdriverio#3270] opened 2019-01-07 16:40 UTC
**Environment :**
 - **WebdriverIO version:** [5.2.2]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [10.15.0]
 - **NPM version:** [6.4.1]
 - **Browser name and version:** [Chrome 71]
 - **Platform name and version:** [Windows 10]
 - **Additional wdio packages used (if applicable):** [@wdio/selenium-standalone service, @wdio/sync, @wdio/local-runner, @wdio/cli]

**Describe the bug**
I want to close an emergent window, but when I use the browser.closeWindow()  method all the windows are being closed

**To Reproduce**

this is my current code, in case an emergent window appears I change the current browsing context to it, and close it.

```
const handles = browser.getWindowHandles();
        if (handles.length > 1) {
            browser.switchToWindow(handles[1]);
            browser.closeWindow();
        }
```
for the WebdriverIO version 4 I used this code and it worked fine.

```
const tabIds = browser.getTabIds();
        if (tabIds.length > 1) {
            browser.switchTab(tabIds[1]);
            browser.close();
        }
```

**Expected behavior**
Only the window with the current browsing context should be closed.

**Comment by abjerstedt** [comment] 2019-01-07 16:42
I cannot reproduce this. I do something similar and my tests behave as designed.

**Comment by abjerstedt** [comment] 2019-01-07 16:47
@raulcabero  Do you actually witness all the windows closing? You are forgetting to change your tab context back to the first window. You need to do the following instead:

const handles = browser.getWindowHandles();
        if (handles.length > 1) {
            browser.switchToWindow(handles[1]);
            browser.closeWindow();
            browser.switchToWindow(handles[0]);
     }

**Closed by abjerstedt** 2019-01-07 16:47 UTC

**Comment by raulcabero** [comment] 2019-01-07 16:51
yep that code worked, thank you very much :).

**Comment by arunqa2code** [comment] 2020-11-05 21:28
Hi, Can you please let me know how we can open a new tab? I have a scenario, where I need to just open a new tab and perform some validations on the previous tab. 

Any help would be much appreciated.
