### ISSUE TITLE
Improve error message for mis-configured proxy

### ISSUE THREAD

**Issue by asocaciu** [webdriverio/webdriverio#6075] opened 2020-11-06 13:23 UTC
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.7.2
 - **Mode:** Standalone (not really sure)
 - **Node.js version:** 10.16.3
 - **NPM version:** 6.9.0
 - **Browser name and version:** not relevant
 - **Platform name and version:** Fedora Linux 29
 - **Additional wdio packages used (if applicable):** @wdio/sauce-service

**Config of WebdriverIO**
Relevant saucelabs configuration values:
```
    user: 'xxx',
    key: 'xxx-xx-xxx',
    region: 'eu',
    sauceConnect: false,
```

global-agent is configured as per https://webdriver.io/docs/proxy.html 
running the tests using: `GLOBAL_AGENT_HTTP_PROXY=http://corporate-proxy:8080 wdio wdio.conf.js`

**Describe the bug**
The tests connect remotely to saucelabs using an URL like: `https://user:pass@ondemand.eu-central-1.saucelabs.com:443/wd/hub`. Our company network is behind a http-only proxy, so the https request needs to be tunneled through the proxy. This does not work, the tests fail with the following error message:

```
[1-0] 2020-11-06T11:29:56.864Z ERROR webdriver: RequestError: write EPROTO 140336396121920:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at ClientRequest.request.once (/home/xxx/node_modules/webdriver/node_modules/got/dist/source/core/index.js:953:111)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:203:15)
    at ClientRequest.EventEmitter.emit (domain.js:448:20)
    at ClientRequest.origin.emit.args (/home/xxx/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:203:15)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at WriteWrap.afterWrite (net.js:788:14)
[1-0] 2020-11-06T11:29:56.864Z ERROR @wdio/runner: Error: Failed to create session.
write EPROTO 140336396121920:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at Object.startWebDriverSession (/home/xxx/node_modules/webdriver/build/utils.js:35:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[1-0]  Error:  Failed to create session.
write EPROTO 140336396121920:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
```

**Additional context**
Running the tests outside the corporate network, without a proxy setting, works correctly.
I am not sure which package is causing this error, I've spent the last 3 days tring to understand which of wdio/sauce-service, webdriver, got, global-agent does not handle this situation properly, but I could not.

> Please use the correct markdown

**Comment by christian-bromann** [comment] 2020-11-06 14:49
Seems to be related to https://github.com/sindresorhus/got/issues/850

**Comment by christian-bromann** [comment] 2020-11-09 17:27
I think this is related to the fact that your proxy is `http` based and WebdriverIO automatically connects through `https`. I think we need to modify the code in [`_createOptions`](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriver/src/request.ts#L72) to properly set up [got](https://www.npmjs.com/package/got) with a HTTP proxy.

Any help on this would be appreciated. Please have a look into our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and let us know if you have any questions.

**Comment by asocaciu** [comment] 2020-11-09 17:38
It turned out our proxy has a whitelist, and the URL I was trying to access was not whitelisted. It will take a few days for that to come through, after that I'll be able to post more details, or it could very well turn out to be a false alarm. From the error message it was not clear what the problem actually way. I'll post an update when I know more.

**Comment by christian-bromann** [comment] 2020-11-09 17:40
@asocaciu great! Some more details would be beneficial, maybe we can at least improve the error message here.

**Comment by asocaciu** [comment] 2020-11-11 13:03
It was indeed only a proxy whitelist issue, now it works correctly. I am not sure webdriverio can do much about improving the error message, I think that would be within global-agent, since the error is caught there.
Thanks again for your support, and sorry for the trouble!

**Comment by christian-bromann** [comment] 2020-11-16 11:17
I think we can do improve the error message in `packages/webdriver/src/request.ts` by checking if the error/response contains or starts with `write EPROTO`.

**Comment by christian-bromann** [comment] 2021-05-28 09:00
I will close this with no action. I doubt we can point to proxy issues given this error as it could be caused by other failures too.

**Closed by christian-bromann** 2021-05-28 09:00 UTC
Labels: Bug🐛, first-timers-only, good first pick, help wanted

**Comment by leejensen** [comment] 2021-06-16 21:39
Is there a solution here? I'm trying to connect to SauceLabs and get this error.

My setup is using all the latest WDIO versions. I'm NOT on a proxy (using my home network). 

WebdriverIO version: 7.7.3
Mode: Standalone
Node.js version: 14.16.0
NPM version: 6.14.11
Browser name and version: not relevant
Platform name and version: Ubuntu 18 or Windows 10
Additional wdio packages used (if applicable):
"@wdio/cli": "^7.5.2",
"@wdio/devtools-service": "^7.5.7",
"@wdio/local-runner": "^7.7.3",
"@wdio/logger": "^7.7.0",
"@wdio/mocha-framework": "^7.5.3",
"@wdio/sauce-service": "^7.7.3",
"@wdio/selenium-standalone-service": "^7.5.7",
"@wdio/spec-reporter": "^7.7.3",
"@wdio/sync": "^7.3.1",
"@wdio/types": "^7.7.3",
"expect-webdriverio": "^2.0.1",
"wdio-chromedriver-service": "^7.0.0",
"webdriverio": "^7.7.3"

wdio config has the basic Sauce Labs setup:

user: 'username',
key: 'apikey',
region: 'us',
services: [
  ['sauce', {
	sauceConnect: true,
  }],
],
capabilities: [{
  browserName: 'chrome',
  browserVersion: 'latest',
  platformName: 'Windows 10',
  'sauce:options': {
	screenResolutions: '1280x1024',
  },
}],

What am I missing?
