### ISSUE TITLE
Warning about 'keys' method

### ISSUE THREAD

**Issue by eGavr** [webdriverio/webdriverio#2238] opened 2017-08-09 18:30 UTC
I use the latest version of wdio (4.8.0). After calling of `keys` method I've got warning

```bash
WARNING: the "keys" command will be depcrecated soon. Please use a different command in order to avoid failures in your test after updating WebdriverIO.
```

Which method should I use?

I've tried method `sendKeys` which I've found in the example, but got that it does not exist.

Please, help.

Thanks.

**Comment by christian-bromann** [comment] 2017-08-09 22:07
Duplicate of #2076

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Closed by christian-bromann** 2017-08-09 22:07 UTC
