### ISSUE TITLE
Devtools Service - Event Listener capture each event twice

### ISSUE THREAD

**Issue by refael-m** [webdriverio/webdriverio#6347] opened 2021-01-26 12:09 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.12.1
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.18.4
 - **NPM version:** 6.14.6
 - **Browser name and version:** Chrome 88

**Config of WebdriverIO**
Generate with npx wdio config -y and add 'devtools' to the service list 

**Describe the bug**
When using the following code to capture events, each event captured twice

```
it('should listen on network events', () => {
        browser.cdp('Network', 'enable')
        browser.on('Network.responseReceived', (params) => {
            console.log(`Loaded ${params.response.url}`)
        })
        browser.url('https://www.google.com')
    })
```

**To Reproduce**
I've created an example repository:
[sample-wdio-duplicate-event](https://github.com/refael-m/sample-wdio-duplicate-event/tree/master
)

**Expected behavior**
Capture each event once.

**Additional context**
![image](https://user-images.githubusercontent.com/72335192/105841496-5eee0380-5fdd-11eb-9514-7181734368b7.png)

> Please use the correct markdown

**Comment by christian-bromann** [comment] 2021-01-26 12:35
@refael-m thank you for this great report. This indeed looks like a bug.

**Comment by joshskumar** [comment] 2021-01-30 23:46
@christian-bromann  puppeteer core might be adding multiple events so can you please let know if I am right about it.
because issue is with this part of the code.

this._puppeteer['_connection']._transport._ws.addEventListener('message', (event: { data: string }) => {
            const data: CDPSessionOnMessageObject = JSON.parse(event.data)
            this._devtoolsGatherer?.onMessage(data)
            const method = data.method || 'event'
            log.debug(`cdp event: ${method} with params ${JSON.stringify(data.params)}`)

            if (this._browser) {
                this._browser.emit(method, data.params)
            }
        })

**Comment by christian-bromann** [comment] 2021-02-01 08:17
> puppeteer core might be adding multiple events so can you please let know if I am right about it.

I am not sure 😄

**Comment by strusbergAlex** [comment] 2021-07-20 13:37
Also happens on my tests. I am not using  puppeteer.

**Comment by newtewt** [comment] 2021-08-13 19:08
I had generated a sample repo to reproduce this issue before finding this issue. 😄

**Comment by nikhil-sharma10** [comment] 2021-11-16 07:14
Is there any we can use below chrome devtools protocol while adding a listener?
browser.cdp('Audits','enable');
browser.on('Audits.issueAdded');
browser.url('https://google.com');
when i tried using it i am seeing its working fine in my local. but when used Jenkins to run it. Its throwing an error saying "Audits" domain doesn't have enable method.
https://chromedevtools.github.io/devtools-protocol/tot/Audits/ its the chrome devtools audits domain.

**Comment by christian-bromann** [comment] 2021-11-16 08:16
You might not be connected to a target. I recommend to use `getPuppeteer` and use the Puppeteer interface which hides away some of the complexities of CDP.

**Comment by nikhil-sharma10** [comment] 2021-11-16 09:31
Thanks @christian-bromann but can you help me by providing an example of how to use it? My use case is i have to navigate at one place i.e. https://googleads.github.io/googleads-ima-html5/vsi/ and put up the Vast URL in the inputfield and then click on the vast AD. Then i need to capture the results. So I've tried using getPuppeteer in this way. 
(async () => {
      const puppeteer = await browser.getPuppeteer();
      const [page] = await puppeteer.pages();
      await page.setRequestInterception(true);
      page.on('requestfinished',async (request) => {
        const response = await request.response();

        const responseHeaders = response.headers();
        let responseBody;
        if (request.redirectChain().length === 0) {
          // body can only be access for non-redirect responses
          responseBody = await response.buffer();
        }

        const information = {
          url: request.url(),
          requestHeaders: request.headers(),
          requestPostData: request.postData(),
          responseHeaders: responseHeaders,
          responseSize: responseHeaders['content-length'],
          responseBody,
        };
        console.log("Request url: " + JSON.stringify(information.url));
      });
    });
I've used this piece of code after clicking on the button. But somehow it doesn't seem to be working. As this console log itself is not printing anything

**Comment by tkmcmaster** [comment] 2022-09-28 19:51
Is there any updates on this or a workaround? I'm not using puppeteer and am having issues with this. I'm currently working around it with a class that tries to detect the duplicates and ignore the duplicate but it's not always reliable.

**Comment by christian-bromann** [comment] 2022-09-28 22:43
@tkmcmaster any contributions that fixes the problem are appreciate. Cheers!

**Comment by christian-bromann** [comment] 2023-01-23 19:51
I can't reproduce this anymore with latest WebdriverIO v8. Closing.

**Closed by christian-bromann** 2023-01-23 19:51 UTC
Labels: Bug 🐛, help wanted, good first pick
