### ISSUE TITLE
Error message ' Error in "<unknown test>" ' is logging in case of using jasmineNodeOpts setting failFast

### ISSUE THREAD

**Issue by mshykov** [webdriverio/webdriverio#5239] opened 2020-04-09 13:01 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** [5.22.4]
 - **Mode:** [Standalone mode]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [10.19.0]
 - **NPM version:** [6.14.4]
 - **Browser name and version:** [Chrome 80.0.3987.163]
 - **Platform name and version:** [Mac OS X]
 - **Additional wdio packages used (if applicable):** 

```
 "devDependencies": {
    "@wdio/allure-reporter": "^5.22.4",
    "@wdio/browserstack-service": "^5.22.1",
    "@wdio/cli": "^5.22.4",
    "@wdio/jasmine-framework": "^5.18.6",
    "@wdio/local-runner": "^5.22.4",
    "@wdio/selenium-standalone-service": "^5.16.10",
    "@wdio/spec-reporter": "^5.22.4",
    "@wdio/sync": "^5.18.7",
    "webdriverio": "5.22.4",
},
```

**Config of WebdriverIO**
```javascript
exports.config = {
  bail: 0,
  framework: 'jasmine',
  jasmineNodeOpts: {
    defaultTimeoutInterval: 100000,
    failFast: true,
    stopSpecOnExpectationFailure: true,
    grep: null,
    invertGrep: null,
  },
};
```

**Describe the bug**
Extra message is logging in case `jasmineNodeOpts` contains the setting `failFast: true`:  
`Error in "<unknown test>"`

**To Reproduce**
```javascript
describe('My test: describe', () => {
  beforeAll(() => {
    console.log('beforeAll');
    throw new Error('before all error');
  });
  beforeEach(() => {
    console.log('beforeEach');
  });
  it('My test: it #1', () => {
    console.log('My test: it #1');
  });
  it('My test: it #2', () => {
    console.log('My test: it #2');
  });
  afterEach(() => {
    console.log('afterEach');
  });
  afterAll(() => {
    console.log('afterAll');
  });
});
```

**Expected behavior**
As the setting `failFast: true` interrupts executing of all hooks in the spec, any additional messages should not be logged after failure appears
Exception: `afterAll()` hook after [jasmine issue 1533](https://github.com/jasmine/jasmine/issues/1533) will be implemented

**Log**
```
Execution of 1 spec files started at 2020-04-09T12:32:37.778Z

[0-0] RUNNING in chrome - /my-test.js
[0-0] beforeAll
[0-0] Error in ""before all" hook"
before all error
[0-0] Error in "<unknown test>"
Error: before all error
[0-0] FAILED in chrome -/my-test.js

 "spec" Reporter:
------------------------------------------------------------------
[chrome 80.0.3987.163 Mac OS X #0-0] Spec: /my-test.js
[chrome 80.0.3987.163 Mac OS X #0-0] Running: chrome (v80.0.3987.163) on Mac OS X
[chrome 80.0.3987.163 Mac OS X #0-0] Session ID: e3b43cc63cfe305a340a5fa7047fdbe5
[chrome 80.0.3987.163 Mac OS X #0-0]
[chrome 80.0.3987.163 Mac OS X #0-0] My test: describe
[chrome 80.0.3987.163 Mac OS X #0-0]    ✖ "before all" hook
[chrome 80.0.3987.163 Mac OS X #0-0]    ✖ <unknown test>
[chrome 80.0.3987.163 Mac OS X #0-0]
[chrome 80.0.3987.163 Mac OS X #0-0] 2 failing (4.4s)
[chrome 80.0.3987.163 Mac OS X #0-0]
[chrome 80.0.3987.163 Mac OS X #0-0] 1) My test: describe "before all" hook
[chrome 80.0.3987.163 Mac OS X #0-0] before all error
[chrome 80.0.3987.163 Mac OS X #0-0]
[chrome 80.0.3987.163 Mac OS X #0-0] 2) My test: describe <unknown test>
[chrome 80.0.3987.163 Mac OS X #0-0] Error: before all error
[chrome 80.0.3987.163 Mac OS X #0-0] Error: before all error
[chrome 80.0.3987.163 Mac OS X #0-0]     at UserContext.<anonymous> (/my-test.js:6:11)

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:09 
```

**Comment by christian-bromann** [comment] 2020-04-09 13:58
To set clear expectations: this is not a critical bug so it is unlikely that it is being picked up by the core team. We would appreciated any contribution for this problem.

**Comment by apkatsikas** [comment] 2020-05-05 23:24
@christian-bromann - seems this issue exists in v6. I would like to fix it for an upcoming v6 jasmine framework release. Should I file a new issue or use this?

**Comment by christian-bromann** [comment] 2020-05-05 23:32
> Should I file a new issue or use this?

@apkatsikas you can use this.

**Comment by apkatsikas** [comment] 2020-05-05 23:34
@christian-bromann ok, can you assign to me?

**Comment by apkatsikas** [comment] 2020-05-07 21:25
It seems like this might be desirable behavior. A "fake" test is created if there are `failedExpectations` but no tests have been run - https://github.com/webdriverio/webdriverio/blob/21539bb965e87df2df5ae4971cc7ce826a538582/packages/wdio-jasmine-framework/src/reporter.js#L74

This fake test is useful, because it allows the suite to exit with a non-zero status, indicating failure. If this fake test is not attached, the suite will exit with status 0 successfully, so you get a false-positive situation.

The original request seems to be wanting this extra test to not be reported. I suppose there could be changes in the spec reporter to accommodate this, but that would require passing around a `failFast` flag between reporter packages, which doesnt seem desirable.

cc: @mshykov @christian-bromann

**Comment by christian-bromann** [comment] 2020-05-08 09:19
I think this is connected to #5220. I think it makes sense to pass in the framework options into the [WDIOReporter](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-reporter/src/index.js#L17) and have the reporter properly act on whether or not the execution is suppose to stop immediately or not.

**Comment by apkatsikas** [comment] 2020-05-08 15:52
> I think this is connected to #5220. I think it makes sense to pass in the framework options into the [WDIOReporter](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-reporter/src/index.js#L17) and have the reporter properly act on whether or not the execution is suppose to stop immediately or not.

ok - when you say execution is supposed to stop, what exactly do you mean? once the beforeAll hook fails, execution _does_ stop. We just get the fake test to attach the error to

**Comment by christian-bromann** [comment] 2020-05-08 17:12
What I mean by that is that if the framework has a feature like `failFast` the WDIO reporter should account to that so propagating these options into a reporter makes sense to me as well as adjusting the output if flags like this are set.

**Comment by apkatsikas** [comment] 2020-07-27 14:58
@christian-bromann sorry for the lack of updates - got confused as i dug deeper on this one and got sidetracked. I've unassigned myself for now.

**Comment by umair2020** [comment] 2021-11-15 23:10
will anyone be looking at this anytime soon?

**Comment by christian-bromann** [comment] 2021-11-15 23:54
@umair2020 would you like to help us out here?

**Comment by umair2020** [comment] 2022-01-25 08:20
@christian-bromann please let me know how can I help.
I am facing this issue in couple of tests but not sure how to fix it. I am not using failFast in the jasmine options

**Comment by christian-bromann** [comment] 2022-01-25 08:31
The problem should be somewhere in the Jasmine framework adapter and is connected with how we propagate the error. Without any knowledge it is hard to say where to look exactly.

**Comment by harsha509** [comment] 2022-02-26 14:51
Hi @umair2020 ,

I tried to reproducing the issue with above details, but I was unable to 
config:
```
    framework: 'jasmine',
    reporters: ['spec'],
    jasmineNodeOpts: {
        defaultTimeoutInterval: 100000,
        failFast: true,
        stopSpecOnExpectationFailure: true,
        grep: null,
        invertGrep: null,
    },
```

Test:
```
describe('My test: describe', () => {
    beforeAll(() => {
        console.log('beforeAll');
        throw new Error('before all error');
    });
    beforeEach(() => {
        console.log('beforeEach');
    });
    it('My test: it #1', () => {
        console.log('My test: it #1');
    });
    it('My test: it #2', () => {
        console.log('My test: it #2');
    });
    afterEach(() => {
        console.log('afterEach');
    });
    afterAll(() => {
        console.log('afterAll');
    });
});
```

console:
```
[chrome 98.0.4758.109 mac os x #0-0] Running: chrome (v98.0.4758.109) on mac os x
[chrome 98.0.4758.109 mac os x #0-0] Session ID: a04bccd7142103ce6ad2ffa8a9514224
[chrome 98.0.4758.109 mac os x #0-0]
[chrome 98.0.4758.109 mac os x #0-0] » /test/specs/jasmine.e2e.js
[chrome 98.0.4758.109 mac os x #0-0] My test: describe
[chrome 98.0.4758.109 mac os x #0-0]    ✖ "before all" hook
[chrome 98.0.4758.109 mac os x #0-0]    ✓ My test: it #1
[chrome 98.0.4758.109 mac os x #0-0]    ✓ My test: it #2
[chrome 98.0.4758.109 mac os x #0-0]
[chrome 98.0.4758.109 mac os x #0-0] 2 passing (69ms)
[chrome 98.0.4758.109 mac os x #0-0] 1 failing
[chrome 98.0.4758.109 mac os x #0-0]
[chrome 98.0.4758.109 mac os x #0-0] 1) My test: describe "before all" hook
[chrome 98.0.4758.109 mac os x #0-0] before all error
```

is this issue intermittent? is there any specific case to reproduce it issue?

**Comment by BorisOsipov** [comment] 2023-03-02 20:06
Hi! We have rewritten the reporter to the new allure-js version. Please try version 8.5.0 of wdio-allure-reporter and provide more details if the issue still persists. Feel free to create a new issue with actual details if it reproduces.

**Comment by sushantsoni5392** [comment] 2023-05-08 11:27
This issue still exists in case of fail fast options in jasmine
<img width="538" alt="image" src="https://user-images.githubusercontent.com/3597767/236811812-404f403e-15eb-4119-b20e-7d13fe01093a.png">

You can reproduce it in this repo - https://github.com/sushantsoni5392/jasmine-boilerplate

**Comment by christian-bromann** [comment] 2023-05-08 15:34
Thanks for providing a reproducible example.

Any contributions that resolves the bug are highly appreciated. Don't expect this to be picked up by active contributors as they have their own priorities. If you depend on this bug to be fixed, your contribution is required. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) or join our [Discord](http://discord.webdriver.io/) development server and let us know if you have any questions. Cheers!

**Comment by christian-bromann** [comment] 2023-06-11 20:36
@sushantsoni5392 I took a look into this and it seems this is what WebdriverIO gets from Jasmine. The Jasmine reporter returns:

```
{
  id: 'spec0.8036648635101069',
  description: '<unknown test>',
  fullName: '<unknown test>',
  failedExpectations: [
    {
      matcherName: '',
      message: 'Error: My error',
      stack: '    at UserContext.<anonymous> (file:///private/tmp/jasmine-boilerplate/test/specs/checkbox.spec.ts:6:15)\n' +
        '    at processTicksAndRejections (node:internal/process/task_queues:95:5)',
      passed: false,
      expected: '',
      actual: ''
    }
  ],
  deprecationWarnings: [],
  passedExpectations: [],
  status: 'failed',
  duration: null,
  properties: {},
  pendingReason: '',
  debugLogs: null
}
```

which is why WebdriverIO propagates this to the reporter. I don't think there is anything we can do. While this experience is definitely not ideal I will go ahead and close this as this should be fixed within Jasmine. You might want to give Mocha a try as it could provide better reporting and is similar to Jasmine.

**Closed by christian-bromann** 2023-06-11 20:36 UTC
Labels: help wanted, good first pick, first-timers-only
