### ISSUE TITLE
[🐛 Bug]: Unable to run tests on Firefox using Selenium Standalone Service

### ISSUE THREAD

**Issue by sam-022** [webdriverio/webdriverio#8282] opened 2022-04-28 17:13 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.19.6

### Node.js Version

17.4.0 

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
   browserName: 'firefox',
}
```

### What happened?

When setting up new project using standalone service and setting up firefox as the browser, it's not running the tests. Keeps throwing the following error -

`webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option`

Dependencies:
```
    "devDependencies": {
        "@wdio/cli": "^7.19.6",
        "@wdio/local-runner": "^7.19.5",
        "@wdio/mocha-framework": "^7.19.5",
        "@wdio/selenium-standalone-service": "^7.19.5",
        "@wdio/spec-reporter": "^7.19.5"
    },
```
### What is your expected behavior?

Should be able to run tests on Firefox

### How to reproduce the bug.

Setup a new project using the `wdio cli` and in service select `selenium-standalone-service` and update the capabilities to add browserName as firefox. Then, try running the project with `npx wdio`

```
{
   browserName: 'firefox',
}
```

### Relevant log output

```typescript
Execution of 1 workers started at 2022-04-28T17:00:49.658Z

2022-04-28T17:00:49.760Z INFO @wdio/cli:launcher: Run onPrepare hook
2022-04-28T17:00:56.931Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-04-28T17:00:56.932Z INFO @wdio/local-runner: Start worker 0-0 with arg: 
[0-0] 2022-04-28T17:00:57.664Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in firefox - /test/specs/example.e2e.js
[0-0] 2022-04-28T17:00:58.506Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2022-04-28T17:00:58.510Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
[0-0] 2022-04-28T17:00:58.510Z INFO webdriver: DATA {
[0-0]   capabilities: { alwaysMatch: { browserName: 'firefox' }, firstMatch: [ {} ] },
[0-0]   desiredCapabilities: { browserName: 'firefox' }
[0-0] }
[0-0] 2022-04-28T17:02:58.536Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
[0-0] 2022-04-28T17:02:58.537Z INFO webdriver: Retrying 1/3
[0-0] 2022-04-28T17:02:58.537Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
[0-0] 2022-04-28T17:02:58.537Z INFO webdriver: DATA {
[0-0]   capabilities: { alwaysMatch: { browserName: 'firefox' }, firstMatch: [ {} ] },
[0-0]   desiredCapabilities: { browserName: 'firefox' }
[0-0] }
[0-0] 2022-04-28T17:04:58.543Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
[0-0] 2022-04-28T17:04:58.544Z INFO webdriver: Retrying 2/3
[0-0] 2022-04-28T17:04:58.544Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
[0-0] 2022-04-28T17:04:58.544Z INFO webdriver: DATA {
[0-0]   capabilities: { alwaysMatch: { browserName: 'firefox' }, firstMatch: [ {} ] },
[0-0]   desiredCapabilities: { browserName: 'firefox' }
[0-0] }
[0-0] 2022-04-28T17:06:58.550Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
[0-0] 2022-04-28T17:06:58.550Z INFO webdriver: Retrying 3/3
[0-0] 2022-04-28T17:06:58.551Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
[0-0] 2022-04-28T17:06:58.551Z INFO webdriver: DATA {
[0-0]   capabilities: { alwaysMatch: { browserName: 'firefox' }, firstMatch: [ {} ] },
[0-0]   desiredCapabilities: { browserName: 'firefox' }
[0-0] }
[0-0] 2022-04-28T17:08:58.536Z ERROR webdriver: Request failed with status undefined due to TimeoutError: Timeout awaiting 'request' for 120000ms when running "http://localhost:4444/wd/hub/session" with method "POST" and args "{"capabilities":{"alwaysMatch":{"browserName":"firefox"},"firstMatch":[{}]},"desiredCapabilities":{"browserName":"firefox"}}"
[0-0] 2022-04-28T17:08:58.537Z ERROR webdriver: TimeoutError: Timeout awaiting 'request' for 120000ms when running "http://localhost:4444/wd/hub/session" with method "POST" and args "{"capabilities":{"alwaysMatch":{"browserName":"firefox"},"firstMatch":[{}]},"desiredCapabilities":{"browserName":"firefox"}}"
[0-0]     at getTimeoutError (/Users/sam/Desktop/automation/wdio-standalone/node_modules/webdriver/build/utils.js:320:24)
[0-0]     at NodeJSRequest._request (/Users/sam/Desktop/automation/wdio-standalone/node_modules/webdriver/build/request/index.js:147:59)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at startWebDriverSession (/Users/sam/Desktop/automation/wdio-standalone/node_modules/webdriver/build/utils.js:67:20)
[0-0]     at Function.newSession (/Users/sam/Desktop/automation/wdio-standalone/node_modules/webdriver/build/index.js:46:45)
[0-0]     at remote (/Users/sam/Desktop/automation/wdio-standalone/node_modules/webdriverio/build/index.js:77:22)
[0-0]     at Runner._startSession (/Users/sam/Desktop/automation/wdio-standalone/node_modules/@wdio/runner/build/index.js:223:56)
[0-0]     at Runner._initSession (/Users/sam/Desktop/automation/wdio-standalone/node_modules/@wdio/runner/build/index.js:176:25)
[0-0]     at Runner.run (/Users/sam/Desktop/automation/wdio-standalone/node_modules/@wdio/runner/build/index.js:88:19)
[0-0] 2022-04-28T17:08:58.543Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] Timeout awaiting 'request' for 120000ms when running "http://localhost:4444/wd/hub/session" with method "POST" and args "{"capabilities":{"alwaysMatch":{"browserName":"firefox"},"firstMatch":[{}]},"desiredCapabilities":{"browserName":"firefox"}}"
[0-0]     at startWebDriverSession (/Users/sam/Desktop/automation/wdio-standalone/node_modules/webdriver/build/utils.js:72:15)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at Function.newSession (/Users/sam/Desktop/automation/wdio-standalone/node_modules/webdriver/build/index.js:46:45)
[0-0]     at remote (/Users/sam/Desktop/automation/wdio-standalone/node_modules/webdriverio/build/index.js:77:22)
[0-0]     at Runner._startSession (/Users/sam/Desktop/automation/wdio-standalone/node_modules/@wdio/runner/build/index.js:223:56)
[0-0]     at Runner._initSession (/Users/sam/Desktop/automation/wdio-standalone/node_modules/@wdio/runner/build/index.js:176:25)
[0-0]     at Runner.run (/Users/sam/Desktop/automation/wdio-standalone/node_modules/@wdio/runner/build/index.js:88:19)
[0-0] FAILED in firefox - /test/specs/example.e2e.js
2022-04-28T17:08:58.671Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2022-04-28T17:08:58.674Z INFO @wdio/cli:launcher: Run onComplete hook
2022-04-28T17:08:58.675Z INFO @wdio/selenium-standalone-service: shutting down all browsers

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:08:09 

2022-04-28T17:08:58.676Z INFO @wdio/local-runner: Shutting down spawned worker
2022-04-28T17:08:58.933Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2022-04-28T17:08:58.933Z INFO @wdio/local-runner: shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by bhorst-tibco** [comment] 2022-04-29 16:35
I am having this same issue with selenium-standalone-service for both firefox and chrome. The browsers do not even open.

My setup
MacOS Monterey 12.3.1
Chrome Version 101.0.4951.41
 
Using this configuration from wdio tutorial also hits the issue

```
? Where is your automation backend located? On my local machine
? Which framework do you want to use? jasmine
? Do you want to use a compiler? No!
? Where are your test specs located? ./test/specs/**/*.js
? Do you want WebdriverIO to autogenerate some test files? Yes
? Do you want to use page objects (https://martinfowler.com/bliki/PageObject.html)? No
? Which reporter do you want to use? dot
? Do you want to add a plugin to your test setup? 
? Do you want to add a service to your test setup? selenium-standalone
? What is the base url? http://localhost
? Do you want me to run `npm install` Yes
```

The run output:
npx wdio run wdio.conf.js

Execution of 1 workers started at 2022-04-29T16:23:23.171Z

```
2022-04-29T16:23:23.256Z INFO @wdio/cli:launcher: Run onPrepare hook
2022-04-29T16:23:28.071Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-04-29T16:23:28.073Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,wdio.conf.js
[0-0] 2022-04-29T16:23:28.623Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - /test/specs/example.e2e.js
[0-0] 2022-04-29T16:23:28.850Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2022-04-29T16:23:28.855Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
[0-0] 2022-04-29T16:23:28.855Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
[0-0] }
[0-0] 2022-04-29T16:25:28.877Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
```

Additional notes:

- WORKS with chromedriver instead of selenium-standalone, I haven't tried geckodriver.
- Also does NOT work in an ubuntu container that I use to run tests.

**Comment by pmerwin** [comment] 2022-04-29 16:59
Seeing a similar issue trying local muti-remote with selenium stand alaone and firifox:

```
ERROR webdriver: WebDriver Error: Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 400. Message: Argument --remote-debugging-port can't be set via capabilities
Build info: version: '4.0.0', revision: '3a21814679'
```

the error appears to be coming from webdriver and the driver version for geckodriver?

```
Driver info: driver.version: unknown
    at getErrorFromResponseBody (/Users/pmerwin/Projects/Adept/lib-webdriver.io/node_modules/webdriver/build/utils.js:197:12)
    at NodeJSRequest._request (/Users/pmerwin/Projects/Adept/lib-webdriver.io/node_modules/webdriver/build/request/index.js:158:60)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at startWebDriverSession (/Users/pmerwin/Projects/Adept/lib-webdriver.io/node_modules/webdriver/build/utils.js:67:20)
    at Function.newSession (/Users/pmerwin/Projects/Adept/lib-webdriver.io/node_modules/webdriver/build/index.js:46:45)
    at remote (/Users/pmerwin/Projects/Adept/lib-webdriver.io/node_modules/webdriverio/build/index.js:77:22)
    at /Users/pmerwin/Projects/Adept/lib-webdriver.io/node_modules/webdriverio/build/index.js:139:26
    at async Promise.all (index 0)
```

**Comment by pmerwin** [comment] 2022-04-29 17:30
So, I bumped the geckodriver version to 31, the latest, and I am running the latest ff locally with the 4.0 selenium standalone release on one firefox browser, what I am seeing is selenium standalone service logs never start, and there is no geckodriver in node_modules ?

is the issue that sel-standlone is not downloading geckodriver?

https://gist.github.com/pmerwin/d028eac552c9b76ba0d27e6447f36584

**Comment by pmerwin** [comment] 2022-04-29 18:51
as a workaround I found geckodriver service is working fine for me:

https://www.npmjs.com/package/wdio-geckodriver-service

```
{
  "runner": "local",
  "services": [
    [
      "geckodriver",
      {
        "args": [
          "--log=info"
        ],
        "logs": "./data/gecko.log"
      }
    ]
  ],
  "specs": [
    "./test/learn-webapp/skill-video/specs/skill.edit.existing.spec.js"
  ],
  "exclude": [],
  "capabilities": [
    {
      "browserName": "firefox"
    }
  ],
  ```

**Comment by SamuelVinay91** [comment] 2022-04-30 11:44
Hi Team, Any update on this. I am facing the same issue

**Comment by christian-bromann** [comment] 2022-04-30 18:39
@SamuelVinay91 I haven't been able to look into this but would appreciated if someone could help us here.

**Comment by SamuelVinay91** [comment] 2022-05-02 13:32
@propheel - Thank you!! When can we expect this be merged.

**Comment by MadSandwich** [comment] 2022-05-02 13:39
@propheel does your pr fix problem for chrome driver also? In current version of wdio-selenium-standalone-service chrome also can't start and also I find out one strange thing about download url when 'installArgs' are exists in the wdio.config.

wdio.conf example (to be more clear):
`    services: [
        ['selenium-standalone', {
            logPath: './temp',
            installArgs: {
                version: "3.9.1",
                baseURL: "https://selenium-release.storage.googleapis.com",
                drivers: {
                    chrome: {
                        version: "102.0.5005.27",
                        arch: process.arch,
                        baseURL: "https://chromedriver.storage.googleapis.com"
                    }
                }
            },
        }]
    ],`

actual ink - 'https://selenium-release.storage.googleapis.com/selenium-3.9.1/selenium-server-standalone-3.9.1.jar'
expected link - 'https://selenium-release.storage.googleapis.com/3.9/selenium-server-standalone-3.9.1.jar'

**Comment by propheel** [comment] 2022-05-03 11:01
> @propheel - Thank you!! When can we expect this be merged?

I'm not the author of the repo, I don't know how to fix this, I just noticed geckodriver 0.30 works for me ;-)

> @propheel does your pr fix problem for chrome driver also? In current version of wdio-selenium-standalone-service chrome also can't start and also I find out one strange thing about download url when 'installArgs' are exists in the wdio.config.

No idea, I was just fixing Firefox on my end.

> I am doing this:
> 
> ```
> "services": [
>     [
>       "selenium-standalone",
>       {
>         "drivers": {
>           "firefox": {
>             "version": "0.30.0"
>           }
>         }
>       }
>     ]
>   ],
> ```

I believe it should look more like this:
```
"services": [
    [
      "selenium-standalone",
      {
        "drivers": {
          "firefox": "0.30.0"
        }
      }
    ]
  ],
```

**Comment by fillyD** [comment] 2022-05-03 15:53
same as the above for chrome on multi-remote. 

this doesn't seem change induced because i was seeing this all of a sudden with wdio version 7.13.0 before updating it all, also unlikely to do with the outdated browsers or browser/driver version matching.

**Comment by christian-bromann** [comment] 2022-05-04 17:12
I am unable to reproduce this. I ran the following commands:

```sh
$ cd /tmp
$ npm init 8282
# switched to selenium-standalone service in service section
$ cd 8282
# updated capabilities to run Firefox
$ npx wdio
# all tests pass
```

Also adding `user` and `key` to the setup and run these tests on Sauce Labs worked fine. The webdriverio packages I've been using:

```json
"@wdio/cli": "^7.19.7",
"@wdio/local-runner": "^7.19.7",
"@wdio/mocha-framework": "^7.19.7",
"@wdio/selenium-standalone-service": "^7.19.5",
"@wdio/spec-reporter": "^7.19.7"
```

**Comment by christian-bromann** [comment] 2022-05-04 17:14
Can someone provide a reproducible example for this?

**Comment by cbrenner04** [comment] 2022-05-04 17:22
> I am unable to reproduce this. I ran the following commands:
> 
> 
> 
> ```sh
> 
> $ cd /tmp
> 
> $ npm init 8282
> 
> # switched to selenium-standalone service in service section
> 
> $ cd 8282
> 
> # updated capabilities to run Firefox
> 
> $ npx wdio
> 
> # all tests pass
> 
> ```
> 
> 
> 
> Also adding `user` and `key` to the setup and run these tests on Sauce Labs worked fine. The webdriverio packages I've been using:
> 
> 
> 
> ```json
> 
> "@wdio/cli": "^7.19.7",
> 
> "@wdio/local-runner": "^7.19.7",
> 
> "@wdio/mocha-framework": "^7.19.7",
> 
> "@wdio/selenium-standalone-service": "^7.19.5",
> 
> "@wdio/spec-reporter": "^7.19.7"
> 
> ```

What node version did you use? I am having similar issues using node 16.15.0 but with jasmine framework instead of mocha. Potentially related to node version?

**Comment by christian-bromann** [comment] 2022-05-04 17:24
I am on v16.14.2

**Comment by MadSandwich** [comment] 2022-05-04 17:48
@christian-bromann 

1. New project
2. npm init wdio . (cucumber + selenium standalone)
3. Changed capabilities
`    capabilities: [{
        maxInstances: 5,
        browserName: 'firefox',
        acceptInsecureCerts: true
    }],`
4. npm run wdio
5. Attaching logs ([logs.txt](https://github.com/webdriverio/webdriverio/files/8624848/logs.txt))
6. Version of npm & node
![image](https://user-images.githubusercontent.com/57759145/166748346-1722abe0-347a-4f46-ae04-b49529dc29f3.png)

**Comment by christian-bromann** [comment] 2022-05-04 17:55
@MadSandwich what's your OS? Mind creating a minimal reproducible example?

**Comment by MadSandwich** [comment] 2022-05-04 17:57
@christian-bromann Windows 11. Yes, if I can help you, I will try.

**Comment by christian-bromann** [comment] 2022-05-04 18:03
Unfortunately I wasn't able to reproduce it on my Mac M1 machine.

**Comment by MadSandwich** [comment] 2022-05-04 18:13
> Unfortunately I wasn't able to reproduce it on my Mac M1 machine.

Did you try to update node version? (as @cbrenner04 above assumed?) Or maybe it's os specific issue? Do you have ff installed locally?

**Comment by JanMedocs** [comment] 2022-05-04 18:24
> Unfortunately I wasn't able to reproduce it on my Mac M1 machine.

Like @MadSandwich I try to run it on Windows 11.
If I remember right, my college has no problems. She is also running the project on Mac.

**Comment by cbrenner04** [comment] 2022-05-04 20:06
full review of my setup in case it helps. unfortunately, i cannot give an example from what i am working on as it is proprietary however i will try to setup something later that is not.

MBP (Mid 2015)
macOS 12.3.1
node 16.15.0
npm 8.5.5

package.json:
  "@wdio/cli": "~7.19.6",
  "@wdio/dot-reporter": "~7.19.5",
  "@wdio/jasmine-framework": "~7.19.5",
  "@wdio/local-runner": "~7.19.5",
  "@wdio/sauce-service": "~7.19.5",
  "@wdio/selenium-standalone-service": "~7.19.5",
  "@wdio/spec-reporter": "~7.19.5",
  
package-lock.json versions:
  "@wdio/cli": "7.19.6",
  "@wdio/dot-reporter": "7.19.5",
  "@wdio/jasmine-framework": "7.19.5",
  "@wdio/local-runner": "7.19.5",
  "@wdio/sauce-service": "7.19.5",
  "@wdio/selenium-standalone-service": "7.19.5",
  "@wdio/spec-reporter": "7.19.5",
  
assuming there are a couple of packages in there that are not directly related but thought i would just add what i have. i will try to update those patch versions to see if that makes a difference

**Comment by cbrenner04** [comment] 2022-05-04 21:10
Oh jeez.... so as a workaround I had just installed the geckodriver service and the chromedriver service. after seeing the patch updates above, i removed those and updated my versions and removed those services:

    "@wdio/appium-service": "~7.19.5",
    "@wdio/cli": "~7.19.7",
    "@wdio/dot-reporter": "~7.19.7",
    "@wdio/jasmine-framework": "~7.19.7",
    "@wdio/local-runner": "~7.19.7",
    "@wdio/sauce-service": "~7.19.7",
    "@wdio/selenium-standalone-service": "~7.19.5",
    "@wdio/spec-reporter": "~7.19.7",
    
 this seems to be functioning as expected. not 100% what is the reason for it working now, especially since "@wdio/selenium-standalone-service" version is the same. 😬

**Comment by fillyD** [comment] 2022-05-05 00:11
yep works for me too now lol. no further changes made since

**Comment by JanMedocs** [comment] 2022-05-05 06:20
it is sadly not running on my maschine.

**Comment by JanMedocs** [comment] 2022-05-09 06:16
Got a Windows update today, except for this I changed nothing on the project or the drivers. 
But it is running again! 🙌  So thanks from my side for all your work and help!
Hopefully, we will not write again so soon! 😁
Jan from Germany 😄

**Closed** 2022-05-09 13:18 UTC
Labels: Bug 🐛, Reproducible Example Missing
