### ISSUE TITLE
Browser hangs on multiple url() calls

### ISSUE THREAD

**Issue by LKay** [webdriverio/webdriverio#1929] opened 2017-03-15 08:07 UTC
## The problem

This might be related to #1736. I have a simple test to check a flow:
- access some secured route
- app kicks to login page
- login using user/password
- redirect back to requested page
- go to `/logout` url to logout user after test
- check if login page is displayed after logout

The first call for `browser.url()` works fine and all statements are processed. But the following call to `browser.url()` never finished and hangs the browser.

Tested in Chrome and Firefox on OSX.

## Environment

* WebdriverIO version: 3.4.0
* Node.js version: 7.7.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio, sync tests
* Additional wdio packages used (if applicable): mocha framework, selenium standalone service

## Link to Selenium/WebdriverIO logs

- Selenium Logs: https://gist.github.com/LKay/841d64d176d8d989c7e52016e58ebb4a

## Code To Reproduce Issue [ Good To Have ]

```javascript
    describe("Login", function () {

        it("should login and logout", function () {
            browser.url("/login?next=%2Ftest")
            browser.waitForVisible(".page-login")
            browser.setValue("[name=email]", "user")
            browser.setValue("[name=password]", "pass")
            browser.click("button[type=submit]")
            browser.waitUntil(() => {
                const pathname = browser.getPathname()
                console.warn(pathname)
                return pathname as any !== "/login"
            })
            browser.waitForVisible(".layout > aside")
            browser.url("/logout")
            browser.waitForVisible(".page-login")
        })
    })
```

**Comment by christian-bromann** [comment] 2017-03-15 11:20
Can you get somehow the iedriver logs? The code looks ok.

**Comment by LKay** [comment] 2017-03-15 12:02
Not really, unless I run it on some cloud service or bring up a virtual machine with Windows environment.

**Comment by LKay** [comment] 2017-03-15 12:04
I managed to go through the test if wdio is run in async mode and I wrap everything in async/await statements, but still hangs browser in sync mode.

**Comment by christian-bromann** [comment] 2017-03-15 12:54
@LKay without IEDriver logs I will have to close this one as it is most likely an IEDriver issue. I also can't reproduce this without example so there is no way for me to fix anything.

**Closed by christian-bromann** 2017-03-15 12:54 UTC
Labels: Logs Missing

**Comment by LKay** [comment] 2017-03-15 14:51
@christian-bromann Why do you think it might me IEDriver issue? I didn't even run it during tests on non windows machine (I don't think it's even possible on mac or *nix environment).

**Comment by christian-bromann** [comment] 2017-03-15 16:15
Sorry I read the wrong log line, you were running Chrome. Still I need for data from you. Is there any error message? It looks like something times out:
```
16:55:39.889 INFO - Executing: [get: http://localhost:8080/logout])
16:55:43.215 INFO - Executing: [delete session: 7ed664a3-f4bb-4d1d-a6fc-c1716af977d8])
```
So maybe it's worth increasing your mochaOpts.timeout property

**Comment by stevenhadcroft** [comment] 2017-07-13 09:55
Sorry to butt in on this... but I've got something very similar. On a very simple test the 2nd URL call always hangs, resulting in a timeout.

test:

`browser.url(settings.LANDING_URL)`
`browser.setValue('#customer_email', settings.LOGIN_USER_VALID)`
`browser.setValue('#customer_password', settings.LOGIN_PASS_VALID)`
`browser.click("(.//*[@name='commit'])[1]")`
(This navs to a logged in page with a href. Ideally a `.click()` on this href is the preferred method but also hangs. I've tried waitForExists etc at this point, nothing helps. The browser url method is therefore a test, but also hangs)
`browser.url('https://fullwebstore.com/awsonline/on-demand/758f6600-dee2-4884-8999-afc3f228a775')`

log tail:

`[10:35:40]  COMMAND     POST     "/wd/hub/session/3078d63c-126d-4f0c-b25a-dee4d6809e5f/element"`
`[10:35:40]  DATA                {"using":"xpath","value":"(.//*[@name='commit'])[1]"}`
`[10:35:40]  RESULT              {"ELEMENT":"3"}`
`[10:35:40]  COMMAND     POST     "/wd/hub/session/3078d63c-126d-4f0c-b25a-dee4d6809e5f/element/3/click"`
`[10:35:40]  DATA                {}`
`.[10:35:42]  COMMAND    POST     "/wd/hub/session/3078d63c-126d-4f0c-b25a-dee4d6809e5f/url"`
`[10:35:42]  DATA                {"url":"https://fullwebstore.com/awsonline/on-demand/758f6600-dee2-4884-8999-afc3f228a775"}`
`F[10:35:52]  COMMAND    DELETE   "/wd/hub/session/3078d63c-126d-4f0c-b25a-dee4d6809e5f"`
`[10:35:52]  DATA                {}`
`[10:35:42]  DATA                {"url":"https://fullwebstore.com/awsonline/on-demand/758f6600-dee2-4884-8999-afc3f228a775"}`
`F[10:35:52]  COMMAND    DELETE   "/wd/hub/session/3078d63c-126d-4f0c-b25a-dee4d6809e5f"`
`[10:35:52]  DATA                {}`

It is successfully navigating to the second URL but freezes at that point
