### ISSUE TITLE
It's impossible to run a single test

### ISSUE THREAD

**Issue by ania-s** [webdriverio/webdriverio#2832] opened 2018-08-03 07:39 UTC
## The problem

It's impossible to run a single test e.g. based on line number in a specific file
yarn cucumber --spec ./test/features/TEST.feature:5

## Environment

* WebdriverIO version: 4.13.1
* Node.js version:10.6.0
* "wdio": "^2.0.2",
* "wdio-cucumber-framework": "^2.1.0",
* "wdio-firefox-profile-service": "^0.1.1",
* "wdio-junit-reporter": "^0.4.3",
* "wdio-selenium-standalone-service": "0.0.10",

**Comment by BorisOsipov** [comment] 2018-08-03 07:43
Duplicate of https://github.com/webdriverio/wdio-cucumber-framework/issues/78

**Closed by BorisOsipov** 2018-08-03 07:43 UTC

**Comment by bharatsinghoh** [comment] 2022-07-14 15:48
I have commented the code until we enable all the toggles
