### ISSUE TITLE
[📖 Docs]: Adding custom commands: Typings for async ChainablePromiseElement<Promise<Element>>

### ISSUE THREAD

**Issue by iamkenos** [webdriverio/webdriverio#7767] opened 2021-11-30 04:42 UTC
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Missing documentation, Other

## Problem

![image](https://user-images.githubusercontent.com/81152923/143851494-3eecbb0d-cb59-4bdf-a60e-4993009ec25f.png)

- Notice how a custom command (`customCommand()`) is not recognized when element `await $('something')` is not wrapped within a parens - see how `Line 20` works and `Line 19` doesnt.

As of writng, the current docs doesn't say how to work with custom command typings without an additional async call.

## Setup
WebdrverIO async `7.16.6` + TypeScript

## To Reproduce

1. Follow the [Getting Started](https://webdriver.io/docs/gettingstarted) guide, use select typescript as transpiler. include page objects so you have samples to play with.
2. Create a custom command by following [Custom Commands | Adding custom commands](https://webdriver.io/docs/customcommands/#adding-custom-commands)

```ts
// customCommand.ts
export default async function customCommand(this: WebdriverIO.Element) {
  const selector = this.selector;
  // do something here...
};

```

3. Create a `wdio.d.ts`, by following [TypeScript Setup | Adding Custom Commands](https://webdriver.io/docs/typescript/#adding-custom-commands)

```ts
// wdio.d.ts
declare global {
  namespace WebdriverIO {
    interface Element {
      customCommand: () => Promise<void>;
    }
  }
}

export {};
```

4. Update `tsconfig.json`: `"include": ["./**/**.ts"]`

5. On one of the pageobject samples, try chaining `customCommand` after calling a `$(<selector>)` (`Line 19` above on the image above) 

6. Wrap the find element call with parens and added another await outside and it works. (`Line 20` above on the image above) 

## Conclusion

The message is pretty straightforward and makes sense because the `$()` return type is a `ChainablePromiseElement<Promise<Element>>` and not a `Element` (which is what we defined in `wdio.d.ts`)

I'm not sure if there is an easier way to this but was [advised to create a docs issue](https://github.com/webdriverio/webdriverio/discussions/6702#discussioncomment-1717491) so there probably is.

---

P.S - I'm open to contributing and improving the docs, just need to know how to do it first.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by praveendvd** [comment] 2021-12-14 03:02
@christian-bromann  could we adding custom commands to typing be automated ? like create this file during project setup and add commands to wdio.d.ts when ever user creates a new command ? .

**Comment by christian-bromann** [comment] 2021-12-14 08:15
@praveendvd good idea. If this is possible, I am all for it.

**Comment by LeoLetourneur** [comment] 2022-02-24 11:12
I'd like to see how to make it work

**Comment by BlackSwan2019** [comment] 2022-08-03 01:34
Thanks @LeoLetourneur. This allowed TypeScript to be happy with my custom command (verifyIsDisplayed()), e.g. `await SomePageName.someElement.verifyIsDisplayed()`. 

But now the regular old Webdriverio.Element methods are not recognized with the ChainablePromise, e.g. 

`await SomePage.someElement.touchAction('tap')`, as it is now auto-correcting to 

`await (await SomePage.someElement).touchAction('tap')`.

Do I need to extend from normal Webdriver.Element differently to allow the co-existence of my custom type and webdriver's?

**Comment by NaZaRKIN123** [comment] 2022-12-19 15:04
> For anyone looking for a workaround waiting for automatic support, I have 2 `.d.ts` files in my project
> 
> wdio-custom.d.ts (for Element/Browser class augmentation)
> 
> ```ts
> import { BrowserCustoms } from './browser-custom.model';
> import { ElementCustoms } from './element-custom.model';
> 
> declare namespace WebdriverIO {
>   interface Browser extends BrowserCustoms {}
>   interface MultiRemoteBrowser extends BrowserCustoms {}
>   interface Element extends ElementCustoms {}
> }
> ```
> 
> chainable-custom.d.ts (for Chainable class augmentation)
> 
> ```ts
> import 'webdriverio';
> import { ElementCustoms } from './element-custom.model';
> 
> declare module 'webdriverio' {
>   interface ChainablePromiseElement extends ElementCustoms {}
> }
> ```
> 
> where `ElementCustoms` contains my custom methods declaration

With WDIO v8 is stopped working saying 
`Property 'myMethod' does not exist on type 'ChainablePromiseElement<WebdriverIO.Element> | ChainablePromiseElement<...>'.`

**Comment by NaZaRKIN123** [comment] 2023-02-13 13:04
> In #9256 I am working on a rewrite of our TypeScript setup and will validate compatibility with the custom command feature.

Hello @christian-bromann. I see the ticket you mentioned was merged so I updated all WDIO libs today and unfortunately it still doesn't work in WDIO V8.
Is there any change I would need to implement on my side to make it work?

**Comment by Ampire-M** [comment] 2023-02-14 10:21
> 

same issue occurred after migrating to wdio v8

**Comment by meskmanz** [comment] 2023-02-14 10:22
> > In #9256 I am working on a rewrite of our TypeScript setup and will validate compatibility with the custom command feature.
> 
> Hello @christian-bromann. I see the ticket you mentioned was merged so I updated all WDIO libs today and unfortunately it still doesn't work in WDIO V8. Is there any change I would need to implement on my side to make it work?

it doesn't work in WDIO V8 for me either :(

**Comment by angelinafedchenko** [comment] 2023-02-14 10:33
> > In #9256 I am working on a rewrite of our TypeScript setup and will validate compatibility with the custom command feature.
> 
> Hello @christian-bromann. I see the ticket you mentioned was merged so I updated all WDIO libs today and unfortunately it still doesn't work in WDIO V8. Is there any change I would need to implement on my side to make it work?

I've faced the same issue

**Comment by christian-bromann** [comment] 2023-02-14 17:54
> I've faced the same issue

These comments don't help to resolve the issue. If anyone can provide a PR with a fix that would be much appreciated.

**Comment by vparlah** [comment] 2023-02-15 16:34
Hi, somehow I managed to make it works for me. But not sure about the correctness of the solution.
I'm using **wdio:8.2.1** with **ems modules**.

wdio-customs.d.ts
```
/// reference path="./custom-commands.js" />

declare namespace WebdriverIO {
  interface Browser extends BrowserCustoms {}
  interface Element extends ElementCustoms {}
}
```

chainable-customs.d.ts
```
/// reference path="./custom-commands.js" />
import 'webdriverio';

declare module 'webdriverio' {
  interface ChainablePromiseElement extends ElementCustoms {}
}
```

custom-commands.ts
```
interface BrowserCustoms {
  logMessage: (message: string) => Promise<void>;
}

interface ElementCustoms {
  logMessage: (message: string) => Promise<void>;
}
```

**Closed** 2023-02-15 18:31 UTC
Labels: TypeScript

**Comment by christian-bromann** [comment] 2023-02-15 18:32
This should be fixed with above patch, so that users only need to extend the `WebdriverIO.Element` interface as mentioned in the [docs](https://webdriver.io/docs/customcommands#extend-type-definitions). If anyone still experiences this issue please ensure you have read the docs on how to extend the WebdriverIO types and provide a reproducible example.
