### ISSUE TITLE
[🐛 Bug]: Cannot run Firefox /w devtools service & `automationProtocol`

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#10412] opened 2023-05-18 14:11 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

18

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
automationProtocol: 'devtools',
capabilities: [
  {
      "browserName": "firefox"
  }
],
services: ['devtools']
}
```

### What happened?

Automation throws error when starting up.
```shell
TypeError: Cannot read properties of undefined (reading 'type')
    at NetworkHandler.onNetworkRequestWillBeSent (file:///Users/redacted/repos/repo/node_modules/@wdio/devtools-service/build/handler/network.js:64:30)
    at file:///Users/redacted/repos/repo/node_modules/puppeteer-core/lib/esm/third_party/mitt/index.js:1:248
    at Array.map (<anonymous>)
    at Object.emit (file:///Users/redacted/repos/repo/node_modules/puppeteer-core/lib/esm/third_party/mitt/index.js:1:232)
    at CDPSessionImpl.emit (file:///Users/redacted/repos/repo/node_modules/puppeteer-core/src/common/EventEmitter.ts:118:18)
    at CDPSessionImpl.ProtocolSession.session.emit (/Users/redacted/repos/repo/node_modules/lighthouse/lighthouse-core/fraggle-rock/gather/session.js:39:27)
    at CDPSessionImpl._onMessage (file:///Users/redacted/repos/repo/node_modules/puppeteer-core/src/common/Connection.ts:549:12)
    at Connection.onMessage (file:///Users/redacted/repos/repo/node_modules/puppeteer-core/src/common/Connection.ts:324:17)
    at WebSocket.<anonymous> (file:///Users/redacted/repos/repo/node_modules/puppeteer-core/src/common/NodeWebSocketTransport.ts:55:24)
    at callListener (/Users/redacted/repos/repo/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:290:14)
```

### What is your expected behavior?

Should not error and skip listening for events that are not implemented yet like "onNetworkRequestWillBeSent", allows users to retrieve console logs, etc

### How to reproduce the bug.

Run any test.

Also needs to work capturing other events:
```ts
import type { Protocol } from 'devtools-protocol/types/protocol.d.ts'

browser.logs = []

// Listen for the logs
browser.on('Runtime.consoleAPICalled', (params: Protocol.Runtime.ConsoleAPICalledEvent) => {
  browser.logs!.push(params)
})
```

### Relevant log output

```typescript
N\A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2023-05-18 17:08
Thanks for reporting!

This could be due to the fact that the Firefox Devtools protocol is not aligned with the Chrome one. I don't think the title of the issue is correct as Firefox in general works with the Devtools protocol.

Any contributions that resolves the bug are highly appreciated. Don't expect this to be picked up by active contributors as they have their own priorities. If you depend on this bug to be fixed, your contribution is required. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) or join our [Discord](http://discord.webdriver.io/) development server and let us know if you have any questions. Cheers!

**Comment by nextlevelbeard** [comment] 2023-05-18 23:10
>  I don't think the title of the issue is correct as Firefox in general works with the Devtools protocol.

Sadly I think that is indeed the case, even if you are not using any CDP / pupeteer commands or features, a normal test run that would run without the service attached does not run for me.

**Comment by christian-bromann** [comment] 2023-05-19 04:39
Yeah unfortunately there are a lot of moving parts here and giving that nothing is standardised I am not surprised that it is broken now. I haven't been looking into the devtools service at all for a long time, very likely the protocol moved on and broke things.

**Comment by christian-bromann** [comment] 2023-06-12 07:59
I will close this issue as moving forward we will not recommend to use the Devtools protocol for this as capturing logs is part of WebDriver bidi. Here is an example how you can capture it:

_capabilities:_
```
    {
        webSocketUrl: true,
        browserName: 'firefox'
    }
```

_code:_
```ts
await browser.sessionSubscribe({ events: ['log.entryAdded'] })

/**
 * returns: {"method":"log.entryAdded","params":{"type":"console","method":"log","realm":null,"args":[{"type":"string","value":"Hello Bidi"}],"level":"info","text":"Hello Bidi","timestamp":1657282076037}}
 */
browser.on('message', (data) => console.log('received %s', data))

await browser.executeScript('console.log("Hello Bidi")', [])
```

**Closed by christian-bromann** 2023-06-12 07:59 UTC
Labels: Bug 🐛, help wanted

**Comment by christian-bromann** [comment] 2023-06-12 12:50
> Does it work with `devtools` automation protocol or only `webdriver`/`geckodriver`?

Only with `webdriver`

> Also not getting the IDE autocompletion for BiDi functions like `sessionSubscribe`.

I will have to take a look.

> I'd make a case for using 'devtools' automationPtotocol (without service) and still make use of BiDi features, if possible. Not having to run/configure browser drivers and selenium servers is great.

Likely we will move away for allowing to use `devtools` because we can't guarantee that we can execute the automation commands in the same way as WebDriver would do. Running drivers automatically will be easier in the future (basically automatic without you having to care about it).
