### ISSUE TITLE
FireFox: web element in iframe cannot be clicked by using the locator.click() function.

### ISSUE THREAD

**Issue by GineaPig** [webdriverio/webdriverio#3884] opened 2019-04-25 05:52 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.7.11
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Browser name and version:** Firefox 66(64bit)
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/spec reporter, @wdio/selenium-standalone service

**Config of WebdriverIO**

`Selenium standalone serivice, geckodriver is 0.23.0.`

**Describe the bug**

In Firefox, switch into an iframe by switching into the iframe web element. And switch into an iframe inside of this iframe. Locate a web element and has a locator. The web element was found successfully and printed out. `$(locator).click()` has no reflection, and no error. It looks like the `click()` function was executed with no error but it did nothing. In Chrome, it works well.

**To Reproduce**

```js
let iframe = $('iframe[id="testiframe"]');
browser.switchToFrame(iframe);
let iframe2 = $('iframe[id="testiframe2"]');
browser.switchToFrame(iframe2);
$('locator').click();
```

**Expected behavior**

The web element in the iframe should be clicked. But it was not clicked, and the test is passed.

**Other comments: (the locator was printed out as below)**
```js
Element {
   sessionId: 'fb48ff11-9a42-4fa6-97f8-79e3064ee6f1',
   elementId: 'e830941c-9e79-493d-9ca3-9fcf576478e6',
   'element-6066-11e4-a52e-4f735466cecf': 'e830941c-9e79-493d-9ca3-9fcf576478e6',
   selector: '#test"]',
}
```

EDIT: improve formatting by @CrispusDH

**Comment by baruchvlz** [comment] 2019-04-25 10:49
I just ran this on my local machine with Firefox 66 on ArchLinux:

```js
import assert from 'assert'


describe('iframe > iframe > button > click', () => {
    it('should click and display the div', () => {
        browser.url('http://localhost:8080')
        let iframe = browser.$('iframe[id="1"]')

        browser.switchToFrame(iframe)
        let iframe2 = browser.$('iframe[id="2"]')

        browser.switchToFrame(iframe2)
        browser.$('#foo').click()

        assert.equal(browser.$('div').isDisplayed(), true)
    })
})
```

And the test pass and the functionality works as expected.

Do you have a website I can test this on a cloud service using Windows?

**Comment by GineaPig** [comment] 2019-04-26 07:12
@baruchvlz Thank you so much for your reply. But sorry I cannot share the website. The selector.click() function can be used in normal firefox iframe. But for my specific case, it doesn't work.  It looks like the mouse doesn't click on the correct element position.

**Comment by CrispusDH** [comment] 2019-04-26 07:37
@GineaPig  probably, you try to click using wrong locator

**Comment by mgrybyk** [comment] 2019-04-26 08:45
@GineaPig without a reproducible example it is difficult to help here.
Tried locally in Firefox 66.0.3 with geckodriver 0.24
```
        browser.url("https://codepen.io/rcass/pen/MmYwEp")
        const iframe = $("#result")
        iframe.waitForExist()
        browser.switchToFrame(iframe)

        $("input[type=submit]").click()
```
works fine

**Comment by christian-bromann** [comment] 2019-04-30 16:53
Closing as it seems to be not reproducible.

**Closed by christian-bromann** 2019-04-30 16:53 UTC
