### ISSUE TITLE
Windows support - absolute screenshotPath

### ISSUE THREAD

**Issue by iongion** [webdriverio/webdriverio#1130] opened 2016-02-24 13:48 UTC
I just noticed a relation to the screenshotPath, where
```
{
...
screenshotPath: path.join(settings.project.root, 'temp/testing/webdriver/screenshots')
}
```
This meaning that screenshotPath is an absolute path that computes to: ```'W:\Workspace\myproject\temp\testing\webdriver\screenshots'```.

I've noticed the errors by logging the exception caught at line 71 *mkdirp/index.js*:
```
could not { [Error: ENOENT: no such file or directory, mkdir 'W:\Workspace\myproject\W:']
```

So screenshotPath is processed later and somehow mkdirp tries to create **W:\Workspace\myproject\W:**

Noticed the **W:** at the end of the path, that one is invalid, then I see in webdriverio.js how path is computed:

```
var screenshotPath = options.screenshotPath[0] === '/' ? options.screenshotPath : _path2['default'].join(process.cwd(), options.screenshotPath);
```
So absolute paths are detected as starting with '/' which on windows is not the case because paths start with drive letter (C:, W:..)
Because of this it defaults to a relative path to which it appends the user provided absolute path which is in the end an invalid path.

If I change to a relative path:
```
"screenshotPath": "temp/testing/webdriver/screenshots"
```

Then the error becomes:
```
[11:09:43] TypeError in plugin 'gulp-mocha'
Message:
    Cannot read property 'info' of undefined
Details:
    domain: [object Object]
    domainThrown: true
Stack:
TypeError: Cannot read property 'info' of undefined
    at Object.reject (W:\Workspace\myproject\node_modules\webdriverio\build\lib\webdriverio.js:287:20)
    at Object.callErrorHandlerAndReject (W:\Workspace\myproject\node_modules\webdriverio\build\lib\webdriverio.js:217:27)
    at W:\Workspace\myproject\node_modules\webdriverio\build\lib\webdriverio.js:192:58
    at run (W:\Workspace\myproject\node_modules\webdriverio\node_modules\core-js\library\modules\es6.promise.js:104:47)
    at W:\Workspace\myproject\node_modules\webdriverio\node_modules\core-js\library\modules\es6.promise.js:115:28
    at flush (W:\Workspace\myproject\node_modules\webdriverio\node_modules\core-js\library\modules\$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickDomainCallback (node.js:422:13)
```

Investigating further on that line:
```
this.logger.info('\tSaved screenshot: ' + fileName);
```
So there is no logger  - so this is looks like a bug

Commenting it out shows that ```this.emit``` is also not existing
Commenting that out more:

```
Message:
    An element could not be located on the page using the given search parameters.
Details:
    type: NoSuchElement
    domain: [object Object]
    domainThrown: true
Stack:
NoSuchElement: An element could not be located on the page using the given search parameters.
    at screenshot() - W:\Workspace\myproject\node_modules\webdriverio\build\lib\commands\saveScreenshot.js:40:17
    at saveScreenshot("W:\Workspace\myproject\temp\testing\webdriver\screenshots\ERROR_chrome_2016-02-24T10-15-38.083Z.png") - W:\Workspace\myproject\node_modules\webdriverio\build\lib\helpers\safeExecute.js:28:24
```

The last error I am unable to solve

**Comment by christian-bromann** [comment] 2016-04-04 23:23
Fixed issue. Will be released with the next version `v4.0.6`. The bottom issue is a duplicate of #1180.

**Closed** 2016-04-04 23:22 UTC
Labels: Bug
