### ISSUE TITLE
WebdriverIO v7 local-runner is opening chromedriver in small resolution

### ISSUE THREAD

**Issue by navasdavid** [webdriverio/webdriverio#6465] opened 2021-02-17 16:58 UTC
**Environment:**
 - **WebdriverIO version:** 7.0.5
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 14.15.1
 - **NPM version:** 6.14.8
 - **Browser name and version:** chrome 88.0.4324.182
 - **Platform name and version:** Mac Big Sur 11.2.1
 - **Additional wdio packages used (if applicable):** 
 - ` "dependencies": {
    "@babel/cli": "^7.12.16",
    "@babel/core": "^7.12.16",
    "@babel/plugin-proposal-export-default-from": "^7.12.13",
    "@babel/preset-env": "^7.12.16",
    "@babel/register": "^7.12.13",
    "@cucumber/cucumber": "^7.0.0",
    "@wdio/cli": "^7.0.5",
    "@wdio/config": "^7.0.4",
    "@wdio/cucumber-framework": "^7.0.6",
    "@wdio/local-runner": "^7.0.5",
    "@wdio/sauce-service": "^7.0.5",
    "@wdio/selenium-standalone-service": "^7.0.4",
    "@wdio/spec-reporter": "^7.0.4",
    "@wdio/static-server-service": "^7.0.4",
    "@wdio/sync": "^7.0.5",
    "chromedriver": "^88.0.0",
    "eslint": "^7.20.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-wdio": "^7.0.0",
    "http-server": "^0.12.3",
    "npm-run-all": "^4.1.5",
    "wdio-chromedriver-service": "^6.0.4",
    "webdriverio": "^7.0.5"
  }`

**Config of WebdriverIO**
` capabilities: [
        {
          browserName: 'chrome',
}]`
**Describe the bug**
The chrome driver is opened on local without filling all the window space (see attached image)
![3B872850-1E1A-44D9-AC9B-86C676FCFD1B](https://user-images.githubusercontent.com/29601780/108238952-b64d4280-7149-11eb-9660-b8f77674361f.jpeg)
. So the resolution is too small, and it is causing a fail in my tests

**To Reproduce**
Run wdio on local: yarn run wdio wdio.local.conf.js in my case

**Expected behavior**
In webdriverIO6 I used  "@wdio/local-runner": "^6.12.0", and the chromedriver was opened filling all the window 

See attached image with the error

**Comment by christian-bromann** [comment] 2021-02-18 13:23
Duplicate of #6471

**Closed by christian-bromann** 2021-02-18 13:23 UTC
