### ISSUE TITLE
[🐛 Bug]: Cannot run Cucumber scenario by line number

### ISSUE THREAD

**Issue by viktor-silakov** [webdriverio/webdriverio#9742] opened 2023-02-10 16:18 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.2.3

### Node.js Version

v14.20.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{          
            maxInstances: 1,
            browserName: 'chrome',
          
},
```

### What happened?

I cannot run the particular scenario using the line number in `--spec` command line option e.g.: 
```
wdio wdio.BUILD.conf.ts  --spec src/features/attribute.feature:8

```
Wdio runs the **whole** feature.

### What is your expected behavior?

I need to run only one scenario (which starts by certain line number)

### How to reproduce the bug.

This is reproduced on the last [wdio cucumber boilerplate project](https://github.com/webdriverio/cucumber-boilerplate) with default settings
```
wdio wdio.BUILD.conf.ts  --spec src/features/attribute.feature:8

```
PS: this perfectly works with 6.x version

### Relevant log output

```typescript
Execution of 1 workers started at 2023-02-10T16:16:05.645Z

[0-0] RUNNING in chrome - file:///src/features/attribute.feature
[0-0] PASSED in chrome - file:///src/features/attribute.feature

 "spec" Reporter:
------------------------------------------------------------------
[chrome 110.0.5481.77 mac os x #0-0] Running: chrome (v110.0.5481.77) on mac os x
[chrome 110.0.5481.77 mac os x #0-0] Session ID: b503e4f031765f1f0d0dfaf082c31e17
[chrome 110.0.5481.77 mac os x #0-0]
[chrome 110.0.5481.77 mac os x #0-0] » /src/features/attribute.feature
[chrome 110.0.5481.77 mac os x #0-0] Test the attributes of a given element
[chrome 110.0.5481.77 mac os x #0-0] As a developer
[chrome 110.0.5481.77 mac os x #0-0] I want to be able to test the attributes of a given element
[chrome 110.0.5481.77 mac os x #0-0]
[chrome 110.0.5481.77 mac os x #0-0] The attribute "role" of a element should be "note"
[chrome 110.0.5481.77 mac os x #0-0]    ✓ Given I open the site "/"
[chrome 110.0.5481.77 mac os x #0-0]    ✓ Then I expect that the attribute "role" from element "#attributeComparison" is "note"
[chrome 110.0.5481.77 mac os x #0-0]
[chrome 110.0.5481.77 mac os x #0-0] The attribute "role" of a element should not be "main"
[chrome 110.0.5481.77 mac os x #0-0]    ✓ Given I open the site "/"
[chrome 110.0.5481.77 mac os x #0-0]    ✓ Then I expect that the attribute "role" from element "#attributeComparison" is not "main"
[chrome 110.0.5481.77 mac os x #0-0]
[chrome 110.0.5481.77 mac os x #0-0] The CSS attribute "color" of a element should be "red"
[chrome 110.0.5481.77 mac os x #0-0]    ✓ Given I open the site "/"
[chrome 110.0.5481.77 mac os x #0-0]    ✓ Then I expect that the css attribute "color" from element "#cssAttributeComparison" is "rgba(255,0,0,1)"
[chrome 110.0.5481.77 mac os x #0-0]
[chrome 110.0.5481.77 mac os x #0-0] The CSS attribute "color" of a element should not be "blue"
[chrome 110.0.5481.77 mac os x #0-0]    ✓ Given I open the site "/"
[chrome 110.0.5481.77 mac os x #0-0]    ✓ Then I expect that the css attribute "color" from element "#cssAttributeComparison" is not " rgba(0,255,0,1)"
[chrome 110.0.5481.77 mac os x #0-0]
[chrome 110.0.5481.77 mac os x #0-0] The (missing) CSS attribute "border" of a element should not be "0"
[chrome 110.0.5481.77 mac os x #0-0]    ✓ Given I open the site "/"
[chrome 110.0.5481.77 mac os x #0-0]    ✓ Then I expect that the css attribute "border" from element "#cssAttributeComparison" is not "0"
[chrome 110.0.5481.77 mac os x #0-0]
[chrome 110.0.5481.77 mac os x #0-0] The CSS attribute "font-weight" of a element should be "bold"
[chrome 110.0.5481.77 mac os x #0-0]    ✓ Given I open the site "/"
[chrome 110.0.5481.77 mac os x #0-0]    ✓ Then I expect that the css attribute "font-weight" from element "#cssAttributeComparison" is "700"
[chrome 110.0.5481.77 mac os x #0-0]
[chrome 110.0.5481.77 mac os x #0-0] 12 passing (10.5s)


Spec Files:      1 passed, 1 total (100% completed) in 00:00:21
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2023-02-10 17:04
Thanks for reporting!

I would start looking into the [`ConfigParser`](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-config/src/lib/ConfigParser.ts) and see why the line number was not picked up. I assumed we had tests for this but it seems this is missing and should be added.

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by esaari** [comment] 2023-02-11 16:42
This is a duplicate of https://github.com/webdriverio/webdriverio/issues/7735

Other contributors have done some root cause analysis already and there's a proposed solution discussed here: https://github.com/webdriverio/webdriverio/pull/8432#issuecomment-1419216928

**Comment by christian-bromann** [comment] 2023-02-14 21:33
Let's continue this conversation in #7735

**Closed by christian-bromann** 2023-02-14 21:33 UTC
Labels: Bug 🐛, help wanted, good first pick
