### ISSUE TITLE
[📖 Docs]: `beforeScenario` hook documentation is missing a parameter

### ISSUE THREAD

**Issue by mekalag** [webdriverio/webdriverio#7723] opened 2021-11-20 15:30 UTC
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Missing documentation

### Description of the improvement / report

Hi, I am trying to use tags in webdriverio hooks, So I want to run beforeScenario or afterScenario for only particular tag(s)
I see no documentation for it. 

I tried something like this `beforeScenario:({tags: '@ssoScenario'}  function (scenario) {`   with the help of some google search but this does not work. 
no matter what tag is specified it works for all scenarios. Tag is not considered. 

also when I console.log(scenario) it prints the file relative path and not the scenario name. 

I want to know the correct format to use tags with the webdriverio cucumberjs hooks. Please provide some examples 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment] 2021-11-22 08:34
WebdriverIO hooks might not know anything about any Cucumber tags that got applied. This is rather a missing feature than missing documentation. We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by nextlevelbeard** [comment] 2021-11-22 09:47
`beforeScenario` hook has a `world` parameter with properties `gherkinDocument` and `pickle` that should have the tags for the entire feature and the scenario in question, respectively.

```js
beforeScenario({ gherkinDocument, pickle }, context){
  console.log("Document: " + JSON.stringify(gherkinDocument));
  console.log("Scenario: " + JSON.stringify(pickle));
  
  if(!pickle.tags.includes("@myTag")){
    return;
  }
}
```

**Comment by christian-bromann** [comment] 2021-11-22 10:12
Thank you @nextlevelbeard .. closing the issue then.

**Comment by nextlevelbeard** [comment] 2021-11-22 11:54
Looking at the docs on the hooks, it seems they don't make it clear @christian-bromann .
Maybe we could keep it open and enhance them?

**Comment by christian-bromann** [comment] 2021-11-22 12:34
> Maybe we could keep it open and enhance them?

Mind making a PR with a suggestion? I don't have much usage experience with Cucumber so I am not an ideal person to do this.

**Comment by mekalag** [comment] 2021-11-22 15:36
@nextlevelbeard I tried with 
```
    beforeScenario({ gherkinDocument, pickle }, context) {
        console.log("Document: " + JSON.stringify(gherkinDocument));
        console.log("Scenario: " + JSON.stringify(pickle));
        if(pickle.tags.includes("@ssoScenario")){
            console.log("inside");
        }
```
it throws : 
Document: undefined
Scenario: undefined
Basically it's not working. 

So whatever you suggested, is different from what webdriverio hooks format is. 
This is how webdriverio beforeScenario hook is 

```    //beforeScenario: function (scenario) {
    //     //do your stuff
    //},
    ```
Can you please provide some workaround with the format suggested in webdriverio ?

**Comment by christian-bromann** [comment] 2021-11-22 15:38
> So whatever you suggested, is different from what webdriverio hooks format is.

Not sure what you mean here, but have you tried to inspect the arguments you get in this hook?

**Comment by mekalag** [comment] 2021-11-22 15:41
> > So whatever you suggested, is different from what webdriverio hooks format is.
> 
> Not sure what you mean here, but have you tried to inspect the arguments you get in this hook?

<img width="938" alt="Screenshot 2021-11-22 at 16 40 04" src="https://user-images.githubusercontent.com/11612209/142890702-c3cd1309-8e4b-457a-84e4-eb5c8b3ac527.png">
please look at the screenshot how beforeScenario is defined in runner file. 

Yes, I have inspected the arguments its undefined

**Comment by christian-bromann** [comment] 2021-11-22 15:42
The comment you have circled is for `beforeStep` not `beforeScenario` the description is always above the method.

**Comment by mekalag** [comment] 2021-11-22 15:44
> The comment you have circled is for `beforeStep` not `beforeScenario` the description is always above the method.

I basically wanted to highlight the syntax of `beforeScenario: function (world, context) {` But what @nextlevelbeard provide is like a function `beforeScenario({ gherkinDocument, pickle }, context) {` 

I dont know if this is ok or not, but atleast when I tried and inspected the arguments it shows undefined

**Comment by christian-bromann** [comment] 2021-11-22 16:05
You can also write it this way:
```js
beforeScenario(world, context){
  console.log("Document: " + JSON.stringify(world.gherkinDocument));
  console.log("Scenario: " + JSON.stringify(world.pickle));
  
  if(!pickle.tags.includes("@myTag")){
    return;
  }
}
```

Also make sure you use latest WebdriverIO.

**Comment by mekalag** [comment] 2021-11-22 16:34
Yeah I am using latest webdriverio. 
`world.gherkinDocument` and `world.pickle` arguments are undefined. 

Where as context argument under the path context.document.feature.children[2].tags[0].name  has scenario name. 
I have attached screenshot for the same. 
  
![Screenshot 2021-11-22 at 17 21 57](https://user-images.githubusercontent.com/11612209/142899437-80271fe2-820b-4603-84f1-ea7b5cd7ca3c.png)

But I wish this simple `if block` worked 
```
if(!world.pickle.tags.includes("@myTag")){
    return;
  }
  ```
  since world.pickle itself is undefined, it never enters into if block. Kindly suggest some simple way to check my tag

**Comment by nextlevelbeard** [comment] 2021-11-22 17:04
> Yeah I am using latest webdriverio. `world.gherkinDocument` and `world.pickle` arguments are undefined.

If you look at this, you'll see the `gherkinDocument` in the context parameter
![image](https://user-images.githubusercontent.com/3788982/142903543-9135c543-64c4-44cf-abba-dd687a713ac0.png)

What's happening is that there is a missing first parameter `uri`.

If you declare the function like this, it should work.

```js
beforeScenario(uri, world, context){
  console.log("Document: " + JSON.stringify(world.gherkinDocument));
  console.log("Scenario: " + JSON.stringify(world.pickle));

  // ...
}
```

**Comment by mekalag** [comment] 2021-11-22 17:07
There are two parameters `world` and `context` in beforeScenario(world, context) { 
So in:
        console.log("Document: " + JSON.stringify(world.gherkinDocument));
        console.log("Scenario: " + JSON.stringify(world.pickle)); 
you can see undefined in the screenshot just right side of each line.
and in  `context` parameter. Path to mytag `@ssoScenario` is  `context.document.feature.children[2].tags[0].name` 
<<attaching screenshot once again for clarity>>
![Screenshot 2021-11-22 at 18 05 00](https://user-images.githubusercontent.com/11612209/142904437-cb0970bf-9c00-48e5-ae04-0efa081dd34d.png)

**Comment by mekalag** [comment] 2021-11-22 17:40
@nextlevelbeard @christian-bromann 
 
```    beforeScenario(uri, world, context) {
        if (context.tags[0].name.includes("@ssoScenario")) {
            console.log('###');
        }
    },
    ```
    with this it works. So world parameters has complete details of feature file, whereas context parameter has details about the current scenario. I could check if my scenario includes tag with above code. 
    
    This I can work with, but if someone comes up with simpler solution to match the tag in beforeScenario hook would be really great.
    
    We work with lot of tags (most of the times each scenario has more than one tag) and steps in our project. Having simpler solution would make it neat and easier to use.

Now I am in a study phase of webdriverIO, I have it to demo my team. Everything so far looked cool to me, except running scenarios based on tags.

**Comment by christian-bromann** [comment] 2021-11-22 17:48
@nextlevelbeard does this mean the docs are wrong [here](https://webdriver.io/docs/options#beforescenario)?

**Comment by mekalag** [comment] 2021-11-22 19:30
Definitely we need better documentation about hooks.  In the runner file beforeScenario hook is defined as `beforeScenario: function (scenario) {` where as finally we landed up into `beforeScenario(uri, world, context) {` I am sure someone like will never know this from the documentation and very time consuming to write a piece of working code. 

Along with the update to the documentation, I also suggest to improve webdriverIO in handling tags more efficiently and in a simpler way. In protractor its simple for ex: 

```
Before({
  tags: '@smartFeature or @fetchFeature'  // for smartrule microservice
}, () => {
 //write code here
})

```
so something like this, will be great addition to webdriverIO. 
Thanks for your time guys!

**Comment by christian-bromann** [comment] 2021-11-22 20:20
I will re-open to investigate the misleading docs on hooks.

> I also suggest to improve webdriverIO in handling tags more efficiently and in a simpler way

I don't think
```js
if(!world.pickle.tags.includes("@myTag")){
    return;
  }
```
is complicated to write. I am not sure if changing the interface for Cucumber hooks makes things simpler.

> Definitely we need better documentation about hooks.

Please suggest improvements, ideally through a PR.

**Comment by mekalag** [comment] 2021-11-22 21:31
@christian-bromann 

```
if(!world.pickle.tags.includes("@myTag")){
    return;
  }
```
atleast if this works it fine, but this is not working when I tried. As I mentioned above this `if (context.tags[0].name.includes("@ssoScenario")) {` is working. Atleast please take a look to fix 

```
if(!world.pickle.tags.includes("@myTag")){
    return;
  }
```

**Comment by christian-bromann** [comment] 2023-04-29 19:42
> Atleast please take a look to fix

Can you suggest what needs to be fixed?

**Comment by christian-bromann** [comment] 2023-06-12 09:59
Closing due to inactivity.

**Closed by christian-bromann** 2023-06-12 09:59 UTC
Labels: wdio-cucumber-framework, Information Missing

**Comment by tibioneh** [comment] 2024-03-07 09:55
The beforeScenario and most other Cucumber hooks are still not working, not even if using `beforeScenario(uri, world, context) {` - why wasn't this addressed yet?

**Comment by christian-bromann** [comment] 2024-03-07 16:44
> why wasn't this addressed yet?

This was addressed and we have tests for these hooks to be executed. Please provide a reproducible example if you experience something not working for you.

**Comment by tibioneh** [comment] 2024-03-08 06:25
https://github.com/serenity-js/serenity-js-cucumber-webdriverio-template/blob/main/wdio.conf.ts
- nothing in the `Cucumber Hooks` section works

**Comment by christian-bromann** [comment] 2024-03-08 18:58
You might want to raise an issue with the Serenity project then as it uses WebdriverIO under the hood.
