### ISSUE TITLE
Retry arguments are no longer working for Mocha and Jasmine

### ISSUE THREAD

**Issue by erwinheitzman** [webdriverio/webdriverio#7367] opened 2021-08-30 13:44 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.11.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** v14.17.4
 - **NPM version:** 6.14.14

**Config of WebdriverIO**
Default config created using the CLI by selecting either Mocha or Jasmine, combined with the CDP and TypeScript.

```js
  "@wdio/cli": "7.11.1",
  "@wdio/jasmine-framework": "^7.11.1",
  "@wdio/local-runner": "^7.11.1",
  "@wdio/spec-reporter": "^7.10.1",
  "ts-node": "^10.2.1",
  "typescript": "^4.4.2"
```

**Describe the bug**
#7339 tried to fix an issue where Jasmine did not play nicely with the retry argument, however the types where not updated, resulting in a TypeScript error when passing both the `timeout` and `retries` argument to a test function.
However, for both Mocha and Jasmine, the whole `retries` argument no longer seems to work at all.

**To Reproduce**

Generate a new project using `npx wdio path/to/create/project`
Select the same config(s) as mentioned above.

Add the following to the `wdio.conf.ts` verify the behavior:
```js
    afterTest: function(test, context, { error, result, duration, passed, retries }) {
        console.log('foo!');
    },
```

When using Jasmine, change the test content to:
```js
describe('My Login application', () => {
    it('should login with valid credentials', async () => {
        await LoginPage.open();
        expect('false').toEqual('true')
    }, 10000, 4); // complains about the types
});
```

When using Mocha, change the test content to:
```js
describe('My Login application', () => {
    it('should login with valid credentials', async () => {
        await LoginPage.open();
        expect('false').toEqual('true')
    }, 4);
});
```

**Expected behavior**
I expect the testrunner to run the failing test a total number of 5 times when `retries` is set to 4 and I expect it to retry a total of 4 times (1 initial failure + 4 retries).

I expect our types to be updated so that it does not complain when both the `timeout` and `retries` are added when using Jasmine.

**Comment by christian-bromann** [comment] 2021-08-31 09:52
> When using Jasmine, change the test content to:

Fixed in #7371

> When using Mocha, change the test content to:

Not sure what is wrong here but if I run:
```js
    it('should have the right title', () => {
        console.log('RUN ME')
        throw new Error('foo')
    }, 4)
```
I get 5 `console.log` messages as you would expect. Are you also saying that the Mocha types are wrong?

**Comment by erwinheitzman** [comment] 2021-09-02 07:22
What if you run my actual example instead of manually throwing an error?

**Comment by christian-bromann** [comment] 2021-09-06 07:26
Also with the following spec:
```js
const LoginPage = require('../pageobjects/login.page');
const SecurePage = require('../pageobjects/secure.page');

describe('My Login application', () => {
    it('should login with valid credentials', async () => {
        await LoginPage.open();
        expect('false').toEqual('true')
    }, 4);
});
```

I am not able to reproduce this. When I run, it successfully retries 4 times.

I will close this. If anyone encounters this issue, please raise a new issue with a reproducible example. Thanks!

**Closed by christian-bromann** 2021-09-06 07:26 UTC
Labels: help wanted, good first pick
