### ISSUE TITLE
[🐛 Bug]: onComplete Hook Provides an exit code of 1 When Test Suite Passes When Using Cucumber Tag Expression Due to Error in onRunnerStart hook of wdio-video-reporter

### ISSUE THREAD

**Issue by alexburkowskypolysign** [webdriverio/webdriverio#9440] opened 2022-12-23 03:27 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.0.13

### Node.js Version

18.12.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [
    {
      maxInstances: 5,
      browserName: 'chrome',
      acceptInsecureCerts: true,
      'goog:chromeOptions': {
        prefs: {
          directory_upgrade: true,
          prompt_for_download: false,
          'download.default_directory': global.downloadDir,
        },
        args: [
          '--allow-insecure-localhost',
          '--disable-dev-shm-usage',
          '--enable-logging',
          '--headless',
          '--no-sandbox',
          '--use-fake-ui-for-media-stream',
          '--use-fake-device-for-media-stream',
          '--v=1',
          '--window-size=1200,900',
        ],
      },
    },
  ],
```

### What happened?
I am running the latest wdio version and plugins with an ESM setup.
I am running a limited set of tests with the following command: `wdio run wdio.conf.ts --baseUrl https://localhost:8080 --cucumberOpts.tagExpression @organization`
My test suite passes but I get an exitCode of 1 in the onComplete hook which cause node to exit with an error:
<img width="700" alt="Screenshot 2022-12-22 at 7 21 08 PM" src="https://user-images.githubusercontent.com/89814961/209264970-3378d95a-69f8-4f68-a938-b608947e95ba.png">

I am able to get the proper exit by checking the results and manually exiting the process with proper exit code as a workaround using the `onComplete` code below:
```ts
  onComplete(wdioExitCode, _config, _capabilities, results) {
    const generation = allure(['generate', 'allure-results', '--clean'])

    return new Promise<void>((resolve, reject) => {
      const reportError = new Error('Could not generate Allure report')

      const generationTimeout = setTimeout(() => {
        console.log('Allure generation timeout')
        return reject(reportError)
      }, 60 * 1000)

      generation.on('exit', async (allureExitCode: number) => {
        clearTimeout(generationTimeout)
        if (allureExitCode !== 0) {
          console.log(`Error in allure generation: exit code=${allureExitCode}`)
          return reject(reportError)
        }

        console.log(
          'Wdio Test Suite Exit Code: ',
          wdioExitCode,
          'Allure Exit Code: ',
          allureExitCode,
        )

        fs.readdirSync('./allure-results').forEach(fileName => {
          if (fileName.endsWith('.xml')) {
            console.log(`copying xml data file to allure-report: ${fileName}`)
            fs.copyFileSync(
              `./allure-results/${fileName}`,
              `./allure-report/data/${fileName}`,
            )
          }
        })
        // Do not change this console.log string, used for detection for kubectl cp in pipeline
        // Produce console output prior to sleep to allow time for copying.
        console.log('Allure Report Generation Success')
        await sleep(5 * 1000)

        console.log('# of Failed tests -> ', results.failed)
        if (results.failed > 0) {
          return reject(new Error(`Test Suite Has ${results.failed} Failures`))
        }
        return resolve(process.exit(0))
      })
    })
  },
```
I have also confirmed that all other hooks provide expected results and the cucumber hooks present passing results.

### What is your expected behavior?

The `onComplete` exit code is 0 when the suite passes

### How to reproduce the bug.

See above for output

### Relevant log output

```typescript
See above
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by alexburkowskypolysign** [comment] 2022-12-23 06:10
To add some color, using the `onWorkerEnd` hook it seems like all the workers are exiting with a code of 1 other than (I think) the worker reserved for allure:
<img width="551" alt="Screenshot 2022-12-22 at 10 09 06 PM" src="https://user-images.githubusercontent.com/89814961/209281691-9d4aeece-9b43-448c-a1ba-32d5b0a77aa6.png">

**Comment by alexburkowskypolysign** [comment] 2022-12-23 06:14
To add some color it looks like all the works that are reserved for skipped tests exit with a code of 1:

```ts
  onWorkerEnd(cid, exitCode, specs) {
    console.log('cid: ', cid, 'exit: ', exitCode, 'specs: ', specs)
  },
```
<img width="751" alt="Screenshot 2022-12-22 at 10 12 51 PM" src="https://user-images.githubusercontent.com/89814961/209282128-5a868f9c-c8d7-4357-8780-ae61630c20e4.png">

**Comment by alexburkowskypolysign** [comment] 2022-12-23 06:15
So I think this is an issue of if any test is skipped the overall exit code is 1. Which was not the behavior on v7.

**Comment by alexburkowskypolysign** [comment] 2022-12-24 02:43
@christian-bromann this commit and the subsequent additions are the problem: https://github.com/webdriverio/webdriverio/commit/c275aa3d040b91014ebb858e19ee2a879896532c

My issue is an error thats risen from the `wdio-video-reporter` in the `onRunnerStart` method it errors out when it looks for a `sessionId`: https://github.com/webdriverio-community/wdio-video-reporter/blob/9f02d2f4bf134bd5fb1a2603056fdabb4853fdf2/src/index.js#L79

Prior to this commit, there was no 'runner:start' emission if initialization failed, so the `onRunnerStart` method would not be called, only the `onRunnerEnd` method. 

What was the justification for adding this block?

**Comment by christian-bromann** [comment] 2022-12-24 09:55
Thanks for investigating the root cause of this issue.

> My issue is an error thats risen from the `wdio-video-reporter` in the `onRunnerStart` method it errors out when it looks for a `sessionId` since it isnt set in the `_shutdown` method

There hasn't been any policy saying that `onRunnerStart` requires a session to be successfully spawned up. The decision for adding the onRunnerStart event seemed reasonable due to the context of the bug that got fixed with it. This seems to be a downstream bug in the video reporter.

> What was the justification for adding this block?

To fix the following bug: https://github.com/webdriverio/webdriverio/issues/8307

> Also it seems like all the logs are being swallowed. I have `debug` set as the logLevel and this is an `error` level log, but I received no output in the terminal. I wouldve caught this much earlier if I had that logging :)

I am not sure what has caused the logs to be swallowed. Any pointers/reproducible example would be appreciated to debug and fix this.

What do you suggest as next step?

**Comment by alexburkowskypolysign** [comment] 2022-12-24 18:52
@christian-bromann as far as the fix in `wdio-video-reporter` its relatively simple. Just return early if there isnt a `sessionId`  or found `runnerInstance`. I can put up a PR for that and tag you if that sounds reasonable.

As for the logs issue, I will have to dig into that some more. The specific error that I would like to show up in the terminal is here https://github.com/webdriverio/webdriverio/blob/cfb83d28a3d28d17de8463d4e823078b7ac3c3ec/packages/wdio-local-runner/src/run.ts#L43. As you can see in my screenshot it is not present. Ill dig a bit after I address the `wdio-video-reporter` PR

**Comment by christian-bromann** [comment] 2022-12-24 22:29
Thanks for raising the PR. I merged and released the patch. I will go ahead and close this. Let's create new issue for other items identified in this thread. Thanks for the contribution and merry Christmas!

**Closed by christian-bromann** 2022-12-24 22:29 UTC
Labels: Bug 🐛, help wanted
