### ISSUE TITLE
[🐛 Bug]: Chaining does not work when using `getParentElement()` with `previousElement()` together in the same line

### ISSUE THREAD

**Issue by mayankshukla94** [webdriverio/webdriverio#8008] opened 2022-02-14 08:25 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.13

### Node.js Version

14.16.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [
    {
      // maxInstances can get overwritten per capability. So if you have an in-house Selenium
      // grid with only 5 firefox instances available you can make sure that not more than
      // 5 instances get started at a time.
      maxInstances: 1,
      //
      browserName: 'chrome',
      acceptInsecureCerts: true,
      // If outputDir is provided WebdriverIO can capture driver session logs
      // it is possible to configure which logTypes to include/exclude.
      // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
      // excludeDriverLogs: ['bugreport', 'server'],
    },
  ],
```

### What happened?

I have a DOM where the HTML is in below format:

```
<div class="previous">
    <p>One</p>
    <p>Two</p>
    <p>Three</p>
</div>
<div class="parent">
    <p>Four</p>
    <p>Five</p>
    <p>Six</p>
</div>
```

Now, I using xpath `//*[text()='Five']` I'm trying to fetch the parent element having class `parent` and then accessing previous element having class `previous`.
```
const fiveElement = //*[text()='Five'];
const previous = await fiveElement.getParentElement().getPreviousElement();
```

Here, I'm getting error that says `getPreviousElement()` is not a function. However, it works absolutely fine when using multiple `await`

```
const fiveElement = //*[text()='Five'];
const previous = await (await fiveElement.getParentElement()).getPreviousElement();
```

### Note: 
When trying to access child node of previous element, then for that again I have to use `await`

```
const previous = await (await (await fiveElement.getParentElement()).getPreviousElement()).$("//*[text()='Two']")
```

### What is your expected behavior?

As WebdriverIO returns a promise compatible object, then below codes should work:

```
const fiveElement = //*[text()='Five'];
const previous = await (await fiveElement.getParentElement()).getPreviousElement();
```
AND

```
const fiveElement = //*[text()='Five'];
const previous = await (await fiveElement.getParentElement()).getPreviousElement().$("//*[text()='Two']");
```

### How to reproduce the bug.

To reproduce a bug, create a DOM having below HTML nodes:

```
<div class="previous">
    <p>One</p>
    <p>Two</p>
    <p>Three</p>
</div>
<div class="parent">
    <p>Four</p>
    <p>Five</p>
    <p>Six</p>
</div>
```

Then try to access any of the element of `previous` class using `getParentElement()` and `getPreviousElement()`

### Relevant log output

```typescript
Error: Can't call $ on previous element of element with selector "function () {
        return this.parentElement;
    }" because sibling wasn't found
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2022-03-11 10:37
It seems that I can't reproduce this. Here is my example:

```js
await browser.url('http://guinea-pig.webdriver.io/')

    console.log(await browser.$('.yellow')
        .parentElement()
        .previousElement()
        .getTagName()
    )
```

I saw that your command is called `getPreviousElement` and `getParentElement` which are not WebdriverIO commands. Not sure how your setup looks like therefor I will close the issue but happy to re-open if new information can be provided.

**Closed by christian-bromann** 2022-03-11 10:37 UTC
Labels: Bug 🐛, Needs Investigation, help wanted

**Comment by mayankshukla94** [comment] 2022-03-31 16:23
@christian-bromann I have updated the commands to `parentElement()` and `previousElement()`. And I'm still facing the issue. I will investigate this because this looks like a valid bug.

**Comment by christian-bromann** [comment] 2022-03-31 16:27
@mayankshukla94 a minimal reproducible example would help 😉

**Comment by mayankshukla94** [comment] 2022-03-31 16:39
I tried this

```js
it('sample', async() => {
    await browser.url('http://guinea-pig.webdriver.io/')
    const yellowElement = await browser.$('.yellow');
    const headerElement = await yellowElement.parentElement().previousElement();
});
```

And got below error:

![image](https://user-images.githubusercontent.com/40030809/161106381-a129c797-d85d-450b-96b7-35580045d983.png)

**Comment by christian-bromann** [comment] 2022-03-31 19:57
I just checked out a new project and ran:
```ts
describe('My Login application', () => {
    it('should login with valid credentials', async () => {
        await browser.url('http://guinea-pig.webdriver.io/')
        const yellowElement = await browser.$('.yellow');
        const headerElement = await yellowElement.parentElement().previousElement();
        console.log(await headerElement.getTagName());
    });
});
```
with no problem.

**Comment by mayankshukla94** [comment] 2022-04-01 11:17
@christian-bromann I tried your same code. I'm getting error. I'm using wdio version `"@wdio/cli": "^7.16.13"`

**Comment by christian-bromann** [comment] 2022-04-01 11:21
Have you tried in a new project setup? Can you create a sample repo with a GitHub Action that can reproduce this issue?
