### ISSUE TITLE
custom commands w/ multiple args not working with chaining

### ISSUE THREAD

**Issue by mherodev** [webdriverio/webdriverio#2582] opened 2018-02-02 02:26 UTC
Here's my custom command:

```javascript
function setText(selector, text) {
  console.log(`selector: ${selector}`);
  console.log(`text: ${text}`);

  const element = this.element(selector);
  element.waitForVisible();
  element.clearElement();
  element.setValue(selector, text); // it's weird to pass the selector here, but setValue complains
}
```

Here's how it's being called:

```javascript
  console.log('using browser object');
  browser.setText(this.searchInput.selector, 90034);
  console.log('using element chaining');
  this.searchInput.setText(90034);
```

And here's the result:

```bash
using browser object
selector: "#setLocationSearchInput"
text: 90034

using element chaining
selector: 90034
text: undefined
```

```bash
selector.slice is not a function
running Chrome on OS X 10.10
TypeError: selector.slice is not a function
    at element(90034) - index.js:263:37
    at element("#setLocationSearchInput") - index.js:312:3
```

How do I properly create a custom version of `setValue` that works with chaining?

**Comment by christian-bromann** [comment] 2018-02-02 04:56
duplicate of #1236

**Closed by christian-bromann** 2018-02-02 04:56 UTC
