### ISSUE TITLE
[🐛 Bug]: Getting error: TypeError: expect(...).withContext is not a function

### ISSUE THREAD

**Issue by restreporush** [webdriverio/webdriverio#9705] opened 2023-02-03 17:05 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.3.2

### Node.js Version

10.9.1

### Mode

Standalone Mode

### What happened?

After upgrading from Webdriverio 7 to Webdriverio 8, the functions from Jasmine's "expect()" like ".withContext()" or ".toBeTrue()" stopped working and report a "is not a function" error. 

`[chrome 109.0.5414.119 mac os x #0-0] Running: chrome (v109.0.5414.119) on mac os x
[chrome 109.0.5414.119 mac os x #0-0] Session ID: 4243c6ddb17f092d9f84865a5824490f
[chrome 109.0.5414.119 mac os x #0-0]
[chrome 109.0.5414.119 mac os x #0-0] » file:///Users/.../wdio%20test/test/specs/example.e2e.ts
[chrome 109.0.5414.119 mac os x #0-0] My Login application
[chrome 109.0.5414.119 mac os x #0-0]    ✖ should login with valid credentials
[chrome 109.0.5414.119 mac os x #0-0]
[chrome 109.0.5414.119 mac os x #0-0] 1 failing (1.2s)
[chrome 109.0.5414.119 mac os x #0-0]
[chrome 109.0.5414.119 mac os x #0-0] 1) My Login application should login with valid credentials
[chrome 109.0.5414.119 mac os x #0-0] TypeError: expect(...).withContext is not a function
[chrome 109.0.5414.119 mac os x #0-0]     at UserContext.<anonymous> (/Users/.../wdio test/test/specs/example.e2e.ts:4:22)
[chrome 109.0.5414.119 mac os x #0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)`

I tried to downgrade to version 7 and the error stopped occurring.

### What is your expected behavior?

The use of the mentioned functions should be allowed and the tests can run correctly when those are used in the "expect()".

### How to reproduce the bug.

Configure Webdriverio 8

Create a simple test like this:
`describe('My Login application', () => {
    it('should login with valid credentials', async () => {
        expect(true).withContext('foo error message').toBe(false);
    });
});`

Execute the test and validate the tests can be run.

tsconfig:
`{
    "compilerOptions": {
        "moduleResolution": "node",
        "module": "commonjs",
        "types": [
            "node",
            "@wdio/jasmine-framework",
            "@wdio/globals/types"
        ],
        "target": "es2021"
    }
}`

### Relevant log output

```typescript
[chrome 109.0.5414.119 mac os x #0-0] Running: chrome (v109.0.5414.119) on mac os x
[chrome 109.0.5414.119 mac os x #0-0] Session ID: 4243c6ddb17f092d9f84865a5824490f
[chrome 109.0.5414.119 mac os x #0-0]
[chrome 109.0.5414.119 mac os x #0-0] » file:///Users/.../wdio%20test/test/specs/example.e2e.ts
[chrome 109.0.5414.119 mac os x #0-0] My Login application
[chrome 109.0.5414.119 mac os x #0-0]    ✖ should login with valid credentials
[chrome 109.0.5414.119 mac os x #0-0]
[chrome 109.0.5414.119 mac os x #0-0] 1 failing (1.2s)
[chrome 109.0.5414.119 mac os x #0-0]
[chrome 109.0.5414.119 mac os x #0-0] 1) My Login application should login with valid credentials
[chrome 109.0.5414.119 mac os x #0-0] TypeError: expect(...).withContext is not a function
[chrome 109.0.5414.119 mac os x #0-0]     at UserContext.<anonymous> (/Users/.../wdio test/test/specs/example.e2e.ts:4:22)
[chrome 109.0.5414.119 mac os x #0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2023-02-03 19:41
Duplicate of https://github.com/webdriverio/expect-webdriverio/issues/987

**Closed by christian-bromann** 2023-02-03 19:41 UTC
Labels: Bug 🐛, Needs Triaging ⏳
