### ISSUE TITLE
ERROR @wdio/utils:shim: HTTPError: Response code 404 (Not Found)

### ISSUE THREAD

**Issue by pedroscattaregi** [webdriverio/webdriverio#5687] opened 2020-08-04 18:43 UTC
## 💬 Questions and Help
I'm using wdio with browserstack service. There is no problem into the execution but there is an error into a request in the lib.

What I'm using:
 "@wdio/local-runner": "~6.3.3"
 "@wdio/appium-service": "~6.1.16"
 "@wdio/browserstack-service": "~6.1.15"
 "@wdio/cucumber-framework": "~6.3.0"
 "@wdio/spec-reporter": "~6.3.0"

Running the test normally and updating the brwoserstack session details, I'm getting the following error in logs but there is no error of functionality (update the session details in browserstack).

### Error Log:
` [0-0] 2020-08-04T18:09:14.135Z ERROR @wdio/utils:shim: HTTPError: Response code 404 (Not Found)
    at onResponse (/home/pedroscattaregi/Documents/projetos/mobile-testing-framework/node_modules/got/dist/source/as-promise/index.js:142:28)
    at process._tickCallback (internal/process/next_tick.js:68:7) `

Into the lib code, there is a comment about an expected error in ts, that "// @ts-expect-error TS doesn't notice that CancelableRequest is a Promise", I do'nt know if it is related or not. I would like to know if I'm doing something wrong or it has a unexpected log error.

**Comment by christian-bromann** [comment] 2020-08-06 10:41
Can you please provide wdio log files? Is it happening in all tests or just randomly?

**Comment by pedroscattaregi** [comment] 2020-08-06 13:02
This is a more complete log from the beginning until the error happens:
`Execution of 1 spec files started at 2020-08-06T12:58:27.026Z

2020-08-06T12:58:27.030Z DEBUG @wdio/utils:initialiseServices: initialise service "browserstack" as NPM package
2020-08-06T12:58:27.046Z INFO @wdio/cli:launcher: Run onPrepare hook
2020-08-06T12:58:27.047Z INFO @wdio/browserstack-service: browserstackLocal is not enabled - skipping...
2020-08-06T12:58:27.048Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2020-08-06T12:58:27.049Z INFO @wdio/local-runner: Start worker 0-0 with arg: ./browserstack.wdio.conf.js
[0-0] 2020-08-06T12:58:27.540Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2020-08-06T12:58:27.544Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2020-08-06T12:58:27.546Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
[0-0] RUNNING in bs://be395bb6079dfb9e52681fc8e0519616dd9805f9 - /src/features/login.feature
[0-0] 2020-08-06T12:58:27.893Z DEBUG @wdio/utils:initialiseServices: initialise service "browserstack" as NPM package
[0-0] 2020-08-06T12:58:27.900Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2020-08-06T12:58:27.901Z INFO webdriverio: Initiate new session using the webdriver protocol
[0-0] 2020-08-06T12:58:27.903Z INFO webdriver: [POST] https://hub-cloud.browserstack.com/wd/hub/session
[0-0] 2020-08-06T12:58:27.903Z INFO webdriver: DATA { capabilities:
   { alwaysMatch:
      { platformName: 'Android',
        deviceName: 'Google Pixel 3',
        app: 'bs://be395bb6079dfb9e52681fc8e0519616dd9805f9',
        automationName: 'uiautomator2',
        build: 'wdio build api test 12',
        'browserstack.debug': true,
        'browserstack.realMobile': true },
     firstMatch: [ {} ] },
  desiredCapabilities:
   { platformName: 'Android',
     deviceName: 'Google Pixel 3',
     app: 'bs://be395bb6079dfb9e52681fc8e0519616dd9805f9',
     automationName: 'uiautomator2',
     build: 'wdio build api test 12',
     'browserstack.debug': true,
     'browserstack.realMobile': true } }
[0-0] 2020-08-06T12:58:51.274Z ERROR @wdio/utils:shim: HTTPError: Response code 404 (Not Found)
    at onResponse (/home/pedroscattaregi/Documents/projetos/mobile-testing-framework/node_modules/got/dist/source/as-promise/index.js:142:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[0-0] 2020-08-06T12:58:53.948Z INFO webdriver: COMMAND findElement("accessibility id", "onboarding-complete-button")
[0-0] 2020-08-06T12:58:53.949Z INFO webdriver: [POST] https://hub-cloud.browserstack.com/wd/hub/session/6bb0e074a2e44b37a7fc476763776d0fa27e0c12/element
[0-0] 2020-08-06T12:58:53.949Z INFO webdriver: DATA { using: 'accessibility id',
  value: 'onboarding-complete-button' }
[0-0] (node:387212) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at onResponse (/home/pedroscattaregi/Documents/projetos/mobile-testing-framework/node_modules/got/dist/source/as-promise/index.js:142:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:387212) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[0-0] (node:387212) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[0-0] 2020-08-06T12:58:54.766Z INFO webdriver: RESULT { ELEMENT: '28a61a20-2f44-4830-ba53-36cca45b5ce5' }`

It happensright after the connection. After these logs are only the get element, click, send keys and every methods for the test.

**Comment by christian-bromann** [comment] 2020-08-06 21:03
@pedroscattaregi not sure why it would fail with 404. Would you mind help us investigate?

**Comment by christian-bromann** [comment] 2020-08-06 21:20
This seems to be a duplicate of #5647

**Closed by christian-bromann** 2020-08-06 21:20 UTC
Labels: Needs Investigation, help wanted
