### ISSUE TITLE
[🐛 Bug]: v9: Previously working method of getting element from classic frame not working

### ISSUE THREAD

**Issue by danielhjacobs** [webdriverio/webdriverio#13384] opened 2024-08-16 22:53 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v9

### Node.js Version

22

### Mode

Standalone Mode

### What happened?

This code is no longer working:

```ts
        await browser.switchToFrame(await browser.$("#test-frame"));
        await browser.$("ruffle-object").waitForExist();

        const actual = await browser
            .$("#test-container")
            .getHTML({ includeSelectorTag: false, pierceShadowRoot: false });
		
```

We're using the following HTML that converts objects to ruffle-objects with the script:

index.html
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>WEB</title>
        <script src="/dist/ruffle.js" type="text/javascript"></script>
    </head>

    <frameset rows="10%,90%">
        <frame
            id="nav-frame"
            name="nav"
            src="frame1.html"
            scrolling="no"
            frameborder="0"
        ></frame>
        <frame
            id="test-frame"
            name="content"
            src="frame2.html"
            scrolling="no"
            frameborder="0"
        ></frame>
    </frameset>
</html>
```
frame1.html
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Nav</title>
    </head>

    <body>
        <a href="frame2.html" target="content" id="reload-link">Reload frame</a>
    </body>
</html>
```
frame2.html
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>REAL CONTENT</title>
        <style>
            * {
                margin: 0;
            }
        </style>
    </head>

    <body>
        <div id="test-container">
            <object
                type="application/x-shockwave-flash"
                data="/test_assets/example.swf"
                width="550"
                height="400"
            >
                <param name="movie" value="/test_assets/example.swf" />
                <param name="quality" value="high" />
            </object>
        </div>
    </body>
</html>
```

The actual source code we had used can be found at https://github.com/ruffle-rs/ruffle/tree/master/web/packages/selfhosted/test/polyfill/classic_frames_provided. Though we did switch the CSS selector and the getHTML call as needed.

### What is your expected behavior?

The ruffle-object should exist after a small amount of time thanks to the JS replacing the object in the frame.

### How to reproduce the bug.

```ts
        await browser.switchToFrame(await browser.$("#test-frame"));
        await browser.$("ruffle-object").waitForExist();

        const actual = await browser
            .$("#test-container")
            .getHTML({ includeSelectorTag: false, pierceShadowRoot: false });
		
```

### Relevant log output

```typescript
Error: element ("ruffle-object") still not existing after 30000ms
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by danielhjacobs** [comment] 2024-08-16 22:54
Does this perhaps relate to https://github.com/webdriverio/webdriverio/pull/13223? If so, what's the suggested replacement method?

**Comment by danielhjacobs** [comment] 2024-08-19 13:38
This also applies to iframes, as the failing tests related to this are the following:

- [test/polyfill/classic_frames_injected/test.ts](https://github.com/ruffle-rs/ruffle/tree/master/web/packages/selfhosted/test/polyfill/classic_frames_injected)
- [test/polyfill/classic_frames_provided/test.ts](https://github.com/ruffle-rs/ruffle/tree/master/web/packages/selfhosted/test/polyfill/classic_frames_provided)
- [test/polyfill/iframes_injected/test.ts](https://github.com/ruffle-rs/ruffle/tree/master/web/packages/selfhosted/test/polyfill/iframes_injected)
- [test/polyfill/iframes_provided/test.ts](https://github.com/ruffle-rs/ruffle/tree/master/web/packages/selfhosted/test/polyfill/iframes_provided)

**Comment by danielhjacobs** [comment] 2024-08-19 13:56
Note that we're not trying to access the shadow root, but we are trying to get an element from an iframe that contains a shadow DOM, we just don't care to pierce the shadow root.

**Comment by christian-bromann** [comment] 2024-08-20 01:08
@danielhjacobs can you help provide a better reproduction case? The two frame HTML files don't contain any `ruffle-object` element.

**Comment by torokati44** [comment] 2024-08-20 01:25
@christian-bromann

> The ruffle-object should exist after a small amount of time thanks to the JS replacing the object in the frame.

**Comment by christian-bromann** [comment] 2024-08-20 01:33
Thanks for providing more context.

Duplicate of #13218

**Closed by christian-bromann** 2024-08-20 01:33 UTC
Labels: Bug 🐛, Reproducible Example Missing
