### ISSUE TITLE
wdio config is broken, new install

### ISSUE THREAD

**Issue by anth0d** [webdriverio/webdriverio#2801] opened 2018-07-12 16:36 UTC
## The problem

Error: ENOENT: no such file or directory, open '/Users/anth0/workspace/auth0-webdriver-tests/node_modules/webdriverio/build/lib/helpers/wdio.conf.ejs' during first time `wdio config`

I suspect `node_modules/webdriverio/..` is being removed as part of the install dependencies step.

To reproduce, run the following (in case the selections are important, I have included the entire config I selected)

```
$ ./node_modules/.bin/wdio config

=========================
WDIO Configuration Helper
=========================

? Where do you want to execute your tests? In the cloud using Sauce Labs, Browserstack or Testingbot
? Environment variable for username SAUCE_USERNAME
? Environment variable for access key SAUCE_ACCESS_KEY
? Which framework do you want to use? mocha
? Shall I install the framework adapter for you? Yes
? Where are your test specs located? ./test/specs/**/*.js
? Which reporter do you want to use?  spec - https://github.com/webdriverio/wdio-spec-reporter,  junit - https://github.com/webdriverio/wdio-junit-reporter,  mochawesome - https:/
/github.com/fijijavis/wdio-mochawesome-reporter
? Shall I install the reporter library for you? Yes
? Do you want to add a service to your test setup?  sauce - https://github.com/webdriverio/wdio-sauce-service,  selenium-standalone - https://github.com/webdriverio/wdio-selenium-
standalone-service,  static-server - https://github.com/LeadPages/wdio-static-server-service,  chromedriver - https://github.com/atti187/wdio-chromedriver-service,  docker - https
://github.com/stsvilik/wdio-docker-service,  screenshots-cleanup - https://github.com/andriilazebnyi/wdio-screenshots-cleanup-service
? Shall I install the services for you? Yes
? Level of logging verbosity error
? In which directory should screenshots gets saved if a command fails? ./errorShots/
? What is the base url? http://test.com

Installing wdio packages:

Packages installed successfully, creating configuration file...
fs.js:143
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/me/workspace/test/node_modules/webdriverio/build/lib/helpers/wdio.conf.ejs'
    at Object.fs.openSync (fs.js:577:3)
    at Object.fs.readFileSync (fs.js:483:33)
    at renderConfigurationFile (/Users/me/workspace/test/node_modules/webdriverio/build/lib/cli.js:315:28)
    at /Users/me/workspace/test/node_modules/webdriverio/build/lib/cli.js:305:17
    at /Users/me/workspace/test/node_modules/npm-install-package/index.js:31:5
    at ChildProcess.exithandler (child_process.js:282:7)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)

```

## Environment

* WebdriverIO version: `"^4.13.1"`
* Node.js version: `v10.3.0`
* Additional wdio packages used (if applicable): See above logs

**Comment by christian-bromann** [comment] 2018-07-12 16:38
Duplicate of #2612

**Closed by christian-bromann** 2018-07-12 16:38 UTC
