### ISSUE TITLE
nullPointerException in firefox when calling setValue

### ISSUE THREAD

**Issue by hborawski** [webdriverio/webdriverio#3878] opened 2019-04-24 00:36 UTC
**Environment (please complete the following information):**
 - WebdriverIO version: **5.7.15**
 - Mode:**WDIO Testrunner**
 - If WDIO Testrunner, running sync/async: **async**
 - Node.js version:**10.15**
 - NPM version:**6.4.1**
 - Browser name and version:**Firefox latest (66)**
 - Platform name and version:**macOS 10.13**
 - Additional wdio packages used (if applicable): **@wdio/sauce-service @wdio/mocha-framework @wdio/spec-reporter @wdio/local-runner @wdio/cli**

**Config of WebdriverIO**
Repo to reproduce the issue:
https://github.com/hborawski/wdio-sauce-junit-error

**Describe the bug**
When using `setValue` in saucelabs firefox environment, a null pointer exception is thrown and the value is never set. (Observed in firefox 59-66, did not test earlier versions)
```
Error: java.lang.NullPointerException
     at getErrorFromResponseBody (/Users/hborawski/sandbox/wdio-sauce-nullpointer/node_modules/webdriver/build/utils.js:348:10)
     at Request._callback (/Users/hborawski/sandbox/wdio-sauce-nullpointer/node_modules/webdriver/build/request.js:121:64)
     at Request.self.callback (/Users/hborawski/sandbox/wdio-sauce-nullpointer/node_modules/request/request.js:185:22)
     at Request.emit (events.js:182:13)
     at Request.EventEmitter.emit (domain.js:441:20)
     at Request.<anonymous> (/Users/hborawski/sandbox/wdio-sauce-nullpointer/node_modules/request/request.js:1161:10)
     at Request.emit (events.js:182:13)
     at Request.EventEmitter.emit (domain.js:441:20)
     at IncomingMessage.<anonymous> (/Users/hborawski/sandbox/wdio-sauce-nullpointer/node_modules/request/request.js:1083:12)
     at Object.onceWrapper (events.js:273:13)
```

**To Reproduce**
Steps to reproduce the behavior in `README.md`:
https://github.com/hborawski/wdio-sauce-nullpointer

**Expected behavior**
Test should pass and exit with exit code `0`

**Log**
https://gist.github.com/hborawski/a8536a3ebb97240005e0eb5bae993d37

**Notes**
I found this issue: https://github.com/webdriverio/webdriverio/issues/3844 that looks to be the same problem but was closed as a duplicate of https://github.com/webdriverio/webdriverio/issues/3834 which seems to be unrelated. In either case, this was reproduced with the newest versions which includes the fix for the log type error from https://github.com/webdriverio/webdriverio/issues/3834

**Comment by xlenz** [comment] 2019-04-24 11:33
@hborawski setValue works fine for me locally.
geckodriver-0.24.0
firefox 66.0.3

I'm not using saucelabs, looks like some configuration issue of the service.

**Comment by baruchvlz** [comment] 2019-04-25 11:20
@xlenz I just tried this with saucelabs. It works for chrome but not for safari nor firefox.

I doubt this is on WDIO's side, this might be an issue with SL.

**Comment by pmerwin** [comment] 2019-04-29 19:07
I found that I have to specify a selenium version or Firefox does not work over sauce at all with wdio vs 5:

 {
            browserName: 'firefox',
            platformName: 'OS X 10.12',
            // extendedDebugging: true,
            browserVersion: 'latest',
            'sauce:options': {
                seleniumVersion: '3.11.0',
            }
        }
}

Not sure if that may help you here, but curious if it does.

**Comment by pmerwin** [comment] 2019-04-29 19:22
also, I see this with edge over sauce too:

HTTP Status: 500
{ "stackTrace": [ { "methodName": "setJsonParameters", "fileName": "SendKeys.java", "className": "org.openqa.selenium.remote.server.handler.SendKeys", "nativeMethod": false, "lineNumber": 41, "hCode": -863529568, "class": "java.lang.StackTraceElement" }, { "methodName": "handle", "fileName": "ResultConfig.java", "className": "org.openqa.selenium.remote.server.rest.ResultConfig", "nativeMethod": false, "lineNumber": 99, "hCode": 517694314, "class": "java.lang.StackTraceElement" }, { "methodName": "handleRequest", "fileName": "JsonHttpCommandHandler.java", "className": "org.openqa.selenium.remote.server.JsonHttpCommandHandler", "nativeMethod": false, "lineNumber": 79, "hCode": -924917091, "class": "java.lang.StackTraceElement" }, { "methodName": "handleRequest", "fileName": "DriverServlet.java", "className": "org.openqa.selenium.remote.server.DriverServlet", "nativeMethod": false, "lineNumber": 202, "hCode": -473869174, "class": "java.lang.StackTraceElement" }, { "methodName": "doPost", "fileName": "DriverServlet.java", "className": "org.openqa.selenium.remote.server.DriverServlet", "nativeMethod": false, "lineNumber": 164, "hCode": -1874935832, "class": "java.lang.StackTraceElement" }, { "methodName": "service", "fileName": "HttpServlet.java", "className": "javax.servlet.http.HttpServlet", "nativeMethod": false, "lineNumber": 707, "hCode": 1081440685, "class": "java.lang.StackTraceElement" }, { "methodName": "service", "fileName": "DriverServlet.java", "className": "org.openqa.selenium.remote.server.DriverServlet", "nativeMethod": false, "lineNumber": 130, "hCode": 1913428016, "class": "java.lang.StackTraceElement" }, { "methodName": "service", "fileName": "HttpServlet.java", "className": "javax.servlet.http.HttpServlet", "nativeMethod": false, "lineNumber": 790, "hCode": 1081440768, "class": "java.lang.StackTraceElement" }, { "methodName": "handle", "fileName": "ServletHolder.java", "className": "org.openqa.jetty.jetty.servlet.ServletHolder", "nativeMethod": false, "lineNumber": 428, "hCode": 1066597463, "class": "java.lang.StackTraceElement" }, { "methodName": "dispatch", "fileName": "ServletHandler.java", "className": "org.openqa.jetty.jetty.servlet.ServletHandler", "nativeMethod": false, "lineNumber": 680, "hCode": 1390736799, "class": "java.lang.StackTraceElement" }, { "methodName": "handle", "fileName": "ServletHandler.java", "className": "org.openqa.jetty.jetty.servlet.ServletHandler", "nativeMethod": false, "lineNumber": 571, "hCode": -1689621664, "class": "java.lang.StackTraceElement" }, { "methodName": "handle", "fileName": "HttpContext.java", "className": "org.openqa.jetty.http.HttpContext", "nativeMethod": false, "lineNumber": 1526, "hCode": 1685351418, "class": "java.lang.StackTraceElement" }, { "methodName": "handle", "fileName": "HttpContext.java", "className": "org.openqa.jetty.http.HttpContext", "nativeMethod": false, "lineNumber": 1479, "hCode": 1685351371, "class": "java.lang.StackTraceElement" }, { "methodName": "service", "fileName": "HttpServer.java", "className": "org.openqa.jetty.http.HttpServer", "nativeMethod": false, "lineNumber": 920, "hCode": 1779095633, "class": "java.lang.StackTraceElement" }, { "methodName": "service", "fileName": "HttpConnection.java", "className": "org.openqa.jetty.http.HttpConnection", "nativeMethod": false, "lineNumber": 820, "hCode": -1150970931, "class": "java.lang.StackTraceElement" }, { "methodName": "handleNext", "fileName": "HttpConnection.java", "className": "org.openqa.jetty.http.HttpConnection", "nativeMethod": false, "lineNumber": 986, "hCode": 1892375929, "class": "java.lang.StackTraceElement" }, { "methodName": "handle", "fileName": "HttpConnection.java", "className": "org.openqa.jetty.http.HttpConnection", "nativeMethod": false, "lineNumber": 837, "hCode": -954717551, "class": "java.lang.StackTraceElement" }, { "methodName": "handleConnection", "fileName": "SocketListener.java", "className": "org.openqa.jetty.http.SocketListener", "nativeMethod": false, "lineNumber": 243, "hCode": 91812189, "class": "java.lang.StackTraceElement" }, { "methodName": "handle", "fileName": "ThreadedServer.java", "className": "org.openqa.jetty.util.ThreadedServer", "nativeMethod": false, "lineNumber": 358, "hCode": -1347859604, "class": "java.lang.StackTraceElement" }, { "methodName": "run", "fileName": "ThreadPool.java", "className": "org.openqa.jetty.util.ThreadPool$PoolThread", "nativeMethod": false, "lineNumber": 537, "hCode": 172881960, "class": "java.lang.StackTraceElement" } ], "cause": null, "localizedMessage": null, "class": "java.lang.NullPointerException", "message": null, "suppressed": [], "hCode": 452277910 }

**Comment by pmerwin** [comment] 2019-04-29 20:21
Adding the selmium server for edge fixes thgis for me over sauce:

```
        {
            browserName: 'MicrosoftEdge',
            platformName: 'Windows 10',
            browserVersion: 'latest',
                 **'sauce:options': {
                seleniumVersion: '3.14.0',
            }**
            
        }
```

**Comment by wswebcreation** [comment] 2019-04-30 07:09
This is the complete set that currently works for Sauce Labs and WDIO

```js
const deskSpecs = join(process.cwd(), './tests/specs/desktop.spec.js');
const defaultBrowserSauceOptions = {
    screenResolution: '1600x1200',
    seleniumVersion: '3.141.59',
};
const chromeOptions = {
    'goog:chromeOptions': {
        'w3c': true,
    },
};

config.capabilities= [
   /**
     * Desktop browsers
     */
    {
        browserName: 'googlechrome',
        platformName: 'Windows 10',
        browserVersion: 'latest',
        specs: [ basicSpecs ],
        'sauce:options': {
            ...defaultBrowserSauceOptions,
        },
        ...chromeOptions,
    },
    {
        browserName: 'googlechrome',
        platformName: 'Windows 10',
        browserVersion: 'latest',
        specs: [ deskSpecs ],
        'sauce:options': {
            ...defaultBrowserSauceOptions,
        },
        ...chromeOptions,
    },
    {
        browserName: 'firefox',
        platformName: 'Windows 10',
        browserVersion: 'latest',
        specs: [ deskSpecs ],
        'sauce:options': {
            ...defaultBrowserSauceOptions,
        },
    },
    {
        browserName: 'internet explorer',
        platformName: 'Windows 8.1',
        browserVersion: 'latest',
        specs: [ deskSpecs ],
        'sauce:options': {
            ...defaultBrowserSauceOptions,
            iedriverVersion: '3.141.59',
        },
    },
    {
        browserName: 'MicrosoftEdge',
        platformName: 'Windows 10',
        browserVersion: 'latest',
        specs: [ deskSpecs ],
        'sauce:options': {
            ...defaultBrowserSauceOptions,
        },
    },
    // Safari 11 is not W3C compliant,
    // see https://developer.apple.com/documentation/webkit/macos_webdriver_commands_for_safari_11_1_and_earlier
    {
        browserName: 'safari',
        platform: 'macOS 10.12',
        version: '11.0',
        specs: [ deskSpecs ],
        ...defaultBrowserSauceOptions,
    },
    {
        browserName: 'safari',
        platformName: 'macOS 10.14',
        browserVersion: '12.0',
        specs: [ deskSpecs ],
        'sauce:options': {
            ...defaultBrowserSauceOptions,
        },
    }
];
```

The problem is that WebdriverIO is already using W3C but the Sauce Labs platform not. By providing the `'sauce:options'` and the new properties, see [here](https://wiki.saucelabs.com/display/DOCS/Selenium+W3C+Capabilities+Support+-+Beta) all should work

**Comment by CrispusDH** [comment] 2019-04-30 09:31
@wswebcreation would it be useful to pin somewhere in wdio docs?

**Comment by wswebcreation** [comment] 2019-04-30 09:38
@christian-bromann 

What should I do with this, create a small blog post for example?

**Comment by christian-bromann** [comment] 2019-04-30 13:25
@wswebcreation I would almost say let's add this for all SL jobs as default options. I don't see a reason why someone would not like to use W3C sessions.

**Comment by wswebcreation** [comment] 2019-04-30 18:34
@christian-bromann

Are we going to rewrite the capabilities then? Because if there are caps that are not compliant the instance will error out

**Comment by christian-bromann** [comment] 2019-04-30 20:33
I think we should check if the customer has custom sauce options set and set them if not

**Comment by christian-bromann** [comment] 2019-05-02 17:39
So imo we should add 

```js
const sauceOptions = {
  'sauce:options': {
    seleniumVersion: '3.141.59',
    build: `Build ${Date.now()}`.slice(0, -3)
  }
}

const chromeOptions = {
  'goog:chromeOptions': {
    'w3c': true
  }
}
```
automatically to the capabilities if someone is running tests on Sauce.

**Comment by pmerwin** [comment] 2019-05-02 17:44
> So imo we should add
> 
> ```js
> const sauceOptions = {
>   'sauce:options': {
>     seleniumVersion: '3.141.59',
>     build: `Build ${Date.now()}`.slice(0, -3)
>   }
> }
> 
> const chromeOptions = {
>   'goog:chromeOptions': {
>     'w3c': true
>   }
> }
> ```
> 
> automatically to the capabilities if someone is running tests on Sauce.

Agreed, make it seamless for the consumer.

**Comment by wswebcreation** [comment] 2019-05-02 18:24
@christian-bromann 

No, that will **not** work, we also **need** to adjust the following, see [here](https://wiki.saucelabs.com/display/DOCS/Selenium+W3C+Capabilities+Support+-+Beta)

- Change the capability `platform` to `platformName`
- For testing on Google Chrome browsers, change `browserName: chrome` to `browserName:googlechrome`
- Change the name of the `versions` capability to `browserVersion` and set the version to `latest`, or use one of the browser versions that is compatible with the W3C protocol

If we don't do the above 3 it will not start a session

**Comment by christian-bromann** [comment] 2019-05-02 18:52
> If we don't do the above 4 it will not start a session (tested and confirmed that it will **not** work if not provided).

This is where Sauce Labs should jump in. My goal is to make it just work. I don't think many people test __purposely__ on non w3c browser anymore.

**Comment by wswebcreation** [comment] 2019-05-02 18:58
> This is where Sauce Labs should jump in. My goal is to make it just work. I don't think many people test purposely on non w3c browser anymore.

Does that mean that WebdriverIO will also change the rest of the capabilities?

**Comment by christian-bromann** [comment] 2019-05-02 20:03
> Does that mean that WebdriverIO will also change the rest of the capabilities?

I actually don't know. I don't believe it is fixed anytime soon on the Sauce side so I believe maybe moving it into the sauce service would make most sense 🤷‍♂ ?

**Comment by wswebcreation** [comment] 2019-05-07 15:19
@hborawski 

Did you try already with the new SL caps? I think this can be closed unless you still are facing issues

**Comment by hborawski** [comment] 2019-05-07 17:47
@wswebcreation Yes setting the capabilities like that did resolve the issue, just got around to trying it yesterday. Apologies for the delay!

**Comment by wswebcreation** [comment] 2019-05-07 18:00
@hborawski 

Ok, cool, tnx, going to close it for now

**Closed by wswebcreation** 2019-05-07 18:00 UTC
