### ISSUE TITLE
support yarn v2 pnp

### ISSUE THREAD

**Issue by missing1984** [webdriverio/webdriverio#5228] opened 2020-04-06 21:07 UTC
**Is your feature request related to a problem? Please describe.**
Encountered couple problems when using wdio together with yarn v2 pnp.

### @wdio/cli
`@wdio/cli` failed to initialize the config. steps to reproduce:
1. `mkdir wdio-yarn2 && cd wdio-yarn2`
2. `yarn init`
3. `yarn add @wdio/cli --dev`
4. `yarn wdio config -y`

Error trace:
```
(node:72873) UnhandledPromiseRejectionWarning: Error: devtools tried to access debug, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: debug (via "debug")
Required by: devtools@npm:6.0.13 (via /Users/mluo/workspace/github/wdio-yarn2-cli/.yarn/cache/devtools-npm-6.0.13-8e9f636a3c-2.zip/node_modules/devtools/build/)
```

Possible causes: 
1. devtools try to access `debug` but doesn't declare debug as its dependency.
```
    let puppeteerDebugPkg = path.resolve(
        path.dirname(require.resolve('puppeteer-core')),
        'node_modules',
        'debug')
```

2. `yarn-install` package used by `@wdio/cli` does not support yarn 2.

3. `wdio-chromedriver-service` used `fs-extra` but don't declare it as dependency.

**The good news is that once I have the wdio.conf.js generated, the basic example passed.**

**Describe the solution you'd like**
1. Add yarn v2 support for `@wdio/cli`
2. Make sure documentation gets updated as well.

**Describe alternatives you've considered**
N/A

**Additional context**

Yarn v2 pnp: https://yarnpkg.com/features/pnp

The issue should be easy to reproduce but I am happy to help if more context or example is needed.

**Comment by christian-bromann** [comment] 2020-04-06 22:26
@missing1984 the problem is that we need to require a dependency from Puppeteer to properly monkey patch it. I am planning to propose a change in Puppeteer to allow accessing the CDP commands easier.

**Comment by missing1984** [comment] 2020-04-07 17:24
Thanks for the update, @christian-bromann.  I also looked at the code of @wdio/utils, It seems the way we load plugin may also need to be revisited in the context of yarn pnp. 

Currently, all plugin (as well as @wdio/sync) is `require` on behalf of pkg `@wdio/utils`. However, `@wdio/utils` is not the package that owns all plugin dependencies. It actually depends on nodejs node_modules resolution to work.

If we can make the plugin `require` on behalf of the config file we can then make it compatible with pnp and node_modules.

node module api `module.createRequire` or `module. createRequireFromPath` can make this happen.

**Comment by christian-bromann** [comment] 2020-04-08 08:26
> node module api `module.createRequire` or `module. createRequireFromPath` can make this happen.

Yep. That said, I think there are plenty of changes required to make this compatible with Yarn PnP and the ESM module system. For example there are plenty examples where things like `__dirname` is used. It's not just that one position.

**Comment by christian-bromann** [comment] 2020-05-15 09:38
Closing in favor of #5401

**Closed by christian-bromann** 2020-05-15 09:38 UTC
Labels: help wanted

**Comment by LouisStAmour** [comment] 2020-10-29 03:29
Could this be re-opened? I'm not sure if TypeScript conversion has been done since @wdio/cli 6.7.0, but I can say that the above error still occurs.

**Comment by christian-bromann** [comment] 2020-10-29 08:18
We are working on transitioning to TypeScript. You can follow along and help contributing here: https://github.com/webdriverio/webdriverio/projects/14

**Comment by darthtrevino** [comment] 2021-09-30 20:21
PnP Support is orthogonal to TypeScript: it's a totally separate issue. 

Aside from the issues listed above, which can be mitigated via .yarnrc configuration and properly marking peers, I'm running into some runtime issues that appear related to runtime package resolution. With a very minimal default configuration (no reporters), I'm seeing the following errors just launching the runner:
```
2021-09-30T20:19:29.233Z INFO @wdio/cli:launcher: Run onPrepare hook
2021-09-30T20:19:29.234Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2021-09-30T20:19:29.235Z INFO @wdio/local-runner: Start worker 0-0 with arg:
[0-0] 2021-09-30T20:19:30.108Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2021-09-30T20:19:30.357Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read properties of undefined (reading 'init')
[0-0]     at Runner.run (C:\ws\cbo-suite\.yarn\__virtual__\@wdio-runner-virtual-649f4ef4c7\0\cache\@wdio-runner-npm-7.13.2-793f57a3dd-718607a4e1.zip\node_modules\@wdio\runner\build\index.js:83:49)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0] FAILED
2021-09-30T20:19:30.385Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:01

2021-09-30T20:19:30.386Z INFO @wdio/local-runner: Shutting down spawned worker
2021-09-30T20:19:30.639Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2021-09-30T20:19:30.639Z INFO @wdio/local-runner: shutting dow
```
