### ISSUE TITLE
v5: spec reporter caches output until completion, making repl impossible

### ISSUE THREAD

**Issue by dylang** [webdriverio/webdriverio#2956] opened 2018-09-14 15:26 UTC
## The problem

I'm trying to see what's happening *while* tests are running. `console.log`, `beforeCommand`, and `browser.debug` all seem to be hidden by either Mocha or the `spec` reporter until the test is complete. This makes logging what selectors the browser is actively waiting for or using the repl impossible.

## Environment

* WebdriverIO version: `5.0.0-beta.2`
* Node.js version: `10`
* Standalone mode or WDIO Testrunner: `wdio runner via cli api`
* if wdio testrunner, running synchronous or asynchronous tests: `sync`
* Additional wdio packages used (if applicable): `mocha`, `spec`

## Details

The new mocha reporter has a timer and seems to try to keep the UI clean until tests are complete. This is nice for a dashboard, but not for development. 

If this is a feature request for a new reporter I can re-word this ticket or create a new one.

## Link to Selenium/WebdriverIO logs

What we see when tests are running and `browser.debug` was called. Typing and pressing enter don't help.
<img width="383" alt="screen shot 2018-09-14 at 11 23 40 am" src="https://user-images.githubusercontent.com/51505/45559539-bc1ffa80-b810-11e8-9252-657060065d90.png">

## Code To Reproduce Issue

```
    framework: 'mocha',
    reporters: [ 'spec' ],
```

```js
    it('Good luck seeing the repl', () => {
        browser.url(process.env.BROWSER_TESTS_BASE_PATH || '/');
        browser.debug();
    });
```

**Comment by christian-bromann** [comment] 2018-09-15 09:29
Duplicate of #2871

**Closed by christian-bromann** 2018-09-15 09:29 UTC
