### ISSUE TITLE
[🐛 Bug]: browser.getMetrics is not a function in wdio 7.8.0

### ISSUE THREAD

**Issue by viswa-uipath** [webdriverio/webdriverio#7768] opened 2021-11-30 06:46 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.8.0

### Node.js Version

14.17.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    browser: 'chrome',
    version: '96.0.4664.45',
    platformName: 'Windows 10'
}
```

### What happened?

`browser.enablePerformanceAudits` is accessible while `browser.getMetrics` is not accessible. No error or warnings in console.

### What is your expected behavior?

`browser.getMetrics` should not throw an error

### How to reproduce the bug.

```
describe('Sample', () => {

	before(() => {
		browser.enablePerformanceAudits({
			networkThrottling: 'Regular 3G',
			cpuThrottling: 4,
			cacheEnabled: false
		});
	});

	it('should show metrics', () => {
		browser.url('http://json.org')
		let metrics = browser.getMetrics()
		console.log(metrics)
	});

	after(() => {
		browser.disablePerformanceAudits();
	})
});
```

### Relevant log output

```typescript
TypeError: browser.getMetrics is not a function
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment] 2021-12-03 14:49
Duplicate of #7778

**Closed by erwinheitzman** 2021-12-03 14:49 UTC
Labels: Bug 🐛, Needs Triaging ⏳
