### ISSUE TITLE
FR: introduce possibilty to work with file uploads then using remote selenium GRID for webdriver.io [v5]

### ISSUE THREAD

**Issue by erinev** [webdriverio/webdriverio#3889] opened 2019-04-26 05:10 UTC
**Is your feature request related to a problem? Please describe.**
`Context:`We have an UI which allows users to upload Banner (ad) files (.png, .html, .zip) to our system and allows to manage (edit/reupload/etc) those created banners through UI. We developing our tests locally (using local selenium standalone - using `webdriver-manager` npm package) but for real execution every time we release tests are run in remote selenium GRID (which is setuped by our devops team).  

We do file upload this way: 
1) we have file upload input 
2) We use [addValue](https://webdriver.io/docs/api/element/addValue.html) method to add file to upload input
3) After file is added to input we press upload button  
```
const fullPathToFile = 'C:/projectDirectory/test-files/test_file.jpg';  
$('input[name="files"]').addValue(fullPathToFile);  
$('a.start-upload').click();
```
It works well locally (using standalone version - webdriver-manager start) all case passes and file is actually uploaded but then we run tests cases with `--remote` flag (it executes test cases in remote selenium grid) it fails randomly with message: `ERROR webdriver: Request failed due to unknown error: path is not absolute: C:/projectDirectory/test-files/test_file.jpg` (event though it cleary seems that path is absolute.  
We face same issue before using `angular/potractor` framework and we managed to solve remote files uploading problem with approach suggested in this protractor [issue](https://github.com/angular/protractor/issues/2153#issuecomment-123439603).  
You need just set remote file detector policy to selenium webdriver:
```
var remote = require('selenium-webdriver/remote');
browser.setFileDetector(new remote.FileDetector());
```
But if i understand correctly webdriver.io doesn't allow to access slenium webdriver it self using `browser` object (i tried to call same method on webdriver.io browser, but got setFileDetector is not defined)

**Describe the solution you'd like**
Possibility to remotel'y (using remote selenium grid) upload files. If issue is really can be solved the way i described above (by setting setFileDetector to remote to selenium webdriver) so some way to set remote file detector is provided.  
OR *instructions how to perform file upload in remote selenium grid in some other way*

**Describe alternatives you've considered**
We did not find any alternatives yet. If we will find some workarround, we will update this FR.

**Additional context**
We are using such packages and versions of webdriver.io: [package.json](https://github.com/erinev/wdio-selenium-tests-playground/blob/master/package.json#L26). Browser - Chrome/Firefox, environment WINDOWS (10/8.1)

**Comment by erinev** [comment] 2019-04-26 07:16
i think its same/similiar issue as: https://github.com/webdriverio/webdriverio/issues/3838

**Comment by christian-bromann** [comment] 2019-04-29 15:37
Duplicate of #3632

**Closed by christian-bromann** 2019-04-29 15:37 UTC
