### ISSUE TITLE
[🐛 Bug]: Devtools Crashes when iframe is Removed from Page

### ISSUE THREAD

**Issue by reecehughes-nw** [webdriverio/webdriverio#8071] opened 2022-03-01 19:28 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.16

### Node.js Version

16.13.2

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  browserName: 'chrome'
}
// Occurred on multiple versions of Chrome, currently using 98.0.4758.102.
```

### What happened?

WDIO crashes with the error

> Unhandled promise rejection: ProtocolError: Protocol error (Target.attachToTarget): No target with given id found

when using the devtools protocol if an `iframe` is removed from the page.  The `iframe` must have a PDF as the source, so the Chrome previewer is used.  Using another web page as the source does not reproduce the issue.

The problem seems to originate with `_targetDestroyedHandler` thinking a page was destroyed when it is actually a `webview` that was destroyed.

### What is your expected behavior?

Removing an `iframe` from the page should be handled and not crash the test.

### How to reproduce the bug.

Steps to Reproduce:

An example is in this [Github repo](https://github.com/reecehughes-nw/wdio-devtools-iframe-bug) but the basics are below.

This must be run using the `devtools` automation protocol.

Setup `index.html` with an `iframe` that has a PDF as the `src` and a button that removes that `iframe` from the page.

```html
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>WDIO iframe</title>
  </head>
  <body>

    <button id="hide" onclick="hide()">Hide iframe</button>

    <div id="frame"><iframe id="frame" src="./pdf-src.pdf" width="500" height="500"></iframe></div>

    <script>
      function hide() {
        document.querySelector('#frame').innerHTML = '';
      }
    </script>
  </body>
</html>
```

Create a test that clicks the button and waits.  It is the command after the `iframe` is removed that fails.  I used Jasmine the for example below.

```js
describe('iframe Test', () => {
  it('Hide iframe', async () => {
    await browser.url('http://localhost:8081/');

    await browser.pause(2000);
    await $('#hide').click();

    // This command fails.
    await browser.pause(2000);
    });
});
```

Run the test, it will fail with this error: `Unhandled promise rejection: ProtocolError: Protocol error (Target.attachToTarget): No target with given id found`

### Relevant log output

```typescript
Chrome 98.0.4758.109 darwin #0-0] Unhandled promise rejection: ProtocolError: Protocol error (Target.attachToTarget): No target with given id found
[Chrome 98.0.4758.109 darwin #0-0] error properties: Object({ originalMessage: 'No target with given id found' })
[Chrome 98.0.4758.109 darwin #0-0] ProtocolError: Protocol error (Target.attachToTarget): No target with given id found
[Chrome 98.0.4758.109 darwin #0-0]     at new Promise (<anonymous>)
[Chrome 98.0.4758.109 darwin #0-0]     at Array.map (<anonymous>)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2022-03-01 19:58
Thanks for reporting!

I assume the problem is somewhere where we [deal with page handles](https://github.com/webdriverio/webdriverio/blob/main/packages/devtools/src/devtoolsdriver.ts#L117-L289) in our devtools package.

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by reecehughes-nw** [comment] 2022-03-07 15:42
It looks like `DevToolsDriver._targetDestroyedHandler` assumes every target is a page.  Puppeteer has several target types it could be (https://github.com/puppeteer/puppeteer/blob/main/src/common/Target.ts#L171). I’m not sure how other types should be handled but for my specific use case ignoring when `'webviews'` are destroyed works fine.  Should the function ignore anything  that doesn't have a type of `'page'`?

**Comment by christian-bromann** [comment] 2024-05-28 06:14
I will go ahead and close the issue as we will deprecate the `devtools` package. We recommend to run tests in WebdriverIO with the WebDriver protocol. If there are any further questions, don't hesitate to reach out.

**Closed by christian-bromann** 2024-05-28 06:14 UTC
Labels: Bug 🐛, help wanted
