### ISSUE TITLE
Missing log colors on Travis-CI after migrating from v4 to v5

### ISSUE THREAD

**Issue by jlchereau** [webdriverio/webdriverio#3212] opened 2018-12-30 17:51 UTC
### Environment:

 - **WebdriverIO version:** 5.1.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 11.6.0
 - **NPM version:** 6.5.0
 - **Browser name and version:** N/A
 - **Platform name and version:** N/A
 - **Additional wdio packages used (if applicable):** @wdio/spec reporter, @wdio/selenium-standalone service

### Config of WebdriverIO

The **coloredLogs** option does not seem to be documented anymore: https://webdriver.io/docs/options.html.

in wdio.conf.js after migrating from webdriverio v4 to v5, I have kept option:

```
coloredLogs: true,
```

Note: but I have changed dot-reporter for spec-reporter.

### Describe the bug

With webdriverio **v4** on Travis-CI with colours (see https://travis-ci.org/kidoju/Kidoju-Blog/jobs/471099689):

![image](https://user-images.githubusercontent.com/2556751/50549773-e0d29d80-0c5a-11e9-9085-6c32b1ce0e47.png)

With webdriverio **v5** on Travis-CI now without colours (see https://travis-ci.org/kidoju/Kidoju-Blog/jobs/473622155):

![image](https://user-images.githubusercontent.com/2556751/50549787-0cee1e80-0c5b-11e9-89b5-37068fab55a4.png)

**Comment by christian-bromann** [comment] 2019-04-04 12:28
As we are using Chalk the color support is not up to WebdriverIO. Looking into the Travis CI build I also see Jest running without colors. Closing as I don't see anything we can fix here.

**Comment by babilog** [comment] 2019-07-23 00:34
I think the issue here is that it's piping the output of the spawned processes and its stripping away all the color and formatting. It's occuring on the `local-runner -> worker.js`. If we remove the custom formatting on the messages, thus removing the piping of the stderr and stdout and just output straight to the terminal, then we'd get all the formatting and color from the logged messages. What are your thoughts around this? 

```const childProcess = (this.childProcess = _child_process.default.fork(
      _path.default.join(__dirname, 'run.js'),
      argv,
      {
        cwd: process.cwd(),
        env: runnerEnv,
        execArgv,
        stdio: [
          'pipe', // Use parent's stdin for child
          0, // avoid pipe for stdout
          0, // avoid pipe for stderr
          'ipc' // required for stdio prop
        ]
      }
    ));```

This would mean that we'd loose the custom formatting with the `cid` pre-pended to every logged line though.

**Comment by mgrybyk** [comment] 2019-07-23 05:49
Hey guys, colors should work fine by simply adding env var `FORCE_COLOR=1`. Can you try?

@christian-bromann @babilog

https://webdriver.io/docs/jenkins.html

**Comment by mgrybyk** [comment] 2019-07-23 05:50
This is not wdio feature, it is chalk https://www.npmjs.com/package/chalk#chalksupportscolor

**Comment by babilog** [comment] 2019-07-23 16:55
Tried `FORCE_COLOR` but it didn't do the trick. To provide more context, we are using a custom debug util (https://www.npmjs.com/package/debug) to capture custom logs from within our step definition files and page object files. `debug` allows us to specify which logs we want to show and generally gives us more flexibility than the `logger` service from webdriverio. On webdriver v4 we were able to see the logs with a different color per log module. For example:

![image](https://user-images.githubusercontent.com/14218994/61730496-7fcdfc80-ad47-11e9-8647-49542b1dc617.png)

Here I just disabled the piping of the output to be able to get the debug log output from the forked processes to show the formatting and color appropriately. 

Could this be something we could toggle based on a config value on the wdio config? Something like `pipeLogOutput` or `preserveLoggingFormat` default to true, if false, then we could bypass piping the output of the forked processes and use the `stdio = 'inherit'` option? Would definitely not mind to raise another issue and submit a PR for this if it makes sense design wise.

**Comment by mgrybyk** [comment] 2019-07-23 17:15
How can I reproduce it?

**Comment by babilog** [comment] 2019-07-23 18:23
I went ahead and setup a sample project with the debug module: https://github.com/babilog/demo-webdriverio-cucumber 

You can run `yarn log:test` to get the debug output.

You should see the following: 

![image](https://user-images.githubusercontent.com/14218994/61737065-73e93700-ad55-11e9-8439-9560fe027375.png)

**Comment by christian-bromann** [comment] 2019-07-23 18:25
let's reopen and figure this out

**Comment by babilog** [comment] 2019-07-23 19:19
Here's a quick POC on adding a config flag for `preserveLoggingFormat` that toggles between either piped or outputting straight to the parent console.

https://github.com/babilog/webdriverio/commit/b1ea09e3e40076ea150d71d1db6c6cc670766ba5

**Comment by mgrybyk** [comment] 2019-07-23 19:26
@babilog how does `steps:contact` is generated?
Thank you for POC. I'd like to see something that would work for everyone

**Comment by mgrybyk** [comment] 2019-07-23 19:47
![image](https://user-images.githubusercontent.com/25589559/61742465-79657200-ad93-11e9-977d-440cad8dc1d4.png)

**Comment by babilog** [comment] 2019-07-23 20:04
Hm that's very strange, not sure how its working for you. I've tried a different terminal than zsh as well and it seems to be replicating the same issue.

**Comment by babilog** [comment] 2019-07-23 20:06
I'm running node 11.12.0. Not sure if that would impact this though 🤔 . Are you running something different?

**Comment by mgrybyk** [comment] 2019-07-23 20:07
As I've mentioned, steps to reproduce would be helpful. 

I have no idea how should debug module work. 
Printing colored messages to console works just fine

**Comment by babilog** [comment] 2019-07-23 20:11
Oops, missed that earlier message. If you look under the `test -> e2e -> steps -> Contact.steps.js`, you'll see the debug module declared. Running it using `yarn log:test` simply filters for that specific debug module name defined on that file.

**Comment by mgrybyk** [comment] 2019-07-23 20:13
Yes, and we are not responsible for debug package.
If you change it to console.log and make your output colored, it will be colored

**Comment by mgrybyk** [comment] 2019-07-23 20:16
`console.log('\x1b[35m FOOBAR \x1b[0m')`

**Comment by babilog** [comment] 2019-07-23 20:19
Hm I see. Then I should probably look into the `debug` module to see why its not working as expected. Thanks for taking a look @mgrybyk , appreciate the time.

**Comment by babilog** [comment] 2019-07-23 20:24
Ah, looks like its an issue with how the processes are spawn and the debugModule. As per issue solution here: https://github.com/visionmedia/debug/issues/558 ... I'm assuming adding this flag to the spawned process step on `worker.js` is not something that would be approved?

**Comment by babilog** [comment] 2019-07-23 20:27
Adding `DEBUG_COLORS: true` when you run wdio should do the trick 👍

**Comment by babilog** [comment] 2019-07-23 20:27
I'm good closing this one 👍

**Closed** 2019-07-23 20:41 UTC
Labels: Bug🐛, good first pick, help wanted

**Comment by mgrybyk** [comment] 2019-07-23 21:04
@babilog thank you for investigating this!
