### ISSUE TITLE
getText broken?

### ISSUE THREAD

**Issue by lscordilis** [webdriverio/webdriverio#633] opened 2015-07-15 15:28 UTC
So I'm just following Sam Hatoum's simple Velocity-Cucumber tutorial which uses Webdriver to define the testing steps as such:

```
    this.Given(/^I have created a landing page with the heading "([^"]*)"$/, function(heading, callback) {
        this.server.call('page/create', {   //create a landing page with heading whatever
            path: '/',
            heading: heading
        }).then(callback);
    });

    this.When(/^a user navigates to the landing page$/, function(callback) {
        this.client.url(process.env.ROOT_URL).call(callback);   //just go to the root url of the page
    });

    this.Then(/^they see the heading "([^"]*)"$/, function(heading, callback) {
        this.client.waitForVisible('h1')
            .getText('h1', function(text) {
                console.log(text);  //this is undefined?
            }).should.become(heading).and.notify(callback);
    });
```

The contents of the h1 tag are returned as undefined, when clearly as you can see below in the testing mirror app it is certainly there. 

![image](https://cloud.githubusercontent.com/assets/12753650/8702109/bd32d68a-2ae3-11e5-91c1-3d87b1d61186.png)

I'm following the tutorial verbatim for now and, having looked at the Webdriver docs, getText is still supposed to work this way. Have you changed the operation of getText recently?

**Comment by christian-bromann** [comment] 2015-07-15 15:32
It should be:

```js
    this.Given(/^I have created a landing page with the heading "([^"]*)"$/, function(heading, callback) {
        this.server.call('page/create', {   //create a landing page with heading whatever
            path: '/',
            heading: heading
        }).then(callback);
    });

    this.When(/^a user navigates to the landing page$/, function(callback) {
        this.client.url(process.env.ROOT_URL).call(callback);   //just go to the root url of the page
    });

    this.Then(/^they see the heading "([^"]*)"$/, function(heading, callback) {
        this.client.waitForVisible('h1')
            .getText('h1', function(err, text) {
                console.log(text);  //this is undefined?
            }).should.become(heading).and.notify(callback);
    });
```

If you pass a callback as last argument the parameter of that callback are error and result (nodejs style). However I would recommend to use `.then(function(result) {...`

**Comment by lscordilis** [comment] 2015-07-15 15:45
Thanks for the quick response. Unfortunately, it still returns undefined. 

This is how the code was originally, and didn't work.
```
    this.Then(/^they see the heading "([^"]*)"$/, function(heading, callback) {
        this.client.waitForVisible('h1')
            .getText('h1').should.become(heading).and.notify(callback);
    });
```

And the Velocity reporter showed:
```
AssertionError: expected '' to deeply equal 'My Book'  ...
```
I put in the console log to see what was causing the test to fail. Then, after following your advice, both this:
```
    this.Then(/^they see the heading "([^"]*)"$/, function(heading, callback) {
        this.client.waitForVisible('h1')
            .getText('h1', function(err, result) {
                console.log(result);    //still undefined
            }).should.become(heading).and.notify(callback);
    });
```
and this
```
    this.Then(/^they see the heading "([^"]*)"$/, function(heading, callback) {
        this.client.waitForVisible('h1')
            .getText('h1').then(function(result) {
                console.log(result);
            }).should.become(heading).and.notify(callback);
    });
```
have the same problem. 

Then in the Velocity reporter it shows:
```
AssertionError: expected undefined to deeply equal 'My Book'  ...
```

I'm running all of this on Windows and testing it in Google Chrome, if that's of any consequence. Everything in Meteor is up to date, as well, I just checked.

Thanks again for your help :)

**Comment by christian-bromann** [comment] 2015-07-15 15:48
could you replace `getText` with `getHTML` to see what this command returns?

**Comment by lscordilis** [comment] 2015-07-15 16:05
Huh, yeah good call. Looks like the Webdriver client doesn't think there are any contents. 

```
    this.Then(/^they see the heading "([^"]*)"$/, function(heading, callback) {
        this.client.waitForVisible('h1')
            .getHTML('h1').then(function(result){
                console.log(result);
            }).should.become(heading).and.notify(callback);
    });
```
![image](https://cloud.githubusercontent.com/assets/12753650/8702867/3e1fc542-2ae8-11e5-9c53-ce7b1a5de67b.png)

I then tested it with a ```<p id="test">test</p>``` in the body,

```
    this.Then(/^they see the heading "([^"]*)"$/, function(heading, callback) {
        console.log(heading);
        this.client.waitForVisible('#test')
            .getText('#test').then(function(result){
                console.log(result);
            }).should.become(heading).and.notify(callback);
    });
```
and getText prints the correct text in the console,
![image](https://cloud.githubusercontent.com/assets/12753650/8703054/46c0baac-2ae9-11e5-87c5-d9b30f6639dc.png)

but Velocity still thinks it's undefined :/
```
AssertionError: expected undefined to deeply equal 'My Book'  ...
```

**Comment by christian-bromann** [comment] 2015-07-15 16:16
mhm according to the result: `<h1></h1>` there is nothing in the heading. Does it get generated by JS? `getHTML` executes `document.queryElement(selector).outerHTML` and returns it.

**Comment by christian-bromann** [comment] 2015-07-15 16:17
maybe add `pause(1000)` before the `getText` command.

**Comment by lscordilis** [comment] 2015-07-15 16:27
Yes, it is bound using Meteor in the client.
```
<body>
    {{> landingPage }}
</body>

<template name="landingPage">
    <h1>{{ page.heading }}</h1>
    <p id="test">test</p>
</template>
```
I also tried moving the test out of the template and added a wait for body command.
```
<body>
    <p id="test">test</p>
    {{> landingPage }}
</body>

<template name="landingPage">
    <h1>{{ page.heading }}</h1>
</template>
```
```
    this.Then(/^they see the heading "([^"]*)"$/, function(heading, callback) {
        console.log(heading);
        this.client
            .waitForVisible('body *')
            .waitForVisible('#test').pause(1000)
            .getText('#test').then(function(result){
                console.log(result);
            }).should.become(heading).and.notify(callback);
    });
```

The pause didn't seem to make a difference, either. I tried with both 1000 ms and 5000 ms. This is starting to look more like a Velocity issue. Should I copy Sam Hatoum on this?

**Comment by christian-bromann** [comment] 2015-07-15 16:34
mhm .. that's weird. So you see everything got rendered in Chrome before the script queries the text on the page?

**Comment by lscordilis** [comment] 2015-07-15 16:38
Yes, when I go to the browser at the Velocity mirror's address, it shows everything just fine

![image](https://cloud.githubusercontent.com/assets/12753650/8703988/46271cda-2aee-11e5-89b1-dd3ff2b74594.png)

**Comment by christian-bromann** [comment] 2015-07-15 16:42
I see. Seems like a basic example page. Could you put that to a new repository with a package.json and everything so I can download it and debug?

**Comment by lscordilis** [comment] 2015-07-15 16:42
And if so, that would imply that the ```waitForVisible``` commands we not working properly. I added one more to the previous test and it doesn't fail.
```
    this.When(/^a user navigates to the landing page$/, function(callback) {
        this.client.url(process.env.ROOT_URL)
            .waitForVisible('body *')
            .call(callback);   //just go to the root url of the page
    });

    this.Then(/^they see the heading "([^"]*)"$/, function(heading, callback) {
        console.log(heading);
        this.client
            .waitForVisible('body *')
            .waitForVisible('#test').pause(1000)
            .getText('#test').then(function(result){
                console.log(result);
            }).should.become(heading).and.notify(callback);
    });
```

**Comment by christian-bromann** [comment] 2015-07-15 16:44
well the element seems to be there but not text in it

**Comment by lscordilis** [comment] 2015-07-15 16:47
Alright, I'll do that now. I really appreciate you sparing so much of your time for a noob like myself :)

**Comment by lscordilis** [comment] 2015-07-15 17:03
Here's the link to the repo with everything:

https://github.com/lscordilis/meteor-cucumber-demo

**Comment by christian-bromann** [comment] 2015-07-15 18:17
Thanks! I will take a look on it

**Comment by lscordilis** [comment] 2015-07-24 16:45
I went through the whole tutorial from scratch just in case and I'm getting stuck in the same place. Did you ever get a chance to check it out? I commented on Sam Hatoum's website a couple days ago and linked him to the issue but he hasn't gotten back to me yet.

**Comment by sircharleswatson** [comment] 2015-07-24 20:49
@lscordilis @christian-bromann I'm running into the same issue.

I did this and it passed, but obviously it's not ideal.

```
this.Then(/^they see the heading "([^"]*)"$/, function (heading, callback) {

    var htmlHeading = "<h1>" + heading + "</h1>";

    this.client.pause(5000).waitForVisible('h1').
      getHTML('h1').should.become(htmlHeading).and.notify(callback);

  });
```

**Comment by samhatoum** [comment] 2015-07-24 21:23
Hey guys

getText works, here's how to implement the step above:

```javascript
this.Then(/^they see the heading "([^"]*)"$/, function(heading) {
    return this.client
      .waitForExist('h1')
      .getText('h1').should.eventually.equal(heading);
});
```

I need to update the book. The issue is due to upgrading to WebdriverIO 3.0 without updating the examples. I'll get those updated shortly.

**Comment by lscordilis** [comment] 2015-07-24 21:46
Thank you very much. Was scratching my head about this for a while :)

**Comment by christian-bromann** [comment] 2015-08-05 07:07
thx @samhatoum for the clarification. Closing

**Closed by christian-bromann** 2015-08-05 07:07 UTC
Labels: Question
