### ISSUE TITLE
Unable to use expect assertion with multiremote feature

### ISSUE THREAD

**Issue by Amrkamel1** [webdriverio/webdriverio#5995] opened 2020-10-15 21:28 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:**6.6.4
 - **Mode:** multiremote
 - **If WDIO Testrunner, running sync/async:**sync
 - **NPM version:** 6.14.4
 - **Browser name and version:** 86.0.4240.75
 - **Platform name and version:** win10
 - **Additional wdio packages used (if applicable):** 
```
"keywords": [],
  "author": "aMr kaMel",
  "license": "ISC",
  "dependencies": {
    "@wdio/browserstack-service": "^6.6.3",
    "@wdio/cli": "^6.6.4",
    "eslint": "^7.11.0",
    "frisby": "^2.1.3",
    "wdio-chromedriver-service": "^6.0.4",
    "webdriverio": "^6.6.4"
  },
  "devDependencies": {
    "@wdio/allure-reporter": "^6.6.3",
    "@wdio/appium-service": "^6.6.3",
    "@wdio/dot-reporter": "^6.6.0",
    "@wdio/local-runner": "^6.6.4",
    "@wdio/mocha-framework": "^6.6.3",
    "@wdio/selenium-standalone-service": "^6.6.5",
    "@wdio/spec-reporter": "^6.6.3",
    "@wdio/sync": "^6.6.4",
    "@wdio/concise-reporter": "^6.6.0",
    "chai": "^4.2.0",
    "mocha": "^8.1.3"
  }
```

**Config of WebdriverIO**

```
exports.config = {
  specs: ['./src/test/specs/CrossPlatform_Suite.js'],

  capabilities: caps.CrossCaps,
  // capabilities: caps.chromeAndBs,



services: [
  ['selenium-standalone', {
      args: {
        seleniumArgs: ['-port', '4444']
      },
  }],  
  // ['browserstack'],
  ['appium',{
    command : 'appium',
    args: {
        debugLogSpacing: true,
        sessionOverride: true,
        port: 4728,
        allowInsecure:'chromedriver_autodownload'
    },
  }]
],
```

**Describe the bug**

**To Reproduce**

[Include code or an example repository that can easily be set up]

**Expected behavior**
Should be able to use expect assertion command

**Log**
![image](https://user-images.githubusercontent.com/32042806/96187753-d4a5f600-0f3d-11eb-8be3-3fb4d3ab6752.png)

**Additional context**
same script is working fine with expect assertion without multiremote, workaround is to user assert command from chai

```
    assert.isTrue(p.theNew.isDisplayed())  ---> working
     expect(p.theNew).toBeDisplayed()   ---> not working in multiremotre mode 
```

**Comment by christian-bromann** [comment] 2020-10-15 22:59
Duplicate of https://github.com/webdriverio/expect-webdriverio/issues/106

**Closed by christian-bromann** 2020-10-15 22:59 UTC
