### ISSUE TITLE
Latest chrome browser version (65.0.3325.162) is not supporting webdriverio

### ISSUE THREAD

**Issue by KumarSunil20** [webdriverio/webdriverio#2647] opened 2018-03-14 12:31 UTC
## The problem

Latest chrome browser version (65.0.3325.162) is not supporting webdriverio

Browser is getting launched and also hits the url successfully.

but while performing operation on UI is throwing different error.

Here are some error I have got:

Case 1: Typing in a Text box
Method Used:  setValue()

unknown error: call function result missing 'value'
[chrome #0-0] Error: An unknown server-side error occurred while processing the command.
[chrome #0-0]     at elementIdValue("0", "text123")

Case 2: Selecting a value from drop down
Method used: selectByVisibleText()

stale element reference: element is not attached to the page document
[chrome #0-0] Error: An element command failed because the referenced element is no longer attached to the DOM.
[chrome #0-0]     at elementIdClick("1")

Note: Same code was working fine with the previous version of Chrome browser (64.0.3282.186)
Since there is no way we can downgrade chrome version we have to go for the latest chrome browser only.

Since it works well in Firefox and Chrome previous version I don't think it is a problem with webdriverIO.

## Environment

* WebdriverIO version: v4.6.2
* Node.js version: v8.9.1
* wdio testrunner
* if wdio testrunner - asynchronous tests:

capabilities: [{
        // maxInstances can get overwritten per capability. So if you have an
        // in-house Selenium grid with only 5 firefox instance available you can
        // make sure that not more than 5 instance gets started at a time.
        maxInstances: 1,
        browserName: 'firefox',
    }, {
        browserName: 'chrome',
        chromeOptions: {
            args: ["start-maximized"],
            prefs: {
                'download.default_directory': __dirname + '\\downloadedFiles',
                'profile.default_content_settings.popups': 0
            },
        },
    }
    ],

## Code To Reproduce Issue [ Good To Have ]
Given(
        /^User login into application"$/,
() => {
     openWebsite(browser.options.baseUrl);
     selectOption('text', 'Name', 'locator');
}
);

Just let me know if anybody can reproduce this issues and give some solution to problem stated.

**Comment by BorisOsipov** [comment] 2018-03-14 12:37
Duplicate of https://github.com/webdriverio/webdriverio/issues/2631

**Closed by BorisOsipov** 2018-03-14 12:37 UTC
