### ISSUE TITLE
[🐛 Bug]: before() hook fail doesn't fail the test itself

### ISSUE THREAD

**Issue by HananArgov** [webdriverio/webdriverio#12138] opened 2024-01-31 19:59 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.26.3

### Node.js Version

18.12.1

### Mode

WDIO Testrunner

### What happened?

if the `before` hook fails, it doesn't fail the test itself, like a `beforeAll` will.
this can cause a test to try and use a variable, which has been failed to initiate during the `before` hook

### What is your expected behavior?

I expect that the test will fail like if `beforeAll` fails

### How to reproduce the bug.

create a new wdio with examples
in wdio.conf replace the commented out `before` hook with the following:

```
  async before() {
     throw new Error('this is a failed before hook');
}
```
run the example test

### Relevant log output

```typescript
the hook fails, but the test will pass
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2024-01-31 21:05
@HananArgov thanks for raising the issue.

This is currently an expected behavior and we might change that with v9. To make a hook actually fail the test use [`SevereServiceError`](https://webdriver.io/docs/customservices/#service-error-handling). I will close the issue but definitely up to change this in the next major release.

**Closed by christian-bromann** 2024-01-31 21:05 UTC
Labels: Bug 🐛, Needs Triaging ⏳

**Comment by HananArgov** [comment] 2024-02-01 08:37
@christian-bromann thank you very much for the fast reply.
I hope this will be addressed in the next major release

**Comment by Marcono1234** [comment] 2026-05-06 14:46
> This is currently an expected behavior and we might change that with v9.

@christian-bromann, was this behavior actually changed for v9? I am using v9.27.1 but the behavior still seems to be the same. And even wrapping any errors in `SevereServiceError` only seems to work for some hooks? For example throwing it in an `async before()` method of my custom service does not cause execution to fail.

It seems this behavior is a common source of confusion for users, see also other previous issues:
- #5398
- #5889
- #7032
- #8013
- #14045

I understand your rationale for the current behavior (see https://github.com/webdriverio/webdriverio/issues/5398#issuecomment-629082304), but I think it would be better if services added error handling and error suppression explicitly themselves, since they are also the ones which can decide which errors are critical and which ones aren't.

Generally treating all errors (except for `SevereServiceError` in some cases) as ignorable is in my opinion rather error-prone. Often such hooks perform important setup or cleanup actions, and if those fail the complete test suit may fail, possibly with highly confusing errors. Finding the actual cause somewhere buried in the log of all the test failures can then be difficult.

Ideally Webdriver would fail fast for any errors thrown by hooks, and not even require wrapping them in `SevereServiceError`, since that would require considering all potential error cases or just wrapping all your hook code in a `try`-`catch` which rethrows the error as `SevereServiceError`, which is quite verbose.

What do you think? Could that behavior be opt-in or opt-out at least?
