### ISSUE TITLE
BrowserStack session times out while waiting for wdio to send commands after initially establishing session

### ISSUE THREAD

**Issue by ianrenauld** [webdriverio/webdriverio#5558] opened 2020-06-29 19:39 UTC
**Environment:**
 - **WebdriverIO version:v6.1.22**
 - **Mode: WDIO Testrunner**
 - **Running sync**
 - **Node.js version: 10.15.0**
 - **NPM version: 6.14.5**
 - **Browser name and version: Chrome 83 (but issue happens with latest Firefox as well)**
 - **Platform name and version: macOS Catalina**
 - **Additional wdio packages used (if applicable): @wdio/browserstack-service version: 6.1.15** 

**Config of WebdriverIO**
See attached repo in To Reproduce, but it's basically the default config provided with Webdriver.io (by following the Getting Started docs from the Website) with BrowserStack service config added on.

**Describe the bug**
Sometimes the `wdio` runner hangs after starting a session, while BrowserStack has started the session with a browser and is just waiting for commands from wdio, which never come. We have to kill the session by CTRL-C (which is shown in the logs below, in case the behavior after the CTRL-C was somehow worthwhile), otherwise nothing ever happens (no Mocha timeout or other timeout happens).  The BrowserStack session itself times out at some point (STOP_SESSION - BROWSERSTACK_IDLE_TIMEOUT is shown in their Text Logs), but nothing ever happens with the `wdio` runner.

**To Reproduce**

Use this repo: https://github.com/ianrenauld/bs_repro but basically it's just the Getting Started test from the Webdriver.io website with added config to user BrowserStack. The README.md file in the repo explains how to proceed, but it's nothing special except configuring the username and access key for BrowserStack.

**Expected behavior**
Sessions should always be established properly - but right now it fails like 50% of the time. We've been running tests with wdio v5 and BrowserStack for months without seeing this type of issue, but we've had problems with BrowserStack as soon as we tried wdio v6 last week.

**Log**
```
Execution of 1 spec files started at 2020-06-29T18:54:51.166Z

2020-06-29T18:54:51.170Z DEBUG @wdio/utils:initialiseServices: initialise service "browserstack" as NPM package
(node:14390) ExperimentalWarning: The dns.promises API is experimental
(node:14390) ExperimentalWarning: The fs.promises API is experimental
2020-06-29T18:54:51.186Z INFO @wdio/cli:launcher: Run onPrepare hook
2020-06-29T18:54:51.186Z INFO @wdio/browserstack-service: browserstackLocal is not enabled - skipping...
2020-06-29T18:54:51.187Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2020-06-29T18:54:51.188Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.conf.browserstack.js,--spec,test/specs/basic2.js
[0-0] (node:14391) ExperimentalWarning: The dns.promises API is experimental
[0-0] (node:14391) ExperimentalWarning: The fs.promises API is experimental
[0-0] 2020-06-29T18:54:51.617Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2020-06-29T18:54:51.640Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2020-06-29T18:54:51.651Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
[0-0] RUNNING in chrome - /test/specs/basic.js
[0-0] 2020-06-29T18:54:51.784Z DEBUG @wdio/utils:initialiseServices: initialise service "browserstack" as NPM package
[0-0] 2020-06-29T18:54:51.797Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2020-06-29T18:54:51.798Z INFO webdriverio: Initiate new session using the webdriver protocol
[0-0] 2020-06-29T18:54:51.800Z INFO webdriver: [POST] https://hub-cloud.browserstack.com/wd/hub/session
[0-0] 2020-06-29T18:54:51.800Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'chrome' } }
^C

Ending WebDriver sessions gracefully ...
(press ctrl+c again to hard kill the runner)
2020-06-29T18:57:03.233Z INFO @wdio/local-runner: Shutting down spawned worker
[0-0] 2020-06-29T18:57:03.232Z INFO @wdio/local-runner: Received SIGINT, giving process 5000ms to shutdown gracefully
2020-06-29T18:57:03.234Z INFO @wdio/local-runner: Run worker command: endSession
[0-0] 2020-06-29T18:57:03.237Z INFO webdriver: COMMAND deleteSession()
[0-0] 2020-06-29T18:57:03.238Z INFO webdriver: [DELETE] https://hub-cloud.browserstack.com/wd/hub/session/dae3bd410a0874ba8b88e5beb60896bb991238e3
2020-06-29T18:57:03.488Z INFO @wdio/local-runner: Waiting for 1 to shut down gracefully
2020-06-29T18:57:03.740Z INFO @wdio/local-runner: Waiting for 1 to shut down gracefully
2020-06-29T18:57:03.991Z INFO @wdio/local-runner: Waiting for 1 to shut down gracefully
2020-06-29T18:57:04.245Z INFO @wdio/local-runner: Waiting for 1 to shut down gracefully
2020-06-29T18:57:04.499Z INFO @wdio/local-runner: Waiting for 1 to shut down gracefully
2020-06-29T18:57:04.753Z INFO @wdio/local-runner: Waiting for 1 to shut down gracefully
2020-06-29T18:57:05.006Z INFO @wdio/local-runner: Waiting for 1 to shut down gracefully
2020-06-29T18:57:05.261Z INFO @wdio/local-runner: Waiting for 1 to shut down gracefully
2020-06-29T18:57:05.511Z INFO @wdio/local-runner: Waiting for 1 to shut down gracefully
2020-06-29T18:57:05.765Z INFO @wdio/local-runner: Waiting for 1 to shut down gracefully
2020-06-29T18:57:06.018Z INFO @wdio/local-runner: Waiting for 1 to shut down gracefully
2020-06-29T18:57:06.271Z INFO @wdio/local-runner: Waiting for 1 to shut down gracefully
2020-06-29T18:57:06.523Z INFO @wdio/local-runner: Waiting for 1 to shut down gracefully
2020-06-29T18:57:06.778Z INFO @wdio/local-runner: Waiting for 1 to shut down gracefully
2020-06-29T18:57:07.030Z INFO @wdio/local-runner: Waiting for 1 to shut down gracefully
2020-06-29T18:57:07.284Z INFO @wdio/local-runner: Waiting for 1 to shut down gracefully
2020-06-29T18:57:07.535Z INFO @wdio/local-runner: Waiting for 1 to shut down gracefully
2020-06-29T18:57:07.789Z INFO @wdio/local-runner: Waiting for 1 to shut down gracefully
2020-06-29T18:57:08.044Z INFO @wdio/local-runner: Waiting for 1 to shut down gracefully
```

**Additional context**
This issue never occurs when running locally, i.e. without going through BrowserStack.

**Comment by christian-bromann** [comment] 2020-06-29 20:10
Duplicate of #5558

**Closed by christian-bromann** 2020-06-29 20:10 UTC

**Comment by SebastianStavar** [comment] 2023-11-27 23:01
did you close this as a duplicate of itself?

**Comment by Mansouri147** [comment] 2024-04-23 09:13
Any solution for the issue yet?
