### ISSUE TITLE
Error mid test "java.net.ConnectException: Connection refused: connect"

### ISSUE THREAD

**Issue by VKnightUT** [webdriverio/webdriverio#3157] opened 2018-12-19 19:37 UTC
Environment (please complete the following information):
 - WebdriverIO version: 4.14.1
 - Mode: WDIO Testrunner running sync mode
 - Node.js version: 10.14.2
 - NPM version: 6.4.1
 - Browser name and version: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
 - Platform name and version: Windows 10
 - Additional wdio packages used: 
     wdio-allure-reporter: 0.8.3
     wdio-chromedriver-service: 0.1.5
     wdio-jasmine-framework: 0.3.8
     wdio-selenium-standalone-service: 0.0.12
- Chromedriver version 2.45

- Config of WebdriverIO:
var shell = require('shelljs');
exports.config = {    
    specs: [
        './suites/HousingRedesignTests/HR_RecordTypeTests.js',
        './suites/HousingRedesignTests/HR_RecordTypeConversion.js',
        './suites/HousingRedesignTests/HR_RequiredFieldChecks.js',
    ],    
    //
    // ============
    // Capabilities
    // ============    
    maxInstances: 1,    
    capabilities: [{
        maxInstances: 1,
        browserName: 'chrome',
    }],    
    // ===================
    // Test Configurations
    // ===================    
    sync: true,    
    logLevel: 'error',    
    coloredLogs: true,    
    deprecationWarnings: true,    
    bail: 0,    
    screenshotPath: './errorShots/',    
    waitforTimeout: 10000,    
    connectionRetryTimeout: 10000,    
    connectionRetryCount: 5,    
    services: ['selenium-standalone','chromedriver'],    
    framework: 'jasmine',    
    jasmineNodeOpts: {
        // Jasmine default timeout
        defaultTimeoutInterval: 9999999,
    },    
    // =====
    // Hooks
    // =====    
    beforeTest: function(test) {
        console.log("******************** BEGIN TEST CASE: " + test.title + "  ********************");
    },    
    afterTest: function (test) {
        console.log("******************** END TEST CASE: "+ test.title + "  ********************");
    },
};
require('babel-core/register')({
    presets: ['env']
});

**Describe the bug**
In the middle of my test run the test will freeze and after a timeout period it will return with the error: 
Failed to take screenshot on reject:     {"message":"java.net.ConnectException: Connection refused: connect","type":"RuntimeError","seleniumStack":{"type":"UnknownError","message":"An unknown server-side error occurred while processing the command.
","orgStatusMessage":"java.net.ConnectException: Connection refused: connect"}}

All of the rest of the tests in that suite will then get the same error and at the bottom of the test run I get the stack trace listed below. 

*** Possible causes and changes that have been tried *****
1. Too many threads running in parallel - We only run one test at a time sequentially
2. Test locators coming back with too many elements, such as over 200. - Our element locators are very specific and only come back with 1 result at any given time
3. Thread pool size needs to be increased - Set threadpool size to the max 128 in the configuration file (and verified it was setting it correctly) didn't have any effect on the error coming up.
4. Utilizing Try/Catch blocks to catch any and all errors and retry tests. No errors were being caught.
5. Tried the retry flaky tests suggestions both for Jasmine and Mocha listed for the WebdriverIO project on this page and neither worked. The connection refused error doesn't seem to be caught by the retries and completely jumps out of the test execution. As such the retries doesn't help at all. http://webdriver.io/guide/testrunner/retry.html
6. Tried the WebdriverIO error handling found on the following page. This wasn't catching the error at all, which it should be catching it if there was a browser error. http://webdriver.io/guide/usage/eventhandling.html
7. Possible Network Errors - Used wireshark to get a log file. Internal Network Engineers inspected the file and stated that my computer was sending a TCP reset. No errors were shown at the port level, the gateway level, or the firewall level. 

ERROR: java.net.ConnectException: Connection refused: connect
chrome
    at new RuntimeError (C:\Repositories\salesforce\webdriverio-test\node_modules\webdriverio\build\lib\utils\ErrorHandler.js:143:12)
    at Request._callback (C:\Repositories\salesforce\webdriverio-test\node_modules\webdriverio\build\lib\utils\RequestHandler.js:318:39)
    at Request.self.callback (C:\Repositories\salesforce\webdriverio-test\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (C:\Repositories\salesforce\webdriverio-test\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (C:\Repositories\salesforce\webdriverio-test\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:273:13)
ERROR: No active session with ID 39e2cff6f4a40b115e30d1c51aab9fea

    at new RuntimeError (C:\Repositories\salesforce\webdriverio-test\node_modules\webdriverio\build\lib\utils\ErrorHandler.js:143:12)
    at Request._callback (C:\Repositories\salesforce\webdriverio-test\node_modules\webdriverio\build\lib\utils\RequestHandler.js:318:39)
    at Request.self.callback (C:\Repositories\salesforce\webdriverio-test\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (C:\Repositories\salesforce\webdriverio-test\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (C:\Repositories\salesforce\webdriverio-test\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:273:13)

**Example Code**
it('Failing Test - Housing Request from Job', function() {
        browser.timeouts('implicit', 10000);
        // Launch the login page and maximize the window
        browser.url('https://test.salesforce.com/');
        browser.windowHandleMaximize();
        // Enter username and password
        browser.element('#username').setValue("test.automation@chghealthcare.com.hrrbox2");
        browser.element('#password').setValue("testAuto2");
        // Click on the Login button
        browser.element('#Login').click();
        // Search for a specific user
        browser.element("//div[@id='phSearchContainer']//input[@id='phSearchInput'][@type='text']").setValue("ITQA CHG");
        browser.element("//div[@id='searchButtonContainer']/input[@id='phSearchButton'][@type='button']").click();
        // Click on the user
        browser.element("//div[@id='User_body']//a[text()='ITQA CHG']").click();
        // Click on the dropdown menu
        browser.element("//a[@id='moderatorMutton']").click();
        // Click on User Detail option in the dropdown menu
        browser.element("//a[@id='USER_DETAIL']").click();
        // Click on Login button to login as the user you searched for
        browser.element("//td[@id='topButtonRow']//input[@title='Login']").click();
        // Load the landing page for the list of jobs for this user
        browser.url("https://chg--hrrbox2.cs77.my.salesforce.com/a0c/o");
        // Click on the first job in the list (only returns first record)
        browser.element("//div[@class='pbBody']//tr[contains(@class, 'first')]/th/a").click();
        // Click on the button "Create Housing Request" on this page
        console.log("Print this out if you get to this line of code... which you never do if the next line of code has the wrong locator...");
        browser.element(".btn[value='Create Test Request']").click();
    });

**Log**
Link to Gist file: https://gist.github.com/VKnightUT/d74755fb394d37e0b6c537c8244f066d

ADDITIONAL NOTES: These tests are testing a Salesforce application.

**Comment by christian-bromann** [comment] 2018-12-19 21:22
@VKnightUT can you narrow down your error and could you provide that as a minimal reproducible example? This is impossible to figure out by just looking at the unformatted code.

**Comment by VKnightUT** [comment] 2018-12-20 17:05
> @VKnightUT can you narrow down your error and could you provide that as a minimal reproducible example? This is impossible to figure out by just looking at the unformatted code.

@christian-bromann I have edited my original code and replaced it with a reproducible example. 

One thing I have noticed, if the locator on that last line of code ( _**browser.element(".btn[value='Create Test Request']").click();**_ ) is incorrect it does not return with any error about not being able to find the element. This is when it comes back with the error message about the connection being refused and kills all of the rest of the tests. If the locator is correct it works though. The odd thing is that the console.log right before that bad locator line of code never gets printed out as if it never hits it.

I did notice in the notes for chromedriver 2.45 they stated _"Fixed Find Element command returns wrong error code when an invalid locator is used"_

Could the two be related?

**Comment by abjerstedt** [comment] 2018-12-20 17:12
services: ['selenium-standalone','chromedriver'],

Why are you using both services at the same time @VKnightUT ? I'm about 80% sure thats your problem, and everything else you sent us is a red herring. 

When you list both in the same array, both are spawned at test execution. 

Please remove chromedriver from your array, and reboot your machine (to remove all the lingering processes).

**Comment by VKnightUT** [comment] 2018-12-20 21:44
> services: ['selenium-standalone','chromedriver'],
> 
> Why are you using both services at the same time @VKnightUT ? When you list both in the same array, both are spawned at test execution. I'm about 80% sure thats your problem, and everything else you sent us is a red herring.
> 
> Please remove chromedriver from your array, and reboot your machine (to remove all the lingering processes).

Thanks for the suggestion @abjerstedt . I'm not sure why we had both services there so I tried removing chromedriver, rebooting my computer, and ran the test again and the same error happened. 

On a side note I tried only using chromedriver and the test wouldn't even launch so I'll just leave the selenium-standalone as the only option in there from now on.

**Comment by VKnightUT** [comment] 2019-01-02 16:08
Is there any update on this issue?

**Comment by VKnightUT** [comment] 2019-01-09 16:34
@christian-bromann and @abjerstedt  I have tried updating to version 5.2.7 today to see if this issue is resolved. When I try running tests on version 4.14.1 it runs but on version 5.2.7 I get the following error:

'wdio' is not recognized as an internal or external command,
operable program or batch file.

Have you guys had a chance to look at this issue yet? Since providing a reproducible example I haven't seen that label removed from this issue. I was hoping that updating to 5.2.7 would fix the issue but I can't test that yet. 

Here are the contents of my package.json file. Please let me know if there is an update I am missing or something else I can do to get the tests running on the new version of webdriverio.

{
  "name": "webdriverio-test",
  "version": "1.0.0",
  "description": "Webdriver IO tests",
  "main": "wdio.conf.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "test-spec-local": "./node_modules/.bin/wdio wdio.LocalChromeConf.js --spec",
    "test-suite-local": "./node_modules/.bin/wdio wdio.LocalChromeConf.js --suite",
    "test-local": "./node_modules/.bin/wdio wdio.LocalChromeConf.js",
    "test-jenkins": "./node_modules/.bin/wdio wdio.JenkinsBSconf.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "aws-sdk": "^2.378.0",
    "chromedriver": "^2.45.0",
    "expect": "^23.6.0",
    "file-type": "^10.7.0",
    "iedriver": "^3.13.0",
    "inbox": "^1.1.59",
    "jasmine-expect": "^4.0.0",
    "js2xmlparser": "^3.0.0",
    "jshint": "^2.9.7",
    "mime": "^2.4.0",
    "require-new": "^1.1.1",
    "shelljs": "^0.8.3",
    "wdio-junit-reporter": "^0.4.4",
    "webdriver": "^5.2.7",
    "webdriverio": "^4.14.1"
  },
  "devDependencies": {
    "@types/node": "^10.12.17",
    "@types/webdriverio": "^4.13.0",
    "allure-commandline": "^2.8.1",
    "babel-eslint": "^10.0.1",
    "babel-loader": "^8.0.4",
    "babel-preset-env": "^1.7.0",
    "babel-register": "^6.26.0",
    "selenium-standalone": "^6.15.4",
    "wdio-allure-reporter": "^0.8.3",
    "wdio-chromedriver-service": "^0.1.5",
    "wdio-iedriver-service": "^0.1.0",
    "wdio-jasmine-framework": "^0.3.8",
    "wdio-mocha-framework": "^0.6.4",
    "wdio-selenium-standalone-service": "^0.0.12"
  }
}

**Comment by abjerstedt** [comment] 2019-01-09 17:12
@VKnightUT You didn't properly upgrade to v5. Please read the upgrade instructions in the docs and then ask out on gitter if you need help. Many of those packages have been renamed, and you only upgraded "webdriver" and not the remaining packages.

**Comment by christian-bromann** [comment] 2019-02-06 22:15
I really don't know how to help you guys here. This looks like a connection problem to the driver which is caused by a configuration issue. As Albert said you should not use selenium-standalone and chromedriver at the same time. There are tutorials out there that show how to setup a grid or just run tests with a single driver. As I can't identify an issue with WebdriverIO directly here I will close this.

**Closed by christian-bromann** 2019-02-06 22:15 UTC
Labels: Reproducible Example Missing
