### ISSUE TITLE
[🐛 Bug]: Error: Callback was already called.

### ISSUE THREAD

**Issue by gauravgandhi1315** [webdriverio/webdriverio#8283] opened 2022-04-28 21:22 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7

### Node.js Version

16.13.2

### Mode

Standalone Mode

### What happened?

Updated my node version to 16 and selenium-standalone was successfully installed. When I run my tests, I see this issue:

```node_modules/selenium-standalone/lib/install.js:626
      cb(new Error("Could not request headers from " + url + ": " + err));
      ^
Error: Callback was already called.```

```"@wdio/selenium-standalone-service": "6.1.14",
"selenium-standalone": "6.20.1",```

### What is your expected behavior?

tests should run

### How to reproduce the bug.

selenium standalone error

### Relevant log output

```typescript
node_modules/selenium-standalone/lib/install.js:626
      cb(new Error("Could not request headers from " + url + ": " + err));
      ^
Error: Callback was already called.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2022-04-28 21:43
Duplicate of https://github.com/webdriverio/selenium-standalone/issues/661

**Closed by christian-bromann** 2022-04-28 21:43 UTC
Labels: Bug 🐛, Needs Triaging ⏳
