### ISSUE TITLE
Ignore `unexpected alert open` for click commands with coordinates

### ISSUE THREAD

**Issue by mkannan007** [webdriverio/webdriverio#6423] opened 2021-02-13 13:33 UTC
**Environment:**
 - **WebdriverIO version:** [e.g. 6.X.X]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync:** 
 - **Node.js version:** [v 12.20.2]
 - **NPM version:** [V 6.4.11]
 - **Browser name and version:** [ Chrome 88]
 - **Platform name and version:** [ Mac OS Big sur 11.2.1]
 - **Additional wdio packages used (if applicable):** ["@wdio/cli": "^ 6.X.X",
    "@wdio/cucumber-framework": "^ 6.X.X",
    "@wdio/local-runner": "^ 6.X.X",
    "@wdio/selenium-standalone-service": "^ 6.X.X",
    "@wdio/spec-reporter": "^ 6.X.X",
    "@wdio/sync": "^ 6.X.X",]

**Config of WebdriverIO**
WebdriverIO local runner using Cucumber framework

**Describe the bug**
In my project, there are many popup alerts that will be displayed and need to capture the alert text to assert. So far I used WebdriverIO version-5 latest (5.23.0) and It works fine in handling alerts but when I upgrade to WebdriverIO V6 the alert is closing automatically. Hence Unable to handle alert text to validate and my test is failed

**To Reproduce**
browser.url('https://chercher.tech/practice/popups')
$("//input[@name='confirmation']").click()
const alertText = browser.getAlertText()
console.log("Text is : " +alertText)

[Include code or an example repository that can easily be set up]

**Expected behavior**
browser.isAlertOpen();
browser.getText();
browser.acceptAlert();
browser.dismissAlert();

The above commands should work fine as like WebdriverIO v5 (5.23.0)

**Additional context**
Actual Error: Throwing an error "No Such Alert". But when we see the test run the alert is opening and closes immediately hence unable to interact with the alert.

**Comment by christian-bromann** [comment] 2021-02-15 09:48
Hey @mkannan007 thanks for raising the issue. We recommend to upgrade straight away to v7 as this is our latest released version. Also, can you provide a reproducible example of this issue? WebdriverIO should not be the one closing these alerts so it is unlikely that it is immediately connected to the framework. To get a better idea it would be helpful to be able to reproduce this.

**Comment by mkannan007** [comment] 2021-02-21 02:04
@christian-bromann Thanks for your reply.
I tried the same issue by upgrading to wdio v7 but the issue still persists. Please try this sample code in wdio either v6 or v7 and kindly let me know your inputs,

  **browser.url('https://chercher.tech/practice/popups');
  $("//input[@name='confirmation']").click();
  browser.pause(3000);
  const alertText = browser.getAlertText();
  console.log(`Text is : ${alertText}`);**

Also, I Observed some when I tried upgrading to v5 to v7

**_cucumber hooks **afterScenario** is not working._** As I used this to handle many things for my project application

As my current project is big and maintained many automation test scenario's. 
Hence upgrading to wdio v7 won't be helpful for my current project without resolving the above two issues **(pop up handling, afterScenario cucumber-hooks)**

Please request you to look into the above issues and kindly provide your inputs

**Comment by christian-bromann** [comment] 2021-03-01 13:29
The code you have provided:
```js
browser.url('chercher.tech/practice/popups')
$("//input[@name='confirmation']").click()
const alertText = browser.getAlertText()
console.log("Text is : " +alertText)
```
works just fine for me, it outputs:

```
Text is : I am confirm
```

> **afterScenario** is not working

Not sure what explicitly is not working. Note that we have updated the hook parameters which needs to be addressed in your project.

Closing as the code example you provided is working. Happy to further discuss and support.

**Comment by kannanmf** [comment] 2021-03-01 15:24
@christian-bromann 
Can you please share what chrome version are you using?

Also, please share what are the wdio version are you using as below,
["@wdio/cli": "^ X.X.X",
"@wdio/cucumber-framework": "^ X.X.X",
"@wdio/local-runner": "^ X.X.X",
"@wdio/selenium-standalone-service": "^ X.X.X",
"@wdio/spec-reporter": "^ Z.X.X",
"@wdio/sync": "^ X.X.X",
"webdriverio": "^ X.X.X",

Also any specific configuration are you using in wdio.conf.js

So that I will try the same in my local machine. Because I tried many times with V6 and v7 and it's not working. Only works with webdriverio v5

**Comment by christian-bromann** [comment] 2021-03-01 15:40
@kannanmf I tried with the latest version. My Chrome browser in on v88.

**Comment by kannanmf** [comment] 2021-03-01 17:38
Thanks @christian-bromann for your reply. 

Are you trued using webdriverio v6 or v7?  Please let me know

**Comment by christian-bromann** [comment] 2021-03-01 18:08
v7

**Comment by michalpelc-beqom** [comment] 2021-03-04 09:00
I do agree, have the same issue with chromedriver 88 and wdio 7.0.7 ... chrome alert appears and disappears immediately after click() function is called on element, no option to catch an alert

**Comment by kannanmf** [comment] 2021-03-04 10:56
@michalpelc-beqom Thanks for your observation where you also face the same issue while doing some interaction with chrome alert.

I am also able to replicate the issue always. But when I checked with @christian-bromann, Unfortunately, he is not able to replicate.

It would be much more helpful if someone investigates this issue again by reopening this ticket.

**Comment by christian-bromann** [comment] 2021-03-04 11:42
I am happy to re-open but again if it helps, my analysis could not reproduce it.

**Comment by kannanmf** [comment] 2021-03-04 20:41
@christian-bromann Please try this piece of code, I hope you can definitely able to reproduce in wdio v7 using chrome. Because the alert closes automatically either it will fail at browser.getAlertText(), or browser.acceptAlert(),


browser.url('https://chercher.tech/practice/popups');
  $('#ez-accept-all').click();
  $("//input[@name='confirmation']").click();
  const alertText = browser.getAlertText();
  console.log(`Alert Text is : ${alertText}`);
  console.log(browser.isAlertOpen());
  browser.acceptAlert();

OR

browser.url('https://chercher.tech/practice/popups');
  $('#ez-accept-all').click();

  for (let i = 1; i <= 10; i += 1) {
    $("//input[@name='confirmation']").click();
    const alertText = browser.getAlertText();
    console.log(`Alert Text iteration ${i} is : ${alertText}`);
    browser.acceptAlert();
  }

**I can also able to reproduce the popup closing issue at firefox too.**

**Comment by christian-bromann** [comment] 2021-03-05 13:38
@kannanmf both fail for me due to:

```
Error: Can't call click on element with selector "#ez-accept-all" because element wasn't found
```

**Comment by kannanmf** [comment] 2021-03-05 17:07
@christian-bromann 
Please comment $('#ez-accept-all').click(); This will appear only when running the test using incognito/private browser. Please find below the screenshot


<img width="1388" alt="Screenshot 2021-03-05 at 17 04 59" src="https://user-images.githubusercontent.com/62020892/110148665-00cef000-7dd5-11eb-9246-d9a720080da3.png">

**Comment by christian-bromann** [comment] 2021-03-05 17:35
> This will appear only when running the test using incognito/private browser. Please find below the screenshot

A new WebDriver session always starts in such modus.

**Comment by kannanmf** [comment] 2021-03-05 17:48
Ok, Please just ignore the step $('#ez-accept-all').click(); If the above screen is not occuring at your end.

Please run again if you are able to replicate the popup handling issues from your end

**Comment by kannanmf** [comment] 2021-03-11 07:44
@christian-bromann 
Did you get a chance to look into this issue? I am very much interested in upgrading to wdio7 but this is the only thing which blocks.

Please provide your inputs

**Comment by christian-bromann** [comment] 2021-03-11 08:06
@kanhaiya15 again, no issues, running the following test:

```js
describe('foo', () => {
    it('bar', () => {
        browser.url('https://chercher.tech/practice/popups');
        for (let i = 1; i <= 10; i += 1) {
            $("//input[@name='confirmation']").click();
            const alertText = browser.getAlertText();
            console.log(`Alert Text iteration ${i} is : ${alertText}`);
            browser.acceptAlert();
        }
    });
});
```

passes with the following logs:
```
[0-0] 2021-03-11T08:02:55.699Z INFO webdriver: COMMAND findElement("xpath", "//input[@name='confirmation']")
[0-0] 2021-03-11T08:02:55.699Z INFO webdriver: [POST] http://localhost:9515/session/8e4c8eb5196f77b6dae7ba0fcd532e19/element
2021-03-11T08:02:55.699Z INFO webdriver: DATA { using: 'xpath', value: "//input[@name='confirmation']" }
[0-0] 2021-03-11T08:02:55.802Z INFO webdriver: RESULT {
  'element-6066-11e4-a52e-4f735466cecf': '34f31e94-536e-45b6-8f7a-66de4eb10ef5'
}
[0-0] 2021-03-11T08:02:55.804Z INFO webdriver: COMMAND elementClick("34f31e94-536e-45b6-8f7a-66de4eb10ef5")
[0-0] 2021-03-11T08:02:55.804Z INFO webdriver: [POST] http://localhost:9515/session/8e4c8eb5196f77b6dae7ba0fcd532e19/element/34f31e94-536e-45b6-8f7a-66de4eb10ef5/click
[0-0] 2021-03-11T08:02:55.881Z INFO webdriver: COMMAND getAlertText()
2021-03-11T08:02:55.881Z INFO webdriver: [GET] http://localhost:9515/session/8e4c8eb5196f77b6dae7ba0fcd532e19/alert/text
[0-0] 2021-03-11T08:02:55.883Z INFO webdriver: RESULT I am confirm
[0-0] Alert Text iteration 9 is : I am confirm
[0-0] 2021-03-11T08:02:55.883Z INFO webdriver: COMMAND acceptAlert()
[0-0] 2021-03-11T08:02:55.883Z INFO webdriver: [POST] http://localhost:9515/session/8e4c8eb5196f77b6dae7ba0fcd532e19/alert/accept
[0-0] 2021-03-11T08:02:55.932Z INFO webdriver: COMMAND findElement("xpath", "//input[@name='confirmation']")
[0-0] 2021-03-11T08:02:55.932Z INFO webdriver: [POST] http://localhost:9515/session/8e4c8eb5196f77b6dae7ba0fcd532e19/element
[0-0] 2021-03-11T08:02:55.932Z INFO webdriver: DATA { using: 'xpath', value: "//input[@name='confirmation']" }
[0-0] 2021-03-11T08:02:56.037Z INFO webdriver: RESULT {
  'element-6066-11e4-a52e-4f735466cecf': '34f31e94-536e-45b6-8f7a-66de4eb10ef5'
}
[0-0] 2021-03-11T08:02:56.039Z INFO webdriver: COMMAND elementClick("34f31e94-536e-45b6-8f7a-66de4eb10ef5")
[0-0] 2021-03-11T08:02:56.039Z INFO webdriver: [POST] http://localhost:9515/session/8e4c8eb5196f77b6dae7ba0fcd532e19/element/34f31e94-536e-45b6-8f7a-66de4eb10ef5/click
[0-0] 2021-03-11T08:02:56.115Z INFO webdriver: COMMAND getAlertText()
[0-0] 2021-03-11T08:02:56.115Z INFO webdriver: [GET] http://localhost:9515/session/8e4c8eb5196f77b6dae7ba0fcd532e19/alert/text
[0-0] 2021-03-11T08:02:56.117Z INFO webdriver: RESULT I am confirm
[0-0] Alert Text iteration 10 is : I am confirm
[0-0] 2021-03-11T08:02:56.117Z INFO webdriver: COMMAND acceptAlert()
2021-03-11T08:02:56.118Z INFO webdriver: [POST] http://localhost:9515/session/8e4c8eb5196f77b6dae7ba0fcd532e19/alert/accept
[0-0] 2021-03-11T08:02:56.154Z INFO webdriver: COMMAND deleteSession()
[0-0] 2021-03-11T08:02:56.154Z INFO webdriver: [DELETE] http://localhost:9515/session/8e4c8eb5196f77b6dae7ba0fcd532e19
[0-0] PASSED in chrome - /test/specs/example.e2e.js
2021-03-11T08:02:56.322Z INFO @wdio/cli:launcher: Run onComplete hook

 "spec" Reporter:
------------------------------------------------------------------
[chrome 89.0.4389.82 mac os x #0-0] Spec: /Users/christianbromann/Sites/WebdriverIO/issues/6423/test/specs/example.e2e.js
[chrome 89.0.4389.82 mac os x #0-0] Running: chrome (v89.0.4389.82) on mac os x
[chrome 89.0.4389.82 mac os x #0-0] Session ID: 8e4c8eb5196f77b6dae7ba0fcd532e19
[chrome 89.0.4389.82 mac os x #0-0]
[chrome 89.0.4389.82 mac os x #0-0] My Login application
[chrome 89.0.4389.82 mac os x #0-0]    ✓ should login with valid credentials
[chrome 89.0.4389.82 mac os x #0-0]
[chrome 89.0.4389.82 mac os x #0-0] 1 passing (2.8s)


Spec Files:      1 passed, 1 total (100% completed) in 00:00:05

2021-03-11T08:02:56.323Z INFO @wdio/local-runner: Shutting down spawned worker
2021-03-11T08:02:56.578Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2021-03-11T08:02:56.579Z INFO @wdio/local-runner: shutting down
```

Here is a Sauce Labs job as proof: https://app.saucelabs.com/tests/687c507d9fce46ed9faa297f52effd07?auth=0d3970a7245b4537d5b5079a416c824f

I will close the issue, happy to re-open once you have a reproducible example.

**Comment by kannanmf** [comment] 2021-03-15 22:59
@christian-bromann 
Today I created a sample wdio v7 using cucumber-framework from the scratch and tried the above popup code, It works perfectly fine and with very good speed of test execution.

However, If I upgrade my existing company project from wdio v5 to wdio v7 (just by updating the version number in the package.json and after that I run the command "npm install". Then I tried running the above popup issue code but it fails as before (i.e. popup closing automatically)  and also the speed of the execution is not good.

I conclude I am doing something wrong way of upgrading the wdio versions.

Please let me know the correct way of migrating the version i.e. from (WDIO v5 to WDIO v7) so that it will be helpful for my current project and kindly share with me any reference document link, if any

**Comment by kgiannelos** [comment] 2021-07-13 15:38
So, I stepped into a similar issue. I am seeing the same behavior when clicking on some UI element, which then triggers an alert box to show up. The alert will go away immediately, right after clicking on the UI element that brings it up and the test will fail. However, I am using the element.click method with coordinates, since my test needs to click on some canvas item at a given location. So, typically, I can say I am using a similar script like the one you shared above @christian-bromann with the only difference being in the click method, like below:
`$("//input[@name='confirmation']").click({x: 1, y: 1});`

After inspecting the webdriver logs (shared below) and comparing these to the ones you shared, I believe the issue is clearly with the element.click method, when using coordinates. What happens in my case is that Instead of the elementClick Command, the performActions command is used under the hood. I suspect that the actions array in the command parameters moves the mouse to the right coordinates and then performs a pointerDown followed by a pointerDown. Till that point everything is fine. However, right after the performActions command, webdriver invokes a releaseActions command, which fails due to the alert box being opened. It also looks like that the releseActions command failure results in the alert dialog to close also.
```
2021-07-13T10:54:21.096Z INFO webdriver: COMMAND findElement("css selector", "#processExplorerContainerDiv canvas")
2021-07-13T10:54:21.096Z INFO webdriver: [POST] http://localhost:9515/session/eb04fdf89c5deac5f42dff12bed82d70/element
2021-07-13T10:54:21.096Z INFO webdriver: DATA { using: 'css selector', value: '#processExplorerContainerDiv canvas' }
2021-07-13T10:54:21.106Z INFO webdriver: RESULT {
  'element-6066-11e4-a52e-4f735466cecf': '0a1528d1-dc3c-42c6-9f9f-50204b950db3'
}
2021-07-13T10:54:21.109Z INFO webdriver: COMMAND performActions(<object>)
2021-07-13T10:54:21.109Z INFO webdriver: [POST] http://localhost:9515/session/eb04fdf89c5deac5f42dff12bed82d70/actions
2021-07-13T10:54:21.109Z INFO webdriver: DATA {
  actions: [
    {
      type: 'pointer',
      id: 'pointer1',
      parameters: [Object],
      actions: [Array]
    }
  ]
}
2021-07-13T10:54:21.163Z INFO webdriver: COMMAND releaseActions()
2021-07-13T10:54:21.164Z INFO webdriver: [DELETE] http://localhost:9515/session/eb04fdf89c5deac5f42dff12bed82d70/actions
2021-07-13T10:54:21.167Z DEBUG webdriver: request failed due to response error: unexpected alert open
2021-07-13T10:54:21.168Z WARN webdriver: Request failed with status 500 due to unexpected alert open: {Alert text : Are you sure you want to leave the page? Data you have entered may not be saved.}
  (Session info: chrome=91.0.4472.114)
2021-07-13T10:54:21.168Z INFO webdriver: Retrying 1/3
2021-07-13T10:54:21.168Z INFO webdriver: [DELETE] http://localhost:9515/session/eb04fdf89c5deac5f42dff12bed82d70/actions
2021-07-13T10:54:21.228Z INFO webdriver: RESULT undefined
2021-07-13T10:54:21.228Z INFO webdriver: COMMAND getAlertText()
2021-07-13T10:54:21.228Z INFO webdriver: [GET] http://localhost:9515/session/eb04fdf89c5deac5f42dff12bed82d70/alert/text
2021-07-13T10:54:21.234Z DEBUG webdriver: request failed due to response error: no such alert
2021-07-13T10:54:21.234Z WARN webdriver: Request failed with status 404 due to no such alert
  (Session info: chrome=91.0.4472.114)
2021-07-13T10:54:21.234Z INFO webdriver: Retrying 1/3
2021-07-13T10:54:21.234Z INFO webdriver: [GET] http://localhost:9515/session/eb04fdf89c5deac5f42dff12bed82d70/alert/text
2021-07-13T10:54:21.237Z DEBUG webdriver: request failed due to response error: no such alert
2021-07-13T10:54:21.237Z WARN webdriver: Request failed with status 404 due to no such alert
  (Session info: chrome=91.0.4472.114)
```

**Comment by christian-bromann** [comment] 2021-07-14 08:10
@kgiannelos so I believe the issue here is that `performActions` triggers the alert to pop up which causes `releaseActions` to fail. A possible solution to this would be to wrap it around try/catch and ignore the error in case the message is `unexpected alert open`. Would you like to take a stab at this?

**Comment by kgiannelos** [comment] 2021-07-14 18:35
Thanks for the suggestion @christian-bromann . I went that path, but when releaseActions fails, it also results in the alert popup to close. As a result, the next step, which is supposed to verify the alert, fails as it cannot find it. I managed to work around this by implementing my own performActions command which just does not call releaseActions at the end. However, I could not make it work with the provided element.click command.

**Comment by christian-bromann** [comment] 2021-07-15 06:14
@kgiannelos I believe the best option then is to make the `releaseAction` call optional and add a new parameter to the click command.

**Comment by frother** [comment] 2021-07-16 04:25
I am running into the same issue, I get the following error:
 Error in logs: Request failed with status 500 due to unexpected alert open

**Comment by christian-bromann** [comment] 2021-07-16 06:53
> Error in logs: Request failed with status 500 due to unexpected alert open

This is unrelated to this issue but you call a command while an alert is open, you need to close the alert first. 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. Thanks!

**Comment by bledoyen** [comment] 2021-07-16 09:36
@christian-bromann I have the same problem of @kgiannelos but I don't undestand how fix it ? 
Could you help me please ?

**Comment by christian-bromann** [comment] 2021-07-16 15:17
> Could you help me please ?

I explained a possible fix for this problem [above](https://github.com/webdriverio/webdriverio/issues/6423#issuecomment-880426477). Please get involved and help us with a patch for this. Thanks.

**Comment by bledoyen** [comment] 2021-07-16 15:57
Yes, thanks @christian-bromann but what does that mean "to make the releaseAction call optional" and "add a new parameter to the click command" ? 

When we use :
```js
selector.click(); 
browser.acceptAlert(); 
```

I had check here "https://webdriver.io/docs/api/element/click/" but I didn't fine any intresting informations about it

**Comment by christian-bromann** [comment] 2021-07-16 16:32
Sorry, I wasn't very clear. In order to fix this we need to enhance the [click command](https://github.com/webdriverio/webdriverio/blob/upgrade_lighthouse_dependencies/packages/webdriverio/src/commands/element/click.ts) and add a new optional parameter to `ClickOptions` called e.g. `skipRelease` that if set, doesn't make the [`releaseAction`](https://github.com/webdriverio/webdriverio/blob/upgrade_lighthouse_dependencies/packages/webdriverio/src/commands/element/click.ts#L133). This is a good first issue to contribute to the project.

**Closed** 2021-10-04 12:39 UTC
Labels: help wanted, good first pick, Hacktoberfest

**Comment by arkhangelsk** [comment] 2021-12-05 05:52
I am also getting this error.  This is shown as a warning:
WARN webdriver: Request failed with status 500 due to unexpected alert open: {Alert text : I am a JS Alert}

I am using WebdriverIO "@wdio/cli": "^7.16.10",

**Comment by praveendvd** [comment] 2022-06-20 21:48
@christian-bromann just eager to know why we are using webdriver actions instead of click ? https://www.w3.org/TR/webdriver/#element-click
