### ISSUE TITLE
Autocompletion - fix screenshots + @types/webdriverio:5.0.0 autocompletion issue

### ISSUE THREAD

**Issue by versedi** [webdriverio/webdriverio#4680] opened 2019-10-25 10:44 UTC
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [x] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [x] Other

**Description of the improvement / report**
The screenshots in Autocompletion guides are inconsistent. Text says user is supposed to select `commmands` from `lib` directory - which doesn't exists in  `5.15.3`:

![](https://webdriver.io/img/autocompletion/6.png)

![](https://i.imgur.com/pfc3H3J.png)

On next screenshot the actual selected directory is root `webdriverio` inside `node_modules`.

![](https://webdriver.io/img/autocompletion/7.png)

Which configuration is correct so I could update the docs? 

When I add the `commands` directory the only autocompletion I get what's on below screen. No matter what directory I choose for it. 
![](https://i.imgur.com/obWC4dZ.png)

When I remove my tsconfig.json, the autocompletion is working properly.

My tsconfig.json is following (and the autocompletion does work with `@types/webdriverio:4.8.7` but not with `^5.0.0`

```
{
  "compilerOptions": {
    "lib": ["es5", "es6", "dom"],
    /* Basic Options */
    "target": "es5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019' or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
    "allowSyntheticDefaultImports": true,
    // "lib": [],                             /* Specify library files to be included in the compilation. */
    // "allowJs": true,                       /* Allow javascript files to be compiled. */
    // "checkJs": true,                       /* Report errors in .js files. */
    // "jsx": "preserve",                     /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
    // "declaration": true,                   /* Generates corresponding '.d.ts' file. */
    // "declarationMap": true,                /* Generates a sourcemap for each corresponding '.d.ts' file. */
    "sourceMap": true,                     /* Generates corresponding '.map' file. */
    // "outFile": "./",                       /* Concatenate and emit output to single file. */
     "outDir": "./public/assets/",                        /* Redirect output structure to the directory. */
    // "rootDir": "./",                       /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
    // "composite": true,                     /* Enable project compilation */
    // "incremental": true,                   /* Enable incremental compilation */
    // "tsBuildInfoFile": "./",               /* Specify file to store incremental compilation information */
     "removeComments": true,                /* Do not emit comments to output. */
    // "noEmit": true,                        /* Do not emit outputs. */
    // "importHelpers": true,                 /* Import emit helpers from 'tslib'. */
    // "downlevelIteration": true,            /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */
    // "isolatedModules": true,               /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */

    /* Strict Type-Checking Options */
    //        "strict": true,                           /* Enable all strict type-checking options. */
//     "noImplicitAny": true,                 /* Raise error on expressions and declarations with an implied 'any' type. */
    // "strictNullChecks": true,              /* Enable strict null checks. */
    //         "strictFunctionTypes": true,           /* Enable strict checking of function types. */
    // "strictBindCallApply": true,           /* Enable strict 'bind', 'call', and 'apply' methods on functions. */
    // "strictPropertyInitialization": true,  /* Enable strict checking of property initialization in classes. */
     "noImplicitThis": true,                /* Raise error on 'this' expressions with an implied 'any' type. */
    // "alwaysStrict": true,                  /* Parse in strict mode and emit "use strict" for each source file. */

    /* Additional Checks */
    // "noUnusedLocals": true,                /* Report errors on unused locals. */
    // "noUnusedParameters": true,            /* Report errors on unused parameters. */
     "noImplicitReturns": true,             /* Report error when not all code paths in function return a value. */
    // "noFallthroughCasesInSwitch": true,    /* Report errors for fallthrough cases in switch statement. */

    /* Module Resolution Options */
//     "moduleResolution": "node",            /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
    // "baseUrl": "./",                       /* Base directory to resolve non-absolute module names. */
    // "paths": {},                           /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */
    // "rootDirs": [],                        /* List of root folders whose combined content represents the structure of the project at runtime. */
//     "typeRoots": [],                       /* List of folders to include type definitions from. */
     "types": [
       "node",
       "@wdio/cli",
       "@wdio/sync",
       "@wdio/mocha-framework",
       "webdriverio",
       "chai",
       "mocha",
       "selenium-webdriver",
       "webdriverio"
     ],                           /* Type declaration files to be included in compilation. */
    "esModuleInterop": true,                 /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    // "preserveSymlinks": true,              /* Do not resolve the real path of symlinks. */

    /* Source Map Options */
     "sourceRoot": "/",                      /* Specify the location where debugger should locate TypeScript files instead of source locations. */
     "mapRoot": "public/assets/",                         /* Specify the location where debugger should locate map files instead of generated locations. */
//     "inlineSourceMap": true,               /* Emit a single file with source maps instead of having a separate file. */
//     "inlineSources": true,                 /* Emit the source alongside the sourcemaps within a single file; requires '--inlineSourceMap' or '--sourceMap' to be set. */

    /* Experimental Options */
    // "experimentalDecorators": true,        /* Enables experimental support for ES7 decorators. */
    // "emitDecoratorMetadata": true,         /* Enables experimental support for emitting type metadata for decorators. */
    "resolveJsonModule": true
  },
  "include": [
    "resources/assets/js/**/*.ts",
    "tests/js/**/*.js"
  ],
  "exclude": [
    "vendor/",
    "node_modules/"
  ]
}
```

**Comment by mgrybyk** [comment] 2019-10-26 08:06
@types/webdriverio package is for v4, for v5 follow https://webdriver.io/docs/typescript.html

Not sure what the issue is about, screenshots? Autocompletion in js? Typescript config?

Please report one issue for one problem.
Feel free to raise PR to update screenshots, that would be helpful! 

Closing this one for now

**Closed by mgrybyk** 2019-10-26 08:06 UTC
