### ISSUE TITLE
clearValue method doesn't work at all

### ISSUE THREAD

**Issue by schwarcu** [webdriverio/webdriverio#4482] opened 2019-09-10 18:46 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version: 5.12.5
 - **Mode: chromedriver
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version: v10
 - **NPM version: 6.4.1
 - **Browser name and version:** Chrome 76
 - **Platform name and version: Windows
 - **Additional wdio packages used (if applicable):
    "@types/chai": "^4.2.2",
    "@types/mocha": "^5.2.7",
    "@types/node": "^10.14.17",
    "@wdio/cli": "^5.12.5",
    "@wdio/local-runner": "^5.12.5",
    "@wdio/mocha-framework": "^5.12.1",
    "@wdio/spec-reporter": "^5.12.1",
    "@wdio/sync": "^5.12.3",
    "wdio-chromedriver-service": "^5.0.2",
    "chromedriver": "^76.0.1",
    "chai": "^4.2.0",
    "mocha": "^5.2.0",
    "ts-node": "^7.0.1",
    "tsconfig-paths": "^3.8.0",
    "tslint": "^5.19.0",
    "typescript": "^3.6.2",
    "webdriverio": "^5.12.5"

**Config of WebdriverIO**
Example config from the official tutorial

**Describe the bug**
After using setValue method to input text into 'input' element. It's impossible to clear the value.

**To Reproduce**
`$('//input[@placeholder="Search…"]').setValue(term);
$('//input[@placeholder="Search…"]').clearValue();`

or

`$('//input[@placeholder="Search…"]').setValue(term);
$('//input[@placeholder="Search…"]').click();
$('//input[@placeholder="Search…"]').clearValue();`

**Expected behavior**
As documentation says:

> Clear a <textarea> or text <input> element’s value. Make sure you can interact with the element before using this command. You can't clear an input element that is disabled or in readonly mode.

**Comment by mgrybyk** [comment] 2019-09-10 19:25
@schwarcu the issue is not reproducible for me, can you please help reproducing it?

```
it("some test", () => {
    browser.url("http://guinea-pig.webdriver.io")
    
    const el = $('input[name="searchinput"]')
    el.setValue('foobar')
    console.log('val', el.getValue())
    el.clearValue()
    console.log('val', el.getValue())
    console.log('THE END')
})
```

**Comment by schwarcu** [comment] 2019-09-15 20:26
Simple as that:
given element:
<input placeholder="Search in…" value="">

This code doesn't work (react app)
`
$('//input[@placeholder="Search in…"]').setValue('Search term');
$('//input[@placeholder="Search in…"]').clearValue();
let value = $('//input[@placeholder="Search in…"]').getValue();
console.log(value);
`
I found a dirty workaround - doubleClick() and then keys('Delete). But this is not satisfying.

btw I found dead links on your documentation page for webrdiver.io, where do I report that?

**Comment by christian-bromann** [comment] 2019-09-15 22:01
> This code doesn't work (react app)

Can you provide a minimal reproducible example? A simple input field is being cleared. Your react app seems to do something with it that breaks the WebDriver automation.

> where do I report that?

Just create an issue.

**Comment by christian-bromann** [comment] 2019-09-25 08:58
@schwarcu have you been able to create a reproducible example? I will close the issue otherwise.

**Closed** 2019-09-30 09:21 UTC
Labels: Reproducible Example Missing

**Comment by buob** [comment] 2019-10-17 19:45
Not sure if the OP was running into the same thing we were, but I want to post this in case anyone else finds this.  `clearValue` is implemented with `input.value = ""`, which if it's a controlled input will be wiped on the next render with whatever is in the state.  #gotcha

**Comment by schwarcu** [comment] 2019-10-18 04:41
Hi.

Sorry but I was not able to provide an exact code I was working with because of NDA. And I don't know React so couldn't create my own version of the form.

If I happen to know what's the logic behind this input I will try to add it here.

There was another weird issue when couldn't click a button which had a specific logic that disable that button right after pressing. While other testing frameworks handled this button okay, webdriverio keeps throwing exception that element is not interactive. But that's topic for a separate ticket I think. Will try to work on that in my free time.

**Comment by unickq** [comment] 2019-10-25 15:45
@schwarcu have the same issue.
Try to use **clearByBackspace()** instead

**Comment by mattdell** [comment] 2020-02-28 11:51
`clearByBackspace` is not a method in the API: 

https://webdriver.io/docs/api.html

**Comment by Ranjithsamalla** [comment] 2020-09-23 13:16
clearValue doesn't working  for me also I'm using version ^5.17.0

it is kind of code
$('//input[@placeholder="Search in…"]').setValue('Search term');
let value = $('//input[@placeholder="Search in…"]').getValue();
console.log(value); // 'Search term'
$('//input[@placeholder="Search in…"]').clearValue();
value = $('//input[@placeholder="Search in…"]').getValue();
console.log(value); // 'Search term'

**Comment by brimo80** [comment] 2021-05-25 09:57
ddd

**Comment by LilyGist** [comment] 2021-07-02 17:41
I was having this issue on a React frontend but I was able to get it to work by first clicking the field and then using browser.execute(), like this:

```
selector.click();
browser.execute(s => {
    s.value = null;
},selector);
selector.setValue('value');
```

I also had the backspace approach working like this, but the other way seemed a little simpler:

```
const selectorValue = selector.getValue();
const backSpaces = new Array(selectorValue.length).fill('Backspace');
selector.setValue(backSpaces);
selector.setValue('value');
```

**Comment by christian-bromann** [comment] 2021-07-12 09:50
@LilyGist thanks for sharing this. Unfortunately React doesn't play well with the WebDriver protocol. I will see if I can raise an issue within the React project.

**Comment by PetrKnedlik** [comment] 2021-07-23 10:45
@LilyGist awesome workaround, thank you! :)

**Comment by robcruz** [comment] 2021-08-30 21:22
I am still seeing this issue when automating React version of our web app. Thanks for the workaround.

**Comment by darkartswizard** [comment] 2021-09-17 05:22
This just started for me a few days ago. Possibly reintroduced?

**Comment by PareshSolanki-Which** [comment] 2021-12-13 16:39
@LilyGist you've saved me!!!...Thank you for the workaround

**Comment by darkartswizard** [comment] 2021-12-13 16:52
Make that two saves!

You are a Superhero!

**Comment by brimo80** [comment] 2022-05-05 19:18
this.value.click()
        browser.keys(['Control','a'])
        browser.keys('Delete')
        browser.pause(2000)
        this.typeFolderName.addValue('Type')

**Comment by dksoni812** [comment] 2023-06-12 06:17
```
const el = await $("input#companyName");
await el.click();
const value = await el.getValue()
const valueLength = value.length;
// Clear the input field by sending a series of backspace key presses
for (let i = 0; i < valueLength; i++) {
    await el.addValue('\uE003');
}
````

**Comment by GreenRidingHood** [comment] 2023-11-14 16:19
@LilyGist 's solution looks simple but Unfortunately didnt work for me (that was react app). I tried @dksoni812 and worked for me. If I rewrite one day definelty update here, thanks again @dksoni812

**Comment by prasanthi0422** [comment] 2024-01-28 12:17
@LilyGist 's solution worked initially when my wdio version is 5 but with wdio8+node20 its not working as I am using await syntax now. @dksoni812 solution works only for string types but the same is not working for url input. For example my initial input value is "https://skillshop.credential.net/4dcc3bb8-1732-4f23-a8c7-61e6c7634089?_gl=1*1yqivj1*_ga*OTc2MjkyNDQzLjE2NjYxNjgxMjA.*_ga_FSDJZHHBH0*MTY2NjE2ODEyMC4xLjEuMTY2NjE2ODEyNC4w" and I want to clear this value using @dksoni812 method. It's clearing only till "https://skillshop.credential.net/4" and appending the updated url to this "dcc3bb8-1732-4f23-a8c7-61e6c7634089?_gl=1*1yqivj1*_ga*OTc2MjkyNDQzLjE2NjYxNjgxMjA.*_ga_FSDJZHHBH0*MTY2NjE2ODEyMC4xLjEuMTY2NjE2ODEyNC4wLjAuMAhttps://www.credly.com/badges/d573beab-71db-46d3-a9fc-6d8d6962600a"

first time input: https://skillshop.credential.net/4dcc3bb8-1732-4f23-a8c7-61e6c7634089?_gl=1*1yqivj1*_ga*OTc2MjkyNDQzLjE2NjYxNjgxMjA.*_ga_FSDJZHHBH0*MTY2NjE2ODEyMC4xLjEuMTY2NjE2ODEyNC4wLjAuMA
second input: https://www.credly.com/badges/d573beab-71db-46d3-a9fc-6d8d6962600a

**Comment by dicrtarasov** [comment] 2024-03-21 12:05
This affect me too. React component trigger on 'input' event, which is not dispatcher by webdriverio upon clearValue
