### ISSUE TITLE
Unknown Serverside Error  with seleniumGrid Extras

### ISSUE THREAD

**Issue by DDeepu** [webdriverio/webdriverio#2695] opened 2018-04-16 22:05 UTC
## The problem

Seeing "Unknown server side error occured while processing the command" while trying to run tests using seleniumGridExtras on Ubuntu or Windows. It is working fine with MAC though. 

## Environment

* WebdriverIO version: **4.12.0**
* Node.js version: **8.11.1**
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): **Standalone Mode**

**Comment by christian-bromann** [comment] 2018-04-16 22:54
@DDeepu can you provide more details about the setup, logs and a reproducible example please?

**Comment by DDeepu** [comment] 2018-04-16 23:39
Reproducible example
/* global expect, require, test, global*/
"use strict";
let webdriverio = require('webdriverio');

let options = {
    desiredCapabilities: {
        maxInstances: 5,
        browserName: 'MicrosoftEdge' ,//Browser choice
        seleniumProtocol: "WebdriverIO"

    }
};

let browser;

beforeEach(async () => {
    browser = webdriverio.remote(options).init();
    console.log(browser);
    var gridDetails = browser.getGridNodeDetails();
    console.log(gridDetails);
}, 10000);

afterEach(async () => {
    browser.end();
}, 10000);



it(
    'can find search results',
    async () => {
        await browser
            .url('https://www.google.com/ncr')
            .setValue('*[name="q"]', 'BrowserStack\n')
            .pause(5000);

        expect(await browser.getTitle()).toEqual('BrowserStack - Google Search');
    },
    10 * 60 * 1000
);

If i run this test using selenium-standalone server test passes. If i run the same test using selenium-gridExtras then i am getting below error

(node:3632) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'addExpectationResult' of undefined
(node:3632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not ha
ndled with .catch(). (rejection id: 1)
(node:3632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 FAIL  test\specs\test.js (7.62s)
  × can find search results (6690ms)

  ● can find search results

    An unknown server-side error occurred while processing the command.

**Comment by christian-bromann** [comment] 2018-04-17 08:25
`getGridNodeDetails` only works if you run the selenium standalone server. Also it is like all other commands an async command that requires to resolve a promise if you don't run wdio in sync mode. Closing as it looks like that this is a setup issue and not a problem with WebdriverIO. Feel free to reach out in our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have more questions.

**Closed by christian-bromann** 2018-04-17 08:25 UTC
Labels: Logs Missing, Reproducible Example Missing

**Comment by DDeepu** [comment] 2018-04-17 14:08
@christian-bromann  thanks for your help. As you said it is not webdriverio, i had a outdated version of MicrosoftDriver in my program files. I just updated it to latest and it started working fine.
