### ISSUE TITLE
@wdio/runner: Error: Cannot find module 

### ISSUE THREAD

**Issue by Jp-Aubry** [webdriverio/webdriverio#12774] opened 2024-04-30 13:59 UTC
### Discussed in https://github.com/webdriverio/webdriverio/discussions/8310

<div type='discussions-op-text'>

<sup>Originally posted by **anandseshadri** May  6, 2022</sup>
Hi I am new on wdio. I use wdio with Angular 17. I am trying to launch a test with rpm run wdio. i get this error:
 **ERROR @wdio/runner: Error: Cannot find module '/home/francois/Documents/dev/new-moulinet/moulinet/test/pageobjects/app.po' imported from /home/francois/Documents/dev/new-moulinet/moulinet/test/specs/app.e2e-spec.ts**
I found a solution by importing the page object with .js extension but but I don't know if it's the right one.
I also try various confing in my ts config but it do'esn't change anything.
My  spec ts config looks like that;

{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/spec",
    "baseUrl": "./",
    "module": "commonjs",
    "target": "es6",
    "types": [
      "node",
      "@wdio/globals/types",
      "@wdio/jasmine-framework"
    ]
  },
  "include": [
    "src/**/*.spec.ts",
    "src/**/*.d.ts"
  ]
}
}`

and tsconfig:
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "sourceMap": true,
    "declaration": false,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "ES2022",
    "module": "ES2022",
    "useDefineForClassFields": false,
    "lib": [
      "ES2022",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}

Thank you for your suppor.t </div>

**Comment by christian-bromann** [comment] 2024-04-30 17:23
Duplicate of https://github.com/webdriverio/webdriverio/discussions/8310

**Closed by christian-bromann** 2024-04-30 17:23 UTC
