### ISSUE TITLE
Shadow DOM Support in Chrome WebDriver for testability of Google Polymer Web Components

### ISSUE THREAD

**Issue by ReactRedux** [webdriverio/webdriverio#4483] opened 2019-09-11 04:29 UTC
Our application is built with Google Polymer 0.5 Web Components. In most of the pages, we are having Shadow DOMs. Multi-level Shadow DOMs are also available in many pages. Depth of the Shadow DOM is from 5 to 8 levels. Now we are trying to set up end-to-end automation testing for this Google Polymer application. We are using the latest version of Selenium Chrome Webdriver (Chrome browser / webdriver version 76.0 as on Sept 11th 2019) to automatically test the Google Polymer web pages. But Selenium Chrome Webdriver is unable to simulate mouse click events especially on the web elements that are residing within multi-level nested Shadow DOMs. Selenium Chrome Webdriver is able to simulate mouse click events on web elements that are residing in the Shadow DOM with a depth of 1 or 2 levels. But further down the level (For instance :- web element residing in 5th level Shadow DOM), Selenium Chrome Webdriver is able to locate the elements but unable to trigger simulated mouse click events on the web elements available within multi-level nested Shadow DOMs. While attempting to trigger simulated mouse click events on web elements residing within multi-level nested Shadow DOMs, "Move Target Out Of Bounds" exception is thrown at run time. This exception is usually thrown when the specific element is out of browser view port. But this element (which is a Google Polymer "core-icon" component) is in the browser view port and also clearly viewable in the page. Googling confirmed that Shadow DOM support is not provided by Selenium Chrome Webdriver. Workaround specified in some of the forums "document.querySelector('selector').shadowRoot" did not work as expected, as this Google Polymer panel (which contains the "core-icon" component) is dynamically injected at run time. So executing "document.querySelector('panelSelector').shadowRoot.querySelector('coreIconPanel')" in Chrome browser console is returning null. Since this became a major showstopper in setting up our end-to-end automation testing, please provide details on when the Shadow DOM Support will be added in Chrome Webdriver for the testability of Google Polymer Web Components. So far we have tried the following tools / combinations and this issue is occurring in all the combinations 1) Selenium 2) TestNG + Selenium 3) Robot + Selenium 4) Protractor + Selenium

**Comment by baruchvlz** [comment] 2019-09-11 05:19
WebdriverIO has a [shadow DOM selector](https://webdriver.io/docs/api/element/shadow$.html), have you tried using this to see if you can select the deeply nested element that you want to perform your interactive actions with?

**Comment by christian-bromann** [comment] 2019-09-11 06:54
Also see this blog post: https://webdriver.io/blog/2019/02/22/shadow-dom-support.html

**Comment by mgrybyk** [comment] 2019-09-13 06:55
@ReactRedux the example above shows how to interact with shadow dom, notice `shadow$` method.

**Comment by mgrybyk** [comment] 2019-09-13 07:25
@ReactRedux from your code above
```
$('').waitForExist(50000, false, 'Expected element cannot be located');
$('').shadow$('#component').waitForExist(50000, false, 'Expected element cannot be located');
```

what do you expect to find with selector like `''` ?
Please use valid selectors

**Comment by ReactRedux** [comment] 2019-09-13 09:29
Now I have added the below code snippet with "Insert Code" option.

`$('<polymer-app />').waitForExist(50000, false, 'Expected element cannot be located');`
`$('<polymer-app />').shadow$('#component').waitForExist(50000, false, 'Expected element cannot be located')`

Initially it was added as plain text.

So `<polymer-app />` tag was not displayed.

**Comment by christian-bromann** [comment] 2019-09-13 09:34
@ReactRedux can you please provide a reproducible example for us so we can run it by ourself? Otherwise it is impossible to understand what you are encountering.

**Comment by ReactRedux** [comment] 2019-09-13 09:34
@mgrbyk @christian-bromann @baruchvtz Since we are not allowed to share details about our internal applications, request you to choose one of the following options that is most convenient for your team to move forward and quickly troubleshoot this WebdriverIO "shadow$" issue.
1. Set up a Skype or Webcast meeting with your team and recreate the issue in screen sharing session.
2. Share the HTML template of our application home page in js fiddle.

**Comment by christian-bromann** [comment] 2019-09-13 09:37
@ReactRedux I suggest to build or choose an existing Polymer app and share it with us including the test code and some description of what is failing. According to your title this is not specific to your application so it should be easy to recreate the scenario in other Polymer apps as well.

**Comment by ReactRedux** [comment] 2019-09-13 09:47
@christian-bromann We will share the markup generated for our Google Polymer application home page. Will this help your team to debug and troubleshoot this issue further ?

**Comment by christian-bromann** [comment] 2019-09-13 09:48
> Will this help your team to debug and troubleshoot this issue further ?

Just the markup won't help as we also need the JavaScript so that the application can be rendered. Please provide a general sample application.

**Comment by mgrybyk** [comment] 2019-09-13 12:24
@ReactRedux the syntax is invalid `$('<polymer-app />')`.  Please use same css/xpatg selector syntax, as you use in chrome.
`$('polymer-app')`

**Comment by ReactRedux** [comment] 2019-09-13 12:36
@mgrybyk `$('<polymer-app />')` is valid syntax as per the below selectors documentation.

https://webdriver.io/docs/selectors.html

To query an element with a specific tag name use `<tag>` or `<tag />`
`<my-element>WebdriverIO is the best</my-element>`
You can query this element by calling:
`const classNameAndText = $('<my-element />');`

Initially I tried with `$('polymer-app')` locator.

But the element was not located.

We will share the jsfiddle link once we have created the general sample Google Polymer application.

**Comment by mgrybyk** [comment] 2019-09-13 12:40
Got it, waiting for a reproducible example then

**Comment by christian-bromann** [comment] 2019-09-25 08:58
@ReactRedux any chance to create a reproducible example? I will have to close this issue otherwise.

**Comment by christian-bromann** [comment] 2019-09-30 09:20
Closing due to inactivity.

**Closed by christian-bromann** 2019-09-30 09:20 UTC
Labels: Reproducible Example Missing

**Comment by Vijay1990** [comment] 2020-09-01 08:51
Hi, below is a quick reproducible an example polymer app [example](https://shop.polymer-project.org/)

![image](https://user-images.githubusercontent.com/3185919/91828136-5e835380-ec5d-11ea-8d0b-7ec471c14696.png)

You can inspect the element and see the DOM structure as well.
I tried in multiple ways to access the above-highlighted shadow dom("Ladies Outerwear- menu link"), using shadow$/shadow$$ nothing works.

@christian-bromann , @mgrybyk , @baruchvlz , @jeresig
