### ISSUE TITLE
Provide an option of not to create a session when there is no test or all tests skip in a spec file

### ISSUE THREAD

**Issue by baechul** [webdriverio/webdriverio#3314] opened 2019-01-11 23:58 UTC
**Is your feature request related to a problem? Please describe.**
In my scenario, the content of the spec is dynamically generated based on several user options passed in the cli. In some situations, a spec could have all skipped tests or there is no test created (an empty spec). Even in this case, I see a session is created and blank web browser launched and dismissed right away. 

**Describe the solution you'd like**
wdio could analyze a given spec file and create a session only when there is a test to run. Or at least not to launch a browser.

**Describe alternatives you've considered**

**Additional context**

**Comment by abjerstedt** [comment] 2019-01-12 00:57
Honestly, this feels out of scope to me and is the responsibility of your CLI to remove the spec from your arrays. 

WDIO runs whatever specs you pass in via either suite or the specs array. Just santize the values you pass in.

**Comment by christian-bromann** [comment] 2019-01-12 12:06
Duplicate of #1247

**Closed by christian-bromann** 2019-01-12 12:06 UTC
