### ISSUE TITLE
Webdriverio + PhantomJS != true

### ISSUE THREAD

**Issue by murm** [webdriverio/webdriverio#540] opened 2015-05-20 14:19 UTC
Hello!

I'm having trouble getting stuff running with PhantomJS as browser.
Everything runs perfectly fine in Firefox, but doesn't get very far in PhantomJS.

I am unsure what kind of info I should post here to be able to explain the situation and I am also unsure if this is a webdriverio problem.

This is the error I get, and it is after a loginpage, after several things has been loaded through ajax and the whole page looks like it is fully loaded (took a screenshot):

`org.openqa.selenium.WebDriverException`
`Timed out waiting for asyncrhonous script result after 5007 ms`

I have tried extending timeout to several minutes.
I have tried PhantomJS 1.9.7, 1.9.8, 2.0.0.
I have tried Selenium 2.45 and 2.43 (as recommended somewhere on the internet).

If it would help, I can post how I initiate phantomjs and so on. Want to make sure I am in the right forum for starters. :)

Best regards!

**Comment by christian-bromann** [comment] 2015-05-20 14:25
You are always right here ;-)

According to the error you've posted a command timesout. Could you paste the code snippet of your tests where it fails? Usually this error happens when you are using a command like `executeAsync` and don't call the callback function to resolve that command.

**Comment by murm** [comment] 2015-05-20 14:35
https://gist.github.com/murm/f931474ab9090960ff5a

I hope a gist will do. :)
I pasted my complete code, cleaned of url, username and password only.
It seem to crash somewhere after this: 
`client.waitForVisibleThenClick('#loginButton');`

The login is completed successfully and all, the printscreen shows a fully loaded dashboard after the login.

**Comment by christian-bromann** [comment] 2015-05-20 14:47
I cleaned up your gist, check out: https://gist.github.com/christian-bromann/ab0700dfe55438a80386

You don't need all these `then`s. WebdriverIO takes care on that. I am also not sure if all these `waitForVisibleThenClick` are necessary. However it seems that `waitForVisible` times-out when looking for `#loginButton`. My bet is that the login button isn't within the viewport which is required to resolve that command (I know it is pretty strict but this changes in `v3`). I would recommend to remove all `waitForVisibleThenClick` helper methods and just click on the damn element :wink: . Selenium is smart enough to wait until page is loaded or to scroll to the desired element if not in the viewport. Here is the super minified version:

https://gist.github.com/christian-bromann/7c737bafdf1af89a3ea2

**Comment by christian-bromann** [comment] 2015-05-20 14:51
Oh and the reason why this works in Chrome and FF is that Phantomjs usually starts with a super small resolution (something around 600x400 I think). Therefor the probability that `waitForVisible` times out is pretty high.

**Comment by christian-bromann** [comment] 2015-05-20 16:58
Closing as it seems to be resolved. Feel free to reopen if not. Cheers

**Comment by murm** [comment] 2015-05-21 06:19
Hello! I didn't have time to test this yesterday.

First, wow thanks! Didn't expect to get cleaned up code! :D
Awesome! :)

I tried both the cleaned up version and the super minified version.
Cleaned up version worked fine on Firefox, but sadly the issue when running with PhantomJS remains.
Super minified version didn't work, it tried to click on element before they were within the viewport. Rather, before they existed at all.

Seems like Selenium is smart, but not that smart! :D

**Comment by christian-bromann** [comment] 2015-05-21 11:06
Ok let's try this:

```
client.waitForVisibleThenClick = function (selector) {
    return client.waitForExists(selector).click(selector);
};
```
I am still convinced that the problem is the strictness of `waitForVisible`. Please replace the `waitForVisibleThenClick` helper with the function above. If this still throws an error at the position where you try to click on `#loginButton` then there is something wrong with that button

**Comment by murm** [comment] 2015-05-21 12:17
Hi!

That solved it!

Seriously, you know that you have chosen the right library when this is the support you get. You are awesome Christian!

Best regards!

**Comment by christian-bromann** [comment] 2015-05-21 12:23
Awesome! Happy testing :wink:

**Closed by christian-bromann** 2015-05-21 12:23 UTC
