### ISSUE TITLE
Request failed with status 500 due to Error: Sauce could not start your job

### ISSUE THREAD

**Issue by alinaIftode** [webdriverio/webdriverio#5900] opened 2020-09-29 13:00 UTC
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:**-- V 6.4.6
 - **Mode:**--WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:**  --sync
 - **Node.js version:** -- 10.19.0
 - **NPM version:** -- 6.13.4
 - **Browser name and version:** -- chrome latest
 - **Platform name and version:** -- Windows 10
 - **Additional wdio packages used (if applicable):** "@wdio/cli": "6.4.6",
    "@wdio/local-runner": "6.4.6",
    "@wdio/mocha-framework": "6.4.0",
    "@wdio/spec-reporter": "6.4.0",
    "@wdio/sync": "6.4.6",
    "@wdio/sauce-service": "6.4.6",
     "wdio-chromedriver-service": "6.0.4",

**Config of WebdriverIO**

```js
exports.config = {

    suites: {

        DriversPageTest: [
            './test/specs/driversPageTest.js'
        ]
    },

    user: process.env.SAUCELABS_USERNAME,
    key: process.env.SAUCELABS_KEY,
    region: 'eu',
    services: [
        ['sauce', {
            sauceConnect: true,
            sauceConnectOpts: {
                logfile: './target/Screenshots/sc-test.log',
                proxy: 'HOST:PORT'
            }
        }]
    ],
    maxInstances: 10,
    capabilities: [{
        browserName: 'chrome',
        browserVersion: 'latest',
        platformName: 'Windows 10',
        'sauce:options': {
            screenResolution: '1920x1080',
            name: process.env.SUITE,
            idleTimeout: 1000,
        }
    }],

    disableWebdriverScreenshotsReporting: false,
    sync: true,
    logLevel: 'error',
    coloredLogs: true,
    bail: 0,
    baseUrl: process.env.BASEURL,
    waitforTimeout: 30000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 5,
    framework: 'mocha',
    reporters: ['spec'],

    mochaOpts: {
        ui: 'bdd',
        timeout: 300000,
    },

    before: function (capabilities, specs) {
        global.screenshotPath = `./target/Screenshots/${Date.now()}.png`
        global.assert = chai.assert;
        browser.setWindowSize(1920, 1080)
        browser.url('/explore.internallogin')
        browser.deleteAllCookies()
            loginPage.loginToBetty()
        try {
            header.navigateTo("Transportation", "Planning")
        } catch (err) {
            loginPage.acceptCookies()
        header.navigateTo("Transportation", "Planning")
        }
        header.navigateTo("Transportation", "Master-Data")
        browser.switchToFrame(0)
    }
}
```

**Describe the bug**
I'm trying to use Sauce Labs secure tunnels but sometimes the test fails with no reason. They are triggered by jenkins and for the most of the time they run successfully, but sometimes they fail with an error that I attached below. This is just random and it looks like the tunnel could not be opened. This only happens when I add sauceConnect: true option to the config file.

**To Reproduce**
I cannot say exactly when this happens. It is just random. It just fails from time to time and from what I analyzed it does not seem to be related with other tests running in the same time. The problem is that the log file is not generated when it fails for this reason so I cannot add it here.

[Include code or an example repository that can easily be set up]

**Expected behavior**
The expected behavior if that the tests always runs successfully and it does not fail randomly even before it starts.

**Log**
Log files are not generated when it fails with this error. Jenkins logs look like:
```log
[0-0] RUNNING in chrome - /test/specs/driversPageTest.js
[0-0] 2020-09-29T11:19:02.349Z ERROR webdriver: Request failed with status 500 due to Error: Sauce could not start your job. For more information on what happened, please visit https://app.eu-central-1.saucelabs.com/tests/12e83b030bac4a558f699c9aa2b87652
[0-0] 2020-09-29T11:19:02.351Z ERROR webdriver: Error: Sauce could not start your job. For more information on what happened, please visit https://app.eu-central-1.saucelabs.com/tests/12e83b030bac4a558f699c9aa2b87652
    at getErrorFromResponseBody (/home/jenkins/agent/workspace/smokeTestsDAN-DriversPageTest/DAN_ui_automation/node_modules/webdriver/build/utils.js:121:10)
    at WebDriverRequest._request (/home/jenkins/agent/workspace/smokeTestsDAN-DriversPageTest/DAN_ui_automation/node_modules/webdriver/build/request.js:149:56)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[0-0] 2020-09-29T11:19:02.352Z ERROR @wdio/runner: Error: Failed to create session.
Sauce could not start your job. For more information on what happened, please visit https://app.eu-central-1.saucelabs.com/tests/12e83b030bac4a558f699c9aa2b87652
    at startWebDriverSession (/home/jenkins/agent/workspace/smokeTestsDAN-DriversPageTest/DAN_ui_automation/node_modules/webdriver/build/utils.js:45:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[0-0]  Error:  Failed to create session.
Sauce could not start your job. For more information on what happened, please visit https://app.eu-central-1.saucelabs.com/tests/12e83b030bac4a558f699c9aa2b87652
[0-0] FAILED in chrome - /test/specs/driversPageTest.js
```

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment] 2020-09-29 13:39
Please provide more log files from your CI or from WDIO and check if the tunnel was created in the tunnel history on the Sauce Labs dashboard.

**Comment by wswebcreation** [comment] 2020-09-29 14:59
@christian-bromann 

I've been helping @alinaIftode with this issue and the tunnel is randomly not created, but the test is starting with a reference to the not started tunnel. This might be something we need to investigate in the Sauce Service with a retry or something?

**Comment by alinaIftode** [comment] 2020-09-29 15:17
I'll try to reproduce this locally. It is very heard since it happens occasionally but maybe there will be more logs there, for now the only logs that I have are those that I already attached. This is how this looks on Sauce Labs side
![image](https://user-images.githubusercontent.com/45980664/94578113-fb96d380-027f-11eb-94e2-91e58121714b.png)

**Comment by wswebcreation** [comment] 2020-10-09 07:03
@alinaIftode 

This might be related https://github.com/webdriverio/webdriverio/pull/5961

**Comment by alinaIftode** [comment] 2020-11-04 07:55
Thanks, @wswebcreation! I see now there is available the solution for #5961, but before upgrading I noticed that in the last days tests fail more with something that seems to be the same problem that I reported but I'm not sure if it is (logs look a bit different). The good thing is that now I have logs. I'll attach them here, hopefully this will be useful in debugging. 

2020-11-03T12:25:35.564Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: 3 Nov 12:25:35 - failed to check for existing tunnels
3 Nov 12:25:35 - Sauce Connect could not establish a connection.

    at Socket.cp.stdout.on.data (/home/jenkins/agent/workspace/smokeTestsDAN-DriversPageTest/DAN_ui_automation/node_modules/saucelabs/build/index.js:316:25)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

Continue...
[0-0] RUNNING in chrome - /test/specs/driversPageTest.js
[0-0] 2020-11-03T12:26:07.626Z ERROR webdriver: Request failed with status 500 due to Error: Sauce could not start your job. For more information on what happened, please visit https://app.eu-central-1.saucelabs.com/tests/49ac9772d00c4a38989d0f681c9146aa
[0-0]  Error:  Failed to create session.
[0-0] 2020-11-03T12:26:07.629Z ERROR webdriver: Error: Sauce could not start your job. For more information on what happened, please visit https://app.eu-central-1.saucelabs.com/tests/49ac9772d00c4a38989d0f681c9146aa
Sauce could not start your job. For more information on what happened, please visit https://app.eu-central-1.saucelabs.com/tests/49ac9772d00c4a38989d0f681c9146aa
    at getErrorFromResponseBody (/home/jenkins/agent/workspace/smokeTestsDAN-DriversPageTest/DAN_ui_automation/node_modules/webdriver/build/utils.js:121:10)
[0-0] FAILED in chrome - /test/specs/driversPageTest.js
    at WebDriverRequest._request (/home/jenkins/agent/workspace/smokeTestsDAN-DriversPageTest/DAN_ui_automation/node_modules/webdriver/build/request.js:149:56)

    at process._tickCallback (internal/process/next_tick.js:68:7)
Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:35 
[0-0] 2020-11-03T12:26:07.630Z ERROR @wdio/runner: Error: Failed to create session.

Sauce could not start your job. For more information on what happened, please visit https://app.eu-central-1.saucelabs.com/tests/49ac9772d00c4a38989d0f681c9146aa
    at startWebDriverSession (/home/jenkins/agent/workspace/smokeTestsDAN-DriversPageTest/DAN_ui_automation/node_modules/webdriver/build/utils.js:45:11)
[errortunel.txt](https://github.com/webdriverio/webdriverio/files/5486274/errortunel.txt)

**Comment by christian-bromann** [comment] 2020-11-04 11:49
@alinaIftode can you update all your packages and try again?

**Comment by alinaIftode** [comment] 2020-11-04 16:04
Yes. I just did, but I'll monitor the tests for a few days to see if this is solved. As I mentioned it randomly happens.

**Comment by christian-bromann** [comment] 2020-11-04 16:21
Closing this then. Happy to re-open if error re-appears.

**Comment by alinaIftode** [comment] 2020-11-06 08:29
Unfortunately the error seem to persist. Still no logs are generated in this case. I'm not really sure what else would help you in debugging this.

2020-11-06T06:25:50.153Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: spawn /home/jenkins/agent/workspace/smokeTestsNewUI-CostCalculation/OT_ui_automation_newUI/node_modules/saucelabs/build/.sc-v4.6.2/bin/sc ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Continue...
[0-0] RUNNING in chrome - /test/specs/costCalculation.js
[0-0] 2020-11-06T06:26:01.583Z ERROR webdriver: Request failed with status 500 due to Error: Sauce could not start your job. For more information on what happened, please visit https://app.eu-central-1.saucelabs.com/tests/4991951198714f2bbe135c63bf0e8685
[0-0] 2020-11-06T06:26:01.585Z ERROR webdriver: Error: Sauce could not start your job. For more information on what happened, please visit https://app.eu-central-1.saucelabs.com/tests/4991951198714f2bbe135c63bf0e8685
    at Object.getErrorFromResponseBody (/home/jenkins/agent/workspace/smokeTestsNewUI-CostCalculation/OT_ui_automation_newUI/node_modules/webdriver/build/utils.js:94:12)
    at WebDriverRequest._request (/home/jenkins/agent/workspace/smokeTestsNewUI-CostCalculation/OT_ui_automation_newUI/node_modules/webdriver/build/request.js:133:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-11-06T06:26:01.585Z ERROR @wdio/runner: Error: Failed to create session.
Sauce could not start your job. For more information on what happened, please visit https://app.eu-central-1.saucelabs.com/tests/4991951198714f2bbe135c63bf0e8685
    at Object.startWebDriverSession (/home/jenkins/agent/workspace/smokeTestsNewUI-CostCalculation/OT_ui_automation_newUI/node_modules/webdriver/build/utils.js:34:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[0-0]  Error:  Failed to create session.
Sauce could not start your job. For more information on what happened, please visit https://app.eu-central-1.saucelabs.com/tests/4991951198714f2bbe135c63bf0e8685
[0-0] FAILED in chrome - /test/specs/costCalculation.js

**Comment by christian-bromann** [comment] 2020-11-06 08:55
@alinaIftode can you please update all your dependencies?

**Comment by alinaIftode** [comment] 2020-11-06 09:06
I did update them all

  "devDependencies": {
    "@wdio/cli": "6.7.2",
    "@wdio/local-runner": "6.7.2",
    "@wdio/mocha-framework": "6.7.0",
    "@wdio/sauce-service": "6.7.2",
    "@wdio/spec-reporter": "6.7.0",
    "@wdio/sync": "6.7.2",
    "app-module-path": "  ^1.0.5",
    "chai": "^3.4.0",
    "chai-as-promised": "^5.3.0",
    "chai-immutable": "^1.5.3",
    "chromedriver": "85.0.0",
    "cucumber": "^2.0.0-rc.7",
    "drag-mock": "^1.4.0",
    "expect": "^1.20.2",
    "fetch-intercept": "^2.2.3",
    "fs": "0.0.2",
    "mocha": "^3.0.0",
    "moment": "^2.29.1",
    "node-yaml": "^3.1.0",
    "sinon": "^1.17.2",
    "sinon-chai": "^2.8.0",
    "sleep": "5.1.1",
    "wdio-chromedriver-service": "6.0.4",
    "webdriverio": "6.7.2"
  },

**Comment by christian-bromann** [comment] 2020-11-06 09:58
Can you provide some more information? How often does this happen? What is your pipeline setup? How are tests being triggered?

**Comment by christian-bromann** [comment] 2020-11-06 16:16
@alinaIftode actually we haven't released #5961 yet which contains a fix for this issue. Will release now.

**Comment by wswebcreation** [comment] 2020-11-10 16:41
@christian-bromann and @enriquegh 

Re-opening this one again. I've had contact with @alinaIftode and found out that the new _retry_ is working, but it's not solving the issue for her. We added some extra logs and now see this

![image](https://user-images.githubusercontent.com/11979740/98703330-acae8480-237b-11eb-91e6-72b31991a471.png)

The `spawn` command it calling the binary, but it looks like it's or corrupt, or not accessible

**Comment by Seamoo13** [comment] 2021-02-17 12:58
Hello, I'm having the same issue on my project. Is there a new solution?

**Comment by markcellus** [comment] 2021-05-05 12:32
Still having this issue. Did any of you ever find a fix?

**Comment by alinageorgianaiftode** [comment] 2021-05-05 12:33
No. This is still happening and I'm using the latest version of wdio.

**Comment by alinageorgianaiftode** [comment] 2021-05-05 12:35
No fix found. The problem still exists and I'm using the latest wdio.

**Comment by maxym-valor** [comment] 2021-06-15 22:14
Also having this problem.

**Comment by alexrogersdesign** [comment] 2021-11-13 21:23
Also having this problem with multiple multi-remote sessions

**Comment by darkartswizard** [comment] 2022-07-27 17:59
Plus one today.
"Request failed with status 500 due to unknown error"
Right after browser.url(url)

I think it's a transient network hit.
My next step is to wrap my 
```
await browser.url(url)
``` 
within a try/catch and taking a 2nd shot at it.

**Comment by christian-bromann** [comment] 2022-07-27 18:08
> within a try/catch and taking a 2nd shot at it.

WebdriverIO already has request retries and if the error says `Sauce could not start your job` then this happened before you can call any commands.

@wswebcreation you wanted to keep this open. I feel like this is a Sauce related issue and I don't think WebdriverIO can do anything about this. What do you think?

**Comment by darkartswizard** [comment] 2022-07-27 18:34
I’m not on Sauce.
Straight Jenkins/Docker on AWS over here.

I have tried the retries setting and it works well, but it bogs down when a
locator changes and most my tests fail and get rerun.

I’ll let you know how it goes with hardening browser.url (url) when the
error gets thrown.

**Comment by darkartswizard** [comment] 2022-07-28 11:23
Hardening browser.url (url) with a try / catch and a 2nd shot did not make any difference.
Both attempts failed. It's not a transient error in this case.

However, we think the root cause is the URL behind the firewall is whitelisted on my local machine, but not on the Docker instance. So it's an issue on my side.

**Comment by ENEMBI** [comment] 2022-08-22 10:59
I have the same issue on browserstack. Seems like it is wdio wdio issue when elements like pop up(element exist -> get element -> page is changed but element is still here -> is displayed?( it is, but app source is changed)
`[0-0] 2022-08-22T10:47:44.333Z INFO webdriver: COMMAND findElement("accessibility id", "Success. Profile was updated")
[0-0] 2022-08-22T10:47:44.333Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/11d126f6c8c1fc2948aef105804725bcb07e278b/element
[0-0] 2022-08-22T10:47:44.333Z INFO webdriver: DATA { using: 'accessibility id', value: 'Success. Profile was updated' }
[0-0] 2022-08-22T10:47:44.536Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '03030000-0000-0000-EC05-000000000000',
[0-0]   ELEMENT: '03030000-0000-0000-EC05-000000000000'
[0-0] }
[0-0] 2022-08-22T10:47:44.539Z INFO webdriver: COMMAND isElementDisplayed("03030000-0000-0000-EC05-000000000000")
[0-0] 2022-08-22T10:47:44.539Z INFO webdriver: [GET] https://hub.browserstack.com/wd/hub/session/11d126f6c8c1fc2948aef105804725bcb07e278b/element/03030000-0000-0000-EC05-000000000000/displayed
[0-0] 2022-08-22T10:47:46.887Z WARN webdriver: Request failed with status 500 due to The previously found element ""Success. Profile was updated" Image" is not present in the current view anymore. Make sure the application UI has the expected state. You could also try to switch the binding strategy using the 'boundElementsByIndex' setting for the element lookup. Original error: No matches found for Find: Identity Binding from input {(
[0-0]     Image, {{0.0, 44.0}, {414.0, 51.0}}, label: 'Success. Profile was updated'
[0-0] )}
[0-0] 2022-08-22T10:47:46.887Z INFO webdriver: Retrying 1/1
[0-0] 2022-08-22T10:47:46.887Z INFO webdriver: [GET] https://hub.browserstack.com/wd/hub/session/11d126f6c8c1fc2948aef105804725bcb07e278b/element/03030000-0000-0000-EC05-000000000000/displayed
[0-0] 2022-08-22T10:47:49.348Z ERROR webdriver: Request failed with status 500 due to WebDriver Error: The previously found element ""Success. Profile was updated" Image" is not present in the current view anymore. Make sure the application UI has the expected state. Original error: No matches found for Find: Elements matching predicate 'wdName == "Success. Profile was updated" AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0 OR selected == 0)' from input {(
[0-0]     Window, {{0.0, 0.0}, {414.0, 896.0}},
[0-0]     Window, {{0.0, 0.0}, {414.0, 896.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 896.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 896.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 896.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 896.0}},
[0-0]     Other, {{0.0, 896.0}, {414.0, 243.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 896.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 896.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 896.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 896.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 896.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 896.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 896.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 896.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 896.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 807.0}},
[0-0]     StaticText, {{267.0, 347.5}, {110.0, 62.0}}, label: 'Verify your Identity',
[0-0]     Image, {{12.0, 810.0}, {52.0, 52.0}},
[0-0]     Image, {{97.7, 810.0}, {48.2, 52.0}},
[0-0]     Image, {{179.6, 810.0}, {52.0, 52.0}},
[0-0]     Image, {{265.3, 810.0}, {52.0, 52.0}},
[0-0]     Image, {{351.0, 810.0}, {51.0, 52.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 807.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 807.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 807.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 807.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 807.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 458.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 807.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 458.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 458.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 458.0}},
[0-0]     ScrollView, {{0.0, 0.0}, {414.0, 807.0}},
[0-0]     Other, {{0.0, 458.0}, {414.0, 349.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 458.0}},
[0-0]     Other, {{0.0, 0.0}, {414.0, 458.0}},
[0-0]     Other, {{0.0, 458.0}, {414.0, 349.0}},
[0-0]     Button, {{32.0, 478.0}, {350.0, 50.0}}, label: 'Get Premium Membership',
[0-0]     Other, {{26.0, 558.0}, {362.0, 56.0}},
[0-0]     Other, {{26.0, 615.0}, {362.0, 56.0}},
[0-0]     Other, {{26.0, 672.0}, {362.0, 56.0}},
[0-0]     Other, {{26.0, 729.0}, {362.0, 56.0}},
[0-0]     Other, {{26.0, 786.0}, {362.0, 21.0}},
[0-0]     Other, {{0.0, 0.0}, {0.0, 0.0}},
[0-0]     Other, {{0.0, 0.0}, {0.0, 0.0}},
[0-0]     Other, {{0.0, 0.0}, {0.0, 0.0}},
[0-0]     Image, {{0.0, 0.0}, {414.0, 458.0}},
[0-0]     Other, {{0.0, 356.0}, {414.0, 102.0}},
[0-0]     Other, {{26.0, 558.0}, {362.0, 56.0}}, label: 'Edit Profile',
[0-0]     Image, {{26.0, 574.0}, {20.0, 20.0}},
[0-0]     Image, {{378.7, 578.0}, {9.3, 16.0}},
[0-0]     Other, {{26.0, 615.0}, {362.0, 56.0}}, label: 'Verify your Identity',
[0-0]     Image, {{26.0, 631.0}, {20.0, 20.0}},
[0-0]     Image, {{378.7, 635.0}, {9.3, 16.0}},
[0-0]     Other, {{26.0, 672.0}, {362.0, 56.0}}, label: 'Matching Survey',
[0-0]     Image, {{26.0, 688.0}, {16.7, 20.0}},
[0-0]     Image, {{378.7, 692.0}, {9.3, 16.0}},
[0-0]     Other, {{26.0, 729.0}, {362.0, 56.0}}, label: 'Activities',
[0-0]     Image, {{26.0, 745.0}, {17.1, 20.0}},
[0-0]     Image, {{378.7, 749.0}, {9.3, 16.0}},
[0-0]     Other, {{26.0, 786.0}, {362.0, 21.0}}, label: 'Availability',
[0-0]     Image, {{26.0, 802.0}, {20.0, 5.0}},
[0-0]     Image, {{378.7, 806.0}, {9.3, 1.0}},
[0-0]     Other, {{0.0, 0.0}, {0.0, 0.0}}, label: 'App Settings',
[0-0]     Image, {{0.0, 0.0}, {0.0, 0.0}},
[0-0]     Image, {{0.0, 0.0}, {0.0, 0.0}},
[0-0]     Other, {{0.0, 0.0}, {0.0, 0.0}}, label: 'Invite friends',
[0-0]     Image, {{0.0, 0.0}, {0.0, 0.0}},
[0-0]     Image, {{0.0, 0.0}, {0.0, 0.0}},
[0-0]     Other, {{0.0, 0.0}, {0.0, 0.0}}, label: 'Need Help?',
[0-0]     Image, {{0.0, 0.0}, {0.0, 0.0}},
[0-0]     Image, {{0.0, 0.0}, {0.0, 0.0}},
[0-0]     Other, {{0.0, 356.0}, {414.0, 102.0}}, label: '​T​e​s​t​A​c​t​i​v​e​
[0-0] , 18
[0-0] View Profile',
[0-0]     Image, {{231.0, 370.5}, {16.0, 16.0}},
[0-0]     Image, {{16.0, 406.5}, {21.3, 16.0}}
[0-0] )}
[0-0] 2022-08-22T10:47:49.353Z INFO webdriver: COMMAND takeScreenshot()
[0-0] 2022-08-22T10:47:49.353Z INFO webdriver: [GET] https://hub.browserstack.com/wd/hub/session/11d126f6c8c1fc2948aef105804725bcb07e278b/screenshot
[0-0] 2022-08-22T10:47:51.631Z INFO webdriver: RESULT iVBORw0KGgoAAAANSUhEUgAABNoAAAqACAYAAAB5oVuGAAAAAXNSR0IArs4c6...
[0-0] WebDriver Error in "Edit Profile.[VS-717] User is able to change "Height".Should go to "Edit Profile" page and change "Height"."
WebDriver Error: The previously found element ""Success. Profile was updated" Image" is not present in the current view anymore. Make sure the application UI has the expected state. Original error: No matches found for Find: Elements matching predicate 'wdName == "Success. Profile was updated" AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0 OR selected == 0)' from input {(
    Window, {{0.0, 0.0}, {414.0, 896.0}},
    Window, {{0.0, 0.0}, {414.0, 896.0}},
    Other, {{0.0, 0.0}, {414.0, 896.0}},
    Other, {{0.0, 0.0}, {414.0, 896.0}},
    Other, {{0.0, 0.0}, {414.0, 896.0}},
    Other, {{0.0, 0.0}, {414.0, 896.0}},
    Other, {{0.0, 896.0}, {414.0, 243.0}},
    Other, {{0.0, 0.0}, {414.0, 896.0}},
    Other, {{0.0, 0.0}, {414.0, 896.0}},
    Other, {{0.0, 0.0}, {414.0, 896.0}},
    Other, {{0.0, 0.0}, {414.0, 896.0}},
    Other, {{0.0, 0.0}, {414.0, 896.0}},
    Other, {{0.0, 0.0}, {414.0, 896.0}},
    Other, {{0.0, 0.0}, {414.0, 896.0}},
    Other, {{0.0, 0.0}, {414.0, 896.0}},
    Other, {{0.0, 0.0}, {414.0, 896.0}},
    Other, {{0.0, 0.0}, {414.0, 807.0}},
    StaticText, {{267.0, 347.5}, {110.0, 62.0}}, label: 'Verify your Identity',
    Image, {{12.0, 810.0}, {52.0, 52.0}},
    Image, {{97.7, 810.0}, {48.2, 52.0}},
    Image, {{179.6, 810.0}, {52.0, 52.0}},
    Image, {{265.3, 810.0}, {52.0, 52.0}},
    Image, {{351.0, 810.0}, {51.0, 52.0}},
    Other, {{0.0, 0.0}, {414.0, 807.0}},
    Other, {{0.0, 0.0}, {414.0, 807.0}},
    Other, {{0.0, 0.0}, {414.0, 807.0}},
    Other, {{0.0, 0.0}, {414.0, 807.0}},
    Other, {{0.0, 0.0}, {414.0, 807.0}},
    Other, {{0.0, 0.0}, {414.0, 458.0}},
    Other, {{0.0, 0.0}, {414.0, 807.0}},
    Other, {{0.0, 0.0}, {414.0, 458.0}},
    Other, {{0.0, 0.0}, {414.0, 458.0}},
    Other, {{0.0, 0.0}, {414.0, 458.0}},
    ScrollView, {{0.0, 0.0}, {414.0, 807.0}},
    Other, {{0.0, 458.0}, {414.0, 349.0}},
    Other, {{0.0, 0.0}, {414.0, 458.0}},
    Other, {{0.0, 0.0}, {414.0, 458.0}},
    Other, {{0.0, 458.0}, {414.0, 349.0}},
    Button, {{32.0, 478.0}, {350.0, 50.0}}, label: 'Get Premium Membership',
    Other, {{26.0, 558.0}, {362.0, 56.0}},
    Other, {{26.0, 615.0}, {362.0, 56.0}},
    Other, {{26.0, 672.0}, {362.0, 56.0}},
    Other, {{26.0, 729.0}, {362.0, 56.0}},
    Other, {{26.0, 786.0}, {362.0, 21.0}},
    Other, {{0.0, 0.0}, {0.0, 0.0}},
    Other, {{0.0, 0.0}, {0.0, 0.0}},
    Other, {{0.0, 0.0}, {0.0, 0.0}},
    Image, {{0.0, 0.0}, {414.0, 458.0}},
    Other, {{0.0, 356.0}, {414.0, 102.0}},
    Other, {{26.0, 558.0}, {362.0, 56.0}}, label: 'Edit Profile',
    Image, {{26.0, 574.0}, {20.0, 20.0}},
    Image, {{378.7, 578.0}, {9.3, 16.0}},
    Other, {{26.0, 615.0}, {362.0, 56.0}}, label: 'Verify your Identity',
    Image, {{26.0, 631.0}, {20.0, 20.0}},
    Image, {{378.7, 635.0}, {9.3, 16.0}},
    Other, {{26.0, 672.0}, {362.0, 56.0}}, label: 'Matching Survey',
    Image, {{26.0, 688.0}, {16.7, 20.0}},
    Image, {{378.7, 692.0}, {9.3, 16.0}},
    Other, {{26.0, 729.0}, {362.0, 56.0}}, label: 'Activities',
    Image, {{26.0, 745.0}, {17.1, 20.0}},
    Image, {{378.7, 749.0}, {9.3, 16.0}},
    Other, {{26.0, 786.0}, {362.0, 21.0}}, label: 'Availability',
    Image, {{26.0, 802.0}, {20.0, 5.0}},
    Image, {{378.7, 806.0}, {9.3, 1.0}},
    Other, {{0.0, 0.0}, {0.0, 0.0}}, label: 'App Settings',
    Image, {{0.0, 0.0}, {0.0, 0.0}},
    Image, {{0.0, 0.0}, {0.0, 0.0}},
    Other, {{0.0, 0.0}, {0.0, 0.0}}, label: 'Invite friends',
    Image, {{0.0, 0.0}, {0.0, 0.0}},
    Image, {{0.0, 0.0}, {0.0, 0.0}},
    Other, {{0.0, 0.0}, {0.0, 0.0}}, label: 'Need Help?',
    Image, {{0.0, 0.0}, {0.0, 0.0}},
    Image, {{0.0, 0.0}, {0.0, 0.0}},
    Other, {{0.0, 356.0}, {414.0, 102.0}}, label: '​T​e​s​t​A​c​t​i​v​e​
, 18
View Profile',
    Image, {{231.0, 370.5}, {16.0, 16.0}},
    Image, {{16.0, 406.5}, {21.3, 16.0}}
)}
    at getErrorFromResponseBody (D:\Work\Projects\vibe-mob-atfv2\node_modules\webdriver\build\utils.js:198:12)
    at NodeJSRequest._request (D:\Work\Projects\vibe-mob-atfv2\node_modules\webdriver\build\request\index.js:166:60)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Element.wrapCommandFn (D:\Work\Projects\vibe-mob-atfv2\node_modules\@wdio\utils\build\shim.js:137:29)
    at async Element.wrapCommandFn (D:\Work\Projects\vibe-mob-atfv2\node_modules\@wdio\utils\build\shim.js:137:29)
    at async Element.elementErrorHandlerCallbackFn (D:\Work\Projects\vibe-mob-atfv2\node_modules\webdriverio\build\middlewares.js:24:32)
    at async Element.wrapCommandFn (D:\Work\Projects\vibe-mob-atfv2\node_modules\@wdio\utils\build\shim.js:137:29)
    at async Element.isDisplayed (D:\Work\Projects\vibe-mob-atfv2\node_modules\webdriverio\build\commands\element\isDisplayed.js:83:9)
    at async Element.wrapCommandFn (D:\Work\Projects\vibe-mob-atfv2\node_modules\@wdio\utils\build\shim.js:137:29)
    at async Element.elementErrorHandlerCallbackFn (D:\Work\Projects\vibe-mob-atfv2\node_modules\webdriverio\build\middlewares.js:24:32)`

**Comment by christian-bromann** [comment] 2023-01-23 20:12
I am going ahead and close this issue. There is nothing actionable here given the root cause of the issue couldn't be found.

**Closed by christian-bromann** 2023-01-23 20:12 UTC
Labels: Needs Investigation, wdio-sauce-service
