### ISSUE TITLE
[🐛 Bug]: Webdriverio acceptAlert() is not working on chrome 99

### ISSUE THREAD

**Issue by linjin-harvey** [webdriverio/webdriverio#8088] opened 2022-03-09 08:33 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

5.23.0

### Node.js Version

7.19.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [
    {
      maxInstances: TYPE === "TEST" ? 15 : 4,
      browserName: "chrome",
      "goog:chromeOptions": {
        useAutomationExtension: false,
        args: ["--start-maximized", "ignore-certificate-errors", "--host-resolver-rules=MAP *.bing.com 127.0.0.1, MAP *.pulsemgr.com 127.0.0.1"]
      },//--host-resolver-rules is using to navigate specific host request to localhost since some 3rd party request takes too long time to response
      "selenoid:options": {
        name: "Core E2E",
        enableVNC: true,
        enableVideo: true,
        acceptSslCerts: true,
        videoName: videoName || "CORE-E2E",
        version: "99"
      }
    }
  ],
```

### What happened?

Cannot accept alter, then script failed when processing next steps( get page element text)
Error:
unexpected alert open: {Alert text : CONGRATULATIONS, THE ENROLLMENT WAS COMPLETED!}
  (Session info: chrome=99.0.4844.51)

### What is your expected behavior?

Accept alert then close the prompt and process next steps success

### How to reproduce the bug.

In my site it always can be reproduced

### Relevant log output

```typescript
Error:
unexpected alert open: {Alert text : CONGRATULATIONS, THE ENROLLMENT WAS COMPLETED!}
  (Session info: chrome=99.0.4844.51)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2022-03-09 08:56
Thanks for reporting!

Unfortunately there is nothing WebdriverIO can do about this. If you check the logs and see that WebdriverIO actually send the command to accept the alert but Chrome still throws the error there must be something wrong in the driver or somewhere else. At the end of the day WebdriverIO just triggers the command but doesn't actually executes it.

Therefor I will close the issue until we can determine that this actually is caused by some misbehavior on WebdriverIO side.

**Closed by christian-bromann** 2022-03-09 08:56 UTC
Labels: Bug 🐛, Needs Triaging ⏳
