### ISSUE TITLE
isExisting fails on the RDC cloud of Sauce Labs

### ISSUE THREAD

**Issue by wswebcreation** [webdriverio/webdriverio#3431] opened 2019-01-26 00:19 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** `^5.3.0`
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** `8.12.0`
 - **NPM version:** `6.4.1`
 - **Browser name and version:** Native app
 - **Platform name and version:** Android

**Config of WebdriverIO**
The Config file for android can be found [here](https://github.com/saucelabs/sample-app-mobile/blob/master/tests/e2e/config/wdio.android.rdc.conf.js)

**Describe the bug**
On the RDC cloud of Sauce Labs Android native app tests fail when trying to check if an element exists or not. In the Appium logs you can see that the element couldn't be found, even after retrying it three times 

**To Reproduce**
Execute a native app testproject on an Android device. 9 out of 10 times elements that are not visible on the screen are also not in the UI-hierarchy. So if you open a new screen and want to verify that the previous screen is not visible anymore the test fails

**Expected behavior**
Return `false` if not found

**Log**
The Webdriver logs

```shell
[0-0] 2019-01-21T15:26:44.086Z INFO webdriver: COMMAND findElement("accessibility id", "test-CONTINUE SHOPPING")
[0-0] 2019-01-21T15:26:44.087Z INFO webdriver: [POST] https://eu1.appium.testobject.com:443/wd/hub/session/a988c8e0-e2e3-4179-a452-ee8b0c40e2d8/element
[0-0] 2019-01-21T15:26:44.087Z INFO webdriver: DATA { using: 'accessibility id', value: 'test-CONTINUE SHOPPING' }
[0-0] 2019-01-21T15:26:44.283Z DEBUG webdriver: request failed due to status 7
[0-0] 2019-01-21T15:26:44.284Z INFO webdriver: Retrying 1/3
[0-0] 2019-01-21T15:26:44.284Z INFO webdriver: [POST] https://eu1.appium.testobject.com:443/wd/hub/session/a988c8e0-e2e3-4179-a452-ee8b0c40e2d8/element
[0-0] 2019-01-21T15:26:44.284Z INFO webdriver: DATA { using: 'accessibility id', value: 'test-CONTINUE SHOPPING' }
[0-0] 2019-01-21T15:26:44.459Z DEBUG webdriver: request failed due to status 7
[0-0] 2019-01-21T15:26:44.460Z INFO webdriver: Retrying 2/3
[0-0] 2019-01-21T15:26:44.460Z INFO webdriver: [POST] https://eu1.appium.testobject.com:443/wd/hub/session/a988c8e0-e2e3-4179-a452-ee8b0c40e2d8/element
[0-0] 2019-01-21T15:26:44.460Z INFO webdriver: DATA { using: 'accessibility id', value: 'test-CONTINUE SHOPPING' }
[0-0] 2019-01-21T15:26:44.624Z DEBUG webdriver: request failed due to status 7
[0-0] 2019-01-21T15:26:44.625Z INFO webdriver: Retrying 3/3
[0-0] 2019-01-21T15:26:44.625Z INFO webdriver: [POST] https://eu1.appium.testobject.com:443/wd/hub/session/a988c8e0-e2e3-4179-a452-ee8b0c40e2d8/element
[0-0] 2019-01-21T15:26:44.625Z INFO webdriver: DATA { using: 'accessibility id', value: 'test-CONTINUE SHOPPING' }
[0-0] 2019-01-21T15:26:44.842Z DEBUG webdriver: request failed due to status 7
```

When I use the `error` logs

```shell
Stderr:
[0-0] 2019-01-21T15:31:39.174Z ERROR webdriver: Request failed due to Error: An element could not be located on the page using the given search parameters.
    at Request._callback (/Users/wimselles/Sauce/Git/sample-app-ios/node_modules/webdriver/build/request.js:113:21)
    at Request.self.callback (/Users/wimselles/Sauce/Git/sample-app-ios/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/wimselles/Sauce/Git/sample-app-ios/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/wimselles/Sauce/Git/sample-app-ios/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```

The Appium logs

```shell
68615:26:44 V [HTTP] --> POST /wd/hub/session/a988c8e0-e2e3-4179-a452-ee8b0c40e2d8/element
68715:26:44 V [HTTP] {"using":"accessibility id","value":"test-CONTINUE SHOPPING"}
68815:26:44 V [debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["accessibility id","test-CONTINUE SHOPPING","a988c8e0-e2e3-4179-a452-ee8b0c40e2d8"]
68915:26:44 V [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
69015:26:44 V [debug] [BaseDriver] Waiting up to 0 ms for condition
69115:26:44 V [debug] [JSONWP Proxy] Matched '/element' to command name 'findElement'
69215:26:44 V [debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8209/wd/hub/session/3382e68c-9992-4820-bd9d-52a832e9e8e1/element] with body: {"strategy":"accessibility id","selector":"test-CONTINUE SHOPPING","context":"","multiple":false}
69315:26:44 V [debug] [MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
69415:26:44 V [debug] [MJSONWP] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
69515:26:44 V [debug] [MJSONWP]     at AndroidUiautomator2Driver.callee$0$0$ (/root/appium/appium/1.9.1/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:75:11)
69615:26:44 V [debug] [MJSONWP]     at tryCatch (/root/appium/appium/1.9.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
69715:26:44 V [debug] [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/root/appium/appium/1.9.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
69815:26:44 V [debug] [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/root/appium/appium/1.9.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
69915:26:44 V [debug] [MJSONWP]     at GeneratorFunctionPrototype.invoke (/root/appium/appium/1.9.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
70015:26:44 V [debug] [MJSONWP]     at <anonymous>
70115:26:44 V [HTTP] <-- POST /wd/hub/session/a988c8e0-e2e3-4179-a452-ee8b0c40e2d8/element 500 73 ms - 164
70215:26:44 V [HTTP] 
70315:26:44 V [HTTP] --> POST /wd/hub/session/a988c8e0-e2e3-4179-a452-ee8b0c40e2d8/element
70415:26:44 V [HTTP] {"using":"accessibility id","value":"test-CONTINUE SHOPPING"}
70515:26:44 V [debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["accessibility id","test-CONTINUE SHOPPING","a988c8e0-e2e3-4179-a452-ee8b0c40e2d8"]
70615:26:44 V [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
70715:26:44 V [debug] [BaseDriver] Waiting up to 0 ms for condition
70815:26:44 V [debug] [JSONWP Proxy] Matched '/element' to command name 'findElement'
70915:26:44 V [debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8209/wd/hub/session/3382e68c-9992-4820-bd9d-52a832e9e8e1/element] with body: {"strategy":"accessibility id","selector":"test-CONTINUE SHOPPING","context":"","multiple":false}
71015:26:44 V [debug] [MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
71115:26:44 V [debug] [MJSONWP] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
71215:26:44 V [debug] [MJSONWP]     at AndroidUiautomator2Driver.callee$0$0$ (/root/appium/appium/1.9.1/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:75:11)
71315:26:44 V [debug] [MJSONWP]     at tryCatch (/root/appium/appium/1.9.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
71415:26:44 V [debug] [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/root/appium/appium/1.9.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
71515:26:44 V [debug] [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/root/appium/appium/1.9.1/node_modules/a
```

I already had a conversation with @abjerstedt about it and he mentioned the following

> we check if the selector returns greater than or equal to 1 response, by using elements instead of element
technically, thats a pointless check since $() would be adequate
return this.parent.$(this.selector).elementId
that should cut it tbh

> but the question is, is appium matching the wc3 expected result for a no such element found error?

**Comment by abjerstedt** [comment] 2019-02-02 15:46
@wswebcreation Please checkout https://github.com/webdriverio/webdriverio/pull/3487 and see if this fixes your issue. 

With this fix, I at least have safari-iphone and chrome-android working.

**Comment by wswebcreation** [comment] 2019-02-02 18:37
Hi @abjerstedt

Tnx

Will try it tomorrow or Monday (just came back from the US, so need to catch some sleep)
Keep you posted

**Comment by abjerstedt** [comment] 2019-02-04 15:08
Closed via https://github.com/webdriverio/webdriverio/pull/3487
(confirmed by @wswebcreation )

**Closed by abjerstedt** 2019-02-04 15:08 UTC
Labels: Bug🐛, good first pick, help wanted

**Comment by wswebcreation** [comment] 2019-02-04 15:17
You beat me, just wanted to close it

**Comment by adamweeks** [comment] 2019-03-19 16:00
@abjerstedt this seems to be happening on IE on sauce labs as well. Should I open another ticket?

Error message is:
>Request failed due to Error: Unable to find element with css selector

**Comment by christian-bromann** [comment] 2019-03-19 16:36
> Unable to find element with css selector

This just means it can't find the element but the strategy was supported.

**Comment by adamweeks** [comment] 2019-03-19 17:16
@christian-bromann 

> > Unable to find element with css selector
> 
> This just means it can't find the element but the strategy was supported.

Right, I understand that, but it is causing the test suite to throw an error and stop running when it should simply return false.

```js
browser.waitUntil(() => this.personSuggestionsItemTitle.isExisting() === false, 3500, 'user lookup did not hide');
```

**Comment by mgrybyk** [comment] 2019-03-19 19:00
Can you update wedriverio to latest version? @adamweeks

**Comment by adamweeks** [comment] 2019-03-19 19:15
> Can you update wedriverio to latest version? @adamweeks

@mgrybyk I'm on the latest, 5.7.4
