### ISSUE TITLE
[🐛 Bug]: Specs behavior in WDIO8 not consistent with documentation

### ISSUE THREAD

**Issue by MadSandwich** [webdriverio/webdriverio#9701] opened 2023-02-02 16:24 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

On both latest LTS and latest

### Mode

WDIO Testrunner

### Which capabilities are you using?

For the first example:
```typescript
{
        maxInstances: 2,
        browserName: 'chrome',
        acceptInsecureCerts: true
}
```

For the second example:
```typescript
{
        maxInstances: 1,
        browserName: 'chrome',
        acceptInsecureCerts: true
}
```

### What happened?

Set maxinstances = 2

Using initially generated wdio + cucumber tests, define the same feature 2 times

```
 specs: [
        './features/login.feature',
        './features/login.feature'
]
```

Instead of 2 executions, one for each defined feature, it simply runs only 1 feature.
________________________

Set maxinstances = 1

Using initially generated wdio + cucumber tests, define the same feature 2 times

```
 specs: [
        './features/login.feature',
        './features/login.feature'
]
```

Instead of 2 executions, one for each defined feature, it fires two times for each defined feature file. So in practice it executes 4 times.

### What is your expected behavior?

If specs defined in **single** array

```
specs: [
        './features/login.feature',
        './features/login.feature',
],
```

should behave according to the documentation: The test for **each** spec file will be run in a separate worker process.

______________
If specs defined in nested array

```
specs: [
        ['./features/login.feature',
        './features/login.feature'],
],
```

should behave according to the documentation: In order to have a group of spec files run in the same worker process, simply enclose them in an array within the specs array.

### How to reproduce the bug.

https://github.com/MadSandwich/wdio_specs_execution

### Relevant log output

```typescript
Execution of 1 workers started at 2023-02-02T16:21:13.955Z

2023-02-02T16:21:14.029Z INFO chromedriver: Initiate Chromedriver Launcher (v8.0.1)
2023-02-02T16:21:14.031Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-02-02T16:21:14.034Z INFO chromedriver: Start Chromedriver (C:\Users\Artsiom_Burlai\projects\wdio_specs_execution1\node_modules\chromedriver\lib\chromedriver\chromedriver.exe) with args --port=9515 --url-base=/
2023-02-02T16:21:14.390Z INFO chromedriver: Starting ChromeDriver 109.0.5414.74 (e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}) on port 9515
2023-02-02T16:21:14.390Z INFO chromedriver: Only local connections are allowed.
2023-02-02T16:21:14.390Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2023-02-02T16:21:14.412Z INFO chromedriver: ChromeDriver was started successfully.
2023-02-02T16:21:14.475Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-02-02T16:21:14.477Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,wdio.conf.js
[0-0] 2023-02-02T16:21:15.832Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - file:///C:/Users/Artsiom_Burlai/projects/wdio_specs_execution1/features/login.feature, file:///C:/Users/Artsiom_Burlai/projects/wdio_specs_execution1/features/login.feature, file:///C:/Users/Artsiom_Burlai/projects/wdio_specs_execution1/features/login.feature, file:///C:/Users/Artsiom_Burlai/projects/wdio_specs_execution1/features/login.feature
[0-0] 2023-02-02T16:21:16.637Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-02-02T16:21:16.797Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2023-02-02T16:21:16.797Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
[0-0] }

DevTools listening on ws://127.0.0.1:63960/devtools/browser/57a5e391-6b98-4989-968b-12d0d8337c46
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2023-02-02 18:40
This behavior happens because both point to the same file. If you create a `./features/login2.feature` the behavior is as expected. Let me know if you have any further questions.

**Comment by MadSandwich** [comment] 2023-02-02 19:01
@christian-bromann  in wdio v7 those behaviour was different and correspond to the documentation, if for the 1st example I can agreed that current behaviour is ok, as name the same. For the second behaviour I can't agree as it double times of execution, instead of 2 times it execute it 4 times (in wdio v7 this behaviour was different and if 2 were specified it run them only 2 times).

I use this in my real project for execution of one feature file specified number of times and after migration to v8 I found that this functionality was changed. As far as I know there is no other build in possibilities to do such in wdio. 

Please take a look into this once again.

**Comment by christian-bromann** [comment] 2023-02-02 19:25
> For the second behaviour I can't agree as it double times of execution, instead of 2 times it execute it 4 times (in wdio v7 this behaviour was different and if 2 were specified it run them only 2 times).

I can't reproduce it, I have my spec defines as:
```js
    specs: [[
        './features/login.feature',
        './features/login2.feature'
    ]],
```

And it runs a single browser session as expected. Please clarify which behavior changed.

**Comment by MadSandwich** [comment] 2023-02-03 09:06
@christian-bromann sorry if my explanations hard to understand. I've tried to show you a simple case.

```
    specs: [
        ['./features/login.feature'],
    ],
```
Then just execute run. Here is a screenshot with a problem:
![image](https://user-images.githubusercontent.com/57759145/216557806-9c6f48b2-6662-4ea9-b1b5-5a9c1bd9d74c.png)

Let me know please if any additional information is needed.

**Comment by christian-bromann** [comment] 2023-02-03 19:56
Now I am able to reproduce what you experience. This is indeed not correct. I will re-open the issue. Feel free to start investigate and help us work on a fix for this. Any contributions are very much appreciated. Thanks!

**Comment by MadSandwich** [comment] 2023-02-06 13:40
The only thing I was able to find that inside wdio/local-runner
config contain array with 1 value, but after worker is assigned workerPool it already have array of 2 specs. Maybe for someone it would help, also attaching a screenshot:

![image](https://user-images.githubusercontent.com/57759145/216985866-ddaceee0-573f-44fd-8205-078ecdc23ae8.png)

**Comment by MadSandwich** [comment] 2023-02-13 17:38
https://github.com/webdriverio/webdriverio/pull/9763

**Closed** 2023-03-01 04:33 UTC
Labels: Bug 🐛, help wanted
