### ISSUE TITLE
wdio testrunner mocha delay option skip spec

### ISSUE THREAD

**Issue by Gordiievskyi** [webdriverio/webdriverio#5444] opened 2020-05-28 14:21 UTC
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1.2
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:**async
 - **Node.js version:** v12.16.1
 - **NPM version:**6.13.4
 - **Browser name and version:** chrome
 - **Platform name and version:** OSX 10.14.6
 - **Additional wdio packages used (if applicable):**     "@wdio/appium-service": "^6.1.0",
    "@wdio/browserstack-service": "^6.0.17",
    "@wdio/cli": "^6.1.2",
    "@wdio/local-runner": "^6.1.2",
    "@wdio/logger": "^6.0.16",
    "@wdio/mocha-framework": "^6.1.0",
    "@wdio/selenium-standalone-service": "^6.0.16",
    "@wdio/spec-reporter": "^6.0.16",
**Config of WebdriverIO**
An example of how you configured WebdriverIO config

#local_with_proxy.js
```
let ProxyService = require('../../src/utils/proxy/proxy-service');
const {COMMON_CONFIG} = require('./common');

exports.config = Object.assign(
  COMMON_CONFIG,
  {
    reporters: ['spec'],
    maxInstances: 1,
    path: '/wd/hub',
    port: 4444,
    capabilities: [
      {
        browserName: 'chrome',
        acceptInsecureCerts: true,
        proxy: {
          'proxyType': 'MANUAL',
          'httpProxy': '0.0.0.0:8081',
          'sslProxy': '0.0.0.0:8081'
        }
      }
    ],

    services: [
      [
        'selenium-standalone',
      ],
      [ProxyService]
    ],
  });

```
#common.js

```
const getLogger = require('@wdio/logger').default;
const setScreenWidth = require('../../src/utils/helpers/screen');
const log = getLogger('root');
log.setLevel('info');
/**
* Loades all containers before tests starts
*/
require('../../classloader');
exports.COMMON_CONFIG = {
  //
  // ====================
  // Runner Configuration
  // ====================


  specs: [
    './src/tests/**/*.js',
  ],
  maxInstances: 1,

  //
  // ===================
  // Test Configurations
  // ===================
  // Define all options that are relevant for the WebdriverIO instance here
  //
  // Level of logging verbosity: trace | debug | info | warn | error | silent
  logLevel: 'info',

  // If you only want to run your tests until a specific amount of tests have failed use
  // bail (default is 0 - don't bail, run all tests).
  bail: 0,
  //
  // Set a base URL in order to shorten url command calls. If your `url` parameter starts
  // with `/`, the base url gets prepended, not including the path portion of your baseUrl.
  // If your `url` parameter starts without a scheme or `/` (like `some/path`), the base url
  // gets prepended directly.
  baseUrl: '0.0.0.0',
  //
  // Default timeout for all waitFor* commands.
  waitforTimeout: 30000,
  //
  // Default timeout in milliseconds for request
  // if browser driver or grid doesn't send response
  connectionRetryTimeout: 90000,
  //
  // Default request retries count
  connectionRetryCount: 3,
  //
  // Test runner services
  // Services take over a specific job you don't want to take care of. They enhance
  // your test setup with almost no effort. Unlike plugins, they don't add new
  // commands. Instead, they hook themselves up into the test process.
  proxyServiceOpts: {
    proxyPorcess: {
      binaryPath: '../../Downloads/browserup-proxy-2.0.1/bin/browserup-proxy',
      proxyApiPort: '8080',
      proxyApiHost: '0.0.0.0',
    },
    proxies: [
      {
        schema: 'http',
        proxy_query: {
          port: 8081,
          trustAllServers: true,
        }
      },
      {
        schema: 'http',
        proxy_query: {
          port: 8082,
          trustAllServers: true,
        }
      }
    ]
  },
  seleniumLogs: 'logs',
  framework: 'mocha',
  //
  // Test reporter for stdout.
  // The only one supported by default is 'dot'
  // see also: https://webdriver.io/docs/dot-reporter.html
  // reporters: ['spec'],

  //
  // Options to be passed to Mocha.
  // See the full list at http://mochajs.org/
  mochaOpts: {
    ui: 'bdd',
    timeout: 3600000,
    delay: true
  },

  /**
   * Gets executed once before all workers get launched.
   * @param {Object} config wdio configuration object
   * @param {Array.<Object>} capabilities list of capabilities details
   */
  onPrepare: async function(config, capabilities) {
    process.env.NODE_ENV='prod';
  },
  /**
   * Gets executed before test execution begins. At this point you can access to all global
   * variables like `browser`. It is the perfect place to define custom commands.
   * @param {Array.<Object>} capabilities list of capabilities details
   * @param {Array.<String>} specs List of spec file paths that are to be run
   */
  before: async function(capabilities, specs) {
    /**
    * Update global object with chai bdd and lodash.
    */
    const chai = require('chai');
    const chaiMatchPattern = require('chai-match-pattern');
    chai.use(chaiMatchPattern);
    global.expect = chai.expect;
    global._lodash = chaiMatchPattern.getLodashModule();
    await setScreenWidth(1350);
    // await setScreenWidth(1112);
  },

};

```

**Describe the bug**
Mocha --delay(delay root) skip tests with mocha opt delay:true

**To Reproduce**
Set mocha opt delay to true in wdio-config.js:
```
 mochaOpts: {
    ui: 'bdd',
    timeout: 3600000,
    delay: true
  },
```

create spec with following content:
#test.js 
```
var assert = require('assert');
async function returnArr() {
  return [2, 2, 1];
}

setTimeout(async function() {
  const arr = await returnArr();

  describe('my suite', function() {
    for (let el of arr) {
      it(`Is element ${el} has index 1`, async function() {
        assert.equal(arr.indexOf(el), 1);
      });
    }
  });

  run();
}, 500);
```
run the test : 
```
./node_modules/.bin/wdio config/wdio-config.js --spec test.js 
```
Result:  spec is skipped in chrome

**Expected behavior**
Spec executed with 3 tests inside it

**Log**
https://gist.github.com/Gordiievskyi/10c759e8bdec76dcef71df15bfafb632

**Additional context**
Note: if run same test with mocha `./node_modules/mocha/bin/mocha test.js --delay` it will execute 3 tests
Note: if set delay to false and change test to synchronous everything it will also execute 3 test

#test.js 
```
var assert = require('assert');
function returnArr() {
  return [2, 2, 1];
}

const arr =  returnArr();

describe('my suite', function() {
  for (let el of arr) {
    it(`Is element ${el} has index 1`, async function() {
      assert.equal(arr.indexOf(el), 1);
    });
  }
});
```

> Please use the correct markdown

**Comment by Gordiievskyi** [comment] 2020-07-27 14:13
Is there any progress ? Its been two month issue is in this state.

**Comment by christian-bromann** [comment] 2020-07-27 15:01
@Gordiievskyi as you can see I added a `help wanted` label which should indicate that we would like to see help from the community (e.g. you 😉) on this. Given that the issue is well written let me promote it to increase the chance for this to be picked up by someone.

**Comment by jonesh66** [comment] 2020-12-09 13:40
I'll take this up for investigation and hopefully also a fix

**Comment by grimxreaper** [comment] 2021-10-04 16:59
Hi! Has there been progress on this @jonesh66 ?

**Comment by jonesh66** [comment] 2021-10-05 04:12
Hello @grimxreaper I wasn't able to finish this. I've unassigned it since it has a tag on it now

**Comment by dragosMC91** [comment] 2022-11-19 07:04
I don't think this is something webdriverio should handle, it's related to how mocha works if i understand it correctly: https://mochajs.org/#serial-mode -> if we look at 8.1 the docs state that mocha loads the test file, execute its suites (describe blocks) and finds/loads tests and hooks (before/ it blocks) within the suite (but does not execute them yet).

There are however workarounds to this and you can implement dynamic tests. I found 2:
```
const assert = require('assert');
const arr = new Promise((resolve, reject) => setTimeout(() => {
    resolve([1,2,3])
}, 1000));

// report will show a single it block where are entries are validated
describe('verify stuff v1', function () {
    let data;

    before(async () => data = await arr);

    it("should validate dynamic data", () => {
        assert.ok(data.length >= 2);
        data.forEach(entry => {
            assert.ok(Number.isInteger(entry));
        })
    });
})

// report will show 1 it block for each entry
describe('verify stuff v2', function () {
    let data;

    before(async () => data = await arr);

    it("should validate dynamic data", () => {
        assert.ok(data.length >= 2);

        describe('', () => {
            data.forEach(entry => {
                it(`validate entry "${entry}"`, () => {
                    assert.ok(Number.isInteger(entry));
                    if(entry % 3 === 0) assert.fail("Dummy fail");
                })
            })
        })
    });
})

```

**Comment by christian-bromann** [comment] 2022-12-11 07:31
@dragosMC91 thanks for looking into this. I agree with your observation. Closing.

**Closed by christian-bromann** 2022-12-11 07:31 UTC
Labels: Needs Investigation, help wanted, good first pick, first-timers-only
