### ISSUE TITLE
RequestError: connect ECONNREFUSED 127.0.0.1:9515

### ISSUE THREAD

**Issue by vasudha0309** [webdriverio/webdriverio#8174] opened 2022-03-31 10:58 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7

### Node.js Version

12.16.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
        maxInstances: 1,
        browserName: 'chrome',
        'goog:chromeOptions': {
            args: [
                '--no-sandbox',
                '--disable-web-security',
                '--ignore-autocomplete-off-autofill',
                '--window-size=1366,768'
            ],
        },
        acceptInsecureCerts: true
    }],
```

### What happened?

I have couple of test cases, when I'm running the test cases few of them are failing randomly with the below error message and url is not loading. I am using latest version of chrome/chromedriver. Any help on this?

RequestError: connect ECONNREFUSED 127.0.0.1:9515
at ClientRequest.<anonymous> (C:\Users\Documents\GitHub2\SwiftTest\node_modules\got\dist\source\core\index.js:962:111)
at Object.onceWrapper (node:events:510:26)
at ClientRequest.emit (node:events:402:35)
at ClientRequest.emit (node:domain:475:12)
at ClientRequest.origin.emit

### What is your expected behavior?

No error should occur.

### How to reproduce the bug.

This is happening randomly.

### Relevant log output

```typescript
[0-7] Error in "0: Given Login to APM"
RequestError: connect ECONNREFUSED 127.0.0.1:9515
    at ClientRequest.<anonymous> (C:\Users\Documents\GitHub2\SwiftTest\node_modules\got\dist\source\core\index.js:962:111)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.emit (node:domain:475:12)
    at ClientRequest.origin.emit (C:\Users\Documents\GitHub2\SwiftTest\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
C:\Users\Documents\GitHub2\SwiftTest\node_modules\got\dist\source\core\index.js:962
            error = error instanceof timed_out_1.TimeoutError ? new TimeoutError(error, this.timings, this) : new RequestError(error.message, error, this);
                                                                                                              ^
node_modules/@cspotcode/source-map-support/source-map-support.js:590
RequestError: connect ECONNREFUSED 127.0.0.1:9515
    at ClientRequest.<anonymous> (C:\Users\Documents\GitHub2\SwiftTest\node_modules\got\dist\source\core\index.js:962:111)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.emit (node:domain:475:12)
    at ClientRequest.origin.emit (C:\Users\Documents\GitHub2\SwiftTest\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  code: 'ECONNREFUSED',
  timings: {
    start: 1648711545330,
    socket: 1648711545392,
    lookup: 1648711545407,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1648711043344,
    abort: undefined,
    phases: {
      wait: 54,
      dns: 19,
      tcp: 18,
      tls: undefined,
      request: 0,
      firstByte: undefined,
      download: undefined,
      total: 75946
    }
  },
  [Symbol(originalCallSite)]: [
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {}
  ],
  [Symbol(mutatedCallSite)]: [
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {}
  ]
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by vasudha0309** [comment] 2022-04-01 06:45
> Please provide full logs and/or a reproducible example of this, thanks!

Hi, There is no reproducable example since it's happening randomly in different test cases. As for the logs I have updated and given the full red error that was there in the console

**Comment by christian-bromann** [comment] 2022-04-01 07:19
Unfortunately I have to close the issue if no reproducible example can be provided. The reason for the problem is that WebdriverIO is unable to connect to your Chromedriver. This is likely due to your system and environment. There is no chance for anyone to create a fix for it as no one as access to your environment.

**Closed by christian-bromann** 2022-04-01 07:19 UTC
Labels: Bug 🐛, Reproducible Example Missing, Logs Missing

**Comment by timlonggr** [comment] 2022-10-12 10:25
I've been trying to solve this same problem. Did you ever make any progress on it?

**Comment by Bapugit** [comment] 2024-01-30 19:46
Hi,
I am facing the same issue. My WDIO framework and tests are working good till today morning, Suddenly getting this error.
Scripts are working some times, but not all the time due to below error. Its not specific to one script, its happening for all the scripts.
Note:I haven't made any upgrade to WDIO version, only change is my chrome browser has upgraded to 121, and then I have upgraded the chrome driver version. It worked for a few time after upgrade also.

Error: 0-0] 2024-01-30T19:19:11.439Z ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:9515
[0-0]     at ClientRequest.<anonymous> (file:///C:/WDIOFrameworkpublic/WDIOAutomationFramework/node_modules/got/dist/source/core/index.js:790:107)
[0-0]     at Object.onceWrapper (node:events:632:26)
[0-0]     at ClientRequest.emit (node:events:529:35)
[0-0]     at ClientRequest.emit (node:domain:489:12)


Complete Log:

024-01-30T19:19:04.849Z DEBUG @wdio/utils:initialiseServices: initialise service "chromedriver" as NPM package
2024-01-30T19:19:05.445Z DEBUG @wdio/utils:initialiseServices: initialise service "shared-store" as NPM package
2024-01-30T19:19:05.498Z INFO chromedriver: Initiate Chromedriver Launcher (v8.1.1)
2024-01-30T19:19:05.499Z INFO @wdio/cli:launcher: Run onPrepare hook
2024-01-30T19:19:05.512Z INFO chromedriver: Start Chromedriver (C:\AutomationFramework\node_modules\chromedriver\lib\chromedriver\chromedriver.exe) with args --port=9515 --url-base=/
2024-01-30T19:19:05.753Z INFO @wdio/shared-store-service: Started shared server on port 57907
2024-01-30T19:19:05.924Z INFO chromedriver: Starting ChromeDriver 121.0.6167.85 (3f98d690ad7e59242ef110144c757b2ac4eef1a2-refs/branch-heads/6167@{#1539}) on port 9515
2024-01-30T19:19:05.925Z INFO chromedriver: Only local connections are allowed.
2024-01-30T19:19:05.925Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2024-01-30T19:19:05.926Z INFO chromedriver: ChromeDriver was started successfully.
2024-01-30T19:19:06.142Z DEBUG @wdio/cli:utils: Finished to run "onPrepare" hook in 641ms
2024-01-30T19:19:06.170Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2024-01-30T19:19:06.170Z DEBUG @wdio/cli:utils: Finished to run "onWorkerStart" hook in 0ms
2024-01-30T19:19:06.172Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.js,--suite,datadriven,--env,dit
2024-01-30T19:19:06.196Z DEBUG @wdio/local-runner: Send command run to worker with cid "0-0"
[0-0] 2024-01-30T19:19:09.616Z INFO @wdio/local-runner: Run worker command: run
[0-0] Selected Test Env is: dit
[0-0] 2024-01-30T19:19:09.802Z DEBUG @wdio/runner: init remote session
[0-0] 2024-01-30T19:19:09.863Z DEBUG @wdio/utils:initialiseServices: initialise service "chromedriver" as NPM package
[0-0] 2024-01-30T19:19:10.180Z DEBUG @wdio/utils:initialiseServices: initialise service "shared-store" as NPM package
[0-0] 2024-01-30T19:19:10.382Z DEBUG @wdio/utils:shim: Finished to run "beforeSession" hook in 26ms
[0-0] RUNNING in chrome - file:///C:....../seleniumUnittests/datadriventest.js
[0-0] 2024-01-30T19:19:11.378Z DEBUG @wdio/runner: init remote session
[0-0] 2024-01-30T19:19:11.383Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2024-01-30T19:19:11.420Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2024-01-30T19:19:11.421Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       browserVersion: 'latest',
[0-0]       acceptInsecureCerts: true,
[0-0]       'sauce:options': [Object],
[0-0]       'goog:chromeOptions': [Object],
[0-0]       timeouts: [Object],
[0-0]       'wdio:sharedStoreServicePort': 57907
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     browserVersion: 'latest',
[0-0]     acceptInsecureCerts: true,
[0-0]     'sauce:options': {
[0-0]       build: 'Build 1706642345_WDIOCoreFramework',
[0-0]       screenResolution: '1100x1000',
[0-0]       name: 'WDIO Core Framework',
[0-0]       prerun: [Object]
[0-0]     },
[0-0]     'goog:chromeOptions': { args: [] },
[0-0]     timeouts: { implicit: 20000, pageLoad: 30000, script: 1300000 },
[0-0]     'wdio:sharedStoreServicePort': 57907
[0-0]   }
[0-0] }
[0-0] 2024-01-30T19:19:11.439Z ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:9515
[0-0]     at ClientRequest.<anonymous> (file:///C:/WDIOFrameworkpublic/WDIOAutomationFramework/node_modules/got/dist/source/core/index.js:790:107)
[0-0]     at Object.onceWrapper (node:events:632:26)
[0-0]     at ClientRequest.emit (node:events:529:35)
[0-0]     at ClientRequest.emit (node:domain:489:12)
[0-0]     at Socket.socketErrorListener (node:_http_client:501:9)
[0-0]     at Socket.emit (node:events:517:28)
[0-0]     at Socket.emit (node:domain:489:12)
[0-0]     at emitErrorNT (node:internal/streams/destroy:151:8)
[0-0]     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[0-0]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
[0-0] 2024-01-30T19:19:11.440Z DEBUG @wdio/utils:shim: Finished to run "after" hook in 0ms
[0-0] 2024-01-30T19:19:11.440Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] Unable to connect to "http://localhost:9515/", make sure browser driver is running on that address.
[0-0] If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
[0-0]     at startWebDriverSession (file:///C:/WDIOFrameworkpublic/WDIOAutomationFramework/node_modules/webdriver/build/utils.js:68:15)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async WebDriver.newSession (file:///C:/WDIOFrameworkpublic/WDIOAutomationFramework/node_modules/webdriver/build/index.js:24:45)
[0-0]     at async remote (file:///C:/WDIOFrameworkpublic/WDIOAutomationFramework/node_modules/webdriverio/build/index.js:48:22)
[0-0]     at async Runner._startSession (file:///C:/WDIOFrameworkpublic/WDIOAutomationFramework/node_modules/@wdio/runner/build/index.js:221:29)
[0-0]     at async Runner._initSession (file:///C:/WDIOFrameworkpublic/WDIOAutomationFramework/node_modules/@wdio/runner/build/index.js:187:25)
[0-0]     at async Runner.run (file:///C:/WDIOFrameworkpublic/WDIOAutomationFramework/node_modules/@wdio/runner/build/index.js:77:19)
2024-01-30T19:19:11.573Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in chrome - file:///C:/.../datadriventest.js
2024-01-30T19:19:26.654Z DEBUG @wdio/cli:utils: Finished to run "onComplete" hook in 1ms

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:21

2024-01-30T19:19:26.656Z INFO @wdio/local-runner: Shutting down spawned worker
2024-01-30T19:19:26.921Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2024-01-30T19:19:26.922Z INFO @wdio/local-runner: shutting down

**Comment by byKosta** [comment] 2024-02-18 15:16
@Bapugit Hi, did you manage to find a solution?
