### ISSUE TITLE
setValue, addValue doesn't work in webview on android mobile devices

### ISSUE THREAD

**Issue by xlenz** [webdriverio/webdriverio#3424] opened 2019-01-25 11:21 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.4.5
 - **Mode:**  WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Appium:** 1.10.1
 - **Browser name and version:** mobile chrome 71, chrome driver 44
 - **Platform name and version:** android 9
 - **Additional wdio packages used (if applicable):** 
```
{
    "@types/mocha": "^5.2.5",
    "@types/node": "^10.12.18",
    "@wdio/allure-reporter": "^5.4.4",
    "@wdio/cli": "^5.4.5",
    "@wdio/dot-reporter": "^5.4.3",
    "@wdio/local-runner": "^5.4.3",
    "@wdio/mocha-framework": "^5.4.3",
    "@wdio/sync": "^5.4.3",
    "ts-node": "^8.0.1",
    "tsconfig-paths": "^3.7.0",
    "typescript": "^3.2.4"
  }
```

**Config of WebdriverIO**
capabilities:
```
{
    maxInstances: 1,
    "appium:platformName": "Android",
    "appium:deviceName": "Pixel 2",
    "appium:browserName": 'chrome',
    "appium:chromeOptions": {
      args: ['--no-first-run'],
    },
    "appium:newCommandTimeout": 240
  }
```

note that I'm using prefixes **appium:**

**Describe the bug**
add /set value throws 
```
/wd/hub/session/a8fb82ff-bd82-4b90-87fb-df81914b27cd/element/0.7572212386769221-1/value has failed

unknown error: 'value' must be a list
```

**To Reproduce**
Run test on Android device in mobile chrome or any webview

```
$("input").setValue("qwe")
$("input").addValue("asd")
```

**Expected behavior**
add / set value should work

**Log**
```
/wd/hub/session/a8fb82ff-bd82-4b90-87fb-df81914b27cd/element/0.7572212386769221-1/value has failed

unknown error: 'value' must be a list
```

**Additional context**
instead of using jsonwp command 
```
{
        "name": "value",
        "type": "string[]",
      }
```

we are using webdriver command
```
{
        "name": "text",
        "type": "string"
      }
```

I've tried to force using jsonwp setvalue and addvalue commands and succeeded.

Maybe problem is because of isW3c is detected incorrectly?

**Comment by xlenz** [comment] 2019-01-25 12:35
found what is causing this defect, will do PR soon

**Comment by mgrybyk** [comment] 2019-01-25 14:37
@nami-varthakavi this might work for you

**Comment by christian-bromann** [comment] 2019-01-25 17:26
Let's continue the discussion in #3425

**Comment by jlipps** [comment] 2019-01-25 17:36
(For context for the log request, I'm wondering if this is an Appium bug, not a wdio bug.)

**Comment by mgrybyk** [comment] 2019-01-25 17:52
There are nothing to do with appium, the log is provided above, it is wdio defect. 
We should use jsonwp here, but using w3c.

**Comment by christian-bromann** [comment] 2019-01-25 17:56
> There are nothing to do with appium

If you run Appium it has something to do with Appium. Please provide the full Appium logs so we can get an idea where the problem is.

**Comment by mgrybyk** [comment] 2019-01-25 17:57
@christian-bromann 

/wd/hub/session/a8fb82ff-bd82-4b90-87fb-df81914b27cd/element/0.7572212386769221-1/value has failed

500: 'value' must be a list


There is nothing else there. With PR proposed these and some other commands start working fine and has no impact on using wdio without appium.

In non w3c mode jsonwp should override w3c commands

**Comment by mgrybyk** [comment] 2019-01-25 17:58
Ok, give me a sec, I'll provide you same error in appium log format

**Comment by jlipps** [comment] 2019-01-25 18:00
> There is nothing else there. With PR proposed these and some other commands start working fine and has no impact on using wdio without appium.

The problem is it would break other Appium usage. That is why I originally proposed https://github.com/webdriverio/webdriverio/pull/3120/files (which @christian-bromann reimplemented)

**Comment by mgrybyk** [comment] 2019-01-25 18:08
Do you know what commands requires w3c mode?

I see that one day setValue was working until it was changed here https://github.com/webdriverio/webdriverio/commit/e6bd400dcdcd327f044a654b9c521af7b7c36936  to make it work with webdriver

**Comment by nami-varthakavi** [comment] 2019-01-25 19:16
The setValue command expects a certain type of string I believe the change @mgrybyk mentioned in his previous command could be the reason why it is throwing an error. Earlier in V4, whatever the protocol be the value was parsed and transformed to an array of characters .

**Comment by mgrybyk** [comment] 2019-01-25 19:41
@jlipps chromedriver itself is non w3c compliant, so in case I'm using webview im my app which is controlled by chromedriver via appium, it is an expected behavior that commands should be  jsonwp.

How is it better to deal with that? Ideally I'd like to be able to switch protocol from w3c to jsonwp and back during test execution.

That would resolve this issue as well. Changes to isW3C or Protocol Commands are not required in such case.

**Comment by christian-bromann** [comment] 2019-01-25 20:15
> How is it better to deal with that?

I think this is handled by Appium proxying W3C calls into Chrome as JSONWP request

**Comment by mgrybyk** [comment] 2019-01-25 20:33
anyway it would be nice to workaround all these somehow.
Let's say be able to set isW3C manually or something...

**Comment by jlipps** [comment] 2019-01-25 20:56
@mgrybyk if you want, you can use appium's `forceMjsonwp` capability to make sure that the entire appium session uses jsonwp. that should force the initial new session response to be jsonwp, and should trigger wdio to use jsonwp mode as well?

**Comment by mgrybyk** [comment] 2019-01-25 21:12
I've just double checked, the only command that differs is 
`/session/:sessionId/element/:elementId/value`

**Comment by mgrybyk** [comment] 2019-01-25 21:13
well, actually also:
```
 /session
 /session/:sessionId/timeouts
 /session/:sessionId/window
```
but I'm not sure it is really a problem

**Comment by jlipps** [comment] 2019-01-25 21:17
@christian-bromann I looked for the Appium issue that describes this problem but couldn't. But yes, it is something Appium can/should fix. Since Appium is the proxy between the client and chromedriver, it's Appium's job to ensure the proxy is protocol-aware.

**Comment by mgrybyk** [comment] 2019-01-25 21:21
1. should I submit this issue?
2. don't you mind if we apply a temporary workaround for this in wdio?

**Comment by nami-varthakavi** [comment] 2019-01-25 21:21
> 1. should I submit this issue?
> 2. don't you mind if we apply a temporary workaround for this in wdio?

probably.

**Comment by mgrybyk** [comment] 2019-01-25 21:34
forceMjsonwp doesn't work for me.

**Comment by christian-bromann** [comment] 2019-01-25 21:43
> then it's just up to @christian-bromann I guess.

I would prefer to take the problem at its roots, make a PR to Appium with a fix and have the Appium team make a release.

**Comment by mgrybyk** [comment] 2019-01-25 21:44
ok then, I'll submit a ticket to Appium and create a temporary workaround as well

**Comment by jlipps** [comment] 2019-01-28 19:56
the fix has been implemented on the appium side, so the wdio workaround is only necessary if using older versions of appium (older than the current beta, i mean).

**Comment by mgrybyk** [comment] 2019-01-28 20:34
Yeah, just saw it.
I'll do some testing around.

**Comment by christian-bromann** [comment] 2019-01-29 16:20
Thanks @jlipps for the quick fix. Closing.

**Closed by christian-bromann** 2019-01-29 16:20 UTC
Labels: Logs Missing

**Comment by praveen8924** [comment] 2023-01-30 16:01
setValue, addValue doesn't work in native android page as well. Do you have any solution?

**Comment by christian-bromann** [comment] 2023-01-30 16:24
> setValue, addValue doesn't work in native android page as well.

It should, please provide logs.

**Comment by praveen8924** [comment] 2023-01-30 22:41
Here is situation on Native Android page  : I  have placeholder text in the search textbox ,where i need to input or send my queries in the text field but i'm getting "Error response status: 12, InvalidElementState - An element command could not be completed because the element is in an invalid state (e.g. attempting to click a disabled element). Selenium error: Cannot set the element to ‘’. Did you interact with the correct element?" I used doubleClick()/clearvalues()/addValues()/setvalue() . None of them work. pls help.

**Comment by jlipps** [comment] 2023-01-30 22:56
@praveen8924 can you please provide your full appium logs. at this point it doesn't seem that webdriverio is at issue, since the error you are getting is coming from appium, implying that webdriverio has sent the command successfully (which is its whole job here).

**Comment by breno174** [comment] 2024-06-10 15:02
@jlipps I have the same problem with appium on an android. I tried clearing the value and then adding a value. I also tried with 'addValue' and 'setValue'. This only happens when my element has a placeholder.
@praveen8924  Did you solve the problem?

Below is the appium log and webdriver log.
webdriver log
```
 2024-06-10T14:50:15.271Z INFO webdriver: COMMAND findElement("-android uiautomator", "new UiSelector().text("E-mail")")       
2024-06-10T14:50:15.274Z INFO webdriver: [POST] http://127.0.0.1:4723/session/346b712a-981f-49c7-935b-8e4dd56fb819/element    
2024-06-10T14:50:15.274Z INFO webdriver: DATA {
  using: '-android uiautomator',
  value: 'new UiSelector().text("E-mail")'
}
2024-06-10T14:50:15.467Z INFO webdriver: RESULT {
  'element-6066-11e4-a52e-4f735466cecf': '00000000-0000-0119-ffff-ffff0000006b',
  ELEMENT: '00000000-0000-0119-ffff-ffff0000006b'
}
2024-06-10T14:50:15.471Z INFO webdriver: COMMAND elementClear("00000000-0000-0119-ffff-ffff0000006b")
2024-06-10T14:50:15.472Z INFO webdriver: [POST] http://127.0.0.1:4723/session/346b712a-981f-49c7-935b-8e4dd56fb819/element/000
00000-0000-0119-ffff-ffff0000006b/clear
2024-06-10T14:50:15.577Z INFO webdriver: RESULT null
2024-06-10T14:50:15.578Z INFO webdriver: COMMAND elementClear("00000000-0000-0119-ffff-ffff0000006b")
2024-06-10T14:50:15.579Z INFO webdriver: [POST] http://127.0.0.1:4723/session/346b712a-981f-49c7-935b-8e4dd56fb819/element/000
00000-0000-0119-ffff-ffff0000006b/clear
2024-06-10T14:50:15.653Z INFO webdriver: RESULT null
2024-06-10T14:50:15.654Z INFO webdriver: COMMAND elementSendKeys("00000000-0000-0119-ffff-ffff0000006b", "jhondoe@email-intern
et.com.br")
2024-06-10T14:50:15.655Z INFO webdriver: [POST] http://127.0.0.1:4723/session/346b712a-981f-49c7-935b-8e4dd56fb819/element/000
00000-0000-0119-ffff-ffff0000006b/value
2024-06-10T14:50:15.656Z INFO webdriver: DATA { text: 'jhondoe@email-internet.com.br' }
2024-06-10T14:50:15.881Z WARN webdriver: Request failed with status 400 due to Cannot set the element to 'jhondoe@email-intern
et.com.br'. Did you interact with the correct element?
ERROR webdriver: Request failed with status 400 due to invalid element state: Cannot set the element 
to 'jhondoe@email-internet.com.br'. Did you interact with the correct element?
file:///C:/Users/breno/desenvolvimento/trabalho/device-smartphone/appium-test-scripts/js-scripts/node_modules/webdriver/build/
utils.js:195
    return new CustomRequestError(body, requestOptions);
    
invalid element state: Cannot set the element to 'jhondoe@email-internet.com.br'.
```

And appium log:
```
 Matched '/element/00000000-0000-0119-ffff-ffff0000006b/value' to command name 'setValue'
[AndroidUiautomator2Driver@ebc9 (346b712a)] Added 'value' property ["j","h","o","n","d","o","e","@","e","m","a","i","l","-","i","n","t","e","r","n","e","t",".","c","o","m",".","b","r"] to 'setValue' request body
[AndroidUiautomator2Driver@ebc9 (346b712a)] Proxying [POST /element/00000000-0000-0119-ffff-ffff0000006b/value] to [POST http://127.0.0.1:8200/session/df9d0cc1-c33c-4381-be26-9eebee1e2cb1/element/00000000-0000-0119-ffff-ffff0000006b/value] with body: {"elementId":"00000000-0000-0119-ffff-ffff0000006b","text":"jhondoe@email-internet.com.br","replace":false,"value":["j","h","o","n","d","o","e","@","e","m","a","i","l","-","i","n","t","e","r","n","e","t",".","c","o","m",".","b","r"]}
[AndroidUiautomator2Driver@ebc9 (346b712a)] Got response with status 400: {"sessionId":"df9d0cc1-c33c-4381-be26-9eebee1e2cb1","value":{"error":"invalid element state","message":"Cannot set the element to 'jhondoe@email-internet.com.br'. Did you interact with the correct element?","stacktrace":"io.appium.uiautomator2.common.exceptions.InvalidElementStateException: Cannot set the element to 'jhondoe@email-internet.com.br'. Did you interact with the correct element?\n\tat io.appium.uiautomator2.handler.SendKeysToElement.setText(SendKeysToElement.java:87)\n\tat io.appium.uiautomator2.handler.SendKeysToElement.safeHandle(SendKeysToElement.java:115)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:259)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:253)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:77)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractCh...
[W3C] Matched W3C error code 'invalid element state' to InvalidElementStateError
[AndroidUiautomator2Driver@ebc9 (346b712a)] Encountered internal error running command: io.appium.uiautomator2.common.exceptions.InvalidElementStateException: Cannot set the element to 'jhondoe@email-internet.com.br'. Did you interact with the correct element?
[AndroidUiautomator2Driver@ebc9 (346b712a)]     at io.appium.uiautomator2.handler.SendKeysToElement.setText(SendKeysToElement.java:87)
[AndroidUiautomator2Driver@ebc9 (346b712a)]     at io.appium.uiautomator2.handler.SendKeysToElement.safeHandle(SendKeysToElement.java:115)
[AndroidUiautomator2Driver@ebc9 (346b712a)]     at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)
[AndroidUiautomator2Driver@ebc9 (346b712a)]     at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:259)
```

**Comment by jlipps** [comment] 2024-06-10 15:08
This is coming from Appium, not wdio, so an issue should be opened there if you think it's a bug. But the error seems to be generated from the underlying uiauto2 framework so not sure there's much we can do about it.
