### ISSUE TITLE
Hooks are not waiting for promises with cucumber framework 2.2.8

### ISSUE THREAD

**Issue by Tallyb** [webdriverio/webdriverio#3068] opened 2018-11-22 14:39 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** 4.14.4
 - **Mode:** WDIO
 - **If WDIO Testrunner, running sync**
 - **Node.js version: 10.13.0
 - **NPM version:** 6.4.1
 - **Browser name and version:** chrome 
 - **Platform name and version:** MacOS latest
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]
wdio-cucumber-framework

Bug repo: https://github.com/Tallyb/wdio-test/tree/async-hooks (branch is async hooks)

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
BeforeFeature hook is not waiting for promise resolve. 

**To Reproduce**
https://github.com/Tallyb/wdio-test/tree/async-hooks 
`npm install`
`npm run test`
install wdio-cucumber-framework in version 1.1.1 to see the desired behaviour. Change to 2.2.8 to see the bug (logging message is showing before the async date logs)

**Expected behavior**
Feature should only run after beforeHook promise was resolved. 

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment] 2018-11-22 14:43
@Tallyb in the meantime this should be a workaround:

```js
    beforeFeature: function (feature) {
        browser.windowHandleSize( {width: 375, height: 800});
        console.log('IN BEFORE FEATURE');
        browser.call(() => utils.runDelays());
    },
```

**Comment by Tallyb** [comment] 2018-11-22 14:48
@christian-bromann I just checked it (also on my real repo previously) and it does not fix.

**Comment by rodrigodiez** [comment] 2018-11-29 14:39
Is this confirmed then? I have some failing tests that could be caused by that behaviour

**Comment by jonatr35** [comment] 2018-12-04 04:33
Seem the same behavior when attempting to make an axios http POST in `beforeScenario` hook. The status code in the `then` block gets logged after `beforeStep` logs have been written.

Using `"wdio-cucumber-framework": "2.2.8"` as well.

**Comment by BorisOsipov** [comment] 2018-12-04 08:19
yes it is 2.x version issue. And this should be moved to cucumber adapter repo @christian-bromann 

For @Tallyb @jonatr35 @rodrigodiez 

You can achive expected behaviour by using "native" cucumber hooks e.g.: 

```
var { Given, Before } = require('cucumber');
const utils = require('./utils');

Before(() => {
    browser.windowHandleSize({ width: 375, height: 800 });
    return utils.runDelays();
});

Given(/^Log Something$/, function () {
    console.log('Logging something')
});
```

In this case `Before` hook will be executed before scenario steps.
Log output:
```
IN BEFORE FEATURE
2018-12-04T08:18:50.702Z 1
2018-12-04T08:18:52.709Z 2
2018-12-04T08:18:55.710Z 3
2018-12-04T08:18:59.711Z 4
Logging something

1 passing (16.10s)
```



For more information see [cucumber hooks documentaion](https://github.com/cucumber/cucumber-js/blob/3.x/docs/support_files/hooks.md)

**Comment by rodrigodiez** [comment] 2018-12-15 16:55
Thanks @BorisOsipov that is really useful

**Comment by christian-bromann** [comment] 2019-02-06 22:08
Closing this. It will be a requirement for the cucumber v5 effort.

**Closed by christian-bromann** 2019-02-06 22:08 UTC
Labels: Bug🐛

**Comment by miguelyoobic95** [comment] 2019-07-31 16:27
Hey guys, we have upgraded to v5 and we are observing this issue. Any workarounds for this ? Our first Given is consistently running before our async afterFeature hook has finished and it breaks our tests essentially ...

**Comment by mgrybyk** [comment] 2019-07-31 16:34
@miguelyoobic95  https://github.com/webdriverio/webdriverio/issues/4207

**Comment by miguelyoobic95** [comment] 2019-07-31 16:37
Having a look now, thanks @mgrybyk. Sticking a timeout makes thing work but is far from being a good solution
