### ISSUE TITLE
setValue is not working for MicrosoftEdge and firefox in webdriverio 5

### ISSUE THREAD

**Issue by ssenthurkani** [webdriverio/webdriverio#4793] opened 2019-11-21 11:19 UTC
setValue is not working in webdriverIO for MicrosoftEdge and firefox in webdriverio 5,
Error: java.lang.NullPointerException - firefox
edge - Error: JSON format error: parameters object must contain pair with name “keysToSend”
Tried with different combination of mac and window platform and firefox and edge version, still not working

**Comment by mgrybyk** [comment] 2019-11-21 16:11
Please provide with reproducible example

**Comment by ssenthurkani** [comment] 2019-11-22 17:03
Please find the replication code below
WebdriverIO version: 5.16.8
Node.js version:8.11.1
NPM version:6.10.0
Browser name : Firefox (70)
Platform name : 'Windows 10' 
Edge 
 browserName: 'MicrosoftEdge',
version: '17.17134',
 platform: 'Windows 10',

**Method -1** 

it('test for setValue', () => {
		try {
			browser.url('https://webdriver.io/docs/api/webdriver.html')
			const search_text = $('.nav-site.nav-site-internal #search_input_react')
			search_text.setValue("setValue")
		} catch (err) {
			throw new Error(err)
		}
	})

**ERROR** 
Firefox - Error: java.lang.NullPointerException
Edge - Error: JSON format error: parameters object must contain pair with name "keysToSend"

**Method -2** 
it('test for setValue', () => {
		try {
			browser.url('https://webdriver.io/docs/api/webdriver.html')
			const search_text = $('.nav-site.nav-site-internal #search_input_react')
			search_text.click()
			browser.keys("text")
		} catch (err) {
			throw new Error(err)
		}
	})
**ERROR** 
Firefox - 
Error: Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'WIN-SB3ER6JQ6ME', ip: '10.119.38.109', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_91'
Driver info: driver.version: unknown
Edge - Error: Unknown command

**Comment by mgrybyk** [comment] 2019-11-22 17:33
Method 1 is some issue on your side, java null pointers have nothing to do with webdriverio...

**Comment by ssenthurkani** [comment] 2019-11-22 17:40
Can you give me the some sample code to setValue for firefox and edge browser

**Comment by mgrybyk** [comment] 2019-11-22 18:29
Your code looks good, the issue is with your environment setup, grid or something like that. 
Try starting project from scratch and use default services, ex selenium standalone service.
Then apply your config to identify what is going on wrong

**Comment by mgrybyk** [comment] 2019-11-23 14:46
Closing the issue for now.
If you need help with running tests in firefox consider using getting started tutorial, choose selenium-service and go ahead.

If you still have some questions I'm happy to help

**Closed by mgrybyk** 2019-11-23 14:46 UTC
Labels: Reproducible Example Missing
