### ISSUE TITLE
XUnit failing to create syntactically valid XML

### ISSUE THREAD

**Issue by arcampbell** [webdriverio/webdriverio#1053] opened 2016-01-25 15:37 UTC
I am experiencing a weird issue when using the XUnit reporter.  Intermittently it will fail to generate accurate XML, with `</system-out>` being the last tag, not `</testsuites>` as expected.  The report itself is 150K + lines long, and I have not been able to create a minimal example that expresses this issue.

Jenkins stacktrace reports an error on line n+1, where n is the number of lines in the report.  Here is the last 10 lines of the report:

```
GET http://localhost:4444/wd/hub/session/32bc0c2a-b341-4945-8df3-a074d65bbe75/element/15448/displayed - {"status":0,"sessionId":"32bc0c2a-b341-4945-8df3-a074d65bbe75","state":"success","value":true,"class":"org.openqa.selenium.remote.Response","hCode":153155609}
POST http://localhost:4444/wd/hub/session/32bc0c2a-b341-4945-8df3-a074d65bbe75/elements - {"status":0,"sessionId":"32bc0c2a-b341-4945-8df3-a074d65bbe75","state":"success","value":[{"ELEMENT":"15448"}],"class":"org.openqa.selenium.remote.Response","hCode":610790586}
GET http://localhost:4444/wd/hub/session/32bc0c2a-b341-4945-8df3-a074d65bbe75/element/15448/enabled - {"status":0,"sessionId":"32bc0c2a-b341-4945-8df3-a074d65bbe75","state":"success","value":true,"class":"org.openqa.selenium.remote.Response","hCode":1505618740}
POST http://localhost:4444/wd/hub/session/32bc0c2a-b341-4945-8df3-a074d65bbe75/element - {"status":0,"sessionId":"32bc0c2a-b341-4945-8df3-a074d65bbe75","state":"success","value":{"ELEMENT":"15448"},"class":"org.openqa.selenium.remote.Response","hCode":1817846834}
POST http://localhost:4444/wd/hub/session/32bc0c2a-b341-4945-8df3-a074d65bbe75/moveto - {"status":0,"sessionId":"32bc0c2a-b341-4945-8df3-a074d65bbe75","state":"success","value":null,"class":"org.openqa.selenium.remote.Response","hCode":1562117169}
POST http://localhost:4444/wd/hub/session/32bc0c2a-b341-4945-8df3-a074d65bbe75/click - {"status":0,"sessionId":"32bc0c2a-b341-4945-8df3-a074d65bbe75","state":"success","value":null,"class":"org.openqa.selenium.remote.Response","hCode":495477342}
POST http://localhost:4444/wd/hub/session/32bc0c2a-b341-4945-8df3-a074d65bbe75/elements - {"status":0,"sessionId":"32bc0c2a-b341-4945-8df3-a074d65bbe75","state":"success","value":[{"ELEMENT":"15449"}],"class":"org.openqa.selenium.remote.Response","hCode":1378115687}
GET http://localhost:4444/wd/hub/session/32bc0c2a-b341-4945-8df3-a074d65bbe75/element/15449/displayed - {"status":0,"sessionId":"32bc0c2a-b341-4945-8df3-a074d65bbe75","state":"success","value":true,"class":"org.openqa.selenium.remote.Response","hCode":587079080}
POST http://localhost:4444/wd/hub/session/32bc0c2a-b341-4945-8df3-a074d65bbe75/elements - {"status":0,"sessionId":"32bc0c2a-b341-4945-8df3-a074d65bbe75","state":"success","value":[],"class":"org.openqa.selenium.remote.Response","hCode":1392267219}
]]></system-out>
```
Here is the stack trace from Jenkins when it is trying to read the file:
```
Failed to read test report file /path/to/log/WDIO.xunit.chrome.16635.xml
org.dom4j.DocumentException: Error on line 159077 of document file:///path/to/log/WDIO.xunit.chrome.16635.xml : XML document structures must start and end within the same entity. Nested exception: XML document structures must start and end within the same entity.
	at org.dom4j.io.SAXReader.read(SAXReader.java:482)
	at org.dom4j.io.SAXReader.read(SAXReader.java:264)
	at hudson.tasks.junit.SuiteResult.parse(SuiteResult.java:123)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:286)
	at hudson.tasks.junit.TestResult.parsePossiblyEmpty(TestResult.java:232)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:167)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:150)
	at hudson.tasks.junit.TestResult.<init>(TestResult.java:126)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:132)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:107)
	at hudson.FilePath.act(FilePath.java:991)
	at hudson.FilePath.act(FilePath.java:969)
	at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:103)
	at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:126)
	at hudson.tasks.junit.JUnitResultArchiver.perform(JUnitResultArchiver.java:144)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:785)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
Caused by: org.xml.sax.SAXParseException; systemId: file:///path/to/log/WDIO.xunit.chrome.16635.xml; lineNumber: 159077; columnNumber: 1; XML document structures must start and end within the same entity.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1437)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.endEntity(XMLDocumentFragmentScannerImpl.java:903)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.endEntity(XMLDocumentScannerImpl.java:563)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.endEntity(XMLEntityManager.java:1391)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1756)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipChar(XMLEntityScanner.java:1405)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2823)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.dom4j.io.SAXReader.read(SAXReader.java:465)
	... 24 more
Nested exception: 
org.xml.sax.SAXParseException; systemId: file:///path/to/log/WDIO.xunit.chrome.16635.xml; lineNumber: 159077; columnNumber: 1; XML document structures must start and end within the same entity.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1437)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.endEntity(XMLDocumentFragmentScannerImpl.java:903)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.endEntity(XMLDocumentScannerImpl.java:563)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.endEntity(XMLEntityManager.java:1391)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1756)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipChar(XMLEntityScanner.java:1405)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2823)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.dom4j.io.SAXReader.read(SAXReader.java:465)
	at org.dom4j.io.SAXReader.read(SAXReader.java:264)
	at hudson.tasks.junit.SuiteResult.parse(SuiteResult.java:123)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:286)
	at hudson.tasks.junit.TestResult.parsePossiblyEmpty(TestResult.java:232)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:167)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:150)
	at hudson.tasks.junit.TestResult.<init>(TestResult.java:126)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:132)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:107)
	at hudson.FilePath.act(FilePath.java:991)
	at hudson.FilePath.act(FilePath.java:969)
	at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:103)
	at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:126)
	at hudson.tasks.junit.JUnitResultArchiver.perform(JUnitResultArchiver.java:144)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:785)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
```

Any thoughts on what could be going on here?  Does it have to do with how the tests are defined or is this a bug in WDIO?

**Comment by christian-bromann** [comment] 2016-01-25 16:40
> or is this a bug in WDIO?

It's probably a bug within our xunit reporter. Can you check if the file is valid xml? We probably need to find a way to scatter the xml output into multiple xml files as they can get too long.

**Comment by arcampbell** [comment] 2016-01-25 19:04
Is is not valid XML.  At the very least, it is missing closing tags for `<testcase>`, `<testsuite>`, and `<testsuites>`.  Here is the xmllint output of one of the files in question:

```
WDIO.xunit.chrome.16635.xml:159077: parser error : Premature end of data in tag testcase line 158907
WDIO.xunit.chrome.16635.xml:159077: parser error : Premature end of data in tag testsuite line 158906
WDIO.xunit.chrome.16635.xml:159077: parser error : Premature end of data in tag testsuites line 1
```

**Comment by christian-bromann** [comment] 2016-01-25 22:08
I assume that the file got to big and node just cropped the file.

**Comment by arcampbell** [comment] 2016-01-25 22:45
I just checked the files I have that express the problem.  I have files that are 47Mb and 169521 lines long that are properly formatted and ones that are 39Mb and 144425 lines long that express the issue, so it doesn't seem to be stopping at some fixed size or line count.

I am happy to help by checking out a branch and test it as this progresses.  Thanks for your help.

**Comment by melwynfurtado** [comment] 2016-03-20 10:18
We had a similar issue with XUnit output and hence Jenkins failed for us. We divided tests in multiple groups so that output is scattered across files.
@austek-mdsol

**Comment by christian-bromann** [comment] 2016-03-25 14:12
I think this is a duplicate of https://github.com/webdriverio/wdio-junit-reporter/issues/1. Let's continue the conversation in this thread

**Closed by christian-bromann** 2016-03-25 14:12 UTC
Labels: Bug
