### ISSUE TITLE
browser.scroll suddenly stopped working

### ISSUE THREAD

**Issue by JulsRicketti** [webdriverio/webdriverio#2632] opened 2018-03-07 14:27 UTC
## The problem

All tests I attempt to run which happen to have a `browser.scroll([ELEMENT])` have stopped working an give the following error:

```
unknown error: call function result missing 'value'
Error: An unknown server-side error occurred while processing the command.
[chrome #0-0]     at execute(<Function>, 482.25, 582.578125) - scroll.js:104:26
```

## Environment

* WebdriverIO version:  4.11.0
* Node.js version: 8.9.4
* wdio-selenium-standalone-service: 0.0.9
* wdio-mocha-framework: 0.5.12
* wdio-spec-reporter: 0.1.4

Not sure if important but...
* ChromeDriver: 2.35.528157
* Chrome: 64.0.3282.186

## Details

Everything was working fine up until yesterday, when I came in today all my tests in all of my projects are giving the same problem. It all links back to the `browser.scroll()` function

## Code To Reproduce Issue [ Good To Have ]

Anything with the `browser.scroll()` function

```
it('test scroll', function() {
  browser.scroll('.someClass')
  assert.ok(true)
})
```

**Comment by christian-bromann** [comment] 2018-03-07 14:37
Duplicate of #2631 , please see https://github.com/webdriverio/webdriverio/issues/2631#issuecomment-371072596

**Closed by christian-bromann** 2018-03-07 14:37 UTC
