### ISSUE TITLE
WaitForVisible command return null error with page objects

### ISSUE THREAD

**Issue by StephenDavidson** [webdriverio/webdriverio#1596] opened 2016-09-16 13:43 UTC
## The problem
With pageobject:
`favoritesPage.favoriteBtn.waitForVisible();`
Returns error:
`Error: element (null) still not visible after 5000ms`

Without pageobject:
`browser.waitForVisible('div[data-reactid*="fav"');`
Returns error:
`Error: element (div[data-reactid*="fav"]) still not visible after 5000ms`

## Environment

* WebdriverIO version: 4.2.15
* Node.js version: 4.5.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Standalone
* if wdio testrunner, running synchronous or asynchronous tests: Sync
* Additional wdio packages used (if applicable): N/a

## Details

It seems that the element information is not passed to the waitForVisible command error message when using pageobjects.

**Comment by christian-bromann** [comment] 2016-09-16 13:45
duplicate of #1481

**Comment by christian-bromann** [comment] 2016-09-16 13:45
@StephenDavidson this is a known issue

**Closed by christian-bromann** 2016-09-16 13:45 UTC

**Comment by christian-bromann** [comment] 2016-09-16 14:11
@StephenDavidson actually it is kinda different however fixed the issue and will publish a new version asap

**Comment by christian-bromann** [comment] 2016-09-16 14:45
released as `v4.2.16`

**Comment by tripleratamacue** [comment] 2016-12-07 21:39
@christian-bromann Hey Cris, not if publishing in the right thread. But, I had this kind of errors, when using waitFor's and PageObjects, I solved it like this:
This is what Documentation recommend:
class LoginPage extends Page {
    	get username()  { return browser.element('#username'); }

This works 
LoginPage.username.setValue('Max Mustermann');

This doesn’t:
LoginPage.username.waitForVisible(5000);
	
So had to changed to this model:
class LoginPage extends Page {
usernameCSS:          { get: function () { return '#email'; } },
username:    { get: function () { return browser.element(this.usernameCSS); } },

And invoke like this to make it work, and avoid have Selector duplicated, I mean have the selector path only in the PageObject.
This is common and works:
LoginPage.usernameBox.setValue(user);
But when using waitFor I do it this way:
browser.waitForVisible(LoginPage.usernameCSS, 5000);

What do you think about this approach, too messy? is there a fix on it way? I am not block thanks to this model, but would love to have your blessing on this :)

**Comment by christian-bromann** [comment] 2016-12-07 21:46
`LoginPage.username.waitForVisible(5000);` should work, what is the error?

**Comment by tripleratamacue** [comment] 2016-12-07 22:22
examples:
Users.emailAlreadyInUseMessageXpath.waitForVisible is not a function
Menu.userDisplayCSS.waitForVisible is not a function

**Comment by christian-bromann** [comment] 2016-12-07 22:31
if you define your element in your PO like
```js
get username() { return $('#username'); }
```

you can call the API commands like
```js
PO.username.waitForVisible()
```

**Comment by tripleratamacue** [comment] 2016-12-08 18:19
It do work, thanks man, time to start a refactor haha, is there a doc, where I can learn more about $

**Comment by christian-bromann** [comment] 2016-12-08 18:33
http://webdriver.io/api/utility/$.html
http://webdriver.io/api/utility/$$.html

**Comment by tripleratamacue** [comment] 2016-12-08 18:54
thanks, I only had to keep my format, the one you provided didn't worked,  I get this error:
Cannot read property 'waitForVisible' of undefined

get usernameBox()    { return $('#email'); } //doesn't work
usernameBox:          { get: function () { return $('#email'); } } //works

calling like 
Login.usernameBox.waitForVisible(browser.globalDelay); 
or
this.usernameBox.waitForVisible(browser.globalDelay);
Any clue? I prefer your format, without function word, cleaner.

**Comment by christian-bromann** [comment] 2016-12-08 19:16
> I prefer your format, without function word, cleaner.

just compile it to ES2016 ;-)

**Comment by tripleratamacue** [comment] 2016-12-08 23:41
1. npm install --save-dev babel-cli babel-preset-es2016
2.  added this to wdio.conf
 before: function() {
            require('babel-register');
            browser.url(browser.options.baseUrl);
    },
3. added a .babelrc with {
  "presets": ["es2016"]
}
4. ./node_modules/.bin/babel tests/ --out-file script-compiled.js

same behaviour, what I am missing?

**Comment by christian-bromann** [comment] 2016-12-09 00:31
Please see http://webdriver.io/guide/getstarted/configuration.html. For further questions please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
