### ISSUE TITLE
getText() not returning all expected data

### ISSUE THREAD

**Issue by AnnemarieD** [webdriverio/webdriverio#2468] opened 2017-11-23 09:23 UTC
## The problem
When running a test, I get unexpected results on getText(). In this particular example I expect 6 results, but somehow my test is reported as failed after only 2 results have come back. Test example below, as well as logs. 
Test results in error:
```
[chrome #0-0] java.net.SocketException: Connection reset by peer
[chrome #0-0] Error: An unknown server-side error occurred while processing the command.
[chrome #0-0]     at elementIdText("0.5538452207450344-20") - getText.js:35:50
```
This does not happen consistently with the same test, nor does it happen all the time, or even for all getText calls in the test (see example).

Also see: https://github.com/SeleniumHQ/selenium/issues/5096 

## Environment

* WebdriverIO version: 4.9.9 (but happened on 4.4.0 also)
* Node.js version:
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio Testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync: true
* Additional wdio packages used (if applicable):

## Details
Please note that the provided test example shows 3 different functions that performs the same action, of which 2 do not cause any problem in this case. Which of the functions fails can not be guessed beforehand as far as we have observed so far. The function using getText() can also fail in a test with only function that uses getText().

## Link to Selenium/WebdriverIO logs
https://gist.github.com/AnnemarieD/b138b3cff0f569683a0467c8970b262e

## Code To Reproduce Issue [ Good To Have ]
https://gist.github.com/AnnemarieD/b138b3cff0f569683a0467c8970b262e
other example can be found here: https://gitter.im/webdriverio/webdriverio/archives/2017/11/21

**Comment by christian-bromann** [comment] 2017-11-23 09:40
duplicate of #2406

**Closed by christian-bromann** 2017-11-23 09:40 UTC
