### ISSUE TITLE
Pretty upset with lack of documentation and general confusion with all the extra addons

### ISSUE THREAD

**Issue by Miladinho** [webdriverio/webdriverio#2525] opened 2017-12-29 00:31 UTC
## The problem
First of all, thank you for building this project. It is very helpful. The documentation on your website though is not as helpful especially since the aim of the project is to simplify testing. The docs should START from the beginning to describe that there are [2 distinct ways/modes to run tests with webdriverio](http://webdriver.io/guide/getstarted/modes.html), testrunner vs standalone. The distinction between the two is pretty well written. My problem though, is that I have no idea how to solve problems with drivers as they arise when running the testrunner in docker or other virtualized, non-GUI env. My ultimate goal is to use the testrunner to automate my tests across several different browsers, but I can't even get the configuration working. 

## Environment

* WebdriverIO version: 1.0.3
* Node.js version: 8.9.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): testrunner mode
* if wdio testrunner, running synchronous or asynchronous tests: synchronous/ N/A
* Additional wdio packages used (if applicable):
    "wdio-chromedriver-service": "0.1.1",
    "wdio-selenium-standalone-service": "~0.1",
    "wdio-cucumber-framework": "1.0.2"

### Cry for help
Its pretty simple, run a set of cucumber tests on different browsers, all in the same run. When running test in a ci environment like circleci, make sure everything is running in a docker container (that circle will use). No fancy stuff. 

I need a guide as to how to install and configure drivers so that I can do this, please help.
### Specifics
Sorry for being vague, but I have tried to remedy this problem in several ways over several days so I don't have exact details for each try, I can best hope to explain some of the approaches and rely on your understanding and experience. 

My reasoning is that if I have chrome or opera installed on my docker instance, say a Debian linux, then the testrunner should be able to just run and execute. With Chrome I found that because there is no gui it needs a graphics driver (xvfb or something) to be running, this came from several blogs and forumns and no mention of it is made on your site/guides. That approach didn't work for me. Running chrome using the chromedriver service and defining it as a service in the configuration file at best would give me a weird error about chroem not starting properly.

`ERROR: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.9.49-moby x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.09 seconds
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:36.161Z'
System info: host: '7db6cffd0f89', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.49-moby', java.version: '1.8.0_151'
Driver info: driver.version: unknown
`

## Link to Selenium/WebdriverIO logs

Have no idea where these reside

## Code To Reproduce Issue [ Good To Have ]

package.json
`{
  "scripts": {
    "test": "wdio"
  },
  "devDependencies": {
    "chai": "4.1.2",
    "cucumber": "3.1.0",
    "eslint": "4.12.1",
    "eslint-config-originate": "2.0.3",
    "eslint-config-prettier": "2.9.0",
    "eslint-plugin-filenames": "1.2.0",
    "eslint-plugin-import": "2.8.0",
    "eslint-plugin-prettier": "2.3.1",
    "prettier": "1.8.2",
    "wdio": "1.0.3",
    "wdio-chromedriver-service": "0.1.1",
    "wdio-selenium-standalone-service": "~0.1",
    "wdio-cucumber-framework": "1.0.2"
  }
}
`

wdio.conf.js

`exports.config = {
  specs: ['./features/**/*.feature'],
  exclude: [
  ],
  maxInstances: 10,
  capabilities: [
    {
      maxInstances: 5,
      browserName: 'safari',
    }, {browserName: 'chrome'},/*{browserName: 'opera'}, {browserName: firefox}*/
  ],
  logLevel: 'error',
  coloredLogs: true,
  deprecationWarnings: true,
  bail: 0,
  screenshotPath: './errorShots/',
  baseUrl: 'http://localhost',
  waitforTimeout: 10000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
services: ['selenium-standalone', 'chromedriver'],
  cucumberOpts: {
    require: ['./features/step_definitions'], 
    compiler: [], 
    dryRun: false, 
    failFast: false, 
    format: ['pretty'], 
    colors: true, 
    snippets: true, 
    source: true, 
    profile: [], 
    strict: false, 
    tags: [], 
    timeout: 20000,
    ignoreUndefinedDefinitions: false, 
  }
}
`
I would add actual test code but it is irrelevant as I cannot even get the environment working to get to the test execution.

### Links to solution paths tried
https://stackoverflow.com/questions/22558077/unknown-error-chrome-failed-to-start-exited-abnormally-driver-info-chromedri

https://bugs.chromium.org/p/chromedriver/issues/detail?id=1972

**Comment by christian-bromann** [comment] 2017-12-29 10:47
Sorry for all the confusion you've experienced. The problem is that there are a million ways to run automated tests in a browser or on a mobile device. WebdriverIO can't documented every use case as it would blow up the documentation page.

I am not sure about the chromedriver issue. It must be related to the environment you are running the browser in.

> I need a guide as to how to install and configure drivers so that I can do this, please help.

This project has a [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) support channel where you can find help.

I am closing this as I don't see an actual issue with WebdriverIO itself. Yes, there is a lack of documentation for your use case (running browser headless in a Docker container) but as I mentioned we can't provide step by step tutorials for all scenarios. Feel free to share your solution in a blog post or create a boilerplate project like [these ones](http://webdriver.io/guide/getstarted/boilerplate.html). And again, you will always find help in the support channel.

**Closed by christian-bromann** 2017-12-29 10:47 UTC

**Comment by Miladinho** [comment] 2017-12-30 00:51
@christian-bromann 

I think webdriverio is at fault actually there is no good documentation on how to run opera and firefox tests for example, even in a simple local environment, knowing details like that actually helps debugging for other browsers as it would shed light on how wdio works in general. As a user I have no idea what is going other than following tutorials and that is no good way to setup a project for a given use-case and thus be able to discern where issues could be coming from.

**Comment by sumeetp4** [comment] 2018-02-02 04:15
Agree with @Miladinho here, no proper documentation. All the examples are directly given or usually in form of browser. What if a user is testing an android application. Appreciate the work you have done, but everything feels so disorganized. As a user, I'm finding it so confusing and difficult to use webdriverio. Also the gitter is of no help
