### ISSUE TITLE
wdio --watch mode changes its behavior of keeping lastResult

### ISSUE THREAD

**Issue by okitan** [webdriverio/webdriverio#2646] opened 2018-03-14 06:20 UTC
## The problem

`wdio --watch` mode changes its behavior of keeping `lastResult` between 1st run and reruns.

## Environment

* WebdriverIO version: 4.12.0
* Node.js version: v9.7.1
* wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: syn
* Additional wdio packages used (if applicable): wdio-chromedriver-service

## Details

At the 1st time Run:
> [15:00:55]  COMMAND     POST     "/session/b0083dcf4ed26c3e9de5873e9b7d2393/element"
[15:00:55]  DATA                {"using":"link text","value":"API"}
[15:00:55]  RESULT              {"ELEMENT":"0.3557136621358876-1"}
[15:00:55]  COMMAND     POST     "/session/b0083dcf4ed26c3e9de5873e9b7d2393/element/0.3557136621358876-1/click"
[15:00:55]  DATA                {}
[15:00:56]  COMMAND     POST     "/session/b0083dcf4ed26c3e9de5873e9b7d2393/elements"

2nd time and more:
> [15:01:04]  COMMAND     POST     "/session/b0083dcf4ed26c3e9de5873e9b7d2393/element"
[15:01:04]  DATA                {"using":"link text","value":"API"}
[15:01:04]  RESULT              {"ELEMENT":"0.9257526474386759-1"}
[15:01:04]  COMMAND     POST     "/session/b0083dcf4ed26c3e9de5873e9b7d2393/element/0.9257526474386759-1/click"
[15:01:04]  DATA                {}
[15:01:04]  COMMAND     POST     "/session/b0083dcf4ed26c3e9de5873e9b7d2393/element/0.9257526474386759-1/elements"

In the reruns log, the last command tried to find elements under the clicked element.
Of course, it was a stale element and should fail.

Why reruns keep `lastResult` longer than 1st run?

#2596 might be the same issue.

## Link to Selenium/WebdriverIO logs

https://gist.github.com/okitan/da8cb9f2ddd491c49a210c4edc418a6f

## Code To Reproduce Issue [ Good To Have ]

https://gist.github.com/okitan/da8cb9f2ddd491c49a210c4edc418a6f#file-test-js

**Comment by christian-bromann** [comment] 2018-03-14 09:29
Yes, this is a duplicate of #2596

**Closed by christian-bromann** 2018-03-14 09:29 UTC

**Comment by okitan** [comment] 2018-03-14 13:39
Although, it is a duplicate of existing issue, when this error will be fixed?
I'm worried that there are no response to the existing issue.

**Comment by christian-bromann** [comment] 2018-03-14 14:19
> when this error will be fixed?

It will be fixed if someone takes the time to fix it, you are welcome to do so 😉
