### ISSUE TITLE
element.getElementRect omits `y` coordinate

### ISSUE THREAD

**Issue by flunderpero** [webdriverio/webdriverio#3608] opened 2019-02-23 16:00 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 5.6.2]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [e.g. 10.13.0]
 - **NPM version:** [e.g. 6.4.1]
 - **Browser name and version:** [Safari 12.0.3]
 - **Platform name and version:** [OSX Mojave]
 
**Config of WebdriverIO**
``` 
{
    capabilities: [{browserName: "safari"}],
    port: 4447,
    seleniumArgs: {seleniumArgs: ["-port", "4447"]},
    services: [ "selenium-standalone"],
}

// Problem exists in BrowserStack Safari, too!
```
**Describe the bug**
Calling `getElementRect` never returns the `y`-value. Note: I do not call `getElementRect` myself
but rather ran into the bug while trying to use `element.moveTo()` which in turn calls `getElementRect` on Safari.

**To Reproduce**
```
    // This will not work because the moveTo-command tries to use a null value for y
    $("any element").moveTo()
``` 

**Expected behavior**
It should work. :-)

**Comment by christian-bromann** [comment] 2019-02-23 16:02
@flunderpero can you provide logs please?

**Comment by flunderpero** [comment] 2019-02-23 16:38
Sorry, I forgot. This is what happens when I try to call `element.moveTo()`:

```
2019-02-23T16:36:18.837Z INFO webdriver: COMMAND getElementRect("node-F85D9EB9-CBD9-4D7E-82D8-A29F2849EEE3")
2019-02-23T16:36:18.837Z INFO webdriver: [GET] http://127.0.0.1:4447/wd/hub/session/0DCB497F-76E4-4E29-93E5-4035A6E5669E/element/node-F85D9EB9-CBD9-4D7E-82D8-A29F2849EEE3/rect
2019-02-23T16:36:18.887Z INFO webdriver: RESULT { x: 102, width: 578, height: 11 }
2019-02-23T16:36:18.888Z INFO webdriver: COMMAND performActions(<object>)
2019-02-23T16:36:18.889Z INFO webdriver: [POST] http://127.0.0.1:4447/wd/hub/session/0DCB497F-76E4-4E29-93E5-4035A6E5669E/actions
2019-02-23T16:36:18.889Z INFO webdriver: DATA { actions:
   [ { type: 'pointer',
       id: 'finger1',
       parameters: [Object],
       actions: [Array] } ] }
2019-02-23T16:36:18.923Z WARN webdriver: Request failed due to Encountered pointerMove action with invalid 'y' coordinate in payload: {
    actions =     (
                {
            duration = 0;
            type = pointerMove;
            x = 391;
            y = "<null>";
        }
    );
    id = finger1;
    parameters =     {
        pointerType = mouse;
    };
    type = pointer;
}
```

I can verify that `element.getElementRect(element.elementId)` will only return `x, width, height` but not `y`.

**Comment by christian-bromann** [comment] 2019-02-23 17:01
@flunderpero can you provide the driver logs please?

**Comment by flunderpero** [comment] 2019-02-23 18:16
The `selenium-standalone-logs`:
```
19:15:28.479 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "safari"
}
19:15:28.480 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.safari.SafariDriverService)
19:15:29.330 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
19:15:29.349 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 0DC54E5A-4E10-4692-B049-764AAF344515 (org.openqa.selenium.safari.SafariDriverService)
```

**Comment by christian-bromann** [comment] 2019-02-23 18:20
Those are not the driver logs .. wdio provides these wherever you've defined the [`outputDir`](https://webdriver.io/docs/options.html#outputdir)

**Comment by flunderpero** [comment] 2019-02-23 18:54
I get a `wdio.log` and a `wdio-0-0.log`. The latter one is what you see [above](https://github.com/webdriverio/webdriverio/issues/3608#issuecomment-466667379). The other one:
```
2019-02-23T18:52:43.253Z DEBUG wdio-config: @wdio/sync found, running tests synchronous
2019-02-23T18:52:43.746Z DEBUG wdio-cli:run: Run suite with config wdio.local_safari.conf.js and params { _: [ 'wdio.local_safari.conf.js' ],
  baseUrl: 'https://dev-pero.cling.com',
  spec: [ 'smoke_inte' ],
  '$0': '../../../../../../node_modules/.bin/wdio' }
2019-02-23T18:52:43.818Z DEBUG wdio-utils:initialiseServices: initialise wdio service "selenium-standalone"
2019-02-23T18:52:43.872Z INFO wdio-cli:Launcher: Run onPrepare hook
2019-02-23T18:52:49.759Z INFO wdio-local-runner: Start worker 0-0 with arg: --baseUrl,https://dev-pero.cling.com,wdio.local_safari.conf.js,--spec,smoke_inte
2019-02-23T18:52:59.155Z DEBUG wdio-local-runner: Runner 0-0 finished with exit code 1
```

**Comment by mgrybyk** [comment] 2019-02-23 22:26
the issue is that getElementRect is not returning y:
`{x: 216, width: 76, height: 19}`

**Comment by mgrybyk** [comment] 2019-02-23 22:28
https://github.com/SeleniumHQ/selenium/issues/6637

**Comment by mgrybyk** [comment] 2019-02-23 22:37
first of all we have to do some minor fix in order to handle it.

Then, you'll be able to workaround you issue like this
```
    const header = $('h1')

    const location = browser.execute(function (el) {
      const rect = el.getBoundingClientRect();
      return {
        x: rect.left + window.scrollX,
        y: rect.top + window.scrollY
      };
    }, header)

    header.moveTo(location.x, location.y)
```

doing PR for this

**Comment by flunderpero** [comment] 2019-02-23 22:47
That's the kind of workaround I'm using. Thanks for the quick reply!

**Comment by mgrybyk** [comment] 2019-02-23 22:59
this workaround should not work as well at the moment

**Comment by flunderpero** [comment] 2019-02-23 23:19
Sorry for causing confusion, I just meant that I use browser.execute(...) as a workaround. My current use case is to open a menu by hovering above it. The workaround is to use dispatchEvent() directly on the DOM-element.
But since I am moving more tests to wdio it is just a matter of time until I run out of workarounds. :-)

**Comment by mgrybyk** [comment] 2019-02-23 23:34
@flunderpero may this PR https://github.com/webdriverio/webdriverio/pull/3610 be helpful for you?

**Comment by mgrybyk** [comment] 2019-02-23 23:37
We can even do something like this, if one of x,y,height,width is undefined get location with javascript.

So that there will be no need to define all that custom commands

**Comment by mgrybyk** [comment] 2019-02-24 01:56
let's proceed conversation in PR https://github.com/webdriverio/webdriverio/pull/3610

**Comment by flunderpero** [comment] 2019-02-25 07:26
As you mentioned in the PR, I too think it is best to throw an exception and let the test fail with an appropriate message. At least this is the best solution from a frameworks pov.

**Comment by mgrybyk** [comment] 2019-02-25 08:31
yeah, agree

**Comment by christian-bromann** [comment] 2019-02-25 11:31
@flunderpero @mgrybyk this looks like a driver issue and should be reported in that project

cc @burg .. seems that safaridriver is not sending rect properties in specific cases like

```
2019-02-23T16:36:18.837Z INFO webdriver: [GET] http://127.0.0.1:4447/wd/hub/session/0DCB497F-76E4-4E29-93E5-4035A6E5669E/element/node-F85D9EB9-CBD9-4D7E-82D8-A29F2849EEE3/rect
2019-02-23T16:36:18.887Z INFO webdriver: RESULT { x: 102, width: 578, height: 11 }
```

Any idea?

**Comment by mgrybyk** [comment] 2019-02-25 12:35
@christian-bromann you are absolutely right.
This is an issue of safari 12.0.3 driver, see details here https://github.com/SeleniumHQ/selenium/issues/6637

Looks like it is fixed in Safari Technology Preview 69


That's why there is an open question on how should webdriverio handle it.

My assumption is to throw proper error if command `getElementRect` is not working as expected, example, in our case it has not returned `y`.

Also, I was thinking on workaround for this issue by using JS wait to get element coords and size in this PR https://github.com/webdriverio/webdriverio/pull/3610 but I think it is awful to add workarounds for specific browsers.

**Comment by mgrybyk** [comment] 2019-02-25 12:35
@christian-bromann please suggest a proper way in terms of framework on how to deal with issues like this.

**Comment by christian-bromann** [comment] 2019-02-25 12:38
> Also, I was thinking on workaround for this issue by using JS wait to get element coords and size in this PR #3610 but I think it is awful to add workarounds for specific browsers.

I liked that workaround. I think it should be the job for WebdriverIO to polyfill problems of specific drivers to provide a consistent automation API. So I would propose to reopen the PR and get it merged.

**Comment by burg** [comment] 2019-02-25 15:12
This will be fixed in the next Safari update. I recommend not to add such a workaround.

**Comment by abjerstedt** [comment] 2019-02-25 20:46
@burg Isn't safari firmware locked though? We'd need the next actual iOS release in order to see the fix.

**Comment by burg** [comment] 2019-02-25 20:49
@abjerstedt I'm not sure what you are asking. iOS Safari does not support WebDriver. safaridriver is updated with Safari, either as part of an OS update or an app update for previous major OS versions. Safari Technology Preview also includes the fix, so people can use that to see the upstream behavior.

**Comment by mgrybyk** [comment] 2019-02-25 23:36
@abjerstedt it is not only about iOS, it is Safari in general, both iOS and Mac.

@burg  iOS Safari works with Appium and has just the same problem

**Comment by burg** [comment] 2019-02-25 23:49
Believe whatever you want, but the bug is in safaridriver, and I fixed it.

**Comment by mgrybyk** [comment] 2019-02-26 00:08
@burg just saying what I see, maybe it is two different issues.
Anyway thank you :)

**Comment by christian-bromann** [comment] 2019-02-26 13:58
We merged the PR that provides a workaround for this bug since we expect people to use the bugged version for quite some time. 

Thanks @mgrybyk for providing that workaround!

**Closed by christian-bromann** 2019-02-26 13:58 UTC
Labels: Driver Releated
