### ISSUE TITLE
[🐛 Bug]: browser.reloadSession() method not working as expected

### ISSUE THREAD

**Issue by deyvisPedrosa** [webdriverio/webdriverio#13816] opened 2024-10-28 17:35 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

^9.2.4

### Node.js Version

v20.11.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
 browserName: 'chrome'
}
```

### What happened?

After running the `browser.reloadSession()` method in a mocha.js test case, the page is blank and no URL are open when using the `browser.url()` method.

### What is your expected behavior?

After executing the reloadSession() method the browser should open a new window when executing the URL() method.

### How to reproduce the bug.

Feel free to clone the following repo [https://github.com/deyvisPedrosa/wdio-v9-reloadSession](https://github.com/deyvisPedrosa/wdio-v9-reloadSession).

The script with a reproducible example gets run by hitting the `npm run wdio` command.

### Relevant log output

```typescript
These are the logs printed after the execution of the reloadSession() and the URL() method:


[0-0] 2024-10-28T17:18:58.650Z INFO webdriver: RESULT You logged into a secure area!
[0-0] ×
Created TensorFlow Lite XNNPACK delegate for CPU.
[0-0] 2024-10-28T17:19:16.949Z INFO webdriver: COMMAND deleteSession(<object>)
[0-0] 2024-10-28T17:19:16.950Z INFO webdriver: [DELETE] http://localhost:55511/session/7b1335246b1a80bddbcf19e55527c243
[0-0] 2024-10-28T17:19:16.951Z INFO webdriver: DATA { deleteSessionOpts: { shutdownDriver: false } }
[0-0] 2024-10-28T17:19:17.226Z INFO webdriver: RESULT null
[0-0] 2024-10-28T17:19:17.239Z INFO webdriver: [POST] http://localhost:55511/session
[0-0] 2024-10-28T17:19:17.240Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       'goog:chromeOptions': [Object],
[0-0]       webSocketUrl: true,
[0-0]       unhandledPromptBehavior: 'ignore'
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   }
[0-0] }

DevTools listening on ws://127.0.0.1:56076/devtools/browser/0ecbdd3f-62e3-475d-bbe6-ccaa5534fd9f
[0-0] 2024-10-28T17:19:24.294Z INFO webdriver: BIDI COMMAND browsingContext.navigate {"context":"1299C18A3548717391B73936E18AE9B8","url":"https://the-internet.herokuapp.com/login","wait":"complete"}
Created TensorFlow Lite XNNPACK delegate for CPU.
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2024-10-28 18:55
Duplicate of #13789

**Closed by christian-bromann** 2024-10-28 18:55 UTC
Labels: Bug 🐛, Needs Triaging ⏳
