### ISSUE TITLE
Supporting running tests in non-tty environments like IntelliJ

### ISSUE THREAD

**Issue by javacoldbrew** [webdriverio/webdriverio#2772] opened 2018-06-13 19:24 UTC
## The problem

Running npm scripts like `"dev": "wdio wdio.dev.conf"` through IntelliJ causes it to hang and not run the tests.

## Environment

* WebdriverIO version: 4.12.0
* Node.js version: v8.9.4
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: asynchronous tests
* Additional wdio packages used (if applicable): 

## Work Around

This can fixed by commenting out `if (process.stdin.isTTY)` in `node_modules\webdriverio\build\lib\cli.js`.

Replace (lines 459 - 478):
```
if (process.stdin.isTTY) {
    launch();
} else {
    var stdinData = '';
    /*
     * get a list of spec files to run from stdin, overriding any other
     * configuration suite or specs.
     */
    var stdin = process.openStdin();
    stdin.setEncoding('utf8');
    stdin.on('data', function (data) {
        stdinData += data;
    });
    stdin.on('end', function () {
        if (stdinData.length > 0) {
            args['specs'] = stdinData.trim().split(/\r?\n/);
        }
        launch();
    });
}
```

With:

`launch();`

And IntelliJ is able to run the npm scripts that contain wdio.

Original fixed was found here: 

https://stackoverflow.com/questions/50724279/how-to-get-wdio-running-through-intellij-run-debug-configurations

## Requested Feature

Allowing to add a `--nontty` arg to `wdio `that will skip the `if (process.stdin.isTTY)` check and will simply run `launch();`.

## Benefits 

It will allow for WebdriverIO tests to run through IntelliJ and will allow for them to use IntelliJ's debugger.

**Comment by christian-bromann** [comment] 2018-06-14 09:31
duplicate of #2624

**Closed by christian-bromann** 2018-06-14 09:31 UTC
