### ISSUE TITLE
ELEMENT method does not return the first matching element located in the dom

### ISSUE THREAD

**Issue by LucasWorld** [webdriverio/webdriverio#1991] opened 2017-04-19 04:05 UTC
## The problem

I am trying to select a element in the page, the DOM likes below
```bash
<div class="ComponentSelector__XType" data-reactid=".c.2.1.2:$3">
  <div data-reactid=".c.2.1.2:$3.0">Order</div>
</div>

<div class="ComponentSelector__XType" data-reactid=".c.2.1.2:$4">
  <div data-reactid=".c.2.1.2:$4.0">Executions</div>
</div>
```
and my code like
```bash
browser.element(`.ComponentSelector__XType`)
			.element(`div=Order`)
			.click();
```
as the document said, i think the code above should click Order item. but actually 
```bash
browser.element(`.ComponentSelector__XType`).element(`div=Order`).getHTML()
```
return something like
```bash
["<div class="ComponentSelector__XType" data-reactid=".a.2.1.2:$3"><div data-reactid=".a.2.1.2:$3.0">Order Blotter</div></div>", "<div data-reactid=".a.2.1.2:$3.0">Order Blotter</div>"]
```
these code works before i update webdriverio to 4.6.2
## Environment

* WebdriverIO version:  4.6.2
* Node.js version:6.10

**Comment by christian-bromann** [comment] 2017-04-19 07:05
Duplicate of #1939

**Closed by christian-bromann** 2017-04-19 07:05 UTC
