### ISSUE TITLE
[🐛 Bug]: Eslint `await-thenable` rule doesn't recognise async commands

### ISSUE THREAD

**Issue by kopax-polyconseil** [webdriverio/webdriverio#9100] opened 2022-10-27 14:16 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.22.0 and 8.0.0-alpha.412

### Node.js Version

18

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
const capabilities = {
  platformName: 'iOS',
  'appium:app':
    IOS_ZIP_PATH || 'https://github.com/appium/appium/raw/1.x/sample-code/apps/TestApp.app.zip',
  'appium:automationName': 'XCUITest',
  'appium:deviceName': IOS_DEVICE_NAME || 'iPhone 12',
  'appium:platformVersion': IOS_PLATFORM_VERSION || '15.5',
}
```

### What happened?

```ts
import { remote, RemoteOptions } from 'webdriverio'

const { IOS_ZIP_PATH, IOS_DEVICE_NAME, IOS_PLATFORM_VERSION } = process.env

const capabilities = {
  platformName: 'iOS',
  'appium:app':
    IOS_ZIP_PATH || 'https://github.com/appium/appium/raw/1.x/sample-code/apps/TestApp.app.zip',
  'appium:automationName': 'XCUITest',
  'appium:deviceName': IOS_DEVICE_NAME || 'iPhone 12',
  'appium:platformVersion': IOS_PLATFORM_VERSION || '15.5',
}

const wdOpts: RemoteOptions = {
  port: 4723,
  logLevel: 'info',
  capabilities,
}

describe('ios', () => {
  let driver: WebdriverIO.Browser | undefined

  beforeAll(async () => {
    driver = await remote(wdOpts)
    expect(driver).toBeDefined()
  })

  afterEach(async () => {
    await driver.deleteSession()
  })

  it('should type "Hello World!" and retrieve value in input', async () => {
    const elementId = await driver.findElement('accessibility id', 'IntegerA')
    driver.elementSendKeys(elementId.ELEMENT, 'Hello World!')

    const elementValue = await driver.findElement('accessibility id', 'IntegerA')
    const attr = await driver.getElementAttribute(elementValue.ELEMENT, 'value')
    expect(attr).toEqual('Hello World!')
  })

  it('should click on "show alert" and read alert text', async () => {
    const element = await driver.findElement('accessibility id', 'show alert')
    await driver.elementClick(element.ELEMENT)
    const alertText = await driver.getAlertText()
    expect(alertText).toEqual(`Cool title this alert is so cool.`)
  })
})
```

Ide shows `Redundant 'await' for a non-promise type` for `driver.getElementAttribute` and `driver.getAlertText()`, looking at the typing he is right:

```ts
    /**
     * Webdriver Protocol Command
     *
     * The Get Element Attribute command will return the attribute of a web element.
     * @ref https://w3c.github.io/webdriver/#dfn-get-element-attribute
     *
     */
    getElementAttribute(elementId: string, name: string): string;
    getAlertText(): string;
    /**
     * Webdriver Protocol Command
     *
     * The Send Alert Text command sets the text field of a window.prompt user prompt to the given value.
     * @ref https://w3c.github.io/webdriver/#dfn-send-alert-text
     *
     */
```

I have **similar problem** with element return by `getElementAttribute`:

```
TS2339: Property 'ELEMENT' does not exist on type 'ElementReference'.
```

I presume there's something wrong, maybe wrong package ?

### What is your expected behavior?

Typing to work well

### How to reproduce the bug.

Copy the test, test it.

Try to remove, the `await`, it will break.

### Relevant log output

```typescript
![image](https://user-images.githubusercontent.com/77674046/198309961-61b119af-db60-4650-8f87-c578d84fd9ab.png)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2022-10-28 18:15
> TS2339: Property 'ELEMENT' does not exist on type 'ElementReference'.

This is a legit error, if you use `findElement` the WebDriver response doesn't contain an `ELEMENT`.

Fixing this results in:
```js
  it('should type "Hello World!" and retrieve value in input', async () => {
    const elementId = await driver.findElement('accessibility id', 'IntegerA')
    driver.elementSendKeys(elementId['element-6066-11e4-a52e-4f735466cecf'], 'Hello World!')

    const elementValue = await driver.findElement('accessibility id', 'IntegerA')
    const attr = await driver.getElementAttribute(elementId['element-6066-11e4-a52e-4f735466cecf'], 'value')
    expect(attr).toEqual('Hello World!')
  })

  it('should click on "show alert" and read alert text', async () => {
    const element = await driver.findElement('accessibility id', 'show alert')
    await driver.elementClick(element['element-6066-11e4-a52e-4f735466cecf'])
    const alertText = await driver.getAlertText()
    expect(alertText).toEqual(`Cool title this alert is so cool.`)
  })
```
which does not have any TS errors.

**Comment by kopax-polyconseil** [comment] 2022-10-28 19:37
Sorry but... how did you get the element id ? And is this not flacky? Why there isnt any conventional api to access it ? 

Thank you in advance for providing more details as this is certainly not what we expect to read when looking at the source...

**Comment by kopax-polyconseil** [comment] 2022-10-28 19:39
Also you didn't reply to the typing problen why do we need to await promise that are not or why promise are wrongly typed... 

can you reopen until i get an answer? I will have to recreate an issue, this question is complete so it will be a copy past with this one linked.

**Comment by christian-bromann** [comment] 2022-10-28 20:30
> Why there isnt any conventional api to access it ?

There is: https://webdriver.io/docs/api/browser/$ - have a read on some of the core concepts to understand why: https://webdriver.io/docs/setuptypes - our assumption is that the `$` command is used in all examples so people would use it automatically. I can totally understand though if this can be confusing when there is a `findElement` method.

> Also you didn't reply to the typing problen

I didn't have this typing problem.

**Comment by kopax-polyconseil** [comment] 2022-10-28 23:34
Typing depends on ts declaration, the declaration I posted are from 7.22.0 and 8.0.0-alpha.412, what version do you use ? Those declaration are incorrect so if you are using the same versions, how can't you have the same problem when calling those methods ? This doesn't sounds realisit so I rather make dure you never used them or face the same problem or used a different version

**Comment by christian-bromann** [comment] 2022-10-28 23:59
> I posted are from 7.22.0 and 8.0.0-alpha.412

I used latest which is `7.22.0`. The other version is not released yet.

> Those declaration are incorrect so if you are using the same versions, how can't you have the same problem when calling those methods ?

Can be many things, wrong TS setup may be one.

> as i still think this issue deserve to be treated because I demonstrated with all details the typing issue

I am helping you here and just because I closed it doesn't mean I leave you hanging. I think the best we can do is you providing a minimal reproducible example that I can check out and look into. What do you think?

**Comment by kopax-polyconseil** [comment] 2022-10-29 14:10
Reproduction here:

https://github.com/pass-culture/pass-culture-app-native/
branch 2.x-poc

Remove the last commit where i disabled typescript.

But this is not necessary, checking the typing of the module in node modules will be as presented here in the snippet.

yarn test:types command will not work as I still didnt found how to allow two tsconfig.json and react native ans webdriverio needs two

**Comment by kopax-polyconseil** [comment] 2022-10-31 08:51
![image](https://user-images.githubusercontent.com/77674046/198968549-cf33011b-dba2-494e-985f-f23f793956b9.png)
![image](https://user-images.githubusercontent.com/77674046/198968652-8da78899-645d-43de-a237-9374b9c52666.png)
![image](https://user-images.githubusercontent.com/77674046/198968827-948075a9-597b-4db3-93d5-e1a5e76d74db.png)

**Comment by kopax-polyconseil** [comment] 2022-10-31 08:57
> There is: https://webdriver.io/docs/api/browser/$ - have a read on some of the core concepts to understand why: https://webdriver.io/docs/setuptypes - our assumption is that the $ command is used in all examples so people would use it automatically. I can totally understand though if this can be confusing when there is a findElement method.

I still don't get what to do here, I just used the appium 1.x JS examples and it seems they used `elementId.ELEMENT`, and it seems also the value is defined, however in your example you target an unknown ID that doesn't reflect anything to us.

I didn't get the explanation with `$`, but we are in a react-native iOS native/Android Native environment so selectors won't work if they are for web.

**Comment by erwinheitzman** [comment] 2022-10-31 09:52
I'm not sure what examples you are using but we have a boilerplate showing you how to use WebdriverIO + Appium + Typescript that you can use as an example.

A branch with the name you shared does not exist so there's no setup for me to look at.
What I can tell is that you are able to use the `$` instead of the `findElement`. `findElement` although available is not the command you should be using, which can also be seen in the mentioned boilerplate.

I stress what Christian has already mentioned, without a reproducible example for us to look at, we can't help as there are a gazillion ways to configure/setup typescript.

**Comment by kopax-polyconseil** [comment] 2022-10-31 09:58
Sorry, I had to rename the branch : https://github.com/pass-culture/pass-culture-app-native/pull/3838

I will have a look to the boilerplate. Thanks !

**Comment by erwinheitzman** [comment] 2022-10-31 10:00
I suggest reading through the readme too as there's a bunch of mobile testing best practices mentioned, I'd take them by heart as Wim (the author) is a true mobile testing guru.

**Comment by kopax-polyconseil** [comment] 2022-10-31 10:03
I just had a check and : 

This repository does only provide one typescript setup : https://github.com/webdriverio/appium-boilerplate/blob/main/tsconfig.json 

This won't work for us as we store the react-native app and the e2e on the same repo, but that's a whole topic on it's own, let's just ignore that.

It also use a deprecated version of appium , upgrading should be quite simple.

All those specs given here are gold, I will clone it and see if I can reproduce the typing issue.

And for sure I will learn them all.

**Comment by erwinheitzman** [comment] 2022-10-31 10:38
Using both in one repo shouldn't be an issue, you can use the following structure:
```
- src

- test
 - tsconfig.json

tsconfig.json // exclude test
```

If you want to place the test files next to the frontend code then there's a bit of a challenge depending on your setup.
The next release (v8) will allow you to import the global types instead which should solve such challenges.

**Comment by kopax-polyconseil** [comment] 2022-10-31 11:07
> Using both in one repo shouldn't be an issue, you can use the following structure:

That's what we do for our `server` directory, but long term, problem is that IDE can't handle multiple ts project configuration, so dev experience won't be good. we need to tell which tsconfig to read.

I saw some monorepo managed to have multiple tsconfig working in IDE, but I gave a try and couldn't fix all the issues, I reported for later to investigate as I am focusing in GitHub actions POC for appium.

Did you had an apportunity to check at the typing problem we have?  I tried to import my e2e test in your project to check if the typing is ok here. I've not been able to find where is defined `driver` and I wasn't unable to check if the typing problem gets resolved. 

I also tried to find where `$` gets configured, I couldn't, but I will dig in the configuration later, perhaps it's done through a module...


Overall, the configuration is really interesting, I stared the project and will keep it as a reference. I wonder about: 

```ts
    // Framework you want to run your specs with.
    // The following are supported: Mocha, Jasmine, and Cucumber
    // see also: https://webdriver.io/docs/frameworks
    //
    // Make sure you have the wdio adapter package for the specific framework installed
    // before running any tests.
    framework: "mocha",
```

As you can see in our repo, we expected to use `jest`, why don't you support jest ? It seems to be the most used lib for testing in here.

**Comment by kopax-polyconseil** [comment] 2022-10-31 15:22
> I am not looking into this at all right now as there doesn't seem to be an issue.

Did you had a look at the screenshot ? How do you explain the wrong types not being an issue ? 
![image](https://user-images.githubusercontent.com/77674046/199044260-52dbc831-e1f4-4db8-b70b-200d73d16ba5.png)


> Not supporting Jest has a long history

We are using jest, it seems to work but we are not aware of development done on your side to call it "supported"

Do you think we should switch to another framework ? what are the pro / cons ?

**Comment by christian-bromann** [comment] 2022-10-31 15:33
Jest is a unit test framework and barely offers any advantages for e2e testing. We also didn't support it as your tests are written the same way given WebdriverIO also uses `expect` as assertion library. Which Jest features are you missing or are important to you for e2e testing?

> How do you explain the wrong types not being an issue ?

Because in your [`tsconfig.json`](https://github.com/pass-culture/pass-culture-app-native/blob/e4544e6e2f957e9d00e71014917aa7ae57acf3a7/e2e/config/jest.e2e.config.js) you are not setting the correct `types` property as describe in [our docs](https://webdriver.io/docs/typescript#framework-setup). WebdriverIO assumes you are running sync tests as this has been a default. With v8 this will go away as we only support async execution.

**Comment by kopax-polyconseil** [comment] 2022-10-31 15:37
> Which Jest features are you missing or are important to you for e2e testing?

I think the right question should be:  "we already have jest, why should we add another library?"

Of course we can add all the modules available on npm, do we want to? 

> Because in your [tsconfig.json](https://github.com/pass-culture/pass-culture-app-native/blob/e4544e6e2f957e9d00e71014917aa7ae57acf3a7/e2e/config/jest.e2e.config.js) you are not setting the correct types property as describe in [our docs](https://webdriver.io/docs/typescript#framework-setup).

https://github.com/pass-culture/pass-culture-app-native/pull/3838/files#diff-b5f32afdd9e8c14b02c570db855022a30aeb595e3dd1c3a71c187d685c0a2860R4

![image](https://user-images.githubusercontent.com/77674046/199047665-98d981f0-fdb7-4567-bb90-16beac3e6480.png)


We are, so according to your answer, I believe the IDE is wrong, because it does read the react-native `tsconfig.json`, thus we do not have proper support for typescript because of that.

**Comment by christian-bromann** [comment] 2022-10-31 15:46
> we already have jest, why should we add another library?

Simple, because you have to use different tools for different purposes. Jest is an unit test tool and designed to do that. WebdriverIO is for e2e testing. While it seems that both tools do the same thing there are a lot of things important for e2e testing that no one writing unit tests cares about. You are welcome to try to use one tool for everything and you certainly can integrate WebdriverIO or anything else into Jest but ultimately this won't be a good choice IMO.

> I still don't get why we should add an extra testing library.

I don't really understand this problem. How many dependencies do you have in your `package.json` that adding a new one would matter. If you use any frontend framework you also don't just one package which does everything.

I believe this problem is related to Eslint actually as I remember to have the same problem before too. The rule causing this is https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/await-thenable.md.

I will re-open to see whether this is something that can be fixed in WebdriverIO land.

**Comment by christian-bromann** [comment] 2022-10-31 15:59
> or do you recommend another one?

I recommend Vitest for unit testing and WebdriverIO for e2e testing. I do __not__ recommend to make flawed choices for frameworks just because there is one less dependency to install 😉 

> My IDE doesn't care of `./e2e/tsconfig.json`, it only care of `./tsconfig.json`. I can try to change the `compilerOptions.types` in the root `tsconfig.json` and see if proper typing gets detected by my IDE.

Again, this is not a TypeScript issue. It is an Eslint issue.

**Comment by kopax-polyconseil** [comment] 2022-11-07 17:01
I am doing a POC here using the boilerplate you have provided, so far it work better, but I cant use https://webdriver.io/docs/typescript/#configuration as I expect, having the `autoCompileOpts` provide the right `tsconfig.json` from e2e folder seems ignored, any clue why ? https://github.com/webdriverio/webdriverio/issues/9151#issuecomment-1305889787

**Comment by christian-bromann** [comment] 2022-11-07 17:03
@kopax-polyconseil this is unrelated to the original issue. Please use the Gitter channel for queries like this.

**Comment by christian-bromann** [comment] 2022-12-06 07:16
I looked into it and am unsure how to reproduce it. My assumption is that the issue was caused my TypeScript being misconfigured as commands usually return promises if `webdriverio/async` (in v7) or `@wdio/globals/types` (in v8) is set. There doesn't seem to be anything left I can do at this point.

@kopax-polyconseil if there is a way you can give me a minimal reproducible example, that would be great and I would be happy to re-open.

**Closed by christian-bromann** 2022-12-06 07:16 UTC
Labels: Bug 🐛, help wanted
