### ISSUE TITLE
With Chromedriver 87 uploadFile doesn't work any more

### ISSUE THREAD

**Issue by Minja90** [webdriverio/webdriverio#6170] opened 2020-11-26 20:35 UTC
After npm install and upgrade to Chromedriver 87,

const remoteFilePath = browser.uploadFile(filePath)

throws an error : 
web driver: Request failed with status 400 due to invalid argument: invalid argument: 'text' is empty

This worked before upgrade

**Comment by mgrybyk** [comment] 2020-11-27 12:47
Please provide with reproducible example, logs, what have you updated, etc.

**Comment by nhle** [comment] 2020-11-27 16:41
I had the same issue and tried to update selenium standalone from 3.141.59 to 4.0.0-alpha-1. It works.

**Comment by mgrybyk** [comment] 2020-11-27 16:44
It should not be related anyhow.

**Comment by brunobasto** [comment] 2020-11-27 18:07
Same issue here:

```js
const remoteFilePath = browser.uploadFile(path.resolve(__dirname, '../assets/file.csv'));
fileInput.setValue(remoteFilePath)
```

`remoteFilePath` returns as an empty string

```json
{
    "devDependencies": {
        "@wdio/browserstack-service": "^6.10.0",
        "@wdio/cli": "^6.10.2",
        "@wdio/local-runner": "^6.10.2",
        "@wdio/mocha-framework": "^6.8.0",
        "@wdio/spec-reporter": "^6.8.1",
        "@wdio/sync": "^6.10.0",
    }
}
```

Also, it would be extremely useful if that worked on IE as well :)

**Comment by Minja90** [comment] 2020-11-28 09:15
Hello @mgrybyk ,
so here is the log : 

ERROR webdriver: Request failed with status 400 due to invalid argument: invalid argument: 'text' is empty
  (Session info: chrome=87.0.4280.67)
[0-0] invalid argument in "Upload Contact via CSV should import new contact successfully"
invalid argument: 'text' is empty
  (Session info: chrome=87.0.4280.67)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
I have same packages as @brunobasto  has in my package.json, and this worked two days ago until I upgraded to the latest Chrome version (87.0.4280.67) and latest Chromedriver. Then this function stopped working, please investigate

**Comment by mgrybyk** [comment] 2020-11-28 10:28
@Minja90 can't investigate without either sufficient amount of logs or a reproducible example. The last one is better

**Comment by PaliwalArpit** [comment] 2020-11-30 08:49
Getting a similar issue while uploading the file using the upload file method.

```
invalid argument: 'text' is empty
  (Session info: chrome=87.0.4280.66)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
I have updated packages recently including Chormedriver and wdio services, for me as well the test was working fine earlier.
My package.json packages:

```
 "devDependencies": {
    "@wdio/allure-reporter": "^6.8.1",
    "@wdio/cli": "^6.0.1",
    "@wdio/devtools-service": "^6.3.7",
    "@wdio/dot-reporter": "^6.8.1",
    "@wdio/junit-reporter": "^6.8.1",
    "@wdio/local-runner": "^6.10.0",
    "@wdio/mocha-framework": "^6.8.0",
    "@wdio/selenium-standalone-service": "^6.10.0",
    "@wdio/spec-reporter": "^6.8.1",
    "@wdio/sync": "^6.10.0",
    "chromedriver": "^87.0.0",
    "devtools": "^6.10.0",
    "mocha": "^6.2.3",
    "wdio-chromedriver-service": "^6.0.0",
    "webdriverio": "^6.10.0"
  }
```

**Comment by christian-bromann** [comment] 2020-11-30 10:00
Proposed a PR with a fix, closing this one.

**Closed by christian-bromann** 2020-11-30 10:00 UTC
Labels: Bug🐛

**Comment by prabhuhiremath237** [comment] 2020-12-01 03:48
> wdio


Execution of 1 spec files started at 2020-12-01T03:36:22.612Z

[0-0] RUNNING in chrome - /test/specs/add.candidate.spec.ts
[0-0] Login as RA and add valid candidate
[0-0] personal.uploadResume
./test/testdata/add-candidate/NandiniB.docx
[0-0] 2020-12-01T03:36:45.580Z ERROR webdriver: Request failed with status 400 due to invalid argument: invalid argument: 'text' is empty
  (Session info: chrome=87.0.4280.67)
[0-0] invalid argument in "All tests Adding candidate Login as RA and add valid candidate"
invalid argument: 'text' is empty
  (Session info: chrome=87.0.4280.67)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Upload.uploadFile (/Users/prabhu/Documents/Talent500/test_automation/src/components/upload.ts:11:27)
    at Personal.fillAllPersonalDetails (/Users/prabhu/Documents/Talent500/test_automation/test/pages/add-candidate/personal.ts:51:44)
    at Context.<anonymous> (/Users/prabhu/Documents/Talent500/test_automation/test/specs/add.candidate.spec.ts:91:18)
[0-0] FAILED in chrome - /test/specs/add.candidate.spec.ts

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:23 

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! talent500@1.0.0 test: `wdio`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the talent500@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/prabhu/.npm/_logs/2020-12-01T03_36_46_707Z-debug.log
prabhu@Prabhus-MBP test_automation % 



Above is log for my test 
Even im facing same issue after updating chrome driver

**Comment by christian-bromann** [comment] 2020-12-01 08:09
@prabhuhiremath237 ensure to update your dependencies. This has been fixed.

**Comment by prabhuhiremath237** [comment] 2020-12-01 08:23
@christian-bromann 

all my dependencies are updated

"devDependencies": {
    "@types/chai": "^4.2.14",
    "@types/faker": "^5.1.4",
    "@types/jsdom": "^16.2.5",
    "@types/mocha": "^8.0.3",
    "@types/node": "^14.14.6",
    "@types/node-fetch": "^2.5.7",
    "@typescript-eslint/eslint-plugin": "^4.6.0",
    "@typescript-eslint/parser": "^4.6.0",
    "@wdio/allure-reporter": "^5.16.0",
    "@wdio/cli": "^6.10.2",
    "@wdio/dot-reporter": "^6.7.0",
    "@wdio/local-runner": "^6.10.2",
    "@wdio/mocha-framework": "^6.8.0",
    "@wdio/selenium-standalone-service": "^6.10.0",
    "@wdio/sync": "^6.10.0",
    "allure-commandline": "^2.13.0",
    "chai": "^4.2.0",
    "chromedriver": "^87.0.0",
    "eslint": "^7.12.1",
    "faker": "^5.1.0",
    "form-data": "^3.0.0",
    "mocha": "^8.2.0",
    "node-fetch": "^2.6.1",
    "soft-assert": "^0.2.3",
    "ts-node": "^9.0.0",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^4.0.5",
    "wdio-chromedriver-service": "^6.0.4",
    "webdriverio": "^6.10.2"
  }


Please let me know what else need to be updated

**Comment by christian-bromann** [comment] 2020-12-01 08:27
@prabhuhiremath237 in order to update your dependencies properly make sure to remove your package-lock.json file and re-install all dependencies.

**Comment by prabhuhiremath237** [comment] 2020-12-01 08:34
@christian-bromann 
Sure thank you let me try
