### ISSUE TITLE
'Cannot read property 'isW3C' of undefined'

### ISSUE THREAD

**Issue by Trueside** [webdriverio/webdriverio#6752] opened 2021-04-23 13:17 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.4.2
 - **Mode:**  WDIO Testrunner, running sync
 - **Node.js version:** v14.16.1
 - **NPM version:** 6.14.12
 - **Browser name and version:**  Chrome "90.0.4430.85"
 - **Platform name and version:** "win32", "10.0.19042"
 - **Additional wdio packages used (if applicable):**
 - "@wdio/allure-reporter": "^7.4.2",
    "@wdio/devtools-service": "^7.4.6",
    "@wdio/local-runner": "^7.4.2",
    "@wdio/mocha-framework": "^7.4.2",
    "@wdio/sync": "^7.4.2",
    "wdio-chromedriver-service": "^7.0.0",
    "webdriverio": "^7.4.2"
    "@wdio/cli": "^7.4.2"

**Config of WebdriverIO**
```js
const headless = process.env.HEADLESS == 'true' ? true : false;
const debug = process.env.DEBUG == 'true' ? true : false;
const browser = process.env.BROWSER || 'chrome';
const streams = parseInt(process.env.STREAMS, 10) || 1;
const pathToMetamask = require('path').join(__dirname, './metamask/app');

let chromeCap = () => {
  let chromeCap = {
    platformName: 'Windows 10', // OS platform
    browserName: 'chrome',
    'goog:chromeOptions': {
      args: [
        `--disable-extensions-except=${pathToMetamask}`,
        `--load-extension=${pathToMetamask}`,
        '--custom-launcher-page',
        '--extensions-on-chrome-urls',
        '--extensions-not-webstore',
        '--window-size=960,740',
        '--mute-audio',
        '--ash-disable-touch-exploration-mode ',
        '--test-name', //passes test's name
      ],
    },
    acceptInsecureCerts: true,
  };
  return chromeCap;
};

let browserCap = () => {
  let res;
    case 'chrome':
    default:
      res = [chromeCap()];
  }
  return res;
};

let specsCap = () => {
  return [
  ];
};

let config = {
  runner: 'local',
  specs: specsCap(),
  suites: {},
  exclude: [
  ],
  maxInstances: debug ? 1 : streams,
  capabilities: browserCap(),

  logLevel: 'debug',
  bail: 0,
  baseUrl: 'https://s-1-stage..com/',
  waitforTimeout: 3000,
  connectionRetryTimeout: 5000,
  connectionRetryCount: 1,
  services: [
  ],
  reporters: [['allure', { outputDir: 'allure-results' }]],

  framework: 'mocha',
  mochaOpts: {
    ui: 'bdd',
    timeout: process.env.DEBUG === 'true' ? 999999 : 23666,
  },

  beforeTest: function () {
    const chai = require('chai');
    global.assert = chai.assert;
    global.should = chai.should;
    global.expect = chai.expect;
  },
};
exports.config = config;
```

**Describe the bug**
Hello. Sorry, I'n newbee in wdio and js. I have been working with them for a couple of weeks and inherited the config file. So, I try to click button of chrome extension named Metamask. I use ccs-selector button.first-time-flow__button , it's valid. In test I call a function from other module Metamask:

```
//Metamask.js
const locators = {
  firstOpen: {
    btnGetStarted: 'button.first-time-flow__button', //started button
  }
}
class Metamask extends Page {
  get getBtnGetStarted() { return $(locators.firstOpen.btnGetStarted); }
  }
}

calledFunction () {
    // this.doSwitchToTab(links.startPage);
    this.doSwitchToMetamaskTab();

    elemUtil.doClick(this.getBtnGetStarted());
  }
}


//elemUtil.js
class ElementUtil {
  doClick(elem, timeout = 10000) {
    elem.waitForDisplayed({
      timeout: timeout,
    });
    elem.waitForClickable({
      timeout: timeout,
    });
    elem.click();
  }
```

It's work for other login test.

**Expected behavior**
be able to click on the ccs-selector button.first-time-flow__button

**Log**
```
[0-0] 2021-04-23T13:55:51.179Z INFO devtools: COMMAND switchToWindow("0a3f56bb-68eb-4a38-8c4d-75fc8e6c165b")
[0-0] 2021-04-23T13:55:51.261Z INFO devtools: RESULT 0a3f56bb-68eb-4a38-8c4d-75fc8e6c165b
[0-0] 2021-04-23T13:55:51.315Z INFO devtools: COMMAND getUrl()
[0-0] 2021-04-23T13:55:51.360Z INFO devtools: RESULT chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/home.html#initialize/welcome
```

**Additional context**
Globar driver state:

```
{
  sessionId: "837dd562-da68-4cae-a194-4fc9051cd5d3",
  capabilities: {
    browserName: "Chrome",
    browserVersion: "90.0.4430.85",
    platformName: "win32",
    platformVersion: "10.0.19042",
    "goog:chromeOptions": {
      debuggerAddress: "localhost:52322",
    },
  },
  addCommand: (name, fn, attachToElement) => (origAddCommand(name, utils_1.runFnInFiberContext(fn), attachToElement)),
  overwriteCommand: (name, fn, attachToElement) => (origOverwriteCommand(name, utils_1.runFnInFiberContext(fn), attachToElement)),
  addLocatorStrategy: (name, func) => {
    if (scope.strategies.get(name)) {
        throw new Error(`Strategy ${name} already exists`);
    }
    scope.strategies.set(name, func);
  },
  config: {
    specs: [
    ],
    suites: {
    },
    exclude: [
    ],
    outputDir: undefined,
    logLevel: "debug",
    logLevels: {
    },
    excludeDriverLogs: [
    ],
    bail: 0,
    waitforInterval: 500,
    waitforTimeout: 3000,
    framework: "mocha",
    reporters: [
      [
        "allure",
        {
          outputDir: "allure-results",
        },
      ],
    ],
    services: [
      [
        {
          savePerInstance: true,
          autoSaveBaseline: true,
          blockOutStatusBar: true,
          blockOutToolBar: true,
        },
      ],
    ],
    maxInstances: 1,
    maxInstancesPerCapability: 100,
    filesToWatch: [
    ],
    connectionRetryTimeout: 5000,
    connectionRetryCount: 1,
    execArgv: [
    ],
    runnerEnv: {
    },
    runner: "local",
    specFileRetries: 0,
    specFileRetriesDelay: 0,
    specFileRetriesDeferred: false,
    reporterSyncInterval: 100,
    reporterSyncTimeout: 5000,
    cucumberFeaturesWithLineNumbers: [
    ],
    autoCompileOpts: {
      autoCompile: true,
      tsNodeOpts: {
        transpileOnly: true,
      },
      babelOpts: {
      },
    },
    mochaOpts: {
      timeout: 999999,
      ui: "bdd",
    },
    jasmineOpts: {
      defaultTimeoutInterval: 10000,
    },
    cucumberOpts: {
      timeout: 10000,
    },
    beforeTest: [
      function () { [native code] },
    ],
    baseUrl: "https://s-1-stage.com/",
    _: [
      "./e2e/wdio.mm.conf.js",
    ],
    spec: [
    ],
    $0: "node_modules\\@wdio\\cli\\bin\\wdio.js",
    ignoredWorkerServices: [
    ],
  },
  _NOT_FIBER: false,
}
```

**Comment by christian-bromann** [comment] 2021-04-23 13:26
Can you please provide the stacktrace and the piece of code where this error is thrown?

**Comment by Trueside** [comment] 2021-04-23 13:34
> Can you please provide the stacktrace and the piece of code where this error is thrown?

findElement (c:\work\wwwwwwwwwwwwwwww\portal\e2e\node_modules\webdriverio\build\utils\index.js:232)
$ (c:\work\wwwwwwwwwwwwwwww\portal\e2e\node_modules\webdriverio\build\commands\browser\$.js:68)
get getBtnGetStarted (c:\work\wwwwwwwwwwwwwwww\portal\e2e\pageobjects\metamask.page.js:94)
doLoginToWallet (c:\work\wwwwwwwwwwwwwwww\portal\e2e\pageobjects\metamask.page.js:143)
<anonymous> (c:\work\wwwwwwwwwwwwwwww\portal\e2e\tests\crypto-payments\usdt-payments-base-suite.test.js:17)
executeSync (c:\work\wwwwwwwwwwwwwwww\portal\node_modules\@wdio\sync\build\index.js:38)
<anonymous> (c:\work\wwwwwwwwwwwwwwww\portal\node_modules\@wdio\sync\build\index.js:69)
Promise.then (Unknown Source:1)
wrapCommandFn (c:\work\wwwwwwwwwwwwwwww\portal\node_modules\@wdio\sync\build\wrapCommand.js:68)
doSwitchToTab (c:\work\wwwwwwwwwwwwwwww\portal\e2e\pageobjects\page.js:43)
doSwitchToMetamaskTab (c:\work\wwwwwwwwwwwwwwww\portal\e2e\pageobjects\metamask.page.js:158)
doLoginToWallet (c:\work\wwwwwwwwwwwwwwww\portal\e2e\pageobjects\metamask.page.js:141)
<anonymous> (c:\work\wwwwwwwwwwwwwwww\portal\e2e\tests\crypto-payments\usdt-payments-base-suite.test.js:17)
executeSync (c:\work\wwwwwwwwwwwwwwww\portal\node_modules\@wdio\sync\build\index.js:38)
<anonymous> (c:\work\wwwwwwwwwwwwwwww\portal\node_modules\@wdio\sync\build\index.js:69)
Promise.then (Unknown Source:1)
wrapCommandFn (c:\work\wwwwwwwwwwwwwwww\portal\node_modules\@wdio\sync\build\wrapCommand.js:68)
doSwitchToMetamaskTab (c:\work\wwwwwwwwwwwwwwww\portal\e2e\pageobjects\metamask.page.js:157)
doLoginToWallet (c:\work\wwwwwwwwwwwwwwww\portal\e2e\pageobjects\metamask.page.js:141)
<anonymous> (c:\work\wwwwwwwwwwwwwwww\portal\e2e\tests\crypto-payments\usdt-payments-base-suite.test.js:17)


async function findElement(selector) {
    /**
     * fetch element using regular protocol command
     */
    if (typeof selector === 'string' || lodash_isplainobject_1.default(selector)) {
        const { using, value } = findStrategy_1.findStrategy(selector, this.isW3C, this.isMobile);               <---------- THERE

**Comment by christian-bromann** [comment] 2021-04-23 15:04
This seems odd because `this` should definitely defined in here, can you provide a reproducible example please?

**Comment by Trueside** [comment] 2021-04-23 16:49
> This seems odd because `this` should definitely defined in here, can you provide a reproducible example please?

There is an example. I transferred all the necessary logic and files. The behavior a little bit different now and code in find Element was different
https://github.com/Trueside/bug_err

**Comment by christian-bromann** [comment] 2021-04-24 09:52
After setting the project up (via `npm install`), when I run `npx wdio run wdio.mm.conf.js`:

- first error I am getting is `this.getBtnGetStarted is not a function` which is a bug that is not WebdriverIO related
- fixing this gets me to another WebdriverIO unrelated error `elem.waitForDisplayed is not a function`

After fixing that issue, the test suite passed. Please be careful with the following:

- when using getters you don't call the property [like a function](https://github.com/Trueside/bug_err/blob/main/pageobjects/metamask.page.js#L16)
- make sure your IDE doesn't [auto import](https://github.com/Trueside/bug_err/blob/main/pageobjects/metamask.page.js#L3) things that can cause issues with running synchronous code

I am closing this given that these are all user errors.

**Closed by christian-bromann** 2021-04-24 09:52 UTC
Labels: Reproducible Example Missing

**Comment by Trueside** [comment] 2021-04-24 14:37
> After setting the project up (via `npm install`), when I run `npx wdio run wdio.mm.conf.js`:
> 
> * first error I am getting is `this.getBtnGetStarted is not a function` which is a bug that is not WebdriverIO related
> * fixing this gets me to another WebdriverIO unrelated error `elem.waitForDisplayed is not a function`
> 
> After fixing that issue, the test suite passed. Please be careful with the following:
> 
> * when using getters you don't call the property [like a function](https://github.com/Trueside/bug_err/blob/main/pageobjects/metamask.page.js#L16)
> * make sure your IDE doesn't [auto import](https://github.com/Trueside/bug_err/blob/main/pageobjects/metamask.page.js#L3) things that can cause issues with running synchronous code
> 
> I am closing this given that these are all user errors.

Thank you!
