### ISSUE TITLE
Selecting test scripts based on mocha --grep option

### ISSUE THREAD

**Issue by kgish** [webdriverio/webdriverio#1452] opened 2016-07-13 13:38 UTC
## The problem

When I run `npm test` then `wdio` is fired off and reads the `wdio.conf.js` file in which test files can be ignored or selected based on filename regex.

Normally, `mocha` can be run with the `--grep string` option to select only those tests containing the given string.

Is this possible to do on the fly with `npm test` without having to modify the `wdio.conf.js` file every time?

## Environment

* WebdriverIO version: v4.09
* Node.js version: v4.4.5

## Details

N/A

## Link to Selenium/WebdriverIO logs

N/A

## Code To Reproduce Issue [ Good To Have ]

N/A

**Comment by christian-bromann** [comment] 2016-07-13 14:10
duplicate of #1247. You might find a solution for that in that thread. We haven't implemented that yet though.

**Closed by christian-bromann** 2016-07-13 14:10 UTC

**Comment by minhnhut1986** [comment] 2018-07-16 04:54
If i have test spec like below:

```
describe('Check Account', function () {

  describe('Register Success', function () {
    it('Open Register Page', function () {

    });
    it('Check Register Page Title', function () {

    });
  });

  describe('Login Success', function () {

    it('Open Login Page', function () {

    });
    it('Check Login Page Title', async function () {

    });
  });
});
```

I just want to run "Register Success" and ignore "Login Success". How to do it?

Normally, mocha can be run with the --grep string option to select only those tests containing the given string.

Please help me.

**Comment by christian-bromann** [comment] 2018-07-16 08:16
You can still apply the grep option in your mochaOpts of your wdio.conf.js
