### ISSUE TITLE
[🐛 Bug]: Can't disable console output

### ISSUE THREAD

**Issue by nzakas** [webdriverio/webdriverio#12231] opened 2024-02-14 00:27 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.31.1

### Node.js Version

v20.11.0 (Windows 10)

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
"chrome", "firefox"
```

### What happened?

Whenever I run tests, I get a ton of console output that makes it difficult to see the results of the tests (or any other console logs I do). I've tried setting everything I could find to `silent` in `wdio.conf.js`, but it doesn't seem to have any effect.

Note: I do not see this output on any CI system  (Mac, Windows, Linux) on GitHub. I just see it locally when I'm developing in VS Code and using the console to run tests.

### What is your expected behavior?

I should only see relevant console output and not a bunch of info logs.

### How to reproduce the bug.

1. Clone https://github.com/humanwhocodes/humanfs
2. `npm install`
3. `npm test -w packages/web`

### Relevant log output

```typescript
[0213/192114.624:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 5ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192114.628:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 4ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192114.646:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 3ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192114.649:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 3ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192114.696:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192114.699:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192114.758:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 3ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192114.761:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeTest" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192114.811:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterTest" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192114.817:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 1ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192114.830:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192114.832:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192114.845:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 1ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192114.847:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192114.879:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192114.882:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 1ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192114.922:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192114.927:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeTest" hook in 5ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192114.982:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterTest" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192114.989:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.003:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.006:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 3ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.017:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 1ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.019:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.057:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.060:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.106:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 3ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.110:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeTest" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.118:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterTest" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.127:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.144:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.148:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 3ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.165:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.167:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.211:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 4ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.215:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 3ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.283:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 5ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.285:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeTest" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.295:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterTest" hook in 3ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.303:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 3ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.318:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.321:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.333:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.338:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 4ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.373:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.376:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.434:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 1ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.437:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeTest" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.492:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterTest" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.498:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.513:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.515:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.527:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.530:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.566:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 1ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.568:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.627:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.629:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeTest" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.686:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterTest" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.695:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.711:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.713:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.734:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.736:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.771:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.774:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.830:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.832:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeTest" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.886:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterTest" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.894:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.911:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 3ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.914:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 1ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.926:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.930:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 3ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.969:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192115.972:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192116.035:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192116.037:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeTest" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192116.045:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterTest" hook in 3ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192116.053:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192116.070:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 1ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192116.073:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192116.085:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192116.087:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192116.122:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192116.125:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192116.185:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192116.188:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeTest" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192116.252:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterTest" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192116.260:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192116.278:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 1ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192116.281:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192116.292:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192116.295:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "beforeHook" hook in 2ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192116.299:INFO:CONSOLE(68)] "@wdio/utils:shim: Finished to run "afterHook" hook in 1ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/utils/build/shim.js?v=cdbd6523 (68)
[0213/192116.335:INFO:CONSOLE(153)] "[WDIO] Finished 
test suite in 15731ms", source: http://localhost:53147/@fs/C:/Users/nzaka/projects/humanwhocodes/fsx/node_modules/@wdio/browser-runner/build/browser/driver.js?import (153)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2024-02-14 01:08
Thanks for raising the issue @nzakas , can you describe a bit more in which environment you are running this in? If I run this in my terminal I get no log output:
![humanfs](https://github.com/webdriverio/webdriverio/assets/731337/14280af8-5fbc-49d3-b638-67df7dd6a30f)

Setting `logLevel` to silent should definitely do the trick, otherwise another option is to set a `outputDir` option that pipes all logs into a directory.

**Comment by nzakas** [comment] 2024-02-14 20:54
I've tried in a few other terminals and it seems like VS Code's terminal is the only one showing that output. 🤔 

I'm on Windows, and basically, any of the command windows I open in VS Code (Git Bash, cmd, etc.) show all of this noisy output, but when I run the tests in the standalone command window, I don't see it.

**Comment by christian-bromann** [comment] 2024-02-15 16:59
> I've tried in a few other terminals and it seems like VS Code's terminal is the only one showing that output. 🤔

Can you describe how you run your WebdriverIO tests through VS Code?

**Comment by nzakas** [comment] 2024-02-15 18:04
As described in my original comment. I run those commands directly in the VS Code terminal.

**Comment by erwinheitzman** [comment] 2024-03-01 16:02
The only difference I know is that vscode's integrated terminal has some differences like:
```
To get the development tools on the $PATH, VS Code will launch a bash login shell on startup. This means that your ~/.bash_profile has already run and when an integrated terminal launches, it will run another login shell, reordering the $PATH potentially in unexpected ways.
```

This means that any custom configuration in your shell files might not load correctly and might (big assumption here) explain the behaviour.

**Comment by christian-bromann** [comment] 2024-03-01 17:22
Sounds good to me. I don't see anything actionable here. I've been running component test from my VS Code terminal too without seeing this behavior.

**Comment by christian-bromann** [comment] 2024-03-14 04:40
I will go ahead and close this as I was not able to reproduce this on my end.

**Closed by christian-bromann** 2024-03-14 04:40 UTC
Labels: Bug 🐛, Reproducible Example Missing
