### ISSUE TITLE
[🐛 Bug]:unable to click an element for iPhone device on browserstack

### ISSUE THREAD

**Issue by vaibhavjagdale** [webdriverio/webdriverio#7685] opened 2021-11-11 09:13 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.13.2

### Node.js Version

v14.17.4

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
            "browserName": "safari",
            "device": "iPhone 12 Pro Max",
            "os_version": "14.0",
            "realMobile": true,
            "browserstack.debug": true,
            "browserstack.console": "errors",
            "build": "",
            "resolution": "1920x1080",
            "project": ""
        }
```

### What happened?

I am running tests for iPhone safari on browser stack. But click command is not working for iPhone safari on browser stack Selector seems to find an element correctly, but click does nothing and no error,no action ,just silently not executing click.

Same test running perfectly with android device. Is there any issue from browser stack or wdio?

I have checked similar thinks in protractor and that has been resolved with JSclick

await browser.executeScript('arguments[0].click();', ele.getWebElement());

I was trying same thing in webdriverIO but getting error:Argument of type 'Element' is not assignable to parameter of type '(string | number | boolean | object)[]'. Type 'Element' is missing the following properties from type '(string | number | boolean | object)[]': length, pop, push, concat, and 28 more.ts(2345) const countryDropDown: WebdriverIO.Element

await browser.executeScript("arguments[0].click();",ele);

Is there any workaround for ele.getWebElement() in WebdriverIO? or any other bettor solution?

### What is your expected behavior?

same test is running perfectly on android device . so it should run same as on IPhone and iPad. There should not be any difference in execuation.

### How to reproduce the bug.

This scenario should be there all some of the elements on iPhone not all elements.
Run any kind of automation script on iPhone with browser stack.

### Relevant log output

```typescript
There is no long for this bug. since the click command is executing but action for click command is not happening. Click does nothing and no error, no action ,just silently not executing click.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2021-11-11 10:53
> Same test running perfectly with android device. Is there any issue from browser stack or wdio?

Please reach out to the support team over at BrowserStack, thanks!

Have you tried a normal click command?

Do you have a reproducible example?

**Comment by opensourcesensor** [comment] 2021-11-11 13:55
Hi @christian-bromann , @vaibhavjagdale ,
since this week my tests are also unable to click elements on Iphone devices with WDIO and Saucelabs.
I will open a a issue and let you know if there are some updates!

BR

**Comment by gauravgandhi1315** [comment] 2021-11-11 14:48
Im able to click elements on iPhone devices with Saucelabs.

**Comment by opensourcesensor** [comment] 2021-11-11 14:55
@gauravgandhi1315  interesting!

Can you share us your capabilities?
Which appium version do you use?

Thanks!

**Comment by christian-bromann** [comment] 2021-11-22 10:24
@opensourcesensor any updates? Have you been able to create a minimal reproducible example?

**Comment by opensourcesensor** [comment] 2021-11-22 11:02
Hi @christian-bromann , yes. It was the error of the appium version. I changed it to Version 1.19.2 - then it works fine. 
I've already had a case like this where the appium connection to saucelabs only works with exactly one appium version, otherwise some elements cannot be clicked. well, now it works again.

**Comment by vaibhavjagdale** [comment] 2021-11-22 11:52
@opensourcesensor  That's great to know ! Thank you !!

**Comment by opensourcesensor** [comment] 2021-11-22 12:03
@vaibhavjagdale - yes -> Means if it not work I tried different Appium versions - dont know why, but it works. Last time it must be the version 1.22.0, this time 1.19.2. Hope this help you,
BR!

**Comment by christian-bromann** [comment] 2021-11-22 12:33
Thanks for letting us know, will close this issue then as there is nothing to do in WebdriverIO.

**Closed by christian-bromann** 2021-11-22 12:33 UTC
Labels: Bug 🐛, Reproducible Example Missing
