### ISSUE TITLE
Please support Mocha Option - "diff"

### ISSUE THREAD

**Issue by twang-bgl** [webdriverio/webdriverio#6853] opened 2021-05-13 00:56 UTC
**Is your feature request related to a problem? Please describe.**
When comparing two objects by using "chai-subset", if "diff" is true in mocha, the detailed differences will be displayed in the error message, but wdio does not support this option.

**Describe the solution you'd like**
Enable "diff" option in wido.conf.js -> "mochaOpts"

**Describe alternatives you've considered**
I am using "diff" and "chalk" packages to get the detailed differences and print them out with color 

**Additional context**
Thanks

**Comment by christian-bromann** [comment] 2021-05-13 12:13
Duplicate of #5035

I recommend to use WebdriverIOs built in [assertion library](https://webdriver.io/docs/api/expect-webdriverio) which already has support for it.

**Closed by christian-bromann** 2021-05-13 12:13 UTC
