### ISSUE TITLE
[🐛 Bug]: IsDisplayed and isExisting still not returning false when element not is available in dom

### ISSUE THREAD

**Issue by MaiMinh650** [webdriverio/webdriverio#11157] opened 2023-09-13 00:52 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.6.9

### Node.js Version

16.18.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{  
    browserName: 'chrome',
    browserVersion: 'latest',
    platformName: 'MacOS Ventura 13.5.2'
    
}
```

### What happened?

When I follow the example code in this comment: https://github.com/webdriverio/webdriverio/issues/10583?fbclid=IwAR1AUt8fxX4JVt_SzZOJDaS8UDoI_x1bzS9XxCgGztCd66rHJ6J4jtvu1FA#issuecomment-1598033210, isDisplayed() and isExisting() are not working as expected when 'implicitWait' attribute in the config file is greater than 0, The unexisted element when using isExisting() will return timeout error instead of false. isDisplayed() and isExisting() are only working as expected when when 'implicitWait' attribute in the config file is equal to 0

### What is your expected behavior?

The unexisted element when using isExisting() should return false instead of timeout error

### How to reproduce the bug.

       // In the config file, implicitWait : 10000

       describe('verify is existing is displayed', () => {
          it('verify is existing is displayed', async () => {
              await browser.url('https://google.com');
             const el1 =  await $('//textarea[@name="q"]');
             const el2 =  await $('//textarea[@name="q123"]');
             console.log(`text area with name=q is displayed: ${await el1.isDisplayed()}`)
             console.log(`text area with name=q is existing: ${await el1.isExisting()}`)
             console.log(`text area with name=q123 is displayed: ${await el2.isDisplayed()}`)
             console.log(`text area with name=q123 is existing: ${await el2.isExisting()}`)

       //------------ Your Example ---------//
       await browser.url('https://webdriver.io/')
       let element=await $("//a[contains(text(),'Docsmaster')]");
       console.log(`element with selector '//a[contains(text(),'Docsmaster')]' is displayed: ${await element.isDisplayed()}`)
       console.log(`element with selector '//a[contains(text(),'Docsmaster')]' is existing: ${await element.isExisting()}`)

       if(await $("//a[contains(text(),'Docsmaster')]").isExisting()){
        console.log(await $("//a[contains(text(),'Docsmaster')]").isExisting())
        }

    })
})

### Relevant log output

```typescript
"spec" Reporter:
------------------------------------------------------------------
[chrome 117.0.0.0 darwin #0-0] Running: chrome (v117.0.0.0) on darwin
[chrome 117.0.0.0 darwin #0-0] Session ID: 9a45cf2a-4321-4501-a218-c3580225ce42
[chrome 117.0.0.0 darwin #0-0]
[chrome 117.0.0.0 darwin #0-0] » /tests/demo/example.ts
[chrome 117.0.0.0 darwin #0-0] verify is existing is displayed
[chrome 117.0.0.0 darwin #0-0]    [FAIL] verify is existing is displayed
[chrome 117.0.0.0 darwin #0-0]    [FAIL] verify is existing is displayed
[chrome 117.0.0.0 darwin #0-0]
[chrome 117.0.0.0 darwin #0-0] 1 failing (23.6s)
[chrome 117.0.0.0 darwin #0-0]
[chrome 117.0.0.0 darwin #0-0] 1) verify is existing is displayed verify is existing is displayed
[chrome 117.0.0.0 darwin #0-0] Waiting for selector .//textarea[@name="q123"] failed: Waiting failed: 10000ms exceeded
[chrome 117.0.0.0 darwin #0-0] Waiting for selector .//textarea[@name="q123"] failed: Waiting failed: 10000ms exceeded
[chrome 117.0.0.0 darwin #0-0] TimeoutError: Waiting for selector .//textarea[@name="q123"] failed: Waiting failed: 10000ms exceeded
[chrome 117.0.0.0 darwin #0-0]     at listOnTimeout (node:internal/timers:559:17)
[chrome 117.0.0.0 darwin #0-0]     at processTimers (node:internal/timers:502:7)
[chrome 117.0.0.0 darwin #0-0]
[chrome 117.0.0.0 darwin #0-0] 2) verify is existing is displayed verify is existing is displayed
[chrome 117.0.0.0 darwin #0-0] Waiting for selector .//textarea[@name="q123"] failed: Waiting failed: 10000ms exceeded
[chrome 117.0.0.0 darwin #0-0] Waiting for selector .//textarea[@name="q123"] failed: Waiting failed: 10000ms exceeded
[chrome 117.0.0.0 darwin #0-0] TimeoutError: Waiting for selector .//textarea[@name="q123"] failed: Waiting failed: 10000ms exceeded
[chrome 117.0.0.0 darwin #0-0]     at listOnTimeout (node:internal/timers:559:17)
[chrome 117.0.0.0 darwin #0-0]     at processTimers (node:internal/timers:502:7)


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:57
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by tamil777selvan** [comment] 2023-09-13 14:43
Hi @MaiMinh650, I attempted to execute the provided code using the latest version of WebDriver, but I couldn't replicate the error. It appears that you are using an older version. Could you please give it a try with the latest version?

![Screenshot 2023-09-13 at 8 13 05 PM](https://github.com/webdriverio/webdriverio/assets/49207189/d29e88cc-fe29-4be1-b0ce-2e82d39c7bae)

**Comment by erwinheitzman** [comment] 2023-09-18 23:00
I cannot reproduce this either, closing this but feel free to re-open if you have a reproducible example.

**Closed by erwinheitzman** 2023-09-18 23:00 UTC
Labels: Bug 🐛, Reproducible Example Missing
