### ISSUE TITLE
[🐛 Bug]: Allure Reporter / Retries not listed anymore.

### ISSUE THREAD

**Issue by muhserks** [webdriverio/webdriverio#9993] opened 2023-03-17 10:08 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.5.6

### Node.js Version

18

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
"@wdio/allure-reporter": "^8.5.0"
"@wdio/mocha-framework": "^8.5.6",
```

### What happened?

It seems that the allure reporter creates a new step instead of a new entry in the "Retries" Tab (if a test fails and retries are configure in wdio).
I believe this also leads to unstable builds in jenkins.
In previuos version (wdio7 and corresponding allure reporter version) retries were listed in the "Retries" Tab and did not made jenkins unstable.

I attached some screenshots for comparison.
![Allure-8 5 0](https://user-images.githubusercontent.com/91063753/225873424-4ac12055-a4c4-4676-b4bd-8eee4dc36333.png)
![Allure-7 26 0_Screenshot_1](https://user-images.githubusercontent.com/91063753/225873458-875f571b-744b-44e3-996b-a80393f02511.png)
![Allure-7 26 0_Screenshot_2](https://user-images.githubusercontent.com/91063753/225873488-faba1f48-0c63-40e6-883b-7fedd0501a63.png)

### What is your expected behavior?

Retries are correctly listed in the retry tab and hopefully the publisher will not consider it as unstable anymore.

### How to reproduce the bug.

Let a test fail and look into the generated allure report.

### Relevant log output

```typescript
n.a.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2023-03-17 16:13
Hey,
thanks for filing the issue. This seems indeed like a regression from the v1 Allure reporter integration. We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by BorisOsipov** [comment] 2023-03-17 20:00
cc @epszaw

**Comment by praveendvd** [comment] 2023-03-19 14:35
@christian-bromann  i will take this up

**Comment by praveendvd** [comment] 2023-03-26 19:22
@muhserks is it test wise retry or step wise retry ? could u add a reproducible example ?

**Comment by praveendvd** [comment] 2023-03-26 21:12
@muhserks  node_modules\@wdio\allure-reporter\build\reporter.js

            this._state.currentTest.historyId=cid;
            this._state.currentTest.testCaseId=cid;
            
  to line 170  , could you check this is the expected behavior ? 
  
  This is the fixed behavior , do you expect something in history tab ?  
  
![image](https://user-images.githubusercontent.com/45095911/227804873-11de1b86-404f-44e3-9911-fe7169ba6f1d.png)

**Comment by praveendvd** [comment] 2023-03-26 21:12
cc : @christian-bromann

**Comment by christian-bromann** [comment] 2023-03-26 21:19
I am not familiar with the Allure reporter, maybe @epszaw has some insights

**Comment by lamkovod** [comment] 2023-03-27 10:34
@praveendvd History tab is used to display previous test runs(suite runs), so I don't think that retries should be added to the history.

**Comment by praveendvd** [comment] 2023-03-27 11:14
@lamkovod like it's not added , but i tried running the suite multiple times and history was still empty , will check if the reason is to be that cid , changes each time , i will try to see if cid changes each time , if so will be adding md5 of testcase name instead of cid and see how it behaves

**Comment by muhserks** [comment] 2023-03-29 15:55
@praveendvd Sorry, I am short on time atm. It can take quite some days until I could provide an example ...

But I gave your latest changes a quick try.
I ran the tests with 2 browsers, chrome & firefox. 
The main list on the left side shows only the steps from chrome, the steps from firefox are listed now in the retries tab (of the chrome steps).
I guess "grouping" should also be done by browser. 

Concerning the history, I never really looked into tab, so I cannot really answer what is expected there ... but I would stick to @lamkovod answer.

**Comment by praveendvd** [comment] 2023-03-29 16:04
@muhserks thank you for getting back on this , i changed , the approach by using hash of suite name and test name instead of cid , could u check the pr and see if that fix

**Comment by christian-bromann** [comment] 2023-03-29 21:58
> could u check the pr

Do you have a link to the PR?

**Comment by muhserks** [comment] 2023-03-30 05:45
@praveendvd I took the changes from https://github.com/webdriverio/webdriverio/pull/10053
The result of "using hash of suite name and test name" is that if you run the tests with 2 browsers (means each test runs in both browsers), the steps from second browser will be listed as retry, because it has same suite and test name.
Basically, browser name/version is missing in the hash, I guess.

So, things are different now but not working as they should be. Now you probably get green runs via the jenkins allure publisher, even though tests were failing in one browser.

**Comment by praveendvd** [comment] 2023-03-30 05:58
@christian-bromann https://github.com/webdriverio/webdriverio/pull/10053

**Comment by praveendvd** [comment] 2023-03-30 08:51
@christian-bromann and @BorisOsipov  will cid be unique for each instance when its multi remote with different browsers ? if i use browser name then if we run same suite across same browser muitlple time the same behavior will still be there .

**Comment by BorisOsipov** [comment] 2023-03-30 08:59
@praveendvd You don't need 'cid'. You can't use 'cid' in 'historyId' generation. 

As @muhserks mentioned, we have to add the browser name to 'historyId' generation, along with **all test parameters**. 

The Allure1 generator generates 'historyId' when it is missing, like this - https://github.com/allure-framework/allure2/blob/master/allure-generator/src/main/java/io/qameta/allure/allure1/Allure1Plugin.java#L494

We should make our 'historyId' generation as close as possible to that implementation.

**Comment by praveendvd** [comment] 2023-03-30 10:08
@BorisOsipov  but as mentioned if we run same suite in same browser n times , the behaviour of test being added to retry tab will still remain . That's why it would be nice if we can separate each run too else we have to find too many unique attributes

**Comment by praveendvd** [comment] 2023-03-30 10:09
@BorisOsipov i was thinking something like md5(testname+suite name+cid)

**Comment by BorisOsipov** [comment] 2023-03-30 10:52
@praveendvd, once again, "cid" is a random value. "historyId" is a unique and reproducible identifier for a specific test. "historyId" must remain the same for a test over time.

Question: How do you ensure that "historyId" is both unique and reproducible if you use a random "cid" for its generation?

Could you please take a look at the Java implementation I mentioned earlier? You just need to backport it to the reporter. 
Nothing more is required

**Comment by praveendvd** [comment] 2023-03-30 10:59
@BorisOsipov my question was , was cid unique for each run , of not cid what else would we use to uniquely identify runs with same suite name , test name , and browser name , 

People might run same suite in parallel across same browser for some performance test

**Comment by BorisOsipov** [comment] 2023-03-30 11:09
@praveendvd

>People might run same suite in parallel across same browser for some performance test

I don't remember that any one registered such issue since wdio 4. I prefer not to solve issues that have never happened.

>my question was , was cid unique for each run , if not cid, what else would we use to uniquely identify runs with same suite name , test name , and browser name ,

It is not our problem. If the user wants to make a unique test, they can add a parameter with any identifier they want using `addArgument(name, value)`. It is our responsibility to make it possible by generating the correct historyId from the full test name and parameters user given.

**Comment by christian-bromann** [comment] 2023-04-10 19:40
No, we can close this. If you like to raise a PR with a test for this, feel free. Thanks for the ping.

**Closed by christian-bromann** 2023-04-10 19:40 UTC
Labels: Bug 🐛, help wanted, good first pick

**Comment by maksym-alavatskyi** [comment] 2024-01-18 11:29
Curious, why this change is not in the main branch anymore?
