### ISSUE TITLE
Allure option `useCucumberStepReporter: true` providing `undefined` status with skipped test

### ISSUE THREAD

**Issue by espekkaya** [webdriverio/webdriverio#4409] opened 2019-08-27 11:49 UTC
**Environment (please complete the following information):**
WebdriverIO version: 5.11.12
Mode: WDIO Testrunner
If WDIO Testrunner, running sync/async: [sync
Node.js version: 10.15.3
NPM version: 6.10.2
Browser name and version: Chrome 68
Platform name and version: Windows 10
Additional wdio packages used (if applicable): `@wdio/allure-reporter, @wdio/cucumber-framework`

**Describe the bug**
~When one test case failed, the other test cases skipped because of dependency. But I have generated report via allure report, the skipped test cases status is undefined.~
When the Allure report with the option `useCucumberStepReporter: true` is used, the status of a skipped test becomes `undefined`, then the `useCucumberStepReporter: true` is not provided the status of the skipped test is `skipped` which is correct.
~wdio v4 these test cases status is skipped.~ This worked correctly in WebdriverIO V4

**To Reproduce**
~Skipped any steps of test case.~

```js
exports.config = {
  //...
     reporters: [
        'spec',
        ['allure', {
            outputDir: '.tmp/allure-result',
            disableWebdriverStepsReporting: true,
            disableWebdriverScreenshotsReporting: true,
            useCucumberStepReporter: true
        }],
    ],
  //...
}
```

```bash
@feature-tag
Feature: Create passed feature
    the description

    @scenario-tag
    Scenario: Open website
        Given I open "http://webdriver.io/"
        Then the title would say "WebdriverIO · Next-gen WebDriver test framework for Node.js"

    @scenario-tag
    Scenario: Open other website
        Given I open "https://developer.mozilla.org/nl/"
        Then the title would say "MDN-webdocumenten"
```

```js
// Steps
import { Given,Then } from 'cucumber';

Given(/I open "(.*)"/, function (url) {
    return 'skipped';
});
Then(/the title would say "(.*)"/, title => {
    expect(browser.getTitle()).to.equal(title);
});
```

**Expected behavior**
Test case status is skipped not unknown like when the Allure option `useCucumberStepReporter: false`

**Updated issue with proper information about the issue**

**Comment by wswebcreation** [comment] 2019-08-27 11:59
@espekkaya 

Can you provide a reproducible example (project) regarding the dependency you refer to?

**Comment by espekkaya** [comment] 2019-08-27 12:56
Hello @wswebcreation ,

You can find out [demo project](https://github.com/espekkaya/webdriverio-v5-cucumber-typescript).

Just run in e2e folder at terminal.

```
npm run test
npm run  report:generate
npm run report:open
```

Thank you.

**Comment by wswebcreation** [comment] 2019-08-27 13:58
@espekkaya 

Checking the project now but I'm getting this error and when I check the your bug and this project I don't see a relation between them.

```log
[0-0] RUNNING in chrome - /Web/Features/Google/Google.feature
[0-1] RUNNING in chrome - /Web/Features/Google1/Google.feature
0-1 worker error { name: 'TSError',
  message:
   '⨯ Unable to compile TypeScript:\nWeb/Shared/World.ts(6,18): error TS2350: Only a void function can be called with the \'new\' keyword.\n',
  stack:
   'TSError: ⨯ Unable to compile TypeScript:\nWeb/Shared/World.ts(6,18): error TS2350: Only a void function can be called with the \'new\' keyword.\n\n    at createTSError (/Users/wimselles/Git/webdriverio-v5-cucumber-typescript/e2e/node_modules/ts-node/src/index.ts:245:12)\n    at reportTSError (/Users/wimselles/Git/webdriverio-v5-cucumber-typescript/e2e/node_modules/ts-node/src/index.ts:249:19)\n    at getOutput (/Users/wimselles/Git/webdriverio-v5-cucumber-typescript/e2e/node_modules/ts-node/src/index.ts:362:34)\n    at Object.compile (/Users/wimselles/Git/webdriverio-v5-cucumber-typescript/e2e/node_modules/ts-node/src/index.ts:395:32)\n    at Module.m._compile (/Users/wimselles/Git/webdriverio-v5-cucumber-typescript/e2e/node_modules/ts-node/src/index.ts:473:43)\n    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at require.extensions.(anonymous function) (/Users/wimselles/Git/webdriverio-v5-cucumber-typescript/e2e/node_modules/ts-node/src/index.ts:476:12)\n    at Object.require.extensions.(anonymous function) [as .ts] (/Users/wimselles/Git/webdriverio-v5-cucumber-typescript/e2e/node_modules/ts-node/src/index.ts:476:12)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Module._load (internal/modules/cjs/loader.js:530:3)\n    at Function.hookedLoader [as _load] (/Users/wimselles/Git/webdriverio-v5-cucumber-typescript/e2e/node_modules/mockery/mockery.js:111:12)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at requiredFiles.forEach.codePath (/Users/wimselles/Git/webdriverio-v5-cucumber-typescript/e2e/node_modules/@wdio/cucumber-framework/build/index.js:133:7)\n    at Array.forEach (<anonymous>)' }
0-0 worker error { name: 'TSError',
  message:
   '⨯ Unable to compile TypeScript:\nWeb/Shared/World.ts(6,18): error TS2350: Only a void function can be called with the \'new\' keyword.\n',
  stack:
   'TSError: ⨯ Unable to compile TypeScript:\nWeb/Shared/World.ts(6,18): error TS2350: Only a void function can be called with the \'new\' keyword.\n\n    at createTSError (/Users/wimselles/Git/webdriverio-v5-cucumber-typescript/e2e/node_modules/ts-node/src/index.ts:245:12)\n    at reportTSError (/Users/wimselles/Git/webdriverio-v5-cucumber-typescript/e2e/node_modules/ts-node/src/index.ts:249:19)\n    at getOutput (/Users/wimselles/Git/webdriverio-v5-cucumber-typescript/e2e/node_modules/ts-node/src/index.ts:362:34)\n    at Object.compile (/Users/wimselles/Git/webdriverio-v5-cucumber-typescript/e2e/node_modules/ts-node/src/index.ts:395:32)\n    at Module.m._compile (/Users/wimselles/Git/webdriverio-v5-cucumber-typescript/e2e/node_modules/ts-node/src/index.ts:473:43)\n    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at require.extensions.(anonymous function) (/Users/wimselles/Git/webdriverio-v5-cucumber-typescript/e2e/node_modules/ts-node/src/index.ts:476:12)\n    at Object.require.extensions.(anonymous function) [as .ts] (/Users/wimselles/Git/webdriverio-v5-cucumber-typescript/e2e/node_modules/ts-node/src/index.ts:476:12)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Module._load (internal/modules/cjs/loader.js:530:3)\n    at Function.hookedLoader [as _load] (/Users/wimselles/Git/webdriverio-v5-cucumber-typescript/e2e/node_modules/mockery/mockery.js:111:12)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at requiredFiles.forEach.codePath (/Users/wimselles/Git/webdriverio-v5-cucumber-typescript/e2e/node_modules/@wdio/cucumber-framework/build/index.js:133:7)\n    at Array.forEach (<anonymous>)' }

```

**Comment by espekkaya** [comment] 2019-08-28 06:56
Hello @wswebcreation ,
It's so weird I'm not getting that error. Anyway I have changed some methods in there. Please try again.

**Comment by wswebcreation** [comment] 2019-08-28 07:29
Hi @espekkaya 

I pulled the latest changes but I still get the error. But I still don't see a diff in the project that explains this

> When one test case failed, the other test cases skipped because of dependency.

Can you please explain what you mean with this, does it happen for scenario's within 1 feature, does it happen when you have multiple features and so on

**Comment by espekkaya** [comment] 2019-08-28 07:46
Hi @wswebcreation,

I'm sorry for not running demo project.

Actually the sceneario is simple. 

1. Just add any step (Given, When or Then) `return "skipped";`
2. Generate Allure report
3. Open report and you should see the test case status is unknown actually it's skipped scenerio insted of unknown.

**Comment by wswebcreation** [comment] 2019-08-28 08:08
@espekkaya 

Hmm, I don't know what the issue it, when I install the allure-report and run my tests

```bash
@feature-tag
Feature: Create passed feature
    the description

    @scenario-tag
    Scenario: Open website
        Given I open "http://webdriver.io/"
        Then the title would say "WebdriverIO · Next-gen WebDriver test framework for Node.js"

    @scenario-tag
    Scenario: Open other website
        Given I open "https://developer.mozilla.org/nl/"
        Then the title would say "MDN-webdocumenten"
```

 I get this, meaning, I have a skipped status

```js
// Steps
import { Given,Then } from 'cucumber';

Given(/I open "(.*)"/, function (url) {
    return 'skipped';
});
Then(/the title would say "(.*)"/, title => {
    expect(browser.getTitle()).to.equal(title);
});
```
![image](https://user-images.githubusercontent.com/11979740/63837331-933e3a00-c97b-11e9-8e76-22d1c941b6e1.png)

**Comment by espekkaya** [comment] 2019-08-28 08:16
@wswebcreation can you please add `return "skipped";`  only second step?

Step 1 : passed
Step 2: skipped

**Comment by wswebcreation** [comment] 2019-08-28 08:22
Same stuff, only with 2 passed steps and 2 skipped

![image](https://user-images.githubusercontent.com/11979740/63838264-52472500-c97d-11e9-8bf3-948bef2dbf08.png)


![image](https://user-images.githubusercontent.com/11979740/63838297-5e32e700-c97d-11e9-9ff0-afc9f20e819d.png)


Even with multiple feature files I don't have a problem

![image](https://user-images.githubusercontent.com/11979740/63838382-8d495880-c97d-11e9-8a7d-b56c909edb09.png)


They only advice I can give you is to update to the latest version if WebdriverIO and all dependencies (I'm on 5.12.5).

Going to close this issue because I can't reproduce it

**Comment by espekkaya** [comment] 2019-08-28 08:53
Hi @wswebcreation , If It's posibble that can you share testsuite.xml files here?

I upgraded latest version of all packages, but my situation is unfortunetly same :s

Here is my packages versions:

```
"dependencies": {
    "@types/archiver": "^3.0.0",
    "@types/chai": "^4.2.0",
    "@types/cucumber": "^4.0.7",
    "@types/fs-extra": "^8.0.0",
    "@types/mysql2": "github:types/mysql2",
    "@types/node": "^12.7.2",
    "@types/nodemailer": "^6.2.1",
    "@types/sprintf-js": "^1.1.2",
    "@types/underscore": "^1.9.2",
    "@types/uuid": "^3.4.5",
    "@types/xml2js": "^0.4.4",
    "@wdio/allure-reporter": "^5.12.1",
    "@wdio/cli": "^5.12.5",
    "@wdio/cucumber-framework": "^5.12.3",
    "@wdio/local-runner": "^5.12.5",
    "@wdio/selenium-standalone-service": "^5.12.1",
    "@wdio/spec-reporter": "^5.12.1",
    "@wdio/sync": "^5.12.3",
    "allure-commandline": "^2.9.0",
    "appium-controller": "^1.1.6",
    "archiver": "^3.1.1",
    "browser-detect": "^0.2.28",
    "chai": "^4.2.0",
    "fs-extra": "^8.1.0",
    "moment": "^2.24.0",
    "mysql2": "^1.7.0",
    "nodemailer": "^6.3.0",
    "sprintf-js": "^1.1.2",
    "ts-node": "^8.3.0",
    "tsconfig-paths": "^3.8.0",
    "typescript": "^3.5.3",
    "underscore": "^1.9.1",
    "uuid": "^3.3.3",
    "webdriverio": "^5.12.5",
    "xml2js": "^0.4.19"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^1.13.0",
    "@typescript-eslint/parser": "^1.13.0",
    "eslint": "^6.2.2",
    "eslint-config-standard": "^13.0.1",
    "eslint-plugin-cucumber": "^1.2.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-node": "^9.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "eslint-plugin-wdio": "^5.12.1",
    "husky": "^3.0.4"
  },
```

![Screenshot](https://user-images.githubusercontent.com/10170737/63840781-49a91b80-c98a-11e9-8aca-c7ea1b8caf5a.png)

**Comment by espekkaya** [comment] 2019-08-28 08:55
And my testsuite.xml file looks like;

 ```
<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1566981951331' stop='1566981960883'>
    <name>EKIP projesi kullanıcı giriş</name>
    <title>EKIP projesi kullanıcı giriş</title>
    <test-cases>
        <test-case start='1566981952741' status='undefined'>
            <name>Kullanıcı sisteme giriş</name>
            <title>Kullanıcı sisteme giriş</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
                <label name='testId' value='YG2-863'/>
                <label name='severity' value='blocker'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome'/>
            </parameters>
            <steps>
                <step start='1566981952751' status='passed' stop='1566981952755'>
                    <name>Given EKIP - Kullanıcı giriş senaryo bilgileri tanımlanır.</name>
                    <title>Given EKIP - Kullanıcı giriş senaryo bilgileri tanımlanır.</title>
                    <attachments/>
                    <steps/>
                </step>
                <step start='1566981952756' status='passed' stop='1566981955405'>
                    <name>Given İlgili "https://test-ekip.csb.gov.tr/DashBoard/Board" link açılır.</name>
                    <title>Given İlgili "https://test-ekip.csb.gov.tr/DashBoard/Board" link açılır.</title>
                    <attachments/>
                    <steps/>
                </step>
                <step start='1566981955405' status='passed' stop='1566981957023'>
                    <name>Given EKIP - Kullanıcı Giriş butonuna tıklar.</name>
                    <title>Given EKIP - Kullanıcı Giriş butonuna tıklar.</title>
                    <attachments/>
                    <steps/>
                </step>
                <step start='1566981957023' status='canceled' stop='1566981957025'>
                    <name>Given EKIP - Kullanıcı adı "test_otomasyon" ve şifre "qwe.1234" ile sisteme giriş yapılır.</name>
                    <title>Given EKIP - Kullanıcı adı "test_otomasyon" ve şifre "qwe.1234" ile sisteme giriş yapılır.</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
        </test-case>
        <test-case start='1566981957029' status='undefined'>
            <name>Prod - Kullanıcı sisteme giriş</name>
            <title>Prod - Kullanıcı sisteme giriş</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
                <label name='testId' value='YG2-863'/>
                <label name='severity' value='blocker'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome'/>
            </parameters>
            <steps>
                <step start='1566981957031' status='passed' stop='1566981957031'>
                    <name>Given EKIP - Kullanıcı giriş senaryo bilgileri tanımlanır.</name>
                    <title>Given EKIP - Kullanıcı giriş senaryo bilgileri tanımlanır.</title>
                    <attachments/>
                    <steps/>
                </step>
                <step start='1566981957032' status='passed' stop='1566981959350'>
                    <name>Given İlgili "https://ekip.csb.gov.tr/DashBoard/Board" link açılır.</name>
                    <title>Given İlgili "https://ekip.csb.gov.tr/DashBoard/Board" link açılır.</title>
                    <attachments/>
                    <steps/>
                </step>
                <step start='1566981959351' status='passed' stop='1566981960879'>
                    <name>Given EKIP - Kullanıcı Giriş butonuna tıklar.</name>
                    <title>Given EKIP - Kullanıcı Giriş butonuna tıklar.</title>
                    <attachments/>
                    <steps/>
                </step>
                <step start='1566981960879' status='canceled' stop='1566981960881'>
                    <name>Given EKIP - Kullanıcı adı "test_otomasyon" ve şifre "qwe.1234" ile sisteme giriş yapılır.</name>
                    <title>Given EKIP - Kullanıcı adı "test_otomasyon" ve şifre "qwe.1234" ile sisteme giriş yapılır.</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
        </test-case>
    </test-cases>
</ns2:test-suite>
```

**Comment by wswebcreation** [comment] 2019-08-28 08:57
This is my XML

```xml
<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1566982549521' stop='1566982551048'>
    <name>Create passed feature: Open other website</name>
    <title>Create passed feature: Open other website</title>
    <test-cases>
        <test-case start='1566982549623' status='passed' stop='1566982551046'>
            <name>Given I open "https://developer.mozilla.org/nl/"</name>
            <title>Given I open "https://developer.mozilla.org/nl/"</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='googlechrome'/>
            </parameters>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1566982551046' status='pending' stop='1566982551047'>
            <name>Then the title would say "MDN-webdocumenten"</name>
            <title>Then the title would say "MDN-webdocumenten"</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='googlechrome'/>
            </parameters>
            <steps/>
            <attachments/>
        </test-case>
    </test-cases>
</ns2:test-suite>
```

**Comment by wswebcreation** [comment] 2019-08-28 08:59
Hmm, it looks like the setup of the xml is different

**Comment by christian-bromann** [comment] 2019-08-28 09:06
@espekkaya if you update your packages please make sure you delete your package-lock.json so NPM actually fetches latest packages

**Comment by espekkaya** [comment] 2019-08-28 11:20
Hello @christian-bromann and @wswebcreation ,

Finally I have figured the problem out.

The problem is that allure report configuration. When I set `useCucumberStepReporter: true` the test case status is unknown.

```
        ['allure', {
            outputDir: ConfigUtils.Paths.allureResult,
            disableWebdriverStepsReporting: true, // this is needed for cucumber reporter to work correctly
            disableWebdriverScreenshotsReporting: false, // needed for browser.saveScreenshot() in hooks
            useCucumberStepReporter: true, // this does literally nothing right n
        }]
```

But When I have removed  `` useCucumberStepReporter: true `` line, test case status is skipped.

And also created xml files also changing. 

You can see that below screenshot, if you removed ``useCucumberStepReporter: true `` that line, your test step is not sorted.

![screenshot](https://user-images.githubusercontent.com/10170737/63851264-94cd2980-c99e-11e9-8382-ef584b5c22b6.png)

**Comment by christian-bromann** [comment] 2019-08-28 11:34
@espekkaya any suggestion how to improve this problem on our side?

**Comment by espekkaya** [comment] 2019-08-28 11:47
@christian-bromann , I think that it should be nice to maintain same standart of wdio v4 and wdio v5. 
I have no idea how it works "allure generate" command.

**Comment by christian-bromann** [comment] 2019-08-28 12:02
> I think that it should be nice to maintain same standart of wdio v4 and wdio v5.

Well we are far ahead of v4 and can't do this, especially given that we don't have the capabilities to do so

**Comment by espekkaya** [comment] 2019-08-28 12:18
Well you are right @christian-bromann. Thank you.

**Comment by espekkaya** [comment] 2019-08-29 07:14
Hello @wswebcreation ,
Would you mind reopen this issue?

Thank you.

**Comment by wswebcreation** [comment] 2019-08-29 07:24
Reopened issue with enough info about the bug

**Comment by christian-bromann** [comment] 2019-08-29 07:42
> Would you mind reopen this issue?

Can you describe in more detail the problem and what solution you would expect?

**Comment by espekkaya** [comment] 2019-08-29 08:19
The problem is : 
1. you set allure report configuration `` useCucumberStepReporter: true ``
2. any of your test step add ``return 'skipped'; `` code.
3. generate allure report and open
4. Allure report shows that corresponding test case status is unknown.

Expection : 

When allure report is created, the corresponding test case should be skipped.

**Comment by christian-bromann** [comment] 2019-08-29 09:10
This was introduced by #4220. @Kignuf can you elaborate why test cases are cancled in this case instead of skipped. Line of code in question: https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-allure-reporter/src/index.js#L139

**Comment by Kignuf** [comment] 2019-08-29 12:37
Hello, I remember discussing that point with @BorisOsipov 
The discussion can be found here:
https://github.com/webdriverio/webdriverio/pull/4220#discussion_r305049394

So apparently we followed allure's guidelines, but somehow this is causing unexpected trouble.

**Comment by christian-bromann** [comment] 2019-08-29 12:46
@BorisOsipov mind chiming in here?

**Comment by BorisOsipov** [comment] 2019-08-29 12:53
@christian-bromann it is just a bug with easy fix - use `skipped` status as it was in v4. 

@Kignuf can I ask you make PR for this?

**Comment by Kignuf** [comment] 2019-08-29 13:16
#4420

**Comment by christian-bromann** [comment] 2019-08-29 13:26
Thanks @Kignuf !

**Closed** 2019-08-29 13:25 UTC
Labels: Bug🐛, good first pick, help wanted
