### ISSUE TITLE
A list of companies which use WebdriverIO

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1000] opened 2016-01-08 16:34 UTC
It would be nice to add a list of companies which use WebdriverIO!

**Comment by christian-bromann** [comment] 2016-01-08 16:36
Absolutely! I already tweeted out to ping me if anyone uses WebdriverIO but there haven't been enough companies to show off. I will try it again.

**Comment by monolithed** [comment] 2016-01-08 17:03
![_ _mail ru](https://cloud.githubusercontent.com/assets/803674/12203973/a0c83248-b642-11e5-89d8-2dd00b5c296c.png)

Email service at [Mail.Ru](https://en.wikipedia.org/wiki/Mail.Ru)
*After a long research of modern frameworks for integration testing, we chose the WebdriverIO. At the moment, it meets all our criteria!* (Frontend team at Mail.Ru)

**Comment by mroien** [comment] 2016-01-08 17:14
We use WebdriverIO at http://www.tapqa.com/ for a client Cox Media Group. Love it and @christian-bromann is a great help ALL the time.

**Comment by tikohatico** [comment] 2016-01-09 16:30
WebdriverIO works with BDD at internetdevels.com as relayable and advanced automation tool.
(QA department)

**Comment by dedmau5** [comment] 2016-01-11 07:59
Been using WebdriverIO since may of 2015 at Thomas Cook Northern Europe. It is so easy to get things going and it is so reliable compared to several other frameworks out there. The api is super well organized and easy to find stuff in, and if you get stuck, the Gitter is awesome. We use WebdriverIO mainly for system regression testing on our internal and external web apps. Can't endorse this enough!

**Comment by pazone** [comment] 2016-01-11 09:47
[Yandex] (https://www.yandex.com)  is using wdio because of flexible plugin system and simple integration with other testing tools.

**Comment by anarwal** [comment] 2016-01-11 20:41
WebdriverIO is a powerful and advanced automation tool, which has helped us with ease of good and faster execution in moving from traditional selenium webdriver. We at Axway ( https://www.axway.com/en ) are using it for our UI Automation Testing,

**Comment by georgecrawford** [comment] 2016-01-13 13:15
We're just starting to use Webdriverio at the [Financial Times](http://ft.com), in particular to test the FT's [web app](http://app.ft.com). This presents particular challenges due to the interactive nature of the app, and its very complex single-page JS environment. The promises of Webdriverio v4 have enticed us to convert our large suite of legacy [Thucydides](http://www.thucydides.info) tests, written in a flaky and cumbersome Java codebase we all hate, to a much cleaner, terser pseudo-synchronous JS style with _far fewer_ lines of code, fewer hacks and greater stability.

Webdriverio is a comprehensive, well documented project with great coverage of the Selenium/Webdriver/Appium specs, as well as loads of very useful helper abstractions. @christian-bromann has been amazing to work with, providing fantastic support and encouraging a helpful community in general.

**Comment by dhoulker** [comment] 2016-01-13 16:02
At [Stage Two] (https://wearestagetwo.com) we use Webdriver.IO to automate as many of our tests as possible. The framework is great to work with, as is the support provided. 

The thing we've found most valuable is that with the [Cucumber boilerplate] (https://github.com/webdriverio/cucumber-boilerplate/) non technical members of the test team can write tests.

WebdriverIO is a great project which we are happy to endorse.

**Comment by kencheeto** [comment] 2016-01-13 19:57
We use webdriver.io in product engineering at [Zendesk](https://www.zendesk.com/).

**Comment by bonjonbovi87** [comment] 2016-01-13 21:43
Here at Nokia (formally Alcatel-Lucent), we execute tens of thousands of tests daily powered by WebdriverIO.  It was chosen based on its flexibility with other tools and ease of use, allowing us to build the framework we have today.

**Comment by kevinmcdonnell** [comment] 2016-01-14 22:12
We use WebdriverIO at https://www.learnosity.com

```At Learnosity we use WebdriverIO to execute hundreds of UI tests as part of our CI pipeline.

The framework is easy to use, and has proven to be extensive, flexible and reliable.

The active community behind the project makes it easy to overcome any obstacles which might be encountered.```

**Comment by jaroslav-kubicek** [comment] 2016-01-21 00:30
It's also used in [Socialbakers](http://www.socialbakers.com/)

**Comment by xeladotbe** [comment] 2016-01-23 15:13
We use WebdriverIO since november 2015 in order to support our 
QA department with automated frontend tests at 1&1.

**Comment by pimterry** [comment] 2016-01-25 16:42
[Build Focus](http://www.buildfocus.io) uses WebdriverIO for all its system testing. It's fantastic to use, far more reliable than the other JS options, and lets you write genuinely readable tests with minimum mess.

**Comment by sajjadhossain** [comment] 2016-01-26 03:10
THIS IS SIMLY THE FUTURE OF TESTING. EASY, OUT THE BOX, MADE BY COMMITTED DEVELOPERS AND TESTING EVANGELISTS!!!!

I am shouting this!

**Comment by lukluk** [comment] 2016-01-26 05:29
we at loket.com willing use that too

2016-01-26 10:10 GMT+07:00 Sajjad Hossain <notifications@github.com>:

> THIS IS SIMLY THE FUTURE OF TESTING. EASY, OUT THE BOX, MADE BY COMMITTED
> DEVELOPERS AND TESTING EVANGELISTS!!!!
>
> I am shouting this!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webdriverio/webdriverio/issues/1000#issuecomment-174793528>
> .
>



-- 
Lukluk Luhuring S. S.Kom, MT
Software Engineer / Seminar Speaker

**Comment by patthiel** [comment] 2016-01-26 21:34
We've just begun using WebdriverIO at [Urban Outfitters](http://www.urbanoutfitters.com/) and [Anthropologie](http://www.anthropologie.com) and are excited about building our integration testing framework using this great tool.

**Comment by bondarum** [comment] 2016-01-27 10:42
I use it at <a href="http://www.instapage.com">Instapage</a> Testing our application

**Comment by dcypherthis** [comment] 2016-02-01 16:12
We're using WebdriverIO at [Emma](http:/myemma.com) for our new JS-based integration testing framework.

**Comment by jonyet** [comment] 2016-02-04 03:14
Some of us at [Moxie](http://moxieusa.com/) have started to migrate to the gulp-webdriver framework for testing/continuous integration, and it's been very exciting. We already use gulp and jenkins for most of our build deployment for both internal and client applications, so it's nice to see that we will be able to easily take existing selenium experience and apply it to our preferred infrastructure

**Comment by Tyriont** [comment] 2016-02-12 21:13
We've integrated WebdriverIO into our automation testing at [1stdibs.com](www.1stdibs.com) which has been incredibly useful in creating clean, easy-to-read tests which are reliable and easy to maintain.  Easy to integrate with other testing tools we use, it clearly won out for us when we began converting an old Java-based testing library into JS.  The move from v2 to v3 only made things better and we're very excited for the future with v4.

**Comment by jordanQA** [comment] 2016-02-12 21:58
[Bambu by Sprout Social](https://getbambu.com/) has found our combination of WebdriverIO and Cucumber to be highly effective. The simplicity, documentation, and support from the community has allowed me to build up an automation suite without _any_ prior programming experience. Super excited for the future of WebdriverIO and automated testing in general.

**Comment by narainsagar** [comment] 2016-02-15 11:33
I am working as an Application Developer at [Recurship](recurship.com) and We're using Webdriver.io since Dec 2016. Currently, we've used webdriver.io in our automation codebase (i.e., web crawling) and We found this very clean, reliable and easy to integrate. I'm sure we'll use this for different purposes (testing, automation, etc) in future as well.

Cheers,
Narain S.

**Comment by xbill82** [comment] 2016-02-23 17:02
We're using WebdriverIO to test our back office at [Kuzzle.io](http://kuzzle.io/)

**Comment by christian-bromann** [comment] 2016-03-09 22:42
Thanks for all your contributions!

**Closed by christian-bromann** 2016-03-09 22:42 UTC

**Comment by BrendanJMurray** [comment] 2017-08-28 20:46
Ever since implementing WebdriverIO's visual regression service at [niche.com](url) we have been deploying with unprecedented confidence. These tests are a strong safety net that cover any potential gaps in the rest of our automated test suites.

**Comment by Shahunks** [comment] 2017-09-05 11:07
we have implemented wdio in zapty.com

**Comment by michaelHicks** [comment] 2017-11-10 13:50
We're using WebdriverIO (with Cucumber integration) at [Reserve](https://reserve.com) for our new JS-based integration testing framework.

**Comment by Vincento89** [comment] 2017-11-27 13:22
Hi everybody,
I am a great enthusiast of the WebdriverIO community. I know this is not the fully appropriate channel to ask things from you all but I have one specific problem via in the planning phase using webdriverio. How can I get in contact somehow one of you? For example email, chat or something.

**Comment by christian-bromann** [comment] 2017-11-27 13:24
> I know this is not the fully appropriate channel to ask things

Nope it is not

> How can I get in contact somehow one of you?

You probably have seen our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by iamdanchiv** [comment] 2018-01-04 06:12
Give a QA Engineer a web-automation framework and he might automate some tests. Give him [WebdriverIO](http://webdriver.io) and he will build a full-fledged, robust automation harness in a matter of days. All jokes aside, WebdriverIO was a blessing in disguise for us @[Avira](https://www.avira.com/). I'll never look back to other JS-based automation frameworks! ~[Dan Chivescu](https://www.instagram.com/iamdanchiv/), QA Lead @Avira

**Comment by mike-phillips** [comment] 2018-07-16 17:12
We started using WebdriverIO at [Affirm](https://www.affirm.com/) at the beginning of 2018. I recently wrote about our initial experience with it for Affirm's [tech blog](https://tech.affirm.com/end-to-end-testing-with-webdriverio-ba33847230ad). We've really enjoyed working with it.

**Comment by msohaib980** [comment] 2018-09-26 19:39
Just started with webdriverio last week. So far it great. Testing more and probably would migrate from webdriver java binding.

**Comment by pmerwin** [comment] 2018-09-26 20:36
cbtnuggets.com We've been on wdio for about 3 years, now on the latest v4 release , and we are currently in beta with vs 5... we love it and are ramping up even more day to day.

**Comment by smarigowda** [comment] 2019-01-31 11:10
Using Webdriver IO for the past 2 years. Excellent product, keep it up.

**Comment by kandarp1691** [comment] 2019-02-26 18:18
Hello. Been using WebdriverIO since a year at [Spectrum](https://www.spectrum.com/). Amazing framework and amazing support community. Keep it up guys :)

**Comment by larryg01** [comment] 2019-04-23 07:48
The framework of choice at Oxford University Press, I have been using webdriverio since 2016 and it has made life so much easier, especially now with v5, hats off to @christian-bromann and his crew who maintain and continualy support it, keep up the good work guys.

**Comment by sandikumar3** [comment] 2019-12-31 08:45
Why to Choose WebDriver IO for mobile automation ? If Yes, give valid reasons with examples

**Comment by christian-bromann** [comment] 2021-01-26 08:36
It's good to hear where WebdriverIO is used in the while. Please keep sharing!

**Comment by jonyet** [comment] 2021-01-26 16:01
since you're asking - wdio is being leveraged happily at both _CNN_ and _Huge Inc_ for a some years now :)
