### ISSUE TITLE
[Cucumber + v5] How to make hooks (afterStep) to run and finish before next step is executed?

### ISSUE THREAD

**Issue by jorgepOktana** [webdriverio/webdriverio#4207] opened 2019-07-16 20:31 UTC
Hi, 
Using wdio v4 + cucumber i used some afterSteps and know im trying to use the same in v5 + cucumber but it seems not to be running in order.
On my afterStep i have certain validations, i.e. if result.status === failed then i take a screenshot and do some extra steps, the problem is i am able to take the screenshot but im never able to do the extra steps because when the afterStep is executed, the runner is already executing another test case.

This is the code im using on my afterStep for the v5 (updated from v4):
```
afterStep: function (uri, feature, scenario, step, result) {
        if (result.status === 'failed') {
            const path =  './errorShots/'+Date.now()+'.png';
            browser.saveScreenshot(path);
            const allitems = $('.slds-icon-waffle');
            const logoutBut = $('button[title="Logout"]');
            const adminMenu = $('.oneAppLauncherItemList a[title="Parsable Admin"]');
            const sfProfilelogo = $('.profileTrigger');
            const sflogOut = $('.profile-link-label.logout.uiOutputURL');
            this.allitems.waitForDisplayed();
            this.allitems.click();
            this.adminMenu.waitForVisible();
            this.adminMenu.click();
            browser.pause(2000)
            if (this.logoutBut.isVisible()) {   
                this.logoutBut.click();
            }
            this.sfProfilelogo.waitForVisible();
            this.sfProfilelogo.click();
            this.sflogOut.waitForVisible();
            this.sflogOut.click();
        } 
        console.log(step.text + ' is ' + result.status)
    },
```
Sometimes it successfully takes the screenshot of the page with the error, but the other steps are never completed since when it gets there, the runner is already executing another test case..

**WebdriverIO version: v5.11.2
**Mode:Selenium Standalone
**If WDIO Testrunner, running sync/async: sync
**Node.js version: v10.16.0
**NPM version: v6.9.0
**Browser name and version: Chrome
**Platform name and version: MacOS

How can i ensure the afterStep is completely executed before the next step is executed? 
I have tried using promises but im not sure if i was implementing well, any help?

**Comment by wswebcreation** [comment] 2019-07-16 22:40
First of alles there is no afterStep anymore, with the migration from V4 to V5 CucumberJS was also updated. Please check the [blog post](https://webdriver.io/blog/2019/07/11/cucumberjs-v5-released.html) to see also the reference to the changes in CucumberJS.

Last but not least the payload from a after-hook changed. Please update all code according to the latest versions and please see if you still have an issue.

Going to close it now but feel free to reopen it if you migrated to all the latest versions and the issue is still there

**Comment by christian-bromann** [comment] 2019-07-16 23:38
> First of alles there is no afterStep anymore

According to the docs there is an afterStep hook: https://webdriver.io/docs/configurationfile.html

**Comment by jorgepOktana** [comment] 2019-07-16 23:46
@wswebcreation thanks for your reply but as @christian-bromann mentioned, there is an afterStep for cucumber on the wdio configuration file (according to wdio documentation).

If you see my code above im actually using and it triggers certain actions after every step but it doesnt wait for the hook to finish running to execute the next step... I already updated my code to be compatible to v5 but the actions seem to be called way too late for what I need.

**Comment by mgrybyk** [comment] 2019-07-16 23:55
This is how it currently designed in wdio, there are no issues with your code.

Should we change the behavior? @wswebcreation @christian-bromann

**Comment by christian-bromann** [comment] 2019-07-17 00:28
> Should we change the behavior?

Yeah, wdio cucumber hooks should run commands synchronously/respect promises like any other hooks too.

**Comment by jorgepOktana** [comment] 2019-07-23 14:24
Hello!, sorry to bother!
Is there any updates on this?

**Comment by christian-bromann** [comment] 2019-07-23 14:25
> Is there any updates on this?

As you can see you are welcome to contribute a bug fix.

**Comment by jorgepOktana** [comment] 2019-07-23 14:30
> > Is there any updates on this?
> 
> As you can see you are welcome to contribute a bug fix.

Would love to help but actually im not really a good coder, just a QA with the most basic programming knowledge...  and actually have no idea how to help with this :(

**Comment by christian-bromann** [comment] 2019-07-23 14:43
> and actually have no idea how to help with this :(

No problem. Then we have to wait until someone can tackle this. You will either see a pull request connected here or other communications in this thread.

**Comment by jorgepOktana** [comment] 2019-07-23 19:19
In the meantime i applied this workaround for my project:
* Use cucumber hooks on the stepDefinitions file:
```
After((scenario) => {
    const path =  './errorShots/'+Date.now()+'.png';
    if(scenario.result.status === 'failed'){
        browser.saveScreenshot(path);
        console.log('Screenshot location:', path);
        //do some more actions here (i call a function to logout from an API)
    }
    console.log('Scenario '+  scenario.pickle.name +' '+ scenario.result.status)
    browser.deleteCookies()
    browser.refresh()
    browser.pause(2000)
});
```

This is executes commands synchronously/respect promises.

**Comment by nextlevelbeard** [comment] 2019-07-24 15:36
@christian-bromann @mgrybyk

Isn't there a case for hooks to NOT wait for promises if the user wants to?

For instance: In the _beforeSenario_ (wdio hook for Cucumber) or in the _Before_ hook (Cucumber) we might want to start a request for an account creation. 

In this case, the hook should not wait for the promise to resolve.
A user can simply call browser.call if he wishes to have it that way.

This would allow to begin the test as quickly as possible, opening pages, performing actions, etc. and when the user really needs the account information, he can await for the account creation promise to be resolved. It his likely that by the time he calls await, the promise is long resolved since we've been performing actions in the meantime.

This is what I'm experiencing right now.

With the wdio hook _beforeScenario_:

```js
  beforeScenario: async function(uri, feature, scenario) {
    if (scenario.tags.find(tag => tag.name === "@newAccount")) {
      this.user = scenario.user = feature.user = createAccount(); // Start a request that creates an account
      // This hook will not resolve the promise before continuing, that's cool
      // ... but this.user, scenario.user or feature.user will not populate Cucumber's world
      // ... therefore the eventually created user will not be available in tests/steps
    }
  }
```

With the Cucumber hook _Before_
```js
  const { Before } = require("cucumber");

  Before("@newAccount", async function() {
    this.user = createAccount(); // Start a request that creates an account
    // This hook WILL resolve the promise before continuing, not cool!
    // This means I can't start opening the page, performing actions, etc until the new account promise is resolved
    // On the plus side, this.user is available for Cucumber steps, yay
});
```

**Comment by nextlevelbeard** [comment] 2019-07-24 15:57
> 
> 
> > Should we change the behavior?
> 
> Yeah, wdio cucumber hooks should run commands synchronously/respect promises like any other hooks too.

In that case, would declaring the hook an async function make it not resolve promises?

**Comment by jbblanchet** [comment] 2019-07-30 14:18
I've looked into this to try and find a solution, and I don't think there's a good generic (i.e. working for both sync/async) way to do this for all the hooks defined in the config file.

Cucumber itself offers only 4 hooks: `BeforeAll` (which maps to `before` in the config I think), `Before` (`beforeScenario`), `After` (`afterScenario`) and `AfterAll` (`after`). For these, we could try and use the hook mechanism of Cucumber to respect promises.

All the other hooks are only attached to fire-an-forget events fired by Cucumber. It might be possible to hack around it in sync mode (using browser.call?), but in async mode I don't see a way to make it work properly.

If you have ideas on how this could be done, I could put in some time. However in the meantime, I will document our project config file (which is running in async mode) to note that these hooks should not be used, and to use the Cucumber ones instead.

**Comment by miguelyoobic95** [comment] 2019-07-31 16:47
We have a similar issue, where we run some async code in the `beforeFeature` hook but the tests do not wait until this is finished before moving onto the first `Given` step of our feature. Sticking a `browser.pause(1500)` seems to be sufficient as a workaround but it would be great if the hooks respected the async/await order.

**Comment by mgrybyk** [comment] 2019-07-31 16:53
I think all the cucumber hooks work same way

**Comment by mgrybyk** [comment] 2019-07-31 20:56
Hey guys, here is update.

- before/after **scenario** will work!
- before/after **feature** won't work until it is implemented, however as a workaround we'll use BeforeAll / AfterAll that should work pretty much the same because wdio has dedicated worker per feature file
- before/after step hooks won't work until https://github.com/cucumber/cucumber-js/issues/997 is implemented

**Comment by mgrybyk** [comment] 2019-08-01 14:20
working is in progress, let's proceed conversation in PR https://github.com/webdriverio/webdriverio/pull/4288

**Closed by mgrybyk** 2019-08-01 14:20 UTC
Labels: Bug🐛, help wanted
