### ISSUE TITLE
Cannot read property 'log' of undefined

### ISSUE THREAD

**Issue by amadofelipe** [webdriverio/webdriverio#1243] opened 2016-04-12 14:25 UTC
When my test fails I am getting a stacktrace like the following, which is not very useful:

```
Cannot read property 'log' of undefined
running chrome
undefined: Cannot read property 'log' of undefined
    at Object.Future.wait (/home/felipeamado/kekanto-delivery/node_modules/fibers/future.js:449:15)
    at Object.setValue (/home/felipeamado/kekanto-delivery/node_modules/wdio-sync/build/index.js:345:27)
    at Utils.waitThenSetValue (/home/felipeamado/kekanto-delivery/tests/IntegrationTests/helper/utils.js:485:13)
    at CustomerAtStoreUser.saveUserFieldAndVerify (/home/felipeamado/kekanto-delivery/tests/IntegrationTests/helper/customerAtStoreUser.js:12:11)
    at Context.<anonymous> (/home/felipeamado/kekanto-delivery/tests/IntegrationTests/specs/storeuser.spec.js:67:33)
    at /home/felipeamado/kekanto-delivery/node_modules/wdio-sync/build/index.js:579:24
    - - - - -
    at elementIdValue("19", "39115543030") - setValue.js:67:80
```

I managed to get a much more useful message by commenting out these lines from the file https://github.com/webdriverio/webdriverio/blob/master/lib/webdriverio.js:

```
this.logger.log(`\tSaved screenshot: ${fileName}`)
this.emit('screenshot', {
    data: err.screenshot,
    filename: fileName,
    path: filePath
})
```

```
invalid element state: Element is not currently interactable and may not be manipulated
running chrome
RuntimeError: invalid element state: Element is not currently interactable and may not be manipulated
    at Object.Future.wait (/home/felipeamado/kekanto-delivery/node_modules/fibers/future.js:449:15)
    at Object.setValue (/home/felipeamado/kekanto-delivery/node_modules/wdio-sync/build/index.js:345:27)
    at Utils.waitThenSetValue (/home/felipeamado/kekanto-delivery/tests/IntegrationTests/helper/utils.js:485:13)
    at CustomerAtStoreUser.saveUserFieldAndVerify (/home/felipeamado/kekanto-delivery/tests/IntegrationTests/helper/customerAtStoreUser.js:12:11)
    at Context.<anonymous> (/home/felipeamado/kekanto-delivery/tests/IntegrationTests/specs/storeuser.spec.js:67:33)
    at /home/felipeamado/kekanto-delivery/node_modules/wdio-sync/build/index.js:579:24
    - - - - -
    at elementIdValue("19", "39115543030") - setValue.js:67:80
```

Thanks!

**Comment by christian-bromann** [comment] 2016-04-12 15:31
duplicate of #1180

**Closed by christian-bromann** 2016-04-12 15:31 UTC
