### ISSUE TITLE
[🐛 Bug]: improve compatibility when setting up in CJS projects

### ISSUE THREAD

**Issue by yogeshgadge** [webdriverio/webdriverio#10189] opened 2023-04-13 19:35 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.8.2

### Node.js Version

18

### Mode

WDIO Testrunner

### What happened?

Various typescript errors:-

1) [Unexpected token 'export'](https://github.com/yogeshgadge/ng-wdio/blob/main/errors.md#syntaxerror-unexpected-token-export)

```
SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module.m._compile (/Users/test/projects/opensource/ng-wdio/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/test/projects/opensource/ng-wdio/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

2) [module not found error](https://github.com/yogeshgadge/ng-wdio/blob/main/errors.md#module-not-found-error)

After adding a tsconfig.json , empty package.json with type: module and further simplification the error still persists

### What is your expected behavior?

After running `npm init wdio@latest` in fresh angular project it should just work

### How to reproduce the bug.

You may checkout the 3-4 commit history of the problem reproduction repo here https://github.com/yogeshgadge/ng-wdio/

But in a gist it is just creating a fresh angular project and then running `npm init edio@latest` and start running your tests.

I choose: devtools, jasmine and other options

```
? A project named "ng-wdio" was detected at 
"/Users/test/projects/opensource/ng-wdio", correct? Yes
? Where should your tests be launched? local - for e2e testing of web and mobile applications
? Where is your automation backend located? On my local machine
? Which framework do you want to use? Jasmine (https://jasmine.github.io/)
? Do you want to use a compiler? TypeScript (https://www.typescriptlang.org/)
? Do you want WebdriverIO to autogenerate some test files? Yes
? Where should these files be located? /Users/test/projects/opensource/ng-wdio/projects/my-ui-1/src/e2e
? Do you want to use page objects (https://martinfowler.com/bliki/PageObject.html)? Yes
? Where are your page objects located? /Users/test/projects/opensource/ng-wdio/projects/my-ui-1/src/e2e/pageobjects
? Which reporter do you want to use? spec
? Do you want to add a plugin to your test setup? angular-component-harnesses
? Do you want to add a service to your test setup? devtools
? What is the base url? http://localhost:4400
? Do you want me to run `npm install` Yes
```

### Relevant log output

```typescript
No logs but console output

Various errors.


> ng-wdio@0.0.0 wdio
> wdio run ./projects/my-ui-1/e2e/wdio.conf.ts


Execution of 1 workers started at 2023-04-13T17:48:24.102Z

2023-04-13T17:48:24.442Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-04-13T17:48:24.444Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-04-13T17:48:24.445Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./projects/my-ui-1/e2e/wdio.conf.ts
[0-0] 2023-04-13T17:48:25.448Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2023-04-13T17:48:25.956Z WARN @wdio/jasmine-framework: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
[0-0] `browser` object has only `capabilities` and some flags like `isMobile`.
[0-0] Helper files that use other `browser` commands have to be moved to `before` hook.
[0-0] Spec file(s): file:///Users/test/projects/opensource/ng-wdio/projects/my-ui-1/e2e/specs/login.page.ts
[0-0]  Error:  Error: Cannot find module '/Users/test/projects/opensource/ng-wdio/projects/my-ui-1/e2e/pageobjects/page' imported from /Users/test/projects/opensource/ng-wdio/projects/my-ui-1/e2e/specs/login.page.ts
[0-0]     at finalizeResolution (/Users/test/projects/opensource/ng-wdio/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:366:11)
[0-0]     at moduleResolve (/Users/test/projects/opensource/ng-wdio/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:801:10)
[0-0]     at Object.defaultResolve (/Users/test/projects/opensource/ng-wdio/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
[0-0]     at /Users/test/projects/opensource/ng-wdio/node_modules/ts-node/src/esm.ts:218:35
[0-0]     at entrypointFallback (/Users/test/projects/opensource/ng-wdio/node_modules/ts-node/src/esm.ts:168:34)
[0-0]     at /Users/test/projects/opensource/ng-wdio/node_modules/ts-node/src/esm.ts:217:14
[0-0]     at addShortCircuitFlag (/Users/test/projects/opensource/ng-wdio/node_modules/ts-node/src/esm.ts:409:21)
[0-0]     at resolve (/Users/test/projects/opensource/ng-wdio/node_modules/ts-node/src/esm.ts:197:12)
[0-0]     at nextResolve (node:internal/modules/esm/loader:163:28)
[0-0]     at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
[0-0] RUNNING in chrome - file:///projects/my-ui-1/e2e/specs/login.page.ts
[0-0] 2023-04-13T17:48:25.966Z INFO devtools:puppeteer: Initiate new session using the DevTools protocol
[0-0] 2023-04-13T17:48:25.968Z INFO devtools: Launch Google Chrome (undefined) with flags: --enable-automation --disable-popup-blocking --disable-extensions --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --no-default-browser-check --disable-hang-monitor --disable-prompt-on-repost --disable-client-side-phishing-detection --password-store=basic --use-mock-keychain --disable-component-extensions-with-background-pages --disable-breakpad --disable-dev-shm-usage --disable-ipc-flooding-protection --disable-renderer-backgrounding --force-fieldtrials=*BackgroundTracing/default/ --enable-features=NetworkService,NetworkServiceInProcess --disable-features=site-per-process,TranslateUI,BlinkGenPropertyTrees --window-position=0,0 --window-size=1200,900
[0-0] 2023-04-13T17:48:26.991Z INFO devtools: Connect Puppeteer with browser on port 51726
[0-0] 2023-04-13T17:48:27.372Z ERROR @wdio/runner: Error: Cannot find module '/Users/test/projects/opensource/ng-wdio/projects/my-ui-1/e2e/pageobjects/page' imported from /Users/test/projects/opensource/ng-wdio/projects/my-ui-1/e2e/specs/login.page.ts
[0-0]     at finalizeResolution (/Users/test/projects/opensource/ng-wdio/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:366:11)
[0-0]     at moduleResolve (/Users/test/projects/opensource/ng-wdio/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:801:10)
[0-0]     at Object.defaultResolve (/Users/test/projects/opensource/ng-wdio/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
[0-0]     at /Users/test/projects/opensource/ng-wdio/node_modules/ts-node/src/esm.ts:218:35
[0-0]     at entrypointFallback (/Users/test/projects/opensource/ng-wdio/node_modules/ts-node/src/esm.ts:168:34)
[0-0]     at /Users/test/projects/opensource/ng-wdio/node_modules/ts-node/src/esm.ts:217:14
[0-0]     at addShortCircuitFlag (/Users/test/projects/opensource/ng-wdio/node_modules/ts-node/src/esm.ts:409:21)
[0-0]     at resolve (/Users/test/projects/opensource/ng-wdio/node_modules/ts-node/src/esm.ts:197:12)
[0-0]     at nextResolve (node:internal/modules/esm/loader:163:28)
[0-0]     at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
[0-0]  Error:  Cannot find module '/Users/test/projects/opensource/ng-wdio/projects/my-ui-1/e2e/pageobjects/page' imported from /Users/test/projects/opensource/ng-wdio/projects/my-ui-1/e2e/specs/login.page.ts
[0-0] 2023-04-13T17:48:27.376Z INFO devtools: COMMAND deleteSession()
[0-0] 2023-04-13T17:48:27.379Z INFO devtools: RESULT null
[0-0] FAILED in chrome - file:///projects/my-ui-1/e2e/specs/login.page.ts
2023-04-13T17:48:27.503Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-04-13T17:48:27.503Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:03 

2023-04-13T17:48:27.505Z INFO @wdio/local-runner: Shutting down spawned worker
2023-04-13T17:48:27.757Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-04-13T17:48:27.757Z INFO @wdio/local-runner: shutting down
```

This following error is fixed after package.json change.

```
/Users/test/projects/opensource/ng-wdio/wdio.conf.ts:1
export const config = {
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module.m._compile (/Users/test/projects/opensource/ng-wdio/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/test/projects/opensource/ng-wdio/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by yogeshgadge** [comment] 2023-04-13 19:53
Update - another attempt - choosing N to the question of your project (existing pacjage.json) `"/Users/test/projects/opensource/ng-wdio", correct? No` fixes most the problems but the original problem remains.

**Comment by yogeshgadge** [comment] 2023-04-13 20:11
Another update after jumping around some workarounds in above I have it a try for 

`https://webdriver.io/docs/badisi-wdio-harness/` 

mjs not supported - wondering whAt option I should use?

```
Error:  Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/test/projects/opensource/ng-wdio/node_modules/@angular/material/fesm2015/datepicker/testing.mjs not supported.
```

**Comment by christian-bromann** [comment] 2023-04-13 20:58
Thanks for reporting!

I think the problem is not about Angular but with creating a WDIO setup inside of CJS projects. We should address this problem.

Any contributions that resolves the bug are highly appreciated. Don't expect this to be picked up by active contributors as they have their own priorities. If you depend on this bug to be fixed, your contribution is required. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by erwinheitzman** [comment] 2023-10-14 11:59
@yogeshgadge we have made tremendous improvements lately, could you check if your issues are resolved with the latest versions?

**Comment by erwinheitzman** [comment] 2023-10-27 21:17
Closing due to inactivity and this should all be solved by now

**Closed by erwinheitzman** 2023-10-27 21:17 UTC
Labels: Bug 🐛, help wanted, good first pick
