### ISSUE TITLE
Custom commands w/ wdio-sync do not work in watch-mode

### ISSUE THREAD

**Issue by flunderpero** [webdriverio/webdriverio#5418] opened 2020-05-19 15:47 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 6.1.12]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync]
 - **Browser name and version:** [e.g. Chrome 81]
 - **Platform name and version:** [e.g. OSX Catalina]

**Config of WebdriverIO**
```{
...
sync: true,
before: () => {
        browser.addCommand("open_page", function () => {
           browser.url("/common_start_uri")  // <- this returns a `Promise` if a test is re-run
        })
}
...
}
```

**Describe the bug**
We use a lot of custom commands like the one you see in the config above. And we use
`wdio-sync`. Everything works great, but now I wanted to use the `watch`-mode to reduce
turnaround times while developing. 
The first run is ok, but when the test is re-run because a file changed, wdio seems to have "forgotten" that it is supposed to be in `wdio-sync`-mode and *some* wdio-commands return a `Promise` instead. Regular test-code is fine, only sync-code in custom commands seems to be affected.
It *seems* as though only *some* commands cause trouble, namely `browser.url`. Most of our custom-commands work even if a spec is re-run.

**Comment by erwinheitzman** [comment] 2020-05-19 22:21
I'm not sure if the issue is that it's a Promise as instead I get an error when trying to reproduce this:
```
[firefox (unknown) #0-0] The "path" argument must be of type string. Received type undefined
[firefox (unknown) #0-0] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
```

**Comment by christian-bromann** [comment] 2020-05-20 09:46
It is hard to say if this is due to Fibers or a bug somewhere in the watch logic. Any help on this would be appreciated.

**Comment by dzsodzso63** [comment] 2020-06-11 13:11
I just opened this ticket, and it looks like they're related: https://github.com/webdriverio/webdriverio/issues/5481

Isn't the problem is that first run locally is through `devtoolsdriver` but all the consecutives are `protocolCommand`s, which needs `path` settings in options?

(I am referring @erwinheitzman experience here. Can you check what was your `path` option?)

**Comment by maxevilmind** [comment] 2020-06-15 14:35
I am experiencing a similar issue with wdio v5.23.0 when I have code in `before:` hook.
It looks like it always runs in async mode despite the fact I have @wdio/sync installed and don't use async functions. I am getting stuff like `TypeError: this.browser.$(...).click is not a function` and once I put `await` before, it passes.

**Comment by flunderpero** [comment] 2021-03-10 19:29
I finally gave `--watch` another try. I still run into the same problem with the latest version (7.0.7). My workaround was to write all custom commands with async instead of sync. Now everything works fine and given that we don't change our custom commands that often, the pain of writing in async is manageable. :-)

**Comment by christian-bromann** [comment] 2021-09-07 09:44
@flunderpero thanks for letting us know. I will close this issue as it is unlikely anyone will pick this bug up given it is related to sync mode execution which we depcrecated.

**Closed by christian-bromann** 2021-09-07 09:44 UTC
Labels: Bug🐛, Needs Investigation, help wanted
