### ISSUE TITLE
[🐛 Bug]: Devtools does not work when wdio-video-reporter is enabled

### ISSUE THREAD

**Issue by owens-ben** [webdriverio/webdriverio#7855] opened 2021-12-30 10:40 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.7.5

### Node.js Version

v14.17.3

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    maxInstances: 1,
    browserName: 'chrome',
    acceptInsecureCerts: true,
    'goog:chromeOptions': {
      args: ['--disable-gpu', '--window-size=1600,1200', '--no-sandbox', '--disable-dev-shm-usage'],
    },
  },
```

### What happened?

When wdio-video-reporter is enabled, all devtools functions throw:

`TypeError: browser.getMetrics is not a function`
`TypeError: browser.getPerformanceScore is not a function`
etc

Commenting out the video reporter solves the issue.

### What is your expected behavior?

Either have both work together, or a way to temporarily disable the video reporter while the performance tests are running.

### How to reproduce the bug.

Use the example code:

https://webdriver.io/docs/devtools-service/#performance-testing

### Relevant log output

```typescript
[0-0] RUNNING in chrome - /test/specs/home.e2e.js
[0-0] TypeError in "Home.[HOME PAGE] Performance Check"
TypeError: browser.getPerformanceScore is not a function
    at HomePage.checkPerformance (/Users/eng7/git/Lively-Dev-Bundle/web/test/pageobjects/page.js:61:20)
    at Context.<anonymous> (/Users/eng7/git/Lively-Dev-Bundle/web/test/specs/home.e2e.js:6:14)
[0-0] FAILED in chrome - /test/specs/home.e2e.js

 "spec" Reporter:
------------------------------------------------------------------
[chrome 96.0.4664.110 mac os x #0-0] Running: chrome (v96.0.4664.110) on mac os x
[chrome 96.0.4664.110 mac os x #0-0] Session ID: 78f8a7c72cb60503b6a268468d7ac6fc
[chrome 96.0.4664.110 mac os x #0-0]
[chrome 96.0.4664.110 mac os x #0-0] » /test/specs/home.e2e.js
[chrome 96.0.4664.110 mac os x #0-0] Home
[chrome 96.0.4664.110 mac os x #0-0]    ✖ [HOME PAGE] Performance Check
[chrome 96.0.4664.110 mac os x #0-0]
[chrome 96.0.4664.110 mac os x #0-0] 1 failing (5.2s)
[chrome 96.0.4664.110 mac os x #0-0]
[chrome 96.0.4664.110 mac os x #0-0] 1) Home [HOME PAGE] Performance Check
[chrome 96.0.4664.110 mac os x #0-0] browser.getPerformanceScore is not a function
[chrome 96.0.4664.110 mac os x #0-0] TypeError: browser.getPerformanceScore is not a function
[chrome 96.0.4664.110 mac os x #0-0]     at HomePage.checkPerformance (/Users/eng7/git/Lively-Dev-Bundle/web/test/pageobjects/page.js:61:20)
[chrome 96.0.4664.110 mac os x #0-0]     at Context.<anonymous> (/Users/eng7/git/Lively-Dev-Bundle/web/test/specs/home.e2e.js:6:14)```
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2022-01-02 14:57
Can you share your `wdio-*` logs?

**Comment by owens-ben** [comment] 2022-01-04 15:23
@christian-bromann
[wdio-log.txt](https://github.com/webdriverio/webdriverio/files/7808562/wdio-log.txt)

**Comment by christian-bromann** [comment] 2022-01-04 16:18
Do you call `browser.enablePerformanceAudits()` before calling `browser.getPerformanceScore()`?

**Comment by owens-ben** [comment] 2022-01-04 16:19
Yes.

`browser.enablePerformanceAudits({networkThrottling: 'online', cpuThrottling: 4, formFactor: 'desktop'})
    this.open(true)
    expect(browser.getPerformanceScore()).toBeGreaterThanOrEqual(minScore)
    browser.disablePerformanceAudits()`

**Comment by christian-bromann** [comment] 2022-01-04 17:03
Can you provide a minimal reproducible example?

**Comment by owens-ben** [comment] 2022-01-04 19:42
@christian-bromann 

[web.zip](https://github.com/webdriverio/webdriverio/files/7810008/web.zip)

set BASE_URL to any valid url (like https://www.google.com)
`export BASE_URL="https://www.google.com"`

then run `yarn` then
`yarn run test.chrome.headless --spec test/specs/home.e2e.js`

**Comment by christian-bromann** [comment] 2022-01-04 20:15
@owens-ben thanks for providing. I can't tell when I get the time to look into this. If anyone has a hint, please post it in the thread.

**Comment by owens-ben** [comment] 2022-02-07 18:56
Any update here? @christian-bromann

**Comment by christian-bromann** [comment] 2022-02-07 20:17
@owens-ben I am unlikely to get into this anytime soon. Any contributions are apprecicated.

**Comment by owens-ben** [comment] 2022-02-07 20:36
How can I help?

**Comment by christian-bromann** [comment] 2022-02-07 23:07
A minimal reproducible example would be a good first step. Any hints what might cause this would help as well.

**Comment by mayankshukla94** [comment] 2022-06-23 14:55
@christian-bromann I would like to contribute here. I can debug the code and investigate how this can be fixed.

cc: @darshanshah1996

**Comment by christian-bromann** [comment] 2022-06-23 15:32
@mayankshukla94 awesome, thanks! Let me know if you have any questions.

**Comment by owens-ben** [comment] 2022-06-23 16:13
@mayankshukla94 cheers!

**Comment by mayankshukla94** [comment] 2022-07-03 16:46
@owens-ben I investigated this and looks like `wdio-video-reporter` does not generate video when `services` is set as `devtools`. The problem is with `wdio-video-reporter` and not with `Devtools`. I'll check how can we fix this.

cc: @christian-bromann @darshanshah1996

**Comment by christian-bromann** [comment] 2022-07-04 07:43
Thanks for investigating @mayankshukla94 , I will close this issue here then.

**Closed by christian-bromann** 2022-07-04 07:43 UTC
Labels: Bug 🐛, Needs Investigation, help wanted

**Comment by mayankshukla94** [comment] 2022-07-04 08:06
@christian-bromann Do we need to check why videos are not generated when services is set to `devtools`?

**Comment by christian-bromann** [comment] 2022-07-04 10:24
@mayankshukla94 right, but I assume this has to do with the video service rather than WebdriverIO itself which is why I suggest to report the issue there.
