### ISSUE TITLE
[🐛 Bug]: spec-reporter SauceLabs links not valid when testing on RDC

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#7648] opened 2021-11-04 15:19 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

14

### Mode

WDIO Testrunner

### What happened?

The spec reporter can output links to SauceLabs sessions.
These are not working when the tests run the Real Device Cloud.
Seems that there are two ID concepts, RDC job ID and test session ID.
The RDC job ID seems to be what's needed here.
https://github.com/webdriverio/webdriverio/blob/5128a8be94eddbf6e6b7f30fcdbc44e7b77a34c6/packages/wdio-spec-reporter/src/utils.ts#L43

### How to reproduce the bug.

Run a test on the SauceLabs RDC and try to open the link on the spec-reporter output.

### Relevant log output

```typescript
*
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2021-11-05 10:55
Duplicate of #6357

**Closed by christian-bromann** 2021-11-05 10:55 UTC
Labels: Bug 🐛, Needs Triaging ⏳
