### ISSUE TITLE
Work around for setValue for Safari 12, Mac 10.14 on SauceLabs

### ISSUE THREAD

**Issue by anxious-confidence** [webdriverio/webdriverio#3670] opened 2019-03-04 01:19 UTC
**Describe your question with as much detail as possible**
the setValue command doesn't seem to work on Safari 12, Mac 10.14 for SauceLabs. I had this same problem with Firefox, but was able to find a work around using the browser.execute function. Unfortunately, the browser.execute function isn't working on SauceLabs in Safari. Anyone have any ideas for a work around?

**If it's about a specific piece of code, try and include some of it to support your question.**
[...]

**Environment (please complete the following information):**
 - **WebdriverIO version:**5.6.4
 - **Mode:** [Standalone mode or WDIO Testrunner] Mocha
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async] sync
 - **Node.js version:** [e.g. 8.9.1] 10.15
 - **NPM version:** [e.g. 5.8.0] Not sure
 - **Browser name and version:** [e.g. Chrome 68] Safari 12
 - **Platform name and version:** [e.g. Windows 10] Mac 10.14
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service] standard stuff, but with SauceLabs

**Additional context**

**Comment by christian-bromann** [comment] 2019-03-04 08:18
duplicate of #3605

**Closed by christian-bromann** 2019-03-04 08:18 UTC
