### ISSUE TITLE
`setValue` after recent upgrade

### ISSUE THREAD

**Issue by DavertMik** [webdriverio/webdriverio#4859] opened 2019-12-06 10:56 UTC
At CodeceptJS we started receiving reports on this failure, then our CI started to fail as well, 

The issue happens for this line

```
return elem.setValue(value.toString());
```
and with error message `fn(...).apply is not a function`

![Selection_663](https://user-images.githubusercontent.com/220264/70317446-70e37480-1826-11ea-9267-14b357326a0e.png)

https://circleci.com/gh/Codeception/CodeceptJS/1598?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by christian-bromann** [comment] 2019-12-06 10:57
This got fixed in #4858

**Comment by DavertMik** [comment] 2019-12-06 10:58
Thanks! That was fast )

**Closed by christian-bromann** 2019-12-06 10:57 UTC

**Comment by mirao** [comment] 2019-12-08 14:58
I'm getting an error "ERROR @wdio/utils:shim: TypeError: Cannot read property 'apply' of undefined" when using `I.seeElement` and `I.fillField` in CodeceptJS with WebDriverIO 5.16.13, see https://github.com/Codeception/CodeceptJS/issues/2074

**Comment by mgrybyk** [comment] 2019-12-08 15:13
@mirao update @wdio/sync to the latest version, it is a regression since 5.16.11 and should be fixed in 5.16.14

**Comment by mirao** [comment] 2019-12-08 17:50
@mgrybyk Thanks, installation of latest @wdio/sync (5.16.14) fixed it.
Before that I hadn't installed the package in CodeceptJS project at all.

**Comment by mgrybyk** [comment] 2019-12-08 18:01
@mirao don't you use sync mode? @wdio/sync should be only responsible for sync mode. If you dont use sync mode it'd be better to remove it and make sure you have the latest version of all wdio packages

**Comment by mirao** [comment] 2019-12-08 18:16
@mgrybyk Not sure what sync mode is. I'm using CodeceptJS and usually only "npm install webdriverio" is needed there: https://codecept.io/quickstart-webdriver

**Comment by mirao** [comment] 2019-12-13 15:15
> @mgrybyk Thanks, installation of latest @wdio/sync (5.16.14) fixed it.
> Before that I hadn't installed the package in CodeceptJS project at all.

Well, finally solved by upgrade to `webdriverio@5.16.15`. And now I don't need `@wdio/sync` anymore so I removed it.
