### ISSUE TITLE
devtools service| ERROR @wdio/sync: TypeError: Cannot delete property 'puppeteer' of #<Browser>

### ISSUE THREAD

**Issue by igivon** [webdriverio/webdriverio#6405] opened 2021-02-10 11:30 UTC
**Environment:**
 - **Package.json dependencies:**
 ```js
    "@babel/cli": "7.12.13",
    "@babel/core": "7.12.13",
    "@babel/plugin-proposal-export-default-from": "7.12.13",
    "@babel/preset-env": "7.12.13",
    "@babel/register": "7.12.13",
    "@wdio/applitools-service": "7.0.1",
    "@wdio/cli": "7.0.1",
    "@wdio/cucumber-framework": "7.0.1",
    "@wdio/devtools-service": "7.0.1",
    "@wdio/junit-reporter": "7.0.1",
    "@wdio/local-runner": "7.0.1",
    "@wdio/selenium-standalone-service": "7.0.1",
    "@wdio/spec-reporter": "7.0.1",
    "@wdio/sync": "7.0.1",
    "commander": "^7.0.0",
    "expect": "^26.6.2",
    "expect-webdriverio": "^1.4.1",
    "fs-extra": "^9.1.0",
    "wdio-reportportal-reporter": "6.1.3",
    "wdio-reportportal-service": "6.1.1",
    "wdio-slack-service": "2.0.8"
```
 - **Mode:** [WDIO Launcher ]
 - **running sync
 - **Node.js version:v12.18.2** 
 - **NPM version:6.14.5** 
 - **Browser name and version: chrome.88_0_4324_146**
 - **Platform name and version: Windoes 10** 

**Config of WebdriverIO**
```js
{

    debug: process.env.DEBUG === "1",
    execArgv: process.env.DEBUG === "1" ? ["--inspect=127.0.0.1:5859"] : [],

    runner: 'local',

    specs: [
        './features/**/*.feature'
    ],
    exclude: [
        // 'path/to/excluded/files'
    ],

    logLevel: 'info',

    outputDir: LOGS_FILE_PATH,
    bail: 0,
    baseUrl: 'https://the-internet.herokuapp.com/',
  
    waitforTimeout: 10000,

    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: process.env.RP_UUID ? [[RpService, {}],['selenium-standalone',seleniumServerConfig],'devtools']:[['selenium-standalone',seleniumServerConfig],'devtools'],
   
    framework: 'cucumber',
    specFileRetries: 0,
    specFileRetriesDelay: 0,
    specFileRetriesDeferred: false,
    reporters: process.env.RP_UUID ? ['spec',[reportportal, reportportalConf],['junit', junitReporterConfig]]:['spec',['junit', junitReporterConfig]],
    checkLeaks:true,
}
```
```js
{
    //
    // If you are using Cucumber you need to specify the location of your step definitions.
    cucumberOpts: {
        // <string[]> (file/dir) require files before executing features
        require: ['./stepDefinitions/**/*.js','./projectHooks/**/*.js'],
        // <boolean> show full backtrace for errors
        backtrace: false,
        // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
        requireModule: ['@babel/register'],
        // <boolean> invoke formatters without executing steps
        dryRun: false,
        // <boolean> abort the run on first failure
        failFast: false,
        // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
        format: ['pretty'],
        // <boolean> hide step definition snippets for pending steps
        snippets: false,
        // <boolean> hide source uris
        source: true,
        // <string[]> (name) specify the profile to use
        profile: [],
        // <boolean> fail if there are any undefined or pending steps
        strict: false,
        // <string> (expression) only execute the features or scenarios with tags matching the expression
        tagExpression: "",
        // <number> timeout for step definitions
        timeout: 60000,
        // <boolean> Enable this config to treat undefined definitions as warnings.
        ignoreUndefinedDefinitions: false,
        //<boolean> Enable this to make webdriver.io behave as if scenarios and not steps were the tests.
        scenarioLevelReporter:false,
    },
}
```

**Describe the bug**
The below Error accurse when using **browser.reloadSession();** at the before scenario or after scenario hooks if disabling the reloadSession it wont happen and also when removing the **devtools service** 

```console
ERROR @wdio/sync: TypeError: Cannot delete property 'puppeteer' of #<Browser>
    at DevToolsService.onReload (C:\Users\iddang\Source\Repos\automatio-wdio-common\node_modules\@wdio\devtools-service\build\index.js:51:21)
    at C:\Users\iddang\Source\Repos\automatio-wdio-common\node_modules\webdriverio\build\commands\browser\reloadSession.js:49:58
    at Array.map (<anonymous>)
    at Browser.reloadSession (C:\Users\iddang\Source\Repos\automatio-wdio-common\node_modules\webdriverio\build\commands\browser\reloadSession.js:49:44)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Browser.runCommandWithHooks (C:\Users\iddang\Source\Repos\automatio-wdio-common\node_modules\@wdio\sync\build\wrapCommand.js:105:25)
    at Browser.runCommandWithHooks (C:\Users\iddang\Source\Repos\automatio-wdio-common\node_modules\@wdio\sync\build\wrapCommand.js:100:24)
    at Browser.reloadSession (C:\Users\iddang\Source\Repos\automatio-wdio-common\node_modules\@wdio\sync\build\wrapCommand.js:67:44)
    at Object.beforeScenario (C:\Users\iddang\Source\Repos\automatio-wdio-common\commonHooks\/automationHooks.js:142:25)
    at execHook (C:\Users\iddang\Source\Repos\automatio-wdio-common\node_modules\@wdio\sync\build\executeHooksWithArgs.js:36:31)
    at PickleRunner.invokeStep (C:\Users\iddang\Source\Repos\automatio-wdio-common\node_modules\@wdio\cucumber-framework\node_modules\@cucumber\cucumber\src\runtime\pickle_runner.ts:240:12)
    at PickleRunner.runHook (C:\Users\iddang\Source\Repos\automatio-wdio-common\node_modules\@wdio\cucumber-framework\node_modules\@cucumber\cucumber\src\runtime\pickle_runner.ts:362:12)
    at C:\Users\iddang\Source\Repos\automatio-wdio-common\node_modules\@wdio\cucumber-framework\node_modules\@cucumber\cucumber\src\runtime\pickle_runner.ts:325:20
    at PickleRunner.aroundTestStep (C:\Users\iddang\Source\Repos\automatio-wdio-common\node_modules\@wdio\cucumber-framework\node_modules\@cucumber\cucumber\src\runtime\pickle_runner.ts:273:28)
    at PickleRunner.run (C:\Users\iddang\Source\Repos\automatio-wdio-common\node_modules\@wdio\cucumber-framework\node_modules\@cucumber\cucumber\src\runtime\pickle_runner.ts:315:9)
    at Runtime.runPickle (C:\Users\iddang\Source\Repos\automatio-wdio-common\node_modules\@wdio\cucumber-framework\node_modules\@cucumber\cucumber\src\runtime\index.ts:118:20)
```
**Expected behavior**
No error

**Comment by balukov** [comment] 2021-03-02 09:35
Hi, is there a workaround for this?

**Comment by acambaswunderflats** [comment] 2021-03-08 14:37
I get the same error, at the moment i have all the newest wdio deps available

**Comment by brinkins** [comment] 2021-04-13 14:22
Downgrading to "@wdio/devtools-service": "^6.3.7" fixes the issue as a workaround.

**Comment by kailin0512** [comment] 2021-05-04 18:41
I got the same error, was anyone able to resolve this? Downgrade seems not a good option since devtools will have more features like code coverage in >7 correct?

**Comment by kailin0512** [comment] 2021-05-04 18:46
Also, since [Sync mode will not be supported in V8 of wdio](https://webdriver.io/docs/sync-vs-async/) should we just get rid of sync and use async? @christian-bromann

**Comment by christian-bromann** [comment] 2021-05-04 20:36
@kailin0512 please read the RFC on our plans to move forward

**Comment by kailin0512** [comment] 2021-05-05 18:13
Thanks, I will follow up with RFC to decide our project's future direction.
In the same time, I looked deeper into this question, it seems caused by rewriting devtools/index.js to typescript
This maybe cause the sync browser is not the same browser for async, so 
```js 
delete this._browser.puppeteer;
```
is not working and cause this error. I try to print this, and it just shows null

Do you have suggestions on which file to look at and I can contribute to this issue? @christian-bromann

**Comment by brinkins** [comment] 2021-05-05 18:28
not sure if it is the right solution, but I've changed delete this._browser.puppeteer; to this._browser.puppeteer = null and seems to work

**Comment by kailin0512** [comment] 2021-05-05 18:44
In my case I did the same, but there are some errors that prevent the correct output, not sure if that related to this reload
```
[0-0] [BABEL] Note: The code generator has deoptimised the styling of  <file path> as it exceeds the max of 500KB.
```

But I assume that browser.puppeteer exists for a reason, if you print that variable out, it is just null, so unable to delete/set to null might miss the desired feature I assume @brinkins

**Comment by christian-bromann** [comment] 2021-05-05 18:59
@kailin0512 can you provide a minimal reproducible example?

**Comment by kailin0512** [comment] 2021-05-05 19:02
Are there any examples from wdio side I can fork and make some modifications and provide a reproducible example? @christian-bromann

**Comment by christian-bromann** [comment] 2021-05-05 19:04
Check our [examples](https://github.com/webdriverio/webdriverio/tree/main/examples) but creating a new repo works as well.

**Comment by brinkins** [comment] 2021-05-05 19:06
@christian-bromann just run browser.reloadSession() will throw the error, latest wdio and devtools service

**Comment by kailin0512** [comment] 2021-05-05 19:22
https://github.com/kailin0512/webdriverio-debug @christian-bromann try this

**Comment by kailin0512** [comment] 2021-05-05 19:32
With 
```js
this._browser.puppeteer = null
```
 will work in this minimal example, but not on a complex project, so I am not sure if this will be this simple fix

**Comment by christian-bromann** [comment] 2021-05-06 09:35
PR with a fixed was created. Closing.

**Closed by christian-bromann** 2021-05-06 09:35 UTC
Labels: Bug🐛
