### ISSUE TITLE
findElement sometimes returns Promise in sync mode

### ISSUE THREAD

**Issue by diachedelic** [webdriverio/webdriverio#4254] opened 2019-07-25 11:12 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version: v5.11.7
 - **Mode: WDIO Testrunner
 - **If WDIO Testrunner, running sync/async: sync
 - **Node.js version: v11.15.0
 - **NPM version: v6.7.9
 - **Browser name and version: 76.0.3809.80 (Official Build) beta (64-bit)
 - **Platform name and version: MacOS 10.14.5 (18F132)
 - **Additional wdio packages used (if applicable):** 
 ```

    "@wdio/allure-reporter": "^5.11.7",
    "@wdio/cli": "^5.11.8",
    "@wdio/local-runner": "^5.11.7",
    "@wdio/mocha-framework": "^5.11.0",
    "@wdio/selenium-standalone-service": "^5.11.2",
    "@wdio/spec-reporter": "^5.11.7",
    "@wdio/sync": "^5.11.9",
```

**Config of WebdriverIO**
See repro

**Describe the bug**
Given the correct circumstances, calling `element.$()` returns a Promise in
sync mode.

**To Reproduce**

```
git clone git@github.com:diachedelic/wdio-repros.git &&
  cd wdio-repros &&
  git checkout sync-promises &&
  npm i &&
  npm test
```

**Expected behavior**
I expect `$()` to always return an Element

**Log**
https://gist.github.com/diachedelic/9af6ccc9a4beedb8918f2ab5616fe004

**Comment by mgrybyk** [comment] 2019-07-25 11:15
Please update to the latest version.

If you still experience the issue, please provide with steps to reproduce

**Comment by diachedelic** [comment] 2019-07-25 11:19
@mgrybyk which version is that?

**Comment by mgrybyk** [comment] 2019-07-25 11:22
Hey, I think I missed something. I though you are still on previous one.

I'll take a look soon.
Thank you for steps to reproduce

**Comment by diachedelic** [comment] 2019-07-25 11:27
@mgrybyk I am on the latest that NPM will give me - I'm pretty sure the latest `webdriverio` and `webdriver` are `v5.11.7`, even though some other packages are at `v5.11.9`

**Comment by diachedelic** [comment] 2019-07-25 11:30
@mgrybyk If I pin `webdriver` to `v5.11.5` (via Yarn's "resolutions" feature) the issue is resolved, e.g.:
```
// package.json
...
  "devDependencies": {
    ...
    "webdriverio": "^5.11.7"
  },
  "resolutions": {
    "webdriver": "5.11.5"
  },
...

**Comment by mgrybyk** [comment] 2019-07-25 11:34
Looks like a regression, hope to deal with it today

**Comment by diachedelic** [comment] 2019-07-25 11:35
@mgrybyk cheers!

**Comment by mgrybyk** [comment] 2019-07-25 14:07
@diachedelic fix is ready and will be merged soon. 
Thank you for your help!

If you see any other issues, please let me know!
https://github.com/webdriverio/webdriverio/pull/4256

**Closed by mgrybyk** 2019-07-25 14:07 UTC
