### ISSUE TITLE
All scenarios in feature are running as of 5.16.0 even tag provided should only run 1 scenario

### ISSUE THREAD

**Issue by mikesalvia** [webdriverio/webdriverio#4744] opened 2019-11-06 17:51 UTC
#4531 has caused all scenarios to run in a feature even if the tag specified is only on a single scenario in that feature.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2] 5.16.0 (using 5.15.2 does not present this issue)
 - **Mode:** [Standalone mode or WDIO Testrunner] WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async] sync
 - **Node.js version:** [e.g. 8.11.2] 10.13.0
 - **NPM version:** [e.g. 5.8.0] 6.4.1
 - **Browser name and version:** [e.g. Chrome 68] Chrome (latest)
 - **Platform name and version:** [e.g. Windows 10] macOS High Sierra
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service] A lot @wdio/cucumber-framework

**Config of WebdriverIO**
To be provided

**Describe the bug**
All scenarios are run even if the tag expression only should include a single scenario.

**To Reproduce**

* Provide a tag expression that should only run 1 scenario in a feature
* Attempt to run the framework
* All scenarios are executed if the feature has a single tag in it

[Include code or an example repository that can easily be set up]

**Expected behavior**
Only the scenario tagged should be ran

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

Working to replicate this with cucumber-boilerplate...

**Comment by mikesalvia** [comment] 2019-11-06 17:53
@mgrybyk Just an FYI it looks like it could be tied to the recent changes in 5.16.0 with @wdio/cucumber-framework

**Comment by mikesalvia** [comment] 2019-11-06 18:06
Also, `cucumber-boilerplate` package-lock.json has 5.15.0 as the version so it won't show up out of the box.

**Comment by mikesalvia** [comment] 2019-11-06 18:15
Oddly enough when updating to 5.16.0 in the cucumber-boilerplate I see no issues. :-/

**Comment by jlin-namely** [comment] 2019-11-06 18:30
It didn't work for me either after upgrading to 5.16.0

**Comment by mgrybyk** [comment] 2019-11-06 18:33
What is not working, do you have a reproducible example?

**Comment by mikesalvia** [comment] 2019-11-06 18:42
I am working on a reproducible example with the Cucumber Boilerplate repository

**Comment by mikesalvia** [comment] 2019-11-06 18:45
Specifically, if I provide a tag `@run_me` on a scenario inside of a feature with say 9 scenarios. Instead of the single scenario running, the entire feature of scenarios are executed.

**Comment by mikesalvia** [comment] 2019-11-06 18:46
I think I have tracked it down, at least I think... Stand by.

**Comment by mgrybyk** [comment] 2019-11-06 18:48
@mikesalvia tags work for me

**Comment by mikesalvia** [comment] 2019-11-06 18:48
I have noticed an issue in the documentation that `before` hook now has (`config` provided as the 1st variable), this is a rather large breaking change IMO. Also, it is not documented in the `ConfigurationFile.md`

**Comment by mgrybyk** [comment] 2019-11-06 18:50
@mikesalvia might be, I'll take a look, but it's another issue, let's handle this one first

**Comment by mgrybyk** [comment] 2019-11-06 18:51
```
cucumberOpts: {
        tagExpression: "@foo",
```
works fine

**Comment by mikesalvia** [comment] 2019-11-06 18:51
In `cucumber-boilerplate`?

**Comment by mgrybyk** [comment] 2019-11-06 18:52
nope, in my own project

**Comment by mikesalvia** [comment] 2019-11-06 18:53
OK going to try to get something reproducible.

**Comment by mikesalvia** [comment] 2019-11-06 19:00
OK, so, I am not sure what provides this value. However, it is marked undefined in our project now...

![Screen Shot 2019-11-06 at 1 58 51 PM](https://user-images.githubusercontent.com/6209204/68328676-c39e0500-009d-11ea-8c14-295ae17e31c4.png)

 `featureFlags: { specFiltering: undefined },` this is supposed to be enabled by default for Cucumber as per the PR

**Comment by mikesalvia** [comment] 2019-11-06 19:04
However, red herring I believe cause it is still happening even after removing that.

**Comment by mikesalvia** [comment] 2019-11-06 19:07
What version of `wdio-cucumber-framework` are you on?

**Comment by mgrybyk** [comment] 2019-11-06 19:08
you don't need that featureFlags, just remove it

**Comment by mgrybyk** [comment] 2019-11-06 19:08
same as mocha and jasmine opts if you use cucumber

**Comment by mikesalvia** [comment] 2019-11-06 19:09
I didn't add that. It was in my config that was generated and logged in the `before` hook.

**Comment by mgrybyk** [comment] 2019-11-06 19:09
ah, so it's not your config but logs?

**Comment by mikesalvia** [comment] 2019-11-06 19:10
Yes that is correct.

**Comment by mgrybyk** [comment] 2019-11-06 19:10
ok, so is the issue is still reproducible for you?

**Comment by mikesalvia** [comment] 2019-11-06 19:10
I am still attempting to figure out what is unique about my setup. It is spanned between 2 of our projects that share common code base.

**Comment by mikesalvia** [comment] 2019-11-06 19:11
Yes, it is reproducible every time but we have a lot of stuff going on and curious if I have a mismatch version of something.

**Comment by mgrybyk** [comment] 2019-11-06 19:17
I'd like to help but I don't know how

**Comment by mikesalvia** [comment] 2019-11-06 19:18
All good I am updating the cucumber boilerplate project to the latest versions available to try again.

**Comment by mgrybyk** [comment] 2019-11-06 20:17
@mikesalvia how is it going?

**Comment by mikesalvia** [comment] 2019-11-06 20:19
Working on it still... 😦 Working to get this to repeat on the boilerplate, I wonder if my code was effected by that before hook variable.

**Comment by mgrybyk** [comment] 2019-11-06 20:23
@mikesalvia tags work fine for me in boilerplate project

**Comment by mikesalvia** [comment] 2019-11-06 20:23
I am seeing that when I log `testCases` after pickle filtering, does not filter it down!

**Comment by mikesalvia** [comment] 2019-11-06 20:24
So this leads me to think something is not set properly at that point.

```[ { pickle:
     { tags: [Array],
       name: 'A CMAF HLS stream should play using HLSjs provider',
       language: 'en',
       locations: [Array],
       steps: [Array] },
    uri: 'features/hlsjs/hls_CMAF_streams.feature' },
  { pickle:
     { tags: [Array],
       name: 'A CMAF HLS live stream should play using HLSjs provider',
       language: 'en',
       locations: [Array],
       steps: [Array] },
    uri: 'features/hlsjs/hls_CMAF_streams.feature' },
  { pickle:
     { tags: [Array],
       name: 'HLSjs - CMAF live stream with a Googima preroll',
       language: 'en',
       locations: [Array],
       steps: [Array] },
    uri: 'features/hlsjs/hls_CMAF_streams.feature' },
  { pickle:
     { tags: [Array],
       name: 'HLSjs - CMAF live stream with a VAST preroll',
       language: 'en',
       locations: [Array],
       steps: [Array] },
    uri: 'features/hlsjs/hls_CMAF_streams.feature' },
  { pickle:
     { tags: [Array],
       name: 'HLSjs - CMAF live stream with a Freewheel preroll',
       language: 'en',
       locations: [Array],
       steps: [Array] },
    uri: 'features/hlsjs/hls_CMAF_streams.feature' },
  { pickle:
     { tags: [Array],
       name:
        'A CMAF HLS stream should play using HTML5 provider for Safari browsers',
       language: 'en',
       locations: [Array],
       steps: [Array] },
    uri: 'features/hlsjs/hls_CMAF_streams.feature' },
  { pickle:
     { tags: [Array],
       name:
        'A CMAF HLS live stream should play using HTML5 provider for Safari browsers',
       language: 'en',
       locations: [Array],
       steps: [Array] },
    uri: 'features/hlsjs/hls_CMAF_streams.feature' },
  { pickle:
     { tags: [Array],
       name:
        'HLSjs - CMAF live stream with a Googima preroll - Safari Variant',
       language: 'en',
       locations: [Array],
       steps: [Array] },
    uri: 'features/hlsjs/hls_CMAF_streams.feature' },
  { pickle:
     { tags: [Array],
       name:
        'HLSjs - CMAF live stream with a VAST preroll - Safari Variant',
       language: 'en',
       locations: [Array],
       steps: [Array] },
    uri: 'features/hlsjs/hls_CMAF_streams.feature' },
  { pickle:
     { tags: [Array],
       name:
        'HLSjs - CMAF live stream with a Freewheel preroll - Safari Variant',
       language: 'en',
       locations: [Array],
       steps: [Array] },
    uri: 'features/hlsjs/hls_CMAF_streams.feature' } ]```

**Comment by mikesalvia** [comment] 2019-11-06 20:27
Figured it out! At least I think...

```{ backtrace: true,
  requireModule: [],
  failAmbiguousDefinitions: true,
  failFast: false,
  ignoreUndefinedDefinitions: false,
  name: [],
  profile: [],
  require: [ './features/step_definitions/**/*.js' ],
  order: 'defined',
  snippetSyntax: undefined,
  snippets: true,
  source: true,
  strict: true,
  tagExpression: '',
  tagsInTitle: false,
  timeout: 360000,
  compiler: [ 'js:babel-core/register' ],
  dryRun: false,
  format: [ 'pretty' ],
  colors: true }```

Looks like my tagExpression is not being set properly or at the right time since Cucumber is `init` sooner than before.

**Comment by mgrybyk** [comment] 2019-11-06 20:28
Lo, let's close it?

**Comment by mikesalvia** [comment] 2019-11-06 20:30
Let me just make sure and document this clearly. To be clear Cucumber is initialize before any hooks we we need the `tagExpression` to be set in the original configuration before any hooks or lifecycle stages?

**Comment by mikesalvia** [comment] 2019-11-06 20:31
I am not sure who else builds there tagExpression on the fly, we actually filter out any unneeded features so we don't get the session spin up for a feature running no scenarios.

**Comment by mgrybyk** [comment] 2019-11-06 20:31
well, yes

**Comment by mikesalvia** [comment] 2019-11-06 20:33
We were setting our tag expression dynamically as such

```
function getTagExpression(browserTagExpression = '') {
    // Configure tags based on config, env tags and capabilities
    const jenkinsTags = (CUCUMBER_TAGS || '').split(/(?:\s*--?t(?:ags)?)?\s+/).map(tag => tag.replace('~', 'not '));
    const browserTags = (browserTagExpression).split(/\s+and\s+/);
    const envTags = (TAGS || '').split(/\s+and\s+/);
    const argvTags = argv.tags || [];
    return jenkinsTags.concat(browserTags).concat(envTags).concat(argvTags).reduce((a, val) => {
        if (val && !a.includes(val)) {
            a.push(val);
        }
        return a;
    }, []).join(' and ');
}

const tagExpression = capabilities.length === 1 ? capabilities[0]['jw:tagExpression'] : '';
const tags = getTagExpression(tagExpression);

if (!config.specs || !config.specs.length) {
    config.specs = parseCucumberTags(tags, global.cucumberFeatures);
}
```

Then `parseCucumberTags` actually reduces the specs provided.

```
function parseCucumberTags(tags, featurePath) {
    const expressionNode = parseTags(tags);
    if (!expressionNode) {
        return [];
    }
    return glob.sync(featurePath).map((file) => {
        const content = fs.readFileSync(file, 'utf8');
        const tagLinesInFile = content.match(/@.*/g) || [];
        if (tagLinesInFile) {
            for (let i = 0; i < tagLinesInFile.length; i++) {
                if (expressionNode.evaluate(tagLinesInFile[i].split(" "))) {
                    return file;
                }
            }
        }
        return null;
    }).filter(x => x !== null);
}
```
Might be worth adding this to wdio-cucumber-framework, which will prevent scenario-less features starting sessions or spinning up browsers. I will look at this next.

**Comment by mgrybyk** [comment] 2019-11-06 20:33
What we can do is move `beforeSession` hook before framework init and you can do whatever you like there

**Comment by mikesalvia** [comment] 2019-11-06 20:34
That is a good idea... is the order `onPrepare` => `beforeSession` => `before`?

**Comment by mgrybyk** [comment] 2019-11-06 20:35
not really
onPrepare/onComplete executes in a main process
beforeSession then before are executed in worker process

**Comment by mikesalvia** [comment] 2019-11-06 20:36
we were doing the tag stuff in `onPrepare` still didn't work there

**Comment by mgrybyk** [comment] 2019-11-06 20:37
well it should not work there

**Comment by mikesalvia** [comment] 2019-11-06 20:38
We probably need to move it into the configuration level and not in the runner cycle...

**Comment by mikesalvia** [comment] 2019-11-06 20:41
OK so in order to dynamically set tags we need to provide them to Cucumber prior to init so they are filtered and done properly beforeSession is not the right time because sessions are built based on how many features we need to run

**Closed** 2019-11-06 20:40 UTC
Labels: Needs Investigation, Reproducible Example Missing

**Comment by mikesalvia** [comment] 2019-11-06 20:43
Moving our parsing and dynamical tag logic to `wdio.config.js`, in fact, allows for tags to be used! 

Applying `config.cucumberOpts.tagExpression` in `onPrepare`, `before`, or `beforeSession` are not possible anymore as it is initialized sooner than was before, it is ignored there. If we can have a preInit hook in order to set that stuff up it would be great but for now doing it in the `wdio.conf.js` will work for us.

**Comment by mikesalvia** [comment] 2019-11-06 20:44
@mgrybyk Thank you for your patience and assistance in getting to the bottom of this! 😄 🍻 🎉

**Comment by mgrybyk** [comment] 2019-11-06 21:36
@mikesalvia I'm glad you've solved your issue and thanks for pointing on an issue with before hook
