### ISSUE TITLE
[🐛 Bug]: V7 Cucumber - Unable to identify the current Scenario Outline example

### ISSUE THREAD

**Issue by kyungkimsf** [webdriverio/webdriverio#7681] opened 2021-11-10 19:00 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest, v7.16.0

### Node.js Version

latest, v16

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    browserName: 'chrome',
    'goog:chromeOptions': {
        args: [
            '--disable-infobars',
            '--window-size=1920,1080',
            '--no-sandbox',
            '--disable-gpu',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage'
        ],
    },
}
```

### What happened?

When a Scenario Outline is run through Cucumber via WebdriverIO, it uses the examples table as a data provider to run the test with different example values. e.g.,

```
    Scenario Outline: Logging in to some website
        When I login to some website as "<user>" user

        Examples:
            | user |
            | a    |
            | b    |
            | c    |
```

I would like to be able to easily parse out the example table row values used for each scenario run in the hooks so I can append their values to the Scenario name to show up as different runs in the test reporters. 

Typically in ruby cucumber, an object like the ```Cucumber::Core::Ast::ExamplesTable::Row:``` is available where you could just fetch the value of the current row in the hooks. 

Looking at the Cucumber step object in javascript implementation, https://github.com/cucumber/common/blob/main/messages/javascript/src/messages.ts#L410-L420, it looks like we should be able to at the very least iterate through each step object and distinguish whether the passed in values are from a data table (examples) or not https://github.com/cucumber/common/blob/main/messages/javascript/src/messages.ts#L422-L429.

However, when I currently step into the BeforeScenario or BeforeStep hooks, I see the argument parameter is never set to any value and just reports `argument = undefined`. I am wondering if the cucumber listener setup WDIO is currently using isn't populating the dataTable/dataString at all or something.

I can however dig into the gherkinDocument object like this `world.gherkinDocument.feature.children[1].scenario.examples[0].tableBody` to see all the examples that's available for the scenario. Unfortunately, this does not provide a good way to tell which example row I am currently running at the hooks level.

### What is your expected behavior?

My expected behavior is that when I am in the hooks, such as the `beforeScenario`, I am able to iterate through the scenario's steps and identify all the values for the particular example row (table row) that my current scenario is running against by checking its `argument` value. I'd achieve this by doing something like this -
```
    beforeScenario: async function (world) {
        if (world.pickle.steps[0].argument typeof PickleTable)
    },
```

### How to reproduce the bug.

Run webdriverio with cucumber in debug mode (--inspect-brk) and check to see if there is a straight forward way to fetch out the current running scenario's example row values. You'd find that the `argument` attribute inthe PickleStep object is always undefined so the only way to try to fetch the example rows would be to identify the examples in the gherkinDocument object for the current scenario, and then find the matching steps that are using the example row's values -- which requires some fuzzy comparison / regex if we went that route.

`world.pickle.steps[0].argument` <- returns undefined

### Relevant log output

```typescript
`world.pickle.steps[0].argument` <- returns undefined
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2021-11-10 20:51
@kyungkimsf thanks for filing the issue.

I agree that populating this data is useful for users. Any contributions that implements this are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by praveendvd** [comment] 2021-11-11 08:12
@christian-bromann  and @kyungkimsf  


     beforeFeature: function (uri ,feature){
        console.log("uri",uri,"context",JSON.stringify(feature.children[0].scenario,null,2))
    },


this information is available in beforefeature ,

**Comment by christian-bromann** [comment] 2021-11-11 10:48
Thanks for investigating @praveendvd!

@kyungkimsf would that be enough for your use case or do you need all this data in the beforeScenario hook? And if so why?

**Comment by kyungkimsf** [comment] 2021-11-11 15:53
@praveendvd @christian-bromann as I've mentioned in the original post, it is 'available' under the gherkin document as well but that doesn't provide a good easy way to distinguish what the currently running scenario actually is -- unless the assumption is being made that children[0] is always going to be the current sccenario -- like having only one scenario in the feature file. But if you have a Background step, the first child is also going to be the background object, not a scenario one. In either case, you'd have to parse out and figure out what your current scenario is and then try to get the example values.

**Comment by christian-bromann** [comment] 2021-11-11 15:56
> unless the assumption is being made that children[0] is always going to be the current sccenario

Well you can check this by having a:

```js
beforeFeature: function (uri ,feature){
    console.log("uri",uri,"context",JSON.stringify(feature.children[0].scenario,null,2))
},
```

in your `wdio.conf.js`.

**Comment by praveendvd** [comment] 2021-11-11 16:20
> @praveendvd @christian-bromann as I've mentioned in the original post, it is 'available' under the gherkin document as well but that doesn't provide a good easy way to distinguish what the currently running scenario actually is -- unless the assumption is being made that children[0] is always going to be the current sccenario -- like having only one scenario in the feature file. But if you have a Background step, the first child is also going to be the background object, not a scenario one. In either case, you'd have to parse out and figure out what your current scenario is and then try to get the example values.

children 0 is the first scenario in the feature file not the current ,  so if you have 5 scenarios , you can choose the 5 sceanrio as scenario[4] 

and for current scenario , the data file is not shown but the <variable> get replaced with the current value of the data table . As christian mentioned it would be great if you specify whats the expected data and where

**Comment by kyungkimsf** [comment] 2021-11-11 16:52
The expected experience that's the easiest for the end user using the framework would be to just be able to say, given `a` being my current scenario -- typically in the beforeScenario hook, give me the example row that it's using if it's a scenario outline.

From what I am gathering, the current suggestions are parse into the feature / gherkin document from the world, find the current scenario that's running, and then if you have 5 examples in your scenario outline, try to parse out **which example it is currently running.** The last part is technically the most annoying-ish because you'd have to parse each step and pull out the values they are using -- with a lot of regex -- and see if they match with the particular example row that you have out of the 5 examples.

**Comment by tamil777selvan** [comment] 2023-09-04 02:57
Hi @kyungkimsf,


As [pickles](https://github.com/cucumber/gherkin#pickles) represent the compiled form of gherkinDocument, the examples are merged into the steps at this stage. Consequently, they are not accessible via the `arguments`. However, if you wish to identify or access the specific example being executed, you can consider the following approaches:

1. Modify the scenario description to include example arguments like this:

   ```
   Scenario Outline: Logging in to a website <user>
       When I log in to the website as "<user>" user

       Examples:
           | user |
           | a    |
           | b    |
           | c    |
   ```

   This modification will internally update the scenario description with examples during compilation, resulting in individual scenario reports.

2. You can use the following code in `beforeScenario` hook to retrieve the example being executed, but you need to append it explicitly to the reports:

   ```javascript
   const tableBody = world.gherkinDocument.feature?.children[0].scenario?.examples[0]?.tableBody;
   const stepAstNodes = world.pickle.steps[0].astNodeIds;
   const examples = tableBody?.find((tb) => stepAstNodes.includes(tb.id))?.cells.map(cell => cell.value).join(', ');
   ```

Furthermore, the reason we can't internally update this within `@wdio-cucumber-framework` is because the `arguments` of pickle contains the `dataTable` value if it's available. I hope this helps.

**Comment by tamil777selvan** [comment] 2023-10-09 04:04
Closing due to inactivity. Please feel free to re-open, if the issue is unresolved.

**Closed by tamil777selvan** 2023-10-09 04:04 UTC
Labels: Enhancement, help wanted, wdio-cucumber-framework
