### ISSUE TITLE
[🐛 Bug]: Not working with Appium 2, `automationName` issues

### ISSUE THREAD

**Issue by milesj** [webdriverio/webdriverio#9531] opened 2023-01-03 23:58 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.1.0

### Node.js Version

16.16

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  platformName: 'iOS',
  'appium:options': {
    app,
    automationName: 'XCUITest',
    autoAcceptAlerts: true,
    deviceName: 'iPhone Simulator',
    fullReset: true,
    noReset: false,
    showXcodeLog: true,
  },
}
```

### What happened?

When I run tests using the capabilities above, I receive the following error:

```
ERROR webdriver: invalid argument: 'automationName' can't be blank
```

When I move `automationName` to the top-level, I instead receive this following error:

```
ERROR @wdio/runner: Error: Invalid or unsupported WebDriver capabilities found ("automationName"). Ensure to only use valid W3C WebDriver capabilities (see https://w3c.github.io/webdriver/#capabilities).If you run your tests on a remote vendor, like Sauce Labs or BrowserStack, make sure that you put them into vendor specific capabilities, e.g. "sauce:options" or "bstack:options". Please reach out to to your vendor support team if you have further questions.
```

Not sure how to proceed...

### What is your expected behavior?

Tests run when `automationName` is nested within `appium:options`, as required by Appium 2: https://github.com/appium/appium/blob/master/packages/appium/docs/en/guides/migrating-1-to-2.md#bangbang-capabilities

### How to reproduce the bug.

Setup wdio to use the appium service, and ensure that appium is configured for v2: https://github.com/appium/appium/blob/master/packages/appium/docs/en/guides/migrating-1-to-2.md

### Relevant log output

```typescript
Execution of 1 workers started at 2023-01-03T23:57:54.273Z

2023-01-03T23:57:54.279Z DEBUG @wdio/utils:initialiseServices: initialise service "appium" as NPM package
2023-01-03T23:57:54.423Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-01-03T23:57:54.424Z DEBUG @wdio/appium-service: Will spawn Appium process: node /Users/milesjohnson/Projects/react-native/node_modules/appium/index.js --base-path / --allow-insecure chromedriver_autodownload
2023-01-03T23:57:58.138Z DEBUG @wdio/appium-service: Appium started with ID: 84426
2023-01-03T23:57:58.139Z DEBUG @wdio/cli:utils: Finished to run "onPrepare" hook in 3716ms
2023-01-03T23:57:58.139Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-01-03T23:57:58.139Z DEBUG @wdio/cli:utils: Finished to run "onWorkerStart" hook in 0ms
2023-01-03T23:57:58.140Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./e2e.config.js,--spec,./src/specs/Signin.spec.ts
2023-01-03T23:57:58.143Z DEBUG @wdio/local-runner: Send command run to worker with cid "0-0"
2023-01-03T23:57:58.144Z DEBUG @wdio/appium-service: Appium logs written to: /Users/milesjohnson/Projects/react-native/src/packages/app/artifacts/logs/wdio-appium.log
[0-0] 2023-01-03T23:57:58.542Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2023-01-03T23:57:59.073Z DEBUG @wdio/runner: init remote session
[0-0] 2023-01-03T23:57:59.077Z DEBUG @wdio/utils:initialiseServices: initialise service "appium" as NPM package
[0-0] RUNNING in Android - file:///src/specs/Signin.spec.ts
[0-0] 2023-01-03T23:57:59.275Z DEBUG @wdio/runner: init remote session
[0-0] 2023-01-03T23:57:59.275Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-01-03T23:57:59.315Z INFO webdriver: [POST] http://127.0.0.1:4723/session
[0-0] 2023-01-03T23:57:59.315Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { platformName: 'Android', 'appium:options': [Object] },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     platformName: 'Android',
[0-0]     'appium:options': {
[0-0]       app: '/Users/milesjohnson/Projects/react-native/src/packages/app/android/app/build/outputs/apk/alphaRelease/app-universal-alphaRelease.apk',
[0-0]       appActivity: 'com.android.MainActivity',
[0-0]       autoGrantPermissions: true,
[0-0]       automationName: 'UiAutomator2',
[0-0]       deviceName: 'Android Emulator',
[0-0]       fullReset: true,
[0-0]       noReset: false
[0-0]     }
[0-0]   }
[0-0] }
[0-0] 2023-01-03T23:57:59.357Z DEBUG webdriver: request failed due to response error: invalid argument
[0-0] 2023-01-03T23:57:59.357Z WARN webdriver: Request failed with status 400 due to 'automationName' can't be blank
[0-0] 2023-01-03T23:57:59.357Z INFO webdriver: Retrying 1/1
[0-0] 2023-01-03T23:57:59.358Z INFO webdriver: [POST] http://127.0.0.1:4723/session
[0-0] 2023-01-03T23:57:59.358Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { platformName: 'Android', 'appium:options': [Object] },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     platformName: 'Android',
[0-0]     'appium:options': {
[0-0]       app: '/Users/milesjohnson/Projects/react-native/src/packages/app/android/app/build/outputs/apk/alphaRelease/app-universal-alphaRelease.apk',
[0-0]       appActivity: 'com.android.MainActivity',
[0-0]       autoGrantPermissions: true,
[0-0]       automationName: 'UiAutomator2',
[0-0]       deviceName: 'Android Emulator',
[0-0]       fullReset: true,
[0-0]       noReset: false
[0-0]     }
[0-0]   }
[0-0] }
[0-0] 2023-01-03T23:57:59.361Z DEBUG webdriver: request failed due to response error: invalid argument
[0-0] 2023-01-03T23:57:59.361Z ERROR webdriver: Request failed with status 400 due to invalid argument: 'automationName' can't be blank
[0-0] 2023-01-03T23:57:59.361Z ERROR webdriver: invalid argument: 'automationName' can't be blank
[0-0]     at getErrorFromResponseBody (file:///Users/milesjohnson/Projects/react-native/node_modules/webdriver/build/utils.js:194:12)
[0-0]     at NodeJSRequest._request (file:///Users/milesjohnson/Projects/react-native/node_modules/webdriver/build/request/index.js:168:23)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at async startWebDriverSession (file:///Users/milesjohnson/Projects/react-native/node_modules/webdriver/build/utils.js:63:20)
[0-0]     at async Function.newSession (file:///Users/milesjohnson/Projects/react-native/node_modules/webdriver/build/index.js:24:45)
[0-0]     at async remote (file:///Users/milesjohnson/Projects/react-native/node_modules/webdriverio/build/index.js:48:22)
[0-0]     at async Runner._startSession (file:///Users/milesjohnson/Projects/react-native/node_modules/@wdio/runner/build/index.js:221:29)
[0-0]     at async Runner._initSession (file:///Users/milesjohnson/Projects/react-native/node_modules/@wdio/runner/build/index.js:187:25)
[0-0]     at async Runner.run (file:///Users/milesjohnson/Projects/react-native/node_modules/@wdio/runner/build/index.js:77:19)
[0-0] 2023-01-03T23:57:59.362Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] 'automationName' can't be blank
[0-0]     at startWebDriverSession (file:///Users/milesjohnson/Projects/react-native/node_modules/webdriver/build/utils.js:68:15)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at async Function.newSession (file:///Users/milesjohnson/Projects/react-native/node_modules/webdriver/build/index.js:24:45)
[0-0]     at async remote (file:///Users/milesjohnson/Projects/react-native/node_modules/webdriverio/build/index.js:48:22)
[0-0]     at async Runner._startSession (file:///Users/milesjohnson/Projects/react-native/node_modules/@wdio/runner/build/index.js:221:29)
[0-0]     at async Runner._initSession (file:///Users/milesjohnson/Projects/react-native/node_modules/@wdio/runner/build/index.js:187:25)
[0-0]     at async Runner.run (file:///Users/milesjohnson/Projects/react-native/node_modules/@wdio/runner/build/index.js:77:19)
2023-01-03T23:57:59.473Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in Android - file:///src/specs/Signin.spec.ts
2023-01-03T23:57:59.473Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-01-03T23:57:59.474Z DEBUG @wdio/cli:utils: Finished to run "onWorkerEnd" hook in 0ms
2023-01-03T23:57:59.474Z INFO @wdio/cli:launcher: Run onComplete hook
2023-01-03T23:57:59.474Z DEBUG @wdio/appium-service: Appium (pid: 84426) killed
2023-01-03T23:57:59.474Z DEBUG @wdio/cli:utils: Finished to run "onComplete" hook in 0ms

Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:05

2023-01-03T23:57:59.474Z INFO @wdio/local-runner: Shutting down spawned worker
2023-01-03T23:57:59.727Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-01-03T23:57:59.728Z INFO @wdio/local-runner: shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by milesj** [comment] 2023-01-03 23:59
Using `'appium:automationName': 'XCUITest',` seems to work though.

**Comment by wswebcreation** [comment] 2023-01-04 07:59
Hi @milesj 

This is not a bug in WDIO, but in Appium, see also https://github.com/appium/appium/issues/17779. Closing this one as this is a 3rd party dependency bug

**Closed by wswebcreation** 2023-01-04 07:59 UTC

**Comment by agray** [comment] 2023-08-04 10:01
> Using `'appium:automationName': 'XCUITest',` seems to work though.

Tried it with C#. Doesn't work

**Comment by christian-bromann** [comment] 2023-08-04 15:37
> Please reopen or tell me what actually works.

Please reach out to the Sauce Labs support team. I doubt this is an issue within WebdriverIO.

**Comment by wswebcreation** [comment] 2023-08-06 21:24
Please share you complete capabilities object. It now seems to land on a Android Emulator

also please check your capabilities with the [Sauce Labs Platform Configurator](https://saucelabs.com/products/platform-configurator#/)
