### ISSUE TITLE
Not able to set view port width and height using browser.setViewportSize in Safari

### ISSUE THREAD

**Issue by karanbajaj2209** [webdriverio/webdriverio#2136] opened 2017-06-09 07:54 UTC
**Code in wdio.conf.js**
before: function (capabilities, specs) {
        browser.setViewportSize({
            width: 2560,
            height: 1440
        });
    },

**Logs:**
Saved screenshot: ERROR_safari_2017-06-09T06-53-00.283Z.png
Error: A request to switch to a different window could not be satisfied because the window could not be found.
    at Object.wait (....../node_modules/fibers/future.js:449:15)
    at Object.setViewportSize (....../node_modules/wdio-sync/build/index.js:278:31)
    at Object.before (....../test-framework/wdio.conf.js:212:17)
    at execHook (....../test-framework/node_modules/wdio-sync/build/index.js:157:35)

**Comment by christian-bromann** [comment] 2017-06-09 09:09
> Error: A request to switch to a different window could not be satisfied because the window could not be found.

This is not an error of WebdriverIO. Seems to be a duplicate of https://github.com/appium/appium/issues/6660

**Closed by christian-bromann** 2017-06-09 09:09 UTC
