### ISSUE TITLE
[🐛 Bug]: first N instances of workers has args from the last created worker

### ISSUE THREAD

**Issue by pharaoh-11** [webdriverio/webdriverio#8971] opened 2022-10-05 09:00 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v7.30.1

### Node.js Version

latest

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    maxInstances: 5,
    browserName: 'chrome',
    acceptInsecureCerts: true,
    'goog:chromeOptions': args: [
      '--no-sandbox',
      '--test-type=browser',
      '--ignore-certificate-errors',
      '--disable-infobars',
      '--disable-extensions',
      'verbose',
      'log-path=/tmp/chromedriver.log',
      '--start-maximized',
      '--disable-gpu',
      '--disable-dev-shm-usage',
    ],
}
```

### What happened?

I use `onWorkerStart` hook to set up all workers of parallel execution. I do it in a next way
```
onWorkerStart(cid: string, caps: any, specs: string[], args: any) {
    args.someField = [some unique needed value here];
}
```
then in each worker I receive that value from browser object like this
`const someField = (browser as any).config.someField;`
I expected that each worker has unique value but first N workers in my case 5 started at the same time and have the value from the Nth `onWorkerStart` hook. After it all looks good as different workers end in a different time, so this bug related only for first N workers

### What is your expected behavior?

Each worker should have unique value from the related `onWorkerStart` hook

### How to reproduce the bug.

To reproduce this bug create several tests that will be run in parallel and then fill wdio.conf.ts file as follows

```
export const config: WebdriverIO.Config = {
  autoCompileOpts: {
    autoCompile: true,
    tsNodeOpts: {
      transpileOnly: true,
      project: 'tsconfig.json',
    },
  },
  suites: {
    // your suites here
  },
  capabilities: [{
    maxInstances: 5, // you can use any number here but more than 1
    browserName: 'chrome',
    acceptInsecureCerts: true,
    'goog:chromeOptions': args: [
      '--no-sandbox',
      '--test-type=browser',
      '--ignore-certificate-errors',
      '--disable-infobars',
      '--disable-extensions',
      'verbose',
      'log-path=/tmp/chromedriver.log',
      '--start-maximized',
      '--disable-gpu',
      '--disable-dev-shm-usage',
    ],
  }],
  waitforTimeout: 30000,
  waitforInterval: 100,
  specFileRetriesDeferred: true,
  mochaOpts: {
    ui: 'bdd',
  },

  framework: 'mocha',
  services: ['chromedriver'],
  logLevel: 'silent',

  reporters: [['allure', {
    outputDir: // your output path here,
    disableWebdriverStepsReporting: true,
    disableWebdriverScreenshotsReporting: true,
  }]],

  onWorkerStart(cid: string, caps: any, specs: string[], args: any) {
    args.someField = [some unique value here];
 },
};
```
 

### Relevant log output

```typescript
I can't do it because it's a proprietary code
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2022-10-05 14:43
Can you provide a reproducible example in a new project so that someone can just clone and run it to inspect the behavior?

**Comment by christian-bromann** [comment] 2022-10-19 16:04
Closing due to inactivity.

**Comment by pharaoh-11** [comment] 2023-04-10 15:51
@christian-bromann can I help to fix this? I didn't see it was closed due to an unused email linked to this GitHub account, but this issue is still repeoducible. Could you please re-open it again?

**Comment by christian-bromann** [comment] 2023-04-10 19:52
Sure thing! Any help on this would be much appreciated. I think a first good step is to at least provide a reproducible example , e.g. in a new Github repository and share it here.

**Comment by pharaoh-11** [comment] 2023-04-11 11:11
I created a project to reproduce this. here is it
https://github.com/pharaoh-11/wdio-threads-bug

**Comment by pharaoh-11** [comment] 2023-04-11 11:53
@christian-bromann where can I find a tutorial or readme file how to run the local working env to try to fix this bug?

**Comment by christian-bromann** [comment] 2023-04-11 16:37
Please see https://webdriver.io/docs/contribute

**Comment by christian-bromann** [comment] 2023-04-29 19:35
I will go ahead and close this issue as I don't see any further development here. As mentioned in #10184 we recommend to use `@wdio/shared-store-service` for these use cases.

**Closed by christian-bromann** 2023-04-29 19:35 UTC
Labels: Bug 🐛, Reproducible Example Missing
