### ISSUE TITLE
[🐛 Bug]: Status 500 Target out of Bound Errors on Scroll for Safari/Firefox on BrowserStack

### ISSUE THREAD

**Issue by omegadash** [webdriverio/webdriverio#9870] opened 2023-03-01 11:58 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.3.5

### Node.js Version

16.19.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
      'bstack:options': {
        'os': 'OS X',
        'osVersion': 'Ventura',
        'resolution': '1600x1200',
      },
      'browserName': 'Safari',
},
{
      'bstack:options': {
        'os': 'OS X',
        'osVersion': 'Monterey',
        'resolution': '1600x1200',
      },
      'browserName': 'Firefox',
}
```

### What happened?

When using `$(element).scrollIntoView()` on BrowserStack OS X Safari or Firefox the following errors are displayed ```
ERROR webdriver: Request failed with status 500 due to move target out of bounds: unknown error
ERROR webdriver: Request failed with status 500 due to move target out of bounds: (1297, 2426) is out of bounds of viewport width (1600) and height (1090)
```. They do tend to slow down the test but still the scroll action is completed and the test finishes successfully. I have tried with a variety of combinations of scrollIntoView options without any success.
![2023-03-01_13-39](https://user-images.githubusercontent.com/30426888/222129115-82434aab-dbf0-4a49-8dd2-6cea033463c7.png)


### What is your expected behavior?

There should be no errors displayed or slowdowns when scrolling on BrowserStack OS X Safari or Firefox

### How to reproduce the bug.


### Relevant log output

```typescript
[0-0] 2023-03-01T11:30:12.280Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: unknown error
[0-0] 2023-03-01T11:30:21.580Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: unknown error
[1-0] 2023-03-01T11:30:22.645Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: (1297, 2426) is out of bounds of viewport width (1600) and height (1090)
[1-0] 2023-03-01T11:30:29.930Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: (1297, 2596) is out of bounds of viewport width (1600) and height (1090)
[0-0] 2023-03-01T11:30:31.437Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: unknown error
[1-0] 2023-03-01T11:30:37.517Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: (1297, 2625) is out of bounds of viewport width (1600) and height (1090)
[0-0] 2023-03-01T11:30:40.919Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: unknown error
[1-0] 2023-03-01T11:30:45.378Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: (1297, 2581) is out of bounds of viewport width (1600) and height (1090)
[0-0] 2023-03-01T11:30:50.781Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: unknown error
[1-0] 2023-03-01T11:30:53.410Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: (1297, 2573) is out of bounds of viewport width (1600) and height (1090)
[0-0] 2023-03-01T11:31:00.412Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: unknown error
[1-0] 2023-03-01T11:31:01.988Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: (1297, 2538) is out of bounds of viewport width (1600) and height (1090)
[0-0] 2023-03-01T11:31:11.979Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: unknown error
[1-0] 2023-03-01T11:31:12.040Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: (1297, 2528) is out of bounds of viewport width (1600) and height (1090)
[1-0] 2023-03-01T11:31:31.507Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: (1297, 2223) is out of bounds of viewport width (1600) and height (1090)
[0-0] 2023-03-01T11:31:38.251Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: unknown error
[1-0] 2023-03-01T11:31:38.254Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: (1297, 2432) is out of bounds of viewport width (1600) and height (1090)
[1-0] 2023-03-01T11:31:45.044Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: (1297, 2512) is out of bounds of viewport width (1600) and height (1090)
[0-0] 2023-03-01T11:31:47.634Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: unknown error
[1-0] 2023-03-01T11:31:51.971Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: (1297, 2550) is out of bounds of viewport width (1600) and height (1090)
[0-0] 2023-03-01T11:31:56.422Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: unknown error
[1-0] 2023-03-01T11:31:59.012Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: (1297, 2451) is out of bounds of viewport width (1600) and height (1090)
[0-0] 2023-03-01T11:32:05.368Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: unknown error
[1-0] 2023-03-01T11:32:06.004Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: (1297, 2511) is out of bounds of viewport width (1600) and height (1090)
[1-0] 2023-03-01T11:32:13.345Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: (1297, 2542) is out of bounds of viewport width (1600) and height (1090)
[0-0] 2023-03-01T11:32:14.962Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: unknown error
[0-0] 2023-03-01T11:32:24.188Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: unknown error
```

### Reproducible Example
Repo with a basic test that demonstrates the issue, Browserstack credentials are required:
https://github.com/omegadash/wdio_scroll_issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2023-03-01 15:37
Can you provide a minimal reproducible example?

**Comment by omegadash** [comment] 2023-03-03 13:51
> Can you provide a minimal reproducible example?

I have added a repo with it

**Comment by christian-bromann** [comment] 2023-03-03 16:01
@omegadash thank you. Feel free help us investigate.

**Comment by christian-bromann** [comment] 2023-03-30 04:08
@omegadash have you been able to find anything that could cause the issue? I am inclined to close this because it is not clear whether this is caused by WebdriverIO or the browser / cloud service.

**Comment by christian-bromann** [comment] 2023-04-29 19:27
Closing due to inactivity.

**Closed by christian-bromann** 2023-04-29 19:27 UTC
Labels: Bug 🐛, Needs Investigation, help wanted

**Comment by lidanataborda** [comment] 2023-11-24 16:50
Hi @christian-bromann and @omegadash I recently updated the framework to the last version and I'm getting the same error during the execution, have you found any solution for this? 
![image](https://github.com/webdriverio/webdriverio/assets/113041672/10fac256-84aa-4310-8cf1-6d86422d60ed)

**Comment by christian-bromann** [comment] 2023-11-24 17:38
We are looking into this as part of #11721
