### ISSUE TITLE
namespaced commands aren't added to prototype properly

### ISSUE THREAD

**Issue by CTaylor1118** [webdriverio/webdriverio#1374] opened 2016-06-08 14:34 UTC
## The problem

When you name space a command, the correct value of lastPromise is not being passed to the next command. When the command is not namespaced, I get the correct value but when it is, I get 'undefined'. I am new to promises so I am not sure if I am doing something wrong or if this is a bug in the how namespacing works.
## Environment
- WebdriverIO version: 4.0.9
- Node.js version:0.12.2
- [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Standalone
## Details

What I am trying to do is write custom assertions that take the value of the lastPromise and perform an assertion on them. Also the namespaced command always returns first so maybe it is executing before it should be.

Edit:
Taking a peek at the command history, it looks like when namespaced, the command is getting executed out of order.

Relelevent portions:
w/o namespacing:
 { name: 'url',
    args: [ 'https://www.google.com ] }
 { name: 'getUrl', args: [] },
 { name: 'url',
    args: [],
    result:
     { sessionId: 'f657eea4-8cb5-4e47-bf87-a6f892b7db42',
       status: 0,
       state: 'success',
       value: 'https://www.google.com',
       class: 'org.openqa.selenium.remote.Response',
       hCode: 1844302865 } },
 { name: 'assertEqual',
    args: [ 'https://www.google.com ] },
w/ namespacing
 { name: 'url',
    args: [ 'https://www.google.com ] }
 { name: 'assertEqual',
    args: [ 'https://www.google.com' ] },
 { name: 'getUrl', args: [] }
## Code To Reproduce Issue [ Good To Have ]

``` javascript
assertEqual = function(expected, msg) {
    var self = this;
    var lastPromise = self.lastPromise.inspect();
    if(lastPromise.state === 'fulfilled'){
      assert.equal(lastPromise.value, expected, msg);
    }
  }

browser.addCommand('assertEqual', assertEqual);
browser.addCommand('assert', 'equal', assertEqual);

browser
  .url('https://www.google.com')
  .getUrl().assertEqual('https://www.google.com') // passes. lastPromise = { state: 'fulfilled',
  value: 'https://www.collage.com/?disable_experiments=1' }
  .getUrl().assert.equal('https://www.google.com') // undefined == 'https://www.collage.com/?disable_experiments=1'. lastPromise = { state: 'fulfilled', value: undefined }
```

**Comment by christian-bromann** [comment] 2016-06-21 06:03
I would not recommend to use `lastPromise`, it is an internal object. You can try to use `getCommandHistory()` to get the result of the last command.

**Comment by CTaylor1118** [comment] 2016-06-21 13:18
There is still a problem here that the namespaced command get executed before the command earlier in the change which is not resolved by using the getCommandHistory(). I don't think the problem I am experiencing comes from the fact I am using lastPromise but instead is because the namespaced command is getting executed out of order.

**Comment by CTaylor1118** [comment] 2016-06-21 14:08
I did some more investigating and I think the problem is how namespaced commands are added. At unit.lift in webdriverio.js if a command is namespaces, then the value of this is just the commandGroup itself not the client so it does not have a value for this.promise, this.isExecuted, this.lastPromise.

**Comment by kwright1** [comment] 2016-08-03 21:40
Want to second this issue.  

For a contrived educational example, really easy to reproduce with (and verbose logging on):
```
    	browser.url('http://webdriver.io/guide.html');
    	browser.element('.doc.guide').isVisible('a=Improve this doc');
    	browser.addCommand('element', browser.element, true);
    	browser.addCommand('elements', browser.elements,true);
    	browser.element('.doc.guide').isVisible('a=Improve this doc');
```
In the first chain it correctly makes the selector for isVisible relative to the previous result.

In the second chain you'll see that when isVisible is chained into it doesn't make the selector relative because it can't find a previous result.

**Comment by christian-bromann** [comment] 2018-04-13 11:39
Name-spaced commands will get deprecated with v5. Closing!

**Closed by christian-bromann** 2018-04-13 11:39 UTC
Labels: Bug
