### ISSUE TITLE
[🐛 Bug]: <Cucumber scenario description not included in result file>

### ISSUE THREAD

**Issue by db798** [webdriverio/webdriverio#8348] opened 2022-05-16 16:26 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.16

### Node.js Version

14.19.0

### Mode

WDIO Testrunner

### What happened?

As per the cucumber documentation it's possible to add a description to Features, Scenario and other feature file properties. In the result file generated the Feature description is populated but the Scenario is not, even though the field does exist.

Cucumber related packages used
```
"@cucumber/cucumber": "^7.3.2",
"@cucumber/pretty-formatter": "1.0.0-alpha.0",
"@wdio/cucumber-framework": "7.16.5",
"wdio-cucumberjs-json-reporter": "^3.0.0",
```

wdio.conf 
```
reporters: [
    ['cucumberjs-json', {
      jsonFolder: './reports/',
      language: 'en',
    }],
    ['spec', {
      addConsoleLogs: true,
    }],
]
```

Feature File
```
Feature: My Feature

  This is my feature description

  Scenario: One
    
    This is my scenario description
    
        Given ....

  Scenario: Two

  etc.
```

Result File
```
 {
        "keyword": "Feature",
        "type": "feature",
        "description": " This is my feature description",
// more fields...
.....
"elements": [
            {
                "keyword": "Scenario",
                "type": "scenario",
                "description": "",
.....
}
```
You'll note above that the description is not set for the Scenario

### How to reproduce the bug.

Run a feature file with a description set for a scenario, the value will not be reported in your result file.

### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by db798** [comment] 2022-05-16 16:28
Without knowing much about the code I assume [this](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cucumber-framework/src/reporter.ts#L66) is the general area of the issue. But please let me know if this is an issue with one of the other packages.

**Comment by christian-bromann** [comment] 2022-05-16 16:35
Thanks for reporting!

I am not sure if the description is propagated to the reporter for the Cucumber framework.

I would see this as a feature request and if above assumption turns out to be right changes need to be applied here and in the reporter project. That said, any contributions are welcome! Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by hammzj** [comment] 2022-05-20 14:12
I have some clarification here as I've been trying to find a good way to handle sending a scenario description to reporters.

Looking at Cucumber's own documentation, a [Pickle does not include the description](https://github.com/cucumber/common/blob/main/messages/messages.md#pickle), but a [Scenario does include it](https://github.com/cucumber/common/blob/main/messages/messages.md#scenario). However, a Scenario object here is always tied with a GherkinDocument underneath a [FeatureChild](https://github.com/cucumber/common/blob/main/messages/messages.md#featurechild) or [RuleChild](https://github.com/cucumber/common/blob/main/messages/messages.md#rulechild) object.

Therefore, the problem is that the Pickle object does **not** include a `description` for a scenario -- only the GherkinDocument will include a scenario's `description` nested inside of it. When sent to a reporter, the only way to access a scenario description is from a `gherkinDocument` and doing some filtering to connect the current `pickle` to it by its `astNodeId`. It is really inconvenient and I'm not sure if I even did it properly when I attempted.


<details>
<summary>Take this feature file for example:</summary>

```gherkin
Feature: General Tests
  This is a feature description

  @simple
  Scenario: Simple
  This has a scenario description
    Given I originally have 2 cucumbers
    When I eat a cucumber
    Then I have 1 cucumber left
```
</details>


<details>
<summary>Looking at the output messages, here is the Pickle message:</summary>

```json
{
  "pickle": {
    "id": "f2ff3f62-5cf7-4f81-9966-717cb4044b76",
    "uri": "features/general.tests.feature",
    "astNodeIds": [
      "97075dfb-921e-4e96-b423-73aad5a4c7d1"
    ],
    "tags": [
      {
        "name": "@simple",
        "astNodeId": "cd13214a-3b88-428b-8e94-9fcc3315a78a"
      }
    ],
    "name": "Simple",
    "language": "en",
    "steps": [
      {
        "id": "f2843425-d2be-41ca-bd4e-dede5f1de0f8",
        "text": "I originally have 2 cucumbers",
        "astNodeIds": [
          "cd7feb8c-fc1a-4cad-b5a8-4a8b2acfb81a"
        ]
      },
      {
        "id": "b318dead-628f-4a7e-af6f-3679bba2e68e",
        "text": "I eat a cucumber",
        "astNodeIds": [
          "321d8f6d-9020-4de7-a09f-9ded80d9df48"
        ]
      },
      {
        "id": "2eb9ade2-984b-44b6-944c-905177a6b04e",
        "text": "I have 1 cucumber left",
        "astNodeIds": [
          "474992ae-e2be-49d1-88d2-664370e9a133"
        ]
      }
    ]
  }
}
```
</details>


<details>
 <summary>and here is the GherkinDocument message with descriptions for each item:</summary>

```json
{
  "gherkinDocument": {
    "feature": {
      "tags": [],
      "location": {
        "line": 1,
        "column": 1
      },
      "language": "en",
      "keyword": "Feature",
      "name": "General Tests",
      "description": "  This is a feature description",
      "children": [
        {
          "scenario": {
            "id": "97075dfb-921e-4e96-b423-73aad5a4c7d1",
            "tags": [
              {
                "location": {
                  "line": 4,
                  "column": 3
                },
                "name": "@simple",
                "id": "cd13214a-3b88-428b-8e94-9fcc3315a78a"
              }
            ],
            "location": {
              "line": 5,
              "column": 3
            },
            "keyword": "Scenario",
            "name": "Simple",
            "description": "  This has a scenario description",
            "steps": [
              {
                "id": "cd7feb8c-fc1a-4cad-b5a8-4a8b2acfb81a",
                "location": {
                  "line": 7,
                  "column": 5
                },
                "keyword": "Given ",
                "text": "I originally have 2 cucumbers"
              },
              {
                "id": "321d8f6d-9020-4de7-a09f-9ded80d9df48",
                "location": {
                  "line": 8,
                  "column": 5
                },
                "keyword": "When ",
                "text": "I eat a cucumber"
              },
              {
                "id": "474992ae-e2be-49d1-88d2-664370e9a133",
                "location": {
                  "line": 9,
                  "column": 5
                },
                "keyword": "Then ",
                "text": "I have 1 cucumber left"
              }
            ],
            "examples": []
          }
        }
      ]
    },
    "comments": [],
    "uri": "features/general.tests.feature"
  }
}
```
</details>

[Here's the example gist of the Cucumber messages formatter for the example above.](https://gist.github.com/hammzj/a382f733eb2ba3702688cce54b87c8f6)

Thus, unless you do some custom code on the GherkinDocument to retrieve the scenario description from it, it's going to be really tricky to get it. This is something for the Cucumber team to add into the `pickle` object and I'm not sure why it isn't there.

Here is how I've tried to do it in a `beforeScenario` hook:
<details>
<summary> <code>getCurrentScenarioDescription</code> </summary>

```js
function getCurrentScenarioDescription(uri, pickle) {
    const scenariosInFeature = uri
        .gherkinDocument
        .feature
        .children
        .map(c => {
            return (c.rule) ?
                c.rule.children.map(c => c.scenario) :
                c.scenario
        })
        .filter(c => c != null)
        .flat();
    const currentScenario = scenariosInFeature
        .find(s => s.name === pickle.name && pickle.astNodeIds.includes(s.id))
    return currentScenario.description;
}
```
</details>

<details>
<summary> <code>getRuleAssociatedWithCurrentScenario</code></summary>

```js
getRuleAssociatedWithCurrentScenario(uri, pickle) {
        let rule;
        const rulesInFeature = uri
            .gherkinDocument
            .feature
            .children
            .map(c => c.rule)
            .filter(r => r != null);
        rulesInFeature.forEach(r => {
            const scenarioBelongsToRule = r.children
                .map(s => s.scenario)
                .filter(s => s != null)
                .some(s => s.name === pickle.name && pickle.astNodeIds.includes(s.id))
            if (scenarioBelongsToRule) rule = r;
        })
        return rule;
    }
```
</details>

**Comment by christian-bromann** [comment] 2023-09-03 18:11
fixed by @tamil777selvan , thanks a lot!

**Closed by christian-bromann** 2023-09-03 18:11 UTC
Labels: help wanted, good first pick, Idea 💡
