### ISSUE TITLE
V5-GekoDriver 0.26 + video reporter - fails to handle alerts 

### ISSUE THREAD

**Issue by kfirbhCS** [webdriverio/webdriverio#5563] opened 2020-07-01 12:06 UTC
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** V5
 - **Mode:**  Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.13.1
 - **NPM version:** 6.12.1
 - **Browser name and version:** FF 77.0.1
 - **Platform name and version:**MAC
 - **Additional wdio packages used (if applicable):** [ @wdio/selenium-standalone service, @allure/Video-reporter]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
 failure when trying to handle alert 

0-0] 2020-07-01T12:23:09.982Z INFO webdriver: COMMAND takeScreenshot()
[0-0] 2020-07-01T12:23:09.982Z INFO webdriver: [GET] http://localhost:4444/wd/hub/session/439eea4d-ef5f-e241-acbc-957ed664eb7c/screenshot
[0-0] 2020-07-01T12:23:09.983Z INFO webdriver: COMMAND acceptAlert()
[0-0] 2020-07-01T12:23:09.984Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/439eea4d-ef5f-e241-acbc-957ed664eb7c/alert/accept
[0-0] 2020-07-01T12:23:10.009Z WARN webdriver: Request failed due to Dismissed user prompt dialog: I am alert
[0-0] 2020-07-01T12:23:10.010Z INFO webdriver: Retrying 1/3
[0-0] 2020-07-01T12:23:10.010Z INFO webdriver: [GET] http://localhost:4444/wd/hub/session/439eea4d-ef5f-e241-acbc-957ed664eb7c/screenshot
[0-0] 2020-07-01T12:23:10.012Z WARN webdriver: Request failed due to unknown error
[0-0] 2020-07-01T12:23:10.013Z INFO webdriver: Retrying 1/3
2020-07-01T12:23:10.014Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/439eea4d-ef5f-e241-acbc-957ed664eb7c/alert/accept
[0-0] 2020-07-01T12:23:10.256Z WARN webdriver: Request failed due to unknown error
[0-0] 2020-07-01T12:23:10.257Z INFO webdriver: Retrying 2/3
[0-0] 2020-07-01T12:23:10.257Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/439eea4d-ef5f-e241-acbc-957ed664eb7c/alert/accept
[0-0] 2020-07-01T12:23:10.272Z INFO webdriver: RESULT iVBORw0KGgoAAAANSUhEUgAACgAAAAZGCAYAAABj9fjdAAAgAElEQVR4nOzd+...
[0-0] 2020-07-01T12:23:10.276Z WARN webdriver: Request failed due to unknown error
[0-0] 2020-07-01T12:23:10.277Z INFO webdriver: Retrying 3/3
[0-0] 2020-07-01T12:23:10.277Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/439eea4d-ef5f-e241-acbc-957ed664eb7c/alert/accept
[0-0] 2020-07-01T12:23:10.282Z ERROR webdriver: Request failed due to no such alert: unknown error
    at getErrorFromResponseBody (/Users/kfirb/dev/dc_cs-tag-automation-test/node_modules/webdriver/build/utils.js:124:10)
    at Request._callback (/Users/kfirb/dev/dc_cs-tag-automation-test/node_modules/webdriver/build/request.js:111:64)
    at Request.self.callback (/Users/kfirb/dev/dc_cs-tag-automation-test/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.EventEmitter.emit (domain.js:475:20)
    at Request.<anonymous> (/Users/kfirb/dev/dc_cs-tag-automation-test/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:210:5)
    at Request.EventEmitter.emit (domain.js:475:20)
    at IncomingMessage.<anonymous> (/Users/kfirb/dev/dc_cs-tag-automation-test/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:299:28)
[0-0] no such alert in "Cherchertech Home Page Get title of cherchertech Home page"
unknown error

**To Reproduce**
run this code 

describe('Cherchertech Home Page', () => {
it('Get title of cherchertech Home page', () => {
browser.url('https://chercher.tech/practice/popups')
$("//input[@name='alert']").click()
browser.acceptAlert()
})
})

**Expected behavior**
alert should be accepted 

see log above

**Comment by kfirbhCS** [comment] 2020-07-01 12:42
{
  capabilities: {
    alwaysMatch: {
      browserName: 'firefox',
      browserVersion: '77.0.1',
      'goog:chromeOptions': [Object],
      'moz:firefoxOptions': [Object]
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'firefox',
    browserVersion: '77.0.1',
    'goog:chromeOptions': { w3c: false, args: [Array], prefs: [Object] },
    'moz:firefoxOptions': { args: [Array] }
  }
}
[0-0] {
  hostname: undefined,
  port: undefined,
  protocol: 'http',
  specs: [ '/Users/kfirb/dev/dc_cs-tag-automation-test/tests/unit.test.js' ],
  suites: {},
  exclude: [
    './tests/standalone.test.js',
    './tests/wdio.test.js',
    './tests/webapp.login.test.js'
  ],
  outputDir: undefined,
  logLevel: 'info',
  logLevels: {},
  excludeDriverLogs: [],
  baseUrl: undefined,
  bail: 1,
  waitforInterval: 500,
  waitforTimeout: 60000,
  framework: 'mocha',
  reporters: [ [ [Function: Video], [Object] ], [ 'allure', [Object] ] ],
  maxInstances: 10,
  maxInstancesPerCapability: 100,
  filesToWatch: [],
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  execArgv: [ '--inspect-brk=127.0.0.1:5859' ],
  runnerEnv: {},
  runner: 'local',
  featureFlags: { specFiltering: undefined },
  mochaOpts: { timeout: 120000, ui: 'bdd' },
  jasmineNodeOpts: { defaultTimeoutInterval: 10000 },
  cucumberOpts: { timeout: 10000 },
  onPrepare: [],
  before: [ [Function: bound before], [Function: bound before] ],
  beforeSession: [],
  beforeSuite: [],
  beforeHook: [],
  beforeTest: [ [Function: bound beforeTest] ],
  beforeCommand: [],
  afterCommand: [],
  afterTest: [],
  afterHook: [],
  afterSuite: [],
  afterSession: [],
  after: [],
  onComplete: [],
  onReload: [],
  beforeFeature: [],
  beforeScenario: [ [Function: bound beforeScenario] ],
  beforeStep: [],
  afterStep: [],
  afterScenario: [],
  afterFeature: [],
  loggingPrefs: { driver: 'INFO', server: 'WARNING', browser: 'INFO' },
  services: [ 'intercept' ],
  dockerOptions: undefined,
  path: undefined,
  _: [],
  spec: [ 'tests/unit.test.js' ],
  '$0': 'node_modules/.bin/wdio',
  specFileRetryAttempts: 0,
  capabilities: {
    browserName: 'firefox',
    browserVersion: '77.0.1',
    'goog:chromeOptions': { w3c: false, args: [Array], prefs: [Object] },
    'moz:firefoxOptions': { args: [Array] }
  }
}

**Comment by kfirbhCS** [comment] 2020-07-01 12:53
look like the issue caused by the video trying to take screenshots while unexpected alert pops

**Comment by christian-bromann** [comment] 2020-07-01 13:00
> Request failed due to no such alert: unknown error

This is what the errors says which means that the endpoint you are calling is not supported. Geckodriver should have support for this command by now. A minimal reproducible example would be helpful.

**Comment by kfirbhCS** [comment] 2020-07-07 15:35
> > Request failed due to no such alert: unknown error
> 
> This is what the errors says which means that the endpoint you are calling is not supported. Geckodriver should have support for this command by now. A minimal reproducible example would be helpful.

describe('Cherchertech Home Page', () => {
it('Get title of cherchertech Home page', () => {
browser.url('https://chercher.tech/practice/popups')
$("//input[@name='alert']").click()
browser.acceptAlert()
})
})

**Comment by christian-bromann** [comment] 2020-07-07 16:07
@kfirbhCS this piece of code doesn't allow me to reproduce the issue. Can you provide an example project?

**Comment by kfirbhCS** [comment] 2020-07-08 06:48
![image](https://user-images.githubusercontent.com/53476275/86885697-6233a780-c0fe-11ea-8152-8d70c925c889.png)

 i cannot provide with the full project cause its part of my workplace project

the method appears above should be good 
i even managed to reproduce on   geko 0.26

and it only reproduced with the video reporter 

![image](https://user-images.githubusercontent.com/53476275/86886716-18e45780-c100-11ea-9120-0fb014b488d8.png)

/Users/kfirb/dev/dc_cs-tag-automation-test/out/wdio-0-0.log
![image](https://user-images.githubusercontent.com/53476275/86885859-a6bf4300-c0fe-11ea-9789-bcc503af85ea.png)
![image](https://user-images.githubusercontent.com/53476275/86886011-e5ed9400-c0fe-11ea-9c1e-c0076374f1b6.png)

**Comment by christian-bromann** [comment] 2020-07-08 07:34
> i cannot provide with the full project cause its part of my workplace project

Can you please provide a new minimal project that can reproduce this? Also it seems that your using WebdriverIO v5 and the reporter says to be only compatible with v5.

**Comment by kfirbhCS** [comment] 2020-07-09 06:48
you can try and pull this 
https://github.com/kfirbhCS/webdriverIO

first start the standalone server from package.json
then run the test

**Comment by christian-bromann** [comment] 2020-07-09 07:09
@kfirbhCS Thanks for providing the example. It is likely that this fixed in v6, have you thought about updating?

**Comment by kfirbhCS** [comment] 2020-07-09 10:34
> @kfirbhCS Thanks for providing the example. It is likely that this fixed in v6, have you thought about updating?

1. Thats not super critical for me 
2. I wanted to move to V6 but there is issue with Allure that i reported in the past , that blocked me from that
3.I think the root cause of that issue is from the video reporter service trying to take screenshot when unexpected alerts pops

**Comment by christian-bromann** [comment] 2020-07-09 11:26
> I think the root cause of that issue is from the video reporter service trying to take screenshot when unexpected alerts pops

Sounds reasonable to me. While we still support v5 we don't actively fix bugs for it anymore. If you can provide a bugfix and make a PR to the `v5` branch I am happy to merge and make a new release.

**Comment by christian-bromann** [comment] 2020-08-31 09:33
Closing due to inactivity. We would love to see a PR to the `v5` branch with a fix.

**Closed by christian-bromann** 2020-08-31 09:33 UTC
Labels: Needs Investigation, help wanted, v5
