### ISSUE TITLE
Unable to upgrade chrome driver version to run tests on latest chrome browser

### ISSUE THREAD

**Issue by lemoncypress** [webdriverio/webdriverio#5747] opened 2020-08-23 23:55 UTC
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** > "^5.23.0"
 - **Mode:** [Standalone mode or WDIO Testrunner] > Jasmine
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async] >async
 - **Node.js version:** [e.g. 8.11.2] > v10.15.3
 - **NPM version:** [e.g. 5.8.0] > 6.4.1
 - **Browser name and version:** [e.g. Chrome 68] > Chrome 84.0.1
 - **Platform name and version:** [e.g. Windows 10] > Mac Catalina 10.15.6
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service] @wdio/selenium-standalone service > "^5.16.10" ; "@wdio/spec-reporter": "^5.23.0"

**Config of WebdriverIO**
Jasmine - wdio config is configured to run locally and remotely (remotely on circle CI)

**Describe the bug**
Scripts are running locally successfully with chrome browser version. But remotely they started failing. 

_[0-10] Error: Failed to create session.
session not created: This version of ChromeDriver only supports Chrome version 83
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: '830567cc7d10', ip: '192.168.80.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1077-aws', java.version: '11.0.6'
Driver info: driver.version: ChromeDriver
remote stacktrace: #0 0x55786a87f579 <unknown>_

We are not sure where to make changes to update the chrome driver.

**To Reproduce**
Steps to reproduce the behavior. We tried:
1. Adding a dependency for "wdio-chromedriver-service": "^6.0.0" > we saw an error

2. Adding a dependency for "chromedriver": "84.0.1" > we saw an error (refer error screenshot)

![image](https://user-images.githubusercontent.com/48631861/90991899-64e93f80-e57a-11ea-8e76-5ae7234c4e3d.png)

3. Updating
seleniumInstallArgs: {
version: '3.5.3'
},
seleniumArgs: {
version: '3.5.3'
}
from 3.4.0 to 3.5.3 (which we read from the docker config) > but it didn't work

4. Adding a config file called .npmrc, install the chromedriver and force the download when the execution starts > no luck!!

[Include code or an example repository that can easily be set up]

**Expected behavior**
Tests to run successfully remotely on circle CI.
We are running out of ideas. Please guide us on how to go about this. This issue started when the remote server we run tests on got upgraded to a newer version automatically.

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment] 2020-08-24 08:03
Duplicate of giggio/node-chromedriver#282

Closing as this needs to be fixed within the dependency.

**Closed by christian-bromann** 2020-08-24 08:03 UTC

**Comment by lemoncypress** [comment] 2020-08-24 18:28
Hi @christian-bromann , Within the dependency as in?

**Comment by christian-bromann** [comment] 2020-08-24 19:50
This needs to be fixed in the project linked above which is consumed by the `wdio-chromedriver-service`.

**Comment by eddivalen** [comment] 2020-08-28 16:37
Hey @christian-bromann  is this still in progress?

**Comment by christian-bromann** [comment] 2020-08-28 16:43
The [issue](https://github.com/giggio/node-chromedriver/issues/282) is still open so I assume yes.

**Comment by balukov** [comment] 2020-08-31 16:24
There is a temporary workaround - to add drivers version for selenium-standalone service
````
  services: [
    [
      "selenium-standalone",
      {
        logPath: "logs",
        installArgs: {
          version: "3.141.5",
          baseURL: "https://selenium-release.storage.googleapis.com",
          drivers: {
            chrome: {
              version: "85.0.4183.83",
              arch: process.arch,
              baseURL: "https://chromedriver.storage.googleapis.com",
            },
          },
        },
        args: {
          version: "3.141.5",
          drivers: {
            chrome: {
              version: "85.0.4183.83",
              arch: process.arch,
            },
          },
        },
      },
    ],
],
````

**Comment by eddivalen** [comment] 2020-08-31 17:01
I'm still getting the same error from above @balukov

**Comment by balukov** [comment] 2020-09-10 08:15
> I'm still getting the same error from above

This is strange, it helps me and a couple of my colleagues.
