### ISSUE TITLE
Getting error : Request failed with status 200 due to Response has empty body

### ISSUE THREAD

**Issue by advait012** [webdriverio/webdriverio#7325] opened 2021-08-24 05:11 UTC
- **WebdriverIO version:** 6.0.0
 - **Mode:** Standalone mode
 - **Node.js version:** 14.0.0
 - **NPM version:** 6.14.4
 - **Browser name and version:** Chrome 91
 - **Platform name and version:** Windows 10

**Config of WebdriverIO**
We are using gauge tests automation framework as a test runner . For creating sessions in webdriver , We are creating capabilities of browser and passing in the remote method of webdriverIO

**Describe the bug**
On Running the gauge tests , we are getting this error :- webdriver: Request failed with status 200 due to Response has empty body
![3f38227d-c678-4ba2-9fa0-15598b7f9974](https://user-images.githubusercontent.com/42748081/130559248-e16ba37b-1728-4696-995d-aaadbaf801ac.PNG)

**Note :- We are using automation protocol as 'Webdriver', But we change it to dev tools , It is working fine**
> Please use the correct markdown

**Comment by christian-bromann** [comment] 2021-08-24 06:53
Duplicate of #6881

**Closed by christian-bromann** 2021-08-24 06:53 UTC
