### ISSUE TITLE
With allure-reported added, I get "RangeError: Invalid typed array length" when browser.execute() returns long integer

### ISSUE THREAD

**Issue by f3ngi** [webdriverio/webdriverio#4961] opened 2020-01-15 15:12 UTC
**Deps versions:**
"webdriverio": "5.18.4"
"@wdio/allure-reporter": "5.16.16"

I just added `allure-reporter` to my project. Now, when I run a test like this (which I had no issues with previously):
```
it("test", function () {
    browser.execute("return Date.now()");
});
```
that returns long integer, then I get the following error:
```
RangeError: Invalid typed array length: 1579099031883
    at typedArrayConstructByLength (&lt;anonymous>)
    at new Uint8Array (native)
    at module.exports.input (/me/wdio/node_modules/allure-js-commons/node_modules/file-type/index.js:8:54)
    at Object.getBufferInfo (/me/wdio/node_modules/allure-js-commons/util.js:6:24)
    at Allure.addAttachment (/me/wdio/node_modules/allure-js-commons/index.js:83:21)
    at AllureReporter.dumpJSON (/me/wdio/node_modules/@wdio/allure-reporter/build/index.js:478:17)
    at AllureReporter.onAfterCommand (/me/wdio/node_modules/@wdio/allure-reporter/build/index.js:244:14)
    at reporters.forEach.reporter (/me/wdio/node_modules/@wdio/runner/build/reporter.js:38:49)
    at Array.forEach (&lt;anonymous>)
    at BaseReporter.emit (/me/wdio/node_modules/@wdio/runner/build/reporter.js:38:20)
    at EventEmitter.browser.on.result (/me/wdio/node_modules/@wdio/runner/build/index.js:199:50)
    at Browser.WebDriver.prototype.(anonymous function) [as emit] (/me/wdio/node_modules/@wdio/utils/build/monad.js:130:33)
    at Object.dateNow (/me/wdio/utils/inBrowserScripts.js:1:93)
    at Context.&lt;anonymous> (/me/wdio/specs/test.spec.js:409:44)
```
where the `1579099031883` (that is suposed to be the mentioned array length is the value that is returned by the `browser.execute(..)` command.

I didn't find any restrictions mentioned in the `browser.execute` documentation regarding the returned data type, so this looks like a bug in the `allure-reporter` to me.

That would be great if you could check it.

Btw. I found a workaround that is to wrap the result of `Date.now()` in an object:
```
it("test", function () {
    browser.execute(() => ({ now: Date.now() })).now
});
```

Thanks!

**Comment by BorisOsipov** [comment] 2020-01-15 15:29
Actually issue in third party dependency of third party dependency... Not sure we can fix it without contribution to `allure-js-commons` package.

Workaround use `disableWebdriverStepsReporting: true` in config. See https://github.com/webdriverio/webdriverio/blob/56dd669fd4b9bfb13d9c65c9d0170a740239e24f/packages/wdio-allure-reporter/README.md#configuration

**Comment by f3ngi** [comment] 2020-01-15 15:31
I've just edited my post mentioning another workaround I found.

**Comment by baruchvlz** [comment] 2020-01-29 18:39
If the issue is a third party library as @BorisOsipov mentioned and also considering there has be no traffic here for 14 days, could we close this issue?

**Comment by christian-bromann** [comment] 2020-01-30 23:18
I will go ahead and close this as it is not related to WebdriverIO.

**Closed by christian-bromann** 2020-01-30 23:18 UTC
