### ISSUE TITLE
Css selector not preserving scope of current element

### ISSUE THREAD

**Issue by bennieswart** [webdriverio/webdriverio#2625] opened 2018-03-01 18:53 UTC
## The problem

It seems that when chaining css selectors the scope of the chained selector is not always limited to the current element.

Consider the following code:

HTML:
```html
<div class="outer accordion">
    <div class="outer accordion-section">
        <div class="middle accordion">
            <div class="middle accordion-section">
                <div class="inner accordion">
                    <div class="inner accordion-section">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
```
JS:
```js
let midacc = browser.$('.accordion .accordion-section .accordion');
                                                                                                                                                                   
let innersec = midacc.$$('.accordion-section .accordion .accordion-section');
console.log(innersec.length); // 2
console.log(innersec[0].getAttribute('class')); // middle accordion-section
console.log(innersec[1].getAttribute('class')); // inner accordion-section
                                                                                                                                                                   
innersec = midacc.$$(".//*[contains(@class, 'accordion-section')]//*[contains(concat(' ', @class, ' '), 'accordion')]//*[contains(@class, 'accordion-section')]");
console.log(innersec.length); // 1
console.log(innersec[0].getAttribute('class')); // inner accordion-section
```

In the code, `midacc` is the `middle accordion` element. Using `midacc` as base, an attempt is made to select `inner accordion-section`, but instead, `middle accordion-section` is also selected. It seems as though the last selection was performed in the global scope instead of the `middle accordion` scope.
When replacing the css selector with an identical (enough) xpath selector, only `inner accordion-section` is returned, as expected.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 9.6.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): wdio-mocha-framework
* Chromedriver version: 2.33.2
* Selenium version: 3.9.1 (also tested on 3.4.0)

## Logs
Since the logs are short I'll put them here directly.

Selenium logs:
```
20:47:18.147 INFO - Selenium build info: version: '3.9.1', revision: '63f7b50'
20:47:18.148 INFO - Launching a standalone Selenium Server on port 4444
2018-03-01 20:47:18.215:INFO::main: Logging initialized @259ms to org.seleniumhq.jetty9.util.log.StdErrLog
2018-03-01 20:47:18.307:INFO:osjs.Server:main: jetty-9.4.7.v20170914, build timestamp: 2017-11-21T23:27:37+02:00, git hash: 82b8fb23f757335bb3329d540ce37a2a2615f0a8
2018-03-01 20:47:18.328:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@210366b4{/,null,STARTING} has uncovered http methods for path: /
2018-03-01 20:47:18.331:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@210366b4{/,null,AVAILABLE}
2018-03-01 20:47:18.346:INFO:osjs.AbstractConnector:main: Started ServerConnector@76707e36{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
2018-03-01 20:47:18.346:INFO:osjs.Server:main: Started @390ms
20:47:18.346 INFO - Selenium Server is up and running on port 4444
2018-03-01 20:47:19.511:INFO:osjshC.ROOT:qtp124313277-15: org.openqa.selenium.remote.server.WebDriverServlet-14acaea5: Initialising WebDriverServlet
20:47:19.570 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.BeginSession@db4f52d
20:47:19.573 INFO - /session: Executing POST on /session (handler: BeginSession)
20:47:19.645 INFO - Capabilities are: Capabilities {browserName: chrome, chromeOptions: {args: []}, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., maxInstances: 4, requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.8.0}, rotatable: true}
20:47:19.647 INFO - Capabilities {browserName: chrome, chromeOptions: {args: []}, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., maxInstances: 4, requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.8.0}, rotatable: true} matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4) on port 9007
Only local connections are allowed.
20:47:20.393 INFO - Detected dialect: OSS
20:47:20.772 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@5d2b5783
20:47:20.773 INFO - Handler thread for session 1f461b9c4ba54823fd2af102076b5792 (chrome): Executing POST on /session/1f461b9c4ba54823fd2af102076b5792/window/current/size (handler: ServicedSession)
20:47:20.776 INFO - To upstream: {"width":1280,"height":720}
20:47:20.897 INFO - To downstream: {"sessionId":"1f461b9c4ba54823fd2af102076b5792","status":0,"value":null}
20:47:20.914 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@5d2b5783
20:47:20.914 INFO - Handler thread for session 1f461b9c4ba54823fd2af102076b5792 (chrome): Executing POST on /session/1f461b9c4ba54823fd2af102076b5792/url (handler: ServicedSession)
20:47:20.915 INFO - To upstream: {"url":"file:///home/staple/Desktop/test.html"}
20:47:20.972 INFO - To downstream: {"sessionId":"1f461b9c4ba54823fd2af102076b5792","status":0,"value":null}
20:47:20.982 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@5d2b5783
20:47:20.982 INFO - Handler thread for session 1f461b9c4ba54823fd2af102076b5792 (chrome): Executing POST on /session/1f461b9c4ba54823fd2af102076b5792/element (handler: ServicedSession)
20:47:20.983 INFO - To upstream: {"using":"css selector","value":".accordion .accordion-section .accordion"}
20:47:20.999 INFO - To downstream: {"sessionId":"1f461b9c4ba54823fd2af102076b5792","status":0,"value":{"ELEMENT":"0.6081251373409386-1"}}
20:47:21.031 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@5d2b5783
20:47:21.031 INFO - Handler thread for session 1f461b9c4ba54823fd2af102076b5792 (chrome): Executing POST on /session/1f461b9c4ba54823fd2af102076b5792/element/0.6081251373409386-1/elements (handler: ServicedSession)
20:47:21.032 INFO - To upstream: {"using":"css selector","value":".accordion-section .accordion .accordion-section"}
20:47:21.047 INFO - To downstream: {"sessionId":"1f461b9c4ba54823fd2af102076b5792","status":0,"value":[{"ELEMENT":"0.6081251373409386-2"},{"ELEMENT":"0.6081251373409386-3"}]}
20:47:21.057 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@5d2b5783
20:47:21.057 INFO - Handler thread for session 1f461b9c4ba54823fd2af102076b5792 (chrome): Executing GET on /session/1f461b9c4ba54823fd2af102076b5792/element/0.6081251373409386-2/attribute/class (handler: ServicedSession)
20:47:21.063 INFO - To downstream: {"sessionId":"1f461b9c4ba54823fd2af102076b5792","status":0,"value":"middle accordion-section"}
20:47:21.071 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@5d2b5783
20:47:21.072 INFO - Handler thread for session 1f461b9c4ba54823fd2af102076b5792 (chrome): Executing GET on /session/1f461b9c4ba54823fd2af102076b5792/element/0.6081251373409386-3/attribute/class (handler: ServicedSession)
20:47:21.078 INFO - To downstream: {"sessionId":"1f461b9c4ba54823fd2af102076b5792","status":0,"value":"inner accordion-section"}
20:47:21.085 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@5d2b5783
20:47:21.086 INFO - Handler thread for session 1f461b9c4ba54823fd2af102076b5792 (chrome): Executing POST on /session/1f461b9c4ba54823fd2af102076b5792/element/0.6081251373409386-1/elements (handler: ServicedSession)
20:47:21.087 INFO - To upstream: {"using":"xpath","value":".//*[contains(@class, 'accordion-section')]//*[contains(concat(' ', @class, ' '), 'accordion')]//*[contains(@class, 'accordion-section')]"}
20:47:21.103 INFO - To downstream: {"sessionId":"1f461b9c4ba54823fd2af102076b5792","status":0,"value":[{"ELEMENT":"0.6081251373409386-3"}]}
20:47:21.110 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@5d2b5783
20:47:21.111 INFO - Handler thread for session 1f461b9c4ba54823fd2af102076b5792 (chrome): Executing GET on /session/1f461b9c4ba54823fd2af102076b5792/element/0.6081251373409386-3/attribute/class (handler: ServicedSession)
20:47:21.115 INFO - To downstream: {"sessionId":"1f461b9c4ba54823fd2af102076b5792","status":0,"value":"inner accordion-section"}
20:47:21.121 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@5d2b5783
20:47:21.121 INFO - Handler thread for session 1f461b9c4ba54823fd2af102076b5792 (chrome): Executing POST on /session/1f461b9c4ba54823fd2af102076b5792/execute_async (handler: ServicedSession)
20:47:21.122 INFO - To upstream: {"script":"return (done => done(JSON.stringify(window.__coverage__))).apply(null, arguments)","args":[]}
20:47:21.130 INFO - To downstream: {"sessionId":"1f461b9c4ba54823fd2af102076b5792","status":0,"value":null}
20:47:21.248 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@5d2b5783
20:47:21.248 INFO - Handler thread for session 1f461b9c4ba54823fd2af102076b5792 (chrome): Executing DELETE on /session/1f461b9c4ba54823fd2af102076b5792 (handler: ServicedSession)
20:47:21.302 INFO - To downstream: {"sessionId":"1f461b9c4ba54823fd2af102076b5792","status":0,"value":null}
20:47:21.305 INFO - Removing session org.openqa.selenium.remote.server.ServicedSession@5d2b5783
20:47:21.306 INFO - To downstream: {"sessionId":"1f461b9c4ba54823fd2af102076b5792","status":0,"value":null}
```

WebdriverIO logs:
```
[20:47:19]  COMMAND	POST 	 "/wd/hub/session"
[20:47:19]  DATA		{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"maxInstances":4,"browserName":"chrome","chromeOptions":{"args":[]},"loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.8.0","name":"webdriverio"}}}
[20:47:20]  INFO	SET SESSION ID 1f461b9c4ba54823fd2af102076b5792
[20:47:20]  RESULT		{"applicationCacheEnabled":false,"rotatable":false,"mobileEmulationEnabled":false,"networkConnectionEnabled":false,"chrome":{"chromedriverVersion":"2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4)","userDataDir":"/tmp/.org.chromium.Chromium.6DKNg6"},"takesHeapSnapshot":true,"pageLoadStrategy":"normal","databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":false,"version":"63.0.3239.84","platform":"Linux","browserConnectionEnabled":false,"nativeEvents":true,"acceptSslCerts":true,"locationContextEnabled":true,"webStorageEnabled":true,"browserName":"chrome","takesScreenshot":true,"javascriptEnabled":true,"cssSelectorsEnabled":true,"setWindowRect":true,"unexpectedAlertBehaviour":"","webdriver.remote.sessionid":"1f461b9c4ba54823fd2af102076b5792"}
[20:47:20]  COMMAND	POST 	 "/wd/hub/session/1f461b9c4ba54823fd2af102076b5792/window/current/size"
[20:47:20]  DATA		{"width":1280,"height":720}
[20:47:20]  COMMAND	POST 	 "/wd/hub/session/1f461b9c4ba54823fd2af102076b5792/url"
[20:47:20]  DATA		{"url":"file:///home/staple/Desktop/test.html"}
[20:47:20]  COMMAND	POST 	 "/wd/hub/session/1f461b9c4ba54823fd2af102076b5792/element"
[20:47:20]  DATA		{"using":"css selector","value":".accordion .accordion-section .accordion"}
[20:47:21]  RESULT		{"ELEMENT":"0.6081251373409386-1"}
[20:47:21]  COMMAND	POST 	 "/wd/hub/session/1f461b9c4ba54823fd2af102076b5792/element/0.6081251373409386-1/elements"
[20:47:21]  DATA		{"using":"css selector","value":".accordion-section .accordion .accordion-section"}
[20:47:21]  RESULT		[{"ELEMENT":"0.6081251373409386-2"},{"ELEMENT":"0.6081251373409386-3"}]
[20:47:21]  COMMAND	GET 	 "/wd/hub/session/1f461b9c4ba54823fd2af102076b5792/element/0.6081251373409386-2/attribute/class"
[20:47:21]  DATA		{}
[20:47:21]  RESULT		"middle accordion-section"
[20:47:21]  COMMAND	GET 	 "/wd/hub/session/1f461b9c4ba54823fd2af102076b5792/element/0.6081251373409386-3/attribute/class"
[20:47:21]  DATA		{}
[20:47:21]  RESULT		"inner accordion-section"
[20:47:21]  COMMAND	POST 	 "/wd/hub/session/1f461b9c4ba54823fd2af102076b5792/element/0.6081251373409386-1/elements"
[20:47:21]  DATA		{"using":"xpath","value":".//*[contains(@class, 'accordion-section')]//*[contains(concat(' ', @class, ' '), 'accordion')]//*[contains(@class, 'accordion-section')]"}
[20:47:21]  RESULT		[{"ELEMENT":"0.6081251373409386-3"}]
[20:47:21]  COMMAND	GET 	 "/wd/hub/session/1f461b9c4ba54823fd2af102076b5792/element/0.6081251373409386-3/attribute/class"
[20:47:21]  DATA		{}
[20:47:21]  RESULT		"inner accordion-section"
[20:47:21]  COMMAND	POST 	 "/wd/hub/session/1f461b9c4ba54823fd2af102076b5792/execute_async"
[20:47:21]  DATA		{"script":"return (done => done(JSON.stringify(window.__coverage__))).apply(null, arguments)","args":[]}
[20:47:21]  COMMAND	DELETE 	 "/wd/hub/session/1f461b9c4ba54823fd2af102076b5792"
[20:47:21]  DATA		{}
```

**Comment by christian-bromann** [comment] 2018-03-05 14:58
Yup, duplicate of #2185

**Closed by christian-bromann** 2018-03-05 14:58 UTC

**Comment by christian-bromann** [comment] 2018-03-05 15:05
Mhm, according to the logs it actually used the element scope. So first you were looking for `.accordion .accordion-section .accordion`:

```
20:47:20.982 INFO - Handler thread for session 1f461b9c4ba54823fd2af102076b5792 (chrome): Executing POST on /session/1f461b9c4ba54823fd2af102076b5792/element (handler: ServicedSession)
20:47:20.983 INFO - To upstream: {"using":"css selector","value":".accordion .accordion-section .accordion"}
20:47:20.999 INFO - To downstream: {"sessionId":"1f461b9c4ba54823fd2af102076b5792","status":0,"value":{"ELEMENT":"0.6081251373409386-1"}}
```

Which returned with the correct element: `0.6081251373409386-1`. Then you looked for `.accordion-section .accordion .accordion-section` within that element `0.6081251373409386-1`:

```
20:47:21.031 INFO - Handler thread for session 1f461b9c4ba54823fd2af102076b5792 (chrome): Executing POST on /session/1f461b9c4ba54823fd2af102076b5792/element/0.6081251373409386-1/elements (handler: ServicedSession)
20:47:21.032 INFO - To upstream: {"using":"css selector","value":".accordion-section .accordion .accordion-section"}
```

So it looks like the requests on WebdriverIO side were correct but Chrome got confused.

**Comment by bennieswart** [comment] 2018-03-05 15:10
@christian-bromann yes I noticed that as well. I'm not convinced that this is indeed a webdriverio bug, but I'm not familiar enough with the codebase to say so definitively.

Perhaps you could investigate whether the problem lies with selenium or chromedriver, or perhaps somewhere else, and report it there. I could do it, but it would take you much less time and you can speak with more authority in the bug report :)

**Comment by christian-bromann** [comment] 2018-03-05 15:12
> whether the problem lies with selenium

This project doesn't use the selenium-bindings, so we can scratch that

> or chromedriver,

Yeah this is what I am seeing here. So I guess it might be the best idea to report this to the chromedriver folks
