### ISSUE TITLE
Error on 'npx wdio config' command

### ISSUE THREAD

**Issue by red-sight** [webdriverio/webdriverio#7428] opened 2021-09-15 09:22 UTC
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2] 7.12.5
 - **Mode:** [Standalone mode or WDIO Testrunner] not initialized
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** [e.g. 8.11.2] 12.21.0
 - **NPM version:** [e.g. 5.8.0] 7.18.1
 - **Browser name and version:** [e.g. Chrome 68] not initialized
 - **Platform name and version:** [e.g. Windows 10] Ubuntu 21.04
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service] not initialized

**Config of WebdriverIO**
An example of how you configured WebdriverIO config not initialized

**Describe the bug**
After the installing the WDIO with 'npm install @wdio/cli' into the project, getting the error on initializing the project with npx wdio config. The response is:
```
.../node_modules/@wdio/cli/node_modules/inquirer/lib/prompts/rawlist.js:126
      this.selected = this.selected ?? -1;
                                     ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Function.promptModule.restoreDefaultPrompts (.../node_modules/@wdio/cli/node_modules/inquirer/lib/inquirer.js:65:36)
    at Object.inquirer.createPromptModule (/home/dm/code/novatum-ui/node_modules/@wdio/cli/node_modules/inquirer/lib/inquirer.js:72:16)
    at Object.<anonymous> (.../node_modules/@wdio/cli/node_modules/inquirer/lib/inquirer.js:84:28)
``` 

**To Reproduce**
npm install @wdio/cli
npx wdio config

[Include code or an example repository that can easily be set up]

**Expected behavior**
Initializing the setup

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment] 2021-09-15 09:38
Duplicate of https://github.com/SBoudrias/Inquirer.js/issues/1046. Please follow that issue.

**Comment by christian-bromann** [comment] 2021-09-15 09:39
I will publish a new `@wdio/cli` version with a pinned `inquirer` version.

**Closed by christian-bromann** 2021-09-15 09:38 UTC

**Comment by red-sight** [comment] 2021-09-15 10:19
@christian-bromann 
TY

**Comment by splurgeop** [comment] 2021-09-15 13:25
@any update on this?
do we have any newer version with the bug fixed available

**Comment by red-sight** [comment] 2021-09-15 13:29
@splurgeop 

Temporarily you can open this file where the error points to and replace this
```
this.selected = this.selected ?? -1;
``` 
with
```
this.selected = this.selected ? this.selected : -1;
```

**Comment by christian-bromann** [comment] 2021-09-15 15:50
@splurgeop just install the latest version of `@wdio/cli`
