### ISSUE TITLE
[📖 Docs]: Flowchart is broken

### ISSUE THREAD

**Issue by viktor-silakov** [webdriverio/webdriverio#9887] opened 2023-03-06 04:09 UTC
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Other

### Description of the improvement / report

I want to immerse myself more in the development of a WDIO as a contributor, for this I need to study more internals, but I ran into a problem the flowchart is broken on the site https://webdriver.io/docs/flowcharts/wdiocommands There are no images in any section.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment] 2023-03-06 05:16
Duplicate of #6540

Would you like to tackle this issue as first issue? Happy to provide support if needed.

**Comment by christian-bromann** [comment] 2023-03-06 05:17
FYI: you can find the flowcharts here: https://v6.webdriver.io/docs/flowchartsoverview.html but not sure how accurate these are.

**Closed by christian-bromann** 2023-03-06 05:16 UTC
Labels: Docs 📖, Needs Triaging ⏳
