### ISSUE TITLE
[🐛 Bug]: @wdio-junit-reporter does not work on WDIO v8 TypeScript

### ISSUE THREAD

**Issue by hpos-oazofeifa** [webdriverio/webdriverio#9536] opened 2023-01-04 15:06 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

18

### Mode

WDIO Testrunner

### What happened?

Upgraded to WebdriverIO 8 with TypeScript and the test wont launch, due to `junit-reporter` cannot be initialized.

### How to reproduce the bug.

Upgrade to WDIO v8 & TypeScript 

Execute any test.

### Relevant log output

```typescript
[0-0] 2023-01-04T15:02:10.563Z ERROR @wdio/local-runner: Failed launching test session: Error: Couldn't initialise "@wdio/junit-reporter".
[0-0] ... `node_modules/validator/es/index.js:1`
[0-0] import toDate from './lib/toDate';
[0-0] ^^^^^^
[0-0] 
[0-0] SyntaxError: Cannot use import statement outside a module
[0-0]     at Object.compileFunction (node:vm:352:18)
[0-0]     at wrapSafe (node:internal/modules/cjs/loader:1032:15)
[0-0]     at Module._compile (node:internal/modules/cjs/loader:1067:27)
[0-0]     at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
[0-0]     at Object.require.extensions.<computed> [as .js] (... node_modules/ts-node/src/index.ts:1608:43)
[0-0]     at Module.load (node:internal/modules/cjs/loader:981:32)
[0-0]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[0-0]     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
[0-0]     at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
[0-0]     at async Promise.all (index 0)
[0-0]     at safeImport (file:///.../node_modules/@wdio/utils/build/utils.js:210:15)
[0-0]     at async initialisePlugin (file:///.../node_modules/@wdio/utils/build/initialisePlugin.js:25:26)
[0-0]     at async BaseReporter._loadReporter (file:///.../node_modules/@wdio/runner/build/reporter.js:178:30)
[0-0]     at async Promise.all (index 2)
[0-0]     at async BaseReporter.initReporters (file:///.../node_modules/@wdio/runner/build/reporter.js:23:27)
[0-0]     at async Runner.run (file:///.../node_modules/@wdio/runner/build/index.js:68:9)
[0-0] /.../node_modules/validator/es/index.js:1
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2023-01-04 22:19
Hey @hpos-oazofeifa , thanks for raising the issue.

Note that `@wdio/junit-reporter` v8 is ESM only and it seems that your have a CJS project. I am not sure why you are importing the package but make sure your are using ESM. I will close this as I don't see any issues with the reporter.

Let me know if you have further questions.

**Comment by redonkulus** [comment] 2023-01-06 17:05
@christian-bromann Does this run counter to the statement in the v8 release? https://webdriver.io/blog/2022/12/01/webdriverio-v8-released/#commonjs-to-esm-transition

We are still on CJS, we are not using `@wdio/junit-reporter` directly, only via this code in the wdio config file: `reporters: ['spec', ['junit', { outputDir: TEST_DIR }]],`.

**Comment by christian-bromann** [comment] 2023-01-06 17:14
You should be able to use the reporter within a CJS project.

**Comment by hpos-oazofeifa** [comment] 2023-01-06 17:25
@christian-bromann I don't think that's the case once you upgrade to WebdriverIo v8 you won't be able to compile any CommonJS projects, it will start breaking.

For example if you have a dependency on `shared-storage` service, it wont compile on CommonJS and then the junior reported won't work

**Comment by christian-bromann** [comment] 2023-01-06 17:32
> For example if you have a dependency on `shared-storage` service,

This service comes with a CJS export.

**Comment by redonkulus** [comment] 2023-01-06 17:36
@christian-bromann do you mind trying on a CJS project to see if you replicate the error we are having?

**Comment by christian-bromann** [comment] 2023-01-06 17:37
@redonkulus I think it would be easier if you can share a minimal reproducible example.

**Comment by redonkulus** [comment] 2023-01-06 17:46
If I get time, I could try. To work around this, I'm removing the junit reporter since it's not actually required for my project.

**Comment by pwespi** [comment] 2023-01-06 18:24
We are getting the same error with `"@wdio/junit-reporter": "8.1.0"`, however `"@wdio/junit-reporter": "8.0.14"` works.

**Comment by pwespi** [comment] 2023-01-06 18:36
I think the problem is this line:
https://github.com/webdriverio/webdriverio/blob/4278ae6b82409e762fb64a12affbcf6be78286e7/packages/wdio-junit-reporter/src/utils.ts#L2

@christian-bromann Is there a reason why it is not just `import validator from 'validator'`?

**Comment by pwespi** [comment] 2023-01-06 18:47
> I think the problem is this line:
> 
> https://github.com/webdriverio/webdriverio/blob/4278ae6b82409e762fb64a12affbcf6be78286e7/packages/wdio-junit-reporter/src/utils.ts#L2
> 
> @christian-bromann Is there a reason why it is not just `import validator from 'validator'`?

I tested locally and can confirm that changing the import to `import validator from 'validator'` fixes the problem in our project.

See PR #9542

**Comment by Xetoris** [comment] 2023-01-10 06:18
I'm not sure if it's helpful anymore, but I sat down and threw together an example project that generates the error:

https://github.com/Xetoris/wdio-v8-junit-error-example#description

If it's not helpful, let me know and I can delete this comment! If you have any questions, let me know.

**Comment by esaari** [comment] 2023-01-10 20:13
@christian-bromann Is it possible to reopen this issue until a fix is in place? I ran into the same issue and was about to open a duplicate issue until this issue was pointed out to me.

**Comment by AndyLysenko** [comment] 2023-01-12 14:06
I vote for this. Our update to werdriverio v8 is blocked by this.

**Comment by esaari** [comment] 2023-01-12 18:57
@AndyLysenko downgrading to `v8.0.14" was a successful workaround for me.

**Comment by SCG82** [comment] 2023-01-13 02:03
https://github.com/validatorjs/validator.js/pull/2147 is needed

**Closed** 2023-01-15 10:23 UTC
Labels: Bug 🐛, help wanted

**Comment by AndyLysenko** [comment] 2023-01-18 08:41
When will we have new version available on npm?

**Comment by christian-bromann** [comment] 2023-01-18 16:13
> When will we have new version available on npm?

Soon™

**Comment by fatkobra** [comment] 2023-01-24 19:30
downgrading to `@wdio/junit-reporter@8.0.14` did not fix the empty xml test results file for me. I am still getting it.

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites/>
```

**Comment by christian-bromann** [comment] 2023-03-24 18:51
@lbett most often an issue is closed because it got fixed or a sub problem is being tracked in a different issue. The original issue got fixed in #9586. You likely experience other issues that are tracked somewhere else, e.g. folks reported #9352 which got fixed in #10035. So maybe try with the latest version of WebdriverIO.

**Comment by nair-sumesh** [comment] 2024-01-18 22:03
Issue still exists with 8.27.0

**Comment by christian-bromann** [comment] 2024-01-18 22:04
@nair-sumesh please provide a reproducible example, thanks!

**Comment by nair-sumesh** [comment] 2024-01-21 17:39
Fount the issue.

The generated file `junit.xml` only stores the last executed feature file.
In my case there are **3** feature files executed sequentially (maxInstances = 1).
On each execution of the feature file, the `junit.xml` is **overwritten** with the values of that particular feature file.
So, when I execute the test with a TAG (due to which the third feature file is skipped), the `junit.xml` is always **empty**.

### Config
```js
   ['junit', {
      outputDir: "./reports",
      errorOptions: {
        error: 'message',
        failure: 'message',
        stacktrace: 'stack'
      },
      outputFileFormat: function (options) { // optional
        return `junit.xml`
      }
    }]
```

# Problem
`junit.xml` should not be cleared at begin of each feature file.     
Instead , it should be **cleared** one time at the begining ( like in onPrepare method) and **appended** at the begin of each feature execution.

**Comment by christian-bromann** [comment] 2024-01-21 19:44
@nair-sumesh if you define a `outputFileFormat` you have to make sure that the filename is different for every worker. This is why you have the `options` parameter. I recommend not to use the option since your name is similar to the default name.

**Comment by shussaincalrom** [comment] 2024-07-31 05:17
@christian-bromann  

I am using JUnit report with WebDriverIO. This is my current code, which generates a report named 'results-0.0.xml'
![image](https://github.com/user-attachments/assets/a0bf34da-551f-4bbd-9844-fc223c779677)

But I want to replace this with **test Name**  which is currently running is it possible?
![image](https://github.com/user-attachments/assets/c96ba0ef-f9a1-46e8-ba85-2f7cd1126ffd)

I have read the documentation of WebDriverIO. According to it, we can read the **capabilities**, but when I tried this, I got a compile-time error and was unable to read any properties of the **capabilities** . please have a look at attached files
![image](https://github.com/user-attachments/assets/e963cad8-1d70-4f09-9406-2c5ac9c32c90)

![image](https://github.com/user-attachments/assets/2c4fc8d9-c138-4a80-a2c8-e3e4b1694614)

**Comment by christian-bromann** [comment] 2024-07-31 21:11
@shussaincalrom `filename` is not a valid capability.

**Comment by christian-bromann** [comment] 2024-08-01 18:06
The file name may not be available, please raise a PR adding that information to the function payload.

**Comment by christian-bromann** [comment] 2024-09-15 08:51
I've never used Azure so I won't be able to help on this.
