### ISSUE TITLE
WDIO - V5- TypeScripte and Allure 

### ISSUE THREAD

**Issue by kfirbhCS** [webdriverio/webdriverio#5172] opened 2020-03-30 12:14 UTC
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.22.1
 - **Mode:** Standalone
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.13.1
 - **NPM version:** 6.12.1
 - **Browser name and version:** chrome 80
 - **Platform name and version:** mac
 - **Additional wdio packages used (if applicable):** [@wdio/spec reporter, @wdio/selenium-standalone service, allure reporter]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
When running spec.ts file that its describe contains before each block
Every thing works fine accept for the allure report 

the report is broken -> the test method appear like before each hook 
![image](https://user-images.githubusercontent.com/53476275/77911129-f9d06100-7298-11ea-8536-8829865247b4.png)

**To Reproduce**
just clone this 
https://github.com/jpolley/WebdriverIO_v5_TypeScript
and add before each block

and use the report script inside the package.json

![image](https://user-images.githubusercontent.com/53476275/77911185-12407b80-7299-11ea-8e9e-502f8e61d369.png)

**Expected behavior**
report should be ok

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment] 2020-04-01 08:08
@kfirbhCS can you verify if this is also a problem in latest WebdriverIO?

**Comment by kfirbhCS** [comment] 2020-04-01 08:22
i will check and update thanks

**Comment by kfirbhCS** [comment] 2020-04-05 13:32
reproduced on 6.0.13

**Comment by christian-bromann** [comment] 2020-04-06 08:31
Duplicate of #5040

**Closed by christian-bromann** 2020-04-06 08:31 UTC
