### ISSUE TITLE
[💡 Feature]: Support mock command for browser-runner

### ISSUE THREAD

**Issue by kenchen-asurion** [webdriverio/webdriverio#12050] opened 2024-01-19 16:20 UTC
### Is your feature request related to a problem?

I am trying to set up WebDriverIO component tests for an existing react project and wanted to use the `browser.mock` function to mock the API requests like so

```
const apiPOSTMock = await browser.mock("**/api", {
  method: "post",
});
```

However, I've been getting this issue for every test that I called `browser.mock` in

```
TypeError: Cannot read properties of undefined (reading 'selenoid:options')
    at Browser.getPuppeteer (http://localhost:52696/node_modules/@wdio/browser-runner/node_modules/webdriverio/build/commands/browser/getPuppeteer.js?v=7bf5bdff:67:52)
    at Browser.wrapCommandFn (http://localhost:52696/node_modules/@wdio/utils/build/shim.js?v=7bf5bdff:88:38)
    at Browser.<anonymous> (http://localhost:52696/node_modules/@wdio/utils/build/shim.js?v=7bf5bdff:240:24)
    at Browser.mock (http://localhost:52696/node_modules/@wdio/browser-runner/node_modules/webdriverio/build/commands/browser/mock.js?v=7bf5bdff:115:20)
    at Browser.wrapCommandFn (http://localhost:52696/node_modules/@wdio/utils/build/shim.js?v=7bf5bdff:88:38)
    at Browser.mock (http://localhost:52696/node_modules/@wdio/utils/build/shim.js?v=7bf5bdff:240:24)
    at Context.<anonymous> (http://localhost:52696/Users/[redacted]:96:45)
```

I tried setting `selenoid:options` in the capabilities object in `wdio.conf.ts`, but it didn't fix the problem

```
capabilities: [
    {
      // capabilities for local browser web tests
      browserName: "chrome", // or "firefox", "microsoftedge", "safari"
      "selenoid:options": {
        enableVNC: true,
        enableVideo: true,
      },
      "moon:options":{}
    },
  ],
```

My package json and `wdio.conf.ts` are attached below for additional context
[configs.zip](https://github.com/webdriverio/webdriverio/files/13991570/configs.zip)

I had asked this question under this bug report and was directed to create an issue for it https://github.com/webdriverio/webdriverio/issues/7780

### Describe the solution you'd like.

I would like to be able to use the `browser.mock` function in both headful and headless tests. It would also be nice to have additional steps in the documentation (https://webdriver.io/docs/mocksandspies/) describing what additional capabilities and steps are needed to properly set up `browser.mock` so that others don't run into the same issue that I did.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment] 2024-01-20 17:41
I looked into this and unfortunately we can't support this just yet. The problem is that we can't run Puppeteer in the browser. The current Mock API implementation is currently based on Puppeteer. We have to wait until network interception is part of bidi and we have support for bidi based network mocking. I created a [branch](https://github.com/webdriverio/webdriverio/tree/cb/browser-runner-mock) with some tests that help continue working on this.

**Comment by kenchen-asurion** [comment] 2024-01-22 18:31
So what is the proper setup to use browser.mock? What extra packages do I need to run browser.mock() in both headless and in-browser modes?
It would be nice to see an example project with tests using browser.mock() in the documentation so that I can base my setup on that project.

**Comment by christian-bromann** [comment] 2024-01-25 02:34
> So what is the proper setup to use browser.mock?

It currently only works on Chrome when testing locally.

> What extra packages do I need to run browser.mock() in both headless and in-browser modes?

No extra packages.

> It would be nice to see an example project with tests using browser.mock() in the documentation so that I can base my setup on that project.

Contributions are welcome! I think the best place for such an example would be here: https://github.com/webdriverio/example-recipes

**Comment by KhrypunAlex** [comment] 2024-07-24 13:40
Hello, I have the same problem when `selenoid:options` are undefined. I use WebDriverIO to create integration tests for Lit Element components. Couple details: the runner is browser, capabilities are the same as above, I run tests locally and on pipeline. Everything work good if I don't use `browser.mock`. In case I use it, test fails and it doesn't matter what do I provide in `browser.mock`. Do you have some native workaround from WebDriverIO perspective to fix it while Puppeteer will provide updates? Just to clarify, is this is some edge case or common issue? Doesn't it mean that mocks are not working at all?

**Comment by christian-bromann** [comment] 2024-07-24 15:12
@KhrypunAlex we have implemented this feature now in the browser runner too as part of v9 which will be released in the upcoming weeks. You can either already switch to the dev version (`9.0.0-alpha.369`) or wait until it is released. I will go ahead and close this.

**Closed by christian-bromann** 2024-07-24 15:12 UTC
Labels: Enhancement, Blocked, Idea 💡

**Comment by KhrypunAlex** [comment] 2024-07-24 17:34
@christian-bromann sounds awesome! Thank you a lot!
