### ISSUE TITLE
beforeSession not changing the outputDir of the allure reporter?

### ISSUE THREAD

**Issue by olioli2345** [webdriverio/webdriverio#4771] opened 2019-11-12 12:00 UTC
- **WebdriverIO version:** [e.g. 4.13.2] - latest
 - **Mode:** [Standalone mode or WDIO Testrunner] - WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async] - sync
 - **Node.js version:** [e.g. 8.9.1] - latest
 - **NPM version:** [e.g. 5.8.0] - latest
 - **Browser name and version:** [e.g. Chrome 68] - chrome 77
 - **Platform name and version:** [e.g. Windows 10] - win10
 - **Additional wdio packages used (if applicable):**selenium-standalone, allure-reporter, it-each

I have 5 capabilities, each of which have a different baseURL to test different servers. I'm trying to generate a different report for each server, so I've tried to set the outputDir for each runner in the beforeSession hook:

config.reporters[1][1].outputDir = 'allure-results/' + capabilities["my:serverName"] + '/' + today + '/';

However, when I run this, the wdio.log, wdio.browser.log, wdio.server.log go into the correct folder, however the .xml files needed to generate the report just go into the default './allure-results'.

Is this possible? the beforeSession() hook says "It alloys you to manipulate configurations depending on the capability or spec", so I feel like this should work? Console logging the config in the afterSession() hook says that the outputDir is correct?

**Comment by mgrybyk** [comment] 2019-11-12 13:59
I think it's not possible right now because reporter is initialised before `beforeSession` hook is called. 

https://github.com/webdriverio/webdriverio/blob/a15f442c2481531317b91784a635088fcd9dd046/packages/wdio-runner/src/index.js#L92

I'm not sure if it's safe to move the line, it should be tested properly to avoid breaking changes and regressions.

**Comment by olioli2345** [comment] 2019-11-12 14:13
> I think it's not possible right now because reporter is initialised before `beforeSession` hook is called.
> 
> https://github.com/webdriverio/webdriverio/blob/a15f442c2481531317b91784a635088fcd9dd046/packages/wdio-runner/src/index.js#L92
> 
> I'm not sure if it's safe to move the line, it should be tested properly to avoid breaking changes and regressions.

Do you think there's any chance of beforeHooks being supported before reporter initialisations in the future?

**Comment by christian-bromann** [comment] 2019-11-12 15:18
I think it makes sense to move the hook call so you can change the `outputDir` dynamically. I agree with @mgrybyk though that I am not sure about the implications but I feel like `beforeSession` isn't used that much yet as it was recently added (in v5).

**Comment by olioli2345** [comment] 2019-11-12 15:19
> I think it makes sense to move the hook call so you can change the `outputDir` dynamically. I agree with @mgrybyk though that I am not sure about the implications but I feel like `beforeSession` isn't used that much yet as it was recently added (in v5).

I just did this and it seems to be working pretty well. I'll keep you updated if I encounter any errors.

**Comment by christian-bromann** [comment] 2019-11-27 08:39
> I just did this and it seems to be working pretty well.

Actually given the fact it works in `beforeSession` I think we can close this. Happy to reopen this.

**Closed by christian-bromann** 2019-11-27 08:39 UTC
Labels: Enhancement, help wanted
