### ISSUE TITLE
TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by lancedolan** [webdriverio/webdriverio#1883] opened 2017-02-17 19:30 UTC
## The problem

I am finding many selector queries that fail while testing in chrome that do not fail in phantomjs. In each of these cases, the cause is using the element() method, and often a solution is to use a different method.

For example:

`browser.element('.my-class input').setValue('NEW VALUE HERE');`

This will throw

```
TypeError: Cannot read property 'trim' of undefined
    at sanitizeErrorMessage (/Users/lancedolan/edlio/cms/node_modules/wdio-sync/build/index.js:190:34)
    at Object.setValue (/Users/lancedolan/edlio/cms/node_modules/wdio-sync/build/index.js:467:23)
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInThisContext (vm.js:26:33)
    at Object.exports.runInThisContext (vm.js:79:17)
    at /Users/lancedolan/edlio/cms/node_modules/webdriverio/build/lib/commands/debug.js:54:43
    at /Users/lancedolan/edlio/cms/node_modules/wdio-sync/build/index.js:321:29
```

However it will work if I refactor to

`browser.setValue( '.my-class input' , 'NEW VALUE HERE' );`

I have demonstrated this problem in dozens of test cases with dozens of selectors - the problem is not that my selector syntax is bad, and that's especially clear when the same selector succeeds in other functions like setValue( selector , value ) or click( selector ).

I'm using the latest version on selenium-standalone, which uses the 2.27 version of chrome driver for mac (I'm on mac sierra).

## Environment

* WebdriverIO version: latest, 4.6.2
* Node.js version: 7.4.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): BOTH, problems occurs in both
* if wdio testrunner, running synchronous or asynchronous tests: Honestly not sure how to determine this
* Additional wdio packages used (if applicable): wdio-mocha-framework@0.5.8

**Comment by christian-bromann** [comment] 2017-02-17 20:11
@lancedolan can you make a gist with an reproducible example please?

**Comment by kajmagnus** [comment] 2017-02-22 05:54
Could this possibly be related to https://github.com/webdriverio/webdriverio/issues/1885 `Unnecessary trim to browser.getValue()` ?

(Possibly related issue:  https://github.com/webdriverio/webdriverio/issues/1751 )

**Comment by christian-bromann** [comment] 2017-02-25 17:31
Closed #1885.

@kajmagnus as I said above: please provide reproducible examples, otherwise it is impossible for me to fix this issue

**Comment by derwok** [comment] 2017-02-28 21:33
We were biten by this topic, also! We use chimp (with webdriver.io). When running the tests headless everything is fine. Wenn running the tests whitch chrome driver, then non-existing selectors lead to a very confusing error message.  ;-( and debugging is very hard...

I created a minimal repo that shows the error:
https://github.com/derwok/chimptest
(The comprehensive README.md gives version numbers of all tools and steps to reproduce)

When running the tests with node 7.x and we hit this line:
`browser.click("#DOES_NOT_EXIST");` then the test runner crashes with:

```
     TypeError: Cannot read property 'trim' of undefined
      at sanitizeErrorMessage (/usr/local/lib/node_modules/chimp/node_modules/wdio-sync/build/index.js:190:34)
      at Object.<anonymous> (/usr/local/lib/node_modules/chimp/node_modules/wdio-sync/build/index.js:467:23)
      at Context.<anonymous> (tests/ChimpTest.js:13:17)
      at /usr/local/lib/node_modules/chimp/dist/lib/utils/fiberize.js:25:14
```
### FunFact: node version matters!
It seems, the problem is strongly related to the used node version. Because when we switch to node 4.x (latest) or node 6.x (latest) we get the expected error:
```
 Error: An element could not be located on the page using the given search parameters.
```

**Comment by christian-bromann** [comment] 2017-03-09 20:33
@derwok please raise an issue in the chimp project. When we push changes to `wdio-sync` we don't test it against chimp.

Closing as this issue is missing a reproducible example. We maintainer can't waste our time to reproduce certain issue since each WebdriverIO setup can be different. I hope you can understand this. I am happy to reopen if I someone can provide such an example.

**Closed by christian-bromann** 2017-03-09 20:33 UTC
