### ISSUE TITLE
💡 Feature: Move mochawesom reporter here

### ISSUE THREAD

**Issue by xwmyth8023** [webdriverio/webdriverio#10364] opened 2023-05-11 08:10 UTC
### Is your feature request related to a problem?

The [wdio-mochawesome-reporter](https://github.com/fijijavis/wdio-mochawesome-reporter) doesn't update any more and is not compatible with the latest wdio version

### Describe the solution you'd like.

Move the project here and make it compatible with the latest wdio version

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment] 2023-05-12 16:36
Duplicate of https://github.com/fijijavis/wdio-mochawesome-reporter/issues/68

**Closed by christian-bromann** 2023-05-12 16:36 UTC
Labels: Needs Triaging ⏳, Idea 💡
