### ISSUE TITLE
intermittent WDIO runtime issue - "Protocol error (Runtime.getProperties): Cannot find context with specified id" - workaround provided

### ISSUE THREAD

**Issue by DanielFreemanTester** [webdriverio/webdriverio#10557] opened 2023-06-12 16:51 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.3.3

### Node.js Version

18.16.0

### Mode

Standalone Mode

### What happened?

From 6th June 2023 when running WebdriverIO v8 tests with chromedriver: "^114.0.1" and the @wdio/cucumber-framework v8.3.0 I found that tests run against one of our MEAN-stack applications was intermittently (50% of runs) failing immediately with:

  "Protocol error (Runtime.getProperties): Cannot find context with specified id"

I searched on the web for a fix / workaround for this error but found very, very little information (5 results) but this page seems
to indicate that all that is needed is a delay somewhere in the test
https://bugs.chromium.org/p/chromedriver/issues/detail?id=2198

WORKAROUND
After some experimentation it seemed that the problem occurred somewhere between the browser being launched and the first use of the browser.url() command and so a workaround that is working for me (on 100% of 60+ test runs) is to insert a hard delay of 1 second before any call to browser.url(). I hope this helps others.

### What is your expected behavior?

The "Protocol error (Runtime.getProperties): Cannot find context with specified id" error should either not occur at all or should at least be handled with a meaningful error message. Please :)

### How to reproduce the bug.

See above.

### Relevant log output

```typescript
Protocol error (Runtime.getProperties): Cannot find context with specified id
ProtocolError: Protocol error (Runtime.getProperties): Cannot find context with specified id
  at new Callback (file:///C:/Git/project-name/node_modules/puppeteer-core/
  src/common/Connection.ts:65:12)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2023-06-12 17:02
@DanielFreemanTester can you provide a minimal reproducible example?

**Comment by DanielFreemanTester** [comment] 2023-06-12 17:22
Thanks for the quick response @christian-bromann. 

Unfortunately I'm not sure I can easily do this - it's only happening on 1 or our 2 UI TA frameworks using WDIO v8 and they share a lot of config and coding so I think this issue is due to some unusual interaction between WDIO v8, our environment and our main application under test. 

My main purpose in posting this Bug was to supply a workaround which might work save someone else who hits the same issue a few hours of the pain I had to go through :) ... which is not to say there is not a Bug to be fixed here ... but maybe it's not the highest priority Bug for WDIO v8 at the moment. I guess we'll see from any other responses which are posted here.

**Comment by christian-bromann** [comment] 2023-06-12 17:39
I am happy to keep this issue open for a bit but this seems not like a WebdriverIO issue because the error indicates a problem with Chrome DevTools.

**Comment by DanielFreemanTester** [comment] 2023-06-12 17:44
Thanks @christian-bromann, that seems perfectly reasonable to me. And, as I said, my main purpose was to record the workaround for other WebdriverIO v8 users in case it helps them.

**Comment by christian-bromann** [comment] 2023-06-23 20:47
Sounds good, closing then. Happy to re-open if there is anything concrete we can change in WebdriverIO to improve this.

**Closed by christian-bromann** 2023-06-23 20:47 UTC
Labels: Bug 🐛, Reproducible Example Missing
