### ISSUE TITLE
[🐛 Bug]: Element cannot access underlying HTML element

### ISSUE THREAD

**Issue by klondon-sc** [webdriverio/webdriverio#12387] opened 2024-02-29 22:36 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.32.3

### Node.js Version

v16

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
@wdio/types: 8.32.2
typescript: 4.9.5
```

### What happened?

I'm upgrading from wdio 5 to wdio 8 with Typescript and it looks like some behaviors have changed for Element-type objects. In particular, I'm looking to modify element styles and seeing this error:

```
MyObject.ts:214:49 - error TS2339: Property 'style' does not exist on type 'Element'.

214     await browser.execute((element) => (element.style.display = 'none'), root);
                                                    ~~~~~
```

Is there a way to cast or otherwise access the underlying HTML elements to modify their style? I reviewed the docs (https://webdriver.io/docs/api/element) and didn't see APIs which might expose the underlying objects. 

I opened a [discussion on Discord](https://discord.com/channels/1097401827202445382/1097674067601010709/threads/1212833050145071144) and discussed with @erwinheitzman. He recommended I open a bug on GH. 

### What is your expected behavior?

I expect that I would be able to access the underlying style element.

### How to reproduce the bug.

Here's a minimal reproduction example confirmed by Erwin:

```
await browser.execute((element: HTMLElement) => (element.style.outline = 'auto'), await $('test'))
```

### Relevant log output

```typescript
MyObject.ts:147:87 - error TS2345: Argument of type 'Element' is not assignable to parameter of type 'HTMLElement'.
  Type 'Element' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 280 more.

147     await browser.execute((element: HTMLElement) => (element.style.outline = 'auto'), await $('test'));
                                                                                          ~~~~~~~~~~~~~~~
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2024-02-29 22:45
@klondon-sc thanks for reporting. This is a duplicate of #6486. Any contribution would be much appreciated.

**Closed by christian-bromann** 2024-02-29 22:45 UTC
Labels: Bug 🐛, Needs Triaging ⏳
