### ISSUE TITLE
[🐛 Bug]: Regression: --spec arg ignores excludes

### ISSUE THREAD

**Issue by ayroblu** [webdriverio/webdriverio#8789] opened 2022-08-31 10:53 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.19.3

### Node.js Version

16

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
[
  {
    browserName: 'chrome',
    browserVersion: 'latest',
    platformName: 'Windows 10',
    exclude: [...globallyDisabledTests],
    sauce: {
      screenResolution: '1680x1050',
    },
  },
  {
    browserName: 'firefox',
    browserVersion: 'latest',
    platformName: 'Windows 10',
    exclude: [
      ...mediaUploadTests,
      ...globallyDisabledTests,
      ...allButLatestChrome,
    ],
    sauce: {
      screenResolution: '1920x1080',
    },
  },
  {
    platformName: 'iOS',
    browserName: 'Safari',
    appium: {
      deviceName: 'iPhone XS Simulator',
      platformVersion: '13.4',
      automationName: 'XCUITest',
    },
    sauce: {
      deviceOrientation: 'portrait',
    },
    exclude: [
      ...mediaUploadTests,
      ...globallyDisabledTests,
      ...mobileDisabledTests,
      ...allButLatestChrome,
    ],
  },
...
]
```

### What happened?

A feature introduced in #3995 was the ability to filter specs by the capabilities.
A regression was introduced in #8432 for #8376 that overrode this behaviour

### What is your expected behavior?

When --spec param is passed, the excludes should be respected. If we explicitly passed a config param where we want a config to be respected it doesn't make sense for a spec to suddenly override our config. 

### How to reproduce the bug.

```
wdio --coloredLogs --debug false --maxInstances 50 <config-path> --spec <spec-path>
```

### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2022-08-31 11:40
duplicate of #8730

**Closed by christian-bromann** 2022-08-31 11:40 UTC
Labels: Bug 🐛, Needs Triaging ⏳
