### ISSUE TITLE
ERROR @wdio/runner: TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by Amrkamel1** [webdriverio/webdriverio#6213] opened 2020-12-10 15:52 UTC
**Environment** :

```
` "keywords": [],
  "author": "aMr kaMel",
  "license": "ISC",
  "dependencies": {
    "@wdio/cli": "^6.4.7",
    "appium": "^1.18.3",
    "eslint": "^7.8.1",
    "frisby": "^2.1.3",
    "webdriverio": "^6.4.7"
  },
  "devDependencies": {
    "@wdio/selenium-standalone-service": "^6.4.7",
    "@wdio/appium-service": "^6.4.7",
    "wdio-chromedriver-service": "^6.0.4",
    "wdio-winappdriver-service": "^0.1.0",
    "@wdio/concise-reporter": "^6.4.7",
    "@wdio/dot-reporter": "^6.4.7",
    "@wdio/local-runner": "^6.4.7",
    "@wdio/mocha-framework": "^6.4.7",
    "@wdio/allure-reporter": "^6.4.7",
    "@wdio/spec-reporter": "^6.4.7",
    "@wdio/sync": "^6.4.7",
    "chai": "^4.2.0",
    "mocha": "^8.1.3"
  }`
```

**Config of WebdriverIO**

```
`exports.config = {

   specs: [
    'src/test/specs/03_WinApp_Suite.js'
  ],

  capabilities: caps.DesktopApp,

  services: [
    ['winappdriver', {
        args: ['localhost', '4729/wd/hub']
    }]
],

  sync: true,
  coloredLogs: true,
  maxInstances: 2,
  waitforTimeout: 13000,
  connectionRetryTimeout: 90000,
  framework: 'mocha',
  mochaOpts: {
    ui: 'bdd',
    timeout: 120000,
    retries: 0
  },

    afterTest: function(test, context, { error, result, duration, passed, retries }) {
        if (error !== undefined) {
            browser.takeScreenshot();
          }
    },

    reporters: ['dot','spec',['allure', {
        outputDir: 'allure-results',
        disableWebdriverStepsReporting: true,
        disableWebdriverScreenshotsReporting: false,
        disableMochaHooks: true
    }]],
}
`
```
**Describe the bug**
`ERROR @wdio/runner: TypeError: Cannot read property 'toLowerCase' of undefined` when the user is not specifying the port and path in his caps, also error logs is pointing to devtools however it's not associated with the test 

![image](https://user-images.githubusercontent.com/32042806/101795123-3df64f80-3b10-11eb-9e3a-76f16a4b8f0c.png)

**To Reproduce**

[Include code or an example repository that can easily be set up]

**Expected behavior**
A clear meaningful message pointing to the main reason for  failing e.g (missing port and path)

**Comment by christian-bromann** [comment] 2020-12-10 18:09
Duplicate of #6214

**Closed by christian-bromann** 2020-12-10 18:09 UTC
