### ISSUE TITLE
Sessions of retried spec files are not closed in Multiremote mode

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#3989] opened 2019-05-18 10:59 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.8.5
 - **Mode:** standalone
 - **If WDIO Testrunner, running sync/async:** sync

```
    capabilities: {
        mmy111: {
            capabilities: { browserName: 'chrome' }
        },
        mmy222: {
            capabilities: { browserName: 'chrome' }
        }
    },
    specFileRetries: 1,
```

- Multiremote mode
- specFileRetries: 1 or more

**Describe the bug**
Run some test that will fail with specFileRetries > 0 in Multiremote mode. Only last session is closed, others are opened.

**To Reproduce**
1. Use Multiremote mode
2. Set specFileRetries to be 1 or more
3. Run some test that will fail

Actual Result:
only last session is closed, others are opened

**Expected behavior**
should work same as in non multiremote mode, sessions have to be closed on retry.

**Comment by christian-bromann** [comment] 2020-09-02 09:25
I tried to reproduce this and it seems to be fixed with the latest version.

**Closed by christian-bromann** 2020-09-02 09:25 UTC
Labels: Bug🐛
