### ISSUE TITLE
[🐛 Bug]: @wdio/cli broken since 8.16.12

### ISSUE THREAD

**Issue by wvankuipers** [webdriverio/webdriverio#11261] opened 2023-09-28 11:18 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.16.12

### Node.js Version

20.7.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  runner: 'local',
  user: ConfigSettings.browserStackUser,
  key: ConfigSettings.browserStackKey,
  browserStackLocal: true,
}
```

### What happened?

Connecting to Browserstack works fine with `@wdio/cli` version `8.16.11` but starting from `8.16.12` we get the error als shown below.

We execute WDIO from inside an Alpine Docker image.

### What is your expected behavior?

With version `@wdio/cli@8.16.11` the connection with Browserstack still worked. We updated all other WDIO dependencies to `8.16.15` and that still worked.

### How to reproduce the bug.

There is no reproducable code. If needed I can try to create a small project that has this issue.

Dependencies:

```json
  "dependencies": {
    "@wdio/cli": "8.16.12",
    "@wdio/jasmine-framework": "8.16.15",
    "@wdio/junit-reporter": "8.16.12",
    "@wdio/local-runner": "8.16.15",
    "@wdio/spec-reporter": "8.16.12",
    "browserstack-local": "1.5.4",
    "ts-node": "10.9.1",
    "typescript": "5.2.2"
  }
  ```

### Relevant log output

```typescript
Error while trying to execute binary Error: Command failed: /root/.browserstack/BrowserStackLocal --daemon start --log-file /web-vr-lib/vr/local.log --source nodejs-1.5.4 --key <REDACTED> --local-identifier <REDACTED> --force --verbose 1
Pkg: FLAGS_MISMATCH

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:488:12)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 4,
  killed: false,
  signal: null,
  cmd: '/root/.browserstack/BrowserStackLocal --daemon start --log-file /web-vr-lib/vr/local.log --source nodejs-1.5.4 --key <REDACTED> --local-identifier <REDACTED> --force --verbose 1'
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2023-09-28 14:58
cc @sriteja777 @kamal-kaur04

**Comment by kamal-kaur04** [comment] 2023-09-29 11:22
Hi @wvankuipers, Thanks for reporting the issue. I have tried to reproduce it using this [sample branch](https://github.com/kamal-kaur04/webdriverio-browserstack/tree/repro-wdio-local) with node `v20.7.0`. 
Could you please point if we miss any options or configuration. Moreover, It would be helpful if you can provide a reproducible sample.

Thanks.

**Comment by christian-bromann** [comment] 2023-10-09 03:45
Closing due to inactivity. Happy to re-open if a reproducible example can be provided.

**Comment by wvankuipers** [comment] 2023-10-09 15:51
Sorry @christian-bromann and @kamal-kaur04 I didn't have enought time to look into this issue before today. When nuilding an reproducible sample and investigationg further I came to the conclusion this issue is within [browserstack-local-nodejs ](https://github.com/browserstack/browserstack-local-nodejs) itseld. I will create an issue there and investigate it further.

**Comment by christian-bromann** [comment] 2023-10-09 15:54
Thanks for confirming @wvankuipers

**Comment by wvankuipers** [comment] 2023-10-10 14:23
@kamal-kaur04 Please find a reproducable repo here: https://github.com/wvankuipers/wdio-bs-issue/tree/main

@christian-bromann could we re-open this issue please?

**Comment by erwinheitzman** [comment] 2023-10-13 13:22
I'll look into this 👍

**Comment by erwinheitzman** [comment] 2023-10-13 15:20
@wvankuipers I think you might be right about the NODE_OPTIONS though I do not see NODE_OPTIONS being set in the browserstack_local package.

Could you check your NODE_OPTIONS to see if it is accidentally set to anything just to be sure before I dive further into this?
```
printenv NODE_OPTIONS
```

**Comment by erwinheitzman** [comment] 2023-10-13 15:31
@wvankuipers I think I found the issue, you set the NODE_OPTIONS over here https://github.com/wvankuipers/wdio-bs-issue/blob/main/build.sh

Since they are conflicting with the options set by webdriverio I would extend them using javascript in this file https://github.com/wvankuipers/wdio-bs-issue/blob/main/browserstack.ts

Simply remove it from the build.sh and add this to the browserstack.ts:
```js
process.env.NODE_OPTIONS += " --experimental-modules"
```

**Comment by wvankuipers** [comment] 2023-10-13 15:34
Thank you @erwinheitzman Let me try this and come back to you with the result

**Comment by wvankuipers** [comment] 2023-10-13 15:45
Unfortunatly this:

```javascript
process.env.NODE_OPTIONS += " --experimental-modules"
```

Didn't resolve the issue. I still get the same error message as before.

The issue is somewhere in the part that is set by WDIO because this:

```javascript
process.env.NODE_OPTIONS = " --experimental-modules";
```

(notice the lkack of the `+`)

Does resolve the issue. The thing is that this is fine for my use-case now but it will most likely hunt other developers who need the same way of running the browserstack intergration.

**Comment by erwinheitzman** [comment] 2023-10-13 16:16
The problem is that users are allowed to add NODE_OPTIONS, what you do is set the options for a usecase of what I feel should be a separate process so it does not interfere. That said you can do the following:

```js
const originalNodeOptions = process.env.NODE_OPTIONS

process.env.NODE_OPTIONS = " --experimental-modules"

// do thing you need to do

process.env.NODE_OPTIONS = originalNodeOptions
```

**Comment by erwinheitzman** [comment] 2023-10-13 16:30
I'm glad that you have it working for your usecase but do you feel that the example above would be enough as we cannot unset the options?

**Comment by wvankuipers** [comment] 2023-10-13 17:11
Yes I would say that adding this to the documentation would be suficcient 👍🏼  Thanks for looking into this

**Comment by christian-bromann** [comment] 2023-11-06 02:50
It seems that this issue has been resolved. I will go ahead and close it. I am not sure what particularly should be added to the docs. Let me know what particular information should be added on what page and I am happy to push that change.

Thanks @erwinheitzman for helping resolving this 🙌

**Closed by christian-bromann** 2023-11-06 02:50 UTC
Labels: Bug 🐛, help wanted
