### ISSUE TITLE
multiremote is not working out of the box

### ISSUE THREAD

**Issue by Poldo8** [webdriverio/webdriverio#4411] opened 2019-08-27 16:02 UTC
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [5.12.4]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [10.15.2]
 - **NPM version:** [6.4.1]
 - **Browser name and version:** [Any]
 - **Platform name and version:** [Any]
 - **Additional wdio packages used (if applicable):** [
"@wdio/cli": "^5.12.5",
    "@wdio/cucumber-framework": "^5.12.3",
    "@wdio/dot-reporter": "^5.12.1",
    "@wdio/local-runner": "^5.12.5",
    "@wdio/sync": "^5.12.3",
    "@wdio/selenium-standalone-service": "^5.12.1",
]

**Config of WebdriverIO**
https://github.com/Poldo8/multiremote-js/blob/master/wdio.conf.js

**Describe the bug**
 Cannot find name 'myChromeBrowser'. using the wdio.config that is on the guide https://webdriver.io/docs/multiremote.html#using-wdio-testrunner

**To Reproduce**
repo https://github.com/Poldo8/multiremote-js
```

$  yarn test:cucumber
yarn run v1.13.0
$ yarn clean && yarn build && wdio wdio.conf.js
$ rimraf build
$ tsc -p tsconfig.json
features/step-definitions/login_step.ts:5:3 - error TS2304: Cannot find name 'myChromeBrowser'.

5   myChromeBrowser.url("https://www.google.com/")
    ~~~~~~~~~~~~~~~

features/step-definitions/login_step.ts:6:3 - error TS2304: Cannot find name 'myFirefoxBrowser'.

6   myFirefoxBrowser.url("https://www.google.de/")
    ~~~~~~~~~~~~~~~~


Found 2 errors.

```

**Expected behavior**
open Firefox to https://www.google.com
open Chrome to https://www.google.de

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment] 2019-08-27 16:05
Duplicate of #4404

**Closed by christian-bromann** 2019-08-27 16:05 UTC
