### ISSUE TITLE
@wdio/sauce-service TypeError: undefined property for version 6.10.4 (latest)

### ISSUE THREAD

**Issue by TheTechHuss** [webdriverio/webdriverio#6189] opened 2020-12-01 11:18 UTC
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** "@wdio/cli": "^6.8.1",
 - **Node.js version:** v14.13.0,
 - **NPM version:** v6.14.8,
 - **Browser name and version:**Chrome - Version 86.0.4240.198 (Official Build) (64-bit)
 - **Platform name and version:** Windows 10 Enterprise
 - **Additional wdio packages used (if applicable):** "@wdio/cli": "^6.8.1",
    "@wdio/local-runner": "^6.9.1",
    "@wdio/mocha-framework": "^6.8.0",
    "@wdio/sauce-service": "^6.8.0", (I had to downgrade the sauce-service version to this to get it to run)
    "@wdio/spec-reporter": "^6.8.1",
    "@wdio/sync": "^6.9.1",

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
My test still passes, however the capabilities and config throw an error when ran

[0-0] RUNNING in Android - <PATH-TO-PROJECT>\test\specs\android\login-page-test.js
[0-0] 2020-12-01T10:39:57.502Z ERROR @wdio/sync: TypeError: Cannot read property 'capabilities' of undefined
    at SauceService.before (<PATH-TO-PROJECT>\node_modules\@wdio\sauce-service\build\service.js:34:43)
    at execHook (<PATH-TO-PROJECT>\node_modules\@wdio\sync\build\executeHooksWithArgs.js:21:31)
[0-0] 2020-12-01T10:40:02.224Z ERROR @wdio/sync: TypeError: Cannot read property 'config' of undefined
    at SauceService.after (<PATH-TO-PROJECT>\node_modules\@wdio\sauce-service\build\service.js:95:26)

**To Reproduce**
Run an Android test against a sauceLabs device. We had this same issue with all sauceLabs tests across all devices.

[Include code or an example repository that can easily be set up]

**Expected behavior**
I expected my test not to throw and error

**Comment by christian-bromann** [comment] 2020-12-07 08:16
> Run an Android test against a sauceLabs device.

Are you talking about a real device test or an emulator test?

**Comment by christian-bromann** [comment] 2020-12-14 13:39
@TheTechHuss can you please provide more information? Otherwise we have to close the issue.

**Comment by blane1988** [comment] 2020-12-18 23:58
Hello. I am getting this as well against iOS/Android virtual and real devices. 

It is failing in /node_modules/@wdio/sauce-service/build/service.js line 34

![Uploading Screen Shot 2020-12-18 at 5.56.28 PM.png…]()

Here are the capabilities I am using:

```
platformName: 'Android',
        platformVersion: '8.0',
        deviceName: 'Android Emulator',
        deviceType: 'phone',
        appiumVersion: '1.18.1',
        // deviceType: 'tablet',
        browserName: '',
        udid: '',
        automationName: 'UiAutomator2',
        app: 'storage:<redact>',
        appPackage: '<redact>',
        appActivity: '<redact>',
        autoGrantPermissions: true,
        noReset: false,
        fastReset: true,
        newCommandTimeout: 240,
        appWaitDuration: 60000,
```

**Comment by blane1988** [comment] 2020-12-19 00:36
Okay, I see what is going on. In the working project, sauce-service before() hook in service.js, it looks like this:

```
before() {
        const capabilities = global.browser.capabilities || {};
        this.isUP = utils_1.isUnifiedPlatform(capabilities);
    }
```

In the newer project, that same hook looks like this:

```
before(caps, specs, browser) {
        this.browser = browser;
        const capabilities = this.browser.capabilities || {};
        this.isUP = utils_1.isUnifiedPlatform(capabilities);
    }
```

When I copy/paste the first code into the new project, it runs without any errors.

**Comment by shabfactor** [comment] 2020-12-24 04:39
i am having the same issue with version `6.10.14` do we have any fix available?

**Comment by christian-bromann** [comment] 2020-12-24 10:50
@shabfactor can you please provide more information, logs or a reproducible example?

**Comment by christian-bromann** [comment] 2021-05-31 09:18
It seems this is due to the usage of incompatible wdio and `@wdio/sauce-service` version. I recommend to update to the latest version to resolve the problem.

**Closed by christian-bromann** 2021-05-31 09:18 UTC
Labels: Bug🐛, good first pick, help wanted
