### ISSUE TITLE
[🐛 Bug]: <Set Cookie, Expiry not setting correct value>

### ISSUE THREAD

**Issue by wbigno** [webdriverio/webdriverio#8893] opened 2022-09-20 19:50 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v14

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
browserName: 'googlechrome',
      platformName: 'Windows 10',
      browserVersion: '103',
      'sauce:options': {
        ...defaultWindowsBrowserSauceOptions
      },
      ...chromeOptions
```

### What happened?

When setting a cookie, the expiry value is showing up in the browser as Session, and when I console log the set cookie I get a -1 value returned. I have set the expiry as a number, in seconds since epoch but it never sets the correct value.

### What is your expected behavior?

If I set an expiry value on a cookie, using epoch.. it should show up correctly in the browser, and be able to be retuned to be verified it was set using getCookie

### How to reproduce the bug.

it('should display the alert banner when cookie set is more than 7 days', async () => {
        await browser.setCookies({ name: 'alert_banner_copy_co-2209151748', value: 'Closed', expiry: 1663703043 });
        const cookies = await browser.getCookies();
        let expireDate = null;
        for (const cookie of cookies) {

            if (cookie.name.includes('alert_banner')) {
                console.log(cookie)
                expireDate = cookie.expiry;

            }
        }

### Relevant log output

```typescript
{
[0-0]   name: 'alert_banner_copy_co-2209151748',
[0-0]   value: 'Closed',
[0-0]   domain: 'intbeta.newyorklife.com',
[0-0]   path: '/',
[0-0]   expires: -1,
[0-0]   size: 37,
[0-0]   httpOnly: false,
[0-0]   secure: true,
[0-0]   session: true,
[0-0]   sameParty: false,
[0-0]   sourceScheme: 'Secure',
[0-0]   sourcePort: 443
[0-0] }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2022-09-24 21:44
Hey @wbigno , thanks for raising the issue.

I am unfortunately not sure if this can be fixed in WebdriverIO. The browser driver is in this case responsible for setting the cookie. Can you share a your WebdriverIO logs with us or a minimal reproducible example?

**Comment by christian-bromann** [comment] 2022-10-03 07:23
Closing due to inactivity.

**Closed by christian-bromann** 2022-10-03 07:23 UTC
Labels: Bug 🐛, Logs Missing

**Comment by rmjensen94** [comment] 2023-06-09 15:37
Hey! So I'm running into this same issue. Have tried setting the date in expiry on many cookies/configs and it always sets the expiry to -1. You're suspecting this is an issue w/ chrome?
