### ISSUE TITLE
[🐛 Bug]: waitForDisplayed driver's method stop working for Mobile Native app automation after upgrading to v8.23.2

### ISSUE THREAD

**Issue by AntRybalko** [webdriverio/webdriverio#11704] opened 2023-11-20 19:58 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
N/A
```

### What happened?

waitForDisplayed driver method stop working for Mobile Native app after updating to v8.23.2

### What is your expected behavior?

waitForDisplayed method should correctly wait with specified timeout for element by specified locator

### How to reproduce the bug.

Run any available Native Mobile App automation using Appium and try to execute waitForDisplayed() method for any element by specified locator
Check WDIO logs

### Relevant log output

```typescript
2023-11-20T19:42:26.835Z DEBUG webdriver: request failed due to response error: unknown method
2023-11-20T19:42:26.835Z WARN webdriver: Request failed with status 405 due to Method is not implemented
2023-11-20T19:42:26.835Z INFO webdriver: Retrying 1/1
2023-11-20T19:42:26.835Z INFO webdriver: [POST] http://0.0.0.0:4111/session/88b21497-e536-4201-87b0-75e093273aa6/execute/sync
2023-11-20T19:42:26.835Z INFO webdriver: DATA {
  script: 'isElementDisplayed(...) [8007 bytes]',
  args: [
    {
      'element-6066-11e4-a52e-4f735466cecf': '58000000-0000-0000-F206-000000000000',
      ELEMENT: '58000000-0000-0000-F206-000000000000'
    }
  ]
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by BorisOsipov** [comment] 2023-11-20 20:04
It seems to regress after https://github.com/webdriverio/webdriverio/pull/11681

**Comment by erwinheitzman** [comment] 2023-11-21 12:36
Thank you for picking this up @christian-bromann as I am still at the conference so I can't look into it (no laptop with me).

**Comment by lasert0uch** [comment] 2023-11-21 15:35
I am experiencing this issue on iOS devices run through GitHub actions (Ubuntu) to real devices on SauceLabs. 
- wdio 8.19.0, Started sometime yesterday, halts at a waitForDisplayed(), No code changes, worked the day before in GH Actions to SL Real Devices - SauceLabs support pointed me to this issue.
- When same test is run from my local (Mac) to SauceLabs, everything works fine.
`[0-0] Error in "Carbon_iOS_App_e2e_iPhone_15_Pro_Max_iOS_17_real.Download-App-First-Time-and-See-Login-Screen"
Error: waitUntil condition failed with the following reason: Method is not implemented
    at Login.pageCheck (/home/runner/work/main-site-automation/main-site-automation/test/appium/carbon/pages/login.page.js:21:5)
    at Context.<anonymous> (/home/runner/work/main-site-automation/main-site-automation/test/specs/ios/carbon/carbon-e2e-flow.spec.js:20:5)`
    
![image](https://github.com/webdriverio/webdriverio/assets/50838262/231fddcd-9ba9-42cd-a473-68ee96b41489)

**Comment by christian-bromann** [comment] 2023-11-21 16:30
I have raised a PR with a fix which will be released in a minute. Sorry for the regression. I made sure to document the current state well enough so we keep the behavior as is moving forward.

**Closed** 2023-11-21 16:29 UTC
Labels: Bug 🐛, help wanted

**Comment by HannaTarasevich** [comment] 2023-11-21 17:10
Hi,
Looks like I have encountered into the same issue with web application (chrome). We have some elements that are displayed right after click on other element. Appeared pop-up contains target element (I can find it in the DOM and it always displays on the screenshots), but WDIO fails with error message that element is not clickable/interactable/displayed. It has started since yesterday. There were no any code changes from our side. We always use the latest WDIO on the pipeline. So, I have to downgrade the versions to 8.22.0 (webdriver, local-runner, cli) and now it works again.

**Comment by christian-bromann** [comment] 2023-11-21 17:52
Hey @HannaTarasevich , thanks for reaching out! Can you provide some WebdriverIO logs of your failing tests running in `8.22.0` and `latest`? For browser tests nothing should have changed so I am curious how the execution changed.

**Comment by lasert0uch** [comment] 2023-11-21 18:12
@christian-bromann - Upgrade to version 8.23.4 appears to have resolved the issue for me - Thank you!

**Comment by AntRybalko** [comment] 2023-11-21 19:34
@christian-bromann Issue has been fixed on our side as well. Thanks for a quick fix

**Comment by HannaTarasevich** [comment] 2023-11-21 20:55
Hi @christian-bromann,
There are logs from the runs of the same test:

v23
2023-11-21T19:25:26.822Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
2023-11-21T19:25:26.822Z INFO webdriver: [POST] http://0.0.0.0:49987/session/da5aa12ceff5f44bb622b633a7234d81/execute
2023-11-21T19:25:26.822Z INFO webdriver: DATA {
  script: 'isElementDisplayed(...) [8033 bytes]',
  args: [
    {
      'element-6066-11e4-a52e-4f735466cecf': '4684D05EC26DCDFA1BD83A49BDF17511_element_164',
      ELEMENT: '4684D05EC26DCDFA1BD83A49BDF17511_element_164'
    }
  ]
}
2023-11-21T19:25:26.833Z INFO webdriver: RESULT false
..
**_FAILURE_**


v22
2023-11-21T19:37:07.821Z INFO webdriver: COMMAND findElement("css selector", "div .k-multiselect")
2023-11-21T19:37:07.821Z INFO webdriver: [POST] http://0.0.0.0:51224/session/f7df37e8192d4936bfef514ad3a8390f/element
2023-11-21T19:37:07.821Z INFO webdriver: DATA { using: 'css selector', value: 'div .k-multiselect' }
2023-11-21T19:37:07.838Z INFO webdriver: RESULT { ELEMENT: '957A04CFD450AEA222A434341E72792B_element_162' }
2023-11-21T19:37:07.841Z INFO webdriver: COMMAND isElementDisplayed("957A04CFD450AEA222A434341E72792B_element_162")
2023-11-21T19:37:07.841Z INFO webdriver: [GET] http://0.0.0.0:51224/session/f7df37e8192d4936bfef514ad3a8390f/element/957A04CFD450AEA222A434341E72792B_element_162/displayed
2023-11-21T19:37:07.852Z INFO webdriver: RESULT true
..
**_PASSED_**

I found out that using previous approach with await this.isElementDisplayed(this.elementId) (that was working for Chrome before https://github.com/webdriverio/webdriverio/pull/11681) fixes the issue.

I guess that previous approach included repeating in getting the element by id (and looks like page reinitialization each time), that current approach does not do so. Therefore, even if the element has appeared on the page in my app, it does not see it.

**Comment by BorisOsipov** [comment] 2023-11-21 21:14
@HannaTarasevich, your issue seems different than the original one. Please don't mix different issues and file a new bug referring to the regression appearing in a particular version.

**Comment by christian-bromann** [comment] 2023-11-21 22:18
@HannaTarasevich interesting, it seems like the script we use to determine displayedness is giving a different result now. Is there any chance you can raise a new issue with something that we can reproduce on our end?

**Comment by HannaTarasevich** [comment] 2023-11-22 15:10
@christian-bromann Thanks, created new issue https://github.com/webdriverio/webdriverio/issues/11710.
