### ISSUE TITLE
Test runner crashes when deleting localStorage before loading a page 

### ISSUE THREAD

**Issue by tkalfigo** [webdriverio/webdriverio#2499] opened 2017-12-04 16:01 UTC
## The problem

Doing `browser.localStorage('DELETE')` before loading a page, crashes the test runner.

## Environment

* WebdriverIO version: 4.9.10
* Node.js version: 8.7.0
* wdio testrunner mode
* sync mode
* Additional wdio related packages: 
   * "wdio-allure-reporter": "~0.1.2"   
    * "wdio-dot-reporter": "0.0.9"
    * "wdio-mocha-framework": "~0.5.11"
    * "wdio-selenium-standalone-service": "0.0.9"
    * "selenium-standalone": "~6.11.0"
* Chrome 61.0.3163.79 (Official Build) (64-bit) on Linux

## Details

If the deletion of local storage (entirely or of specific key) is requested before a `browser.url()` call, the whole suite fails with error:
```
/home/foo/Projects/project-name/node_modules/webdriverio/build/lib/utils/ReporterStats.js:381
            if (!suiteStats.tests[uid]) throw Error(`Unrecognised test [${runner.title}] for suite [${runner.parent}]`);
                                        ^

Error: Unrecognised test ["before each" hook for "should contain iframe with correct "src""] for suite [Page with library with syncing]
    at ReporterStats.getTestStats (/home/foo/Projects/project-name/node_modules/webdriverio/build/lib/utils/ReporterStats.js:381:47)
    at ReporterStats.testFail (/home/foo/Projects/project-name/node_modules/webdriverio/build/lib/utils/ReporterStats.js:450:30)
    at BaseReporter.<anonymous> (/home/foo/Projects/project-name/node_modules/webdriverio/build/lib/utils/BaseReporter.js:159:25)
    at emitOne (events.js:115:13)
    at BaseReporter.emit (events.js:210:7)
    at BaseReporter.handleEvent (/home/foo/Projects/project-name/node_modules/webdriverio/build/lib/utils/BaseReporter.js:300:27)
    at Launcher.messageHandler (/home/foo/Projects/project-name/node_modules/webdriverio/build/lib/launcher.js:646:28)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at emit (internal/child_process.js:774:12)
```

I can understand that actions on the localstorage make little sense when no page is loaded, but don't think it's justified to bring down the entire test run. 

The equivalent of deleting a cookie for example with `browser.deleteCookie('cookieName')`, has no effect if done before page is loaded with `browser.url()`.

## Code To Reproduce Issue

```
beforeEach(() => {
     browser.localStorage('DELETE');
     browser.url(indexUrl);
});
```

**Comment by adamweeks** [comment] 2017-12-05 20:23
We are seeing the same failure, but not 100% of the time. Code is slightly different, but dealing with clearing localstorage:

```js
browser
  .url(`/myPage.html`)
  .execute(() => {
    localStorage.clear();
  });
```

**Comment by tkalfigo** [comment] 2017-12-06 14:59
I guess our bigger problem is that the error thrown is uninformative. And we get this a lot i.e. whenever the problem is outside an `it` clause, we get these stack traces. 

Is there a way to improve error stacktraces for these cases? @adamweeks Are you having a similar problem?

Side question: declaring in `wdio.conf.js` the flag `sync: true` means all callbacks need to return promises?

**Comment by christian-bromann** [comment] 2017-12-06 15:38
Actually duplicate of #2494

**Closed by christian-bromann** 2017-12-06 15:38 UTC
Labels: Bug
