### ISSUE TITLE
Sometimes only half of all key strokes are set

### ISSUE THREAD

**Issue by binarykitchen** [webdriverio/webdriverio#465] opened 2015-03-17 04:59 UTC
This bug seems to happen by random.

Whenever I do a `.setValue('input[name=password]', 'password')` in my tests, I can see on Chrome that sometimes only half of it are set. The password field has only `passw` and `ord` are missing, not entered. And then my tests do fail, sometimes. Weird.

Either it goes too fast or the input has lost focus. No idea. But IMO it should be stable and ensure the input has focus all the time until the last key stroke.

Anyone?

**Comment by christian-bromann** [comment] 2015-03-17 05:38
Hi @binarykitchen 

I've experienced the same (mostly on linux/chrome). It's because the Chromedriver acts to fast. This is actually a problem on Selenium site but since this seems to be getting more and more problematic it might be worth to think about a workaround.

**Comment by binarykitchen** [comment] 2015-03-17 20:21
Ouch, this worries me. We just wrote lots of tests based on this driver in conjunction with webdriverio. And now this :(

**Comment by binarykitchen** [comment] 2015-03-17 20:22
How about adding `pause(50)` between each command?

**Comment by christian-bromann** [comment] 2015-03-17 20:25
@binarykitchen I am going to implement that (check out #390). However sending a row of key strokes to the server is one single command. So this won't work unless you do this thing:

```js
client
     .addValue('#input', 'H')
     .addValue('#input', 'e')
     .addValue('#input', 'l')
     .addValue('#input', 'l')
     .addValue('#input', 'o')
```

**Comment by binarykitchen** [comment] 2015-03-17 20:27
Good. For the keystrokes, do you think you could add a convenient function pausing between each one and have this wrapped in `setValue()`?

**Comment by christian-bromann** [comment] 2015-03-17 20:29
btw: this is not a WebdriverIO related issue. Though I would love to fix that issue on user level. How about a flag for [set|add]Value (like `deferred`) that if set you `true` sends the keystrokes on after each other with a specific delay.

**Comment by binarykitchen** [comment] 2015-03-17 20:38
yes, sounds good, whatever works for you best. haven't seen the source code yet. thanks

**Comment by binarykitchen** [comment] 2015-03-19 02:06
i found out that when i click on the input before setting the value worked. no idea why. using this helper command for now:

```coffee
  clickAndSet = (selector, value, cb) ->
    client
      .click(selector)
      .setValue(selector, value, cb)
```

like that it's 100% sure the input gains focus before value is set.

**Comment by christian-bromann** [comment] 2015-03-19 02:22
awesome .. thanks for figuring that out @binarykitchen. I guess there is no problem to click on the input element before sending keys. Will add that.

**Comment by binarykitchen** [comment] 2015-03-19 22:01
Hmmm, somehow it still doesn't work properly. Weird. Digging deeper now ...

**Comment by binarykitchen** [comment] 2015-03-19 22:13
By the way, it's a password input. Maybe you should add this in your tests to be sure?

**Comment by christian-bromann** [comment] 2015-03-19 22:20
@binarykitchen good idea

**Comment by christian-bromann** [comment] 2015-05-26 23:37
@binarykitchen I just circled back to this issue. According to #390 you can pause between commands using:

```js
client.on('command', function(e) {
    client.pause(1000);
});
```

and then setting the input like this:

```js
client
     .addValue('#input', 'H')
     .addValue('#input', 'e')
     .addValue('#input', 'l')
     .addValue('#input', 'l')
     .addValue('#input', 'o')
```

I don't think it is a good idea to introduce an option to pause between commands. It leads to bad patterns and is probably just a temporary Selenium bug. Therefor I gonna close this issue. Please let me know if the example above doesn't work out for you.

**Closed by christian-bromann** 2015-05-26 23:37 UTC
Labels: Enhancement, Project Related, v3

**Comment by binarykitchen** [comment] 2015-05-26 23:45
Thanks but I don't like the idea of pausing commands. Not reliable and not async-oriented. Can lead to more trouble.

Better report this to Selenium. Wouldn't you mind to report the bug?

**Comment by christian-bromann** [comment] 2015-05-26 23:47
I bet there is already an issue raised. I will check and report if not.

**Comment by conradkleinespel** [comment] 2017-04-14 14:40
@christian-bromann Hello Christian ! Thanks for your comments. I'm having the same issue. Would you have any news about this bug by any chance ? Seems like it's still active for me using `selenium-server-standalone-3.3.1` and `ChromeDriver 2.29.461571` (the latest stable versions at this time).

**Comment by nossbigg** [comment] 2017-11-09 08:57
+1 was also facing the same issue with `setValue()`, but was resolved when I upgraded ChromeDriver version to 2.33 (was on 2.31).

**Comment by filenko45** [comment] 2023-01-18 10:05
Hi. Is there any update on this bug? I encountered it when using the regular input (not password). It looks like the driver doesn't wait for the field to be filled in and leaves the input field only with part of the data entered. Reproduces not every time, but sometimes.
