### ISSUE TITLE
[🐛 Bug]: @wdio/allure-reporter cucumber step reporter adds blank steps before and after each scenario 

### ISSUE THREAD

**Issue by JordiSAGE** [webdriverio/webdriverio#10358] opened 2023-05-09 15:17 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v18.16.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
package.json:

  "dependencies": {
    "@cucumber/cucumber": "^9.1.0",
    "@types/chai": "4.3.4",
    "@types/cucumber": "^7.0.0",
    "@types/node": "^18.16.0",
    "@types/source-map-support": "^0.5.6",
    "@wdio/allure-reporter": "^8.10.1",
    "@wdio/cli": "^8.10.1",
    "@wdio/config": "^8.10.1",
    "@wdio/cucumber-framework": "^8.10.1",
    "@wdio/devtools-service": "^8.10.1",
    "@wdio/dot-reporter": "^8.10.1",
    "@wdio/local-runner": "^8.10.1",
    "@wdio/shared-store-service": "^8.10.1",
    "@wdio/spec-reporter": "^8.10.1",
    "@wdio/types": "^8.10.1",
    "allure-commandline": "2.21.0",
    "bytenode": "1.4.0",
    "chai": "~4.3.7",
    "cucumber-tag-expressions": "2.0.3",
    "devtools": "8.8.4",
    "dotenv": "^16.0.3",
    "fs-copy-file-sync": "1.1.1",
    "image-size": "^1.0.2",
    "npm": "^9.6.4",
    "npm-check-updates": "^16.10.8",
    "pdfkit": "^0.13.0",
    "puppeteer": "^19.9.1",
    "rimraf": "5.0.0",
    "source-map-support": "0.5.21",
    "wdio-cucumber-reporter": "^0.0.2",
    "wdio-typescript-service": "0.0.3",
    "wdio-wait-for": "^3.0.3",
    "webdriverio": "^8.10.1"
  }

Allure report config:

    reporters: [
        'dot',
        'spec',
        [
            'allure',
            {
                outputDir: path.resolve(cfgReportDir + '/allure-results'),
                disableWebdriverStepsReporting: true,
                disableWebdriverScreenshotsReporting: false,
                useCucumberStepReporter: true,
                disableMochaHooks: true,
            },
        ],
    ],
```

### What happened?

It seems that, since upgrading all the packages related to webdriverio to version 8 (checked with v8.10.1), new blank steps are appearing at the beginning and the end of each scenario execution in Allure report, using the Cucumber step reporter option, those seem to correspond to the Before and After events, which in turn, aren't adding any kind of info to the allure report and were not visible using the previous wdio version 7.
Additionally, we recently added the parameter disableMochaHooks trying to disable them, but they're still there.

![AllureWdio8_IssueScreenshot](https://github.com/webdriverio/webdriverio/assets/33693547/68423334-f224-4eb7-adac-687fd846d10e)

Thank you in advance.

### What is your expected behavior?

The report using the useCucumberStepReporter shouldn't show the blanck steps before and after each scenario execution.

### How to reproduce the bug.

To reproduce a similar behaviour, you can use a default webdriverio project, add allure as reporter, and the configuration mentioned above.

![image](https://github.com/webdriverio/webdriverio/assets/33693547/91d6d6c1-4622-40ea-825e-fecaae26570e)

### Relevant log output

```typescript
None
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2023-05-09 18:45
Thanks for reporting!



Any contributions that resolves the bug are highly appreciated. Don't expect this to be picked up by active contributors as they have their own priorities. If you depend on this bug to be fixed, your contribution is required. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) or join our [Discord](http://discord.webdriver.io/) development server and let us know if you have any questions. Cheers!

**Comment by JordiSAGE** [comment] 2023-05-29 09:57
It seems that the error is produced when executing the following line:

https://github.com/webdriverio/webdriverio/blob/5666889c6a4899522738e5e9603ce6eec7cb0968/packages/wdio-allure-reporter/src/reporter.ts#L544

This method is triggered when executing both the config and cucumber hooks, which produced the blank passed steps at the beginning and the end of each scenario, as well as when the report is configured to "useCucumberStepReporter" and independently of "disableMochaHooks" is set to true or false.

I hope this info could help to solve the problem, I can by-pass it by adding a (!disableMockaHooks && hook.title) condition, but I don't know if it will produce other tests execution side defects or why these events are executed even when the config and cucumber hooks aren't specifically adding them.

Any help will be appreciated.
Thank you in advance!

**Comment by christian-bromann** [comment] 2023-05-30 04:00
I am unfortunately not too familiar with the reporter so I can't make any advice. In general though if any changes keep the test green that would be a good sign for me that we can apply it without expecting any regression.

**Comment by epszaw** [comment] 2023-08-25 09:45
The problem can still be reproduced:

<img width="1333" alt="image" src="https://github.com/webdriverio/webdriverio/assets/13414205/f6c03b3d-e33c-4f02-a8fd-2b99adc7bc3f">

Trying to figure out, what's going wrong and how it can be fixed.

**Comment by BorisOsipov** [comment] 2023-08-25 10:00
@epszaw Please don't waste your time. It was fixed in https://github.com/webdriverio/webdriverio/pull/10475

You see an "empty" case because there are some steps inside.

**Closed by BorisOsipov** 2023-08-25 10:00 UTC
Labels: Bug 🐛, help wanted, good first pick, wdio-allure-reporter
