### ISSUE TITLE
Allure report. Failed BeforeHooks  are not  overwritten after retry 

### ISSUE THREAD

**Issue by skovalenkoLohika** [webdriverio/webdriverio#7143] opened 2021-07-15 13:30 UTC
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:**  6.7.4
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** 12.19.0
 - **NPM version:** 6.14.8
 - **Browser name and version:** Chrome 90
 - **Platform name and version:** MacOs/Linux
 - **Additional wdio packages used (if applicable):** @wdio/allure-reporter": "7.7.3", "@wdio/mocha-framework": "6.7.3","@wdio/sync": "6.7.3",  "typescript": "4.0.5", "@types/mocha": "8.0.4",

**Config of WebdriverIO**
const wdioConfig = {
  runner: "local",
  maxInstances: 1,
  capabilities: [],
  framework: "mocha",
  specFileRetries: 1,
  specFileRetriesDelay: 0,
  specFileRetriesDeferred: true,
  reporters: [
    [
      video,
      {
        saveAllVideos: true, 
        videoSlowdownMultiplier: 10, 
      },
    ],
    [
      "allure",
      {
        outputDir: "allure-results",
        disableWebdriverStepsReporting: true,
        disableWebdriverScreenshotsReporting: true,
        disableMochaHooks: true,
      },
    ]
  ],
  mochaOpts: {
    require: ["ts-node/register"],
    ui: "bdd",
    timeout: process.env.DEBUG === "true" ? 999999 : 80000,
    retries: 1,
  },

**Describe the bug**
Allure report display failed BeforeHooks step from first run even if retry - all  passed.  In this case Allure display all tests are passed and failed beforeHook . (see please screenshot ) Flag  *disableMochaHooks: true* doesn't hide this rows.  Webdriver IO  v7  has same behaviour. 
![Screenshot 2021-07-15 at 15 18 17](https://user-images.githubusercontent.com/38782937/125798175-d34dfb3d-2489-4686-91b8-b7dc85630bf5.jpg)

**To Reproduce**
1. first run  - before hook has to be  failed
2.  retry test - before hook -  pass 
3.  allure report any way display failed before hook from first run 

[Include code or an example repository that can easily be set up]

**Expected behavior**
Failed beforeHooks are overwritten if retry was successful . Allure report doesn't display beforeHooks if set flag  *disableMochaHooks: true*.

**Log**
There is a logs  https://gist.github.com/skovalenkoLohika/eaee2374c35510e9caaa99aefd7d7f37

**Additional context**

> Please use the correct markdown

**Comment by skovalenkoLohika** [comment] 2021-07-15 13:34
![Uploading Screenshot 2021-07-15 at 15.18.17.png…]()

**Comment by christian-bromann** [comment] 2021-07-15 14:40
Thanks for reporting. This seems like a bug indeed. Contributions with fixes are appreciated, thanks!

**Comment by BorisOsipov** [comment] 2021-07-15 18:07
@skovalenkoLohika would be nice to have repo with reproduceable example. 
As I see from your config you mix mocha and wdio retries and it is not clear when the issue appears

**Comment by skovalenkoLohika** [comment] 2021-07-16 16:47
Hi Boris, thank you for your response. 
I tried to run only with wdio retry.  And have same behaviour. So i think the root of issue is wdio retry.
Cannot provide repo with example. It is not easy to simulate :  1 run  failed  BeforeHook and 2 run  passed  BeforeHook

**Comment by christian-bromann** [comment] 2021-07-16 16:57
> Cannot provide repo with example. It is not easy to simulate

How so?

**Comment by BorisOsipov** [comment] 2021-07-16 17:29
Issue appears because we don't report passed `beforeAll` hooks at all.
We do it because we want to avoid differences in total test cases count in spec and allure reporter and etc.
When `beforeAll` hook fails we have to report it as test - because user wants to know about all failed specs. So that's why hook appears in report and not overwritten by retry.

There is nothing to do. It is weird to have such retry garbage in report for retry feature users, but 
it's better than have 100 test cases in real life but allure says its count 130 (because of redundant hooks) for all who uses allure.

I would suggest to mark it as known issue and close in a couple of months if no one will offer fix.

**Comment by christian-bromann** [comment] 2021-07-16 18:48
> offer fix.

@BorisOsipov thanks for your input, what kind of fix would you think makes sense here?

**Comment by BorisOsipov** [comment] 2021-07-16 19:13
@christian-bromann From my point of view it is not possible to fix. Only way it is report all hook always, but I think it is awful and not acceptable.

**Comment by christian-bromann** [comment] 2021-07-16 19:32
Gotcha, agree. Closing.

**Closed by christian-bromann** 2021-07-16 19:32 UTC
Labels: Bug🐛, good first pick, help wanted, wdio-allure-reporter
