### ISSUE TITLE
Possibility to configure test spec process spawning?

### ISSUE THREAD

**Issue by timbru31** [webdriverio/webdriverio#1247] opened 2016-04-14 09:21 UTC
## The problem

According to https://github.com/webdriverio/webdriverio/issues/1106#issuecomment-184728530 `each test spec gets executed in a single child process`.
We have currently 101 individual `.feature files` (we are using Cucumber) and cannot put them into one big file.
When we launch our test script, my Selenium Server is trying to spawn 101 process, this results in a very heavy lag and I need to kill the processes.

Is there a way to configure this behaviour? Do we need to adjust our wdio.conf?
## Environment

**updated on 07/05/16**
- WebdriverIO version: 4.1.1
- Node.js version: 4.4.6
- Selenium Server 2.53.0
- using wdio testrunner
- running synchronous or asnychronous tests: does not matter
- Additional wdio packages used (if applicable):
  wdio-cucumber-framework: 0.2.0
## Details

Even with the cucumber option tags like `-cucumberOpts.tags=@foo`, it will spawn 101 processes, even though only 1 feature was tagged with `@foo`
(Note: The setup is working fine with wdio 3.4.0)

**Comment by AndrewKeig** [comment] 2016-04-14 15:44
I have the same issue, 👍

**Comment by christian-bromann** [comment] 2016-04-14 15:50
@timbru31 @AndrewKeig please checkout the `maxInstance` property. You can apply them globally for all capabilities or a specific one per capability:

https://github.com/webdriverio/webdriverio/blob/master/examples/wdio.conf.js#L52-L60
https://github.com/webdriverio/webdriverio/blob/master/examples/wdio.conf.js#L69-L72

**Comment by AndrewKeig** [comment] 2016-04-14 16:17
hi @christian-bromann, we have this set to `maxInstance:1`, but regardless of tags set, it will still spawn a process, and open a blank browser window, for each feature file, run 0 tests and close it.  It does run the tests tagged once it reaches the feature file tagged.  

Even if a feature file is empty it opens an empty browser window and does nothing, then closes it, so it appears that it opens a new browser window regardless of the tests enabled in a feature file.

Hope this makes sense..

**Comment by christian-bromann** [comment] 2016-04-14 16:21
@AndrewKeig sounds like we can improve the cucumber integration here. Can you file an issue in the wdio-cucumber-project with a detailed description so I can reproduce and understand it? Thanks!

**Comment by timbru31** [comment] 2016-04-14 16:33
@AndrewKeig experiencing the same issue. Can you tag me if you create an issue?

**Comment by attila** [comment] 2016-05-11 17:15
@christian-bromann I just tested this with mocha and I am getting the same bug. I used `fgrep` in `mochaOpts` to run only specific tests and found that a new session is initialised in selenium regardless there are tests to run or not.

After all, it does not seem a test framework specific issue. Is it possible in the framework adapter API to assemble/compile test files files before a selenium session is initiated, based on framework specific criteria in the adapter, e.g cucumber feature tags or mocha grep/fgrep configuration values?

I think this issue could be reopened here too to elaborate on this further?

**Comment by christian-bromann** [comment] 2016-05-11 18:46
> I think this issue could be reopened here too to elaborate on this further?

Agree, I think this can't be solved on the framework level because the Selenium session already started if the framework adapter starts working.

**Comment by attila** [comment] 2016-05-12 08:57
I think it would be worth thinking about adding another step to the framework adapter api in which adapters should parse and return the required feature/spec files using their own framework-specific logic. Based on that (and `maxInstances`, etc) webdriverio could determine how many processes it needs to spawn?

When a framework adapter does not implement this method then it could fall back to the default (current) behaviour.

**Comment by christian-bromann** [comment] 2016-05-12 16:55
@attila good idea, hopefully the methods that determine which files to run are somehow publicly available.

**Comment by monolithed** [comment] 2016-07-03 13:54
I've the same issue and I know how to solve it.

My workaround

```
npm test --suite="login" --grep="oauth"
```

1. Parse command line arguments (--grep value)
2. Get all files in your suite
3. Parse your test cases like `new RegExp(`describe\s*\(\s*${name}\s*\)`)`;
4. Pass all filtered specs to the Launcher

```
new WebDriverIO.Launcher('conf.js', {
    spec: [FILTERED_FILES] 
});
```

@christian-bromann, could we pass our specs to the Launcher?

**Comment by timbru31** [comment] 2016-07-05 20:38
@christian-bromann I've found the culprit.
It's in the https://github.com/webdriverio/webdriverio/blob/master/lib/launcher.js#L194 while loop. Since the spec is a big glob it's looped and each time (with the first spec popped off) called again to execute.

Instead it should be called once with all specs, since cucumber handles execution itself with tags and not tags (~@foo tags), shouldn't it?

Any idea how to fix/change this code?

(3.4.0 was https://github.com/webdriverio/webdriverio/blob/1109adab9a5dbd1449fd035b20693d3c68d1d557/lib/launcher.js#L34)

**Comment by monolithed** [comment] 2016-07-06 22:22
If someone wants to know how implements a custom `--grep` option:


#### helpers.js

```js
let path = require('path'),
	fs = require('fs');

let merge = require('deepmerge'),
	glob = require('glob');

module.exports = {
	/**
	 * @returns {string|undefined}
	 */
	options () {
		for (let option of process.argv) {	
			let [key, value] = option.split('=');

			if (key === name) {
				return value;
			}
		}
	},

	/**
	 * { <suite>: [ <files> ] }
	 *
	 * @param {string} directory
	 * @param {string} additional
	 * @returns {Object}
	 */
	suites (directory, additional = {}) {
		let files = fs.readdirSync(directory),
			cases = {};

		let grep = this.options('--grep');

		files.forEach(suite => {
			let files = path.join(directory, suite, '**/*.js'),
				debug = false;

			if (process.env.NODE_DEBUG) {
				debug = true;
			}

			files = glob.sync(files, {
				cache: true,
				debug
			});

			cases[suite] = files.filter(file => {
				if (grep) {
					let match = new RegExp(grep);

					if (grep && match.test(file)) {
						return file;
					}
				} else {
					return file;
				}
			});
		});

		return this.extend(cases, additional);
	}

	/**
	 * @param {Object} x
	 * @param {Object} y
	 * @returns {Object}
	 */
	extend (x, y) {
		return merge(...arguments);
	}
}
```


### wdio.config.js

```js
let helpers = require('./helpers');

exports.config = {
	suites: helpers.suites('tests')
}
```

### tests

```
tests 
     foo
         test_1.js
         test_2.js
```

### package.json

```json
{
	"scripts": {
		"test"   : "wdio wdio.config.js",
	},

	"dependencies": {
		"deepmerge"           : "^0.2.10",
		"glob"                : "^7.0.5",
		"webdriverio"         : "^4.1.1",
		"wdio-spec-reporter"  : "^0.0.1",
		"wdio-mocha-framework": "^0.3.4",
	}
}
```

### shell

```js
npm test -- --suite=foo --grep=test_1*;
```

**Comment by wirsingj** [comment] 2016-07-18 15:30
Is this fix going to be put into the main codebase?

**Comment by christian-bromann** [comment] 2016-07-18 15:37
@wirsingj maybe. I was hoping to use the frameworks internals to do that. Haven't investigated that though.

**Comment by wirsingj** [comment] 2016-07-18 17:09
@christian-bromann   Cool, thanks.    I've found this issue also messes with wdio-cucumber-framework's debug support..  it opens a debug port for each of the child processes. :\

**Comment by cheapaschips** [comment] 2016-08-18 14:06
I've been having the same problem with multiple browsers opening up. Is everyone still using @monolithed's work around?

**Comment by wirsingj** [comment] 2016-08-18 14:36
Ive just been specifying the feature file (using cucumber)  for now.   We've been waiting to see if this fix makes it into a release before using the more creative solution :)

**Comment by wirsingj** [comment] 2016-08-18 14:37
Ive just been specifying the feature file (using cucumber)  for now.   We've been waiting to see if this fix makes it into a release before using the more creative solution :)

**Comment by cheapaschips** [comment] 2016-08-18 22:22
Thanks @wirsingj I take it when you say you're using cucumber you're not using the wdio test runner? and running wdio in async mode?

**Comment by wirsingj** [comment] 2016-08-20 23:13
@cheapaschips   We are using the wdio-cucumber test runner in async mode.

**Comment by si-mikey** [comment] 2016-09-19 20:59
any progress on this issue?

**Comment by tripleratamacue** [comment] 2016-09-27 17:49
++1, any status on this?

**Comment by si-mikey** [comment] 2016-09-27 17:58
not much of a workaround but I have used
```js
wdio wdio.conf.js --spec "features/scenarios/test.feature" 
```
this will only launch that one file but if your using tags your out of luck and going to get browsers 1 to 1 of .features.

**Comment by GeoffreyBooth** [comment] 2017-03-01 06:30
In `wdio.conf.js` you can define a function for `specs`:

```js
specs: require('./specs-processor')(process.argv),
```

In my case:
```js
const fs = require('fs');
const path = require('path');

const dir = require('node-dir'); // https://github.com/fshost/node-dir


/**
 * Based on https://github.com/webdriverio/cucumber-boilerplate/blob/master/src/tagProcessor.js
 * If specific tags are specified, and match the filename of a feature file, only load that/those feature files
 * Workaround for https://github.com/webdriverio/wdio-cucumber-framework/issues/8
 *
 * @param  {Object} consoleArguments The arguments to parse from the console
 * @return {Array}                   The specs to process
 */
module.exports = (consoleArguments) => {
  // This is required since this file is not parsed with Babel

  'use strict';

  let specs = [];

  let files = dir.files(path.join(__dirname, 'features'), {sync: true});

  consoleArguments.forEach((val) => {
    if (val.indexOf('--tags=') === 0) {
      const tags = val.replace('--tags=', '').split(',');

      tags.forEach((tagWithAtSymbol) => {
        const tag = tagWithAtSymbol.replace(/^@/, '');
        files.forEach((file) => {
          if (new RegExp(path.sep + tag + '\.feature$').test(file)) {
            file = file.replace(__dirname, '.');
            specs.push(file);
          }
        });
      });
    } else if (val.indexOf('--specs=') === 0) {
      specs = specs.concat(val.replace('--specs=', '').split(','));
    }
  });

  if (specs.length === 0) {
    specs.push('./features/**/*.feature');
  }

  return specs;
};
```

What I’m doing here checking if a requested tag has a matching `.feature` file—so if you want `@foo`, and `foo.feature` exists, set `specs` to just `foo.feature` (or multiple feature files for multiple requested tags). You could go further and search the `.feature` files for the requested tags and only load those; that would actually fix this bug, I suppose. In my case when I have a tag that doesn’t match the feature file filename, I declare the `spec` file explicitly, e.g. `wdio --spec=./features/foo.feature --tags=@wip`

**Comment by ludeknovy** [comment] 2017-06-18 10:54
Any progress on this issue?

**Comment by picklelv** [comment] 2017-07-20 13:16
Is this going to be fixed in wdio or wdio-cucumber-framework?

**Comment by christian-bromann** [comment] 2017-07-20 15:55
Eventually yes, but this has not a high priority since wdio also supports tools to select single specs

**Comment by arunaousula9421** [comment] 2017-10-29 07:47
@christian-bromann Is there any work around for this?? or is it going to be fixed in wdio-cucumber-framework??

**Comment by anilkoithara** [comment] 2018-02-05 16:23
Anybody have any update on this or a work around about the initial Issues or I need  wait for https://github.com/AlexGalichenko/webdriver-io-cucumber/issues/13 to be fixed ?.

**Comment by ivan-myob** [comment] 2018-02-13 21:33
+1 on this issue, super annoying

**Comment by christian-bromann** [comment] 2018-02-13 21:35
We will try to find a way around this in v5

**Comment by gaurist** [comment] 2018-02-13 22:35
Is any work around available as of date for this issue ?

**Comment by christian-bromann** [comment] 2018-02-13 22:36
no, you can define suites and specs with `--spec` or `--suite` , so make sure you only define the tests you actually want to run

**Comment by gaurist** [comment] 2018-02-13 22:59
Hope to see some solution soon to run the files using tags. Facing a lot of problems due to this issue.

**Comment by christian-bromann** [comment] 2018-02-13 23:01
You can use other utilities than tags to structure your tests, I don't even see this as a major or urgent issue.

**Comment by aruiz-caritsqa** [comment] 2018-04-09 23:27
I just tried this out, and it seemed to work first time in the `wdio.conf.js`... probably needs a bit of work, but seems ok

```
const TagExpressionParser = require('cucumber-tag-expressions').TagExpressionParser
const tagParser = new TagExpressionParser()
...
const cucumberTags = process.env.TAGS != null ? process.env.TAGS : 'not @x'
....
const expressionNode = tagParser.parse(cucumberTags)
const filesWithTags = glob.sync('./features/**/*.feature').map((file) => {
    const content = fs.readFileSync(file, 'utf8')
    if (content.length > 0) {
      const tagsInFile = content.match(/(@\w+)/g) || []
      if (expressionNode.evaluate(tagsInFile)) {
        return file
      }
    }
    return null
  }).filter(x => x != null)

...

exports.config = {
  specs: filesWithTags,
...
}
```

You can pass in the tags as an environment variable like this:
`TAGS="@smoke and @dev" ./node_modules/.bin/wdio`

**Comment by gogonutsss** [comment] 2018-07-12 10:53
Tags is the most efficient way to be able to filter our tests against multiple purposes (e.g. characterize a test if it is smoke or regression, if it covers appX or appY, if it covers featureX or featureY and another featureZ. What are the other non tagging options for someone to be able to characterize for more than one aspects his tests and be able to trigger/filter for them for execution?

**Comment by mgrybyk** [comment] 2019-05-17 14:03
How about something like this https://github.com/webdriverio/webdriverio/issues/2859#issuecomment-492802582 ?

**Comment by imranazad** [comment] 2019-09-06 16:15
I've managed to do a very simple work around. It's bit crazy but it works! We needed this because the unnecessary spawning of chrome instances was adding too much time to our deployment time as we wanted to run a subset of tests post deployment without having to duplicate them in a specific post deployments feature file. All I'm doing is looping through all the feature files, extracting tags from each file and then reconstructing the files in another directory. I have a conditional on the "specs" field in wdio.conf.js to pick up the path if the site is being deployed otherwise it uses the default path. 

``` 
specs: [
        helpers.cherryPickTags(featuresDir, taggedFeaturesDir, this_is_running_during_a_deployment) ? "./"+taggedFeaturesDir+"**/*.feature" : "./"+featuresDir+"**/*.feature"
    ],
```
```
var path = require("path");
var fs  = require('fs');

module.exports = {
    cherryPickTags:function(featuresDir, taggedFeaturesDir, this_is_running_during_a_deployment){  
        if(this_is_running_during_a_deployment)
        {
            if (!fs.existsSync(taggedFeaturesDir)) {
                console.log("Cherry picking tags from feature files...");
                fs.mkdirSync(taggedFeaturesDir);
                fs.readdir(featuresDir, (err, files) => {
                  files.forEach(file => {
                        fs.readFile(featuresDir+file, 'utf8', function(err, contents) {
                            if(contents != null){
                                var featureBody = contents.replace(/Scenario:.+|Scenario Outline:.+/s,"");
                                featureBody = featureBody.replace("@postDeploymentTests", "");
                                var tags = contents.match(/@postDeploymentTests.+.^\n|@postDeploymentTests.+.$/msg)
                                if(tags != null)
                                {
                                    featureBody = featureBody + tags.join("\n");
                                    fs.writeFile(taggedFeaturesDir+file, featureBody, (err) => {
                                      if (err) throw err;
                                      console.log('Feature file with tags created: ' + file);
                                    });
                                }

                            }
                        });
                  });
                });
             }
        } 
        return this_is_running_during_a_deployment;
    }
}
```
If you are going to use this just remember to change the regex entries to your specific tag.

**Comment by mgrybyk** [comment] 2019-10-04 15:11
Gonna be implemented in https://github.com/webdriverio/webdriverio/pull/4531

**Closed by mgrybyk** 2019-10-04 15:11 UTC
Labels: Enhancement
