### ISSUE TITLE
Host and port error

### ISSUE THREAD

**Issue by cristian-smocot** [webdriverio/webdriverio#628] opened 2015-07-13 13:48 UTC
The following `options` object 
``` javascript
{
	host                    : '127.1.2.3',
	port                    : 4444
	desiredCapabilities     : {
		seleniumProtocol    : 'WebDriver',
		platform            : 'ANY',
		browserName         : 'chrome',
		acceptSslCerts      : true,
		cssSelectorsEnabled : true,
		handlesAlerts       : true
	}
}
```
doesn't work any more in version 3.1.0 (it worked just fine in version 2.4.5)

I have a Selenium Hub server that listens on 127.1.2.3:4444.

After investigating, I think that the culprit are the following lines in [__`lib/helpers/detectSeleniumBackend.js`__](https://github.com/webdriverio/webdriverio/blob/master/lib/helpers/detectSeleniumBackend.js)

``` javascript
 /**
     * local Selenium server
     */
    if(!capabilities.user || !capabilities.key) {
        return {
            host: '127.0.0.1',
            port: 4444
        };
    }
```

Why do you assume that `host` and `port` properties must be used together with a user or key (auth token or what key is)?

This should be corrected. I do not use Saucelabs or some other cloud platform. I have my own Selenium Hub and I do not use a user to authenticate to it.

If I pass a `host` and a `port` that should just work.

**Comment by cristian-smocot** [comment] 2015-07-13 14:07
Update:
after setting logLevel to verbose, I get:
```
[16:06:22]:  COMMAND    POST     "/wd/hub/session"
[16:06:22]:  DATA                {"desiredCapabilities":{"browserName":"chrome","version":"","javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"platform":"ANY","loggingPrefs":{"driver":"WARNING","browser":"INFO","server":"SEVERE"},"acceptSslCerts":true,"cssSelectorsEnabled":true,"requestOrigins":{"url":"http://webdriver.io","version":"3.1.0","name":"webdr
iverio"}}}
[16:06:22]:  ERROR      Unknown Remote end send an unknown status code.
```
__ Unknown Remote end send an unknown status code__

**Comment by cristian-smocot** [comment] 2015-07-13 14:20
When changing to version __2.4.5__, it works perfectly. Something must be screwed up in v.3.1.0 that loses the host.

**Comment by cristian-smocot** [comment] 2015-07-13 14:26
I believe that the logic of [__`lib/helpers/detectSeleniumBackend.js`__](https://github.com/webdriverio/webdriverio/blob/master/lib/helpers/detectSeleniumBackend.js) is not very good.

You should simply allow us the developers to use the host, port and key as we like. What's the sense in  parsing the length of the `key` and depending on the length assuming that the user wants to use a specific host??
What if in the future the length of the key for, say SauceLabs changes? 

The developer should simply define in the options object the host, port (&key) he would like to use for the test session.

**Comment by christian-bromann** [comment] 2015-07-13 14:53
> When changing to version 2.4.5, it works perfectly. Something must be screwed up in v3.1.0 that loses the host value from the options object used to create the client

mhm .. it should not. As you can see [here](https://github.com/webdriverio/webdriverio/blob/master/lib/webdriverio.js#L41) everything that comes from lib/helpers/detectSeleniumBackend.js only gets applied if host & port isn't set. If you set host and port WebdriverIO will go with those values. Let me investigate this.

My general idea behind this was that setting host & port for cloud services are kind of a redundant task. Since the keys differentiate from each other I thought it could make the live of people easier.

> What if in the future the length of the key for, say SauceLabs, changes?

I doubt that key length changes that often since they are tightly coupled to an username. I can imagine that the key format might change in future but this is an easy fix to do.

**Comment by christian-bromann** [comment] 2015-07-13 14:57
mhm .. I just started a standalone server on port `5555` and was able to connect to it using this script:

```js
var client = require('webdriverio').remote({
    host                    : '127.0.0.1',
    port                    : 5555,
    desiredCapabilities     : {
        seleniumProtocol    : 'WebDriver',
        platform            : 'ANY',
        browserName         : 'chrome',
        acceptSslCerts      : true,
        cssSelectorsEnabled : true,
        handlesAlerts       : true
    }
});


client.init().end();
```

**Comment by christian-bromann** [comment] 2015-07-13 15:00
@cristian-smocot could you debug what the output of that line is:
https://github.com/webdriverio/webdriverio/blob/master/lib/webdriverio.js#L41 ?

**Comment by cristian-smocot** [comment] 2015-07-13 15:08
The output of line
https://github.com/webdriverio/webdriverio/blob/master/lib/webdriverio.js#L41
 ```
Debug webdriver 
{ host: '127.1.2.3',
  port: 4444,
  protocol: 'http',
  waitforTimeout: 500,
  coloredLogs: true,
  logLevel: 'silent',
  baseUrl: null,
  desiredCapabilities:
   { seleniumProtocol: 'WebDriver',
     platform: 'ANY',
     browserName: 'chrome',
     loggingPrefs: { driver: 'WARNING', server: 'SEVERE', browser: 'INFO' },
     acceptSslCerts: true,
     cssSelectorsEnabled: true,
     handlesAlerts: true } 
}
```

**Comment by cristian-smocot** [comment] 2015-07-13 15:10
Who/what generate the error __Unknown Remote end send an unknown status code__?

**Comment by christian-bromann** [comment] 2015-07-13 15:13
This error is generated by chromedriver. It has a problem with the capabilities and the standalone server returns with that is not 200. Could you check your standalone server logs? Maybe try to run the chromedriver as standalone?

**Comment by cristian-smocot** [comment] 2015-07-13 15:13
__logLevel : 'verbose'__

```
[17:12:04]:  COMMAND    POST     "/wd/hub/session"
[17:12:04]:  DATA                {"desiredCapabilities":{"browserName":"chrome","version":"","javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"platform":"ANY","loggingPrefs":{"driver":"WARNING","browser":"INFO","server":"SEVERE"},"seleniumProtocol":"WebDriver","acceptSslCerts":true,"cssSelectorsEnabled":true,"requestOrigins":{"url":"http://webdriver.io",
"version":"3.1.0","name":"webdriverio"}}}
[17:12:05]:  ERROR      Unknown Remote end send an unknown status code.
```

**Comment by christian-bromann** [comment] 2015-07-13 15:14
These are the webdriverio logs, the selenium standalone server logs will have more information. Also could you remove `seleniumProtocol    : 'WebDriver'` and try again. Afaik this is deprecated.

**Comment by cristian-smocot** [comment] 2015-07-13 15:18
I don't think the error is generated by ChromeDriver be cause when looking at the logs of the SeleniumHub I see no connection to it. So it doesn't even connect to the hub, it it can't be generated by the Chrome node I use in the grid, because first it connects to the Hub who the forwards the request to the node.

Logs from Selenium Hub: 
```
starting selenium hub with configuration:

{
  "host": null,
  "port": 4444,
  "prioritizer": null,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "newSessionWaitTimeout": -1,
  "jettyMaxThreads": -1,
  "nodePolling": 5000,
  "cleanUpCycle": 5000,
  "timeout": 300000,
  "browserTimeout": -1,
  "maxSession": 5,
  "unregisterIfStillDownAfter": 30000
}
15:11:52.091 INFO - Launching Selenium Grid hub
2015-07-13 15:11:53.016:INFO:osjs.Server:jetty-7.x.y-SNAPSHOT
2015-07-13 15:11:53.057:INFO:osjsh.ContextHandler:started o.s.j.s.ServletContextHandler{/,null}
2015-07-13 15:11:53.067:INFO:osjs.AbstractConnector:Started SocketConnector@0.0.0.0:4444
15:11:53.068 INFO - Nodes should register to http://172.17.0.31:4444/grid/register/
15:11:53.068 INFO - Selenium Grid hub is up and running
15:11:59.289 INFO - Registered a node http://172.17.0.32:5555
```

Logs from the Chrome node:
```
08:11:58.320 INFO - Launching a Selenium Grid node
08:11:59.090 INFO - Java: Oracle Corporation 24.79-b02
08:11:59.090 INFO - OS: Linux 4.0.5-boot2docker amd64
08:11:59.096 INFO - v2.46.0, with Core v2.46.0. Built from revision 87c69e2
08:11:59.162 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{platform=WINDOWS, ensureCleanSession=true, browserName=internet explorer, version=}] does not match the current platform LINUX
08:11:59.162 INFO - Driver class not found: com.opera.core.systems.OperaDriver
08:11:59.162 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
08:11:59.216 INFO - Version Jetty/5.1.x
08:11:59.217 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
08:11:59.218 INFO - Started HttpContext[/selenium-server,/selenium-server]
08:11:59.218 INFO - Started HttpContext[/,/]
08:11:59.221 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@534041ec
08:11:59.222 INFO - Started HttpContext[/wd,/wd]
08:11:59.227 INFO - Started SocketListener on 0.0.0.0:5555
08:11:59.227 INFO - Started org.openqa.jetty.jetty.Server@55a1a614
08:11:59.228 INFO - Selenium Grid node is up and ready to register to the hub
08:11:59.264 INFO - Starting auto registration thread. Will try to register every 5000 ms.
08:11:59.264 INFO - Registering the node to the hub: http://172.17.0.31:4444/grid/register
08:11:59.290 INFO - The node is registered to the hub and ready to use
```

In version 2.4.5 I can see in the logs how the Hub receives a request from Webdriver and forwards it to the Chrome node.

**Comment by christian-bromann** [comment] 2015-07-13 15:20
Your hub is running on `http://172.17.0.31:4444` why do you have the host set to `127.1.2.3:4444` then?

**Comment by cristian-smocot** [comment] 2015-07-13 15:22
I use Docker, on Windows which uses boot2docker (virtual machine).

So when I start my Docker containers (of the Selenium Hub  and teh Chrome node) they register with those virtual IPs. The hub is listening on port 4444.
So in Virtual Box I map the guest port (4444) to my Host machine (127.1.2.3:4444).

**Comment by christian-bromann** [comment] 2015-07-13 15:24
Ok, I am wondering what has changed compared to `v2.4.5`. Could you please check what the fullRequestOptions are at https://github.com/webdriverio/webdriverio/blob/master/lib/utils/RequestHandler.js#L149
compared to `v2.4.5`?

**Comment by cristian-smocot** [comment] 2015-07-13 15:31
__v.3.1.0__
```
fullRequestOptions 
{ uri:
   { protocol: 'http:',
     slashes: true,
     auth: null,
     host: '127.1.2.3:4444',
     port: '4444',
     hostname: '127.1.2.3',
     hash: null,
     search: null,
     query: null,
     pathname: '/wd/hub/session',
     path: '/wd/hub/session',
     href: 'http://127.1.2.3:4444/wd/hub/session' },
  method: 'POST',
  json: true,
  followAllRedirects: true,
  headers:
   { Connection: 'keep-alive',
     Accept: 'application/json',
     'User-Agent': 'webdriverio/webdriverio/3.1.0',
     'Content-Type': 'application/json; charset=UTF-8',
     'Content-Length': 377 },
  body: '{"desiredCapabilities":{"browserName":"chrome","version":"","javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"platform":"ANY","loggingPrefs":{"driver":"WARNING","browser":"INFO","server":"SEVERE"},"acceptSslCerts":true,"cssSelectorsEnabled":true,"requestOrigins":{"url":"http://webdriver.io","version":"3.1.0","name":"webdriverio"}}}' }
```

**Comment by cristian-smocot** [comment] 2015-07-13 15:37
they look the same to me.

**Comment by christian-bromann** [comment] 2015-07-13 15:41
Thanks for helping me debugging that thing. I guess we can narrow it down to `request` then. I've updated the module from `~2.34.0` to `~2.49.0`

**Comment by christian-bromann** [comment] 2015-07-13 15:54
ok, just tried to reproduce the problem by setting up a hub + node server but it was working fine

**Comment by cristian-smocot** [comment] 2015-07-13 15:55
@https://github.com/webdriverio/webdriverio/blob/master/lib/utils/RequestHandler.js#L198 
`body` is undefined.

That is why I get `Remote end send an unknown status code.`

**Comment by christian-bromann** [comment] 2015-07-13 15:58
could you log the response object and put it in a gist, maybe we will find something in there

**Comment by cristian-smocot** [comment] 2015-07-13 15:59
```
request error null
```
```
body  <HTML><HEAD>
<TITLE>Network Error</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Network Error (tcp_error)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
A communication error occurred: "Connection refused"
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>
For assistance, contact your network support team.
</FONT>
</TD></TR>
</TABLE>
</blockquote>
</FONT>
</BODY></HTML>
```
```
body status undefined

```

**Comment by christian-bromann** [comment] 2015-07-13 16:02
interesting `Network Error (tcp_error)`
according to [SO](http://stackoverflow.com/a/18783114/765174) it seems to be Selenium related?

**Comment by christian-bromann** [comment] 2015-07-13 16:02
Could you try these instructions?

**Comment by cristian-smocot** [comment] 2015-07-13 16:09
response Gist https://gist.github.com/cristian-smocot/7b9db5556bbc46fce671

**Comment by cristian-smocot** [comment] 2015-07-13 16:20
I think I solved it.

I defined a __`NO_PROXY = 127.1.2.3`__ environment variable on my Windows PC. And now I can see logs in the Selenium Hub, that show that __webdriverio__ managed to connect to the hub and is executing commands.

**Comment by christian-bromann** [comment] 2015-07-13 16:22
Sweet! So everything is running now?
Closing.

**Closed by christian-bromann** 2015-07-13 16:22 UTC

**Comment by cristian-smocot** [comment] 2015-07-13 16:24
For some reason in 2.4.5 is you had proxies defined, it worked if you didn't have NO_PROXY environment variables. But in 3.1.0, request needs you to explicituly set NO_PROXY for those hostname that don't need to pass trough the proxy.

It appears to be working (I'm tired, so I'll test tomorrow more)

**Comment by christian-bromann** [comment] 2015-07-13 16:26
I see, this seems to be the solution then. According to request/request#1096 it got introduced in request `v2.49.0`
