### ISSUE TITLE
[🐛 Bug]: SevereServiceError: Couldn't start Chromedriver: timeout Please check if port 9515 is in use

### ISSUE THREAD

**Issue by philippthiele** [webdriverio/webdriverio#8522] opened 2022-07-13 12:13 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.20.5

### Node.js Version

16.15.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
        maxInstances: 1,
        browserName: 'chrome',
        'goog:chromeOptions':  {
            args: [
                "--window-size=1920,1080",
                "--lang=en-US",
                "--disable-gpu",
                "--disable-extensions",
                "--disable-translate",
                "--no-sandbox",  // important! without this browser cannot be reached in pipeline
                "--disable-popup-blocking"
            ]
        }
    }
```

### What happened?

When using wdio-chromedriver-service >= 7.2.8 the chromedriver can't be started. Using chromedriver version 103.0.0.

Question has been asked on Stackoverflow and workaround is using version 7.2.8

### What is your expected behavior?

chromedriver can be started

### How to reproduce the bug.

Use wdio-chromedriver-service >= 7.2.8

### Relevant log output

```typescript
npm run wdio

> webdriverio-tests@0.1.0 wdio
> wdio run wdio.conf.js


Execution of 1 workers started at 2022-03-14T18:56:58.789Z

2022-03-14T18:56:58.810Z INFO @wdio/cli:launcher: Run onPrepare hook
2022-03-14T18:56:58.811Z INFO chromedriver: Start Chromedriver (/home/davidshare/Documents/davidshare/QA/webdriverio-test/node_modules/chromedriver/lib/chromedriver/chromedriver) with args --port=9515 --url-base=/
2022-03-14T18:56:58.820Z INFO chromedriver: Starting ChromeDriver 99.0.4844.51 (d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}) on port 9515
2022-03-14T18:56:58.821Z INFO chromedriver: Only local connections are allowed.
2022-03-14T18:56:58.821Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2022-03-14T18:56:58.821Z INFO chromedriver: ChromeDriver was started successfully.
2022-03-14T18:57:08.818Z INFO @wdio/local-runner: Shutting down spawned worker
2022-03-14T18:57:09.070Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2022-03-14T18:57:09.071Z INFO @wdio/local-runner: shutting down
Error: 
A service failed in the 'onPrepare' hook
SevereServiceError: Couldn't start Chromedriver: timeout
Please check if port 9515 is in use!
    at ChromeDriverLauncher.onPrepare (/home/davidshare/Documents/davidshare/QA/webdriverio-test/node_modules/wdio-chromedriver-service/build/launcher.js:96:13)
    at async /home/davidshare/Documents/davidshare/QA/webdriverio-test/node_modules/@wdio/cli/build/utils.js:28:17
    at async Promise.all (index 0)
    at async Launcher.run (/home/davidshare/Documents/davidshare/QA/webdriverio-test/node_modules/@wdio/cli/build/launcher.js:86:13)



Stopping runner...
    at /home/davidshare/Documents/davidshare/QA/webdriverio-test/node_modules/@wdio/cli/build/utils.js:44:35
    at async Launcher.run (/home/davidshare/Documents/davidshare/QA/webdriverio-test/node_modules/@wdio/cli/build/launcher.js:86:13)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2022-07-13 17:19
As the error states, wdio-chromedriver-service is unable to start on the default port `9515`. If this port is used please set a different port in the capabilities. Closing as this is not a bug.

**Closed by christian-bromann** 2022-07-13 17:19 UTC
Labels: Bug 🐛, Needs Triaging ⏳

**Comment by nair-sumesh** [comment] 2022-11-10 17:05
HI,
Passing the port number in the config.capabilities, or via command line --port = 4444, or -p=4444, is not being considered. I am still getting the error.
**CMD line**
```cmd
npx wdio /home/jenkins/agent/workspace/##########/conf/wdio_chrome_mocha.conf.js -p=4444 --verbose
```
**Result**
```log
10:19:13  2022-11-10T15:19:13.720Z INFO chromedriver: Start Chromedriver (/home/jenkins/agent/workspace/##########/node_modules/chromedriver/lib/chromedriver/chromedriver) with args --port=9515 --url-base=/
```

**Comment by christian-bromann** [comment] 2022-11-10 17:08
I am not sure what your script (`wdio_chrome_mocha.conf.js`) is doing here.
