### ISSUE TITLE
`browser.setValue` only does appending without clearing textfield on Chrome 70 on Chromdriver 2.43

### ISSUE THREAD

**Issue by DrakeW** [webdriverio/webdriverio#3024] opened 2018-10-24 21:41 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** 4.12.0
 - **Mode:** WDIO Test runner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version**: 8.8.1
 - **NPM version:** 5.5.1
 - **Browser name and version:** Chrome 70
 - **Platform name and version:** Windows 7
 - **Additional wdio packages used (if applicable):** None

**Config of WebdriverIO**

**Describe the bug**
`browser.setValue` doesn't clear the text field anymore, and only append characters. We noticed the difference after Saucelab changed its chrome version from Chrome 69 to Chrome 70.

Update: the issue is solved temporarily on our side by locking chromedriver version to `2.41`, and the `setValue` behavior changed when running with chromedriver `2.43`

**To Reproduce**
Write a test that set value to a text field using `browser.setValue`

**Expected behavior**
Textfield should be cleared first before adding characters

**Log**
```
[1540415680.649][INFO]: Waiting for pending navigations...
[1540415680.654][INFO]: Done waiting for pending navigations. Status: ok
[1540415680.654][INFO]: [e5c4c773e39d5016e546eb515334594a] RESPONSE ClearElement
[1540415680.865][INFO]: [e5c4c773e39d5016e546eb515334594a] COMMAND TypeElement {
   "id": "0.17530959876229257-2",
   "text": "foobar",
   "value": [ "f", "o", "o", "b", "a", "r" ]
}
```

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment] 2018-10-31 20:39
@DrakeW this is a known issue with Chrome. If you find a workaround please share. This issue is most likely to stale an being closed eventually since it should be fixed on Chromedriver side.

**Comment by DrakeW** [comment] 2018-11-01 02:11
@christian-bromann good to know! our workaround is to set manually set chromedriver version to 2.41 and chrome version to 69 in the capability of the config file
```
config.capabilities = [{
  browserName: 'chrome',
  version: '69',
  chromedriverVersion: '2.41',
}];
```

**Comment by christian-bromann** [comment] 2018-12-03 22:48
I don’t know the issue number

**Comment by christian-bromann** [comment] 2018-12-05 10:36
Closing. This issue needs to be reported in Chromedriver. WebdriverIO sends the commands according to the W3C WebDriver spec.

**Closed by christian-bromann** 2018-12-05 10:36 UTC
Labels: Needs Investigation, Protocol Related, Reproducible Example Missing, help wanted

**Comment by y-okady** [comment] 2019-01-10 04:14
This is our workaround.
```js
browser.waitUntil(() => {
  // attempt to clear value by setValue
  browser.setValue(selector, '');
  // attempt to clear value by JavaScript injection
  browser.execute((s) => {
    document.querySelector(s).value = '';
  }, selector);
  // set value
  browser.setValue(selector, value);
  // retry if the value is not correct
  return browser.getValue(selector) === value;
}, 60000);
```

**Comment by y-okady** [comment] 2019-01-10 06:14
I think this may be smarter than the above workaround.
```js
browser.setValue(selector, '\uE003'.reppeat(browset.getValue(selector).length) + value);
```

**Comment by abjerstedt** [comment] 2019-01-10 13:13
This is an issue with react specifically. It was already reported to chromedriver and closed with a "won't fix".

**Comment by kajmagnus** [comment] 2019-01-25 08:41
@y-okady  thanks I like that workaround. Simpler than the other workarounds.  B.t.w. this (from your 1st workaround): `browser.setValue(selector, '');` usually doesn't work / never-works for me (nothing happens) — instead, I do:  `browser.setValue(selector, ' ');`  that is, clear, by typing a space.

@abjerstedt 

> Other browsers have the same behavior fyi.

For me, with React, Firefox works fine with `setValue`. It properly clears the value.  FF, Ubuntu Linux, It's only Chrome that now just recently (December?) has started appending the text instead.  FF 64, and:

``
    "selenium-standalone": "^6.15.4",
    "webdriverio": "^4.14.1"
```

**Comment by ArthurGIT2017** [comment] 2019-04-09 18:08
Please be aware that blur event handlers running on the page restoring the contents after ChromeDriver has cleared it, so that will explain why you may see appending a new value to the old one. Please make sure if the web page you are using in your code has blur event handler.

Clear command in ChromeDriver 2.43 and above has been updated to conform to the new W3C WebDriver specification, so step 5 of  that specification requires ChromeDriver to move the focus away from the element that has just been cleared. So, if you are running hromeDriver 2.43 and upper version, then in order to set value after element was cleared you'll need to set focus back to the element.

**Comment by kajmagnus** [comment] 2019-04-10 04:30
@ArthurGIT2017  

> blur event handlers running on the page restoring the contents after ChromeDriver has cleared it

You mean if one has one's own *blur* event handler that does that?

B.t.w. here's a topic about Chromedriver and that weird extra *blur* after clear(): https://github.com/w3c/webdriver/issues/1354  — I wonder why that was added to the spec, making Selennium behave differently than a real browser and person, right :- /  (who deletes all text with ctrl-a-delete and starts typing something new)

**Comment by pathmapper** [comment] 2019-06-14 19:41
Here is the bug on the `chromedriver` issue tracker https://bugs.chromium.org/p/chromedriver/issues/detail?id=2842

> Without more details, there isn't much we can do to help.
> Closing the bug as we're unable to repro this issue. 
> Please let us know if you have additional information that can help us to reproduce the issue.

**Comment by Mufeez** [comment] 2019-08-31 12:18
browser.waitUntil(() => {
        // attempt to clear value by setValue
        configurationPage.complianceNumberOfExtraLetters.setValue(' ');
        // attempt to clear value by JavaScript injection
        browser.execute((s) => {
          document.querySelector(s).value = '3';
        }, '#extraLetters');
        // set value
      //  configurationPage.complianceNumberOfExtraLetters.setValue('3');
        // retry if the value is not correct
        return configurationPage.complianceNumberOfExtraLetters.getValue() === '3';
      }, 60000);
Worked for me in webdriverIO 5 for a react input

**Comment by kathar1223** [comment] 2019-10-16 04:27
Working Code 
`const username = "admin"
const password = "12345"
    browser.execute(setUserName,username)
    function setUserName(username){
        var userNameElement = document.querySelector(`[data-qa=\'input-username\']`);
        var event = new Event('input',{bubbles:true});
        const previousValue = userNameElement.value
        userNameElement.value = username
        console.log(previousValue)
        userNameElement._valueTracker.setValue(previousValue)
        userNameElement.dispatchEvent(event)
    }
   

    browser.execute(setPassword,password)
    function setPassword(password){
        var passwordElement = document.querySelector(`[data-qa=\'input-password\']`);
        var event = new Event('input',{bubbles:true});
        const previousValue = passwordElement.value
        passwordElement.value = password
        passwordElement._valueTracker.setValue(previousValue)
        passwordElement.dispatchEvent(event)
    }
`

**Comment by emtammaru** [comment] 2019-10-16 20:35
> Closing. This issue needs to be reported in Chromedriver. WebdriverIO sends the commands according to the W3C WebDriver spec.

@christian-bromann even if this is an issue that chromedriver _should_ technically fix, it would be really awesome if webdriver had a workaround for it. It has been a year since this was reported, and chromedriver still hasn't _fixed_ the issue.

**Comment by emtammaru** [comment] 2019-10-16 20:56
@kathar1223, thank you!  That workaround worked for me.  Here's a more generic version:
```
function setValue(selector, value) {
  browser.execute((selector, value) => {
    var elem = document.querySelector(selector);
    var event = new Event('input', { bubbles: true });
    const previousValue = elem.value
    elem.value = value
    elem._valueTracker.setValue(previousValue)
    elem.dispatchEvent(event)
    elem.focus();
  }, selector, value);
}
```

**Comment by mgrybyk** [comment] 2019-10-16 21:27
Works fine in latest chrome with latest chromedriver, not sure what kind of workarounds are you looking for.
Can you please clarify?

**Comment by emtammaru** [comment] 2019-10-16 21:58
@mgrybyk it does not work fine in latest chrome with latest chromedriver.

I just updated all my wdio packages to the latest versions (using the guide here: https://webdriver.io/blog/2018/12/19/webdriverio-v5-released.html#how-to-upgrade-to-v5), retested, and the same thing happens where the text is appended without clearing.
```
"webdriverio": "^5.15.1",
"chromedriver": "^77.0.0",
```
Chrome Version 77.0.3865.90 (Official Build) (64-bit).  

This issue is happening with a react, state-controlled, material-ui input.  As mentioned above, the workaround that kathar1223 gave fixes the issue.

**Comment by mgrybyk** [comment] 2019-10-16 22:14
Got it, great that it works

**Comment by R0m3rCh** [comment] 2020-01-30 15:18
In my case I performed a `Ctrl+A`:
```sh
browser.keys(['\ue009', 'a']);
browser.setValue(selector, value);
```

**Comment by vinicius-vilacalara** [comment] 2020-01-31 19:10
Hello @R0m3rCh ! Which webdriverIO version are you using? v4 right?
I tried all of the solution above and it did not work.

**Comment by R0m3rCh** [comment] 2020-02-03 12:13
> Hello @R0m3rCh ! Which webdriverIO version are you using? v4 right?
> I tried all of the solution above and it did not work.

Actually my wdio version is 5.16

**Comment by abjerstedt** [comment] 2020-02-05 21:19
@vinicius-vilacalara If you send a backspace for every letter in the textfield... it'll clear it for you. This is particular to react if i recall correctly.

**Comment by rrivem** [comment] 2020-03-13 03:25
> This is an issue with react specifically. It was already reported to chromedriver and closed with a "won't fix". React resets the value when focus is just in an attempt to "repair" the element.
> 
> Other browsers have the same behavior fyi.

Following this suggestion we found the issue was originated by the use of the custom controlled fields we have in our project. Here's a snippet of how the Field looks like:

```
/// Field.js
class Field extends React.Component {
	constructor(props) {
		super(props);

		this.handleBlur = this.handleBlur.bind(this);
		this.handleFocus = this.handleFocus.bind(this);
		this.handleInputChange = this.handleInputChange.bind(this);

		this.state = { focused: false, value: props.value };
	}

	render() {
		const { name } = this.props;
		const { focused, value } = this.state;

		return (
					<input
						name={name}
						value={value}
						style={focused && {border-color: 'blue'}}
						onChange={this.handleInputChange}
						onBlur={this.handleBlur}
						onFocus={this.handleFocus}
					/>
		);
	}

	handleBlur({ target }) {
		this.setState({ focused: false });
		this.props.onBlur(target);
		if (target.value !== this.state.originalValue) {
			this.props.onValueChanged(target);
		}
	}

	handleFocus() {
		this.setState({ focused: true, originalValue: this.state.value });
		this.props.onFocus();
	}

	handleInputChange(event) {
		const { value, name } = event.target;
		this.setState({ value }, () => {
			this.props.onChange({ name, value });
		});
	}
}
```

And a Form using it:
```
/// Form.js
function Form() {
	const [value1, setValue1] = useState('');
	return (<div>
		<input name="test1" value={value1} onChange={event => setValue1(event.target.value)} />
		<Field name="test2" value={value2} onChange={({ value }) => setValue2(value)} />
	</div>);
}
```

The wdio test:
```
/// Test.js
	this.test1.setValue('hello');
	this.test1.setValue('world');
	console.info(this.test1.getValue());
	this.test2.setValue('hello');
	this.test2.setValue('world');
	console.info(this.test2.getValue());
```

If you run this test with wdio (V4 in our case) you'll be able to reproduce the bug for test2 (helloworld printed in the latter, instead of world) shows but it works fine for an input with simple events.

Then, if we change the first line in `handleBlur` from `this.setState({ focused: false });` to `this.setState({ focused: false, value: target.value });`, the bug is not reproducible anymore, which matches what @ArthurGIT2017 mentioned above. Setting the value at this callback should be irrelevant, but avoids the restoring of the previous value.

So please consider revisiting how you're handling your input events.

**Comment by coustoue** [comment] 2020-04-30 15:57
Maybe it will be useful for someone. My workaround for input is:
```
function setInput(selector, text='') {
  it ('Set ' + selector), function (){
    return this.browser
      .waitForVisible(selector)
      .click(selector)
      .keys(["\ue009"+"a", "\ue017", "\ue000"]) // ctr+a, del
      .setValue(selector, text)
      .getValue(selector)
      .then((value) => {
        if (value!==text) { assert.fail('Typed value : Actual value' + text + ':' + value) }
      })
  })
}
```

**Comment by jedwards1211** [comment] 2020-11-20 07:04
There should really be a builtin webdriver command to change the value of an input and fire an event as if a user did select all and pasted the new value.
