### ISSUE TITLE
[🐛 Bug]: WDIO 8.21.0JUnit report is no more 100% working on bitbucket pipelines

### ISSUE THREAD

**Issue by MarcusQA1982** [webdriverio/webdriverio#11621] opened 2023-11-06 15:54 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.21.0

### Node.js Version

20

### Mode

Standalone Mode

### What happened?

After my update from WDIO 6 to WDIO 8 (exactly 8.21.0), bitbucket pipelines duplicates the number of failures and the tab tests doesn't display the failures results.
I suspect that bitbucket pipeline sum failures + errors but in WDIO 6 the numbers were corrects, probably the logic of these numbers are changed in JUnit!
For the empty errors results, I saw that there is the new <failures> tag.

### How to reproduce the bug.

run a failing test on bitbucket pipeline with WDIO8 

### Relevant log output

```typescript
<testsuite name="and remove all query" timestamp="2023-11-03T16:20:39" time="22.667" tests="5" failures="1" errors="1" skipped="0">
    <properties>
      <property name="specId" value="0"/>
      <property name="suiteName" value="XXXXXX"/>
      <property name="capabilities" value="chrome.111_0_5563_146.linux"/>
      <property name="file" value="file://./tests/XXXXXXX.js"/>
    </properties>
    <testcase classname="chrome.111_0_5563_146.linux.SUITE.TESTNAME" name="TESTNAME" time="13.04">
      <failure/>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2023-11-06 17:32
Thanks for reporting!

> For the empty errors results, I saw that there is the new tag.

Would you mind help raise a PR with a fix? I am not familiar with JUnit to much nor do I have access to a BitBucket pipeline.

We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by MarcusQA1982** [comment] 2023-11-07 09:04
Sorry but I'm not able to help you but i need this fix asap ! :(
In another way, in which version this change was made?

**Comment by MarcusQA1982** [comment] 2023-11-07 13:14
> Thanks for reporting!
> 
> > For the empty errors results, I saw that there is the new tag.
> 
> Would you mind help raise a PR with a fix? I am not familiar with JUnit to much nor do I have access to a BitBucket pipeline.
> 
An important thing: a part of bitbucket, the counters are wrong, isn't it? Do you know that there's a bug? the failures are always the same of errors then some logic has changed.

**Comment by BorisOsipov** [comment] 2023-11-07 14:14
Seems like a failed test [here ](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-junit-reporter/src/index.ts#L135) and [here ](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-junit-reporter/src/index.ts#L213)is always marked as a failure, even if it was marked as an error before. Not sure when it was done and if it is correct or not.

**Comment by MarcusQA1982** [comment] 2023-11-07 14:26
but why in wdio 6 only the errors were counted? maybe now the failures contains failures + errors?

**Comment by MarcusQA1982** [comment] 2023-11-09 09:10
I think it's the same error:
https://lightrun.com/answers/webdriverio-webdriverio-wdio-junit-reporter---extra-failure-tag-breaks-circleci-from-error-message-reporting

**Comment by bog777bog** [comment] 2023-11-09 16:07
@MarcusQA1982 @christian-bromann,

I suppose this bug relates to this one which has been already raised.

[🐛 Bug]: @wdio/junit-reporter in WebDriverIO v8 with CucumberJS shows step counts instead of test counts in JUnit report #11574

**Comment by MarcusQA1982** [comment] 2023-11-09 16:39
> @MarcusQA1982 @christian-bromann,
> 
> I suppose this bug relates to this one which has been already raised.
> 
> [🐛 Bug]: @wdio/junit-reporter in WebDriverIO v8 with CucumberJS shows step counts instead of test counts in JUnit report #11574

<it's not the same but it's affected by the same change. I don't understand how is it possible that about 1 year we have this problem.Wrong counters and empty result

**Comment by MarcusQA1982** [comment] 2023-11-10 08:20
sure!
BEFORE:
```
<testsuite name="and remove all query" timestamp="2023-11-03T16:20:39" time="22.667" tests="5" failures="0" errors="1" skipped="0">
    <properties>
      <property name="specId" value="0"/>
      <property name="suiteName" value="XXXXXX"/>
      <property name="capabilities" value="chrome.111_0_5563_146.linux"/>
      <property name="file" value="file://./tests/XXXXXXX.js"/>
    </properties>
    <testcase classname="chrome.111_0_5563_146.linux.SUITE.TESTNAME" name="TESTNAME" time="13.04">
```

AFTER:
```
<testsuite name="and remove all query" timestamp="2023-11-03T16:20:39" time="22.667" tests="5" failures="1" errors="1" skipped="0">
    <properties>
      <property name="specId" value="0"/>
      <property name="suiteName" value="XXXXXX"/>
      <property name="capabilities" value="chrome.111_0_5563_146.linux"/>
      <property name="file" value="file://./tests/XXXXXXX.js"/>
    </properties>
    <testcase classname="chrome.111_0_5563_146.linux.SUITE.TESTNAME" name="TESTNAME" time="13.04">
      <failure/>
```

**Comment by MarcusQA1982** [comment] 2023-11-10 08:36
As you can see, the first problem it that the counters are pretty different, it seems that the failures are always the same as the errors but BEFORE only the error counters was incremented. 
The second difference is the failure tag

**Comment by christian-bromann** [comment] 2023-11-10 16:55
@MarcusQA1982 I assume here that certain changes landed to fix issues related to using the JUnit reporter in Cucumber which might cause an undesired behavior in Jasmine or Mocha. @BorisOsipov has pointed out some great starting points to look at certain changes made in the past. As I mentioned in my previous comment, any contributions are welcome!

**Comment by christian-bromann** [comment] 2024-05-28 06:26
Closing this due to inactivity. I don't see much actionable here for anyone outside to pick this up. I am happy to re-open if a reproducible example can be provided.

**Closed by christian-bromann** 2024-05-28 06:26 UTC
Labels: Bug 🐛, help wanted, good first pick
