### ISSUE TITLE
[🐛 Bug]: ScrollIntoView Not Working with Class Selector and Out of Bounds Error

### ISSUE THREAD

**Issue by shlomo100** [webdriverio/webdriverio#11056] opened 2023-08-30 07:42 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v16.13.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
from auto-generated example
```

### What happened?

Navigate to https://webdriver.io/
Run the following test cases:
scroll into view - getStarted with href selector - works fine
scroll into view - getStarted with class selector - doesn't work
The element targeted with the class selector in the second test case does not scroll into view and remains hidden, causing the test to fail.
An error occurs when attempting to use scrollIntoView: "ERROR webdriver: Request failed with status 500 due to move target out of bounds: move target out of bounds".

### What is your expected behavior?

In the second test case, using the class selector for getStarted, the element should be scrolled into view and displayed in the viewport as expected.

### How to reproduce the bug.

```ts
it("scroll into view - getStarted with href selector - works fine", async ()=> {
    await browser.url('https://webdriver.io/');
    const whoIsUsingLogos = $('.logos_YIMf');
    const getStarted = $('[href="/docs/gettingstarted"]');
    await whoIsUsingLogos.scrollIntoView();
    await expect(await whoIsUsingLogos).toBeDisplayedInViewport();
    await getStarted.scrollIntoView();
    await expect(await getStarted).toBeDisplayedInViewport();
});

it("scroll into view - getStarted with class selector - doesn't work", async ()=> {
    await browser.url('https://webdriver.io/');
    const whoIsUsingLogos = $('.logos_YIMf');
    const getStarted = $('.buttons_pzbO a');
    await whoIsUsingLogos.scrollIntoView();
    await expect(await whoIsUsingLogos).toBeDisplayedInViewport();
    await getStarted.scrollIntoView(); // Issue occurs here
    await expect(await getStarted).toBeDisplayedInViewport();
});

```

### Relevant log output

```typescript
The issue seems to be specific to using the class selector for scrolling into view.
The first test case using the href selector works correctly, suggesting that the scrollIntoView method is functional.
The added error message indicates that the move target is out of bounds.
Consider checking the compatibility of the scrollIntoView method with class selectors.
Investigate the out-of-bounds error and its relation to the element's position on the page.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2023-08-30 15:31
Thanks for reporting!

We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by erwinheitzman** [comment] 2023-09-02 22:37
I cannot reproduce this, could you Christian?

**Comment by erwinheitzman** [comment] 2023-09-02 23:06
Christian, how do you feel about replacing the command with the native scrollIntoView like so in v9:
``` 
// scollIntoView command file
await this.waitForExist();
await browser.execute((elem) => elem.scrollIntoView(), this);
```

**Comment by christian-bromann** [comment] 2023-09-05 06:25
@erwinheitzman I found a fix for this issue. Using the Actions API for scrolling is intentional because it comes closer to reality than triggering the JS API. Imagine a use case which makes an app listens to scroll events. These events are not emitted when using the JS APIs. Users always have the option to fall back to that if they desire using your example.

**Closed** 2023-09-05 07:00 UTC
Labels: Bug 🐛
