### ISSUE TITLE
expect-webdriverio  with Multiremote is returning Unexpected return from a matcher function

### ISSUE THREAD

**Issue by fege** [webdriverio/webdriverio#5652] opened 2020-07-22 12:44 UTC
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1.17
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v12.16.1
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name and version:** [e.g. Chrome 68]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]
    "expect": "26.1.0",
    "expect-webdriverio": "^1.2.0",

**Config of WebdriverIO**
```
var wdioConfig = {
  config: {
    maxInstances: 1,
    capabilities: {
      webClient: {
        port: seleniumPort,
        path: '/wd/hub',
        maxInstances: 1,
        capabilities: {
          "goog:chromeOptions": {
            args: [
              "--ignore-certificate-errors",
              "--no-cache",
              "--no-sandbox",
              "--allow-insecure-localhost",
              "--allow-sxg-certs-without-extension",
              "--disable-web-security",
              "--disable-popup-blocking",
              "--disable-default-apps",
              "--window-size=1920,1080"
            ],
            binary: (execSync("uname -s").includes("Linux")) ? "/usr/bin/google-chrome" : "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
          },
          browserName: "chrome"
        }
      },
      androidClient: {
        maxInstances: 1,
        port: appiumPort,
        platformName: "android",
        browserName: "android",
        capabilities: {
          "appium:automationName": "Espresso",
          "appium:nativeWebScreenshot": true,
          "appium:forceEspressoRebuild": true,
          "appium:unicodeKeyboard": true,
          "appium:resetKeyboard": true,
          "appium:appActivity": process.env.ANDROID_APP_ACTIVITY ? process.env.ANDROID_APP_ACTIVITY : "com.here.hnod.app.activities.MainActivity",
          "appium:appPackage": process.env.ANDROID_APP_PACKAGE,
          "appium:autoGrantPermissions": true,
          "appium:clearDeviceLogsOnStart": true,
          "appium:newCommandTimeout": 300000,
          "appium:deviceName": process.env.ANDROID_DEVICE,
          "appium:app": path.resolve(process.env.ANDROID_APP_PATH)
        }
      }
    },

    beforeSession: function (config, capabilities, specs) {
      require('expect-webdriverio')
    },

```
**Describe the bug**
using expect-webdriverio with multiremote 

```expect(webClient.$(MainPage.welcomeMessage)).toHaveText(messageFromVariable);```
is returning an error 
```
 Unexpected return from a matcher function.
Matcher functions should return an object in the following format:
  {message?: string | function, pass: boolean}
'[{"message": [Function message], "pass": true}, {"message": [Function message], "pass": true}]' was returned
```

while the same works fine with single remote
```expect(loginPage.usernameInput).toHaveValue("")```

**To Reproduce**

[Include code or an example repository that can easily be set up]

**Expected behavior**
expect-webdriverio works on multiremote 

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment] 2020-07-22 12:45
Duplicate of https://github.com/webdriverio/expect-webdriverio/issues/106

**Closed by christian-bromann** 2020-07-22 12:45 UTC
