### ISSUE TITLE
[🐛 Bug]: cucumber options tagExpression cannot work on multiple tags

### ISSUE THREAD

**Issue by LayMui** [webdriverio/webdriverio#8331] opened 2022-05-12 09:45 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.14

### Node.js Version

16.14.2

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
// The defaults you need to have in your config
    browserName: '',
    platformName: 'iOS',
    maxInstances: 1,
    // For W3C the appium capabilities need to have an extension prefix
    // This is `appium:` for all Appium Capabilities which can be found here
    // http://appium.io/docs/en/writing-running-appium/caps/
    'appium:deviceName': 'iPhone 13',
    'appium:platformVersion': '15.4',
    'appium:orientation': 'PORTRAIT',
    'appium:automationName': 'XCUITest',
    // The path to the app
    'appium:app': join(
      process.cwd(),
      './tests/apps/nativeIntegration.app',
    ),
    // Read the reset strategies very well, they differ per platform, see
    // http://appium.io/docs/en/writing-running-appium/other/reset-strategies/
    'appium:noReset': false,
    'appium:newCommandTimeout': 240,
    // 'appium:unicodeKeyboard': true,
    // 'appium:resetKeyboard':  true
  },
}
```

### What happened?

the wdio.conf.ts
cucumberOpts: {
    // <string[]> (file/dir) require files before executing features
    require: ['./tests/src/**/*.ts'],
    // <boolean> show full backtrace for errors
    backtrace: false,
    // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
    requireModule: [],
    // <boolean> invoke formatters without executing steps
    dryRun: false,
    // <boolean> abort the run on first failure
    failFast: false,
    // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
    format: ['pretty'],
    // <boolean> hide step definition snippets for pending steps
    snippets: true,
    // <boolean> hide source uris
    source: true,
    // <string[]> (name) specify the profile to use
    profile: [],
    // <boolean> fail if there are any undefined or pending steps
    strict: false,
    // <string> (expression) only execute the features or scenarios with tags matching the expression
    tagExpression: '@embedded and @universal',
    // <number> timeout for step definitions
    timeout: 1000000,
    // <boolean> Enable this config to treat undefined definitions as warnings.
    ignoreUndefinedDefinitions: false,
  },

when I run the test
the console.log show, nothing is run

### What is your expected behavior?

expect test scenario to be run

### How to reproduce the bug.

NA

### Relevant log output

```typescript
failsafe] Script 'clean' exited with code 0
[update:app]
[update:app] > nativeIntegration@0.0.1 update:app
[update:app] > sh scripts/ios.sh
[update:app]
[failsafe] Script 'update:app' exited with code 0
[test:execute:ios]
[test:execute:ios] > nativeIntegration@0.0.1 test:execute:ios
[test:execute:ios] > wdio config/wdio.ios.app.conf.ts
[test:execute:ios]
[test:execute:ios]
[test:execute:ios] Execution of 2 workers started at 2022-05-12T09:38:35.755Z
[test:execute:ios]
[test:execute:ios] 2022-05-12T09:38:35.851Z INFO @wdio/cli:launcher: Run onPrepare hook
[test:execute:ios] 2022-05-12T09:38:44.772Z INFO @wdio/cli:launcher: Run onWorkerStart hook
[test:execute:ios] 2022-05-12T09:38:44.774Z INFO @wdio/local-runner: Start worker 0-0 with arg: config/wdio.ios.app.conf.ts
[test:execute:ios] [0-0] 2022-05-12T09:38:48.342Z INFO @wdio/local-runner: Run worker command: run
[test:execute:ios] [0-0] 2022-05-12T09:38:50.676Z INFO wdio-multiple-cucumber-html-reporter: The 'reportFilePerRetry' was not set, it has been set to the default 'true'
[test:execute:ios] 2022-05-12T09:38:54.161Z INFO @wdio/cli: [0-0] SKIPPED in iOS - /tests/features/embeddedLogin.feature
[test:execute:ios] 2022-05-12T09:38:54.162Z INFO @wdio/cli:launcher: Run onWorkerStart hook
[test:execute:ios] 2022-05-12T09:38:54.164Z INFO @wdio/local-runner: Start worker 0-1 with arg: config/wdio.ios.app.conf.ts
[test:execute:ios] [0-1] 2022-05-12T09:38:55.087Z INFO @wdio/local-runner: Run worker command: run
[test:execute:ios] [0-1] 2022-05-12T09:38:55.823Z INFO wdio-multiple-cucumber-html-reporter: The 'reportFilePerRetry' was not set, it has been set to the default 'true'
[test:execute:ios] 2022-05-12T09:38:56.466Z INFO @wdio/cli: [0-1] SKIPPED in iOS - /tests/features/universalLogin.feature
[test:execute:ios] 2022-05-12T09:38:56.467Z INFO @wdio/cli:launcher: Run onComplete hook
[test:execute:ios]
[test:execute:ios] Spec Files:   0 passed, 2 skipped, 2 total (100% completed) in 00:00:20
[test:execute:ios]
[test:execute:ios] 2022-05-12T09:38:56.468Z INFO @wdio/local-runner: Shutting down spawned worker
[test:execute:ios] 2022-05-12T09:38:56.720Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
[test:execute:ios] 2022-05-12T09:38:56.721Z INFO @wdio/local-runner: shutting down
[failsafe] Script 'test:execute:ios' exited with code 0
✨  Done in 35.34s.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2022-05-12 15:01
As mentioned by @osmolyar on the Gitter Channel this is suppose to work, so not sure why it is not for you. Can you provide a reproducible example please?

**Comment by christian-bromann** [comment] 2022-05-13 06:54
Closing as we have figured the support channel that this is not a bug.

**Closed by christian-bromann** 2022-05-13 06:54 UTC
Labels: Bug 🐛, Reproducible Example Missing

**Comment by Mr1skylab** [comment] 2023-08-02 17:52
is this working as expected? I am on v8 and facing this issue.
single tag works fine but multiple tags wont. It gets the correct count of scenarios to run but ultimately skips all
