### ISSUE TITLE
WDIO hangs on tests which have multiple browser windows in Chrome's headless mode

### ISSUE THREAD

**Issue by goyney** [webdriverio/webdriverio#2230] opened 2017-08-07 14:16 UTC
## The problem

Webdriver.io's test runnder, wdio, when used with chromedriver does not handle new browser windows in chrome's headless mode properly, causing tests to hang and fail.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 8.2.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: both
* Additional wdio packages used (if applicable):
** wdio-chromedriver-service: ~0.1.0
** wdio-mocha-framework: ~0.5.10
** wdio-spec-reporter: ~0.1.0

## Details

We have a simple test which tests our Facebook social login. Facebook popups open a new browser window for their login which returns to the main browser tab. The test we have runs perfectly fine when run normally. However, when running with the `--headless` argument on Chrome, the test stops responding as soon as it is to take action in the next window. Look at the reproduction code below inline for comments.

## Link to Selenium/WebdriverIO logs

NA

## Code To Reproduce Issue [ Good To Have ]

```
  browser.url(url);
  const mainTab = browser.getCurrentTabId();
  console.log('Main Tab', mainTab); // Logs properly
  pages.login.facebookButton.waitForVisible();
  takeScreenshot('Main Login Page'); // Screenshot is taken
  pages.login.facebookButton.click();
  browser.waitUntil(() => {
    console.log('Tabs = ', browser.getTabIds()); // Logs an array with two ids
    return browser.getTabIds().length > 1;
  }, 5000, 'expected Facebook login window', 250);
  const facebookTab = browser.getTabIds().filter(id => id !== mainTab)[0];
  console.log('Facebook Tab', facebookTab); // Logs properly
  takeScreenshot('Before Facebook Login Page'); // Screenshot is taken
  browser.switchTab(facebookTab);
  takeScreenshot('Facebook Login Page'); // Screenshot is never taken
  // At this point, the test hangs and times out on headless only
```

**Comment by christian-bromann** [comment] 2017-08-07 14:20
This might be an issue with Chromedriver not being able to handle this in headless mode. I could tell if you could provide Chromedriver logs. However this can't be fixed in WebdriverIO. You should [report a bug](https://sites.google.com/a/chromium.org/chromedriver/help) in the Chromedriver project.

**Closed by christian-bromann** 2017-08-07 14:20 UTC

**Comment by goyney** [comment] 2017-08-07 14:23
@christian-bromann Where can I find the chromedriver logs? I can share them with you to be definitive.

**Comment by kgiannelos** [comment] 2021-07-05 09:20
We just stepped into an issue that looks identical with this one, using webdriverio v7.7.3. Our environment configuration is:
WebdriverIO version: 7.7.3
Node.js version: 14.17.0

We also use the following set of packages:
`
"@wdio/cli": "7.7.3",
"@wdio/cucumber-framework": "^7.7.3",
"@wdio/dot-reporter": "^7.7.3",
"@wdio/junit-reporter": "^7.7.3",
"@wdio/local-runner": "^7.7.3",
"@wdio/spec-reporter": "^7.7.3",
"chromedriver": "91.0.1",
"wdio-chromedriver-service": "^7.1.0",
"wdio-cucumberjs-json-reporter": "4.0.0",
"webdriverio": "7.7.3",
`
The behavior is the same. The test runs fine until we run it in headless mode, where it hangs after opening a page in a new tab and when using browser.getUrl or browser.execute on that new tab. When switching tabs and moving back to the original one, both of those 2 methods work fine. I am skeptical this is a chromedriver issue @christian-bromann , since the same tests run fine  when launched through chimpy and webdriverio v4. We started having issues, when we were forced to upgrade to node 14, so we had to stop using chimpy due to fibers compatibility issues and decided to upgrade to the latest webdriverio version also. I have attached both webdriverio and chromedriver logs if that helps.

[wdio-chromedriver.log.zip](https://github.com/webdriverio/webdriverio/files/6763146/wdio-chromedriver.log.zip)
[wdio-0-0.log.zip](https://github.com/webdriverio/webdriverio/files/6763150/wdio-0-0.log.zip)

**Comment by BorisOsipov** [comment] 2021-07-05 09:27
@kgiannelos as you can see in wdio logs, `getUrl` command ran and send request to chromedriver, but it has not responded at all.

I think it is chromedriver issue, though.

```
2021-07-05T09:01:54.031Z INFO webdriver: [GET] http://localhost:9515/session/06626bdce51ec4bc8cdd8ea84d60e370/window
2021-07-05T09:01:54.032Z INFO webdriver: RESULT CDwindow-DA12EB686470A4EDDB8D7C3D6A3FA15F
2021-07-05T09:01:56.035Z INFO webdriver: COMMAND getUrl()
2021-07-05T09:01:56.035Z INFO webdriver: [GET] http://localhost:9515/session/06626bdce51ec4bc8cdd8ea84d60e370/url
2021-07-05T09:02:06.044Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
```

**Comment by kgiannelos** [comment] 2021-07-05 09:31
Yes, I understand. Just saying it is odd that we have the same test cases running fine on the same chromedriver version and a previous version of chimpy/webdriverio.

**Comment by BorisOsipov** [comment] 2021-07-05 09:36
Yes it is strange. Only thing I guess, maybe wdio 4 works on old JSON-wire protocol and that's why it works.

**Comment by kgiannelos** [comment] 2021-07-06 11:39
@BorisOsipov , you are right. This seems like to be a chromedriver bug. I was able to actually get the same behavior by using chromedriver REST api, /session/{session id}/url by submitting a GET request. After 5 minutes, the response that is being send back is the following:
{"value":{"error":"timeout","message":"timeout: Timed out receiving message from renderer: 300.000\n  (Session info: headless chrome=91.0.4472.114)","stacktrace":"#0 0x55be4724f949 \u003Cunknown>\n"}}

For anyone else facing the same issue, I logged a ticket to the chromedriver folks here:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=3855

**Comment by BorisOsipov** [comment] 2021-07-06 11:43
@kgiannelos greate job! I get the sense that I ran into the similar issue and workaround was `browser.pause(1000)` after switching to new window. I am not sure, but maybe it will help.

**Comment by kgiannelos** [comment] 2021-07-07 06:13
Thanks for the tip @BorisOsipov. I've tried your suggestion and all sort of hacks to get this working, even closing all other tabs and leaving a single one open. It looks like though that chromedriver times out on any other tab, other than the original one opened with the new session. There seems to be no obvious workaround for me at this point other than altering the test steps to avoid the APIs that time out. Of course, this comes with a cost as I can't verify the software exactly the way I want to.

**Comment by christian-bromann** [comment] 2021-07-12 08:52
@kgiannelos if you have a reproducible example it might be worth filing a bug in the Chromedriver project.
