### ISSUE TITLE
Tests hang in Bamboo 

### ISSUE THREAD

**Issue by ConnerAiken** [webdriverio/webdriverio#2637] opened 2018-03-09 00:14 UTC
## The problem

When ran in a dockerized bamboo build agent (CentOS 7.4), Webdriver.io hangs and does not reach the onPrepare hook. 

## Environment

* WebdriverIO version: **4.12.0**
* Node.js version: **v8.9.4**
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): **wdio**
* if wdio testrunner, running synchronous or asynchronous tests: **synchronous**

Additional wdio packages used (if applicable):
- visual-regression
- browserstack-local
- jasmine framework
- junit reporter
- babel

## Details

No errors are fired, I do not see anything in the logs. I am just now integrating UI test into our CI so this may be related to browserstack/plugins. 

Important note: This build agent is dockerized with CentOS 7.4, if I bash into the running container, the wdio commands work fine. It is only when bamboo kicks of the build agent. However, if I step back webdriverio it works. For ex: 4.8.0

## Link to Selenium/WebdriverIO logs

Unless there are additional logs that I am missing, this is the only output that I see and I have set the logging to verbose.

```
build	08-Mar-2018 16:06:32	> wdio tests/ui/wdio.conf.js
build	08-Mar-2018 16:06:32	
```

## Code To Reproduce Issue [ Good To Have ]

Wdio config file
```
var VisualRegressionCompare = require('wdio-visual-regression-service/compare');
var path = require('path');  
var jsonfile = require('jsonfile');
var _ = require('lodash'); 
var browserstack = require('browserstack-local');

var suiteResults = {all: [], failed: [], passed: []};  
var cacheFile = path.join(process.cwd(), 'tests/output/uiCache.json');
  
exports.config = {
    user: process.env.bstack_user,
    key: process.env.bstack_key,
    //
    // ==================
    // Specify Test Files
    // ==================
    // Define which test specs should run. The pattern is relative to the directory
    // from which `wdio` was called. Notice that, if you are calling `wdio` from an
    // NPM script (see https://docs.npmjs.com/cli/run-script) then the current working
    // directory is where your package.json resides, so `wdio` will be called from there.
    //
    specs: [ 
       path.join(process.cwd(), 'tests/ui/suites/**/*.js')
    ],
    // Patterns to exclude.
    exclude: [
        path.join(process.cwd(), 'tests/ui/suites/integration/*.js'),
        path.join(process.cwd(), 'tests/ui/suites/integration/**/*.js')
    ],
    //
    // ============
    // Capabilities
    // ============
    // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
    // time. Depending on the number of capabilities, WebdriverIO launches several test
    // sessions. Within your capabilities you can overwrite the spec and exclude options in
    // order to group specific specs to a specific capability.
    //
    // First, you can define how many instances should be started at the same time. Let's
    // say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
    // set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
    // files and you set maxInstances to 10, all spec files will get tested at the same time
    // and 30 processes will get spawned. The property handles how many capabilities
    // from the same test should run tests.
    //
    maxInstances: 1,
    //
    // If you have trouble getting all important capabilities together, check out the
    // Sauce Labs platform configurator - a great tool to configure your capabilities:
    // https://docs.saucelabs.com/reference/platforms-configurator
    //
    capabilities: [
        { 
            maxInstances: 1, 
            'browserstack.local': true,
            'browserstack.debug': true,
            'browserstack.networkLogs': true, 
            'browserstack.timezone': 'PST',
            browserVersion: '64.0',
            browserName: 'chrome',
            chromeOptions: {
                args: ['--start-maximized']
            }
        },
        { 
            maxInstances: 1, 
            'browserstack.local': true,
            'browserstack.debug': true,
            'browserstack.networkLogs': true, 
            'browserstack.timezone': 'PST',
            browserName: 'firefox',
            browserVersion: '59.0 beta',
        },
        { 
            maxInstances: 1, 
            'browserstack.local': true,
            'browserstack.debug': true,
            'browserstack.networkLogs': true, 
            'browserstack.timezone': 'PST',
            browserName: 'IE',
            browserVersion: '11.0',
        },
        { 
            maxInstances: 1, 
            'browserstack.local': true,
            'browserstack.debug': true,
            'browserstack.networkLogs': true, 
            'browserstack.timezone': 'PST',
            browserName: 'edge',
            browserVersion: '16.0',
        }
    ], 
    //
    // ===================
    // Test Configurations
    // ===================
    // Define all options that are relevant for the WebdriverIO instance here
    //
    // By default WebdriverIO commands are executed in a synchronous way using
    // the wdio-sync package. If you still want to run your tests in an async way
    // e.g. using promises you can set the sync option to false.
    sync: true,
    //
    // Level of logging verbosity: silent | verbose | command | data | result | error
    logLevel: 'verbose',
    //
    // Enables colors for log output.
    coloredLogs: true,
    //
    // Warns when a deprecated command is used
    deprecationWarnings: false,
    //
    // If you only want to run your tests until a specific amount of tests have failed use
    // bail (default is 0 - don't bail, run all tests).
    bail: 1,
    //
    // Saves a screenshot to a given path if a command fails.
    screenshotPath: path.join(process.cwd(), 'tests/output/screenshots/'),
    //
    // Set a base URL in order to shorten url command calls. If your `url` parameter starts
    // with `/`, the base url gets prepended, not including the path portion of your baseUrl.
    // If your `url` parameter starts without a scheme or `/` (like `some/path`), the base url
    // gets prepended directly.
    baseUrl: process.env.test_baseUrl || 'http://localhost',
    //
    // Default timeout for all waitFor* commands.
    waitforTimeout: 30000,
    //
    // Default timeout in milliseconds for request
    // if Selenium Grid doesn't send response
    connectionRetryTimeout: 90000,
    //
    // Default request retries count
    connectionRetryCount: 3,
    //
    // Initialize the browser instance with a WebdriverIO plugin. The object should have the
    // plugin name as key and the desired plugin options as properties. Make sure you have
    // the plugin installed before running any tests. The following plugins are currently
    // available:
    // WebdriverCSS: https://github.com/webdriverio/webdrivercss
    // WebdriverRTC: https://github.com/webdriverio/webdriverrtc
    // Browserevent: https://github.com/webdriverio/browserevent
    // plugins: {
    //     webdrivercss: {
    //         screenshotRoot: 'my-shots',
    //         failedComparisonsRoot: 'diffs',
    //         misMatchTolerance: 0.05,
    //         screenWidth: [320,480,640,1024]
    //     },
    //     webdriverrtc: {},
    //     browserevent: {}
    // },
    //
    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.
    services: ['visual-regression'],
    visualRegression: {
        compare: new VisualRegressionCompare.LocalCompare({
            referenceName: utilities.getScreenshotName(path.join(process.cwd(), 'tests/output/screenshots/reference')),
            screenshotName: utilities.getScreenshotName(path.join(process.cwd(), 'tests/output/screenshots/screen')),
            diffName: utilities.getScreenshotName(path.join(process.cwd(), 'tests/output/screenshots/diff')),
            misMatchTolerance: 0.01,
        }),
        viewportChangePause: 500,
        viewports: [{ width: 1920, height: 1080 }]
    },
    // Framework you want to run your specs with.
    // The following are supported: Mocha, Jasmine, and Cucumber
    // see also: http://webdriver.io/guide/testrunner/frameworks.html
    //
    // Make sure you have the wdio adapter package for the specific framework installed
    // before running any tests.
    framework: 'jasmine',
    //
    // Test reporter for stdout.
    // The only one supported by default is 'dot'
    // see also: http://webdriver.io/guide/reporters/dot.html
    reporters: ['dot', 'junit'],
    reporterOptions: {
        junit: {
            outputDir: path.join(process.cwd(), 'tests/output/'),
            outputFileFormat: function(opts) { // optional
                return `uiresults-${opts.cid}.${opts.capabilities}.xml`
            }
        }
    },
    
    //
    // Options to be passed to Jasmine.
    jasmineNodeOpts: {
        helpers: [
            path.join(process.cwd(), 'node_modules/jasmine-expect/index.js'), 
            path.join(process.cwd(), 'node_modules/jasmine-es6/lib/install.js')
        ],
        // Jasmine default timeout
        defaultTimeoutInterval: 30000,
        //
        // The Jasmine framework allows interception of each assertion in order to log the state of the application
        // or website depending on the result. For example, it is pretty handy to take a screenshot every time
        // an assertion fails.
        expectationResultHandler: function(passed, assertion) { 
        }
    },
    
    //
    // =====
    // Hooks
    // =====
    // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
    // it and to build services around it. You can either apply a single function or an array of
    // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
    // resolved to continue.
    /**
     * Gets executed once before all workers get launched.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     */
     onPrepare: function (config, capabilities) {   
        // Start up browserstack tunnel
        return new Promise(function(resolve, reject){
          exports.bs_local = new browserstack.Local();

          var bstack_config = { 
                'key': exports.config.key ,
                'verbose': true,
                'forceLocal': true
          };

          exports.bs_local.start(bstack_config, function(error) {
            if (error) return reject(error);
            console.log('Connected to browserstack. Now testing...');
    
            resolve();
          });
        });
     },
    /**
     * Gets executed just before initialising the webdriver session and test framework. It allows you
     * to manipulate configurations depending on the capability or spec.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     */
    // beforeSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed before test execution begins. At this point you can access to all global
     * variables like `browser`. It is the perfect place to define custom commands.
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     */
    before: function (capabilities, specs) {     
        process.env.uiTesting = true;
        return;
    },
    /**
     * Runs before a WebdriverIO command gets executed.
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     */
    // beforeCommand: function (commandName, args) {
    // },
    
    /**
     * Hook that gets executed before the suite starts
     * @param {Object} suite suite details
     */
    //beforeSuite: function (suite) {   
    //},
    /**
     * Function to be executed before a test (in Mocha/Jasmine) or a step (in Cucumber) starts.
     * @param {Object} test test details
     */
    // beforeTest: function (test) {
    // },
    /**
     * Hook that gets executed _before_ a hook within the suite starts (e.g. runs before calling
     * beforeEach in Mocha)
     */
    // beforeHook: function () {
    // },
    /**
     * Hook that gets executed _after_ a hook within the suite starts (e.g. runs after calling
     * afterEach in Mocha)
     */
    // afterHook: function () {
    // },
    /**
     * Function to be executed after a test (in Mocha/Jasmine) or a step (in Cucumber) starts.
     * @param {Object} test test details
     */
    //afterTest: function (test) {   
    //},
    /**
     * Hook that gets executed after the suite has ended
     * @param {Object} suite suite details
     */
    //afterSuite: function (suite) { 
    //},
    
    /**
     * Runs after a WebdriverIO command gets executed
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     * @param {Number} result 0 - command success, 1 - command error
     * @param {Object} error error object if any
     */
    // afterCommand: function (commandName, args, result, error) {
    // },
    /**
     * Gets executed after all tests are done. You still have access to all global variables from
     * the test.
     * @param {Number} result 0 - test pass, 1 - test fail
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
     //after: function (result, capabilities, specs) {  
     //},
    /**
     * Gets executed right after terminating the webdriver session.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    //afterSession: function (config, capabilities, specs) {   
    //},
    /**
     * Gets executed after all workers got shut down and the process is about to exit.
     * @param {Object} exitCode 0 - success, 1 - fail
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     */
    onComplete: function(exitCode, config, capabilities) {    
        exports.bs_local.stop(function() {}); 
    }
}


// Tell webdriver to accept ES6 syntax
require("babel-core/register")({
    presets: ['es2015']
});
```

**Comment by christian-bromann** [comment] 2018-03-09 10:31
Duplicate of #2624

**Closed by christian-bromann** 2018-03-09 10:31 UTC
