### ISSUE TITLE
@wdio/local-runner can not kill the WebDriver sessions after completing test

### ISSUE THREAD

**Issue by flyHe** [webdriverio/webdriverio#4328] opened 2019-08-07 07:44 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** [^5.11.12]
 - **Mode:** [chromedriverr]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [10]
 - **NPM version:** [6]
 - **Browser name and version:** [Chrome 76]
 - **Platform name and version:** [mac OS 10.14.6]
 - **Additional wdio packages used (if applicable):** [@wdio/local-runner, @wdio/cucumber-framework, wdio-chromedriver-service]

**Config of WebdriverIO**
https://github.com/flyHe/UI_H5_Test/blob/master/tests/wdio.conf.js

**Describe the bug**
@wdio/local-runner can not kill the WebDriver sessions after completing test, the gulp is pending after completing all the tasks

**To Reproduce**
repo: https://github.com/flyHe/UI_H5_Test
`npm i`
`npm run test:search:local`

**Expected behavior**
no need to kill the task by [process.exit(0);](https://github.com/flyHe/UI_H5_Test/blob/master/gulp-tasks/test.js#L85)

**Log**
<img width="709" alt="Screen Shot 2019-08-05 at 5 35 59 PM" src="https://user-images.githubusercontent.com/10543919/62454895-c68c0f80-b7a7-11e9-8741-6fe07eb5dd69.png">
kill manually
<img width="717" alt="Screen Shot 2019-08-05 at 5 36 08 PM" src="https://user-images.githubusercontent.com/10543919/62454897-c68c0f80-b7a7-11e9-9edd-3de5c4cb99c5.png">

**Comment by mgrybyk** [comment] 2019-08-07 07:49
There are no issues when running without gulp, how is webdriverio related?

**Comment by beshanoe** [comment] 2019-08-07 09:13
@mgrybyk there is an issue when you use webdriver through the node API. WdioCLI has to terminate the process manually because of the same issue here: https://github.com/webdriverio/webdriverio/blob/91bc19ae25477184efbd89e72b8dd64417fbd433/packages/wdio-cli/src/run.js#L70

Apparently, that problem was spotted while writing gulp-webdriver plugin and the solution was to pause the stdin pipe: https://github.com/webdriverio/gulp-webdriver/blob/815cfa93d94b6bd883f198ab5f993e9689645c6c/src/index.js#L13

This probably happens because local-runner pipes the parent's process stdin to worker's one: https://github.com/webdriverio/webdriverio/blob/91bc19ae25477184efbd89e72b8dd64417fbd433/packages/wdio-local-runner/src/worker.js#L83

We also encountered that issue and did that stdin.pause() hack, but it turned out that it became impossible to test in in jest, since it runs tests in workers and apparently relies on stdin pipe.

**Comment by mgrybyk** [comment] 2019-08-07 09:19
Yeah, runner runs each spec file in a child process, thats why we pipe stdin.

So, what suggestions do you have? 
Framework runs normally both with runner and programmatically but there is a problem with gulp which is not supported

**Comment by beshanoe** [comment] 2019-08-07 09:25
What do you mean by normally? If the process needs to be exited forcefully it doesn't seem normal to me. I feel like local-runner can somehow release that pipe, but when we tried `process.stdin.unpipe(childProcess.stdin) ` method inside worker's code, it would still hang. Only `process.stdin.unref()` method worked but I think this way we loose stdin completely. I'm just not that deep in process' pipes to give a fully working solution

**Comment by mgrybyk** [comment] 2019-08-07 09:36
By normally I mean that I don't need to do anything to run webdriverio without gulp

**Comment by danielamaia** [comment] 2019-08-07 10:59
Hey @mgrybyk, I made a minimal reproducing example 🙂 
Can you run it and confirm please that when we run wdio programatically it prevents process from exiting? 
Clone this gist repo: https://gist.github.com/danielamaia/b2085b41189adbff1032bda5f169ef79

**Comment by mgrybyk** [comment] 2019-08-07 11:12
I can see what are you taking about even without that. I'll think about it. Thank you

**Comment by beshanoe** [comment] 2019-08-07 16:36
Related issues:
https://github.com/nodejs/node/issues/2276
https://github.com/nodejs/node/issues/24327

Maybe, the problem is that child process doesn't actually consume stdin stream and that's why keeps hanging 🧐

**Comment by mgrybyk** [comment] 2019-08-07 16:47
I'll take a look, thank you!

**Comment by mgrybyk** [comment] 2019-08-07 18:30
@beshanoe fixed it, going to create PR soon

**Comment by mgrybyk** [comment] 2019-08-07 19:21
Let's proceed conversation in PR. 

Have to add some tests and pass review before it can be merged and then released.

Feel free to add comments.

Thank you for all the details and help!

**Closed by mgrybyk** 2019-08-07 19:21 UTC

**Comment by mgrybyk** [comment] 2019-08-20 09:42
@flyHe FYI https://github.com/webdriverio/webdriverio/issues/4368#issuecomment-522938239
