### ISSUE TITLE
@wdio/runner: FetchError: Failed to fetch browser webSocket URL from http://localhost:51804/json/version: request to http://localhost:51804/json/version failed, reason: connect ECONNREFUSED ::1:51804🐛 Bug]: <title>

### ISSUE THREAD

**Issue by sayrah01** [webdriverio/webdriverio#8279] opened 2022-04-26 16:37 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.15

### Node.js Version

v17.9.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [
        {
            maxInstances: 1,
            browserName: "Chrome",
            "goog:chromeOptions": {
                args: ["--headless"],
            },
        },
    ],
```

### What happened?

after starting to work react-native project then I am getting this error while running webdriverio project

running API with cucumber 

### What is your expected behavior?

No error should occur.

### How to reproduce the bug.

This is happening randomly.

### Relevant log output

```typescript
 wdio@1.0.0 test-api
> ./node_modules/.bin/wdio run ./config/local/wdio.api.config.js --cucumberOpts.tagExpression "@CartService"


Execution of 6 workers started at 2022-04-26T16:27:52.014Z

2022-04-26T16:27:52.025Z INFO @wdio/cli:launcher: Run onPrepare hook
2022-04-26T16:27:52.027Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-04-26T16:27:52.028Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./config/local/wdio.api.config.js,--cucumberOpts.tagExpression,@CartService
[0-0] 2022-04-26T16:27:52.424Z INFO @wdio/local-runner: Run worker command: run
2022-04-26T16:27:54.086Z INFO @wdio/cli: [0-0] SKIPPED in Chrome - /test/api/features/login.feature
2022-04-26T16:27:54.086Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-04-26T16:27:54.087Z INFO @wdio/local-runner: Start worker 0-1 with arg: run,./config/local/wdio.api.config.js,--cucumberOpts.tagExpression,@CartService
[0-1] 2022-04-26T16:27:54.298Z INFO @wdio/local-runner: Run worker command: run
[0-1] RUNNING in Chrome - /test/api/features/cart.feature
[0-1] 2022-04-26T16:27:55.765Z INFO devtools:puppeteer: Initiate new session using the DevTools protocol
[0-1] 2022-04-26T16:27:55.766Z INFO devtools: Launch Google Chrome with flags: --enable-automation --disable-popup-blocking --disable-extensions --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --no-default-browser-check --disable-hang-monitor --disable-prompt-on-repost --disable-client-side-phishing-detection --password-store=basic --use-mock-keychain --disable-component-extensions-with-background-pages --disable-breakpad --disable-dev-shm-usage --disable-ipc-flooding-protection --disable-renderer-backgrounding --force-fieldtrials=*BackgroundTracing/default/ --enable-features=NetworkService,NetworkServiceInProcess --disable-features=site-per-process,TranslateUI,BlinkGenPropertyTrees --window-position=0,0 --window-size=1200,900 --headless
[0-1] 2022-04-26T16:27:56.799Z INFO devtools: Connect Puppeteer with browser on port 60144
[0-1] 2022-04-26T16:27:56.817Z ERROR @wdio/runner: FetchError: Failed to fetch browser webSocket URL from http://localhost:60144/json/version: request to http://localhost:60144/json/version failed, reason: connect ECONNREFUSED ::1:60144
[0-1]     at ClientRequest.<anonymous> (/Users/sayrah/Desktop/decathlonauto/WebDriverIo/dosa-autobot/node_modules/node-fetch/lib/index.js:1491:11)
[0-1]     at ClientRequest.emit (node:events:527:28)
[0-1]     at ClientRequest.emit (node:domain:475:12)
[0-1]     at Socket.socketErrorListener (node:_http_client:454:9)
[0-1]     at Socket.emit (node:events:527:28)
[0-1]     at Socket.emit (node:domain:475:12)
[0-1]     at emitErrorNT (node:internal/streams/destroy:164:8)
[0-1]     at emitErrorCloseNT (node:internal/streams/destroy:129:3)
[0-1]     at processTicksAndRejections (node:internal/process/task_queues:83:21)
[0-1] FAILED in Chrome - /test/api/features/cart.feature
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by stephanie-engel** [comment] 2022-04-27 18:34
Someone on my team is also seeing the same issue as detailed in this ticket:

**WebdriverIO Version**
7.16.15

**Node.js Version**
v17.7.1

**Mode**
WDIO Testrunner

**What happened?**
The repo that contains the automated tests was cloned 2 weeks ago, and this team member has been seeing this error message whenever attempting to run the tests.

**What is your expected behavior?**
The test should run without any errors.

**How to reproduce the bug.**
Run the test with the following command:
`ENV=staging npm test -- --spec zfront-spec.js` (which translates to 
`wdio run wdio.base.conf.js "--spec" "zfront-spec.js"` on our staging environment)

**Relevant log output**

```
> elev8-tests@0.1.0 test
> wdio run wdio.base.conf.js "--spec" "zfront-spec.js"

Execution of 1 workers started at 2022-04-27T16:58:23.133Z

[0-0] RUNNING in chrome - /test/specs/zfront/zfront-spec.js
[0-0] 2022-04-27T16:58:24.127Z ERROR @wdio/runner: FetchError: Failed to fetch browser webSocket URL from http://localhost:58489/json/version: request to http://localhost:58489/json/version failed, reason: connect ECONNREFUSED ::1:58489
[0-0]     at ClientRequest.<anonymous> (/Users/*****/projects/elev8/node_modules/node-fetch/lib/index.js:1491:11)
[0-0]     at ClientRequest.emit (node:events:527:28)
[0-0]     at ClientRequest.emit (node:domain:475:12)
[0-0]     at Socket.socketErrorListener (node:_http_client:442:9)
[0-0]     at Socket.emit (node:events:527:28)
[0-0]     at Socket.emit (node:domain:475:12)
[0-0]     at emitErrorNT (node:internal/streams/destroy:164:8)
[0-0]     at emitErrorCloseNT (node:internal/streams/destroy:129:3)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:83:21)
[0-0] FAILED in chrome - /test/specs/zfront/zfront-spec.js
Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:01
```

**Comment by stephanie-engel** [comment] 2022-04-27 19:05
**Update:**
- When I use node version 16.13.0 then I don't get the ECONNREFUSED error. The tests run and pass without any issues.
- When I upgrade to node version 17.7.1 (same as my coworker), then I'm able to reproduce this error.

**Tests Run and Pass with Node v 16.13.0**

```
$ node  -v
v16.13.0
                                                                                                                                                                                                              
$ ENV=staging npm test -- --spec zfront-spec.js


> elev8-tests@0.1.0 test
> wdio run wdio.base.conf.js "--spec" "zfront-spec.js"


Execution of 1 workers started at 2022-04-27T18:38:22.617Z

[0-0] RUNNING in chrome - /test/specs/zfront/zfront-spec.js
[0-0] PASSED in chrome - /test/specs/zfront/zfront-spec.js

 "spec" Reporter:
------------------------------------------------------------------
[Chrome 100.0.4896.127 darwin #0-0] Running: Chrome (v100.0.4896.127) on darwin
[Chrome 100.0.4896.127 darwin #0-0] Session ID: c49413e0-83b0-422a-8d05-659f132c6f2f
[Chrome 100.0.4896.127 darwin #0-0]
[Chrome 100.0.4896.127 darwin #0-0] » /test/specs/zfront/zfront-spec.js
[Chrome 100.0.4896.127 darwin #0-0] Zfront: Home Page Landing
[Chrome 100.0.4896.127 darwin #0-0]    ✓ should verify primary CTA cards on homepage
[Chrome 100.0.4896.127 darwin #0-0]
[Chrome 100.0.4896.127 darwin #0-0] 1 passing (1.7s)


Spec Files:      1 passed, 1 total (100% completed) in 00:00:04 
```


**Error with Node v 17.7.1**

```
$ node -v
v17.7.1
                                                                                                                                                                                                              
$ ENV=staging npm test -- --spec zfront-spec.js


> elev8-tests@0.1.0 test
> wdio run wdio.base.conf.js "--spec" "zfront-spec.js"


Execution of 1 workers started at 2022-04-27T18:37:40.895Z

[0-0] RUNNING in chrome - /test/specs/zfront/zfront-spec.js
[0-0] 2022-04-27T18:37:42.416Z ERROR @wdio/runner: FetchError: Failed to fetch browser webSocket URL from http://localhost:58069/json/version: request to http://localhost:58069/json/version failed, reason: connect ECONNREFUSED ::1:58069
[0-0]     at ClientRequest.<anonymous> (/Users/*****/code/elev8/node_modules/node-fetch/lib/index.js:1491:11)
[0-0]     at ClientRequest.emit (node:events:527:28)
[0-0]     at ClientRequest.emit (node:domain:475:12)
[0-0]     at Socket.socketErrorListener (node:_http_client:442:9)
[0-0]     at Socket.emit (node:events:527:28)
[0-0]     at Socket.emit (node:domain:475:12)
[0-0]     at emitErrorNT (node:internal/streams/destroy:164:8)
[0-0]     at emitErrorCloseNT (node:internal/streams/destroy:129:3)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:83:21)
[0-0] FAILED in chrome - /test/specs/zfront/zfront-spec.js

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:01 
```

**Comment by christian-bromann** [comment] 2022-05-04 17:15
Can someone create a reproducible example, like a little GitHub project using GitHub actions?

**Comment by mherger** [comment] 2022-05-18 10:00
Example code (mocha): 

```javascript
const { createServer } = require('http');
const { remote } = require('webdriverio');

const host = '127.0.0.1';
const port = 4000;
let browser;

const server = createServer((req, res) => {
  res.writeHead(200);
  res.end(`{
    foo: 'bar'
  }`);
});
server.listen(port);

describe(`Testing NodeJS version ${process.version}`, () => {
  before(async () => {

    try {
      browser = await remote({
        capabilities: {
          browserName: 'chrome',
          'goog:chromeOptions': {
            args: ['--headless', '--disable-gpu']
          }
        }
      });
    }
    catch(e) {
      console.error(e);
    }
  });

  after(async () => {
    await browser.deleteSession();
    server.close();
  });

  it('Run that test!', async () => {
    await browser.url(`http://${host}:${port}/`);
  });
});
```

Using NodeJS v14:

```
  Testing NodeJS version v14.17.1
2022-05-18T09:57:34.732Z INFO devtools:puppeteer: Initiate new session using the DevTools protocol
2022-05-18T09:57:34.734Z INFO devtools: Launch Google Chrome with flags: --enable-automation --disable-popup-blocking --disable-extensions --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --no-default-browser-check --disable-hang-monitor --disable-prompt-on-repost --disable-client-side-phishing-detection --password-store=basic --use-mock-keychain --disable-component-extensions-with-background-pages --disable-breakpad --disable-dev-shm-usage --disable-ipc-flooding-protection --disable-renderer-backgrounding --force-fieldtrials=*BackgroundTracing/default/ --enable-features=NetworkService,NetworkServiceInProcess --disable-features=site-per-process,TranslateUI,BlinkGenPropertyTrees --window-position=0,0 --window-size=1200,900 --headless --disable-gpu
2022-05-18T09:57:35.257Z INFO devtools: Connect Puppeteer with browser on port 63907
2022-05-18T09:57:35.337Z INFO devtools: COMMAND navigateTo("http://127.0.0.1:4000/")
2022-05-18T09:57:35.365Z INFO devtools: RESULT null
    ✔ Run that test!
2022-05-18T09:57:35.380Z INFO devtools: COMMAND deleteSession()
2022-05-18T09:57:35.382Z INFO devtools: RESULT null


  1 passing (665ms)
```

Using NodeJS v18:

```
  Testing NodeJS version v18.1.0
2022-05-18T10:00:18.226Z INFO devtools:puppeteer: Initiate new session using the DevTools protocol
2022-05-18T10:00:18.227Z INFO devtools: Launch Google Chrome with flags: --enable-automation --disable-popup-blocking --disable-extensions --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --no-default-browser-check --disable-hang-monitor --disable-prompt-on-repost --disable-client-side-phishing-detection --password-store=basic --use-mock-keychain --disable-component-extensions-with-background-pages --disable-breakpad --disable-dev-shm-usage --disable-ipc-flooding-protection --disable-renderer-backgrounding --force-fieldtrials=*BackgroundTracing/default/ --enable-features=NetworkService,NetworkServiceInProcess --disable-features=site-per-process,TranslateUI,BlinkGenPropertyTrees --window-position=0,0 --window-size=1200,900 --headless --disable-gpu
2022-05-18T10:00:18.751Z INFO devtools: Connect Puppeteer with browser on port 64129
FetchError: Failed to fetch browser webSocket URL from http://localhost:64129/json/version: request to http://localhost:64129/json/version failed, reason: connect ECONNREFUSED ::1:64129
    at ClientRequest.<anonymous> (/Users/mh/Documents/git/cto-service-lids/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:527:28)
    at ClientRequest.emit (node:domain:475:12)
    at Socket.socketErrorListener (node:_http_client:454:9)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
    1) Run that test!
    2) "after all" hook for "Run that test!"


  0 passing (563ms)
  2 failing

  1) Testing NodeJS version v18.1.0
       Run that test!:
     TypeError: Cannot read properties of undefined (reading 'url')
      at Context.<anonymous> (test/webdriverio-failure.js:40:19)
      at process.processImmediate (node:internal/timers:471:21)

  2) Testing NodeJS version v18.1.0
       "after all" hook for "Run that test!":
     TypeError: Cannot read properties of undefined (reading 'deleteSession')
      at Context.<anonymous> (test/webdriverio-failure.js:35:19)
      at process.processImmediate (node:internal/timers:471:21)
```

**Comment by mherger** [comment] 2022-05-18 10:01
https://github.com/puppeteer/puppeteer/issues/8289?

**Comment by pavanzebra** [comment] 2022-05-25 13:38
**I'm also getting the same error while executing via browserstack**

2022-05-25T13:34:50.034Z INFO @wdio/local-runner: Run worker command: run
2022-05-25T13:34:52.637Z INFO webdriver: Initiate new session using the WebDriver protocol
2022-05-25T13:34:52.641Z INFO webdriver: [POST] https://hub-cloud.browserstack.com/wd/hub/session
2022-05-25T13:34:52.641Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      browserName: 'chrome',
      acceptInsecureCerts: true,
      'bstack:options': [Object],
      'wdio:sharedStoreServicePort': 62186
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'chrome',
    acceptInsecureCerts: true,
    'bstack:options': { os: 'Windows', osVersion: '10', buildName: 'Test' },
    'wdio:sharedStoreServicePort': 62186
  }
}
2022-05-25T13:34:58.350Z ERROR @wdio/utils:shim: FetchError: Failed to fetch browser webSocket URL from http://localhost:7026/json/version: request to http://localhost:7026/json/version failed, reason: connect ECONNREFUSED 127.0.0.1:7026
    at ClientRequest.<anonymous> (C:\Users\ph1477\OneDrive - Zebra Technologies\WebDriverIO_Notes\automation\zpa-rnd-automation\node_modules\node-fetch\lib\index.js:1491:11)
    at ClientRequest.emit (node:events:390:28)
    at ClientRequest.emit (node:domain:475:12)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by cpcallen** [comment] 2022-06-21 18:17
We are seeing this on node.js v18.4 on Linux (including [in GitHub CI here](https://github.com/google/blockly/runs/6922998643?check_suite_focus=true)) but not on node.js v14 or v16.

Interestingly we are also _not_ seeing this issue on node.js v18.4 on macOS (Monterrey).

**Comment by mauriceKA** [comment] 2022-08-12 23:39
I also see this on node v18.7.0

**Comment by posthello-code** [comment] 2022-08-18 02:32
This also occurred for me on my local machine in node 18.3.0.
I ran an npm update and the issue went away locally.

After pushing my code to our bitbucket pipelines it's occurring once again.
I also tried on node v17, and had the same result (see below)

`2022-08-18T01:46:30.494Z DEBUG @wdio/local-runner:utils: init remote session
2022-08-18T01:46:30.509Z INFO devtools:puppeteer: Initiate new session using the DevTools protocol
2022-08-18T01:46:30.510Z INFO devtools: Launch Google Chrome with flags: --enable-automation --disable-popup-blocking --disable-extensions --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --no-default-browser-check --disable-hang-monitor --disable-prompt-on-repost --disable-client-side-phishing-detection --password-store=basic --use-mock-keychain --disable-component-extensions-with-background-pages --disable-breakpad --disable-dev-shm-usage --disable-ipc-flooding-protection --disable-renderer-backgrounding --force-fieldtrials=*BackgroundTracing/default/ --enable-features=NetworkService,NetworkServiceInProcess --disable-features=site-per-process,TranslateUI,BlinkGenPropertyTrees --window-position=0,0 --window-size=1200,900 --headless --no-sandbox
2022-08-18T01:46:31.093Z INFO devtools: Connect Puppeteer with browser on port 37453
2022-08-18T01:46:31.114Z ERROR @wdio/runner: FetchError: Failed to fetch browser webSocket URL from [http://localhost:37453/json/version:](http://localhost:37453/json/version) request to http://localhost:37453/json/version failed, reason: connect ECONNREFUSED ::1:37453
    at ClientRequest.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:527:28)
    at ClientRequest.emit (node:domain:475:12)
    at Socket.socketErrorListener (node:_http_client:454:9)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)`
    
My current work around was to downgrade to 16.17.0.

**Comment by juanrgm** [comment] 2022-10-10 16:47
> This also occurred for me on my local machine in node 18.3.0. I ran an npm update and the issue went away locally.
> 
> After pushing my code to our bitbucket pipelines it's occurring once again. I also tried on node v17, and had the same result (see below)
> 
> ```
> 2022-08-18T01:46:30.494Z DEBUG @wdio/local-runner:utils: init remote session
> 2022-08-18T01:46:30.509Z INFO devtools:puppeteer: Initiate new session using the DevTools protocol
> 2022-08-18T01:46:30.510Z INFO devtools: Launch Google Chrome with flags: --enable-automation --disable-popup-blocking --disable-extensions --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --no-default-browser-check --disable-hang-monitor --disable-prompt-on-repost --disable-client-side-phishing-detection --password-store=basic --use-mock-keychain --disable-component-extensions-with-background-pages --disable-breakpad --disable-dev-shm-usage --disable-ipc-flooding-protection --disable-renderer-backgrounding --force-fieldtrials=*BackgroundTracing/default/ --enable-features=NetworkService,NetworkServiceInProcess --disable-features=site-per-process,TranslateUI,BlinkGenPropertyTrees --window-position=0,0 --window-size=1200,900 --headless --no-sandbox
> 2022-08-18T01:46:31.093Z INFO devtools: Connect Puppeteer with browser on port 37453
> 2022-08-18T01:46:31.114Z ERROR @wdio/runner: FetchError: Failed to fetch browser webSocket URL from [http://localhost:37453/json/version:](http://localhost:37453/json/version) request to http://localhost:37453/json/version failed, reason: connect ECONNREFUSED ::1:37453
>     at ClientRequest.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/node-fetch/lib/index.js:1491:11)
>     at ClientRequest.emit (node:events:527:28)
>     at ClientRequest.emit (node:domain:475:12)
>     at Socket.socketErrorListener (node:_http_client:454:9)
>     at Socket.emit (node:events:527:28)
>     at Socket.emit (node:domain:475:12)
>     at emitErrorNT (node:internal/streams/destroy:164:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:129:3)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21)
> ```
> 
> My current work around was to downgrade to 16.17.0.

Same case here.

**Comment by bjouhier** [comment] 2022-10-29 22:03
The following config hook fixed it for me:
```js
    beforeSession: () => {
        dns.setDefaultResultOrder('ipv4first');
    },
```

**Comment by kopax-polyconseil** [comment] 2022-11-09 10:17
> The following config hook fixed it for me:
> 
> ```js
>     beforeSession: () => {
>         dns.setDefaultResultOrder('ipv4first');
>     },
> ```

What is `dns`?

**Comment by christian-bromann** [comment] 2022-11-09 17:09
> What is `dns`?

It is a [Node.js](https://nodejs.org/api/dns.html) module, e.g.

```ts
import dns from 'node:dns'
```

**Comment by toan301** [comment] 2022-11-27 09:22
> The following config hook fixed it for me:
> 
> ```js
>     beforeSession: () => {
>         dns.setDefaultResultOrder('ipv4first');
>     },
> ```

it didn't work for me. but thank ur suggestion

**Comment by AndyLysenko** [comment] 2022-12-07 10:17
> The following config hook fixed it for me:
> 
> ```js
>     beforeSession: () => {
>         dns.setDefaultResultOrder('ipv4first');
>     },
> ```

Worked for me.
node 19.2.0
macOS 12.6

**Comment by christian-bromann** [comment] 2022-12-07 16:38
This should be fixed with WebdriverIO v8 as we updated Puppeteer to the latest version. If someone can provide a patch for the `v7` branch to release it for v7 I am happy to merge and release it.

**Closed by christian-bromann** 2022-12-07 16:38 UTC
Labels: Bug 🐛, Needs Investigation, help wanted

**Comment by dragosMC91** [comment] 2023-01-04 10:54
this is also happenning for me in wdio 8.1.2 and node 18.12.1, does anyone else still have the issue ?

**Comment by rdpanek** [comment] 2023-01-06 10:01
Yep, i have the same problem.
- OSX Ventura 13.1
- node v18.13.0
and wdio
```javascript
  "devDependencies": {
    "@wdio/cli": "8.1.2",
    "@wdio/devtools-service": "^8.1.2",
    "@wdio/local-runner": "8.1.2",
    "@wdio/mocha-framework": "8.1.2",
    "@wdio/spec-reporter": "8.1.2"
  },
  ```
  
  Result
  ```bash
  [0-0] RUNNING in chrome - file:///test/specs/example.e2e.js
[0-0] 2023-01-06T10:00:54.267Z ERROR @wdio/utils:shim: TypeError: Failed to fetch browser webSocket URL from http://localhost:60324/json/version: fetch failed
...
```

**Comment by christian-bromann** [comment] 2023-01-06 17:22
Can someone who is still experience this create a reproducible example?

**Comment by thorsten-wolf-neptune** [comment] 2023-01-10 08:51
> The following config hook fixed it for me:
> 
> ```js
>     beforeSession: () => {
>         dns.setDefaultResultOrder('ipv4first');
>     },
> ```

Hi all. We had the same issue since working with node v18.12.1 and the mentioned beforeSession hook fixed the problem in our case.
Upgrading to Webdriver v8 seems to require a big refactoring for us because of the switch do ES Module.

**Comment by christian-bromann** [comment] 2023-01-11 08:18
> Upgrading to Webdriver v8 seems to require a big refactoring for us because of the switch do ES Module.

You can use WebdriverIO v8 within CJS projects as well.

**Comment by thorsten-wolf-neptune** [comment] 2023-01-11 08:20
oh ok. i'll give it a shot. Thx for that info @christian-bromann

**Comment by romaricpascal** [comment] 2023-01-12 18:00
> Can someone who is still experience this create a reproducible example?

@christian-bromann I've had to set up the workaround while evaluating Webdriver.io for our browser tests. The branch is [publicly available there](https://github.com/alphagov/govuk-frontend/tree/90791a0):

- configuration is in `wdio.conf.js` as created by running `npm init wdio .`
- there's a single test in `src/govuk/components/character-count/character-count.e2e.js`

The error only happened for me when wdio watched for changes. The first run was OK, and the error showed once I saved my test file to get the tests to run again. That last commit on the branch was the one I added the workaround in so the previous commit should still show the error.

Note that with the workaround, the tests do re-run, but another error gets logged:

```txt
[0-0] 2023-01-12T17:47:37.962Z ERROR @wdio/runner: Error: You are trying to attach to a protocol stub, this should never occur, please file an issue.
[0-0]     at ProtocolStub.attachToSession (file:///<redacted>/govuk-frontend/node_modules/webdriverio/build/protocol-stub.js:31:19)
[0-0]     at attach (file:///<redacted>/govuk-frontend/node_modules/webdriverio/build/index.js:73:27)
[0-0]     at async Runner._startSession (file:///<redacted>/govuk-frontend/node_modules/@wdio/runner/build/index.js:221:29)
[0-0]     at async Runner.run (file:///<redacted>/code/govuk-frontend/node_modules/@wdio/runner/build/index.js:58:23)
```

Hope this is helpful 😄

**Comment by christian-bromann** [comment] 2023-01-15 10:40
@romaricpascal thanks for investigating the issue. Mind raising a new issue with these findings given that the original issue was based on a different bug. I believe this one might be related to the watcher functionality.

**Comment by romaricpascal** [comment] 2023-01-16 12:09
> @romaricpascal thanks for investigating the issue. Mind raising a new issue with these findings given that the original issue was based on a different bug. I believe this one might be related to the watcher functionality.

Done. I've split it into two issues:
- https://github.com/webdriverio/webdriverio/issues/9612 for the FetchError similar to this one
- https://github.com/webdriverio/webdriverio/issues/9608 for the protocol stub one

**Comment by rowah** [comment] 2023-05-10 06:16
downgrading to Node 16.17.0 on MacOS Monterey 12.6 fixed it for me.

**Comment by alek75** [comment] 2023-09-27 10:41
I had the same issue after upgrade to node 18.18
The issue seems to be solved after i've upgraded to the latest wdio versions - 8.16.12
Fingers crossed!

**Comment by markomirtic** [comment] 2023-09-27 15:15
I also have the same issue for my API test, for UI everything works fine:

ERROR @wdio/runner: FetchError: Failed to fetch browser webSocket URL from http://localhost:45463/json/version: request to http://localhost:45463/json/version failed, reason: connect ECONNREFUSED ::1:45463

**Comment by nitram-work** [comment] 2024-04-26 13:23
Probable cause is node-fetch on Node 18 resolving localhost to ipv6 ::1 and rejecting served connection from ipv4 interfaces https://github.com/node-fetch/node-fetch/issues/1624
