### ISSUE TITLE
[🐛 Bug]: what is wrong with typing in v8 with intelij ? (& problems with demo project)

### ISSUE THREAD

**Issue by pinim** [webdriverio/webdriverio#10817] opened 2023-07-30 12:50 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v16

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
from auto-generated example
```

### What happened?

typing behaviors are weird, and no correct types of global values like browser, $, and expect.

I tried to upgrade my existing repo from v7 to v8, and I thought there is a problem in my repo, to make sure it regards only my project I opened a fresh project and run `npm init wdio .`, and then I saw that all the problems are also there ...

all types are not recognized, `got errors like Corresponding file is not included in tsconfig.json`

![image](https://github.com/webdriverio/webdriverio/assets/24281112/939313cd-5003-4450-9e3e-a726aa5b22ab)

and some more problems with the demo, I created a ts project, and in the script in the package.json it tries to launch a js extension file - 
```
"scripts": {
        "wdio": "wdio run wdio.conf.js"
    }
```
I changed it manually, but then when I tried to run the demo test, it crashed because of chrome binary is not found (but actually he is in there, according to the wdio setup), the log is attached.

### What is your expected behavior?

after initializing the setup I assume that the demo will work fine

### How to reproduce the bug.

just run  `npm init wdio .`  in an empty project .......

### Relevant log output

```typescript
> webdriverio-tests@0.1.0 wdio
> wdio run wdio.conf.ts


Execution of 1 workers started at 2023-07-30T12:39:35.439Z

2023-07-30T12:39:35.484Z INFO chromedriver: Initiate Chromedriver Launcher (v8.1.1)
2023-07-30T12:39:35.485Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-07-30T12:39:35.487Z INFO chromedriver: Start Chromedriver (/Users/pinim/dev/webdriverio-fresh/node_modules/chromedriver/lib/chromedriver/chromedriver) with args --port=9515 --url-base=/
2023-07-30T12:39:35.508Z INFO chromedriver: Starting ChromeDriver 115.0.5790.102 (90efd4b0ad6aa15eeafcdabd5817ae939f7ba059-refs/branch-heads/5790_90@{#9}) on port 9515
2023-07-30T12:39:35.508Z INFO chromedriver: Only local connections are allowed.
2023-07-30T12:39:35.508Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2023-07-30T12:39:35.509Z INFO chromedriver: ChromeDriver was started successfully.
2023-07-30T12:39:35.607Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-07-30T12:39:35.608Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,wdio.conf.ts
[0-0] 2023-07-30T12:39:36.456Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2023-07-30T12:39:38.141Z WARN @wdio/mocha-framework: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
[0-0] `browser` object has only `capabilities` and some flags like `isMobile`.
[0-0] Helper files that use other `browser` commands have to be moved to `before` hook.
[0-0] Spec file(s): file:///Users/pinim/dev/webdriverio-fresh/test/specs/test.e2e.ts
[0-0] Error: TSError: ⨯ Unable to compile TypeScript:
[0-0] test/pageobjects/login.page.ts(1,1): error TS6133: 'ChainablePromiseElement' is declared but its value is never read.
[0-0] 
[0-0]     at createTSError (/Users/pinim/dev/webdriverio-fresh/node_modules/ts-node/src/index.ts:859:12)
[0-0]     at reportTSError (/Users/pinim/dev/webdriverio-fresh/node_modules/ts-node/src/index.ts:863:19)
[0-0]     at getOutput (/Users/pinim/dev/webdriverio-fresh/node_modules/ts-node/src/index.ts:1077:36)
[0-0]     at Object.compile (/Users/pinim/dev/webdriverio-fresh/node_modules/ts-node/src/index.ts:1433:41)
[0-0]     at Module.m._compile (/Users/pinim/dev/webdriverio-fresh/node_modules/ts-node/src/index.ts:1617:30)
[0-0]     at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
[0-0]     at require.extensions.<computed> (/Users/pinim/dev/webdriverio-fresh/node_modules/ts-node/src/index.ts:1621:12)
[0-0]     at Object.require.extensions.<computed> [as .ts] (/Users/pinim/dev/webdriverio-fresh/node_modules/ts-node/src/index.ts:1621:12)
[0-0]     at Module.load (node:internal/modules/cjs/loader:981:32)
[0-0]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[0-0] RUNNING in chrome - file:///test/specs/test.e2e.ts
[0-0] 2023-07-30T12:39:38.143Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-07-30T12:39:38.207Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2023-07-30T12:39:38.207Z INFO webdriver: DATA {
[0-0]   capabilities: { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
[0-0]   desiredCapabilities: { browserName: 'chrome' }
[0-0] }
[0-0] 2023-07-30T12:39:38.227Z WARN webdriver: Request failed with status 500 due to unknown error: cannot find Chrome binary
[0-0] 2023-07-30T12:39:38.227Z INFO webdriver: Retrying 1/3
[0-0] 2023-07-30T12:39:38.227Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2023-07-30T12:39:38.227Z INFO webdriver: DATA {
[0-0]   capabilities: { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
[0-0]   desiredCapabilities: { browserName: 'chrome' }
[0-0] }
[0-0] 2023-07-30T12:39:38.231Z WARN webdriver: Request failed with status 500 due to unknown error: cannot find Chrome binary
[0-0] 2023-07-30T12:39:38.231Z INFO webdriver: Retrying 2/3
[0-0] 2023-07-30T12:39:38.231Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2023-07-30T12:39:38.231Z INFO webdriver: DATA {
[0-0]   capabilities: { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
[0-0]   desiredCapabilities: { browserName: 'chrome' }
[0-0] }
[0-0] 2023-07-30T12:39:38.234Z WARN webdriver: Request failed with status 500 due to unknown error: cannot find Chrome binary
[0-0] 2023-07-30T12:39:38.234Z INFO webdriver: Retrying 3/3
[0-0] 2023-07-30T12:39:38.234Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2023-07-30T12:39:38.234Z INFO webdriver: DATA {
[0-0]   capabilities: { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
[0-0]   desiredCapabilities: { browserName: 'chrome' }
[0-0] }
[0-0] 2023-07-30T12:39:38.237Z ERROR webdriver: Request failed with status 500 due to unknown error: unknown error: cannot find Chrome binary
[0-0] 2023-07-30T12:39:38.237Z ERROR webdriver: unknown error: unknown error: cannot find Chrome binary
[0-0]     at getErrorFromResponseBody (file:///Users/pinim/dev/webdriverio-fresh/node_modules/webdriver/build/utils.js:194:12)
[0-0]     at NodeJSRequest._request (file:///Users/pinim/dev/webdriverio-fresh/node_modules/webdriver/build/request/index.js:164:23)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at async startWebDriverSession (file:///Users/pinim/dev/webdriverio-fresh/node_modules/webdriver/build/utils.js:63:20)
[0-0]     at async Function.newSession (file:///Users/pinim/dev/webdriverio-fresh/node_modules/webdriver/build/index.js:26:45)
[0-0]     at async remote (file:///Users/pinim/dev/webdriverio-fresh/node_modules/webdriverio/build/index.js:48:22)
[0-0]     at async Runner._startSession (file:///Users/pinim/dev/webdriverio-fresh/node_modules/@wdio/runner/build/index.js:221:29)
[0-0]     at async Runner._initSession (file:///Users/pinim/dev/webdriverio-fresh/node_modules/@wdio/runner/build/index.js:187:25)
[0-0]     at async Runner.run (file:///Users/pinim/dev/webdriverio-fresh/node_modules/@wdio/runner/build/index.js:77:19)
[0-0] 2023-07-30T12:39:38.238Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] unknown error: cannot find Chrome binary
[0-0]     at startWebDriverSession (file:///Users/pinim/dev/webdriverio-fresh/node_modules/webdriver/build/utils.js:68:15)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at async Function.newSession (file:///Users/pinim/dev/webdriverio-fresh/node_modules/webdriver/build/index.js:26:45)
[0-0]     at async remote (file:///Users/pinim/dev/webdriverio-fresh/node_modules/webdriverio/build/index.js:48:22)
[0-0]     at async Runner._startSession (file:///Users/pinim/dev/webdriverio-fresh/node_modules/@wdio/runner/build/index.js:221:29)
[0-0]     at async Runner._initSession (file:///Users/pinim/dev/webdriverio-fresh/node_modules/@wdio/runner/build/index.js:187:25)
[0-0]     at async Runner.run (file:///Users/pinim/dev/webdriverio-fresh/node_modules/@wdio/runner/build/index.js:77:19)
[0-0] FAILED in chrome - file:///test/specs/test.e2e.ts
2023-07-30T12:39:38.363Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-07-30T12:39:38.363Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:02 

2023-07-30T12:39:38.364Z INFO @wdio/local-runner: Shutting down spawned worker
2023-07-30T12:39:38.614Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-07-30T12:39:38.614Z INFO @wdio/local-runner: shutting down

Process finished with exit code 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2023-07-30 19:05
Thanks for raising the issue.

> ```ts
> [0-0] test/pageobjects/login.page.ts(1,1): error TS6133: 'ChainablePromiseElement' is declared but its value is never read.
> ```

This error is a linting error, you can remove the parameter in `test/pageobjects/login.page.ts`. Duplicate of #10812

> ```ts
> unknown error: cannot find Chrome binary
> ```

This issue is know and will be fixed with #10767

**Closed by christian-bromann** 2023-07-30 19:05 UTC
Labels: Bug 🐛, Needs Triaging ⏳

**Comment by pinim** [comment] 2023-07-30 23:08
tnx @christian-bromann for the response.
what about the issues with the types? (as shown in the attached picture)

**Comment by christian-bromann** [comment] 2023-07-31 01:51
It should work out of the box, have you looked at https://webdriver.io/docs/autocompletion/#intellij
