### ISSUE TITLE
How can I add custom-header with the url I want to visit? For an example : x-original-host: for a particular locale or market?[💡 Feature]: <title>

### ISSUE THREAD

**Issue by raktim1988** [webdriverio/webdriverio#8147] opened 2022-03-23 13:50 UTC
### Is your feature request related to a problem?

adding custom headers to the url

### Describe the solution you'd like.

to have the simple solution to be able to add headers in my requests

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment] 2022-03-23 13:54
Duplicate of #6361

**Closed by christian-bromann** 2022-03-23 13:54 UTC
Labels: Needs Triaging ⏳, Idea 💡
