### ISSUE TITLE
cookies aren't enable - selenium webdriver.io with phantomjs  [urgent]

### ISSUE THREAD

**Issue by narainsagar** [webdriverio/webdriverio#1027] opened 2016-01-14 10:40 UTC
```
var webdriverio = require('webdriverio');

var opts = desiredCapabilities: {
    browserName: 'phantomjs',
    javascriptEnabled: true
  },
  "host": "localhost",
  "port": 4444
};

var email = ''; // your email
var password: ''; // your password

var client = webdriverio
      .remote(opts)
      .init()
      .url('https://www.amazon.co.uk/gp/sign-in.html')
      .setValue('#ap_email', email)
      .setValue('#ap_password', password)
      .submitForm('form[name="signIn"]')
      .then(function() { // save the screenshot
              this.saveScreenshot(__dirname + '/loginPage.png');
      })
      .end();
```
Here is saved screenshot:
![loginpage562a11f15abf63000002ec1d](https://cloud.githubusercontent.com/assets/13800762/12322296/f02ce0ae-bad4-11e5-8c2c-2f39d4757442.png)
Thanks.

**Comment by christian-bromann** [comment] 2016-01-14 14:32
Cookies are enabled in PhantomJS by default. I am not sure why Amazon returns that page. Was able to reproduce it though.

**Comment by narainsagar** [comment] 2016-01-14 16:14
@christian-bromann Thanks for the reply. Yeah, I had logged cookies but return none, tried to set a custom Cookie with `.setCookie({name: '', value: '', domain: 'amazon.co.uk'})` but still it have the same problem..

**Comment by christian-bromann** [comment] 2016-01-15 22:32
@narainsagar I would suggest to file an issue in the phantomjs repository. I tried to get it working using several cli arguments without success :-/

**Comment by narainsagar** [comment] 2016-01-16 07:56
@christian-bromann  Ok.

**Comment by christian-bromann** [comment] 2016-01-22 12:04
This seems to be a limitation of PhantomJS and I don't see a way to get this working with a tweak. Closing

**Closed by christian-bromann** 2016-01-22 12:04 UTC
