### ISSUE TITLE
[🐛 Bug]: Unable to connect to "http://localhost:9515/"

### ISSUE THREAD

**Issue by sdoigmm** [webdriverio/webdriverio#11484] opened 2023-10-20 02:15 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.20.0

### Node.js Version

16.15.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [{
    
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 5,
        //
        browserName: 'chrome',
        acceptInsecureCerts: true
        // If outputDir is provided WebdriverIO can capture driver session logs
        // it is possible to configure which logTypes to include/exclude.
        // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
        // excludeDriverLogs: ['bugreport', 'server'],
    }],
```

### What happened?

- Install webdriverio using default options
- Edit `wdio.conf.js`: `baseUrl: 'https://example.com',`
- Run `npx wdio run wdio.conf.js`
- Receive an error  `ERROR @wdio/runner: Error: Failed to create session.
[0-0] Unable to connect to "http://localhost:9515/", make sure browser driver is running on that address.`

### What is your expected behavior?

Default test to run without an error

### How to reproduce the bug.

- Install webdriverio using default options
- Edit `wdio.conf.js`: `baseUrl: 'https://example.com',`
- Run `npx wdio run wdio.conf.js`

### Relevant log output

```typescript
`2023-10-20T02:10:16.730Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] Unable to connect to "http://localhost:9515/", make sure browser driver is running on that address.`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2023-10-20 02:58
@sdoigmm thanks for raising the issue.

> * Install webdriverio using default options

Can you describe what you did? Did you use `npm init wdio@latest .`?

**Comment by sdoigmm** [comment] 2023-10-20 04:07
> @sdoigmm thanks for raising the issue.
> 
> > * Install webdriverio using default options
> 
> Can you describe what you did? Did you use `npm init wdio@latest .`?

Ahh. No. I used `npm wdio init`

**Comment by christian-bromann** [comment] 2023-10-20 05:12
Does it work with `npm init wdio@latest .`?

Also see https://webdriver.io/docs/gettingstarted 😉

**Comment by sdoigmm** [comment] 2023-10-20 07:04
No, receive:

`Ups, something went wrong: Error calling: yarn add --exact --cwd /Users/Steven/Documents/Projects/wdio-test3 --dev @wdio/cli@latest!
npm ERR! code 1
npm ERR! path /Users/Steven/Documents/Projects/wdio-test3
npm ERR! command failed
npm ERR! command sh -c create-wdio

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Steven/.npm/_logs/2023-10-20T07_03_13_174Z-debug-0.log`

**Comment by christian-bromann** [comment] 2023-10-20 15:08
> No, receive:

Can you provide more logs or terminal data? Maybe a gif animation?

**Comment by sdoigmm** [comment] 2023-10-23 04:58
Was the command `npm init wdio@latest .`? If so, receive:

Installing @wdio/cli to initialize project...


```⚠️  Ups, something went wrong: Error calling: yarn add --exact --cwd /Users/Steven/Documents/Projects/wdio-test3 --dev @wdio/cli@latest!
npm ERR! code 1
npm ERR! path /Users/Steven/Documents/Projects/wdio-test3
npm ERR! command failed
npm ERR! command sh -c create-wdio "."

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Steven/.npm/_logs/2023-10-23T04_54_19_281Z-debug-0.log```

`/Users/Steven/.npm/_logs/2023-10-23T04_54_19_281Z-debug-0.log` contains:

```0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@8.11.0
2 info using node@v16.15.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:/Users/Steven/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:credentials Completed in 1ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 8ms
18 timing npm:load:configload Completed in 8ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm init wdio@latest .
22 verbose argv "init" "wdio@latest" "."
23 timing npm:load:setTitle Completed in 5ms
24 timing config:load:flatten Completed in 1ms
25 timing npm:load:display Completed in 2ms
26 verbose logfile logs-max:10 dir:/Users/Steven/.npm/_logs
27 verbose logfile /Users/Steven/.npm/_logs/2023-10-23T04_54_19_281Z-debug-0.log
28 timing npm:load:logFile Completed in 2ms
29 timing npm:load:timers Completed in 0ms
30 timing npm:load:configScope Completed in 0ms
31 timing npm:load Completed in 17ms
32 silly logfile start cleaning logs, removing 1 files
33 silly logfile done cleaning log files
34 timing arborist:ctor Completed in 0ms
35 http fetch GET 200 https://registry.npmjs.org/create-wdio 1237ms (cache revalidated)
36 timing arborist:ctor Completed in 0ms
37 timing arborist:ctor Completed in 0ms
38 timing command:init Completed in 10868ms
39 verbose stack Error: command failed
39 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
39 verbose stack     at ChildProcess.emit (node:events:527:28)
39 verbose stack     at maybeClose (node:internal/child_process:1092:16)
39 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
40 verbose cwd /Users/Steven/Documents/Projects/wdio-test3
41 verbose Darwin 23.0.0
42 verbose node v16.15.1
43 verbose npm  v8.11.0
44 error code 1
45 error path /Users/Steven/Documents/Projects/wdio-test3
46 error command failed
47 error command sh -c create-wdio "."
48 verbose exit 1
49 timing npm Completed in 10922ms
50 verbose code 1
51 error A complete log of this run can be found in:
51 error     /Users/Steven/.npm/_logs/2023-10-23T04_54_19_281Z-debug-0.log```

**Comment by sdoigmm** [comment] 2023-10-23 04:59
`/Users/Steven/.npm/_logs/2023-10-23T04_54_19_281Z-debug-0.log` contains:

```0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@8.11.0
2 info using node@v16.15.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:/Users/Steven/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:credentials Completed in 1ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 8ms
18 timing npm:load:configload Completed in 8ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm init wdio@latest .
22 verbose argv "init" "wdio@latest" "."
23 timing npm:load:setTitle Completed in 5ms
24 timing config:load:flatten Completed in 1ms
25 timing npm:load:display Completed in 2ms
26 verbose logfile logs-max:10 dir:/Users/Steven/.npm/_logs
27 verbose logfile /Users/Steven/.npm/_logs/2023-10-23T04_54_19_281Z-debug-0.log
28 timing npm:load:logFile Completed in 2ms
29 timing npm:load:timers Completed in 0ms
30 timing npm:load:configScope Completed in 0ms
31 timing npm:load Completed in 17ms
32 silly logfile start cleaning logs, removing 1 files
33 silly logfile done cleaning log files
34 timing arborist:ctor Completed in 0ms
35 http fetch GET 200 https://registry.npmjs.org/create-wdio 1237ms (cache revalidated)
36 timing arborist:ctor Completed in 0ms
37 timing arborist:ctor Completed in 0ms
38 timing command:init Completed in 10868ms
39 verbose stack Error: command failed
39 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
39 verbose stack     at ChildProcess.emit (node:events:527:28)
39 verbose stack     at maybeClose (node:internal/child_process:1092:16)
39 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
40 verbose cwd /Users/Steven/Documents/Projects/wdio-test3
41 verbose Darwin 23.0.0
42 verbose node v16.15.1
43 verbose npm  v8.11.0
44 error code 1
45 error path /Users/Steven/Documents/Projects/wdio-test3
46 error command failed
47 error command sh -c create-wdio "."
48 verbose exit 1
49 timing npm Completed in 10922ms
50 verbose code 1
51 error A complete log of this run can be found in:
51 error     /Users/Steven/.npm/_logs/2023-10-23T04_54_19_281Z-debug-0.log```

**Comment by christian-bromann** [comment] 2023-10-23 16:08
It is hard to tell why this is failing for you. I can't reproduce this and I am on a Mac machine as well. Can you try with the latest Node.js version?

**Comment by sdoigmm** [comment] 2023-10-24 01:52
Thanks, node 20.8.1 fixed it, will remember that, cheers

**Comment by christian-bromann** [comment] 2023-10-24 03:35
Thanks for verifying. Closing.

**Closed by christian-bromann** 2023-10-24 03:35 UTC
Labels: Bug 🐛, Information Missing
