### ISSUE TITLE
Unexpected test names

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1816] opened 2017-01-13 13:45 UTC
## The problem

```js
describe ('TESTMAIL-33624', () => {
  // ...
})
```

```js
// WDIO.xunitchrome.0-1.xml

<testsuite name="testmail_33624_2" timestamp="2017-01-10T18:44:03" time="12.37" tests="1" failures="0" errors="0" skipped="0">
```

We must keep the original name. 
For example, I use these names for navigation (in Jenkins and Bamboo) between my issues in JIRA.

**Comment by christian-bromann** [comment] 2017-01-13 17:00
duplicate of webdriverio/wdio-junit-reporter#22

**Closed by christian-bromann** 2017-01-13 17:00 UTC
