### ISSUE TITLE
Add grep option

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1414] opened 2016-06-29 11:43 UTC
### Problem

The option `--grep` does not work as expected.

**test**

```js
describe('TESTMAIL-0001', () => {
   /// ...
})
```

**config**

```js
{
   suites: {
       login: [
               'TESTMAIL-0001.js',
               'TESTMAIL-0002.js',
               'TESTMAIL-0003.js'
       ]
   }
}
```

**runner**

```
wdio --suite=login --mochaOpts.grep=TESTMAIL-0001;
```

What i see:

Application is starting the browser instance for TESTMAIL-0003 (not expected)
Application is starting the browser instance for TESTMAIL-0002 (not expected) 
Application is starting the browser instance for TESTMAIL-0001 (expected)
Mocha is running TESTMAIL-0001

```
Wrote xunit report to [./cache/tests/e.mail.ru/reports].
Wrote xunit report to [./cache/tests/e.mail.ru/reports].
Wrote xunit report to [./cache/tests/e.mail.ru/reports].
Wrote json report to [./cache/tests/e.mail.ru/reports].
Wrote json report to [./cache/tests/e.mail.ru/reports].
Wrote json report to [./cache/tests/e.mail.ru/reports].
```

`describe.only` and `it.only` i'ts not working for me as well.

### Proposal

Please, add standard grep option to filter test cases

**Comment by christian-bromann** [comment] 2016-06-29 11:57
Duplicate of #1247

**Closed by christian-bromann** 2016-06-29 11:57 UTC

**Comment by monolithed** [comment] 2016-07-06 22:22
If someone wants to know how implements a custom `--grep` option:


#### helpers.js

```js
let path = require('path'),
	fs = require('fs');

let merge = require('deepmerge'),
	glob = require('glob');

module.exports = {
	/**
	 * @returns {string|undefined}
	 */
	options () {
		for (let option of process.argv) {	
			let [key, value] = option.split('=');

			if (key === name) {
				return value;
			}
		}
	},

	/**
	 * { <suite>: [ <files> ] }
	 *
	 * @param {string} directory
	 * @param {string} additional
	 * @returns {Object}
	 */
	suites (directory, additional = {}) {
		let files = fs.readdirSync(directory),
			cases = {};

		let grep = this.options('--grep');

		files.forEach(suite => {
			let files = path.join(directory, suite, '**/*.js'),
				debug = false;

			if (process.env.NODE_DEBUG) {
				debug = true;
			}

			files = glob.sync(files, {
				cache: true,
				debug
			});

			cases[suite] = files.filter(file => {
				if (grep) {
					let match = new RegExp(grep);

					if (grep && match.test(file)) {
						return file;
					}
				} else {
					return file;
				}
			});
		});

		return this.extend(cases, additional);
	}

	/**
	 * @param {Object} x
	 * @param {Object} y
	 * @returns {Object}
	 */
	extend (x, y) {
		return merge(...arguments);
	}
}
```


### wdio.config.js

```js
let helpers = require('./helpers');

exports.config = {
	suites: helpers.suites('tests')
}
```

### tests

```
tests 
     foo
         test_1.js
         test_2.js
```

### package.json

```json
{
	"scripts": {
		"test"   : "wdio wdio.config.js",
	},

	"dependencies": {
		"deepmerge"           : "^0.2.10",
		"glob"                : "^7.0.5",
		"webdriverio"         : "^4.1.1",
		"wdio-spec-reporter"  : "^0.0.1",
		"wdio-mocha-framework": "^0.3.4",
	}
}
```

### shell

```js
npm test -- --suite=foo --grep=test_1*;
```
