### ISSUE TITLE
@wdio/appium-service does not work with iOS Simulator 12.2

### ISSUE THREAD

**Issue by Spinnenzunge** [webdriverio/webdriverio#3893] opened 2019-04-29 09:28 UTC
Update @wdio/appium-service to newerst appium peer-dependency to fix problems fixed with appium version https://github.com/appium/appium/releases/tag/v1.12.1

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.7.9
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.14.1
 - **NPM version:** 6.9.0
 - **Browser name and version:** Safari iOS 12.2
 - **Platform name and version:** iOS 12.2
 - **Additional wdio packages used (if applicable):** @wdio/appium-service

**Config of WebdriverIO**
```
  //
  // Test runner services
  // Services take over a specific job you don't want to take care of. They enhance
  // your test setup with almost no effort. Unlike plugins, they don't add new
  // commands. Instead, they hook themselves up into the test process.
  services: ['appium'],

  //
  // ============
  // Capabilities
  // ============
  // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
  // time. Depending on the number of capabilities, WebdriverIO launches several test
  // sessions. Within your capabilities you can overwrite the spec and exclude options in
  // order to group specific specs to a specific capability.
  //
  // If you have trouble getting all important capabilities together, check out the
  // Sauce Labs platform configurator - a great tool to configure your capabilities:
  // https://docs.saucelabs.com/reference/platforms-configurator
  //
  capabilities: [{
    browserName: '',
    app: path.join(__dirname, '../platforms/ios/build/emulator/MyMobiliar.app'),
    version: '11.4',
    deviceName: 'iPhone X',
    platform: 'iOS',
    platformName: 'iOS',
    platformVersion: "12.2",
    automationName: 'XCUITest',
    nativeWebTap: true,
    autoGrantPermissions: true,
    autoWebview: true,
    autoWebviewTimeout: 10000,
    autoAcceptAlerts: true
  }]
```

**Describe the bug**
It looks like the Appium version before v1.12.1 had a bug with the new XCode Version 10.2.1 and its simulator platformVersion 12.2. If i want to run my automated tests I get the following error:

```An unknown server-side error occurred while processing the command. Original error: Remote debugger error with code '-32601': 'Page' domain was not found```

According to Appium release notes this bug should be fixed with the version [1.12.1](https://github.com/appium/appium/releases/tag/v1.12.1).

The package `@wdio/appium-service` version `5.7.9` still has the appium peer dependency 1.12.0 in the package.json.

Updateing the peer dependency of appium to 1.12.1 should fix the iOS 12.2 platform bug.

**To Reproduce**
Update XCode to 10.2.1
Set WDIO Capability platformVersion: to 12.2
Run WDIO Testrunner `./node_modules/.bin/wdio` e2e/wdio.emulator-ios.conf.js`
Get error ```An unknown server-side error occurred while processing the command. Original error: Remote debugger error with code '-32601': 'Page' domain was not found```

**Expected behavior**
Updating the appium peer dependency of @wdio/appium-service to the latest appium version should let me run my e2e test suite without error according to appium issue https://github.com/appium/appium/issues/12398

**Comment by wswebcreation** [comment] 2019-04-29 09:51
Can you please provide more info about what the problem is, this is not clear for us

**Comment by Spinnenzunge** [comment] 2019-04-29 11:05
Sorry for the lacking documentation. I updated my initial bug report. Long story short: My request is updating the appium peer dependency in @wdio/appium-service to the latest appium version 1.12.1.

This is actually an appium bug, but @wdio/appium-service should implement the latest version to get the appium fix.

**Comment by wswebcreation** [comment] 2019-04-30 07:14
@Spinnenzunge 

This is not needed, if you go to https://semver.npmjs.com/ and add `appium` and `^1.12.0` you will get this overview

![image](https://user-images.githubusercontent.com/11979740/56945655-27aca300-6b28-11e9-870f-8e13cc908faf.png)

There you would see that with `^1.12.0` as a version number you would also get `1.12.1`, even future releases that would not be a `major` because the `^` will always give minor and patches. 
Please remove your package lock, remove your `node_modules` and check again.

I'm closing this now because it works as it should be

**Closed by wswebcreation** 2019-04-30 07:14 UTC

**Comment by Spinnenzunge** [comment] 2019-05-01 12:01
Oh I'm stupid I missed the carret symbol so it just updates patches. Thank you for responding, will update my package-lock.
