### ISSUE TITLE
[🐛 Bug]: browser.execute breaks when declaring functions

### ISSUE THREAD

**Issue by Dinnerbone** [webdriverio/webdriverio#13444] opened 2024-08-23 18:18 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.0.7

### Node.js Version

v20.13.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    browserName: 'chrome'
}
```

### What happened?

When using `browser.execute` with a script that declares a function, the script gets transformed in such a way that no longer runs inside a browser. This works fine in v8.

For example:

```typescript
browser.execute(() => {
    function fn() {}
});
```

The above gets transformed, and the script that's injected onto the page becomes:

```javascript
((...args) => {
      function callFunction(f, args) {
        const deserializedThis = args.shift();
        const deserializedArgs = args;
        return f.apply(deserializedThis, deserializedArgs);
      }
      return callFunction((
        ()=>{function fn(){}__name(fn,"fn")}
      ), args);
    })
```

`__name` doesn't exist, so it throws an error.

### What is your expected behavior?

It should work.

### How to reproduce the bug.

I've made a minimal reproducible example at https://github.com/Dinnerbone/wdio-bug-repro/

The actual test that breaks is https://github.com/Dinnerbone/wdio-bug-repro/blob/main/test/specs/test.e2e.ts

This was generated with `npx create-wdio@latest` just moments ago, the only change is that test.

### Relevant log output

```
[0-0] 2024-08-23T18:20:53.484Z INFO webdriver: BIDI COMMAND script.callFunction {"functionDeclaration":"<Function[53 bytes]>","awaitPromise":false,"arguments":[],"target":{"context":"29984D43E1634C4142BF795BC9F87764"}}
[0-0] AssertionError in "Javascript execution.works"
AssertionError [ERR_ASSERTION]: {
  error: {
    columnNumber: 28,
    exception: {
      type: 'error'
    },
    lineNumber: 6,
    message: 'ReferenceError: __name is not defined',
    stackTrace: {
      callFrames: [
        {
          columnNumber: 28,
          functionName: '',
          lineNumber: 6,
          url: ''
        },
        {
          columnNumber: 17,
          functionName: 'callFunction',
          lineNumber: 3,
          url: ''
        },
        {
          columnNumber: 13,
          functionName: '',
 ... == 'Success!'
    at Context.<anonymous> (C:\Users\Dinnerbone\workspace\personal\wdio-bug\test\specs\test.e2e.ts:13:16)
    at Context.executeAsync (C:\Users\Dinnerbone\workspace\personal\wdio-bug\node_modules\@wdio\utils\build\index.js:1488:20)
    at Context.testFrameworkFnWrapper (C:\Users\Dinnerbone\workspace\personal\wdio-bug\node_modules\@wdio\utils\build\index.js:1559:14)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by danielhjacobs** [comment] 2024-08-23 19:10
For reference, possibly relevant esbuild issue (closed as unsupporte): https://github.com/evanw/esbuild/issues/1438

**Comment by gavvvr** [comment] 2024-08-23 22:06
Hello. I use wdio for testing Electron app. Having the same issue after upgrade to wdio v9.0.x

Here is the error:
```text
[0-0] 2024-08-23T22:02:04.347Z INFO webdriver: DATA {
[0-0]   script: 'return (imgurPluginId=>{const uploadStub=__name(()=>Promise.resolve("https://i.imgur.com/w88wB4I.png"),"uploadStub");app.plugins.plugins[imgurPluginId].imgUploader.upload=uploadStub}).apply(null, arguments)',
[0-0]   args: [ 'obsidian-imgur-plugin' ]
[0-0] }
[0-0] 2024-08-23T22:02:04.350Z ERROR webdriver: Request failed with status 500 due to javascript error: javascript error: __name is not defined
[0-0]   (Session info: chrome=120.0.6099.283)
[0-0] javascript error in "Electron Testing.blank note.uploads clipboard image on PASTE shortcut"
javascript error: javascript error: __name is not defined
  (Session info: chrome=120.0.6099.283)
    at async Context.<anonymous> (/Users/user/Documents/projects/obsidian-imgur-plugin/test/e2e/specs/test.e2e.ts:22:7)
```

The function my e2e test executes is:

https://github.com/gavvvr/obsidian-imgur-plugin/blob/286431937b7b62169abdded83ffc833bc86d34a8/test/e2e/specs/test.e2e.ts#L19-L24


Rolling back wdio to the latest v8.x solves the issue.

**Comment by danielhjacobs** [comment] 2024-08-26 13:40
> ```ts
> await browser.addInitScript(() => {
>     const closure = new Function(
>         'var __defProp = Object.defineProperty;' +
>         'var __name = (target, value) => __defProp(target, \'name\', { value, configurable: true });' +
>         'window.__name = __name;'
>     )
>     return closure()
> })
> ```
If that were the only workaround Ruffle needed it may be worth it, but it seems pretty hacky so we may just stay on webdriverio v8 until this and https://github.com/webdriverio/webdriverio/issues/13218 are resolved.

**Closed** 2024-09-05 09:41 UTC
Labels: Bug 🐛

**Comment by gavvvr** [comment] 2024-09-05 22:16
Hi @christian-bromann. Just upgraded to 9.0.9. Unfortunately, there is still the same error in my example code from [the above comment](https://github.com/webdriverio/webdriverio/issues/13444#issuecomment-2307867885)

**Comment by gavvvr** [comment] 2024-09-06 20:02
@christian-bromann I was able to only reproduce that in a test involving Electron service. [Here](https://github.com/webdriverio-community/wdio-electron-service/issues/756#issuecomment-2334724905) are the details and steps to reproduce.

**Comment by goosewobbler** [comment] 2024-09-08 21:13
@christian-bromann Confirmed still an issue with the Electron service.  Does this solution require BiDi?  The service is currently disabling BiDi using `wdio:enforceWebDriverClassic`.

**Comment by christian-bromann** [comment] 2024-09-09 07:53
I think it is more related to the fact that we are using `tsx` to transpile the code at runtime. Can we get a reproduction case in a more simpler form?

**Comment by goosewobbler** [comment] 2024-09-09 16:44
Adding `__name` to the preload script works.  We'll likely need to use a different approach after https://github.com/webdriverio-community/wdio-electron-service/issues/308 is implemented as the preload script will go away, hopefully ESBuild will fix it before then.

**Comment by goosewobbler** [comment] 2024-09-19 23:53
@christian-bromann I fixed this in the Electron service but it's still an issue for the WDIO `execute` function.

> I think it is more related to the fact that we are using `tsx` to transpile the code at runtime. Can we get a reproduction case in a more simpler form?

Needs to install `@wdio/cli` but this is a good repro:

https://github.com/gavvvr/wdio-electron-service-756

**Comment by christian-bromann** [comment] 2024-09-20 14:16
> You need to install `@wdio/cli` before the last command runs but this is a good repro:
> 
> [gavvvr/wdio-electron-service-756](https://github.com/gavvvr/wdio-electron-service-756)

I tested the repo and it passed.

**Comment by goosewobbler** [comment] 2024-09-20 15:00
Yeah, I just fixed it with 7.0.4

**Comment by christian-bromann** [comment] 2024-09-21 18:30
@goosewobbler awesome, can you reference to the commit with the workaround?

**Comment by goosewobbler** [comment] 2024-09-22 22:09
Sure, it's in this PR: https://github.com/webdriverio-community/wdio-electron-service/pull/774

I previously had it in the preload, here I moved it to the `before` which will still work if we manage to get rid of the IPC bridge.  And obviously expanded to `browser.execute`

**Comment by christian-bromann** [comment] 2024-09-23 16:08
Interesting, it seems that Electron tests don't run with Bidi since WebdriverIO is suppose to set these execute scripts up as preload scripts.

**Comment by goosewobbler** [comment] 2024-09-23 16:32
> Interesting, it seems that Electron tests don't run with Bidi since WebdriverIO is suppose to set these execute scripts up as preload scripts.

Do you mean that the IPC bridge is not functioning when BiDi is used?  Is the preload somehow ignored when using BiDi?

**Comment by christian-bromann** [comment] 2024-09-23 16:53
Not sure, I've pushed a patch that is fixing the problem for basic browser tests by creating a preload script that is being executed in each execution context of the browser. For Electron this doesn't seem to be working 🤔 I wonder if the context tree is giving us more insights now.

**Comment by goosewobbler** [comment] 2024-09-23 17:39
Ah ok, interesting.  I have been thinking it might be worth trying to find a replacement for the IPC bridge with BiDi before continuing down the CDP route, then users have the choice of using BiDi or CDP with bridge.  Currently if I enable BiDi in the service the E2Es all fail with `webdriver: Request failed with status 404 due to no such window`.

**Comment by christian-bromann** [comment] 2024-09-23 17:42
Interesting. I wonder if this is a Chromedriver issue as the Chrome team doesn't really focus on Electron compatibility right now. I think it is totally fine to go the CDP route since Electron is Chromium only.

**Comment by lacell75** [comment] 2024-09-27 12:21
I have the same issue with bidi disable. `javascript error: javascript error: __name is not defined` . Works with bidi.
My code below: 

```
 import toastInterceptor from './toasts-interceptor.js'; -> It is a TS file
 await browser.execute(toastInterceptor.start);
```
@goosewobbler Do you have found a workaround?

**Comment by christian-bromann** [comment] 2024-09-27 16:01
@lacell75 mind raising a new issue with a minimal reproducible example please?
