### ISSUE TITLE
Failed to create Appium session

### ISSUE THREAD

**Issue by sam-022** [webdriverio/webdriverio#5569] opened 2020-07-04 23:28 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** [6.0.13]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [14.4.0]
 - **NPM version:** [6.14.5]
 - **Browser name and version:** [Chrome]
 - **Platform name and version:** [Windows 10]

**Config of WebdriverIO**
Appium Config: 
``` 
services: [
        [
            "appium",
            {
                // For options see
                // https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-appium-service
                args: {
                    // ...
                    debugLogSpacing: true,
                    platformName: "android",
                    // ...
                },
                command: "appium",
            },
        ],
    ],
    port: 4723, 

   config.capabilities = [
    {
        // The defaults you need to have in your config
        platformName: "Android",
        browserName: "chrome",
        maxInstances: 1,
        // For W3C the appium capabilities need to have an extension prefix
        // http://appium.io/docs/en/writing-running-appium/caps/
        // This is `appium:` for all Appium Capabilities which can be found here
        "appium:deviceName": "Pixel_2_XL_API_29",
        "appium:platformVersion": "11",
        "appium:orientation": "PORTRAIT",
        // `automationName` will be mandatory, see
        // https://github.com/appium/appium/releases/tag/v1.13.0
        "appium:automationName": "UiAutomator2",
        "appium:newCommandTimeout": 240,
        "goog:chromeOptions": {
            w3c: true,
            // Add this option to prevent the annoying "Welcome"-message
            args: ["--no-first-run"],
        },
    },
```

**Describe the bug**
Not able to create a session with Appium. Getting error `Unable to connect to "http://localhost:4723/", make sure browser driver is running on that address.`

If I run `Appium` instance separately then I get this error: `ERROR webdriver: Error: The URL '/session' did not map to a valid resource`

**To Reproduce**
I'm using the `appium-boilerplate`, no changes made to it other than the `deviceName` and `platformVersion`

**Expected behavior**
Be able to run tests in Android simulator

**Comment by wswebcreation** [comment] 2020-07-05 08:24
@sam-022 

I've updated the `appium-boilerplate` with the latest dependencies, can you try again. I've tried it and it works on my machine. If it doesn't work on your machine please provide the logs and run your test with `logLevel=debug`.

Going to close it for now because it works based on the latest dependencies, but it's still open for conversation

**Closed by wswebcreation** 2020-07-05 08:24 UTC

**Comment by sam-022** [comment] 2020-07-05 14:06
@wswebcreation I pulled the latest changes and did a fresh `npm i`. I'm still seeing the same error. See my logs below:
- [Appium server running separately](https://gist.github.com/sam-022/48611f768af79c85fc01d997c9edd165)
- [Running Appium server with WebdriverIO](https://gist.github.com/sam-022/ae0add47a5cb1891bfafecf74f5d582e)

**Comment by wswebcreation** [comment] 2020-07-06 10:44
@sam-022 

Can you create a reproducible example? I can't seem to find the problem in the logs

**Comment by sam-022** [comment] 2020-07-06 16:39
@wswebcreation I'm using the same boilerplate example, every time I run the test I get this error: `ERROR webdriver: Error: The URL '/session' did not map to a valid resource`
For some reason, it's not able to connect to `/wd/hub`. Do you have any suggestions? Or, any other alternative way to get this running?

**Comment by wswebcreation** [comment] 2020-07-07 06:12
@sam-022 

Strange, do you have a version of Appium already running in the background? The boilerplate starts a session on its own, not using `/wd/hub`.

If you run Appium as a separate service you need to set the basePath as `/`, see also below from https://webdriver.io/blog/2020/03/26/webdriverio-v6-released.html

![image](https://user-images.githubusercontent.com/11979740/86724978-8d989280-c029-11ea-82a2-e63d7d514707.png)


 if you run it as a service you need to stop the current separate appium service, that's why possibly get `connect ECONNREFUSED 127.0.0.1:4723`
