### ISSUE TITLE
buttonDown, moveTo and buttonUp in documentation are deprecated but gives no alternatives

### ISSUE THREAD

**Issue by ArnasAlex** [webdriverio/webdriverio#2240] opened 2017-08-11 10:08 UTC
## Description
While using these commands webdriverio gives deprecation warning. What's the alternative to this? 
As I understand touchPerform only works on mobile. I want to test drawing on canvas on desktop.

## Environment
* WebdriverIO version: 4.8.0

## Logs
```
WARNING: the "moveTo" command will be depcrecated soon. Please use a different command in order to avoid failures in your test after updating WebdriverIO.
WARNING: the "buttonDown" command will be depcrecated soon. Please use a different command in order to avoid failures in your test after updating WebdriverIO.
WARNING: the "moveTo" command will be depcrecated soon. Please use a different command in order to avoid failures in your test after updating WebdriverIO.
WARNING: the "moveTo" command will be depcrecated soon. Please use a different command in order to avoid failures in your test after updating WebdriverIO.
WARNING: the "buttonUp" command will be depcrecated soon. Please use a different command in order to avoid failures in your test after updating WebdriverIO.
```

**Comment by christian-bromann** [comment] 2017-08-11 10:10
Duplicate of #2076

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Closed by christian-bromann** 2017-08-11 10:10 UTC
