### ISSUE TITLE
setValue() throws exception for unknown error: call function result missing 'value'

### ISSUE THREAD

**Issue by Monaspatel** [webdriverio/webdriverio#2635] opened 2018-03-08 18:08 UTC
Hi,

I am using the WebDriverIO latest version 4.12.0 with Selenium-standalone.
Trying to use 
 browser.setValue('.sc-input',"Some Value");
but it throws error of unknown error: call function result missing 'value' (it started coming all sudden and having issues with all text fields)

I did check that ".sc-input" as element is available

**Comment by christian-bromann** [comment] 2018-03-08 18:10
Duplicate of https://github.com/webdriverio/webdriverio/issues/2631

**Closed by christian-bromann** 2018-03-08 18:10 UTC
