### ISSUE TITLE
Getting started examples doesn't work

### ISSUE THREAD

**Issue by evil-shrike** [webdriverio/webdriverio#1723] opened 2016-11-22 16:24 UTC
* `npm init -t`
* `npm install webdriverio --save-dev`
* Go to http://webdriver.io/guide.html and copy sample:
```
var webdriverio = require('webdriverio');
var options = {
    desiredCapabilities: {
        browserName: 'firefox'
    }
};
webdriverio
    .remote(options)
    .init()
    .url('http://www.google.com')
    .getTitle().then(function(title) {
        console.log('Title was: ' + title);
    })
```
* Run: `node test.js`
* Nothing happens (Node executed the script and exited with not output)

I'd expect that the very first example from "getting started" doc page to work. But it doesn't. Just nothing happens :(

Needless to say how discouraging for continuing to learn this tool. 

WebDriverIO version: 4.4.0

**Comment by evil-shrike** [comment] 2016-11-22 16:49
I understand that it's pretty useless moving on to using wdio runner w/o getting wdio to work directly. But I tried it as well. 
Run `wdio config` and generated a sample config:
```
exports.config = {
    specs: [
        './tests/**/*.js'
    ],
    maxInstances: 1,
    capabilities: [{
        maxInstances: 1,
        browserName: 'chrome'
    }],

    sync: true,
    logLevel: 'result',
    coloredLogs: true,
    screenshotPath: './errorShots/',
    baseUrl: 'http://localhost/ajax',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    services: ['selenium-standalone','phantomjs'],
    framework: 'mocha',
    reporters: ['teamcity','concise'],
    mochaOpts: {
        ui: 'bdd'
    },
}
```
* I accepted to install all packages for me (they are in node_modules):
```
    "wdio-concise-reporter": "0.0.3",
    "wdio-mocha-framework": "^0.5.4",
    "wdio-phantomjs-service": "^0.2.2",
    "wdio-selenium-standalone-service": "0.0.7",
    "wdio-teamcity-reporter": "^1.1.0",
    "webdriverio": "^4.4.0"
```
* run wdio:
```
node node_modules/webdriverio/bin/wdio wdio.conf.js
```

and got the error:
```
D:\Work\ui-tests.wdio>node node_modules/webdriverio/bin/wdio wdio.conf.js 
A service failed in the 'onPrepare' hook
Error: Selenium exited before it could start
    at ChildProcess.errorIfNeverStarted (D:\Work\ui-tests.wdio\node_modules\selenium-standalone\lib\start.js:144:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

Continue...
D:\Work\ui-tests.wdio\node_modules\webdriverio\build\lib\utils\BaseReporter.js:336
                        throw _iteratorError;
                        ^

TypeError: Cannot read property 'failed' of undefined
    at ConciseReporter.prepareConsole (D:\Work\ui-tests.wdio\node_modules\wdio-concise-reporter\build\reporter.js:86:27)
    at ConciseReporter.<anonymous> (D:\Work\ui-tests.wdio\node_modules\wdio-concise-reporter\build\reporter.js:58:29)
    at emitOne (events.js:96:13)
    at ConciseReporter.emit (events.js:188:7)
    at BaseReporter.handleEvent (D:\Work\ui-tests.wdio\node_modules\webdriverio\build\lib\utils\BaseReporter.js:324:35)
    at Launcher.endHandler (D:\Work\ui-tests.wdio\node_modules\webdriverio\build\lib\launcher.js:618:28)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

It's hard to understand what is going on. I have no 'onPrepare' hook which it complains for.
I indeed had selenium-server-standalone running before run wdio (`selenium-standalone start` - https://www.npmjs.com/package/selenium-standalone). I also tried running jar directly.

BTW: it's very unclear why do we need to run `java -jar selenium-server-standalone-3.0.1.jar` directly if we have `selenium-standalone` service. Shouldn't it run on automatically?
Anyway it isn't even touched by wdio. 

BTW2: also it's unclear why do you require running selenium server at all. Why not just run a WebDriver? If WDIO is WebDriver client lib then it should work with any WD-server, doesn't it? I have some experience with Intern and their it's possible to choose what to run: selenium-standalone or webdrivers (chromedriver.exe, IEDriverServer.exe) directly.

**Comment by evil-shrike** [comment] 2016-11-22 18:06
I tried running samples in the repo. Cloned the repo and built (BTW `npm install` and `grunt build` fails on Windows). 
Run: `node webdriverio.addCommand.js` in examples\commands folder. 
Nothing.

**Comment by christian-bromann** [comment] 2016-11-23 15:04
@evil-shrike 

> I'd expect that the very first example from "getting started" doc page to work. But it doesn't. Just nothing happens :(

You need to start a selenium server as you can see in step 3.

as you can see from the logs:

```js
Error: Selenium exited before it could start
```

So probably you had a selenium server running and started another server on the same port which will fail of course


> Shouldn't it run on automatically?

yes

> Why not just run a WebDriver? If WDIO is WebDriver client lib then it should work with any WD-server, doesn't it?

No!! A server is required that excepts the http calls to automate the browser.

> I have some experience with Intern and their it's possible to choose what to run: selenium-standalone or webdrivers (chromedriver.exe, IEDriverServer.exe) directly.

WebdriverIO is a selenium runner and it is out of scope on what Selenium infrastructure you are running your tests on. We have couple of service that help you to start a selenium server out of the box though.

The goal of the getting started guide is to give a high level introduction to WebdriverIO. It certainly doesn't cover all aspects of Selenium testing. It is in the nature of all getting started guides that your first try doesn't work out. Please don't be discouraged by that (#neverGiveUp). Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have any questions getting started. We have a large community that can help you out.

**Closed by christian-bromann** 2016-11-23 15:04 UTC

**Comment by evil-shrike** [comment] 2016-11-23 17:19
@christian-bromann thanks for your answers. 

Unfortunately it's unclear for me what's wrong with the simplest setup.

# direct execution
* If I run `node test1.js`: nothing happens. Should WDIO start webdriver? Probably no. But then wdio should report some error. But it just exits. 
* If I run `node test1.js` *and* run selenium-server-standalone - I have absolutely the same result, nodejs just exits

where `test1.js` is:
```
var webdriverio = require('webdriverio');
var options = { desiredCapabilities: { browserName: 'chrome' } };
webdriverio
    .remote(options)
    .init()
    .url('http://www.google.com')
    .title().then(function (title) {
        console.log('Title was: ' + title.value);
    })
.end();
```

# execution via runner 
If I run tests via wdio runner with the config from my second post above then I'm getting "A service failed in the 'onPrepare' hook / Error: Selenium exited before it could start" error.   
> So probably you had a selenium server running

it'd be too easy :). No, I do not have any Selenium running.

After the stacktrace it reports in console some HTML with "Credentials are missing" error:
```html
ERROR: <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Access Denied (authentication_failed)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
Your credentials could not be authenticated: "Credentials are missing.". You will not be permitted access until your credentials can be verified.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
This is typically caused by an incorrect username and/or password, but could also be caused by network problems.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>
For assistance, contact your network support team.
</FONT>
</TD></TR>
</TABLE>
</blockquote>
</FONT>
</BODY></HTML>
```
But the test just open google.com (I tried to open a local site). I have no idea what (and who) wants my credentials :(
Test itself is almost the same as before only wrapped in mocha:
```js
describe('test', function() {
    it('open google', function() {
        browser.url('https://google.com');
        var title = browser.getTitle();
        console.log('Title is: ' + title);
    });
});
```


> It is in the nature of all getting started guides that your first try doesn't work out

I'm sorry, but I totally disagree.   
A "getting stated" guide should just work. Without digging into source code and debugging. 


>> Why not just run a WebDriver? If WDIO is WebDriver client lib then it should work with any WD-server, doesn't it?

> No!! A server is required that excepts the http calls to automate the browser.

Any WebDriver (chromedriver.exe, IEDriverServer.exe and so on) actually *is* a server already.  They accept http requests via WD-protocol and control their browsers. So they are web-driver-servers actually

**Comment by christian-bromann** [comment] 2016-11-28 14:45
> direct execution

if you run WebdriverIO as standalone package you need to have a Selenium server or browser driver running. It doesn't do that for you.

> No, I do not have any Selenium running.

Then it can't run the server due to a different issue. If you would post the whole error message I could see why.

> I'd suspect that the error during execution via WDIO runner is because of our corporate proxy.

Yeah, this sounds like the root cause of the issue. Not sure how you need to start the selenium server so that you don't get this error tho.

> A "getting stated" guide should just work. Without digging into source code and debugging.

Right and this guide will also just work. However if you can't run step 3 successfully due to your corporate proxy the example will fail.

> They accept http requests via WD-protocol and control their browsers. So they are web-driver-servers actually

That is right! And as along as you start them before running a script, WebdriverIO will be able to connect with these. It is out of scope for this project to start and tear down the server for you. There are projects like [selenium-standalone](https://www.npmjs.com/package/selenium-standalone) that can doe these jobs.

**Comment by evil-shrike** [comment] 2016-11-29 13:40
>>    direct execution

> if you run WebdriverIO as standalone package you need to have a Selenium server or browser driver running. It doesn't do that for you.

Sure I have. But when the simplest test is being run under node directly *without* any WD running WDIO doesn't report any error. It just exits. I believe it's incorrect behavior. If WDIO tries to connect to some port and nobody responds why does it not report an error? 
I tried run a simple direct test on my home machine and it worked. But on my work machine it doesn't - WDIO silently exits (`node test.js` I mean), regardless of existence of WD running.

BTW the issue take place even if the test accesses a local site.


As for running under wdio runner:

>>  No, I do not have any Selenium running.

> Then it can't run the server due to a different issue. If you would post the whole error message I could see why.

You can find it in the first post above.

>> I'd suspect that the error during execution via WDIO runner is because of our corporate proxy.

> Yeah, this sounds like the root cause of the issue. Not sure how you need to start the selenium server so that you don't get this error tho.

To make it clear WDIO should report where it tries to access to (address/port) and report an error if it cannot.
Another reason for the failure can be the fact that my machine has several IP addresses (some virtual networks)...

**Comment by mikkqu** [comment] 2017-09-09 10:35
Same issues here, I expected to see some error but 'getting started example' just silently exits if there's no Selenium running.

**Comment by willmacdonald** [comment] 2017-11-21 12:07
If you are on a Mac check the following:
Sys Prefs -> Network -> Advanced -> Proxies -> Uncheck 'Auto Proxy Discovery'

**Comment by inspiraller** [comment] 2018-03-21 03:05
I have had similar problems and while it isn't the problem with webdriverio, there isn't a nice easy to use alternative boilerplate solution on the webdriverio site that caters for this common problem. So i have hunted around, experimented, and built a boilerplate example that just works. This is using cucumber-boilerplate but theoreticall you could use this appeoach with just the default webderiverio guide.

I developed a workaround by downloading the selenium server java file and chromedriver manually, using gulp plus node run cmd package to run dual cmds, updating some arguments in capabalities, and removing the reference in wdio.conf which refers to services. Here is my solution: https://github.com/inspiraller/cucumber-boilerplate-behind-corporate-network
