### ISSUE TITLE
$('.some.elem').setValue() throws error on edge over saucelabs

### ISSUE THREAD

**Issue by pmerwin** [webdriverio/webdriverio#3844] opened 2019-04-11 22:53 UTC
When using .setValiue() on Edge over sauce, wdio throws java null pointer excpetion .

 ERROR webdriver: Request failed due to Error: java.lang.NullPointerException

**Environment (please complete the following information):**
 - **WebdriverIO version:** [5.7.12]
 - **Mode:** [ WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [8.10]
 - **NPM version:** [6.5.0]
 - **Browser name and version:** [ie 11]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/sauce]

**Config of WebdriverIO**
```
user: config.saucelabs.user,
    key: config.saucelabs.key,
    hostname: 'ondemand.saucelabs.com',
    maxInstances: 3,
    capabilities: [
        {
            browserName: 'MicrosoftEdge',
            platformVersion: 'Windows 10',
            browserVersion: 'latest',
            // screenResolution: '1280x960',
        },
    ],
    mochaOpts: {
        ui: 'bdd',
        timeout: 120000,
        bail: true
    },
    services: ['sauce'],
    reporters: ['spec'],
    coloredLogs: true,
    deprecationWarnings: false
});
```

**Describe the bug**
$('.some.elem').setValue() throws error on edge over saucelabs.
 ERROR webdriver: Request failed due to Error: java.lang.NullPointerException
2019-04-11T22:44:31.776Z INFO webdriver: RESULT { ELEMENT: '1' }
2019-04-11T22:44:31.786Z INFO webdriver: COMMAND elementClear("1")
2019-04-11T22:44:31.786Z INFO webdriver: [POST] https://ondemand.saucelabs.com:443/wd/hub/session/1133bcb1338549a29267df16e5ee0ec0/element/1/clear
2019-04-11T22:44:32.172Z INFO webdriver: COMMAND elementSendKeys("1", "atesting+sd23d21@cbtnuggets.com")
2019-04-11T22:44:32.173Z INFO webdriver: [POST] https://ondemand.saucelabs.com:443/wd/hub/session/1133bcb1338549a29267df16e5ee0ec0/element/1/value
2019-04-11T22:44:32.173Z INFO webdriver: DATA { text: 'atesting+sd23d21@cbtnuggets.com' }
2019-04-11T22:44:32.498Z WARN webdriver: Request failed due to java.lang.NullPointerException

**To Reproduce**
Run a spec that uses $('.some-elem').setValue();

```
 it.only('should not throw error', function () {
        $('#username').waitForDisplayed();
        $('#username').setValue(user);
    });
```

[Include code or an example repository that can easily be set up]

**Expected behavior**
The method should  setValue correctly

**Log**
https://gist.github.com/pmerwin/95cd8a745aee4fe9e9de77d81aa5d163

sauce job:
https://app.saucelabs.com/tests/1133bcb1338549a29267df16e5ee0ec0

**Comment by christian-bromann** [comment] 2019-04-12 09:04
Duplicate of #3834

**Closed by christian-bromann** 2019-04-12 09:04 UTC
Labels: Bug🐛

**Comment by Ranjithsamalla** [comment] 2020-09-28 05:45
![image](https://user-images.githubusercontent.com/37171202/94394784-c4d79500-017b-11eb-8409-87ca915fb34d.png)
when I use setValue getting java.lang.NullPointerException could you please help one ?
