### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by StephenABoyd** [webdriverio/webdriverio#3877] opened 2019-04-23 21:52 UTC
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.7.14
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.9.0
 - **NPM version:** 6.2.0
 - **Browser name and version:** Chrome 74
 - **Platform name and version:** Windows NT 10
 - **Additional wdio packages used (if applicable):** 
@wdio/junit-reporter, 
@wdio/cli, 
@wdio/mocha-framework, 
@wdio/local-runner, 
@wdio/spec-reporter, 
@wdio/sync

**Describe the bug**
During my CI build I'm seeing this happen. The build continues as normal after this
```
(node:4488) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit
(node:4488) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpipe listeners added. Use emitter.setMaxListeners() to increase limit
(node:4488) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit
(node:4488) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:4488) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
(node:4488) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit
(node:4488) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpipe listeners added. Use emitter.setMaxListeners() to increase limit
(node:4488) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit
(node:4488) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:4488) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
(node:4488) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit
```

**To Reproduce**
Not really sure, I'm only seeing it in my CI pipeline.

**Comment by mgrybyk** [comment] 2019-04-24 05:57
Some more logging and steps to reproduce in CI would be really helpful

**Comment by CrispusDH** [comment] 2019-04-24 08:43
I also see this issue when run locally:
```js
RUNNING  0-10 in chrome - /dist/test/games/.../two-lines.js
... 3 pending test suites

Test Suites:	 10 passed, 14 total (71% completed)
Time:		 🕛  151.67s
(node:35212) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpipe listeners added. Use emitter.setMaxListeners() to increase limit
(node:35212) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit
(node:35212) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:35212) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
(node:35212) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit
(node:35212) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpipe listeners added. Use emitter.setMaxListeners() to increase limit
(node:35212) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit

RUNNING  0-10 in chrome - /dist/test/games/.../two-lines.js
```
it always happens after 10 tests were done. I'm not sure why. In `'trace'` logLevel mode these lines don't appear.

I see such `WARN` in trace mode.
```js
[0-1] 2019-04-24T08:34:40.977Z WARN webdriver: Request failed due to unknown error: Element <div class="home-button game-...">123</div> is not clickable
 at point (205, 591). Other element would receive the click: <img src="/mobile/img/splash0.jpg">
   (Session info: chrome=74.0.3729.108)
   (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.14.2 x86_64)
[0-1] 2019-04-24T08:34:41.010Z WARN webdriver: Request failed due to unknown error: Element <div class="home-button game-...">123</div> is not clickable
 at point (205, 591). Other element would receive the click: <img src="/mobile/img/splash0.jpg">
   (Session info: chrome=74.0.3729.108)
   (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.14.2 x86_64)
[0-2] 2019-04-24T08:34:47.443Z WARN webdriver: Request failed due to java.io.IOException: Error writing to server
[0-4] 2019-04-24T08:35:20.871Z WARN webdriver: Request failed due to unknown error: Element <div class="home-button game-...">123</div> is not clickable
 at point (205, 591). Other element would receive the click: <img src="/mobile/img/splash0.jpg">
   (Session info: chrome=74.0.3729.108)
   (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.14.2 x86_64)
[0-5] 2019-04-24T08:35:38.486Z WARN webdriver: Request failed due to unknown error: Element <div class="home-button game-...">123</div> is not clickable
 at point (205, 591). Other element would receive the click: <img src="/mobile/img/splash0.jpg">
   (Session info: chrome=74.0.3729.108)
   (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.14.2 x86_64)
[0-6] 2019-04-24T08:35:47.854Z WARN webdriver: Request failed due to java.io.IOException: Error writing to server
[0-6] 2019-04-24T08:35:55.782Z WARN webdriver: Request failed due to unknown error: Element <div class="home-button game-...">123</div> is not clickable
 at point (205, 591). Other element would receive the click: <img src="/mobile/img/splash0.jpg">
   (Session info: chrome=74.0.3729.108)
   (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.14.2 x86_64)
[0-7] 2019-04-24T08:36:04.932Z WARN webdriver: Request failed due to java.io.IOException: Error writing to server
[0-8] 2019-04-24T08:36:25.556Z WARN webdriver: Request failed due to java.io.IOException: Error writing to server
[0-9] 2019-04-24T08:36:43.429Z WARN webdriver: Request failed due to java.net.SocketException: Connection reset by peer (connect failed)
[0-10] 2019-04-24T08:37:00.623Z WARN webdriver: Request failed due to java.io.IOException: Error writing to server
[0-12] 2019-04-24T08:37:37.300Z WARN webdriver: Request failed due to unknown error: Element <div class="nav-icon">...</div> is not clickable at point (
22, 22). Other element would receive the click: <img src="/mobile/img/splash0.jpg">
```

**Comment by mgrybyk** [comment] 2019-04-24 10:39
This is happening because we are not doing pipe multiple times
https://github.com/webdriverio/webdriverio/blob/cdb285697ef6b9537dffbf4e54f18db3282a1a73/packages/wdio-local-runner/src/worker.js#L75

**Comment by mgrybyk** [comment] 2019-04-24 13:19
Fixing

**Comment by goatsy** [comment] 2019-07-01 11:45
With every run we have these messages in the log.

`(node:10728) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 3 error listeners added. Use emitter.setMaxListeners() to increase limit`

We use 5.10.9

**Comment by mgrybyk** [comment] 2019-07-01 12:32
@goatsy please provide with reproducible example or steps to reproduce.

**Comment by goatsy** [comment] 2019-07-18 14:37
I have now a small example with which I can reproduce it

**Dependencies:**
`  "dependencies": {
    "@wdio/cli": "^5.11.6",
    "@wdio/dot-reporter": "^5.11.0",
    "@wdio/local-runner": "^5.11.6",
    "@wdio/mocha-framework": "^5.11.0",
    "@wdio/selenium-standalone-service": "^5.11.2",
    "@wdio/spec-reporter": "^5.11.6",
    "@wdio/sync": "^5.11.0"
  }`

**Two .spec files:** 

basic.js
basic2.js

Both have the same content

`const assert = require('assert');

describe('webdriver.io page', () => {
    it('should have the right title', () => {
        browser.url('https://webdriver.io');
        const title = browser.getTitle();
        assert.strictEqual(title, 'WebdriverIO · Next-gen WebDriver test framework for Node.js');
    });
});`


**wdio.conf.js**

capabilities: 

maxInstances: 20,
    capabilities: [
        {
            browserName: 'chrome',
        },
        {
            browserName: 'chrome',
        },
        {
            browserName: 'chrome',
        },
        {
            browserName: 'chrome',
        },
        {
            browserName: 'chrome',
        },
        {
            browserName: 'chrome',
        }],


    runner: 'local',




Whenever I run the tests I get the following output

`./node_modules/.bin/wdio wdio.conf.js`



`/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js test --scripts-prepend-node-path=auto

> wdio_mvp@1.0.0 test /Users/mzehetmeier/workspace/wdio_mvp
> wdio wdio.conf.js


Execution of 12 spec files started at 2019-07-18T14:34:15.750Z

[0-0] RUNNING in chrome - /test/specs/basic.js
[1-0] RUNNING in chrome - /test/specs/basic.js
[2-0] RUNNING in chrome - /test/specs/basic.js
[3-0] RUNNING in chrome - /test/specs/basic.js
[4-0] RUNNING in chrome - /test/specs/basic.js
[5-0] RUNNING in chrome - /test/specs/basic.js
[0-1] RUNNING in chrome - /test/specs/basic2.js
[1-1] RUNNING in chrome - /test/specs/basic2.js
[2-1] RUNNING in chrome - /test/specs/basic2.js
[3-1] RUNNING in chrome - /test/specs/basic2.js
[4-1] RUNNING in chrome - /test/specs/basic2.js
[5-1] RUNNING in chrome - /test/specs/basic2.js
(node:93378) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:93378) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit
(node:93378) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit
[5-0] PASSED in chrome - /test/specs/basic.js
[4-0] PASSED in chrome - /test/specs/basic.js
[1-0] PASSED in chrome - /test/specs/basic.js
[5-1] PASSED in chrome - /test/specs/basic2.js
[2-1] PASSED in chrome - /test/specs/basic2.js
[0-0] PASSED in chrome - /test/specs/basic.js
[4-1] PASSED in chrome - /test/specs/basic2.js
[3-0] PASSED in chrome - /test/specs/basic.js
[0-1] PASSED in chrome - /test/specs/basic2.js
[3-1] PASSED in chrome - /test/specs/basic2.js
[2-0] PASSED in chrome - /test/specs/basic.js
[1-1] PASSED in chrome - /test/specs/basic2.js
`

**Comment by christian-bromann** [comment] 2019-07-18 14:47
I've seen these too, reopening

**Comment by WillBrock** [comment] 2019-07-18 16:08
I've noticed this sometimes as well when we run over 600 spec files on jenkins with maxInstances set to 15 on chrome.

**Comment by mgrybyk** [comment] 2019-07-19 20:15
@goatsy thanks a lot for a reproducible example. 
Closing this issue according to https://github.com/webdriverio/webdriverio/pull/4223

**Closed by mgrybyk** 2019-07-19 20:15 UTC
Labels: Bug🐛, Needs Investigation, help wanted

**Comment by Slurpgoose** [comment] 2020-10-29 23:59
@mgrybyk your solution in #4223 helped me fix this warning in a project I'm working on. Thank you!

**Comment by dkuznetsov21** [comment] 2023-08-16 09:17
@mgrybyk Hello, i have the same problem on wdio 8.

(node:215) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 19 unpipe listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit

and then error Command failed with exit code 137.


can you please check

**Comment by dkuznetsov21** [comment] 2023-08-17 08:34
@christian-bromann 

i create a new project by npm init wdio .

then i add remote server `moon` to my config 
```
 hostname: mylink,
  port: myport,
  path: mypath,
```

and just add .circleci folder with the config file to run this branch on my circleci machine
and then I get 

yarn run v1.22.19
$ wdio run ./wdio.conf.js

Execution of 1 workers started at 2023-08-17T08:21:10.338Z

```
2023-08-17T08:21:10.369Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-08-17T08:21:10.373Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-08-17T08:21:10.374Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.js
(node:223) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 19 unpipe listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(Use node --trace-warnings ... to show where the warning was created)
(node:223) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 19 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:223) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 19 close listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:223) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 19 finish listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:223) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 19 unpipe listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:223) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 19 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:223) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 19 close listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:223) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 19 finish listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
[0-0] 2023-08-17T08:21:11.414Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - file:///test/specs/test.e2e.js
[0-0] 2023-08-17T08:21:11.513Z INFO webdriver: Initiate new session using the WebDriver protocol

```




circle ci 
cimg/node:18.12.1:
and 
cimg/node:19.7.0

try both

**Comment by deyvisPedrosa** [comment] 2023-08-17 12:04
#### When using node --trace-waring flag:

```
> ui-automation@2.0.0 vendorDocs
> npx cross-env NODE_OPTIONS=--trace-warnings wdio run wdio.conf.js --suite vendorDocs


Execution of 2 workers started at 2023-08-14T21:21:02.628Z

(node:1469) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 19 unpipe listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:588:17)
    at WriteStream.addListener (node:events:606:10)
    at Readable.on (node:internal/streams/readable:887:35)
    at Readable.pipe (node:internal/streams/readable:692:8)
    at file:///home/circleci/project/node_modules/@wdio/local-runner/build/worker.js:15:14
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
(node:1469) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 19 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:588:17)
    at WriteStream.prependListener (node:events:620:14)
    at prependListener (node:internal/streams/legacy:100:20)
    at Readable.pipe (node:internal/streams/readable:791:3)
    at file:///home/circleci/project/node_modules/@wdio/local-runner/build/worker.js:15:14
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
(node:1469) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 19 close listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:588:17)
    at WriteStream.addListener (node:events:606:10)
    at Readable.on (node:internal/streams/readable:887:35)
    at WriteStream.once (node:events:650:8)
    at Readable.pipe (node:internal/streams/readable:798:8)
    at file:///home/circleci/project/node_modules/@wdio/local-runner/build/worker.js:15:14
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
(node:1469) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 19 finish listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:588:17)
    at WriteStream.addListener (node:events:606:10)
    at Readable.on (node:internal/streams/readable:887:35)
    at WriteStream.once (node:events:650:8)
    at Readable.pipe (node:internal/streams/readable:804:8)
    at file:///home/circleci/project/node_modules/@wdio/local-runner/build/worker.js:15:14
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
(node:1469) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 19 unpipe listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:588:17)
    at WriteStream.addListener (node:events:606:10)
    at Readable.on (node:internal/streams/readable:887:35)
    at Readable.pipe (node:internal/streams/readable:692:8)
    at file:///home/circleci/project/node_modules/@wdio/local-runner/build/worker.js:16:14
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
(node:1469) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 19 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:588:17)
    at WriteStream.prependListener (node:events:620:14)
    at prependListener (node:internal/streams/legacy:100:20)
    at Readable.pipe (node:internal/streams/readable:791:3)
    at file:///home/circleci/project/node_modules/@wdio/local-runner/build/worker.js:16:14
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
(node:1469) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 19 close listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:588:17)
    at WriteStream.addListener (node:events:606:10)
    at Readable.on (node:internal/streams/readable:887:35)
    at WriteStream.once (node:events:650:8)
    at Readable.pipe (node:internal/streams/readable:798:8)
    at file:///home/circleci/project/node_modules/@wdio/local-runner/build/worker.js:16:14
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
(node:1469) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 19 finish listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:588:17)
    at WriteStream.addListener (node:events:606:10)
    at Readable.on (node:internal/streams/readable:887:35)
    at WriteStream.once (node:events:650:8)
    at Readable.pipe (node:internal/streams/readable:804:8)
    at file:///home/circleci/project/node_modules/@wdio/local-runner/build/worker.js:16:14
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

**Comment by deyvisPedrosa** [comment] 2023-08-17 12:10
Those logs are from CircleCI. I can't replicate that running locally, but I'm getting that warning for all the specs in CIrcleCI.

#### (Mocha framework) Capabilities:
```
  capabilities: [{
    // capabilities for local browser web tests
    maxInstances: 1,
    browserName: 'chrome', // or "firefox", "microsoftedge", "safari"
    browserVersion: `${process.env.CHROME_DRIVER}`,
    acceptInsecureCerts: true,
    'goog:chromeOptions': {
      // args: ['--start-maximized', '--enable-automation']
      args: [
        '--no-sandbox',
        '--disable-infobars',
        '--disable-extensions',
        '--disable-dev-shm-usage',
        '--enable-automation',
        '115.0.5790.170',
        '--window-size=1920,1080',
        '--disable-gpu'
      ],
      // Sets up the directory where the downloaded files will be stored.
      prefs: {
        'download.default_directory': global.downloadDir,
        'profile.default_content_setting_values.automatic_downloads': 1
      }
    }
  }],
```
`package.json`:
```
  "devDependencies": {
    "@babel/register": "^7.22.5",
    "@eslint/eslintrc": "^2.1.2",
    "@eslint/js": "^8.47.0",
    "@wdio/allure-reporter": "^8.15.0",
    "@wdio/cli": "^8.15.5",
    "@wdio/local-runner": "^8.15.4",
    "@wdio/mocha-framework": "^8.15.4",
    "@wdio/spec-reporter": "^8.15.0",
    "chai": "^4.3.7",
    "cross-env": "^7.0.3",
    "eslint": "^8.47.0",
    "eslint-plugin-import": "^2.28.0",
    "eslint-plugin-wdio": "^8.8.7",
    "eslint-plugin-yml": "^1.8.0",
    "mocha-multi": "^1.1.7"
  },
  "dependencies": {
    "@faker-js/faker": "^8.0.2",
    "allure-js-commons": "^2.0.0-beta.19",
    "allure-mocha": "^2.0.0-beta.19",
    "authenticator": "^1.1.5",
    "axios": "^1.4.0",
    "camelize": "^1.0.1",
    "dotenv": "^16.3.1",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-plugin-simple-import-sort": "^10.0.0",
    "moment": "^2.29.4",
    "pdf-parse": "^1.1.1"
  }
```

**Comment by christian-bromann** [comment] 2023-08-28 05:17
@deyvisPedrosa @dkuznetsov21 thanks, do you think there is a chance to have this replicated locally or on a Github repository. I don't use CircleCI anywhere which makes it hard to debug this.

**Comment by mpermperpisang** [comment] 2024-07-15 04:00
got same error in local also jenkins
<img width="332" alt="Screenshot 2024-07-15 at 10 57 42" src="https://github.com/user-attachments/assets/e124ee71-fdd3-4ee1-b51e-92f0bbeb8b3e">

when i updated nodejs to >= v18 and appium-service to ^8.39.0, the issue is happening
before i'm using nodejs v16 and appium-service ^7.16.6 the issue not happened
please help and thanks

**Comment by SerhiiMaksymiv** [comment] 2025-05-18 09:56
having the same issue on 
```
❯ node -v
v20.18.3
```
```
    "@wdio/allure-reporter": "^9.14.0",
    "@wdio/browser-runner": "^9.14.0",
    "@wdio/cli": "^8.38.1",
    "@wdio/cucumber-framework": "^9.14.0",
    "@wdio/dot-reporter": "^9.14.0",
    "@wdio/junit-reporter": "^8.32.2",
    "@wdio/local-runner": "^9.14.0",
    "@wdio/shared-store-service": "^9.12.3",
    "@wdio/spec-reporter": "^8.38.0",
    "@wdio/visual-service": "^8.0.2",
```
```
[0-0] (node:28860) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 result listeners added to [EventEmitter]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
[0-0] (Use `node --trace-warnings ...` to show where the warning was created)
```
