### ISSUE TITLE
[Cucumber JSON Reporter] Failed launching test session: TypeError: args[0].endsWith is not a function

### ISSUE THREAD

**Issue by tlee-fm** [webdriverio/webdriverio#4539] opened 2019-09-26 20:52 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.0
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15.3
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome 77.0.3865.90
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/cucumber-framework, @wdio/local-runner, @wdio/sync, and wdio-cucumberjs-json-reporter

**Config of WebdriverIO**
```
{
  capabilities: [
    {
      browserName: "chrome"
    }
  ],
  connectionRetryCount: 3,
  connectionRetryTimeout: 90000,
  cucumberOpts: {
    backtrace: false,
    colors: true,
    compiler: [],
    dryRun: false,
    failFast: false,
    format: ["pretty"],
    ignoreUndefinedDefinitions: false,
    profile: [],
    require: ["steps.js"],
    requireModule: ["@babel/register"],
    snippets: true,
    source: true,
    strict: false,
    tags: [],
    timeout: 60000
  },
  framework: "cucumber",
  hostname: "localhost",
  logLevel: "trace",
  maxInstances: 1,
  outputDir: ".",
  path: "/wd/hub",
  port: 4444,
  reporters: ["cucumberjs-json"],
  runner: "local",
  specs: ["*.feature"],
  waitforTimeout: 10000
};
```

**Describe the bug**
Whenever I try to add in `reporters: ["cucumberjs-json"]` into the `wdio.config.js` file and run the WDIO test runner, the feature files never execute. The WDIO Testrunner exits and fails immediately without outputting the Cucumber JSON Reporter results. Logs are shown below. 

**To Reproduce**
[Gist Code](https://gist.github.com/tlee-fm/97ba6e935378054fbe8587df7c22fc43)
1) Download Zip file of Gist Code above.
2) `npm install`
3) `npm run startSelenium` in one terminal
4) `npm test` in another terminal
5) The terminal that ran `npm test` will output `Running` and then `Failed` without any Cucumber JSON Reporter results. 

**Expected behavior**
The WDIO Testrunner should successfully run all feature files and output the Cucumber JSON Reporter results.

**Log**
```
Feature: Login

	Scenario: Login Feature
		Given user logs in`
Run worker command: run
init remote session
InitiRunner 0-0 finished with exit code 1
rotocol
[POST] http://localhost:4444/wd/hub/session
DATA { capabilities:
   { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'chrome' } }
The 'jsonFolder' was not set, it has been set to the default '.tmp/json/'
The 'language' was not set, it has been set to the default 'en'
Failed launching test session: TypeError: args[0].endsWith is not a function
    at Object.values.filter.x (C:\amtm_dev\d6-amtm-ui-e2e-tests\node_modules\webdriver\node_modules\@wdio\logger\build\node.js:63:62)
    at Array.filter (<anonymous>)
    at Logger.args [as error] (C:\amtm_dev\d6-amtm-ui-e2e-tests\node_modules\webdriver\node_modules\@wdio\logger\build\node.js:63:42)
    at Runner.run (C:\amtm_dev\d6-amtm-ui-e2e-tests\node_modules\@wdio\runner\build\index.js:129:11)
```

**Comment by wswebcreation** [comment] 2019-09-27 06:35
Hi @tlee-fm 

I've checked your code and I based on the provided example I got compilation errors, it was missing the proper Babel setup and I got Cucumber syntax errors due to adding a not used argument in the given step.

After changing that it worked as expected. Are you sure you are on the latest versions of everything?

Going to close it for now because based on the example provided (and the made adjustments) it's working

**Closed by wswebcreation** 2019-09-27 06:35 UTC

**Comment by tlee-fm** [comment] 2019-09-27 12:52
@wswebcreation Thanks for reproducing! Could you create a gist of the adjustments you made? I'll try installing the dependencies again from a clean slate in the meantime.

**Comment by tratch** [comment] 2019-10-01 17:28
I have the same error
```
Failed launching test session: TypeError: args[0].endsWith is not a function
```
Unrelated to `wdio-cucumberjs-json-reporter`

**Comment by mgrybyk** [comment] 2019-10-01 18:07
Please provide with steps to reproduce

**Comment by Lazar-Adrian** [comment] 2019-10-02 08:20
In my case it was solved after upgrading all wdio related packages to the latest version.
Using Typescript and Mocha.

**Comment by johnnymo87** [comment] 2019-11-15 22:07
I've got this problem too, unrelated to cucumber or typescript. I'm triggering it with just a syntax error. Here's my full stack trace:
```
ERROR @wdio/local-runner: Failed launching test session: TypeError: args[0].endsWith is not a function
    at Object.values.filter.x (/testeng-webdriverio/node_modules/@wdio/sync/node_modules/@wdio/logger/build/node.js:63:62)
    at Array.filter (<anonymous>)
    at Logger.args [as error] (/testeng-webdriverio/node_modules/@wdio/sync/node_modules/@wdio/logger/build/node.js:63:42)
    at Runner.run (/testeng-webdriverio/node_modules/@wdio/runner/build/index.js:129:11)
```

The origin of this stack trace is `index.js` in `@wdio/runner` here:
```js
try {
  failures = await this.framework.run()
  await this._fetchDriverLogs(this.config, caps.excludeDriverLogs)
} catch (e) {
  log.error(e)
  this.emit('error', e)
  failures = 1
}
```
It's catching an error from my babel compiler, and calling `log.error(e)` with it.

Like @anton-bot says, the next item in the stack trace points to `node.js` in `@wdio/logger`:
```js
const match = Object.values(matches).filter(x => args[0].endsWith(`: ${x}`))[0];
```
because it assumes `args[0]` is a string, but in my case it's an object.

This is what `args` is for me:
```
[ { SyntaxError: /testeng-webdriverio/app/tests/ui/regression/hcm/profile/profile.test.js: Unexpected token, expected "," (37:31)

       it('C228352: Verify that clicking on My Profile link will redirect user to correspondent page ', function() {
         (
         reporter.severity('normal');
                                    ^
         reporter.feature('Profile');
         reporter.addTRLabel('TC - C228352');
      at Parser.raise (/testeng-webdriverio/node_modules/@babel/parser/lib/index.js:6325:17)
      at Parser.unexpected (/testeng-webdriverio/node_modules/@babel/parser/lib/index.js:7642:16)
      at Parser.expect (/testeng-webdriverio/node_modules/@babel/parser/lib/index.js:7628:28)
      at Parser.parseParenAndDistinguishExpression (/testeng-webdriverio/node_modules/@babel/parser/lib/index.js:8962:14)
      at Parser.parseExprAtom (/testeng-webdriverio/node_modules/@babel/parser/lib/index.js:8762:21)
      at Parser.parseExprSubscripts (/testeng-webdriverio/node_modules/@babel/parser/lib/index.js:8412:23)
      at Parser.parseMaybeUnary (/testeng-webdriverio/node_modules/@babel/parser/lib/index.js:8392:21)
      at Parser.parseExprOps (/testeng-webdriverio/node_modules/@babel/parser/lib/index.js:8267:23)
      at Parser.parseMaybeConditional (/testeng-webdriverio/node_modules/@babel/parser/lib/index.js:8240:23)
      at Parser.parseMaybeAssign (/testeng-webdriverio/node_modules/@babel/parser/lib/index.js:8187:21)
    pos: 1520,
    loc: Position { line: 37, column: 31 },
    code: 'BABEL_PARSE_ERROR' } ]
```

So I'm thinking we should either change `@wdio/logger` to handle `args` not being a string, or we should change `@wdio/runner` to somehow differently log this kind error. The change to `@wdio/logger` seems like something I could PR, but I'm not sure if it's the right approach. @mgrybyk what do you think?

**Comment by mgrybyk** [comment] 2019-11-15 23:18
I don't mind adding type check before endsWith in logger. Will it resolve your issue? If so feel free to raise a PR.

**Comment by johnnymo87** [comment] 2019-11-19 17:35
@mgrybyk I've opened [a PR](https://github.com/webdriverio/webdriverio/pull/4785) with a test that reproduces the bug. However, I've got a question about how to better test this. Could you take a look at my PR and comment there what you think? Thank you.
