### ISSUE TITLE
Create a flag on commands to only interact with visible elements

### ISSUE THREAD

**Issue by vrundbaken** [webdriverio/webdriverio#1069] opened 2016-02-03 03:54 UTC
The way the codebase works that I am testing there are often elements in the dom that are disabled/hidden instead of destroyed. This can make it very hard to select the correct visible element without making overly complex brittle selectors. Ideally our code would be structured in such a way that was easier to test but I and I assume other don't always have that luxury. 

To solve this problem I have created a custom command that calls elements and strips all results that are not visible. I have then overridden some commands to use my custom elements command so that they will not try to interact with an element that is not visible.

If it would be useful I'd be interested in implementing something similar into webdriverio. My plan would be to create a visible flag on elements.js and corresponding flags on other commands that use elements.js.

**Comment by christian-bromann** [comment] 2016-02-03 08:20
so you mean something like `browser.elements(".someSelector:visible")`?

**Comment by vrundbaken** [comment] 2016-02-03 08:29
Exactly, as far as I know the visible pseudo class can't be used currently.

**Comment by christian-bromann** [comment] 2016-04-06 23:21
duplicate of #891

**Closed by christian-bromann** 2016-04-06 23:21 UTC
Labels: Enhancement
