### ISSUE TITLE
Allow way to distinguish runs of same browser

### ISSUE THREAD

**Issue by halovanic** [webdriverio/webdriverio#5411] opened 2020-05-18 13:07 UTC
**Is your feature request related to a problem? Please describe.**

I can configure multiple runs of the same browser on the same platform, but passed different launch options or capabilities.  These are generally indistinguishable in any reporter output as only the browser name, platform and device name (if any) get used for identification.

For example, I can run a test suite on my desktop machine against both Chrome and Chrome with [mobile emulation](https://chromedriver.chromium.org/mobile-emulation). While this isn't a true substitute for a real mobile device, it can be much faster and cheaper for a developer to test their responsive website behavior under both modes.

As another example, I may need to test different configurations of Firefox like two different user profiles or sets of preferences.

In both these cases, I can set custom browser capabilities to achieve the desired results, but reporter grouping never reflects these, instead only ever showing something like "chrome 50 windows 8.1".

**Describe the solution you'd like**

I'd like a way to specify a custom identifier within the WebDriverIO capabilities at the level of maxInstances in the config that can be seen by reporters.  Reporters could use this user-specified identifier instead of the generated one usually made out of platform + browser name.  Alternatively, an identifier could function as an additional optional value to append to these.

**Describe alternatives you've considered**

Reporters do have access to the requested capabilities and a custom reporter could construct an identifier out of current information, but every user would need to override or reimplement their reporters for their particular use cases since browsers have an undefined set of custom capabilities, any of which could be relevant.

Multiremote breaks apart browser executions into named sets, but is only intended for actual synchronization between browsers. It does not work well for this use case when this synchronization is not needed or desired.

Thanks,
Alex

**Comment by christian-bromann** [comment] 2020-05-18 14:10
@halovanic the spec reporter usually looks as follows:

```
[Chrome 50 Windows 10 #0-0] Spec: /foo/bar/baz.js
[Chrome 50 Windows 10 #0-0] Running: Chrome (v50) on Windows 10
[Chrome 50 Windows 10 #0-0] Session ID: foobar
[Chrome 50 Windows 10 #0-0]
[Chrome 50 Windows 10 #0-0] Foo test
[Chrome 50 Windows 10 #0-0]    green ✓ foo
[Chrome 50 Windows 10 #0-0]    green ✓ bar
[Chrome 50 Windows 10 #0-0]
[Chrome 50 Windows 10 #0-0] Bar test
[Chrome 50 Windows 10 #0-0]    green ✓ some test
[Chrome 50 Windows 10 #0-0]    red ✖ a failed test
[Chrome 50 Windows 10 #0-0]    red ✖ a failed test with no stack
[Chrome 50 Windows 10 #0-0]
[Chrome 50 Windows 10 #0-0] Baz test
[Chrome 50 Windows 10 #0-0]    green ✓ foo bar baz
[Chrome 50 Windows 10 #0-0]    cyan - a skipped test
[Chrome 50 Windows 10 #0-0]
[Chrome 50 Windows 10 #0-0] green 4 passing (5s)
[Chrome 50 Windows 10 #0-0] red 1 failing
[Chrome 50 Windows 10 #0-0] cyan 1 skipped
[Chrome 50 Windows 10 #0-0]
[Chrome 50 Windows 10 #0-0] 1) Bar test a failed test
[Chrome 50 Windows 10 #0-0] red expected foo to equal bar
[Chrome 50 Windows 10 #0-0] gray Failed test stack trace
[Chrome 50 Windows 10 #0-0]
[Chrome 50 Windows 10 #0-0] 2) Bar test a failed test with no stack
[Chrome 50 Windows 10 #0-0] red expected foo to equal bar
[Chrome 50 Windows 10 #0-0]
[Chrome 50 Windows 10 #0-0] Check out job at https://app.eu-central-1.saucelabs.com/tests/ba86cbcb70774ef8a0757c1702c3bdf9
```

You see the identifier `#0-0` which the first number is the key of the capability and the second is the number of the test. Is there something you would like to add to this or why would this identifier not be sufficient?

**Comment by halovanic** [comment] 2020-05-18 20:05
Yes, this works if you have access to the configuration file and can check the array order of the test configurations.  But if they grow large, or you are looking through test results without direct access to the configuration in question (such as if you are a non-technical user), this can be cumbersome.

What I would want as the enhancement is being able to define something like the following:

```js
    capabilities: [
        {
            browserName: 'chrome'
            id: 'Regular Chrome'
        },
        {
            browserName: 'chrome',
            id: 'Chrome emulating iPhone 6',
            'goog:chromeOptions': {
                mobileEmulation: { deviceName: 'iPhone 6' }
            },
        }
    ]
```
resulting in more readable output similar to this:
```
[Regular Chrome #0-0]
...
[Chrome emulating iPhone 6 #1-0]
```
or
```
[Regular Chrome - Chrome 50 Windows 10 #0-0]
...
[Chrome emulating iPhone 6 - Chrome 50 Windows 10 #1-0]
```

I should clarify that every reporter of course has its own different way of printing the execution data.  The spec reporter is probably the least important to alter here for the reasons you gave.  I was just hoping for a starting point of defining such a general identifier for drivers.

**Comment by christian-bromann** [comment] 2020-05-19 13:16
I would suggest to introduce an option to the spec reporter that allows to dynamically modify the identifier. The function would receive various of identifier options like config or capabilities and the user could then build a custom identifier.

PRs are welcome!

**Comment by erwinheitzman** [comment] 2020-05-26 15:54
How about using sessionId's instead since I can run the exact same setup twice as well which still would not be identifiable without it?

**Comment by halovanic** [comment] 2020-06-05 14:46
A session ID is needed to distinguish multiple runs, yes, but it is not helpful to someone who only has the final reporter output of a single run from something like Allure.

The difficulty I am having with adding an option to any given reporter to override or supplement the identifiers output is that it really is going to require every user to custom implement a function for matching each of their setups in their capabilities array to a custom name.  At this point, it feels like it's going to end up being essentially the same effort for a user as just extending an existing reporter or implementing one from scratch.

I would really like if there was a way that these could be defined as "named" instances for reporter use but a structure like that is currently only reserved for multi-remote.  Would it be possible that we allow an "expanded" configuration notation like this?

```
capabilities: [
    {
        'Regular Chrome': {
            browserName: 'chrome'
        }
    },
    {
        'Chrome emulating iPhone 6': {
            browserName: 'chrome',
            'goog:chromeOptions': {
                mobileEmulation: { deviceName: 'iPhone 6' }
            }
        }
    }
]
```

I'm sorry if I'm not being very clear about the problem here.  Maybe the better way is to just tackle getting specific reporters to print more of the likely custom capabilities like we do for deviceName since mobileEmulation in particular is essentially 1:1 with that.

Thanks,
Alex

**Comment by brucehubbardKroger** [comment] 2020-11-16 21:00
We are also hitting this problem.  We run two versions of Chrome, one at desktop resolution and one at a mobile resolution and we can't distinguish between the two in output.  Is it possible to set the CID for the runner to something other than 0-0?  If it was possible to override the CID then that should cascade and display properly in any reporters that use that field.

**Comment by christian-bromann** [comment] 2020-11-16 21:33
`cid` is an internal id to identify workers and should not be changed or up to be modified by the user. I still think the best idea to solve this problem is to allow an option for reporter to modify the identifier, so you can do e.g.

```js
// wdio.conf.js
reporters: [['spec', {
  specIdentifier: (cid, caps) => (
    caps['goog:chromeOptions']?.mobileEmulation
        ? `${caps.browserName} emulating ${caps['goog:chromeOptions']?.mobileEmulation.deviceName}`
        : cid
  ) 
}]]
```

to get e.g this reporter prefix: `[Chrome emulating iPhone 6 - Chrome 50 Windows 10 #1-0]`

**Comment by brucehubbardKroger** [comment] 2020-11-17 19:57
@christian-bromann I like it.  When I tested it locally in the spec reporter though it did not seem to work.  I ran it with this capability:

```
const chromeMobile = {
  browserName: 'chrome',
  maxInstances: 5,
  acceptInsecureCerts: true,
  'goog:chromeOptions': {
    args: [
      '--headless',
      '--no-sandbox',
      '--disable-dev-shm-usage',
      '--enable-precise-memory-info',
    ],
    mobileEmulation: {
      deviceMetrics: {
        width: 375,
        height: 812,
      },
    },
  },
}
```

But when I console.log `caps['goog:chromeOptions']` all I see is { debuggerAddress: 'localhost:51226' } and it does not contain my mobileEmulation settings.  I am running with the selenium-standalone service.  Am I doing something wrong?  Are those settings supposed to be propogated and visible to the reporters?

**Comment by christian-bromann** [comment] 2020-11-17 21:10
> When I tested it locally in the spec reporter though

Not sure what you've tested but this feature doesn't exist yet, we would need to implement it first.

**Comment by brucehubbardKroger** [comment] 2020-11-17 21:15
Yeah I changed my node_modules to add the method to test it out locally.  The console.log's I put in were in the spec reporter.  I didn't see the goog:chromeOptions.mobileEmulation properties being passed through at that point.

**Comment by christian-bromann** [comment] 2020-11-17 21:19
@brucehubbardKroger not sure but `onRunnerStart` should have the capabilities you are looking for, see https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-reporter/README.md#L383-L409

**Comment by brucehubbardKroger** [comment] 2020-11-17 21:19
Cool, thanks.  I'll check that out.  I'll submit a PR when I have it working.

**Comment by christian-bromann** [comment] 2021-09-07 09:45
@brucehubbardKroger any updates?

**Comment by user7699** [comment] 2022-02-08 14:00
Any progress on this issue? 

This issue is also present when using browserstack on multiple iOS devices. If you are running a spec file on e.g iPhone 8, iPhone12 and iPad8, Allure is not able to distinguish one device from another device. Only a single test will be marked as either passed or failed and the rest will be marked as retries of the same test. I think this is due to the following code in the XML file: 

```
            <parameters>
                <parameter kind='argument' name='device' value='safari'/>
            </parameters>
```
where every iPhone and iPad have the same value.

**Comment by user7699** [comment] 2022-02-10 14:24
I managed to find a workaround for this issue, but it does require a little fiddling with capabilities. 

As far as I understand, the reason why Allure is unable to distinguish between (some) devices and browsers is because of the following in the XML file: 

            <parameters>
                <parameter kind='argument' name='device' value='safari'/>
            </parameters>

where "value" is immutable. 

However, you can use the following command from the Allure API to modify/add a parameter

`addArgument(name, value) `

If you put that in an afterTest hook and add session based data which is unique to a certain browser, Allure will not have any problems to distinguish between them. 

If you are using browserstack, you can set any value to "browserName", e.g "MyCustomCap"

In the afterTest hook: 

`addArgument('Custom Argument', String(browser.requestedCapabilities.browserName));`

The XML file will display:

            <parameters>
                <parameter kind='argument' name='device' value='safari'/>
                <parameter kind='argument' name='Custom Argument' value='MyCustomCap'/>
            </parameters>

If you are using ChromeDriver, you can set browserVersion to a custom value in the capabilities section, e.g browserVersion: 'MyCustomDriver', and then add the code mentioned above in the afterTest hook. The result will be the same and Allure should have no problems to distinguish between different browsers/devices. 

It's not pretty but it works.

**Comment by BorisOsipov** [comment] 2023-03-02 20:06
Hi! We have rewritten the reporter to the new allure-js version. Please try version 8.5.0 of wdio-allure-reporter and provide more details if the issue still persists. Feel free to create a new issue with actual details if it reproduces.

**Closed by BorisOsipov** 2023-03-02 20:06 UTC
Labels: Enhancement, help wanted
