### ISSUE TITLE
wdi5 drag and drop not working for treetable

### ISSUE THREAD

**Issue by akmasaupe** [webdriverio/webdriverio#10374] opened 2023-05-15 11:03 UTC
Hi, I'm trying to do a drag and drop test for the rows in tree table. Somehow, it didn't works. It seems like it highlights the row (trying to drag) but the element is not moving at all. May I know if this is even possible?

Here is my test script:

it("01. Drag and drop", async () => {
    await $("#__field19-__clone367-text").waitForDisplayed();
    const elem = await $("#__field19-__clone367-text");
    const target = await $("#__field19-__clone327-text");
    await elem.dragAndDrop(target, 2000);
    await browser.pause(10000);
  });

**Comment by christian-bromann** [comment] 2023-05-15 15:55
duplicate of #8022

**Closed by christian-bromann** 2023-05-15 15:55 UTC
