### ISSUE TITLE
[🐛 Bug]: failSpecWithNoExpectations leads to "Unknown error."

### ISSUE THREAD

**Issue by foerstj-dv** [webdriverio/webdriverio#10480] opened 2023-05-31 14:23 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8

### Node.js Version

19

### Mode

WDIO Testrunner

### What happened?

When running wdio tests, every test case fails with "Unknown error." when you have failSpecWithNoExpectations:true in your jasmineOpts.

### What is your expected behavior?

Tests pass (except those that shouldn't)

### How to reproduce the bug.

- New Angular app
- Add wdio via schematic
  - local machine, jasmine, typescript, example tests & page objects, spec & allure, wait-for, chromedriver
  - You might need to install @wdio/cli yourself in addition
  - You might need to fix the spec path in wdio.conf.ts
- Run wdio tests -> it works
- Add failSpecWithNoExpectations:true to jasmineOpts
- Run wdio tests -> "Unknown error."

### Relevant log output

```typescript
Unknown error.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2023-06-08 11:37
Duplicate of #5239

**Comment by christian-bromann** [comment] 2023-06-11 20:10
Fixed in #10533

**Closed by christian-bromann** 2023-06-11 20:10 UTC
Labels: Bug 🐛
