### ISSUE TITLE
[🐛 Bug]: Unable to switch to Webview context

### ISSUE THREAD

**Issue by heychirag** [webdriverio/webdriverio#11252] opened 2023-09-26 10:02 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.13.13

### Node.js Version

16.20.2

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
        browserName: "",
        platformName: "Android",
        "appium:recreateChromeDriverSessions": true,
        "appium:ensureWebviewsHavePages": false,
        "appium:automationName": "UIAutomator2",
        "appium:autoGrantPermissions": true,
        "appium:deviceName": "AppiumIgnoresThis",
        "appium:appActivity": "<>",
        "appium:appPackage": "<>",
        "appium:appWaitActivity": "<>"
}
```

### What happened?

Appium is unable to switch to the Webview context. The driver just hangs and the promise to `switchContext()` never gets fulfilled. After a while, webdriverio throws this:

```
2023-09-26T09:56:14.726Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
2023-09-26T09:56:14.726Z INFO webdriver: Retrying 1/3
```

### What is your expected behavior?

Driver should be able to switch to Webview context.

### How to reproduce the bug.

Try switching to a webview context with the latest Webview version `Chrome/117.0.0.0`

### Relevant log output

```typescript
[debug] [AndroidDriver] Found 1 webview: ["WEBVIEW_app.bundle.id"]
[debug] [AndroidUiautomator2Driver@b3c0 (fd292e50)] Available contexts: ["NATIVE_APP","WEBVIEW_app.bundle.id"]
[debug] [AndroidUiautomator2Driver@b3c0 (fd292e50)] Connecting to chrome-backed webview context 'WEBVIEW_app.bundle.id'
[debug] [AndroidUiautomator2Driver@b3c0 (fd292e50)] A port was not given, using random free port: 8000
[debug] [AndroidUiautomator2Driver@b3c0 (fd292e50)] Passing web view details to the Chromedriver constructor: {
[debug] [AndroidUiautomator2Driver@b3c0 (fd292e50)]   "info": {
[debug] [AndroidUiautomator2Driver@b3c0 (fd292e50)]     "Android-Package": "app.bundle.id",
[debug] [AndroidUiautomator2Driver@b3c0 (fd292e50)]     "Browser": "Chrome/117.0.0.0",
[debug] [AndroidUiautomator2Driver@b3c0 (fd292e50)]     "Protocol-Version": "1.3",
[debug] [AndroidUiautomator2Driver@b3c0 (fd292e50)]     "User-Agent": "Mozilla/5.0 (Linux; Android 13; SM-G991B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36",
[debug] [AndroidUiautomator2Driver@b3c0 (fd292e50)]     "V8-Version": "11.7.439.16",
[debug] [AndroidUiautomator2Driver@b3c0 (fd292e50)]     "WebKit-Version": "537.36 (@1404acff38afe99f1585ba7d820005d6ca209351)",
[debug] [AndroidUiautomator2Driver@b3c0 (fd292e50)]     "webSocketDebuggerUrl": "ws://127.0.0.1:10900/devtools/browser"
[debug] [AndroidUiautomator2Driver@b3c0 (fd292e50)]   },
[debug] [AndroidUiautomator2Driver@b3c0 (fd292e50)]   "process": {
[debug] [AndroidUiautomator2Driver@b3c0 (fd292e50)]     "name": "app.bundle.id",
[debug] [AndroidUiautomator2Driver@b3c0 (fd292e50)]     "id": "5404"
[debug] [AndroidUiautomator2Driver@b3c0 (fd292e50)]   }
[debug] [AndroidUiautomator2Driver@b3c0 (fd292e50)] }
[debug] [AndroidDriver] Precalculated Chromedriver capabilities: {
[debug] [AndroidDriver]   "androidPackage": "app.bundle.id",
[debug] [AndroidDriver]   "androidUseRunningApp": true,
[debug] [AndroidDriver]   "androidProcess": "app.bundle.id",
[debug] [AndroidDriver]   "androidDeviceSerial": "R3CR401YLCL"
[debug] [AndroidDriver] }
[debug] [AndroidUiautomator2Driver@b3c0 (fd292e50)] Before starting chromedriver, androidPackage is 'app.bundle.id'
[debug] [Chromedriver@8b10] Changed state to 'starting'
[debug] [Chromedriver@8b10] Using the static Chromedriver->Chrome mapping
[debug] [Chromedriver@8b10] The most recent known Chrome version: 117.0.5938
[debug] [Chromedriver@8b10] Found 2 executables in '/Users/username1/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac'
[debug] [Chromedriver@8b10] The following Chromedriver executables were found:
[debug] [Chromedriver@8b10]     '/Users/username1/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver-mac-arm64_v117.0.5938.92' (version '117.0.5938.92', minimum Chrome version '117.0.5938')
[debug] [Chromedriver@8b10]     '/Users/username1/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver-mac-arm64_v116.0.5845.96' (version '116.0.5845.96', minimum Chrome version '116.0.5845')
[debug] [Chromedriver@8b10] Browser version in the supplied details: Chrome/117.0.0.0
[debug] [Chromedriver@8b10] Found Chrome bundle 'undefined' version '117.0.0'
[debug] [Chromedriver@8b10] Found 1 executable capable of automating Chrome '117.0.0'.
[debug] [Chromedriver@8b10] Choosing the most recent, '/Users/username1/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver-mac-arm64_v117.0.5938.92'.
[debug] [Chromedriver@8b10] If a specific version is required, specify it with the `chromedriverExecutable`desired capability.
[Chromedriver@8b10] Set chromedriver binary as: /Users/username1/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver-mac-arm64_v117.0.5938.92
[debug] [Chromedriver@8b10] Killing any old chromedrivers, running: pkill -15 -f "/Users/username1/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver-mac-arm64_v117.0.5938.92.*--port=8000"
[Chromedriver@8b10] No old chromedrivers seem to exist
[debug] [Chromedriver@8b10] Cleaning this device's adb forwarded port socket connections: R3CR401YLCL
[debug] [ADB] List forwarding ports
[debug] [ADB] Running '/Users/username1/Library/Android/sdk/platform-tools/adb -P 5037 -s R3CR401YLCL forward --list'
[debug] [ADB] Removing forwarded port socket connection: 51187
[debug] [ADB] Running '/Users/username1/Library/Android/sdk/platform-tools/adb -P 5037 -s R3CR401YLCL forward --remove tcp:51187'
[Chromedriver@8b10] Spawning chromedriver with: /Users/username1/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver-mac-arm64_v117.0.5938.92 --port=8000 --adb-port=5037 --verbose
[debug] [Chromedriver@8b10] ChromeDriver version: '117.0.5938.92'
[debug] [Chromedriver@8b10] Matched '/status' to command name 'getStatus'
[debug] [Chromedriver@8b10] Proxying [GET /status] to [GET http://127.0.0.1:8000/status] with no body
[Chromedriver@8b10] connect ECONNREFUSED 127.0.0.1:8000
[debug] [Chromedriver@8b10] Matched '/status' to command name 'getStatus'
[debug] [Chromedriver@8b10] Proxying [GET /status] to [GET http://127.0.0.1:8000/status] with no body
[debug] [Chromedriver@8b10] Got response with status 200: {"value":{"build":{"version":"117.0.5938.92 (67649b10b92bb182fba357831ef7dd6a1baa5648-refs/branch-heads/5938_62@{#14})"},"message":"ChromeDriver ready for new sessions.","os":{"arch":"arm64","name":"Mac OS X","version":"13.6.0"},"ready":true}}
[Chromedriver@8b10] Starting W3C Chromedriver session with capabilities: {
[Chromedriver@8b10]   "capabilities": {
[Chromedriver@8b10]     "alwaysMatch": {
[Chromedriver@8b10]       "goog:chromeOptions": {
[Chromedriver@8b10]         "androidPackage": "app.bundle.id",
[Chromedriver@8b10]         "androidUseRunningApp": true,
[Chromedriver@8b10]         "androidProcess": "app.bundle.id",
[Chromedriver@8b10]         "androidDeviceSerial": "R3CR401YLCL"
[Chromedriver@8b10]       },
[Chromedriver@8b10]       "goog:loggingPrefs": {
[Chromedriver@8b10]         "browser": "ALL"
[Chromedriver@8b10]       }
[Chromedriver@8b10]     }
[Chromedriver@8b10]   }
[Chromedriver@8b10] }
[debug] [Chromedriver@8b10] Matched '/session' to command name 'createSession'
[debug] [Chromedriver@8b10] Proxying [POST /session] to [POST http://127.0.0.1:8000/session] with body: {"capabilities":{"alwaysMatch":{"goog:chromeOptions":{"androidPackage":"app.bundle.id","androidUseRunningApp":true,"androidProcess":"app.bundle.id","androidDeviceSerial":"R3CR401YLCL"},"goog:loggingPrefs":{"browser":"ALL"}}}}
[debug] [Chromedriver@8b10] Webview version: 'Chrome/117.0.0.0'
```
Appium just hangs here waiting for the promise to fulfil.
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by heychirag** [comment] 2023-09-26 12:24
I think it's because of `Chrome/113.0.5672.136`. Can you try with `Chrome/117.0.0.0` which is the latest version?

**Comment by tamil777selvan** [comment] 2023-09-26 14:02
> I think it's because of `Chrome/113.0.5672.136`. Can you try with `Chrome/117.0.0.0` which is the latest version?

Let me try with `Chrome/117.0.0.0`

**Comment by tamil777selvan** [comment] 2023-09-26 14:39
Even tried with `Chrome/117.0.0.0`, but couldn't reproduce the error reported.

WDIO Logs:
```
[0-0] 9213 2023-09-26T14:33:26.764Z INFO 2023-09-26T14:33:26.764Z INFO webdriver: [GET] http://127.0.0.1:4723/session/5644b177-a422-4f70-97cb-31152b7332ac/contexts
[0-0] 9213 2023-09-26T14:33:27.658Z INFO 2023-09-26T14:33:27.657Z INFO webdriver: RESULT { '0': 'NATIVE_APP', '1': 'WEBVIEW_com.wdiodemoapp' }
[0-0] 9213 2023-09-26T14:33:27.659Z INFO 2023-09-26T14:33:27.659Z INFO webdriver: COMMAND switchContext("WEBVIEW_com.wdiodemoapp")
[0-0] 9213 2023-09-26T14:33:27.660Z INFO 2023-09-26T14:33:27.660Z INFO webdriver: [POST] http://127.0.0.1:4723/session/5644b177-a422-4f70-97cb-31152b7332ac/context
[0-0] 9213 2023-09-26T14:33:27.660Z INFO 2023-09-26T14:33:27.660Z INFO webdriver: DATA { name: 'WEBVIEW_com.wdiodemoapp' }
[0-0] 9213 2023-09-26T14:33:30.586Z INFO 2023-09-26T14:33:30.586Z INFO webdriver: RESULT null
[0-0] 9213 2023-09-26T14:33:30.642Z INFO 2023-09-26T14:33:30.642Z INFO webdriver: COMMAND findElement("xpath", "//*[normalize-space(text())="hero__subtitle"]")
```

Appium Logs:
```
[debug] [Chromedriver@fbcf] Using the static Chromedriver->Chrome mapping
[debug] [Chromedriver@fbcf] The most recent known Chrome version: 117.0.5938
[debug] [Chromedriver@fbcf] Found 2 executables in '/Users/tamil/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac'
[debug] [Chromedriver@fbcf] The following Chromedriver executables were found:
[debug] [Chromedriver@fbcf]     '/Users/tamil/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver-mac-x64_v117.0.5938.92' (version '117.0.5938.92', minimum Chrome version '117.0.5938')
[debug] [Chromedriver@fbcf]     '/Users/tamil/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver_mac64_v113.0.5672.63' (version '113.0.5672.63', minimum Chrome version '113.0.5672')
[debug] [Chromedriver@fbcf] Browser version in the supplied details: Chrome/117.0.0.0
[debug] [Chromedriver@fbcf] Found Chrome bundle 'undefined' version '117.0.0'
[debug] [Chromedriver@fbcf] Found 1 executable capable of automating Chrome '117.0.0'.
[debug] [Chromedriver@fbcf] Choosing the most recent, '/Users/tamil/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver-mac-x64_v117.0.5938.92'.
[debug] [Chromedriver@fbcf] If a specific version is required, specify it with the `chromedriverExecutable`desired capability.
[Chromedriver@fbcf] Set chromedriver binary as: /Users/tamil/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver-mac-x64_v117.0.5938.92
[debug] [Chromedriver@fbcf] Killing any old chromedrivers, running: pkill -15 -f "/Users/tamil/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver-mac-x64_v117.0.5938.92.*--port=8000"
[Chromedriver@fbcf] No old chromedrivers seem to exist
[debug] [Chromedriver@fbcf] Cleaning this device's adb forwarded port socket connections: emulator-5554
[debug] [ADB] List forwarding ports
[debug] [ADB] Running '/Users/tamil/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --list'
[Chromedriver@fbcf] Spawning chromedriver with: /Users/tamil/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver-mac-x64_v117.0.5938.92 --port=8000 --adb-port=5037 --verbose
[debug] [Chromedriver@fbcf] ChromeDriver version: '117.0.5938.92'
[debug] [Chromedriver@fbcf] Matched '/status' to command name 'getStatus'
[debug] [Chromedriver@fbcf] Proxying [GET /status] to [GET http://127.0.0.1:8000/status] with no body
[debug] [Chromedriver@fbcf] Got response with status 200: {"value":{"build":{"version":"117.0.5938.92 (67649b10b92bb182fba357831ef7dd6a1baa5648-refs/branch-heads/5938_62@{#14})"},"message":"ChromeDriver ready for new sessions.","os":{"arch":"x86_64","name":"Mac OS X","version":"12.6.7"},"ready":true}}
[Chromedriver@fbcf] Starting W3C Chromedriver session with capabilities: {
[Chromedriver@fbcf]   "capabilities": {
[Chromedriver@fbcf]     "alwaysMatch": {
[Chromedriver@fbcf]       "goog:chromeOptions": {
[Chromedriver@fbcf]         "androidPackage": "com.wdiodemoapp",
[Chromedriver@fbcf]         "androidUseRunningApp": true,
[Chromedriver@fbcf]         "androidProcess": "com.wdiodemoapp",
[Chromedriver@fbcf]         "androidDeviceSerial": "emulator-5554"
[Chromedriver@fbcf]       },
[Chromedriver@fbcf]       "goog:loggingPrefs": {
[Chromedriver@fbcf]         "browser": "ALL"
[Chromedriver@fbcf]       }
[Chromedriver@fbcf]     }
[Chromedriver@fbcf]   }
[Chromedriver@fbcf] }
[debug] [Chromedriver@fbcf] Matched '/session' to command name 'createSession'
[debug] [Chromedriver@fbcf] Proxying [POST /session] to [POST http://127.0.0.1:8000/session] with body: {"capabilities":{"alwaysMatch":{"goog:chromeOptions":{"androidPackage":"com.wdiodemoapp","androidUseRunningApp":true,"androidProcess":"com.wdiodemoapp","androidDeviceSerial":"emulator-5554"},"goog:loggingPrefs":{"browser":"ALL"}}}}
[debug] [Chromedriver@fbcf] Webview version: 'Chrome/117.0.0.0'
[debug] [Chromedriver@fbcf] Got response with status 200: {"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"117.0.0.0","chrome":{"chromedriverVersion":"117.0.5938.92 (67649b10b92bb182fba357831ef7dd6a1baa5648-refs/branch-heads/5938_62@{#14})"},"fedcm:accounts":true,"goog:chromeOptions":{"debuggerAddress":"localhost:64442"},"pageLoadStrategy":"normal","platformName":"android","proxy":{},"setWindowRect":false,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":false,"webauthn:extension:largeBlob":false,"webauthn:extension:minPinLength":false,"webauthn:extension:prf":false,"webauthn:virtualAuthenticators":false},"sessionId":"b2f2775082532255a3cf5c88c648f374"}}
[Chromedriver@fbcf] Determined the downstream protocol as 'W3C'
```

**Comment by heychirag** [comment] 2023-09-26 19:36
I asked the Appium team and they say it's a known issue with Chromedriver. Not sure what's correct now.

https://github.com/appium/appium/issues/19001

**Comment by heychirag** [comment] 2023-09-26 19:39
These are the logs for Chromedriver: https://gist.github.com/heychirag/cf926e50261d6c6d6404ae7fb14c4bad

There are a lot of errors printed to STDERR

**Comment by tamil777selvan** [comment] 2023-09-27 01:36
> @tamil777selvan Could you share you environment details?

@heychirag, I've tested it with below env setup and it works as expected.

```
Node Version: 18.8.0
WDIO Version: 8.16.12
Appium Version: 2.1.2
Appium Driver Versions:
    - uiautomator2@2.29.10
    - xcuitest@4.34.1
```

**Comment by heychirag** [comment] 2023-09-27 10:44
How is your setup working with Node 18? I am getting this:

```
2023-09-27T10:16:57.296Z ERROR webdriver: RequestError: connect ECONNREFUSED ::1:4723
    at ClientRequest.<anonymous> (file:///Volumes/workplace/0I18nPickerMobileAutomationTests/src/I18nPickerMobileAutomationTests/node_modules/webdriver/node_modules/got/dist/source/core/index.js:790:107)
    at Object.onceWrapper (node:events:629:26)
    at ClientRequest.emit (node:events:526:35)
    at ClientRequest.emit (node:domain:489:12)
    at Socket.socketErrorListener (node:_http_client:501:9)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
```

Got same question on SO as well: https://stackoverflow.com/questions/74982412/error-wdio-runner-error-failed-to-create-session-0-0-unable-to-connect-to

**Comment by tamil777selvan** [comment] 2023-09-27 12:08
@heychirag As indicated in the environment details above, I was utilising Node 18.

**Comment by heychirag** [comment] 2023-09-27 12:16
@tamil777selvan I created a new wdio project from scratch this time with Node 18. The driver now works with Node 18 but still facing the same issue.

```
[0-0] Searching for WEB context (attempt)
[0-0] 2023-09-27T12:10:36.561Z INFO webdriver: COMMAND getContexts()
[0-0] 2023-09-27T12:10:36.564Z INFO webdriver: [GET] http://127.0.0.1:4723/session/ba821d9d-e89e-4f0f-9df1-371751b5085a/contexts
[0-0] 2023-09-27T12:10:39.506Z INFO webdriver: RESULT [ 'NATIVE_APP', 'WEBVIEW_app.bundle.id' ]
[0-0] Contexts: ["NATIVE_APP","WEBVIEW_app.bundle.id"]
[0-0] switch context
[0-0] 2023-09-27T12:10:39.506Z INFO webdriver: COMMAND switchContext("WEBVIEW_app.bundle.id")
[0-0] 2023-09-27T12:10:39.506Z INFO webdriver: [POST] http://127.0.0.1:4723/session/ba821d9d-e89e-4f0f-9df1-371751b5085a/context
[0-0] 2023-09-27T12:10:39.506Z INFO webdriver: DATA { name: 'WEBVIEW_app.bundle.id' }
[0-0] 2023-09-27T12:12:39.528Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
[0-0] 2023-09-27T12:12:39.528Z INFO webdriver: Retrying 1/3
[0-0] 2023-09-27T12:12:39.528Z INFO webdriver: [POST] http://127.0.0.1:4723/session/ba821d9d-e89e-4f0f-9df1-371751b5085a/context
[0-0] 2023-09-27T12:12:39.528Z INFO webdriver: DATA { name: 'WEBVIEW_app.bundle.id' }
[0-0] 2023-09-27T12:14:39.553Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
[0-0] 2023-09-27T12:14:39.553Z INFO webdriver: Retrying 2/3
[0-0] 2023-09-27T12:14:39.553Z INFO webdriver: [POST] http://127.0.0.1:4723/session/ba821d9d-e89e-4f0f-9df1-371751b5085a/context
[0-0] 2023-09-27T12:14:39.553Z INFO webdriver: DATA { name: 'WEBVIEW_app.bundle.id' }
```

**Comment by tamil777selvan** [comment] 2023-09-27 12:33
In this instance, I suspect that the problem is likely linked to either Appium itself or the application being tested, rather than being an issue with WebdriverIO.

**Comment by christian-bromann** [comment] 2023-09-27 14:41
I will go ahead and close this. I know this can be very frustrating but our hands are tight here as we depend on a lot of external software (e.g. Chrome and Chromedriver) to be working correctly. It doesn't seem that there is anything we can change within the scope of WebdriverIO. Let me know if you have further questions.

Thanks @tamil777selvan for investigating.

**Closed by christian-bromann** 2023-09-27 14:41 UTC
Labels: Bug 🐛, Reproducible Example Missing
