### ISSUE TITLE
Elements selected by browser.$ intermittently lose parent context

### ISSUE THREAD

**Issue by diachedelic** [webdriverio/webdriverio#3579] opened 2019-02-20 06:16 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.4.17
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** [e.g. 8.12.0]
 - **NPM version:** 6.4.1 (although using Yarn 1.10.1)
 - **Browser name and version:** Chrome 72.0.3626.109 (Official Build) (64-bit)
 - **Platform name and version:** MacOS 10.14.3
 - **Additional wdio packages used (if applicable):**
```
// package.json
    "@wdio/cli": "^5.0.0",
    "@wdio/local-runner": "^5.0.0",
    "@wdio/mocha-framework": "^5.0.0",
    "@wdio/spec-reporter": "^5.0.0",
    "@wdio/sync": "^5.0.0",
    "wdio-chromedriver-service": "^5.0.0",
    "webdriverio": "^5.0.0",
    "chromedriver": "^2.45.0",
```

**Config of WebdriverIO**
```
{
  exclude: [],
  path: '/wd/hub', // must be absolute
  maxInstances: 1,
  sync: true,
  logLevel: 'silent',
  coloredLogs: true,
  deprecationWarnings: false,
  waitforTimeout: 20000,
  waitforInterval: 100,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,

  capabilities: [],
  protocol: 'http',
  chromeDriverArgs: ['--headless'],
  services: ['chromedriver'],
  reporters: ['spec'],
  framework: 'mocha',
  mochaOpts: {
    ui: 'bdd',
    timeout: 120000,
    bail: true, // abort suite if any test fails
  },
  bail: 1, // abort if any suite fails
}
```

**Describe the bug**
Intermittently, perhaps once every three times I run my tests, an element loses its parent's selector context.

**To Reproduce**

```html
<div class="course-count"></div>

<div class="event-list">
  <ul class="results">
    <li><span class="course-count">1</span></li>
  </ul>
</div>
```

```javascript
const resultEl = browser.$('.event-list .results > :nth-child(1)')
const countEl = resultEl.$('.course-count')

countEl.getText() // should return "1", but returns ""
```

**Expected behavior**

For elements to always keep within their parents' context.

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

Full logs: https://gist.github.com/diachedelic/01e607675a05b80bfff875be2946ad18

## Relevant log when working as expected
```
COMMAND findElement("css selector", ".event-list .results > :nth-child(1)")
[POST] http://127.0.0.1:57803/wd/hub/session/1596ccdecf59515a467b8004123a3654/element
DATA {using: "css selector", value: ".event-list .results > :nth-child(1)"}
RESULT {ELEMENT: "0.5626322163319011-5"}
COMMAND findElementFromElement("0.5626322163319011-5", "css selector", ".course-count")
[POST] http://127.0.0.1:57803/wd/hub/session/1596ccdecf59515a467b8004123a3654/element/0.5626322163319011-5/element
DATA {using: "css selector", value: ".course-count"}
RESULT {ELEMENT: "0.5626322163319011-6"}
COMMAND getElementText("0.5626322163319011-6")
[GET] http://127.0.0.1:57803/wd/hub/session/1596ccdecf59515a467b8004123a3654/element/0.5626322163319011-6/text
RESULT 1
```

## Relevant log when broken
```
COMMAND findElement("css selector", ".event-list .results > :nth-child(1)")
[POST] http://127.0.0.1:56951/wd/hub/session/ade84d006a526abbadf39c85df38ef9f/element
DATA {using: "css selector", value: ".event-list .results > :nth-child(1)"}
RESULT {ELEMENT: "0.35017796119983724-5"}
COMMAND findElement("css selector", ".course-count")
[POST] http://127.0.0.1:56951/wd/hub/session/ade84d006a526abbadf39c85df38ef9f/element
DATA {using: "css selector", value: ".course-count"}
RESULT {ELEMENT: "0.35017796119983724-6"}
COMMAND getElementText("0.35017796119983724-6")
[GET] http://127.0.0.1:56951/wd/hub/session/ade84d006a526abbadf39c85df38ef9f/element/0.35017796119983724-6/text
RESULT 
```

## Diff (working vs broken)
```diff
 [POST] http://127.0.0.1:56951/wd/hub/session/ade84d006a526abbadf39c85df38ef9f/element
 DATA {using: "css selector", value: ".event-list .results > :nth-child(1)"}
 RESULT {ELEMENT: "0.5626322163319011-5"}
-COMMAND findElementFromElement("0.5626322163319011-5", "css selector", ".course-count")
-[POST] http://127.0.0.1:56951/wd/hub/session/ade84d006a526abbadf39c85df38ef9f/element/0.5626322163319011-5/element
+COMMAND findElement("css selector", ".course-count")
+[POST] http://127.0.0.1:56951/wd/hub/session/ade84d006a526abbadf39c85df38ef9f/element
 DATA {using: "css selector", value: ".course-count"}
 RESULT {ELEMENT: "0.5626322163319011-6"}
 COMMAND getElementText("0.5626322163319011-6")
 [GET] http://127.0.0.1:56951/wd/hub/session/ade84d006a526abbadf39c85df38ef9f/element/0.5626322163319011-6/text
-RESULT 1
+RESULT 
```

As you can see, `findElement` is sent instead of `findElementFromElement`, meaning the element is selected without a parent context.

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment] 2019-02-20 09:51
This looks like a race condition. I was not able to reproduce it with the code you provided. It would be great if you could provide a reproducible example of some sort otherwise it is impossible for us to help you out.

**Comment by diachedelic** [comment] 2019-02-21 11:07
Okay I understand.  I don't think I'll be able to create a repo which reproduces this bug reliably, I'll try debug it instead when I next see it.  

@christian-bromann could you please answer a question to help me out?  To my understanding, the only way `findElement` would be called instead of `findElementFromElement` would be if `elementId` was not set on the parent ([utils.js:321](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/utils.js#L321)).  The only way I can see that `elementId` would not be set, in my case, is if a `browser.$` call failed to set the `elementId` property on the client.  This is indeed checked, and `client.error` is set ([browser/$.js:73](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/browser/%24.js#L73)) upon failure.  

What I'd like to know is, what happens when `client.error` is set?  Does that fail the test?  Where is the code that actually checks the `error` property, because I can't find it.

**Comment by mgrybyk** [comment] 2019-02-21 21:36
@diachedelic  may I ask you a question, have you @wdio/sync installed? 
Can't see it in your package.json. 
If you haven't got it installed wdio will run in async mode which mean you have to resolve each call to driver.

**Comment by diachedelic** [comment] 2019-02-22 00:58
@mgrybyk yes I do, sorry, I've updated the description

**Comment by christian-bromann** [comment] 2019-02-22 08:56
> What I'd like to know is, what happens when `client.error` is set? Does that fail the test? Where is the code that actually checks the `error` property, because I can't find it.

What error property? We don't throw errors if an element can't be found.

**Comment by diachedelic** [comment] 2019-02-22 09:01
@christian-bromann [this error property](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/browser/%24.js#L73)

**Comment by christian-bromann** [comment] 2019-02-22 09:50
> Does that fail the test?

No. We use to see if the element was found and if you log the object to make you aware that the element could not be fetched.

**Comment by diachedelic** [comment] 2019-02-22 12:54
@christian-bromann ah, inspecting wdio code further I see that in `elementErrorHandler` there is code to ensure `client.elementId` is populate before going on to call `client.$`.  I have been unable to reproduce the bug since reporting it.  Next time it occurs reliably I will try to pin it down.

**Comment by abjerstedt** [comment] 2019-03-06 00:31
@diachedelic So I have a idea of what could be broken, but your example wouldn't cover it.

Please review your code and ensure that you truely are doing $().$() and not $()[i].$().

**Comment by diachedelic** [comment] 2019-03-06 01:42
@abjerstedt yes it is `browser.$().$()` which triggers the bug.  I still have not been able to reproduce the bug since i reported it.

**Comment by abjerstedt** [comment] 2019-03-06 15:53
> @abjerstedt yes it is `browser.$().$()` which triggers the bug. I still have not been able to reproduce the bug since i reported it.

Based on this, I'm going to close this issue. If its not consistently reproducible, theres nothing we can do.

**Closed by abjerstedt** 2019-03-06 15:53 UTC
Labels: Reproducible Example Missing
