### ISSUE TITLE
setValue() is only entering the first character in a List Box

### ISSUE THREAD

**Issue by smtripathi99** [webdriverio/webdriverio#13733] opened 2024-10-03 13:52 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
browserName: 'chrome',
version: '129',
platformName: 'Windows 10',

}
```

### What happened?

After clearing the list box setValue() is entering only the first character of string

### What is your expected behavior?

All the characters should be entered by setValue()

### How to reproduce the bug.

  ```
await browser.$(PICKUP_LOCATION_CAR_HOME).waitAndClick();
        if (!await browser.$(PICKUP_LOCATION_CAR_HOME).getValue()==='') {
            await browser.$('//button[@id="axp-travel-search-locations_clearButton_departure"]').waitAndClick();
            await browser.pause(Constants.WAIT_CONSTANT_1_SECS);
            await browser.$(PICKUP_LOCATION_CAR_HOME).click();
            let pick='${testDataSearch[searchdata]["Pickup"]}';
            console.log('Pickup New Location: '+pick);
            await browser.$(PICKUP_LOCATION_CAR_HOME).setValue('${pick}');

        }
```

Before Clear:

![image](https://github.com/user-attachments/assets/f25fc36e-7cc9-4f03-8447-517d2dd89d9b)

Clear the List Box

![image](https://github.com/user-attachments/assets/31855dd3-739e-4098-8ac1-3ccca630ae65)

setValue('LHR') is only entering L

![image](https://github.com/user-attachments/assets/4db916a6-9beb-4ace-aff6-b5af937addc6)

### Relevant log output

```typescript
[0-0] 2024-10-03T13:36:56.502Z INFO webdriver: RESULT null
[0-0] 2024-10-03T13:36:56.502Z INFO webdriver: COMMAND releaseActions()
[0-0] 2024-10-03T13:36:56.502Z INFO webdriver: [DELETE] http://localhost:9515/session/d4460bd3fb5ab3eb3b867cd5da87235c/actions
[0-0] 2024-10-03T13:36:56.520Z INFO webdriver: RESULT null
[0-0] 2024-10-03T13:36:56.520Z INFO webdriver: COMMAND findElement("xpath", "//input[@id="axp-travel-search-locations_locationsInput_departure"]")      
[0-0] 2024-10-03T13:36:56.521Z INFO webdriver: [POST] http://localhost:9515/session/d4460bd3fb5ab3eb3b867cd5da87235c/element
[0-0] 2024-10-03T13:36:56.521Z INFO webdriver: DATA {
[0-0]   using: 'xpath',
[0-0]   value: '//input[@id="axp-travel-search-locations_locationsInput_departure"]'
[0-0] }
[0-0] 2024-10-03T13:36:56.533Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': 'f.A9947931400E4A2121AF297CECE74501.d.0C04A438AA489C136FD0B875D4D49B2A.e.480'
[0-0] }
[0-0] 2024-10-03T13:36:56.534Z INFO webdriver: COMMAND getElementProperty("f.A9947931400E4A2121AF297CECE74501.d.0C04A438AA489C136FD0B875D4D49B2A.e.480",
 "value")
[0-0] 2024-10-03T13:36:56.535Z INFO webdriver: [GET] http://localhost:9515/session/d4460bd3fb5ab3eb3b867cd5da87235c/element/f.A9947931400E4A2121AF297CEC
E74501.d.0C04A438AA489C136FD0B875D4D49B2A.e.480/property/value
[0-0] 2024-10-03T13:36:56.568Z INFO webdriver: RESULT Dallas-Fort Worth International Airport (DFW), Texas, United States of America
[0-0] 2024-10-03T13:36:56.568Z INFO webdriver: COMMAND findElement("xpath", "//input[@id="axp-travel-search-locations_locationsInput_departure"]")
[0-0] 2024-10-03T13:36:56.568Z INFO webdriver: [POST] http://localhost:9515/session/d4460bd3fb5ab3eb3b867cd5da87235c/element
[0-0] 2024-10-03T13:36:56.568Z INFO webdriver: DATA {
[0-0]   using: 'xpath',
[0-0]   value: '//input[@id="axp-travel-search-locations_locationsInput_departure"]'
[0-0] }
[0-0] 2024-10-03T13:36:56.580Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': 'f.A9947931400E4A2121AF297CECE74501.d.0C04A438AA489C136FD0B875D4D49B2A.e.480'
[0-0] }
[0-0] 2024-10-03T13:36:56.582Z INFO webdriver: COMMAND elementClear("f.A9947931400E4A2121AF297CECE74501.d.0C04A438AA489C136FD0B875D4D49B2A.e.480")      
[0-0] 2024-10-03T13:36:56.582Z INFO webdriver: [POST] http://localhost:9515/session/d4460bd3fb5ab3eb3b867cd5da87235c/element/f.A9947931400E4A2121AF297CE
CE74501.d.0C04A438AA489C136FD0B875D4D49B2A.e.480/clear
[0-0] 2024-10-03T13:36:56.623Z INFO webdriver: RESULT null
[0-0] 2024-10-03T13:36:56.623Z INFO webdriver: COMMAND elementSendKeys("f.A9947931400E4A2121AF297CECE74501.d.0C04A438AA489C136FD0B875D4D49B2A.e.480", "L
HR")
[0-0] 2024-10-03T13:36:56.624Z INFO webdriver: [POST] http://localhost:9515/session/d4460bd3fb5ab3eb3b867cd5da87235c/element/f.A9947931400E4A2121AF297CE
CE74501.d.0C04A438AA489C136FD0B875D4D49B2A.e.480/value
[0-0] 2024-10-03T13:36:56.624Z INFO webdriver: DATA { text: 'LHR' }
[0-0] 2024-10-03T13:36:56.737Z INFO webdriver: RESULT null
[0-0] 2024-10-03T13:36:57.753Z INFO webdriver: COMMAND performActions(<object>)
[0-0] 2024-10-03T13:36:57.754Z INFO webdriver: [POST] http://localhost:9515/session/d4460bd3fb5ab3eb3b867cd5da87235c/actions
[0-0] 2024-10-03T13:36:57.754Z INFO webdriver: DATA {
[0-0]   actions: [
[0-0]     { id: 'action11', type: 'wheel', parameters: {}, actions: [Array] }
[0-0]   ]
[0-0] }
[0-0] 2024-10-03T13:36:57.781Z INFO webdriver: RESULT null
[0-0] 2024-10-03T13:36:57.781Z INFO webdriver: COMMAND releaseActions()
[0-0] 2024-10-03T13:36:57.781Z INFO webdriver: [DELETE] http://localhost:9515/session/d4460bd3fb5ab3eb3b867cd5da87235c/actions
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2024-10-03 16:22
> ```ts
> [0-0] 2024-10-03T13:36:56.623Z INFO webdriver: COMMAND elementSendKeys("f.A9947931400E4A2121AF297CECE74501.d.0C04A438AA489C136FD0B875D4D49B2A.e.480", "L
> HR")
> [0-0] 2024-10-03T13:36:56.624Z INFO webdriver: [POST] http://localhost:9515/session/d4460bd3fb5ab3eb3b867cd5da87235c/element/f.A9947931400E4A2121AF297CE
> CE74501.d.0C04A438AA489C136FD0B875D4D49B2A.e.480/value
> [0-0] 2024-10-03T13:36:56.624Z INFO webdriver: DATA { text: 'LHR' }
> [0-0] 2024-10-03T13:36:56.737Z INFO webdriver: RESULT null
> ```

According to these logs, WebdriverIO did what it was suppose to do. The reason the characters don't show up in the UI can be application related or an issue with Chromedriver. Given we don't have a reproduction case I can only close the issue as there is no chance for us to do any further investigations.

Let me know if you have further questions.

**Closed by christian-bromann** 2024-10-03 16:22 UTC
Labels: Bug 🐛, Needs Triaging ⏳
