### ISSUE TITLE
WDIO api's like isDisplayed fails on shadowDom element.

### ISSUE THREAD

**Issue by asif-m** [webdriverio/webdriverio#5693] opened 2020-08-05 22:36 UTC
#[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment :**
 - **WebdriverIO version:** 6.1.17
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** v10.19.0
 - **NPM version:** 6.13.4
 - **Browser name and version:** chrome 84.0.4147.105
 - **Platform name and version: MAC Mohjave 10.14.6
 - **Additional wdio packages used (if applicable):** our package.json would look like this : https://gist.github.com/asif-m/4489809b2cf179e41ea26bee954f22e4

**Config of WebdriverIO**
We run the test suite using command :  npx wdio Config/abt-conf.js --spec 'Regression/LandingPage/fmiVerification.js'

**Describe the bug**
Our app uses shadowDom, and we tried to use wdio to write our automation tests. But we are blocked because the wdio is not returning the correct results for API's like isDisplayed, getText etc, for elements inside shadowDom. We are using the shadow$ api provided by wdio to locate the element inside shadowDom.

This is posted in already closed issue : https://github.com/webdriverio/webdriverio/issues/4098. But since there is no response there, creating a new issue here. 

To simulate this issue, you can load the [website](https://dev.nebula.care/practice/). In here there is a web element "neb-practice-app" that has shadowDom. On this element there is one more element that has id "#login". So when we write a test to see if this condition evaluates to true, the isDisplayed method evaluates to false. 

Also we have tried to set the "w3c": false, in 'goog:chromeOptions' but that too didn't help. 

**To Reproduce**
use this simple test block to reproduce this issue. 

`  it('Test if Shadow Dom element is visible.', () => {
browser.url("https://dev.nebula.care/practice/");
browser.pause(5000);
const element = $("neb-practice-app").shadow$('#login')
expect(element.isDisplayed()).toBeTruthy();
})`

**Expected behavior**
isDisplayed method should return true. 

**Log**
https://gist.github.com/asif-m/751fa1db3a1cff3a3a0e47220cad00d9

**Comment by christian-bromann** [comment] 2020-08-06 08:48
This is a duplicate of #4484. Your test script works very well when run with Chromedriver.

**Closed by christian-bromann** 2020-08-06 08:48 UTC
