### ISSUE TITLE
setViewportSize does not update screen for Chrome if any part of window is off of the screen

### ISSUE THREAD

**Issue by TravisPaul** [webdriverio/webdriverio#756] opened 2015-09-03 15:00 UTC
We discovered today that chromedriver doesn't update the viewport (it displays a white empty page) if any part of the browser window is off the screen.  The test still run, but the browser window does not show the tests being run.

I believe this is an issue with chromedriver, but I'm not familiar enough with the webdriver protocol yet to file a bug against the chromedriver project so I thought I would record it here (for now.)

Example:
```javascript
var webdriverio = require('webdriverio');
var options = {
    desiredCapabilities: {
        browserName: 'chrome'
    }
};
 
webdriverio
    .remote(options)
    .init()
    .setViewportSize({
            width: 1500, // resolution of PC is 1366x768
            height: 768
    })
    .url('http://www.google.com')
    .title(function(err, res) {
        console.log('Title was: ' + res.value);
    })
    .end();
```
![screenshot](https://cloud.githubusercontent.com/assets/2118993/9661879/c5b7daa8-522a-11e5-9448-84dab1af36e1.jpg)

Selenium Server Version: 27.1
Chrome Driver Version: 2.19
WebDriver Version: 2.45
OS Version: Windows 7, Windows 10

**Comment by drets** [comment] 2015-09-03 16:26
not reproducible on OS X Yosemite

**Comment by christian-bromann** [comment] 2015-09-08 17:58
Thanks for testing it @drets. I (OS X Yosemite) was also not able to find any bug regarding the viewport. If so it would be definitely a bug in chromedriver because WebdriverIO just sends the command to the driver. Closing this.

Do you mean that the whole screen and url bar kept blank (like on the screenshot) during the test?

**Closed by christian-bromann** 2015-09-08 17:58 UTC

**Comment by TravisPaul** [comment] 2015-09-08 18:25
@christian-bromann Yes, the whole screen and url stayed like the screenshot for the entire test.

We'll look into sending this bug to chrome driver, thanks for confirming.

**Comment by christian-bromann** [comment] 2015-09-08 18:30
> We'll look into sending this bug to chrome driver

Awesome :+1:  thanks

**Comment by josephkuruvilla** [comment] 2018-01-22 10:50
Same issue happening for me also. what would be the solution? Please let me know.

**Comment by KillChaos** [comment] 2018-01-22 14:02
One way to get around the problem should be to set the setViewportSize height and width to values that do not exceed your monitor resolution.

**Comment by josephkuruvilla** [comment] 2018-01-23 07:46
I have set the value, but still i couldn't solve the issue. It throw the following error

RuntimeError: session not created exceptionfrom unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"(49EC6B9643211547873078F6AF48CB91)","isDefault":true},"id":1,"name":"","origin":"://"}
