### ISSUE TITLE
clearElement, or setValue empty string does not trigger onChange event

### ISSUE THREAD

**Issue by idw111** [webdriverio/webdriverio#530] opened 2015-05-14 03:56 UTC
I'm using react js to develop hybrid app,
and testing the app with appium and webdriverio.

When I input some value using setValue method,
it triggers 'onChange' event.

However, when I clear the input using clearElement(selector) or setValue(selector, '')
it does not trigger any event.

I'm not sure if it's appium-related or issue of webdriver implementation.

I resolved the issue temporarily by inserting space character.

Thank you.

**Comment by swamyuma** [comment] 2015-08-17 16:09
I am having the same issue with `setValue(selector, '')`.  It does not trigger the appearance of a tooltip.

**Comment by idw111** [comment] 2015-08-18 01:08
I changed my code to work in the same way with an empty string and a white space.

and used setValue(selector, ' ')

**Comment by swamyuma** [comment] 2015-08-22 13:54
I have finally figured a way to make the tooltip appear for an empty string with help from a stackoverflow user

`setValue(selector, [,'Tab'])`

http://stackoverflow.com/questions/32057081/how-to-test-setting-a-field-to-empty-string-using-webdriverio-mocha-and-phantom

**Comment by Dharmoslap** [comment] 2016-04-26 17:50
Is this bug related to v4 as well?

**Comment by christian-bromann** [comment] 2016-04-26 18:00
it's not related to WebdriverIO, it's a problem within the browser driver. This issue is only open here in case someone comes up with a workaround that 100% ensures that the onChange event gets triggered (using javascript on the page).

**Comment by christian-bromann** [comment] 2016-06-01 02:37
I don't think there is a good workaround for that though. Closing.

**Closed by christian-bromann** 2016-06-01 02:37 UTC
Labels: Bug, Selenium Related

**Comment by s2t2** [comment] 2016-06-27 19:55
Unfortunately `setValue(selector, ['','Tab'])` does not trigger `onChange` or `onInput` as I had hoped. Does anyone know a fix?

If the problem is browser driver-related, can someone share the configuration of an alternate browser driver that does trigger these events?

Thank you!

**Comment by s2t2** [comment] 2016-06-29 17:54
For anyone googling in the future, you should be able to use the workaround: `setValue(selector, [" ", "\uE003"])`, where the first value is a space or any other character, and the second value is the unicode representation of a [backspace keystroke](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-character-types).

I can confirm this combination of values does trigger the `onInput` event and the `onChange` event of the form inputs.

For example:

```` js
var testBrowser = webdriverio.remote({desiredCapabilities: {browserName: 'firefox'}});
var BACKSPACE_UNICODE = "\uE003";

testBrowser
  .init()
  .url('http://localhost:3000/some-page-with-a-form')
  .setValue('#my-input', [' ', BACKSPACE_UNICODE])
  .submitForm("#my-form")
  .end()
````
