### ISSUE TITLE
[🐛 Bug]: @wdio/reporter is not compatible with CommonJs module

### ISSUE THREAD

**Issue by maksym-alavatskyi** [webdriverio/webdriverio#10168] opened 2023-04-11 12:15 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.8.0

### Node.js Version

v16.19.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{ 
  browserName: 'chrome',
  browserVersion: '111.0.5563.146'
  platfromName: 'macOS'
}
```

### What happened?

for commonJs module wdio config failing on @wdio/config:ConfigParser when custom reporter is used:

ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///Users/maksym.alavatskyi/Documents/copy/test-w8/wdio.conf.ts: require() of ES Module /Users/maksym.alavatskyi/Documents/copy/test-w8/node_modules/@wdio/reporter/build/index.js from /Users/maksym.alavatskyi/Documents/copy/test-w8/custom-reporter.ts not supported.
Instead change the require of index.js in /Users/maksym.alavatskyi/Documents/copy/test-w8/custom-reporter.ts to a dynamic import() which is available in all CommonJS modules.

### What is your expected behaviour?

e2e tests are running, config is loaded with not error

### How to reproduce the bug.
Link 
https://github.com/maksym-alavatskyi/test-wdiov8
Run installation script
`yarn`
run test
`yarn wdio`

### Relevant log output

```typescript
test-w8 % yarn wdio
yarn run v1.22.19
warning package.json: No license field
$ wdio run ./wdio.conf.ts
2023-04-11T11:54:55.159Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///Users/maksym.alavatskyi/Documents/copy/test-w8/wdio.conf.ts: require() of ES Module /Users/maksym.alavatskyi/Documents/copy/test-w8/node_modules/@wdio/reporter/build/index.js from /Users/maksym.alavatskyi/Documents/copy/test-w8/custom-reporter.ts not supported.
Instead change the require of index.js in /Users/maksym.alavatskyi/Documents/copy/test-w8/custom-reporter.ts to a dynamic import() which is available in all CommonJS modules.
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/maksym.alavatskyi/Documents/copy/test-w8/node_modules/@wdio/reporter/build/index.js from /Users/maksym.alavatskyi/Documents/copy/test-w8/custom-reporter.ts not supported.
Instead change the require of index.js in /Users/maksym.alavatskyi/Documents/copy/test-w8/custom-reporter.ts to a dynamic import() which is available in all CommonJS modules.
    at Object.require.extensions.<computed> [as .js] (/Users/maksym.alavatskyi/Documents/copy/test-w8/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/Users/maksym.alavatskyi/Documents/copy/test-w8/custom-reporter.ts:4:20)
    at Module.m._compile (/Users/maksym.alavatskyi/Documents/copy/test-w8/node_modules/ts-node/dist/index.js:857:29)
    at Object.require.extensions.<computed> [as .ts] (/Users/maksym.alavatskyi/Documents/copy/test-w8/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/Users/maksym.alavatskyi/Documents/copy/test-w8/wdio.conf.ts:4:27)
    at Module.m._compile (/Users/maksym.alavatskyi/Documents/copy/test-w8/node_modules/ts-node/dist/index.js:857:29)
    at Object.require.extensions.<computed> [as .ts] (/Users/maksym.alavatskyi/Documents/copy/test-w8/node_modules/ts-node/dist/index.js:859:16)
    at async Promise.all (index 0)
    at async ConfigParser.addConfigFile (file:///Users/maksym.alavatskyi/Documents/copy/test-w8/node_modules/@wdio/config/build/lib/ConfigParser.js:85:36)
    at async ConfigParser.initialize (file:///Users/maksym.alavatskyi/Documents/copy/test-w8/node_modules/@wdio/config/build/lib/ConfigParser.js:47:13)
    at async Launcher.run (file:///Users/maksym.alavatskyi/Documents/copy/test-w8/node_modules/@wdio/cli/build/launcher.js:37:9) {
  code: 'ERR_REQUIRE_ESM'
}
error Command failed with exit code 1.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2023-04-11 16:36
Duplicate of #9869

**Closed as completed by christian-bromann** 2023-04-11 16:36 UTC
Labels: Bug 🐛, Needs Triaging ⏳
