### ISSUE TITLE
element.moveTo() is throwing exception if element needs to be scrolled into view.

### ISSUE THREAD

**Issue by tzurp** [webdriverio/webdriverio#7311] opened 2021-08-20 18:19 UTC
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.9.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync
 - **Node.js version:** 14.17.0
 - **NPM version:** 6.14.13
 - **Browser name and version:** Chrome 92
 - **Platform name and version: ** Windows 10 / Centos 7
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
When calling element.moveTo(), when 'element' is existing element that is not in 'view' (need to be scrolled into view), an exception is thrown: "error move target out of bounds". If 'element' is in view no exception is thrown.

**To Reproduce**
Find the elements in a long scrollable list and for each of the list elements do:  element.moveTo().

[Include code or an example repository that can easily be set up]

**Expected behavior**
moveTo is expected to move the mouse cursor to the element. If it is not in view, it should scroll into view and then move the cursor on the element.

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!
[wdio-chromedriver.log](https://github.com/webdriverio/webdriverio/files/7023420/wdio-chromedriver.log)
[wdio.log](https://github.com/webdriverio/webdriverio/files/7023421/wdio.log)
[wdio-0-0.log](https://github.com/webdriverio/webdriverio/files/7023422/wdio-0-0.log)

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment] 2021-08-23 09:07
Can you provide a reproducible example?

**Comment by tzurp** [comment] 2021-08-23 13:53
@christian-bromann sure. Try this:

```
    it("Test moveTo", ()=> {
        browser.url("https://skinnyties.com/");
        browser.$(".ShopTheLook__Inner").moveTo();
    })
```

**Comment by erwindetesters** [comment] 2021-08-23 15:00
Confirmed, adding `this.scrollIntoView();` to the internal command fixes the issue. Should be easy and should be applied to all places where `performActions` is used internally because it doesn't automatically scroll the element into view.

**Comment by christian-bromann** [comment] 2021-08-25 12:18
I mean theoretically it makes sense, if you want to move your mouse to an element that is out of bounds you won't be able to execute the action. That is why I would suggest to modify the error message in `moveTo` and if there is an element out of bounds error, document what is going on and suggest a solution like using `scrollIntoView`.

Any contributions to this are welcome!

**Comment by christian-bromann** [comment] 2021-10-11 11:55
We already have a function that transforms error messages. It can be found here: https://github.com/webdriverio/webdriverio/blob/main/packages/webdriver/src/utils.ts#L270-L325

**Comment by justusromijn** [comment] 2021-10-15 07:02
@erwinheitzman the out of bounds error is when an index is given which is greater then the total length of said array (of elements). The out-of-viewport case errors somewhere else. I'm taking another breath and a deep dive to figure out where we can cover this case. If I can find the specific error message, I'll make sure to cover it within the transformers at the utils.

**Comment by justusromijn** [comment] 2021-10-15 07:36
Also note that the documentation of moveTo explicitly states that it scrolls the element into view if it is outside of view.

**Comment by erwinheitzman** [comment] 2021-10-15 07:49
moveTo does not scroll, it only moves the cursor. however when using the old JSON Wire protocol the default for that protocol was that the commands automatically scrolled. With Webdriver this is no longer the case. This is the reason that the documentation is a mismatch and why I suggested to simply auto scroll for elements that need it.

**Comment by christian-bromann** [comment] 2021-10-15 08:42
> With Webdriver this is no longer the case. This is the reason that the documentation is a mismatch and why I suggested to simply auto scroll for elements that need it.

The WebDriver still [states](https://w3c.github.io/webdriver/webdriver-spec.html#element-click):

> The Element Click command scrolls into view the element and clicks the in-view centre point. If the element is not pointer-interactable, an element not interactable error is returned.

**Comment by erwinheitzman** [comment] 2023-12-10 16:57
This should now be resolved as we pushed a fix for this not too long ago

**Closed by erwinheitzman** 2023-12-10 16:57 UTC
Labels: help wanted, good first pick
