### ISSUE TITLE
Getting HTTPError: Response code 404 (Not Found) Error while installing selenium-standalone

### ISSUE THREAD

**Issue by amir-dentsu** [webdriverio/webdriverio#6174] opened 2020-11-28 18:35 UTC
WebDriverIO Version: "wdio": "^4.0.0"
   Node.js version:  12.19.0
   NPM version:  6.14.8
   Browser name and version: Chrome 87
   Platform name and version: Windows 10
   Additional wdio packages used (if applicable):  "@wdio/selenium-standalone-service": "^6.10.0",

In package.json, I have

"scripts": {
    "start:selenium-standalone": "./node_modules/.bin/selenium-standalone install"
  },

When we run
        npm run start:selenium-standalone then getting below output

selenium-standalone installation starting
----------

---
selenium install:
from: https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
to: /ops/node_modules/selenium-standalone/.selenium/selenium-server/3.141.59-server.jar
---
chrome install:
from: https://chromedriver.storage.googleapis.com/87.0.4280.20/chromedriver_linux64.zip
to: /ops/node_modules/selenium-standalone/.selenium/chromedriver/latest-x64-chromedriver
---
firefox install:
from: https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
to: /ops/node_modules/selenium-standalone/.selenium/geckodriver/latest-x64-geckodriver
---
chromiumedge install:
from: https://msedgedriver.azureedge.net/87.0.664.47/edgedriver_linux64.zip
to: /ops/node_modules/selenium-standalone/.selenium/chromiumedgedriver/latest-x64-msedgedriver

HTTPError: Response code 404 (Not Found)
    at Request._onResponseBase (/ops/node_modules/got/dist/source/core/index.js:896:31)
    at Request._onResponse (/ops/node_modules/got/dist/source/core/index.js:931:24)
    at ClientRequest.<anonymous> (/ops/node_modules/got/dist/source/core/index.js:945:23)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:326:22)
    at ClientRequest.origin.emit (/ops/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:601:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
    at TLSSocket.socketOnData (_http_client.js:474:22)
    at TLSSocket.emit (events.js:314:20) {
  code: undefined,
  timings: {
    start: 1606584754249,
    socket: 1606584754250,
    lookup: 1606584754314,
    connect: 1606584754320,
    secureConnect: 1606584754343,
    upload: 1606584754343,
    response: 1606584755015,
    end: 1606584755016,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 64,
      tcp: 6,
      tls: 23,
      request: 0,
      firstByte: 672,
      download: 1,
      total: 767
    }
  }
}

**Expected behavior**
It should successfully install the selenium-standalone

**Comment by HananArgov** [comment] 2020-11-29 09:48
i'm getting the same error, when trying the latest wdio version and a different version (detail at the bottom)
although it tried for @amir-dentsu to install the chromium edge, for me the issue is the same with regular chromedriver.

I think there's a `selenium-standalone` issue here, since they changed their installation configs to support `latest`:
https://github.com/vvo/selenium-standalone/releases/tag/v6.22.0

```
    "@wdio/appium-service": {
      "version": "6.6.3",
      "resolved": "https://registry.npmjs.org/@wdio/appium-service/-/appium-service-6.6.3.tgz",
      "integrity": "sha512-5K/PX3K2usGGRCL9x9rCAx5rshFBX0wcmWgz6CDLZsYYDS8k0NIqcR1biKHHTIlo/GiVZjgVxuzHGiUBG0fWsw==",
      "dev": true,
      "requires": {
        "@wdio/config": "6.6.3",
        "@wdio/logger": "6.6.0",
        "fs-extra": "^9.0.0",
        "param-case": "^3.0.0"
      }
    },
    "@wdio/cli": {
      "version": "6.7.2",
      "resolved": "https://registry.npmjs.org/@wdio/cli/-/cli-6.7.2.tgz",
      "integrity": "sha512-g1L8FfrKBaOPqWPcn6NzGFf/ysNl9m+hC7OLYfxAb5Pa33RDBDxtZzsebmvveghw8ZXRGFmvdhEv71cp9dla/A==",
      "requires": {
        "@wdio/config": "6.6.3",
        "@wdio/logger": "6.6.0",
        "@wdio/utils": "6.7.0",
        "async-exit-hook": "^2.0.1",
        "chalk": "^4.0.0",
        "chokidar": "^3.0.0",
        "cli-spinners": "^2.1.0",
        "ejs": "^3.0.1",
        "fs-extra": "^9.0.0",
        "inquirer": "^7.0.0",
        "lodash.flattendeep": "^4.4.0",
        "lodash.pickby": "^4.6.0",
        "lodash.union": "^4.6.0",
        "mkdirp": "^1.0.4",
        "recursive-readdir": "^2.2.2",
        "webdriverio": "6.7.2",
        "yargs": "^16.0.3",
        "yarn-install": "^1.0.0"
      },
      "dependencies": {
        "mkdirp": {
          "version": "1.0.4",
          "resolved": "https://registry.npmjs.org/mkdirp/-/mkdirp-1.0.4.tgz",
          "integrity": "sha512-vVqVZQyf3WLx2Shd0qJ9xuvqgAyKPLAiqITEtqW0oIUjzo3PePDd6fW9iFz30ef7Ysp/oiWqbhszeGWW2T6Gzw=="
        }
      }
    },
    "@wdio/config": {
      "version": "6.6.3",
      "resolved": "https://registry.npmjs.org/@wdio/config/-/config-6.6.3.tgz",
      "integrity": "sha512-zJjPpjJu05els9A2ZzOVMAYccaHSXmmqQ2h+ftelXmFgO4mYDlKufx0HaCZDdn+O0SCG0ASqv+u1KNuqmNhjDw==",
      "requires": {
        "@wdio/logger": "6.6.0",
        "deepmerge": "^4.0.0",
        "glob": "^7.1.2"
      }
    },
    "@wdio/devtools-service": {
      "version": "6.6.6",
      "resolved": "https://registry.npmjs.org/@wdio/devtools-service/-/devtools-service-6.6.6.tgz",
      "integrity": "sha512-jvxkH1/TM4JCCwUhXOtwgDe2yuOtoL42LkPQ5Ir9HUvBzHyHITD4cEvz+r/bnyQpxbKYLFztWzClAVaYAVljCw==",
      "requires": {
        "@types/puppeteer": "^3.0.1",
        "@wdio/logger": "6.6.0",
        "core-js": "~3.6.0",
        "lighthouse": "^6.4.1",
        "puppeteer-core": "^5.1.0",
        "speedline": "^1.4.1",
        "stable": "^0.1.8"
      },
      "dependencies": {
        "@types/puppeteer": {
          "version": "3.0.5",
          "resolved": "https://registry.npmjs.org/@types/puppeteer/-/puppeteer-3.0.5.tgz",
          "integrity": "sha512-NkphUMkpbr/us6hp1AqUh/UxX5Tf2UJU94MvaF8OOgIUPBipYodql+yRjcysJKqwnDkchp+cD/8jntI/C9StzA==",
          "requires": {
            "@types/node": "*"
          }
        }
      }
    },
    "@wdio/jasmine-framework": {
      "version": "6.7.2",
      "resolved": "https://registry.npmjs.org/@wdio/jasmine-framework/-/jasmine-framework-6.7.2.tgz",
      "integrity": "sha512-9jgMyktYtkktALSHkyDqcwC3BVNVDFjWbiY49UC+AMIQ+M0joQo77+bL0oVL2S/xxWegdlpTGCShhyAh/Ot4+A==",
      "requires": {
        "@wdio/logger": "6.6.0",
        "@wdio/utils": "6.7.0",
        "expect-webdriverio": "^1.1.5",
        "jasmine": "3.6.3"
      }
    },
    "@wdio/local-runner": {
      "version": "6.7.2",
      "resolved": "https://registry.npmjs.org/@wdio/local-runner/-/local-runner-6.7.2.tgz",
      "integrity": "sha512-eJl0Nt2sEqV0ZX6a2mdh+WI+tAs8qcEdsBecr2qSmALvz38m2FGgvTUf/INVvg89Mu4o5x9HGh1KSkzC+hKdSw==",
      "requires": {
        "@types/stream-buffers": "^3.0.3",
        "@wdio/logger": "6.6.0",
        "@wdio/repl": "6.7.1",
        "@wdio/runner": "6.7.2",
        "async-exit-hook": "^2.0.1",
        "stream-buffers": "^3.0.2"
      }
    },
    "@wdio/logger": {
      "version": "6.6.0",
      "resolved": "https://registry.npmjs.org/@wdio/logger/-/logger-6.6.0.tgz",
      "integrity": "sha512-BAvXcnlWdQC93MLWObetpcjHUEGR8niW2mH2KAwLPQhXwJkKxXjhlMKH/DmUn5uQ4/S7iySLlMq9EEEg9KuCwA==",
      "requires": {
        "chalk": "^4.0.0",
        "loglevel": "^1.6.0",
        "loglevel-plugin-prefix": "^0.8.4",
        "strip-ansi": "^6.0.0"
      }
    },
    "@wdio/protocols": {
      "version": "6.6.0",
      "resolved": "https://registry.npmjs.org/@wdio/protocols/-/protocols-6.6.0.tgz",
      "integrity": "sha512-0wWSZTB4sBzr9HG3hT9a0jaO+xPhz+eFdE/qMLvM8b1yPOOgHieGPSoTXPjkBaks0CZpqeimbT4myYoim2JK1w=="
    },
    "@wdio/repl": {
      "version": "6.7.1",
      "resolved": "https://registry.npmjs.org/@wdio/repl/-/repl-6.7.1.tgz",
      "integrity": "sha512-Ty69x6HTU/dl+xO2cLiHnYqxnf9ydylgKXiqktEvnGgft47+UEcXmnz18qWwPcqX10bu6lhr8J33hEk1A4kjIQ==",
      "requires": {
        "@wdio/utils": "6.7.0"
      }
    },
    "@wdio/reporter": {
      "version": "6.7.0",
      "resolved": "https://registry.npmjs.org/@wdio/reporter/-/reporter-6.7.0.tgz",
      "integrity": "sha512-P8shE281uqPHJk5fRNgmvBFPaPF/J3j52fjVMn5oIUpqnDHeocDsLRNSWelFFPySZ/OFOl4pzMx5LTMqIKML6g==",
      "requires": {
        "@types/cucumber": "^6.0.1",
        "@types/fs-extra": "^9.0.1",
        "fs-extra": "^9.0.0"
      }
    },
    "@wdio/runner": {
      "version": "6.7.2",
      "resolved": "https://registry.npmjs.org/@wdio/runner/-/runner-6.7.2.tgz",
      "integrity": "sha512-0VXZ18vli/FsC7rQhCNJVHNcIgvUgjojfQc+7FrkysxNlWHBrMisk+ZyEEHKrQ45etRBP4qo+NSdCSfnBOxaMQ==",
      "requires": {
        "@wdio/config": "6.6.3",
        "@wdio/logger": "6.6.0",
        "@wdio/utils": "6.7.0",
        "deepmerge": "^4.0.0",
        "gaze": "^1.1.2",
        "webdriver": "6.7.1",
        "webdriverio": "6.7.2"
      }
    },
    "@wdio/selenium-standalone-service": {
      "version": "6.6.5",
      "resolved": "https://registry.npmjs.org/@wdio/selenium-standalone-service/-/selenium-standalone-service-6.6.5.tgz",
      "integrity": "sha512-iAp9wY5bUQ5d8jPgUvgBkDk6KWaI2SJtyp0TvUGReXXTMIOPcyzupjWcxSYXTSLajKiC/8xoxFpjcntLoABtwg==",
      "dev": true,
      "requires": {
        "@types/fs-extra": "^9.0.1",
        "@types/selenium-standalone": "^6.15.2",
        "@wdio/config": "6.6.3",
        "@wdio/logger": "6.6.0",
        "fs-extra": "^9.0.1",
        "selenium-standalone": "^6.20.1"
      }
    },
    "@wdio/spec-reporter": {
      "version": "6.7.0",
      "resolved": "https://registry.npmjs.org/@wdio/spec-reporter/-/spec-reporter-6.7.0.tgz",
      "integrity": "sha512-xUW78Qw4ig2FBrxtxy1IG1xdPRnFk8OCREMfohEAxvTfDHaR/vU5xcX7fX1YE8c6QBJdgE/8zbIvd8QDrUhDfQ==",
      "requires": {
        "@wdio/reporter": "6.7.0",
        "chalk": "^4.0.0",
        "easy-table": "^1.1.1",
        "pretty-ms": "^7.0.0"
      }
    },
    "@wdio/sync": {
      "version": "6.7.2",
      "resolved": "https://registry.npmjs.org/@wdio/sync/-/sync-6.7.2.tgz",
      "integrity": "sha512-IPQidufkdFvmcFCYbm9o13dKfegPn/a+EBD3w7df6zDvyzr6MVrtYDilAlULDZJ/wm+wKhR27wcipCMPs0fjrw==",
      "requires": {
        "@types/puppeteer": "^3.0.1",
        "@wdio/logger": "6.6.0",
        "fibers": "^4.0.1"
      },
      "dependencies": {
        "@types/puppeteer": {
          "version": "3.0.5",
          "resolved": "https://registry.npmjs.org/@types/puppeteer/-/puppeteer-3.0.5.tgz",
          "integrity": "sha512-NkphUMkpbr/us6hp1AqUh/UxX5Tf2UJU94MvaF8OOgIUPBipYodql+yRjcysJKqwnDkchp+cD/8jntI/C9StzA==",
          "requires": {
            "@types/node": "*"
          }
        }
      }
    },
    "@wdio/utils": {
      "version": "6.7.0",
      "resolved": "https://registry.npmjs.org/@wdio/utils/-/utils-6.7.0.tgz",
      "integrity": "sha512-YhbExE89Ya5d1XIh4QIOuU1UjG30fB7iiFGgldu9ZfdUusIgjTwL4vMHhK30e+5+jdqzV6jMkTAf5a6OvH+02g==",
      "requires": {
        "@wdio/logger": "6.6.0"
      }
    },
```

**Comment by amir-dentsu** [comment] 2020-11-29 09:55
Hi @HananArgov ,

So Will this issue be fixed by webdriverio or selenium-standalone team?

**Comment by HananArgov** [comment] 2020-11-29 10:35
you can put a workaround, use a fixed version:
https://webdriver.io/docs/selenium-standalone-service.html
```
// wdio.conf.js
const drivers = {
    chrome: { version: '86.0.4240.22' }, // https://chromedriver.chromium.org/
    firefox: { version: '0.27.0' }, // https://github.com/mozilla/geckodriver/releases
    chromiumedge: { version: '85.0.564.70' } // https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
}

export.config = {
    // ...
    services: [
        ['selenium-standalone', {
            logPath: 'logs',
            installArgs: { drivers },
            args: { drivers }
        }]
    ],
    // ...
};
```

**Comment by gulatirajat** [comment] 2020-11-29 20:15
Faced similar issue, have logged this issue with Selenium standalone - https://github.com/vvo/selenium-standalone/issues/515.

What I observed was that the components (selenium standalone + browser drivers) just did not download with the latest v6.22.1.
Had to explicitly install the previous version for selenium standalone (6.20.1), to successfully download the drivers without errors.

Regarding the driver version, **strangely the following format just did not worked for me**:
services: [ [ 'selenium-standalone', {
                logPath: './logs',
                installArgs: {
                    chrome: { version: '87.0.4280.20' },
                    firefox: {version: '0.28.0'},
                    },
                args: {
                    chrome: { version: '87.0.4280.20' },
                    firefox: {version: '0.28.0'},
                },
            }]],

**Instead the following did**:
services: [['selenium-standalone', { drivers: { chrome: '87.0.4280.20', firefox: '0.28.0' } }]],

Not sure if the expected format is now changed with @wdio/selenium-standalone-service@6.10.3, as I was simply following the samples provided here - https://webdriver.io/docs/selenium-standalone-service.html

**Comment by mgrybyk** [comment] 2020-11-29 22:39
I've tried both old and new ways of specifying browser drivers.
Please provide with reproducible example.

**Comment by gulatirajat** [comment] 2020-11-30 02:38
Could you try these steps to reproduce the error:
1. Clean remove existing node_modules  .
2. Ensure following versions in package.json 
@wdio/cli - 6.10.2
@wdio/sync - 6.10.0
 @wdio/local-runner - 6.10.2 
@wdio/selenium-standalone-service - 6.10.3 (=> dependency - "selenium-standalone": "^6.22.1")
@wdio/cucumber-6.8.0 
@wdio/junit-reporter - 6.8.1 
@wdio/spec-reporter - 6.8.1

3. Install using - npm i
4.  Start your test execution - ./node_modules/.bin/wdio ./test/config/wdio.local.conf.js

Download operation results in the previously mentioned errors.

**Comment by gulatirajat** [comment] 2020-11-30 02:50
Regarding the way of specifying the driver version - closely following the document,  both ways are working for me now (with selenium-standalone@6.20.1). I was missing the additional nested json layer of "drivers: {" inside the "installArgs" and "args"

**Comment by mgrybyk** [comment] 2020-11-30 06:23
Great that it works, can the issue be closed?

**Comment by gulatirajat** [comment] 2020-11-30 14:45
To clarify, my last comment was in relation to the way of specifying the driver version (to override the default versions, if required) in case of selenium-standalone@**6.20.1**.

For me the issue still exists for **v6.22.1**.  The steps to reproduce are also provided above. I would ask @amir-dentsu @HananArgov to provide more details/steps to reproduce from their side as well.

**Comment by mgrybyk** [comment] 2020-11-30 14:49
Closing this one for now according to https://github.com/vvo/selenium-standalone/issues/515

Let's have convo in a single thread. Please reply there @gulatirajat and provide with reproducible example

**Closed by mgrybyk** 2020-11-30 14:49 UTC
Labels: Reproducible Example Missing
