### ISSUE TITLE
browser.getCookie() or browser.cookie() not returning values on IE

### ISSUE THREAD

**Issue by diwakarChapagain** [webdriverio/webdriverio#3060] opened 2018-11-21 20:58 UTC
Hi I am using `browser.getCookie()` function to access all the cookies from the browser, but recently it started failing to return. I have tried `browser.cookie()` as well wit no Luck. can anybody help me?

**Comment by christian-bromann** [comment] 2018-11-21 21:32
> can anybody help me?

Please provide log messages or a reproducible example. How do you expect help without giving any context?

**Comment by diwakarChapagain** [comment] 2018-11-21 21:48
Hi I am running my tests on Sauce labs and its does not have any logs as well all i get on my system is below: 

Error communicating with the remote browser. It may have died.
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'sauce-win10', ip: '10.100.20.6', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: RemoteWebDriver

**Comment by christian-bromann** [comment] 2018-11-21 21:58
@diwakarChapagain if you run tests on saucelabs you have tons of logs!

**Comment by diwakarChapagain** [comment] 2018-11-21 22:19
This is the server log: 

21:28:17.321 INFO - Executing: [get all cookies])
21:28:51.256 INFO - I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:20362: Connection reset
21:28:51.260 INFO - Retrying request to {}->http://localhost:20362

This is Automation log in sauce labs: 
2018-11-21 21:28:17:329 server.cc(281) Command: GET /session/50fb1ac9-87c3-4bb4-b954-89dfff2bad0a/cookie {}
D 2018-11-21 21:28:17:329 command.cc(36) Raw JSON command: { "name" : "getCookie", "locator" : { "sessionid" : "50fb1ac9-87c3-4bb4-b954-89dfff2bad0a" }, "parameters" : {} }
D 2018-11-21 21:28:17:330 IECommandExecutor.cpp(572) No alert handle is found
I 2018-11-21 21:28:17:330 Browser.cpp(124) No child frame focus. Focus is on top-level frame
D 2018-11-21 21:28:17:351 HookProcessor.cpp(234) Created named pipe \\.\pipe\IEDriverPipe720
D 2018-11-21 21:28:17:354 HookProcessor.cpp(288) Waiting for connection from browser via named pipe
D 2018-11-21 21:28:17:355 HookProcessor.cpp(297) Connection from browser established via named pipe
D 2018-11-21 21:28:17:357 HookProcessor.cpp(288) Waiting for connection from browser via named pipe
D 2018-11-21 21:28:17:357 HookProcessor.cpp(297) Connection from browser established via named pipe
D 2018-11-21 21:28:17:359 HookProcessor.cpp(288) Waiting for connection from browser via named pipe
D 2018-11-21 21:28:17:360 HookProcessor.cpp(297) Connection from browser established via named pipe
D 2018-11-21 21:28:17:361 HookProcessor.cpp(288) Waiting for connection from browser via named pipe
D 2018-11-21 21:28:17:384 HookProcessor.cpp(297) Connection from browser established via named pipe


"suggestion": null,
    "duration": 35.990999937057495,
    "path": "cookie",
    "method": "GET",
    "statusCode": 13,
    "timelineSeconds": 51.246999979019165


Not sure which log being asked here?

**Comment by christian-bromann** [comment] 2018-11-21 22:40
Can you provide the job id?

**Comment by diwakarChapagain** [comment] 2018-11-22 19:51
Hi This is a Sauce labs Job ID : 

`5a1d1bf579f64c5eabdefe67528bd066`

**Comment by christian-bromann** [comment] 2018-11-23 10:38
Can you also share the test code?

**Comment by diwakarChapagain** [comment] 2018-11-23 18:08
```let allCookies = browser.getCookie();
console.log("all cookies from Browser", allCookies);
       let qbnCookies = process.env.ENV !=="PROD" ? toolUtility.filterObjByKeyValInclude(allCookies,
            "name", "qbn.ptc") : toolUtility.filterObjByKeyValInclude(allCookies,
            "name", "qbn.");
        for(var cookieSet in qbnCookies){
          var cookieItem = qbnCookies[cookieSet]
          console.log("cookieitem", cookieItem);
          Object.keys(cookieItem).forEach(function (key, index) {
          if(key === "name" ){
            console.log("value",cookieItem[key]);
          }
          if(key === "value"){
              console.log("key value",cookieItem[key]);
              assert.isDefined(cookieItem[key], `Cookie ${cookieItem[key]}`
      + ` is not available`)
            assert.isNotNull(cookieItem[key], `Cookie ${cookieItem[key]}`
      + ` is not available`)
              }
          })
        }```

**Comment by diwakarChapagain** [comment] 2018-11-26 17:30
Hi Any update on this @christian-bromann ?

**Comment by worc** [comment] 2018-11-27 00:01
i've run into issues with `getCookie` before. it can be inconsistent and cause tests to fail periodically.

when i went digging into the problem i reran some tests with very verbose logs from webdriver, but never found the true root cause. but i did find that calling a `setCookie` immediately before `getCookie` was related to the issue. in the very verbose readout from webdriver, you could see `setCookie` not fully complete before `getCookie` was staged and executed.

@diwakarChapagain another angle might be to check if you're setting cookies through webdriver and if that's completing successfully.

**Comment by diwakarChapagain** [comment] 2018-11-27 07:20
> @diwakarChapagain another angle might be to check if you're setting cookies through webdriver and if that's completing successfully
Is this mean should I be using the set cookie to drop something and use `getCookie`? @worc

**Comment by worc** [comment] 2018-11-27 17:43
i mean you might want to look into how you're setting the cookies in the first place. the webdriver `setCookie` function is async and has caused timing issues for me before.

**Comment by diwakarChapagain** [comment] 2018-11-27 17:53
I got it, I am not setting any cookies using `setCookie` through webdriver, I am checking other cookies being set by the application code.

**Comment by christian-bromann** [comment] 2018-12-05 10:02
Yeah it seems like a weird connection error of the driver. Closing.

**Closed by christian-bromann** 2018-12-05 10:02 UTC
Labels: Logs Missing, Reproducible Example Missing
