### ISSUE TITLE
[devtools] [selenium grid] Should the dev-tools service work with Selenium Grid?

### ISSUE THREAD

**Issue by zhq745w** [webdriverio/webdriverio#4795] opened 2019-11-22 07:04 UTC
**Environment:**
 - **WebdriverIO version:** Latest
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.13 LTS
 - **NPM version:** 6.12
 - **Browser name and version:** Chrome 78
 - **Platform name and version:** Xubuntu 18.04 LTS
 - **Additional wdio packages used (if applicable):** dev-tools

**Config of WebdriverIO**
...
hostname: '192.168.20.xxx',
port: '4445',
services: ['devtools'],
...

**Describe the bug**

I have 2 PC.
PC A:
- Xubuntu
- wdio (latest). Testrunner mode, sync, dev-tools.
- jre 11
- Selenium Hub (3.141.59)

PC B:
- Xubuntu
- Chrome 78
- Selenium Node (3.141.59)

I run the test on PC A and get an error:
(node:24589) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:36735 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)

Tests pass successfully without dev-tools.
Should the dev-tools service work with Selenium Grid and, if so, what needs to be adjusted?

**Comment by naddison** [comment] 2019-11-22 23:05
I am pretty sure it should not work as the devtools are expecting to connect directly to the Chrome instance. I am pretty sure selenium-hub does not know how to proxy chrome dev tools protocol as its not a webdriver spec.

**Comment by christian-bromann** [comment] 2019-11-25 10:08
> Should the dev-tools service work with Selenium Grid and, if so, what needs to be adjusted?

It currently doesn't work because the IP in the debugger address is not updated to the host IP.

**Comment by wyhmichael** [comment] 2019-11-26 19:40
Hi @zhq745w, based on your description, I assume that you ran your test remotely from PC A to PC B:

If that's the case, devtools shouldn't work for you directly, 'cause the host is default to 'localhost'. Base on the documentation here: https://webdriver.io/docs/devtools-service.html#configuration, you need to set the host in the config to connect to devtools
````
// wdio.conf.js
export.config = {
  // ...
  services: [['devtools', {
      debuggerAddress: '[IP of PC B]:9222' // 9222 is default port, make sure PC A and PC B available to each other over your network, and debugger port is open
  }]],
  // ...
};
```

**Comment by zhq745w** [comment] 2019-11-27 07:17
Hi @wyhmichael 

I tried setting debuggerAddress to A (hub) and B (host), but that still doesn't work.

**Comment by wyhmichael** [comment] 2019-11-28 18:04
Hi @zhq745w , the default port is 9222, did that not work for you? do you mind checking if that port is not take by other applications and opened to be accessed on PC B? 

I am going to verify it on my end as well, will get back to you if I get some updates

**Comment by zhq745w** [comment] 2019-11-29 08:29
Hi @wyhmichael !

Port is not take by other applications.

> debuggerAddress: '[IP of PC B]:9222'

This will not work by 2 reasons:
1. Chromedriver accepts only local connections
2. Node configuration includes several copies of Chromedriver

**Comment by nami-varthakavi** [comment] 2019-12-10 00:10
Reposting my question from Gitter: Hey team, I'm working with dev-tools service andI'm looking for a way to work the dev tools for my remote test. I have selenium running my remote machine and my chrome starts but i get an error as follows:

(node:27628) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT <ip of the machine>:9234
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
[0-0] (node:27628) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27628) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
and my caps look like this:

{
  "browserName": "chrome",
  "goog:chromeOptions": {
    "args": [
      "--remote-debugging-port=9234"
    ]
  },
  "platformName": "windows"
}
has anyone tried with a remote testing? I got it working it locally but my usecase is for remote testing

**Comment by al3xand3r-K** [comment] 2019-12-10 08:08
I have the same issue, but in a bit slightly different way.

I'm using Selenoid + docker, which is technically the same as Selenium grid from perspective of connecting Devtools to chrome instance. I have 2+n containers running under the same network:
- 1 container with tests
- 1 container with Selenoid (a hub that receives a request from tests for a container with a specific browser in it)
- `n` containers with browsers, pulled and launched by Selenoid on request from the container with tests. The exact number depends on how many tests are running in parallel right now.

The end-problem is the same: I can put all the containers under the same network and assign static IPs to them within that network, so I always know the address of Selenoid (the hub), but I don't know the IP of the browser container. Plus, I'm not sure how it'd be handled in case of multiple browser instances running simultaneously - which is also a case for me since I do use that feature too.

**Comment by mgrybyk** [comment] 2019-12-10 08:29
The issue here is that selenium grid can't do it out of the box. 
I know that webdriver v4 will have devtools protocol support and we can use it.

Alternatively grid of webdriver v3 can be extended and be used to forward commands to remote chrome but it's not trivial at all.

I want to checkout what is already working in webdriver v4 and comeback to you soon

**Comment by spy686** [comment] 2020-01-20 09:18
Hi @mgrybyk,
Do you have news about devtools in the selenium grid v4?

**Comment by mgrybyk** [comment] 2020-01-20 09:26
@spy686 yes, sorry to say it won't help at this point.
It can't forward devtools connection to remote machine, at least in alpha 4, not sure if they have any plans to deal with it.

**Comment by mgrybyk** [comment] 2020-01-20 09:28
Devtools service won't work with selenium grid. Maybe someone can build custom one, cloud providers can definitely do it for us

**Comment by spy686** [comment] 2020-01-20 09:33
I need to use 'network_conditions' in the Selenium Grid.
https://codoid.com/how-to-set-network-conditions-in-selenium

Do you have any approach for my case?

**Comment by mgrybyk** [comment] 2020-01-20 09:35
@spy686 no, if you want to use grid

**Comment by spy686** [comment] 2020-01-20 09:37
So sad...

**Comment by christian-bromann** [comment] 2020-01-20 09:38
> Do you have any approach for my case?

The Selenium 4 grid server will support this.

**Comment by mgrybyk** [comment] 2020-01-20 13:33
@christian-bromann do you have some information about when will it support that? Currently it's not working (

**Comment by VisuSubbaiyan** [comment] 2020-02-13 11:26
@christian-bromann @mgrybyk  So I can't use "wdio-devtools-services" with selenium-standalone service + selenium/standalone-chrome-debug also, right?

**Comment by christian-bromann** [comment] 2020-02-13 13:12
@VisuSubbaiyan no

@mgrybyk it should be supported in one of the next alpha/beta releases

**Comment by VisuSubbaiyan** [comment] 2020-02-13 13:56
@christian-bromann Thank you

**Comment by christian-bromann** [comment] 2020-04-30 11:27
Closing as there is nothing WebdriverIO can do here. Once Selenium 4 is released this will be supported by the grid.

**Closed by christian-bromann** 2020-04-30 11:27 UTC
Labels: Bug🐛, help wanted

**Comment by anastasiyamazheika** [comment] 2021-11-08 13:51
Hello!
Is this issue fixed? How to tell Selenium Grid 4 to use a specific DevTools port?

**Comment by AlfredoMoretta** [comment] 2022-11-08 11:07
good morning guys, any news for devtools working on selenium-grid v4?

**Comment by BorisOsipov** [comment] 2022-11-08 11:18
@AlfredoMoretta it is done in https://github.com/webdriverio/webdriverio/pull/6508
File an issue with reproducible example if it doesn't work.

**Comment by AlfredoMoretta** [comment] 2022-11-08 11:20
@BorisOsipov thank you so much!
