### ISSUE TITLE
$('.some-element').waitForDisplayed(30000, true); is broken on IE and Edge

### ISSUE THREAD

**Issue by pmerwin** [webdriverio/webdriverio#3839] opened 2019-04-10 18:15 UTC
When using the reverse of waitForDisplayed on IE, wdio is failing with error:

```
Unable to find element with css selector == .some-ele
m (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 375 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_e
lement.html

```

because we are doing the reverse, this error should be consumed and not fail the command/test.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [5.7.12]
 - **Mode:** [ WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [8.10]
 - **NPM version:** [6.5.0]
 - **Browser name and version:** [ie 11]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/sauce]

**Config of WebdriverIO**
```
user: config.saucelabs.user,
    key: config.saucelabs.key,
    hostname: 'ondemand.saucelabs.com',
    maxInstances: 3,
    capabilities: [
        {
            browserName: 'internet explorer',
            platformVersion: 'Windows 10',
            browserVersion: '11.0',
        }
    ],
    mochaOpts: {
        ui: 'bdd',
        timeout: 120000,
        bail: true
    },
    services: ['sauce'],
    reporters: ['spec'],
    coloredLogs: true,
    deprecationWarnings: false
});
```

**Describe the bug**
waitForDisplayed , reverse should exit without an error if the element being waited for is not present.

**To Reproduce**
Run a spec that does the reverse of waitForDisplayed

```
it('should not throw an erro if element is not displayed', function () {
        browser.url('https://www.google.com');
        // console.log(JSON.stringify(browser.capabilities, null, 4));
        $('.some-elems').waitForDisplayed(30000, true);
    });
```

[Include code or an example repository that can easily be set up]

**Expected behavior**
The method should exit with no error, as it does on chrome and ff

**Log**
https://gist.github.com/pmerwin/63827f01be54809b7894288defe3e985

sauce job:
https://app.saucelabs.com/tests/afbd7f8d91944846bea0e2870a220b3b

**Additional context**
https://github.com/webdriverio/webdriverio/pull/3690 I think this issue may help with a fix here

**Comment by pmerwin** [comment] 2019-04-17 15:32
Safari is not working here, either.

**Comment by mgrybyk** [comment] 2019-04-23 20:40
@pmerwin works fine for me in Safari 12.1, please provide with reproducible example.

**Comment by StephenABoyd** [comment] 2019-04-23 20:41
@mgrybyk I think this will be fixed with #3874

**Comment by mgrybyk** [comment] 2019-04-23 20:43
Was reading logs and have to agree, will have to ask author to check this issue again in next WebdriverIO release

**Comment by pmerwin** [comment] 2019-04-23 20:55
I will test as soon as its published.

**Comment by pmerwin** [comment] 2019-04-29 20:13
Still seeing this on Edge:
```
[MicrosoftEdge  Windows 10 #0-0] The specified element was not found in the current frame or window. (WARNING: The se
rver did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: 'SAUCE-WIN10', ip: '10.100.22.158', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', j
ava.version: '1.8.0_131'
Driver info: driver.version: unknown
```

**Comment by wswebcreation** [comment] 2019-06-04 11:14
@christian-bromann 

This is still happening with Edge on Sauce Labs, see https://app.eu-central-1.saucelabs.com/tests/c9b50749426549c8ab0f651f6e777ce6

This is my script

```js
   /**
     * Wait for the element to be displayed
     *
     * @return {boolean}
     */
    waitForIsDisplayed(isShown = true) {
        return $(this.selector).waitForDisplayed(DEFAULT_TIMEOUT, !isShown);
    }
```

After the retry is fails with an error instead of returning `false`

**Comment by mgrybyk** [comment] 2019-08-04 22:24
@wswebcreation this one is not reproducible for me locally, tried in ie11 and edge (html) Version: 6.17134 | Microsoft Edge version supported: 17.17134

**Comment by christian-bromann** [comment] 2019-08-28 08:06
> this one is not reproducible for me locally

Closing then. Happy to reopen with a reproducible example script.

**Closed by christian-bromann** 2019-08-28 08:06 UTC
Labels: Bug🐛

**Comment by jbterry** [comment] 2019-08-30 13:27
i may still be seeing this issue. i've recently finished updating all my dependencies and during debugging i am seeing that while isDisplayedInViewport() returns `true` for clearly visible elements, waitForExist() and waitForDisplayed() are returning `false`

```
$("#pagelet_bluebar").waitForExist(2000)
/Users/jterry/cnn-qa/node_modules/@wdio/sync/build/wrapCommand.js:42
      throw e;
      ^

Error: element ("#pagelet_bluebar") still not existing after 2000ms
    at <anonymous>
    at evalmachine.<anonymous>:1:23
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at Object.runInContext (vm.js:120:6)
    at WDIORepl._runCmd (/Users/jterry/cnn-qa/node_modules/@wdio/repl/build/index.js:54:34)
    at /Users/jterry/cnn-qa/node_modules/@wdio/repl/build/index.js:46:58
[0-0] › 0-0 debugger result undefined
undefined
[0-0] › 0-0 debugger result undefined
[0-0] › $("#pagelet_bluebar").waitForDisplayed(2000)
/Users/jterry/cnn-qa/node_modules/@wdio/sync/build/wrapCommand.js:42
      throw e;
      ^

Error: element ("#pagelet_bluebar") still not displayed after 2000ms
    at <anonymous>
    at evalmachine.<anonymous>:1:23
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at Object.runInContext (vm.js:120:6)
    at WDIORepl._runCmd (/Users/jterry/cnn-qa/node_modules/@wdio/repl/build/index.js:54:34)
    at /Users/jterry/cnn-qa/node_modules/@wdio/repl/build/index.js:46:58
[0-0] › 0-0 debugger result undefined
undefined
[0-0] › 0-0 debugger result undefined
[0-0] › $("#pagelet_bluebar").isDisplayedInViewport()
true
[0-0] › 0-0 debugger result undefined
```

if you need more information just lmk -- pagelet_bluebar is just the facebook blue bar at the top of the page, so should be fairly easy to disprove. running locally on chrome 76.

**Comment by christian-bromann** [comment] 2019-08-30 13:43
> if you need more information just lmk

please provide a minimal reproducible example

**Comment by jbterry** [comment] 2019-08-30 15:10
on further testing, this appears to be an issue with `waitForX` methods not changing contexts from one tab to another. the following example will fail exactly as the `it()` blocks describe:

```
describe("new tab test", () => {
  it("reaches CNN", () => {
    browser.url("https://www.cnn.com/")
  })

  it("clicks the facebook social button", () => {
    $("button.optanon-alert-box-close.banner-close-button").click()  
    $( "svg.menu-icon" ).click()
    $( '[data-icon="facebook"]' ).scrollIntoView()
    $( '[data-icon="facebook"]' ).click()
  })

  it("returns true for isDisplayedInViewport", () => {
    $("#pagelet_bluebar").isDisplayedInViewport()
  })

  it("returns false for waitForExist", () => {
    $("#pagelet_bluebar").waitForExist(2000)
  })

  it("returns false for waitForDisplayed", () => {
    $("#pagelet_bluebar").waitForDisplayed(2000)
  })

  it("still returns true for isDisplayedInViewport", () => {
    $("#pagelet_bluebar").isDisplayedInViewport()
  })

})
```

notes:
- use of `switchWindow()` produces the exact same results
- navigating directly to the facebook.com url and running the same test steps will result in total success

sounds to me like a bug different that the one i found this thread for, i'll flip through the open issues docs and see if i find this already entered. trace log output will be added shortly

**Comment by jbterry** [comment] 2019-08-30 15:23
tracelog for above test failure: https://gist.github.com/jbterry/a35b285fbb10ca8ac287c8dc9cc24731

didn't see anything already open in issues, if you can reproduce this and believe this is a new issue i'll take the examples & data and go create one. thanks @christian-bromann !

**Comment by jbterry** [comment] 2019-08-30 18:24
ignore my comments, found the issue. switchWindow() does make the difference, i was getting unexpected constant success on `isDisplayedInViewport` because it doesn't fail out like waitForX will. all good here!
