### ISSUE TITLE
browser.isMobile and Google Chrome mobile emulation

### ISSUE THREAD

**Issue by flunderpero** [webdriverio/webdriverio#6560] opened 2021-03-07 16:42 UTC
I just removed my custom code to detect the platform in favour of using `browser.isMobile`. But to my surprise the Google Chrome mobile emulation is not recognised as being mobile.

I enable the emulation like this:
```
    capabilities: [
        {
            browserName: "chrome",
            "goog:chromeOptions": {
                args: chrome_args,
                mobileEmulation: {deviceName: "Pixel 2 XL"},
            },
        } as Capabilities,
    ],
```

`"goog:chromeOptions".mobileEmulation` is not taken into consideration in `envDetector.ts`.

My first question would be: Is this intended? I would say no, because it is an emulated mobile device. But I'm sure that others have a different opinion.

Regardless of that I still need a way to detect whether my PWA is rendered as "mobile". Should we add another flag like `browser.isMobileBrowser`?

I could provide the PR once I know what's the desired solution.

**Comment by christian-bromann** [comment] 2021-03-07 16:59
The `isMobile` flag is deferred from the capabilities and since you are running Chrome on a desktop machine the flag returns `false`. It is intended to help decide which automation is appropriate for the environment you are running your tests in. Even though you emulate a mobile device, all commands that work for desktop Chrome would still work which is why this is the intended behavior.

> Regardless of that I still need a way to detect whether my PWA is rendered as "mobile". Should we add another flag like `browser.isMobileBrowser`?

I would be happy to add the flag if this is a common practice and there is evidence that this would be helpful for a lot of people. Until then I recommend to just check your capabilities, e.g.:

```js
const isMobileEmulation = Boolean(browser.capabilities["goog:chromeOptions"].mobileEmulation)
```

Closing issue but happy to further discuss.

**Closed by christian-bromann** 2021-03-07 16:59 UTC

**Comment by flunderpero** [comment] 2021-03-07 17:11
@christian-bromann Thanks for the clarification. I use this flag (better: tried to use) to distinguish between the modes of our application. The UI differs whether it is open in a mobile or a desktop browser. We test using appium, too, but again, we test the web-app in the browser. So our tests would need to check `browser.isMobile || isMobileEmulation`. We had our own logic for this which would actually use the `platform` package to decide that for us. I thought it to be overkill once I saw that there's `isMobile`. :-)

The meaning of `isMobile` is more `isAppium && it's a browser` then.

I go back to a custom implementation then.
