### ISSUE TITLE
Tests passed in the browserstack are finished with error

### ISSUE THREAD

**Issue by andikfil** [webdriverio/webdriverio#2434] opened 2017-11-10 15:45 UTC
## The problem
Tests passed in the browserstack are finished with error:

>
ERROR:
chrome
Error
    at new RuntimeError (\Projects\...\node_modules\webdriverio\build\lib\utils\ErrorHandler.js:144:12)
    at Request._callback (\Projects\...\node_modules\webdriverio\build\lib\utils\RequestHandler.js:318:39)
    at Request.self.callback \Projects\...\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (\Projects\...\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (\Projects\...\node_modules\request\request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
ERROR: Session not started or terminated
    at new RuntimeError (\Projects\...\node_modules\webdriverio\build\lib\utils\ErrorHandler.js:144:12)
    at Request._callback (\Projects\...\node_modules\webdriverio\build\lib\utils\RequestHandler.js:318:39)
    at Request.self.callback (\Projects\...\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (\Projects\...\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (\Projects\...\node_modules\request\request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9) 

> 

This error breaks the reporter's output

## Environment

* WebdriverIO version: 4.9.5
* Node.js version: 6.10.3

## Details

I found problematic commit
https://github.com/webdriverio/webdriverio/commit/752bb60b09cc3aeba526eae1d679a5a0fcca4e19#diff-faed32601c42612df113897c056a1a22

 lib/helpers/utilities.js -> 25 line always returns false for our case when test is finished and Browserstask returns response: { state: 'success', status: 0 }

**Comment by christian-bromann** [comment] 2017-11-10 15:52
Duplicate of #2429

**Closed by christian-bromann** 2017-11-10 15:52 UTC
