### ISSUE TITLE
[🐛 Bug]: XPath locators work differently since v9

### ISSUE THREAD

**Issue by TimmiTester** [webdriverio/webdriverio#13525] opened 2024-09-06 12:20 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.0.6

### Node.js Version

v20.10.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
        browserName: 'chrome',
        'goog:chromeOptions': {
            args: ['--disable-gpu', '--start-maximized', "--window-size=960,540"],
        }
}
```

### What happened?

Since we updated to v9,
1.XPAth doesn't allow to search globally when called from some parent
![image](https://github.com/user-attachments/assets/149e8d63-d367-4a45-b043-257181a27567)
2. After research on point 1, I found no way to make any other axes work. Below are my attempts to get anything from axes and without them. Axes attempts were not successful
![image](https://github.com/user-attachments/assets/31714a51-16be-4d79-b51f-857e42126855)

### What is your expected behavior?

With proper axes usage, user can decide should he follow relative search or use absolute path
$("button").$("//body") should give me body element
$("button").$(".//body") should give me error, because I point to the fact I want search from the context

Why I think this is useful, is because there can be layout objects, when they look combined on UI but parts are placed separately within layout. It makes harder to build proper wrapper classes for such elements. For our project we have multiple dropdown elements, that have 'expand' button deep in layout, but all options are sitting separately close to 'body'

### How to reproduce the bug.

        browser.url("https://webdriver.io/");
        const arr = [];
        arr.push(await $("[class*='buttons']").$("/ancestor::body/div"));
        arr.push(await $("[class*='buttons']").$("./ancestor::body/div"));
        arr.push(await $("[class*='buttons']").$("//ancestor::body/div"));
        arr.push(await $("[class*='buttons']").$(".//ancestor::body/div"));
        const found = arr.filter(e => !e.error).map(e => e.selector);
        
[log.txt](https://github.com/user-attachments/files/16907675/log.txt)

### Relevant log output

```typescript
the log is too big, attached to the previous block
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2024-09-24 00:12
> 1.XPAth doesn't allow to search globally when called from some parent

Fetching an element from a parent object will limit the lookup scope to the parent inner DOM. This means starting your query with `//...` will still be limited to the parent scope. I don't see why WebdriverIO should allow escaping from it since you technically can always do root look up via `browser.$('//...')`. Yes, this may be a regression from v8 as we have implemented a whole new selector engine with WebDriver Bidi which does such element look ups differently.

> It makes harder to build proper wrapper classes for such elements.

Can you elaborate why this makes it harder for you? Can't you just check if the selector starts with `//` and if so , make the query from the root, e.g. `browser.$(...)`?

**Comment by TimmiTester** [comment] 2024-09-24 10:07
@christian-bromann it's not hard, but it requires additional attention to context. Plus the described limitation blocks usage for XPath axes, like ancestor, parent and others. 
Imho, XPath itself perfectly sets the context through own syntax. I undesrstand that from framework point of view it's better to have consistent expectations from parent-child relations, but this works when user doesn't know about XPath in details.

**Comment by christian-bromann** [comment] 2024-09-28 22:01
> Imho, XPath itself perfectly sets the context through own syntax.

This syntax needs to be understood well, which not everyone can say about themselves.

I will go ahead and close this issue as this seems to be a limitation to WebDriver Bidi and can't be directly fixed in WebdriverIO. If you have a use case that worked in v8 but doesn't in v9, please let me know. WebdriverIO provides a lot of primitives, e.g. `parentElement()`, `previousElement()` or `nextElement()` which should provide enough power to swing through the DOM to access any element.

We however are always open to ideas and comments on how to improve the current selector engine.

**Closed by christian-bromann** 2024-09-28 22:01 UTC
Labels: Bug 🐛, Information Missing
