### ISSUE TITLE
Webdriver-io test works with chrome but fails with firefox & safari #webdriverio #firefox #safari

### ISSUE THREAD

**Issue by jineshkhimsaria** [webdriverio/webdriverio#5419] opened 2020-05-19 16:29 UTC
I'm trying to open airbnb.com & just click login button. 
I'm using selenium-standalone-service (for chrome & firefox) & safari-technology-preview (for safari browser). 

Chrome - The above steps of going to url & clicking login button work properly in Chrome.
Firefox - The same steps work in Firefox but throw error at the end - "**_ERROR webdriver: Request failed with status 404 due to invalid session id: No active session with ID B9DC6483-9125-4549-BE2C-7C5940074DE3
[0-0] 2020-05-19T15:39:02.716Z ERROR @wdio/local-runner: Failed launching test session: invalid session id: No active session with ID B9DC6483-9125-4549-BE2C-7C5940074DE3_**" Safari - In safari only the 1st step works, clicking on button fails & the error is same as above. 

Any leads on what is going wrong? Thanking you in advance

My package.json - 
```
{
  "name": "wdio_playground",
  "version": "1.0.0",
  "description": "Playground for WebdriverIO",
  "main": "index.js",
  "scripts": {
    "test": "wdio"
  },
  "author": "Jinesh Khimsaria",
  "license": "ISC",
  "devDependencies": {
    "@wdio/allure-reporter": "^6.1.12",
    "@wdio/cli": "^6.1.12",
    "@wdio/local-runner": "^6.1.12",
    "@wdio/mocha-framework": "^6.1.8",
    "@wdio/selenium-standalone-service": "^6.0.16",
    "@wdio/sync": "^6.1.8",
    "chai": "^4.2.0",
    "chai-webdriverio": "^1.0.0",
    "local-runner": "^0.1.1-alpha",
    "webdriverio": "^6.1.12"
  }
}
```

In wdio.conf.js, only browserName is specified as "safari" or "firefox" or "chrome" depending on what i use

**Comment by christian-bromann** [comment] 2020-05-19 17:53
Can you provide a minimal reproducible example?

**Comment by jineshkhimsaria** [comment] 2020-05-19 18:02
[Archive.zip](https://github.com/webdriverio/webdriverio/files/4652304/Archive.zip)
This contains the code as well as package.json & wdio.conf.js
It's just a simple button click that i wanted to verify on multiple browsers using wdio

**Comment by erwinheitzman** [comment] 2020-05-19 22:14
Just tested with Firefox and works fine, the only issue I had was that `=Log in` didn't work since I have Firefox install in my mother tongue so after changing the selector to match that it's working as expected.
However that would be a downside of using selectors like this instead of using something more reliable like creating an element attribute called `data-testid="some-unique-value"`

**Comment by jineshkhimsaria** [comment] 2020-05-19 22:48
It worked for me as well but was getting above error in the console, you didn’t see any error or what?
And how about Safari? Did you try that?

**Comment by christian-bromann** [comment] 2020-05-20 09:39
This seems like a bug in Safaridriver where it fails to close the session if no window is present. Removing `browser.closeWindow()` fixes the issue. To reproduce this you can just run the following curl commands:

```sh
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"capabilities":{"browserName":"safari"}}' \
  http://localhost:4444/session

# without this curl it works
curl -i \
  --request DELETE \
  http://localhost:4444/session/824C18F6-2720-4A4D-AA44-7FD0D9C07794/window

curl -i \
  --request DELETE \
  http://localhost:4444/session/824C18F6-2720-4A4D-AA44-7FD0D9C07794
```

This can't be fixed in WebdriverIO and needs to be reported in the Safaridriver project.

**Closed by christian-bromann** 2020-05-20 09:39 UTC

**Comment by jineshkhimsaria** [comment] 2020-05-20 09:55
@christian-bromann - It's not about closing the session, the login button click doesn't work. Did it work for you?

**Comment by christian-bromann** [comment] 2020-05-20 10:00
> Did it work for you?

yes

**Comment by jineshkhimsaria** [comment] 2020-05-20 10:18
thanks, it worked for me too.
