### ISSUE TITLE
isDisplayed returns incorrect value in some cases

### ISSUE THREAD

**Issue by ablok** [webdriverio/webdriverio#5534] opened 2020-06-23 10:01 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1.20 (but also happens on latest version 5)
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.16.2
 - **NPM version:** 6.14.4
 - **Browser name and version:** Chrome 83.0.4103.106
 - **Platform name and version:** macOS Catalina 10.15.5 (but also on my Windows VM)

**Config of WebdriverIO**
Sample project can be found here:
https://github.com/ablok/ChromeDriverTest

**Describe the bug**
When running isDisplayed on the element that is in the sample repo, Chrome returns true, but Firefox returns false. I also tried it for Chromium Edge and that also returns false. The expected value is false.

**To Reproduce**
npm install & npm test in the sample repository: https://github.com/ablok/ChromeDriverTest

**Expected behavior**
Chrome should also return false

**Log**
Are stored in the logs folder of the sample project when you run it

**Additional context**
It looks like the script that is used in Chrome does not correctly determine the visibility of the element.

**Comment by ablok** [comment] 2020-06-23 10:04
As @erwinheitzman pointed out to me on gitter, this probably also happens for Safari since that uses the same script.

**Comment by christian-bromann** [comment] 2020-06-23 10:18
Would be great if someone could investigate why the [`isElementDisplayed`](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/scripts/isElementDisplayed.js) script returns `true` for Chrome and propose a fix for it. Any help would be very appreciated.

**Comment by erwinheitzman** [comment] 2020-06-23 18:25
It returns true because it sees one it's children's width/height being greater then 0. However I doubt we should be using this script for visibility and perhaps look at the way that Selenium is handling visibility at the moment since the script we are using is from Apple's Safari Atom which hasn't been touched for 3 years.

**Comment by erwinheitzman** [comment] 2020-06-23 18:27
Also for now a fix would be to rely on the ChromeDriver implementation with the risk that some day it might be removed

**Comment by christian-bromann** [comment] 2020-06-23 20:55
> However I doubt we should be using this script for visibility and perhaps look at the way that Selenium is handling visibility at the moment since the script we are using is from Apple's Safari Atom which hasn't been touched for 3 years.

I agree with that. Let's use a different Atom then.

> Also for now a fix would be to rely on the ChromeDriver implementation with the risk that some day it might be removed

Let's try to use a valid Atom to ensure cross browser compatibility.

**Comment by christian-bromann** [comment] 2020-06-24 10:15
I found the code in the [Selenium codebase](https://github.com/SeleniumHQ/selenium/blob/b8ef89b47b0e1ca422c21baf101738f512d2f535/javascript/atoms/dom.js#L555-L616). I am not sure if this one is any better than the Selenium one. There might be a better Atom in the Chromedriver code.

**Comment by erwinheitzman** [comment] 2020-06-24 11:37
I found that ChromeDriver uses that same method under the hood https://github.com/SeleniumHQ/selenium/blob/8ea80770657e83a5d8bebd0562952e120e38b70e/javascript/atoms/dom.js#L573

Reference: https://github.com/bayandin/chromedriver/blob/6580a995766dafe0a8dfdc0bc405ce487570045b/element_commands.cc#L754

**Comment by ablok** [comment] 2020-06-27 08:27
I updated my example repo with a case where firefox also doesn't seem to display correct visibility. Is that a bug in the geckodriver implementation then?

**Comment by jlchereau** [comment] 2021-02-06 16:17
I have an overlay for FOUJUI which is removed with `$('body>div.k-loading-image').delay(250).fadeOut();` after everything is loaded and ready for display. The following constantly times out since upgrading to webdriver v6.11.0 (was working in v6.10.+). 

```
$('body>div.k-loading-image').waitForDisplayed({
    timeout: 2000,
    reverse: true,
});
```

Maybe this helps...

**Comment by erwinheitzman** [comment] 2023-12-10 16:47
Closing this as the original repo has been deleted so we can no longer reproduce this and the command has been updated a lot in the meantime with fixes for cases like this.

**Closed by erwinheitzman** 2023-12-10 16:47 UTC
Labels: Needs Investigation, help wanted, good first pick
