### ISSUE TITLE
Errors not reporting useful line number in call stack

### ISSUE THREAD

**Issue by mherodev** [webdriverio/webdriverio#2639] opened 2018-03-09 21:26 UTC
## The problem

When an error is thrown, I am seeing a call stack which points to a line within webdriverio code instead of to the line of the test which failed. This makes it difficult to know, for example, which click within a test was the click which didn't register correctly.

e.g.

```
1) My Example Test:
unknown error: Element <label for="val_1">...</label> is not clickable at point (108, 20). Other element would receive the click: <a href="/" class="header">...</a>
running Chrome on OS X 10.10
Check out job at https://saucelabs.com/tests/09as8d09a8sd098asd098as098asd098as
Error: An unknown server-side error occurred while processing the command.
    at elementIdClick("0.8803705949365321-14") - click.js:20:22
```

I wish this error pointed to the test file and the line of the click.

## Environment

* WebdriverIO version: 4.10.2
* Node.js version: 8.9.4
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):

**Comment by Gary-Osteen-Q2** [comment] 2018-03-09 21:50
Thanks for logging this issue. I was just getting around to logging this same thing.
I'm running:
WebdriverIO: 4.12.0
Node: v8.9.4

```
describe('Sand Box', function() {
  it('Stack Traces', function() {
    var x = 10

    // Handled good and staces are visible with relavent fail lines
    // x.should.equal(11)
    // var y = x + z
    // throw (new Error('I threw the game.'))

    // Failed to give target line stacktrace
    // browser.click('alskdjf')
    browser.waitForVisible('lakdsjf', 1000)
  })
}
```

Output:
```
ERROR: An element could not be located on the page using the given search parameters.

    no stack available
F

ERROR: element ("lakdsjf") still not visible after 1000ms

    no stack available
F
```

**Comment by alfonso-presa** [comment] 2018-03-19 15:50
I'm seeing something similar. The index.js file of wdio-sync, in it's 237 line is being displayed as "culprit" for the Errors.

I've confirmed that changing this line: https://github.com/webdriverio/webdriverio/blob/master/lib/webdriverio.js#L600

To
```js
let lineInTest = stack.split('\n').slice(3, 4).join('\n')
```
solves my issue and file and position starts displaying correctly.

I can try to PR, thought:
1. I'm not sure of the collateral damage that this change might take
2. I don't think parsing the stack trace and taking arbitrary lines from it is a good practice to get this information, as it's very error prone.

**Comment by Gary-Osteen-Q2** [comment] 2018-03-19 16:59
I agree Alfonso. The stack traces works in node 6, so changing that line to parse a different line will likely break it in node 6 even if it fixes it in node 8. Just a guess right now though.

**Comment by Gary-Osteen-Q2** [comment] 2018-03-19 17:21
I changed this locally and your fix didnt' work for me. Still same results of 'no stack available'.

**Comment by alfonso-presa** [comment] 2018-03-20 07:26
I'm also in node 8.9.4 and wdio 4.12.0 and I can't reproduce your issue. I get the following:

```
Sand Box Stack Traces:
element ("lakdsjf") still not visible after 1000ms
running chrome
Error: element ("lakdsjf") still not visible after 1000ms
    at elements("lakdsjf") - safeExecute.js:28:24
```

Though, it's true that I don't get the file in which the test is but the wdio's safeExecute.js internal file, even with my patch :-(.

**Comment by alfonso-presa** [comment] 2018-03-20 12:12
I've been able to get some useful stacktrace information by adding the following to the `before` hook:

```js
    Object.keys(Object.getPrototypeOf(global.browser)).forEach((commandName) => {
      let origFn = global.browser[commandName];
      global.browser[commandName] = function () {
          try {
              return origFn.apply(this, arguments);
          }catch( e) {
              Error.captureStackTrace(e);
              throw e;
          }
      }.bind(global.browser); 
    });
```

I think the main issue is due to the monkey patching performed by wdio-sync... Maybe webdriver-io should monkey patch on top to ensure stacktraces are preserved....

**Comment by mherodev** [comment] 2018-03-20 21:10
@alfonso-presa That works great for native commands! For my custom commands, the stack trace points inside the command definition unfortunately.

**Comment by alfonso-presa** [comment] 2018-03-21 07:26
@mherodev, are you registering the custom commands before executing the patch? If not, you should do it so, as it will not work for commands registered after the patch is executed.

**Comment by mherodev** [comment] 2018-03-22 18:29
@alfonso-presa In the `before` hook I'm calling them like so

```
addCustomCommands();
improveStackTrace();
```

The issue is that our custom commands are typically wrappers for native commands and don't use context, so the stack trace bubbles only to the custom command's definition, instead of the location where that custom command was called.

e.g. Here's a custom command we're using to make sure an element is not hidden under our footer/header before clicking. 

```
function scrollClick(element) {
  if (!element || !element.selector) {
    throw new Error('scrollClick: missing required element');
  }
  browser.scroll(element.selector, 0, -110);
  browser.click(element.selector);
}
```

It occurs to me though that we're not actually taking advantage of context (since we had element chaining issues) and that these are less "custom commands" than a helper lib piggybacking on  `browser`. 

I think we can probably get the same functionality and better stack traces if we just replace `browser.addCommand` calls with `browser.commandName = ...`

**Comment by ragu-ravi** [comment] 2018-04-20 17:01
@alfonso-presa I tried the above patch you mentioned 
```
function improveStackTrace() {
   Object.keys(Object.getPrototypeOf(global.browser)).forEach(commandName => {
     const origFn = global.browser[commandName];
     global.browser[commandName] = function() {
       try {
         return origFn.apply(this, arguments);
       } catch (e) {
         Error.captureStackTrace(e);
         throw e;
       }
     }.bind(global.browser);
   });
}
```
and tried to call that under `before` hook, it gets called but not giving enough stacktrace informatiion like the line number, file name, etc., I am using node `8.9.4` and webdriverio `4.12.0`

**Comment by KGBemployee** [comment] 2018-05-16 12:56
I have also encountered this issue. It would be nice if, when running a test spec and get a fail, we could have the stacktrace show the line where the problem occurred.
Things like this aren't really informative:
`Failed: element not visible
[chrome #0-0] Error: An element command could not be completed because the element is not visible on the page.
[chrome #0-0]     at elementIdClick("0.5316202364119931-7") - click.js:20:22`

Has anything been done on this?

**Comment by KGBemployee** [comment] 2018-05-16 18:28
Hm, i've tried his solution but haven't had any luck. Perhaps I'm doing something wrong. 
@alfonso-presa could you please give more detailed steps for your workaround?
Thank you!

**Comment by mherodev** [comment] 2018-05-16 19:02
All of the details are there, but I'll reiterate them here:

improveStackTrace.js
```javascript
function improveStackTrace() {
  Object.keys(Object.getPrototypeOf(global.browser)).forEach(commandName => {
    const origFn = global.browser[commandName];
    global.browser[commandName] = function(...args) {
      try {
        return origFn.apply(this, args);
      } catch (e) {
        Error.captureStackTrace(e);
        throw e;
      }
    }.bind(global.browser);
  });
}

module.exports = improveStackTrace;
```

default.conf.js
```javascript

const defaultConfig = {
  before() {
    addCustomCommands();
    browser.windowHandleSize({ width: 960, height: 1200 });
    browser.currentUrl = null;
    Object.assign(browser, {
      baseUrl,
      baseUrlMobile,
      ecustCookie,
      isDev: env === 'dev',
      isProd: env === 'prod',
      isQA: env === 'qa',
      isDark: env === 'dark',
    });
    improveStackTrace();
  },
  // etc.
}
```

**Comment by marcelas** [comment] 2018-05-18 14:11
This doesn't seem to work when using things like: $('.selector').waitForVisible()
Those will still get 
```
Error: element (".selector") still not visible after 20000ms
    at elements(".selector") - isVisible.js:54:17
    at isVisible(".selector") - waitForVisible.js:73:22
```

@mherodev have you got this working as well?

**Comment by KGBemployee** [comment] 2018-05-18 18:30
I've actually found a working solution for this, but it's an ugly one that shouldn't really be done. It did work for me.
It has no negative effect, as far as I can tell, and the exact line and file is present in the output.
I know a PR probably wouldn't be approved with something like this but at least leave it here as a quick and dirty fix.

My setup is:

```javascript
 "devDependencies": {
    "allure-commandline": "^2.5.0",
    "babel-cli": "^6.26.0",
    "babel-preset-env": "^1.6.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-node8": "^1.2.0",
    "jasmine-data-provider": "^2.2.0",
    "wdio-allure-reporter": "^0.5.1",
    "wdio-browserstack-service": "^0.1.14",
    "webdriver-manager": "^12.0.6",
    "webdriverio": "^4.12.0"
  },
  "dependencies": {
    "babel-register": "^6.26.0",
    "wdio-jasmine-framework": "^0.3.2"
  }
```

In wdio-sync\build\index.js I've added the following to the sanitizeErrorMessage function:

```javascript
var sanitizeErrorMessage = function sanitizeErrorMessage(e) {

    let myStackTrace;

    /**
     * Because the error obejct does not contain the entire stack trace we attempt to get the caller of the method from
     * the prototype chain. Because the 'use stric' directive is used, the caller is unreacheable but a new error is
     * thrown that cotains the entire stack, including the line in the test where the initial failure was recorded.
     */
    try{
        var line = Object.getPrototypeOf(e).__proto__.constructor.__proto__.caller;
    }catch(e){
        myStackTrace = e.stack.split('\n').slice(2,7).join('\n');
    }

```

And at the end of the function I also added something:

```javascript
  /**
     * add back error message
     */
    if(myStackTrace !== undefined) {
        stack.unshift(errorMsg + '\n' + myStackTrace);
    }else{
        stack.unshift(errorMsg);
    }
    return stack.join('\n');
};
````

**Comment by mherodev** [comment] 2018-05-18 20:32
@marcelas I believe we're getting proper traces for waitForVisible, yes.

**Comment by Gary-Osteen-Q2** [comment] 2018-05-31 14:49
Some added info into the varying stack trace results.

Using one browser vs multiple target browsers matters. I have a setup where one test requires two unique browser sessions to bypass local storage constraints.

When using browser.commandName() I get no stack available message.

If I use cb1.commandName() to target a specific browser created in the wdio.conf.js file, in this case cb1 means chrome browser 1, Then I get a stack trace, but no useful line numbers that trace back to my code. It gets stuck in the node_modules.

**Comment by haukot** [comment] 2018-06-01 13:33
I also encountered this issue, thanks @mherodev for the workaround!
Only thing, the workaround works great for functions like `browser.waitForVisible('some_element')`, but not for `browser.element('some_element').waitForVisible()`. Maybe

This is my slightly more complicated solution for fix track trace of element functions too
```

function wrapMethods (element, commands, options = {}) {
  const { makeCopy } = options

  const functions = makeCopy ? {} : element

  commands.forEach(commandName => {
    const origFn = element[commandName]
    functions[commandName] = function (...args) {
      try {
        if (commandName === 'element') {
          // so browser.element('.some').element('.elem').click()
          // will also have better stack trace
          // You also can add waitForVisible and other functions here
          return wrapMethods(origFn.apply(this, args), ['click', 'element'], {makeCopy: true})
        } else {
          return origFn.apply(this, args)
        }
      } catch (e) {
        Error.captureStackTrace(e)
        throw e
      }
    }.bind(element)
  })

  // Functions .click in elements is read-only. So by this way we make copy-like of the element
  return new Proxy({}, {
    get (target, prop) {
      if (functions[prop]) {
        return functions[prop]
      } else {
        return element[prop]
      }
    },

    set (target, prop, value) {
      return element[prop] = value
    }
  })
}

function improveStackTrace () {
  const commands = Object.keys(Object.getPrototypeOf(global.browser))
  wrapMethods(global.browser, commands)
}

module.exports = improveStackTrace

```

In our environment it works great

**Comment by Gary-Osteen-Q2** [comment] 2018-07-06 20:16
I modified @mherodev script and threw it in my before hook. I have 3 copies of the pattern because I have a test that requires two browsers at the same time that don't share session cache, named cb1 and cb2. These as far as I can tell have their own methods outside of the browser global.

```javascript
before: function(/* capabilities, specs */) {
    const chai = require('chai')
    global.assert = chai.assert
    chai.should()

    Object.keys(Object.getPrototypeOf(global.browser)).forEach((commandName) => {
      let origFn = global.browser[commandName]
      global.browser[commandName] = function() {
        browser.lastCommandLocation = new Error().stack.split('\n').slice(2, -1).join('\n')
        return origFn.apply(this, arguments)
      }.bind(global.browser)
    })

    Object.keys(Object.getPrototypeOf(global.cb1)).forEach((commandName) => {
      let origFn = global.cb1[commandName]
      global.cb1[commandName] = function() {
        cb1.lastCommandLocation = new Error().stack.split('\n').slice(2, -1).join('\n')
        return origFn.apply(this, arguments)
      }.bind(global.cb1)
    })

    if ((browser.options.cb2)) {
      Object.keys(Object.getPrototypeOf(global.cb2)).forEach((commandName) => {
        let origFn = global.cb2[commandName]
        global.cb2[commandName] = function() {
          cb2.lastCommandLocation = new Error().stack.split('\n').slice(2, -1).join('\n')
          return origFn.apply(this, arguments)
        }.bind(global.cb2)
      })
    }

    // Setting default view port size for all specs.
    browser.setViewportSize({width: 900, height: 858})
  },
```

This actually gives me more useful logging as I am able to find out which command was used on each instance of the browser at the time of the test failure. Typically, the failure for browser will always point to the `browser.setViewportSize({width: 900, height: 858})` in the wido.conf.js file, which one way might be very useful. Then I can see the prior commands on both cb1 and cb1 browsers.

```javascript
afterTest: function(test) {
    if (test.passed === false) {
      console.log(`\n*** ${test.fullTitle} fail logs ***`)
      console.log('Last Browser Command Location:\n', browser.lastCommandLocation)
      console.log('Last CB1 Command Location:\n', cb1.lastCommandLocation)
      if (browser.options.cb2) {
        console.log('Last CB2 Command Location:\n', cb2.lastCommandLocation)
      }
      console.log(`*** End of logs for ${test.fullTitle} ***\n`)
    }
  },
```

I must admit I don't run parallel tests at the moment. If someone tries this bypass using parallel testing, please let me know how it works out. One day soon I will want to run these 3 at a time at least.

I don't use custom commands, but this might even work for custom commands without changing the code I have as along as it gets added before the object prototype loops.

**Comment by christian-bromann** [comment] 2018-10-31 23:02
If anyone is interested in a fix for this, feel free to propose a PR on the v4 branch. This is most likely fixed in v5.

**Closed by christian-bromann** 2018-10-31 23:02 UTC
Labels: Bug

**Comment by pyxis828** [comment] 2019-02-05 17:54
@KGBemployee  Your solution worked beautifully for me.  Thank you.

**Comment by KGBemployee** [comment] 2019-02-06 07:58
@pyxis828 you're welcome! Glad it helped.

**Comment by GineaPig** [comment] 2019-02-24 22:30
This doesn't look fixed on v5, any work around for v5?

**Comment by mgrybyk** [comment] 2019-02-25 06:56
Should be fixed in v5

**Comment by miroslawmajka** [comment] 2019-09-11 20:41
Does not look fixed as of today either:
`
[chrome 76.0.3809.132 Windows NT #0-0] Spec: C:\GitHub\cucumber-boilerplate\features\sample.feature
[chrome 76.0.3809.132 Windows NT #0-0] Running: chrome (v76.0.3809.132) on Windows NT
[chrome 76.0.3809.132 Windows NT #0-0]
[chrome 76.0.3809.132 Windows NT #0-0] Sample Cucumber Feature
[chrome 76.0.3809.132 Windows NT #0-0]     Sample Scenario for "google" website
[chrome 76.0.3809.132 Windows NT #0-0]        ✓ Given I open "google" website
[chrome 76.0.3809.132 Windows NT #0-0]        ✓ When I get the text value of the sample element
[chrome 76.0.3809.132 Windows NT #0-0]        ✓ Then I verify that the expected text value equals "About"
[chrome 76.0.3809.132 Windows NT #0-0]
[chrome 76.0.3809.132 Windows NT #0-0]     Sample Scenario for "github" website
[chrome 76.0.3809.132 Windows NT #0-0]        ✓ Given I open "github" website
[chrome 76.0.3809.132 Windows NT #0-0]        ✖ When I get the text value of the sample element
[chrome 76.0.3809.132 Windows NT #0-0]        - Then I verify that the expected text value equals "Features"
[chrome 76.0.3809.132 Windows NT #0-0]
[chrome 76.0.3809.132 Windows NT #0-0] 4 passing (7.9s)
[chrome 76.0.3809.132 Windows NT #0-0] 1 failing
[chrome 76.0.3809.132 Windows NT #0-0] 1 skipped
[chrome 76.0.3809.132 Windows NT #0-0]
[chrome 76.0.3809.132 Windows NT #0-0] 1) Sample Scenario for "github" website When I get the text value of the sample element
[chrome 76.0.3809.132 Windows NT #0-0] element ("/html/body/div[1]/header/div/div[2]/nav/ul/li[1]/a") still not existing after 5000ms
[chrome 76.0.3809.132 Windows NT #0-0] Error: element ("/html/body/div[1]/header/div/div[2]/nav/ul/li[1]/a") still not existing after 5000ms
[chrome 76.0.3809.132 Windows NT #0-0]     at timer.catch.e (C:\GitHub\cucumber-boilerplate\node_modules\webdriverio\build\commands\browser\waitUntil.js:30:15)
[chrome 76.0.3809.132 Windows NT #0-0]     at Element.runCommandWithHooks (C:\GitHub\cucumber-boilerplate\node_modules\@wdio\sync\build\wrapCommand.js:48:22)
[chrome 76.0.3809.132 Windows NT #0-0]     at Element.wrapCommandFn (C:\GitHub\cucumber-boilerplate\node_modules\@wdio\sync\build\wrapCommand.js:25:40)
[chrome 76.0.3809.132 Windows NT #0-0]     at Element.elementErrorHandlerCallbackFn (C:\GitHub\cucumber-boilerplate\node_modules\webdriverio\build\middlewares.js:21:57)
[chrome 76.0.3809.132 Windows NT #0-0]     at Element.elementErrorHandlerCallback (C:\GitHub\cucumber-boilerplate\node_modules\webdriverio\build\middlewares.js:40:8)
[chrome 76.0.3809.132 Windows NT #0-0]     at Element.waitForExist (C:\GitHub\cucumber-boilerplate\node_modules\webdriverio\build\commands\element\waitForExist.js:15:15)
[chrome 76.0.3809.132 Windows NT #0-0]     at Element.wrapCommandFn (C:\GitHub\cucumber-boilerplate\node_modules\@wdio\sync\build\wrapCommand.js:20:17)
[chrome 76.0.3809.132 Windows NT #0-0]     at Function.getElementText (C:\GitHub\cucumber-boilerplate\page-objects\page.js:13:12)
[chrome 76.0.3809.132 Windows NT #0-0]     at CustomWorld.<anonymous> (C:\GitHub\cucumber-boilerplate\features\step_definitions\steps.js:31:50)
[chrome 76.0.3809.132 Windows NT #0-0]     at C:\GitHub\cucumber-boilerplate\node_modules\@wdio\sync\build\runFnInFiberContext.js:16:27
`

**Comment by mgrybyk** [comment] 2019-09-12 00:01
Ah, it might be windows related issue.
It would be better to raise another issue and specify that you are running tests on windows
