### ISSUE TITLE
Can't find fullTitle property of test after upgrading to wdio6

### ISSUE THREAD

**Issue by unickq** [webdriverio/webdriverio#5373] opened 2020-05-07 08:03 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1.9 and 5.22
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.14.1
 - **NPM version:** 6.13.4
 - **mocha**: 7.1.2 
 - **@wdio/mocha-framework**: 6.1.8 and 5.18.7

**Config of WebdriverIO**
```ts
  afterTest: (test: any, _context: any, result: any): void => {
    console.log(`Title: ${test.title}`);
    console.log(`FullTitle: ${test.fullTitle}`);
  }
```

**Describe the bug**
After upgrade to wdio6 fullTitle property missed. 
```js
describe("Cards PrintNow Finish option", () => {
  describe("Preview", () => {
    it("Preview loads", () => {
    });
  });
});
```

### wdio6 output
```
Execution of 1 spec files started at 2020-05-07T07:56:21.230Z

[0-0] RUNNING in chrome - C:\Git\**\sendNow.spec.ts
[0-0] Title: Preview loads
[0-0] FullTitle: undefined
```

### wdio5 output
```
Execution of 1 spec files started at 2020-05-07T07:54:21.691Z

[0-0] RUNNING in chrome - C:\Git\**\sendNow.spec.ts
[0-0] Title: Preview loads
[0-0] FullTitle: Cards PrintNow Finish option Preview Preview loads
Preview loads: passed
```

**Comment by christian-bromann** [comment] 2020-05-07 11:41
Have you checked what the `test` param returns?

```js
  afterTest: (test: any, _context: any, result: any): void => {
    console.log(test);
  }
```

**Comment by unickq** [comment] 2020-05-07 11:58
I checked all sub properties and didn't find fullTitle

**Comment by mgrybyk** [comment] 2020-05-07 12:00
It might be that full title was the proprerty computed by webdriverio by concatenation of suite and title

**Comment by christian-bromann** [comment] 2020-05-07 13:49
@mgrybyk is right, the test is directly coming from Mocha in v6 so you need to generate the full title by yourself doing `test.parent + ' ' + test.title`. Closing as this is not a bug and more an interface change.

**Closed by christian-bromann** 2020-05-07 13:49 UTC
