### ISSUE TITLE
Screenshot is not attached to report when using multiremote

### ISSUE THREAD

**Issue by tiecongli** [webdriverio/webdriverio#5447] opened 2020-05-29 00:16 UTC
Allure 5
appium + cucumber 

I follow the allure report instruction to enable screenshot taken per each step. However, that doesn't work when I am using multiremote. No screenshot is attached after test

[0-0] -------- Generated capabilities --------
[0-0] {
  device1: {
    capabilities: {
      platformName: 'iOS',
      automationName: 'XCUITest',
      xcode_org_id: '[your_org_id]',
      xcode_signing_id: 'iPhone Developer',
      useNewWDA: false,
      usePrebuiltWDA: true,
      derivedDataPath: '[your_path_to_runner]'
      noReset: true,
      app: '[your_ipa_path]',
      bundleId: '[your_bundle_id]',
      processArguments: [Object],
      platformVersion: '13.4.1',
      deviceName: 'iPhone XS Max rose 512gb',
      udid: '00008020-001A2CD036C2002E',
      wdaLocalPort: 8100
    }
  },
  device2: {
    capabilities: {
      platformName: 'iOS',
      automationName: 'XCUITest',
      xcode_org_id: '[your_org_id]',
      xcode_signing_id: 'iPhone Developer',
      useNewWDA: false,
      usePrebuiltWDA: true,
      derivedDataPath: '[your_path_to_runner]',
      noReset: true,
      app: '[your_ipa_path]',
      bundleId: '[your_bundle_id]',
      processArguments: [Object],
      platformVersion: '13.4.1',
      deviceName: 'iPhone XS rose 512gb',
      udid: '00008020-000529020188002E',
      wdaLocalPort: 8101
    }
  }
}

**Comment by christian-bromann** [comment] 2020-05-29 07:02
duplicate of #4973

Any help on this would be highly appreciated. Cheers!

**Closed by christian-bromann** 2020-05-29 07:02 UTC
