### ISSUE TITLE
All Shadow DOM operations are broken on devtools protocol

### ISSUE THREAD

**Issue by diervo** [webdriverio/webdriverio#5317] opened 2020-04-24 01:39 UTC
**Environment:**
 - **WebdriverIO version:** 5 & 6 (blocking on 6 by default)
 - **Mode:** TestRunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 14
 - **NPM version:** latests 5 & latest 6

**Config of WebdriverIO**
```
    maxInstances: 1,
    capabilities: [
        {
            maxInstances: 1,
            browserName: 'chrome',
        },
    ],
    automationProtocol: 'devtools',
```

**Describe the bug**
Any DOM operation that traverses the shadow directly or indirectly fails while using `devtools` protocol.

**To Reproduce**
Steps to reproduce the behavior: Run any test that access the shadow in any way, in this trivial example I just do getText() which should traverse the shadow by spec:

```
  it('basic test traversing shadow', async () => {
        await browser.url('http://localhost:8080');
        const counterElement = await browser.$('my-counter');
        const counterElementText = await counterElement.getText();
        console.log('>>>> counterElementText: ', counterElementText);
```

**Expected behavior**
Operations that traverse the shadow should work when using devtools protocol.

**Additional context**

It might be an issue with the protocol in itself, but I haven't look in pupeteer.

As a somewhat orthogonal observation, bootstraping with devtools/pupeteer its way slower than bootstraping with old selenium. Not sure if is my configuration, but just pointing as a potential future optimization.

**Comment by diervo** [comment] 2020-04-24 01:40
@christian-bromann FWIW, this is blocking us to upgrade to the latest version.

**Comment by christian-bromann** [comment] 2020-04-24 07:13
> which should traverse the shadow by spec:

I am not sure what you mean by that. This doesn't work even in WebDriver which is the reason we created the `shadow$` command. Here is a better example:

```js
(async function () {
    browser = await remote({
        // automationProtocol: 'devtools',
        capabilities: {
            browserName: 'chrome'
            'goog:chromeOptions': {
                args: ['--ignore-certificate-errors', '--ignore-ssl-errors=yes']
            }
        }
    })

    await browser.url('https://rawgit.com/ebidel/2d2bb0cdec3f2a16cf519dbaa791ce1b/raw/fancy-tabs-demo.html')
    await browser.pause(2000)
    const tabs = await browser.$('fancy-tabs')
    await (await tabs.shadow$('#panels')).getText()

    await browser.deleteSession()
})().catch(async (e) => {
    console.error(e.stack)
    await browser.deleteSession()
})
```

Which indeed does not work using Puppeteer. Looking at the error message is says:

> Element with selector "[data-devtoolsdriver-fetchedElement="__executeElement_0"]" not found

Which makes sense because Puppeteer allows only to select an element with one method `$` or `$x` and return an element reference with a different method `$eval`. This is why the devtools package marks an element and then uses that data parameter to return its reference which fails in the shadow DOM case because you can't use `document.querySelector` to look into all elements including their shadow DOMs.

**Comment by diervo** [comment] 2020-04-24 15:26
@christian-bromann yeah the example I provided was confusing, the point was that `getText()` in webdriver underneath uses an atom that does the shadow traversal to return the full text of all content correctly, in devtools returns nothing.

But to the point, your example its way more illustrative, so yeah any shadow operation doesn't work, and I assume that we want the result of the test to be the same regardless of the protocol.

You marked the issue as good first pick, will be happy to tackle but I would need some help from you to point me to the right set of files so I don't waste a lot of time.

As a final note, I don't seem to be able to switch in v6 between `selenium-standalone` and devtool. When using webdiver the runner seems to be hanging in a white screen.

**Comment by christian-bromann** [comment] 2020-04-30 11:58
Duplicate of #4484

**Closed by christian-bromann** 2020-04-30 11:58 UTC
Labels: Bug🐛, good first pick, help wanted
