### ISSUE TITLE
Override 'specs' and 'exclude' from CLI

### ISSUE THREAD

**Issue by georgecrawford** [webdriverio/webdriverio#807] opened 2015-09-28 10:47 UTC
I'd like to be able to quickly override the list of included specs with the CLI tool (in a similar way to running `'wdio --baseUrl='...'`, rather than editing the wdio.conf.js file or adding `describe.only` or 'describe.skip` to the spec files.

**Comment by christian-bromann** [comment] 2015-09-28 15:58
duplicate of #791

**Closed by christian-bromann** 2015-09-28 15:58 UTC
Labels: Enhancement

**Comment by georgecrawford** [comment] 2015-09-28 16:18
Oops, sorry. And I even commented on it. :-(
