### ISSUE TITLE
execute() never completes if target page had document.write()

### ISSUE THREAD

**Issue by sergey-su** [webdriverio/webdriverio#2519] opened 2017-12-15 13:56 UTC
## The problem

This code never completes if web page under test was filled by `document.write()`
```
driver
    .url(...)
    .execute('return 123')
    .then(a => {
        console.log(`got response ${a.value}`);
    })
```

## Environment

* WebdriverIO version: 4.9.11
* Node.js version: 8.0.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): standalone
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details

Reproduces with chrome and gecko drivers.

## Link to Selenium/WebdriverIO logs

```
[14:50:40]  COMMAND	POST 	 "/wd/hub/session"
[14:50:40]  DATA		{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"chrome","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.9.11","name":"webdriverio"}}}
[14:50:41]  INFO	SET SESSION ID d534645ab29f87a59030208ef40e0538
[14:50:41]  RESULT		{"applicationCacheEnabled":false,"rotatable":false,"mobileEmulationEnabled":false,"networkConnectionEnabled":false,"chrome":{"chromedriverVersion":"2.34.522932 (4140ab217e1ca1bec0c4b4d1b148f3361eb3a03e)","userDataDir":"/var/folders/hn/q_1g9rks2vx8p4jp6ryj_k542px85x/T/.org.chromium.Chromium.TmvA5s"},"takesHeapSnapshot":true,"pageLoadStrategy":"normal","databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":false,"version":"63.0.3239.84","platform":"Mac OS X","browserConnectionEnabled":false,"nativeEvents":true,"acceptSslCerts":true,"locationContextEnabled":true,"webStorageEnabled":true,"browserName":"chrome","takesScreenshot":true,"javascriptEnabled":true,"cssSelectorsEnabled":true,"setWindowRect":true,"unexpectedAlertBehaviour":""}
[14:50:41]  COMMAND	POST 	 "/wd/hub/session/d534645ab29f87a59030208ef40e0538/url"
[14:50:41]  DATA		{"url":"http://127.0.0.1:8080/freeze.html"}
```

## Code To Reproduce Issue [ Good To Have ]

See README in the attachment
[webdriver_freeze.zip](https://github.com/webdriverio/webdriverio/files/1562849/webdriver_freeze.zip)

**Comment by erwinheitzman** [comment] 2017-12-15 15:15
execute accepts a callback method, you are providing a string. I think that is the cause of your issue.

**Comment by sergey-su** [comment] 2017-12-15 15:24
http://webdriver.io/api/protocol/execute.html
script String/Function The script to execute.

**Comment by erwinheitzman** [comment] 2017-12-15 15:24
Have tried the same code with node 6.10 and can at least verify that this example works with your repo in that version. So there's something with webdriverio and nodejs v8+ it seems.

**Comment by sergey-su** [comment] 2017-12-15 15:37
I can also repro with node 5.7.1

**Comment by sergey-su** [comment] 2017-12-15 15:39
Just found the root cause: `document.write()` is not followed by `document.close()`. Probably browsers refuse to reply on webdriver commands until document is closed. Not sure if it's a bug or  by-design.

**Comment by christian-bromann** [comment] 2017-12-17 15:11
I think this is a driver issue and not a bug in WebdriverIO. Closing.

**Closed by christian-bromann** 2017-12-17 15:11 UTC
