### ISSUE TITLE
[🐛 Bug]: Attempt to set up browser/driver on Ubuntu gives Error: Error: Command failed: which google-chrome

### ISSUE THREAD

**Issue by twegener-embertec** [webdriverio/webdriverio#11250] opened 2023-09-26 07:30 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.16.12

### Node.js Version

v18.17.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    browserName: 'chrome',
    'goog:chromeOptions': {
        args: ['--headless', '--disable-gpu', '--window-size=1280,800'],
        binary: '/usr/bin/chromium-browser'
    }
}
```

### What happened?

Starting wdio failed with the following error:

```
Error: Error: Command failed: which google-chrome

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:323:12)
Error: Command failed: which google-chrome

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:323:12) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'which google-chrome',
  stdout: '',
  stderr: ''
}
```

### What is your expected behavior?

Should start wdio successfully and give output something like:

```
[0-0] RUNNING in chrome - file:///redacted
```

### How to reproduce the bug.

```
./node_modules/.bin/wdio vic/wdio.conf.js
```

Ubuntu 20.04.6 LTS

### Relevant log output

```typescript
Error: Error: Command failed: which google-chrome

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:323:12)
Error: Command failed: which google-chrome

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:323:12) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'which google-chrome',
  stdout: '',
  stderr: ''
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by twegener-embertec** [comment] 2023-09-26 07:33
I was able to work around this by making the following change:

```
diff --git a/packages/wdio-cli/src/launcher.ts b/packages/wdio-cli/src/launcher.ts
index 015914fda..e4c67e3f5 100644
--- a/packages/wdio-cli/src/launcher.ts
+++ b/packages/wdio-cli/src/launcher.ts
@@ -138,7 +138,7 @@ class Launcher {
             /**
              * pre-configure necessary driver for worker threads
              */
-            await Promise.all([
+            await Promise.allSettled([
                 setupDriver(config, caps),
                 setupBrowser(config, caps)
             ])

```

**Comment by twegener-embertec** [comment] 2023-09-26 07:35
Oops, a correction to my original reported details:
webdriverio version: 8.16.15

**Comment by erwinheitzman** [comment] 2023-09-26 07:42
Sounds like an error happens in one of the promises because you now ignore the reject using allSettled.

What happens if you run `which google-chrome` manually?

**Comment by twegener-embertec** [comment] 2023-09-26 10:26
```
$ which google-chrome ; echo $?
/usr/bin/which: no google-chrome in (/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/tim/.local/bin:/home/tim/bin)
1
```

That is expected, because I am using chromium rather than chrome.

```
$ which chromium-browser ; echo $?
/usr/bin/chromium-browser
0
```

Also, note that I have explicitly specified `binary: '/usr/bin/chromium-browser'` (see original description).

**Comment by christian-bromann** [comment] 2023-09-26 14:47
@twegener-embertec can you verify that you are using the latest WebdriverIO version?

**Comment by fleszczynski** [comment] 2023-09-26 16:45
I am having the same issue while trying to run over a gcloud function. Webdriverio is 8.16.12

**Comment by twegener-embertec** [comment] 2023-09-27 00:07
@christian-bromann 

```
$ grep 'version' node_modules/@wdio/*/package.json
node_modules/@wdio/cli/package.json:  "version": "8.16.15",
node_modules/@wdio/config/package.json:  "version": "8.16.15",
node_modules/@wdio/dot-reporter/package.json:  "version": "8.16.12",
node_modules/@wdio/globals/package.json:  "version": "8.16.15",
node_modules/@wdio/local-runner/package.json:  "version": "8.16.15",
node_modules/@wdio/logger/package.json:  "version": "8.11.0",
node_modules/@wdio/mocha-framework/package.json:  "version": "8.16.15",
node_modules/@wdio/protocols/package.json:  "version": "8.16.5",
node_modules/@wdio/repl/package.json:  "version": "8.10.1",
node_modules/@wdio/reporter/package.json:  "version": "8.16.12",
node_modules/@wdio/runner/package.json:  "version": "8.16.15",
node_modules/@wdio/spec-reporter/package.json:  "version": "8.16.12",
node_modules/@wdio/types/package.json:  "version": "8.16.12",
node_modules/@wdio/utils/package.json:  "version": "8.16.15",
```
```
$ grep 'version' node_modules/webdriver*/package.json
node_modules/webdriver/package.json:  "version": "8.16.15",
node_modules/webdriverio/package.json:  "version": "8.16.15",
```

**Comment by christian-bromann** [comment] 2023-10-02 20:54
Mhm .. not sure exactly where this is failing. Can someone provide a reproducible example as a `Dockerfile`?

**Comment by fleszczynski** [comment] 2023-10-03 16:41
Does this trace mean anything? 
  at checkExecSyncError (node:child_process:861:11)
    at Object.execSync (node:child_process:932:15)
    at getBuildIdByChromePath (file:///opt/atlassian/pipelines/agent/build/node_modules/@wdio/utils/build/driver/utils.js:41:30)
    at setupChromedriver (file:///opt/atlassian/pipelines/agent/build/node_modules/@wdio/utils/build/driver/utils.js:174:38)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Launcher.run (file:///opt/atlassian/pipelines/agent/build/node_modules/@wdio/cli/build/launcher.js:98:13)
    at async Module.run (file:///opt/atlassian/pipelines/agent/build/node_modules/@wdio/cli/build/run.js:64:20)
Error: Command failed: "/usr/bin/google-chrome" --version --no-sandbox

**Comment by christian-bromann** [comment] 2023-10-03 17:37
@fleszczynski WebdriverIO fails to get the version from Chrome when calling `const versionString = cp.execSync(`"${chromePath}" --version --no-sandbox`).toString();`

**Comment by gr0l** [comment] 2023-10-04 10:19
The same problem occurs when running on Alpine.

As a workaround I installed chromium and set a link for the command `google-chrome` which points to the `chromium` binary
```sh
ln /usr/bin/chromium /usr/bin/google-chrome
```

**Comment by fleszczynski** [comment] 2023-10-04 13:39
@christian-bromann there's no chrome installed, there's a chromium version under a /tmp floder and we are using that as a binary on our capabilities binary: puppeteer.executablePath()

**Comment by christian-bromann** [comment] 2023-10-04 15:07
As mentioned in my previous comment, a reproducible example with a Dockerfile would be helpful to investigate.

**Comment by twegener-embertec** [comment] 2023-10-04 23:34
@christian-bromann I suspect that you could reproduce this by temporarily renaming your `/usr/bin/google-chrome` to something else, make sure chromium is installed, and in `capabilities` -> `goog:chromeOptions` specify: `binary: '/usr/bin/chromium-browser'` then try running `wdio` with that config.

**Comment by christian-bromann** [comment] 2023-10-05 15:01
@twegener-embertec mind creating a little GitHub project for this?

**Comment by twegener-embertec** [comment] 2023-10-06 00:09
@christian-bromann I'm not sure what you have in mind there. I'm not familiar with GitHub projects.
Meanwhile, my headspace has moved elsewhere.
But taking a quick look now:

The problem seems to be related to the use of locate-app locateChrome which assumes an executable with name: `google-chrome`

This alternative patch appears to solve (or at least work around) the problem:

```
$ git diff packages/wdio-utils/src/driver/utils.ts
diff --git a/packages/wdio-utils/src/driver/utils.ts b/packages/wdio-utils/src/driver/utils.ts
index 209def840..99003fd6d 100644
--- a/packages/wdio-utils/src/driver/utils.ts
+++ b/packages/wdio-utils/src/driver/utils.ts
@@ -189,7 +189,7 @@ export async function setupChromedriver (cacheDir: string, driverVersion?: strin
         throw new Error('The current platform is not supported.')
     }
 
-    const version = driverVersion || getBuildIdByChromePath(await locateChrome()) || ChromeReleaseChannel.STABLE
+    const version = driverVersion || getBuildIdByChromePath(await locateChrome().catch(() => undefined)) || ChromeReleaseChannel.STABLE
     const buildId = await resolveBuildId(Browser.CHROMEDRIVER, platform, version)
     let executablePath = computeExecutablePath({
         browser: Browser.CHROMEDRIVER,
```

Cf. the existing call to `locateChrome` in `setupPuppeteerBrowser`.

**Comment by diosmosis** [comment] 2023-10-16 03:02
Occurring for me as well on Ubuntu 23.04 with chromium installed via snap and a fresh wdio project (installed via `npm init wdio .`, no modifications made after init).

**Comment by soulgalore** [comment] 2023-10-20 10:51
Hi, I think this comes from locate-app, asking for Chrome on Linux always searches for google-chrome: https://github.com/hejny/locate-app/blob/978634416b7c039c55c5c4db7a7aac868f6c6a9b/src/browsers/locateChrome.ts#L6

**Comment by christian-bromann** [comment] 2023-10-20 17:00
With #11492 you will be able to run Chromium tests, so if your environment does not support to run Chrome you can set `browserName: 'chromium'`

**Comment by fleszczynski** [comment] 2023-11-03 18:07
browserName: 'chromium' fixed for me. Thanks @christian-bromann

**Comment by christian-bromann** [comment] 2023-11-20 04:19
This got fixed by https://github.com/webdriverio/webdriverio/commit/ee45c83a8abe33972af8fabe183db130316379c5 with the suggestion @twegener-embertec posted. Closing. Please let me know if anyone still experiences issues. Thanks for all your input.

**Closed by christian-bromann** 2023-11-20 04:19 UTC
Labels: Bug 🐛, Reproducible Example Missing
