### ISSUE TITLE
[🐛 Bug]: <title> calling setValue on an input box results in submit.click() doesn't work

### ISSUE THREAD

**Issue by idavollen** [webdriverio/webdriverio#11353] opened 2023-10-04 20:25 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.11.2

### Node.js Version

20.5.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
const capabilities = {
  platformName: 'Android',
  'appium:automationName': 'UiAutomator2',
  'appium:deviceName': 'Android',
  'appium:dontStopAppOnReset': false,
  'appium:autoGrantPermissions': true,
  'appium:noReset': true,
  'appium:fullReset': false,  
  'appium:autoAcceptPermissions': true,
  //'appium:appPackage': 'com.android.chrome',
  'browserName': 'chrome'
};
```

### What happened?

When a web page is initially loaded in Chrome on Android device by browser.url('https://www.example.com'), the web page is displayed in _overview_. If an input box is now set a value via $('input#personalIdNumber').**setValue**('abc'), it'll result in that input box is being _focused_ and the web page is _zoomed in_. Afterwards, the submission via  **browser.$('button#next').click()** of that containing form on that web page doesn't work as expected

### What is your expected behavior?

Although the web page is zoomed due to focusing on an input box, the  browser.$('button#next').click() should still be able to submit the containing form

### How to reproduce the bug.

```
//it should be reproduced with a web page is initially loaded in overview
//the setValue() call results in focus on this input box, and the web page is zoomed in
await browser.$('div.inputFullNameBox input').setValue('123456')
    //await browser.sendKeyEvent(13)
    //await browser.keys('Enter');
    console.log('sending keyPress event')
    await browser.hideKeyboard()
    await browser.pause(50)
//although we have no problem to select this input with type of submit, calling click() on this submit button doesn't work as expected
    const btnSubmit = await browser.$('input[type="submit"]')
    const location = await btnSubmit.getLocation();
    //I've tried various possible measures to deal with it, however without any luck
    //await browser.touchPinch(100, 300, 50)
    /*await browser.execute(() => {
      document.body.style.zoom = '50%'
    })*/

    //console.log('isClickable?', await btnSubmit.isClickable())
    //console.log('isDisplayedInViewport?', await btnSubmit.isDisplayedInViewport())
    //await btnSubmit.scrollIntoView({ block: 'center', inline: 'center' })
    await btnSubmit.click()
```

### Relevant log output

```typescript
2023-10-04T20:15:08.691Z INFO webdriver: COMMAND findElement("css selector", "input[type="submit"]")
2023-10-04T20:15:08.691Z INFO webdriver: [POST] http://localhost:4723/session/678d26f6-14b4-4e29-a068-f35f73c8db05/element
2023-10-04T20:15:08.691Z INFO webdriver: DATA { using: 'css selector', value: 'input[type="submit"]' }
2023-10-04T20:15:08.723Z INFO webdriver: RESULT {
  ELEMENT: 'B3E962ACAC68769E20BC1A664A9E1887_element_51',
  'element-6066-11e4-a52e-4f735466cecf': 'B3E962ACAC68769E20BC1A664A9E1887_element_51'
}
2023-10-04T20:15:08.726Z INFO webdriver: COMMAND getElementRect("B3E962ACAC68769E20BC1A664A9E1887_element_51")
2023-10-04T20:15:08.727Z INFO webdriver: [GET] http://localhost:4723/session/678d26f6-14b4-4e29-a068-f35f73c8db05/element/B3E962ACAC68769E20BC1A664A9E1887_element_51/rect
2023-10-04T20:15:08.774Z INFO webdriver: RESULT { height: 31, width: 109, x: 759.0000610351562, y: 280.4285888671875 }
2023-10-04T20:15:08.775Z INFO webdriver: COMMAND executeScript("return ((elem, options) => elem.scrollIntoView(options)).apply(null, arguments)", <object>)
2023-10-04T20:15:08.776Z INFO webdriver: [POST] http://localhost:4723/session/678d26f6-14b4-4e29-a068-f35f73c8db05/execute/sync
2023-10-04T20:15:08.776Z INFO webdriver: DATA {
  script: 'return ((elem, options) => elem.scrollIntoView(options)).apply(null, arguments)',
  args: [
    {
      'element-6066-11e4-a52e-4f735466cecf': 'B3E962ACAC68769E20BC1A664A9E1887_element_51',
      ELEMENT: 'B3E962ACAC68769E20BC1A664A9E1887_element_51'
    },
    { block: 'center', inline: 'center' }
  ]
}
2023-10-04T20:15:08.803Z INFO webdriver: RESULT null
2023-10-04T20:15:08.803Z INFO webdriver: COMMAND elementClick("B3E962ACAC68769E20BC1A664A9E1887_element_51")
2023-10-04T20:15:08.804Z INFO webdriver: [POST] http://localhost:4723/session/678d26f6-14b4-4e29-a068-f35f73c8db05/element/B3E962ACAC68769E20BC1A664A9E1887_element_51/click
2023-10-04T20:15:08.974Z INFO webdriver: RESULT null
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment] 2023-10-05 08:41
When submitting an issue we expect you to note what is the problem. Stating that the click `doesn't work as expected` while there's no errors in the log, does not give us any lead.

Please provide a small GH repo that we can run to reproduce the issue.

**Comment by idavollen** [comment] 2023-10-05 09:34
>>the submission via browser.$('button#next').click() of that containing form on that web page _doesn't work as expected_
when the input button with type of _submit_ is being clicked, its associated containing form SHOULD be submitted, that is, POST or GET the form data to the specified ACTION URL in the form, which is the normal expected behaviour on a normal web page

**Comment by erwinheitzman** [comment] 2023-10-07 13:18
Let me share some knowledge of what is likely the cause (9 out of 10 times).

When a click happens without errors and an element does not do anything, it is often a sign of a problem with state (of the element) or a race condition of some sort (in the frontend code).

Example of state issue:
When a you have a button (either native or web component) has different states of which, loading state is a good example. And the loading state should inform the users that they have to wait. WebdriverIO is not able to tell that the button does not do anything during this time. To solve this there are a few options of which the best would be to make the button disabled during this loading state. This way WebdriverIO but also your users (blind, bad eye sight) will know the state of the application. If that's a problem, since you never know if the state will kick in, you will have to make a retry function that for example clicks 3 times and asserts a follow-up condition. Only if the assertion passes, you continue.

Another cause could be that the element is visible but that the code for the click handling has not been loaded due to asynchronous code. In this case, the best solution would be not to load a button that is not interactive until it is. That said the retry applies here as well.

I very much doubt that this is a bug in the test tooling.

Hope this helps

**Comment by erwinheitzman** [comment] 2023-10-11 07:33
Going to close this due to a lack of a reproduction example and no reply since creation.

**Closed as completed by erwinheitzman** 2023-10-11 07:33 UTC
Labels: Bug 🐛, Reproducible Example Missing
