### ISSUE TITLE
isDisplayed() and waitForDisplayed() throws error in Edge

### ISSUE THREAD

**Issue by sgreener** [webdriverio/webdriverio#3509] opened 2019-02-05 19:31 UTC
**Environment (please complete the following information):**
 - **WebdriverIO:** version: 5.4.7
 - **Mode:** Standalone
 - **If WDIO Testrunner, running sync/async:** Sync
 - **Node.js version:** 8.11.4
 - **NPM version:** 5.6.0
 - **Browser name and version:** Edge
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/selenium-standalone-service": "^5.2.2

**Config of WebdriverIO**
Latest WebDriver for edge (the windows installed one)
bits include...
```
...
seleniumArgs: {
    javaArgs: ['-Dwebdriver.edge.driver=C:\\Windows\\System32\\MicrosoftWebDriver.exe']
},
capabilities: [
    browserName: 'MicrosoftEdge'
],
sync: true,
services: ['selenium-standalone'],
...
```

**Describe the bug**
isDisplayed() & waitForDisplayed() result in a;
WARN webdriver: Request failed due to Unknown error
ERROR webdriver: Request failed due to Error: Unknown error

Not sure if this is an issue with the Edge web driver or Wdio

**To Reproduce**
The following snippet will error on isDisplayed() ...
```
        browser.url('http://www.google.com');
        $('//input[@name="q"]').waitForExist();
        $('//input[@name="q"]').isDisplayed();
```
If you comment out the isDisplayed() line, it all works as expected.

**Expected behavior**

**Log**
Log found [here](https://gist.github.com/sgreener/41501a716ccd5b8dedd72623e408f27f)

**Additional context**
Seems to happen with waitForDisplayed() as well (guessing its the same issue)

**Comment by sgreener** [comment] 2019-02-05 19:34
For the record, this works in Chrome & Firefox

**Comment by christian-bromann** [comment] 2019-02-05 19:44
Duplicate of #2962

**Closed by christian-bromann** 2019-02-05 19:44 UTC
