### ISSUE TITLE
Rerun option should be required in WDIO test runner only for failed tests

### ISSUE THREAD

**Issue by jnkrao** [webdriverio/webdriverio#2986] opened 2018-10-05 11:52 UTC
## The problem
We have hundreds of tests implemented through WDIO, some tests are failing due to some expected reason like network slow/application server slow/time out and so on... but those tests are passing if we do rerun, so it could be help if we get option to rerun those failed tests only.

## Environment

* WebdriverIO version: 4.12

**Comment by abjerstedt** [comment] 2018-12-04 16:07
@jnkrao Is there a reason you cannot do this using your build server? In jenkins / team city/etc, its super easy to make a test retry multiple times upon a failure. This also also the reporting to be more accurate and to track flakey tests.

**Comment by abjerstedt** [comment] 2018-12-20 19:05
I'm going to close this as a duplicate of https://github.com/webdriverio/webdriverio/issues/2484.

**Closed by abjerstedt** 2018-12-20 19:05 UTC
Labels: Enhancement
