### ISSUE TITLE
moveTo leads to NPE

### ISSUE THREAD

**Issue by tav1313** [webdriverio/webdriverio#1091] opened 2016-02-11 11:11 UTC
win 7

14:06:29.910 INFO - Executing: [mousemove: .slick-cell l2 r2 false])
14:06:29.911 WARN - Exception thrown
java.lang.NullPointerException
	at org.openqa.selenium.remote.server.handler.interactions.MouseMoveToLocation.call(MouseMoveToLocation.java:53)
	at org.openqa.selenium.remote.server.handler.interactions.MouseMoveToLocation.call(MouseMoveToLocation.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
14:06:29.913 WARN - Exception: null

**Comment by christian-bromann** [comment] 2016-02-11 11:48
This is usually because the driver doesn't support this action. We could have a better error message though to help user understand the root cause.

**Comment by christian-bromann** [comment] 2016-10-25 16:46
Unable to reproduce NPE, closing.

**Closed by christian-bromann** 2016-10-25 16:46 UTC
Labels: Enhancement

**Comment by Cristy94** [comment] 2017-06-12 08:25
I got the same problem, any fix?
