### ISSUE TITLE
wdio running all tests in folder despite use of cucumber tag

### ISSUE THREAD

**Issue by dimirey** [webdriverio/webdriverio#1909] opened 2017-03-09 18:48 UTC
## The problem

I'm trying to run some tests in a folder that are tagged using cucumber and saucelabs. The runner is executing all of the tests (which are showing up in saucelabs) although only the tagged tests are being completed. The tests which are excluded via tags are not updated through saucelabs and are named 'Unamed Job **************************'

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.9.4
* [Standalone mode or wdio testrunner] test runner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): wdio-sauce-service@0.2.5, wdio-dot-reporter@0.0.6, wdio-cucumber-framework@0.2.15

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment] 2017-03-09 20:14
Duplicate of #1247

**Closed by christian-bromann** 2017-03-09 20:14 UTC
