### ISSUE TITLE
[🐛 Bug]: Cannot use import statement outside of module with V8 and babel setup.

### ISSUE THREAD

**Issue by skamineni** [webdriverio/webdriverio#11124] opened 2023-09-09 08:32 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.16.5

### Node.js Version

v18.17.1

### Mode

WDIO Testrunner

### What happened?

Hi, I have upgraded to V8 latest version and I see "Cannot use import statement outside a module" for import statements. 

My project uses commanjs and in V7 we used babel to compile the files that uses import statements. 
But now in V8 that is not working.

if I set type=module in my package.json, my whole test codebase has require statements which are not working.
In our test code we import Dev constants file which uses es6 i.e imports

My wdio config has autoCompile section as below in V7, which use to take care of my imports as well. But now after upgrade to V8 that is not working.

autoCompileOpts: {
    babelOpts: {
      presets: [
        [
          '@babel/preset-env',
          {
            targets: {
              node: '18'
            }
          }
        ]
      ],
      plugins: [],
      ignore: []
    }
  },

### How to reproduce the bug.

don't set type=module in package.json but try to use a simple import in wdio config file.

Have a autocompileOpts section as below:
autoCompileOpts: {
    babelOpts: {
      presets: [
        [
          '@babel/preset-env',
          {
            targets: {
              node: '18'
            }
          }
        ]
      ],
      plugins: [],
      ignore: []
    }
  },

Run any test you have, import will fail after upgrade to V8 but works in V7.

### Relevant log output

```typescript
(node:65307) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
2023-09-09T08:17:54.637Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///Users/lkamineni/huey/libs/testUtils/wdio.local.e2e.conf.js: Cannot use import statement outside a module
/Users/lkamineni/huey/libs/testUtils/wdio.local.e2e.conf.js:8
import _ from 'lodash';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._compile (/Users/lkamineni/huey/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.newLoader [as .js] (/Users/lkamineni/huey/node_modules/pirates/lib/index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Process finished with exit code 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by skamineni** [comment] 2023-09-09 08:34
I also tried removing babel integration i.e autoCompileOpts section, still same error with or without this section in V8

**Comment by christian-bromann** [comment] 2023-09-09 14:58
@skamineni thanks for reporting, can you provide a reproducible example?

I recommend creating a new WebdriverIO project and compare the setup with yours. ESM vs CJS can be tricky some time but I am sure we can get this fixed.

**Comment by skamineni** [comment] 2023-09-09 15:28
so mine is a mono repo of this structure
Project
  Feature A
     Has wdio test file that has both require and import statements.
  Feature B
  Feature C
  testUtils
    - Drivers wdio executables and executes all features. This has my wdio config file which has autoCompileOptions with babelOpts as described above. In V7 this worked. In V8 this integration doesnt compile FeatureA files.

You want me to give some sort of code as reproducible example or you want me to share a wdio config file ? What are you looking for ?

**Comment by skamineni** [comment] 2023-09-09 15:35
Just a note tough. I use javascript and not typescript

**Comment by christian-bromann** [comment] 2023-09-09 15:37
> What are you looking for ?

Ideally a little github project I can clone and test myself.

**Comment by skamineni** [comment] 2023-09-09 15:58
> > What are you looking for ?
> 
> Ideally a little github project I can clone and test myself.

hmm very complex setup, since i have to create a monorepo with multiple features and have to create whole wdio again there in a new repo. Will it help if I share you my wdio config file and package.json file ?

**Comment by skamineni** [comment] 2023-09-09 16:01
my package.json. Not allowing me to attach a file tough

{
  "name": "@quickbase/ui-test-utils",
  "version": "1.2.1",
  "license": "UNLICENSED",
  "description": "UI Testing utilities for the Hybrid UI",
  "repository": {
    "type": "git",
    "url": "https://github.com/QuickBase/huey.git"
  },
  "engines": {
    "npm": ">=3",
    "node": ">=6"
  },
  "author": "Quick Base",
  "publishConfig": {
    "registry": "https://quickbase.jfrog.io/artifactory/api/npm/npm/"
  },
  "files": [
    "docker",
    "interactiveTools",
    "internals",
    "jsDoc",
    "localizationTestHelpers",
    "sauceConnect",
    "scripts",
    "testDataGenerators",
    "testHelpers",
    "wdio",
    "wdio.docker.base.conf.js",
    "wdio.docker.e2e.conf.js",
    "wdio.docker.functional.conf.js",
    "wdio.docker.qbservice.conf.js",
    "wdio.docker.smoke.conf.js",
    "wdio.docker.systemRegression.conf.js",
    "wdio.docker.visual.conf.js",
    "wdio.local.base.conf.js",
    "wdio.local.e2e.conf.js",
    "wdio.local.functional.conf.js",
    "wdio.local.prodSmoke.conf.js",
    "wdio.local.qbservice.conf.js",
    "wdio.local.systemRegression.conf.js"
  ],
  "scripts": {
    "build": "echo 'no build'",
    "build:all": "yarn workspaces foreach -A -p -v run build",
    "runCmd:all": "yarn workspaces foreach -A -p -v -i ",
    "lint": "yarn run lint:js",
    "lint:eslint": "qb-eslint --ignore-path .gitignore --ignore-pattern internals/scripts",
    "lint:js": "yarn run lint:eslint . ",
    "lint:fix": "yarn run lint:eslint --fix .",
    "test": "jest --testPathPattern=${API_NAME}.perf.test.js$",
    "test:ci": "echo 'no tests'",
    "pretest:functional": "node ../../libs/testUtils/wdio/helpers/checkForServer.js",
    "test:feature:functional": "env BROWSER_NAME=${BROWSER_NAME} FEATURE_NAME=${FEATURE_NAME} yarn run pretest:functional && cross-env NODE_ENV=test QB_HOST=localhost:9448 HYBRID_UI_HOST=https://localhost:9447 ../../node_modules/.bin/wdio ../../libs/testUtils/wdio.local.functional.conf.js --suite functionalTestsCustomList",
    "test:feature:e2e": "env FEATURE_NAME=${FEATURE_NAME} BASE_URL=${BASE_URL} HYBRID_UI_HOST=${HYBRID_UI_HOST} cross-env NODE_ENV=test ../../node_modules/.bin/wdio ../../libs/testUtils/wdio.local.e2e.conf.js --suite e2eTestsCustomList",
    "apiBenchmarkingToolUnitTests": "jest --testPathPattern=.unit.test.js$",
    "publish-package": "cross-env npm_config_yes=true npx --userconfig .npmrc @quickbase/npm-publish-scripts@1.0.x",
    "publish:patch": "yarn publish-package -i patch",
    "publish:minor": "yarn publish-package -i minor",
    "publish:major": "yarn publish-package -i major",
    "wdio:local:functional": "../../node_modules/.bin/wdio wdio.local.functional.conf.js",
    "wdio:local:e2e": "../../node_modules/.bin/wdio wdio.local.e2e.conf.js",
    "wdio:docker:functional": "../../node_modules/.bin/wdio wdio.docker.functional.conf.js",
    "wdio:docker:visual:functional": "../../node_modules/.bin/wdio wdio.docker.visual.conf.js --suite ${WDIO_SUITE}",
    "wdio:docker:e2e": "../../node_modules/.bin/wdio wdio.docker.e2e.conf.js --suite ${WDIO_SUITE}",
    "wdio:docker:visual:e2e": "../../node_modules/.bin/wdio wdio.docker.visual.e2e.conf.js --suite ${WDIO_SUITE}",
    "wdio:docker:system:regression": "../../node_modules/.bin/wdio wdio.docker.systemRegression.conf.js --suite ${WDIO_SUITE}",
    "wdio:docker:smoke": "../../node_modules/.bin/wdio wdio.docker.smoke.conf.js",
    "wdio:docker:qbservice": "../../node_modules/.bin/wdio wdio.docker.qbservice.conf.js --suite qbServiceTestsCustomList",
    "generateMultipleApps": "node ../../libs/testUtils/interactiveTools/createMultipleApps.js",
    "createTestUser": "node ../../libs/testUtils/interactiveTools/createTestUsers.js",
    "AppWithDashboardsFormsAndPlugins": "env BASE_URL=${BASE_URL} HYBRID_UI_HOST=${HYBRID_UI_HOST} BROWSER_NAME=firefox ../../node_modules/.bin/wdio wdio.local.base.conf.js --spec ../../libs/testUtils/interactiveTools/AppWithDashboardsFormsAndPlugins.js",
    "deleteTestsCreatedLeftOverDataInProduction": "env PROD_USERNAME=svc-qatest@quickbase.com PROD_PASSWORD=${PROD_PASSWORD} DELETE_AUTOMATED_TESTS_CREATED_PRODUCTION_APPS=${DELETE_AUTOMATED_TESTS_CREATED_PRODUCTION_APPS} node ../../libs/testUtils/interactiveTools/automatedTestsDataCleanupTools/deleteAutomationTestsCreatedLeftOverDataInProduction.js",
    "deleteAutomatedTestsCreatedLeftOverDataInEnvironments": "env BASE_URL=${BASE_URL} HYBRID_UI_HOST=${HYBRID_UI_HOST} node ../../libs/testUtils/interactiveTools/automatedTestsDataCleanupTools/deleteAutomatedTestsCreatedLeftOverDataInEnvironments.js",
    "deleteAutomatedTestsCreatedLeftOverPipelinesDataInEnvironments": "env BASE_URL=${BASE_URL} HYBRID_UI_HOST=${HYBRID_UI_HOST} node ../../libs/testUtils/interactiveTools/automatedTestsDataCleanupTools/deleteAutomatedTestsCreatedLeftOverPipelinesDataInEnvironments.js",
    "deleteTestsCreatedMailosaurAccountEmails": "node ../../libs/testUtils/interactiveTools/automatedTestsDataCleanupTools/deleteTestsCreatedMailosaurAccountEmails.js",
    "createMultipleUsersInAnAppWithRoles": "node ../../libs/testUtils/interactiveTools/createMultipleUsersInAnAppWithRoles.js",
    "generateAnAppWithTableWithAllFieldTypes": "node ../../libs/testUtils/interactiveTools/createAnAppWithTableWithAllFieldTypes.js",
    "generateAnAppWithTableWithManyFieldsAndRecords": "node ../../libs/testUtils/interactiveTools/createAnAppWithTableWithManyFieldsAndRecords.js",
    "addAllFieldTypesAndRecordsToExistingTable": "node ../../libs/testUtils/interactiveTools/addAllFieldTypesAndRecordsToExistingTable.js",
    "deleteTestUsersAndRealmsAgainstDevVM": "node ../../libs/testUtils/interactiveTools/deleteMatchingUsersAndRealmsAgainstDevVM.js",
    "createRealmWithMultipleAccountsUnderSameCompany": "node ../../libs/testUtils/interactiveTools/createARealmWithMultipleAccountsUnderSameCompany.js",
    "createRealmWithMultipleAccounts": "node ../../libs/testUtils/interactiveTools/createARealmWithMultipleAccounts.js",
    "generateAnAppWithMultipleRelationships": "node ../../libs/testUtils/interactiveTools/createAnAppWithMultipleRelationships.js",
    "collectFeatureSwitchesStatusFromProduction": "env YOUR_CORP_USERNAME=${YOUR_CORP_USERNAME} YOUR_CORP_PASSWORD=${YOUR_CORP_PASSWORD} BROWSER_NAME=firefox ../../node_modules/.bin/wdio wdio.local.base.conf.js --spec ../../libs/testUtils/interactiveTools/collectFeatureSwitchesStatusFromProduction.js",
    "collectFeatureSwitchesStatusFromLocal": "env ../../node_modules/.bin/wdio wdio.local.base.conf.js --spec ../../libs/testUtils/interactiveTools/collectFeatureSwitchesStatusFromLocalvm.js",
    "runAllFunctionalTests": "node ./scripts/runFunctionalTestsLocally/runAllFunctionalTests",
    "buildJSDoc": "jsdoc -c ./jsDoc/jsdoc_config.js && mkdir -p ./jsDoc/output/scripts && cp -R ./tutorials/scripts ./jsDoc/output/ && cp -R ./tutorials/static ./jsDoc/output/",
    "linuxPackageJSDoc": "yarn run buildJSDoc; mv jsDoc/output ./${TAR_FILE_NAME_PREFIX};  tar -cjf ${TAR_FILE_NAME_PREFIX}.tar.bz2 ./${TAR_FILE_NAME_PREFIX}; ls -l ${TAR_FILE_NAME_PREFIX}.tar.bz2",
    "openJSDoc": "/bin/zsh -c 'if [ -x /usr/bin/xdg-open  ]; then `xdg-open ./jsDoc/output/index.html > /dev/null 2>&1 &` ;fi; if [ -x /usr/bin/open ]; then `open ./jsDoc/output/index.html`;fi; if [ ! -x /usr/bin/open ] && [ ! -x /usr/bin/xdg-open ]; then echo \"to view docs open file: ./jsDoc/output/index.html\"; fi'",
    "test:api:test:utils": "cd ../../libs/api-test-utils && yarn run test"
  },
  "dependencies": {
    "@lightspeed/i18n-number-format": "0.3.11",
    "@wdio/allure-reporter": "8.16.3",
    "@wdio/cli": "8.16.5",
    "@wdio/jasmine-framework": "8.16.5",
    "@wdio/junit-reporter": "8.16.3",
    "@wdio/local-runner": "8.16.5",
    "@wdio/sauce-service": "8.16.5",
    "@wdio/selenium-standalone-service": "7.31.1",
    "@wdio/spec-reporter": "7.31.1",
    "axe-core": "4.5.1",
    "chalk": "1.1.3",
    "cross-env": "7.0.3",
    "currency-formatter": "1.5.9",
    "depcheck": "1.4.3",
    "faker": "5.5.3",
    "html-dnd": "1.2.0",
    "inquirer": "8.2.0",
    "jszip": "3.7.1",
    "locale-currency": "0.0.2",
    "lodash": "4.17.21",
    "request-promise": "4.2.1",
    "table-parser": "1.0.1",
    "webdriverio": "8.16.5",
    "yargs": "17.3.0"
  },
  "devDependencies": {
    "@quickbase/api-test-utils": "0.0.x",
    "@quickbase/build-ui": "1.0.x",
    "@quickbase/lint-packages": "1.0.x",
    "date-fns": "2.28.0",
    "docdash": "1.2.0",
    "jest": "24.9.0",
    "jest-chain": "1.1.5",
    "jsdoc": "3.6.3",
    "rimraf": "2.6.1"
  }
}

**Comment by skamineni** [comment] 2023-09-09 16:22
one thing I also tried is just upgrading webdriverio package to 8.16 and nothing else in ^ package.json, Then babel integration worked since @wdio/jasmine-framework was still using V7. But as soon as I upgrade all other packages to V8 the error happens. Some how I feel might be bug that integration is broken with @wdio/jasmine-framework in V8

**Comment by skamineni** [comment] 2023-09-09 17:46
Here is the project I created. You can pull this and run the test https://github.com/skamineni/PersonalSamples
My config
<img width="1030" alt="image" src="https://github.com/webdriverio/webdriverio/assets/18192016/688a7467-ef37-4c03-ac7a-d308218e0666">


Here is the error:
<img width="1130" alt="image" src="https://github.com/webdriverio/webdriverio/assets/18192016/33d62edc-1b1e-40b7-836e-c5a045ed1537">

**Comment by skamineni** [comment] 2023-09-10 11:42
Steps to reproduce:
1. Clone the repo https://github.com/skamineni/PersonalSamples
2. From testWdio directory do yarn install.
3. Run the test, In V8 tests complain as import cannot be used. autoCompileOpts is NOT working here i.e not compiling code.

V7:
-----
1. Now update the package.json under testWdio to use V7 for all @wdio packages instead.
2. Do yarn install.
3. Run the test. It works great. autoCompileOpts is working great here that it compiles code using babel.

**Comment by erwinheitzman** [comment] 2023-09-11 08:32
My findings:
- you use the autoCompileOpts while when generating a babel project using our CLI we use a babel.config.js instead which works fine and is also the most recommended option in our docs: https://webdriver.io/docs/babel/

Also:
- you use some package called require to cache requires which can have an impact as it hasn't been updated for 6 years
- you start webdriverio without the correct config in your example

The autoCompileOpts aren't really doing at this moment, I agree with that and would like to remove it in v9 as there are much better options to configure Babel and TypeScript so I recommend to use the babel config rather than placing it in the autoCompileOpts object.

Example:
```js
module.exports = {
    "presets": [
        [
            "@babel/preset-env",
            {
                "targets": {
                    "node": 18
                }
            }
        ]
    ]
}
```

All of this said, this is my opinion based on the issues I have seen as of late regarding to TypeScript/ts-node in combination with the autoCompileOpts so I am curious what Christian has to say as well.

**Comment by skamineni** [comment] 2023-09-11 10:35
> ```js
> module.exports = {
>     "presets": [
>         [
>             "@babel/preset-env",
>             {
>                 "targets": {
>                     "node": 18
>                 }
>             }
>         ]
>     ]
> }
> ```

I tried adding babel.config.js as well and also removed autoCompile options. I have same issue. I will push the code , so you guys can see it as well.

**Comment by skamineni** [comment] 2023-09-11 11:58
This is how I solved this issue if anyone looking for it in future. I have monorepo setup.

1. I created babel.config.js inside testUtils directory.
2. I removed autoCompileOpts from all my wdio config files since this is not working in V8
3. For my wdio config files I added below
require('@babel/register')({
  // Find babel.config.js up the folder structure.
  rootMode: 'upward',

  // Since babel ignores all files outside the cwd, it does not compile sibling packages
  // So rewrite the ignore list to only include node_modules
  ignore: ['*/node_modules/*'],
  // And only transpile huey code and @quickbase node_modules here.
  only: [
    '../../features/*',
    '../../libs/*',
    '../../mock-services/*',
    '../../node_modules/@quickbase/*',
    '../../qbServiceTests/*',
    '../../services/*',
    '../../tools/*',
    '../../widgets/*'
  ]
});

**Comment by erwinheitzman** [comment] 2023-09-11 12:16
Nice find!

When using the babal config did not work at first, did you place it at the root of the project, the testUtils or the directory in which you ran the script from?

**Comment by skamineni** [comment] 2023-09-11 15:45
> Nice find!
> 
> When using the babal config did not work at first, did you place it at the root of the project, the testUtils or the directory in which you ran the script from?

correct when just using the babel config didnt work. Since its monorepo and each feature has its own package.json. To transpile you have to add that @babel/register with the directories specified above. My project structure looks like below:

Project
 - Feature A - Has its own package.json with wdio tests
 - FeatureB -  Has its own package.json with wdio tests
 - FeatureC -  Has its own package.json with wdio tests
 - testUtils -  Has its own package.json and wdio config files , That runs all above feature tests. So I added babel.config.js here . Adding under project didnt work either. Then I added that @babel/register in wdio config files which made the trick

**Comment by christian-bromann** [comment] 2023-09-11 17:22
Thanks for working this out folks, is there anything specific we would like to document on the WebdriverIO site or can we close this?

**Comment by skamineni** [comment] 2023-09-11 19:36
Ya I think you guys should document this out on wdio site, since there is no documentation available at all for babel. Especially when using babel in monorepos and to support both ES5 and ES6, this is very useful!

**Comment by erwinheitzman** [comment] 2023-09-11 21:45
I'm happy you got it to work but I still don't understand why a project, generated using the CLI with the same folder structure works fine with having the babel config in the root of the project.

Since babel works with different types of configs I have a feeling there were some misconceptions on what I meant when I said to use a babel config.

As you can read here there is a project wide configuration and a file relative configuration: https://babeljs.io/docs/config-files
I think this should help and we can add this link to our docs.

What do you think @skamineni could you perhaps try the project wide setup or the file relative? Both would require different approaches but I feel like the register setup you have now works but shouldn't be needed.
Hope this helps 👍

**Comment by skamineni** [comment] 2023-09-11 23:30
sounds good.I will try and update here!

**Comment by skamineni** [comment] 2023-09-12 11:07
> sounds good.I will try and update here!

So I did go through the documentation. In my case project wide setup is not relevant for monorepos
<img width="1017" alt="image" src="https://github.com/webdriverio/webdriverio/assets/18192016/c8033639-29f6-4353-b6ae-798c3bdfc10e">

So now I looked at relative-path configuration. They took me to https://babeljs.io/docs/config-files#monorepos
There they also gave an example of @babel/register to use, which is what I am using currently
<img width="1056" alt="image" src="https://github.com/webdriverio/webdriverio/assets/18192016/fc787ed7-f775-40a6-8999-36bfc407ed0d">

**Comment by erwinheitzman** [comment] 2023-09-12 12:02
Ah so the go-to relative setup works for simple projects, your way works for complex monorepo setups and project wide works for most other projects. This is very useful information!

I'll update the docs soon to include this.
Thank you for helping out @skamineni 👍

**Comment by skamineni** [comment] 2023-09-12 17:22
yw! Thanks for followups on this. We can close the bug now!

**Comment by christian-bromann** [comment] 2023-09-12 23:08
Thanks @skamineni

**Closed by christian-bromann** 2023-09-12 23:08 UTC
Labels: Bug 🐛, Reproducible Example Missing
