### ISSUE TITLE
"browser.reloadSession()" throws "invalid session id: invalid session id" error in WDIO 8.3.9

### ISSUE THREAD

**Issue by venkatrvaradhan** [webdriverio/webdriverio#9888] opened 2023-03-06 07:51 UTC
Hi Team, 

In our current project, we are using **WebdriverIO** with **Typescript** for our web automation. We are currently migrating our project from sync to async with the latest WDIO version 8. We are using **Cucumber** as the framework and added the afterScenario as mentioned below in the wdio.conf.js file. When we try to execute the scenarios, we're getting the error "**invalid session id: invalid session id**", "**ERROR webdriver: Request failed with status 404 due to invalid session id: invalid session id**". Could someone please help me to resolve this issue? 

afterScenario: async (world, result, context) => {
      await browser.reloadSession();
    }

Please let me know if you need additional information.

**Comment by christian-bromann** [comment] 2023-03-06 16:16
> Could someone please help me to resolve this issue?

Could you please provide a minimal reproducible example?

**Comment by venkatrvaradhan** [comment] 2023-03-07 05:25
Hi Christian, 
Attached is the file containing package.json dependencies and wdio.conf.js file details. When we try to run 5 scenarios in a feature file, only 1 or 2 get executed and the remaining fail due to an invalid session id issue. 
Note: We have added await and async in all the required places, but still the issue occurs. 
[wdio conf.txt](https://github.com/webdriverio/webdriverio/files/10905689/wdio.conf.txt)

**Comment by christian-bromann** [comment] 2023-03-07 07:36
@venkatrvaradhan can you please create a repository for me to check out and run?

**Comment by venkatrvaradhan** [comment] 2023-03-07 11:05
Hi @christian-bromann, I could see this error is thrown in the terminal. 

![image](https://user-images.githubusercontent.com/102894942/223404735-53a83260-5471-4830-8850-7ce52015319a.png)

**Comment by venkatrvaradhan** [comment] 2023-03-07 11:06
> @venkatrvaradhan can you please create a repository for me to check out and run?

We are currently trying to reproduce this issue in a separate project and will share once it's done.

**Comment by venkatrvaradhan** [comment] 2023-03-15 11:50
Hi Christian, this issue got resolved after changing the **forEach** loop with **for await of.** This issue can be closed. Thanks for the support.

**Comment by harsha509** [comment] 2023-03-15 12:09
Closing as resolved then!

**Closed by harsha509** 2023-03-15 12:09 UTC
Labels: Reproducible Example Missing

**Comment by ashil88** [comment] 2023-04-17 10:51
Hi @venkatrvaradhan. Just wondering if you'd be able to provide an example of your `for await of` loop? I'm currently using forEach and getting this `invalid session id` error every 5 successful passes or so. Tried various implementations of `for of` but can't get it working for me...

**Comment by venkatrvaradhan** [comment] 2023-04-17 11:09
> Hi @venkatrvaradhan. Just wondering if you'd be able to provide an example of your `for await of` loop? I'm currently using forEach and getting this `invalid session id` error every 5 successful passes or so. Tried various implementations of `for of` but can't get it working for me...

Hi @ashil88, could you please make sure all the **forEach** loop is replaced with **'for of'/'for await of'** loop in all the places and add 'await' in all the required places? 
We followed [WDIO documentation](https://webdriver.io/docs/async-migration/#foreach-loops) to resolve this issue. Hope this helps!

**Comment by nderevjanik-fond** [comment] 2023-05-20 00:05
I'm running into the same issue with WDIO v8 + Appium v2.0.

I created a very simple project that reproduces the issue:
https://github.com/nderevjanik-fond/wdio-reload-session

The only test in this project fails:

```typescript
describe('wdio reload session', function () {
  it('should create new sessions ids', async function () {
    const sessionIdA = driver.sessionId;
    await driver.reloadSession();
    const sessionIdB = driver.sessionId;

    expect(sessionIdA).not.toEqual(sessionIdB);
  });
});
```

```
Error in "wdio reload session.should create new sessions ids"
Error: expect(received).not.toEqual(expected) // deep equality

Expected: not "d5e3d285-3501-4a36-81dc-a78dd79b3791"
```

@christian-bromann let me know if you'd like me to open a new issue.

**Comment by christian-bromann** [comment] 2023-05-20 00:15
@nderevjanik-fond feel free to open a new issue since yours seems different from the original. Any contributions are appreciated.
