### ISSUE TITLE
Better exclusion options

### ISSUE THREAD

**Issue by marklagendijk** [webdriverio/webdriverio#4497] opened 2019-09-13 08:07 UTC
**Is your feature request related to a problem? Please describe.**
I am trying to execute all tests except a certain `suite`. This is currently only possible by explicitly listing all suites without the specific suites.

**Describe the solution you'd like**
- Add support for a new command line param: `excludeSuite`
- Support globs in the existing `exclude` command line param.

**Comment by christian-bromann** [comment] 2019-09-13 09:16
> * Support globs in the existing `exclude`.

Globs should be already supported for specs defined in the `exclude` property.

**Comment by marklagendijk** [comment] 2019-09-13 09:41
@christian-bromann I didn't formulate it clearly. I meant the `exclude` command line param.
I tried using a glob with that, but it didn't work.

**Comment by schuttsm** [comment] 2019-09-15 17:45
@christian-bromann Is this what you were thinking?  https://github.com/webdriverio/webdriverio/compare/master...schuttsm:exclude-suite-arg?expand=1

I'll file the pull request, but since I'm new to webdriverio, I'll need some help getting this tested first.  I've tried the instructions in [CONTRIBUTING.md] for linking changes in packages (https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) & it comes back with the following error:

```
> webdriverio_test@1.0.0 test C:\Users\Stephen\code\webdriverio_test
> wdio.cmd wdio.conf.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../build'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Stephen\code\webdriverio_test\node_modules\wdio-cli\bin\wdio.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! Test failed.  See above for more details.
```

I've tried a number of other hacks to test it against a small wdio script I have, nothing seems to work.

**Comment by christian-bromann** [comment] 2019-09-15 17:49
Have you tried to run `npm run setup-full`?

**Comment by schuttsm** [comment] 2019-09-22 19:02
@christian-bromann https://github.com/webdriverio/webdriverio/pull/4520

**Comment by christian-bromann** [comment] 2019-09-23 07:53
> I tried using a glob with that, but it didn't work.

@marklagendijk how did you call it?

> I am trying to execute all tests except a certain `suite`

why don't you just run: `wdio run wdio.conf.js --suite mySuite`? This way you only run specs that are defined within `mySuite`

**Comment by baruchvlz** [comment] 2019-09-23 13:24
To extend on what @christian-bromann said. The `--suite` flag takes in an Array, so you could define your suites like:

```bash
wdio run wdio.conf.js --suite suiteOne suiteTwo suiteThree
```

Or if you want to be very confused, you can also do this

```bash
wdio run wdio.conf.js --suite suiteOne --suite suiteTwo --suite suiteThree
```

Both of these will be [parsed by yargs](http://yargs.js.org/docs/#array) (library WDIO uses for CLI interaction) as `['suiteOne', 'suiteTwo', 'suiteThree']`.

**Comment by marklagendijk** [comment] 2019-09-23 15:43
@christian-bromann, @baruchvlz   I know how suites work. However, I have a case where I have many suites and want to execute all, except one. 

As for the exclude param, I did something like this: `wdio run wdio.conf --exclude "some-folder/**/*.ts"` (and also tried with many other variants of the glob pattern).

**Comment by schuttsm** [comment] 2019-09-23 15:49
@christian-bromann @baruchvlz  

the exclude param glob bug is caused by this line:
> https://github.com/webdriverio/webdriverio/pull/4520/files#diff-12c6010b2e286406d2efd5ef06b411d7R242

its just a regex compare.  My fix is a few lines above it (229-235 & 238-239).

I don't mind separating out that fix in a separate pull request if its decided the excludeSuite param won't make it in.  But I agree with @marklagendijk that's its a useful feature to have

**Comment by christian-bromann** [comment] 2019-09-23 15:59
> As for the exclude param, I did something like this: `wdio run wdio.conf --exclude "some-folder/**/*.ts"`

If we fix this error, would it help to solve your use case of running all specs but one?

> I don't mind separating out that fix in a separate pull request

@schuttsm let's do that!

**Comment by marklagendijk** [comment] 2019-09-25 15:03
@christian-bromann it would. Apart from that I still think excludeSuite might be nice.

**Comment by schuttsm** [comment] 2019-09-27 19:38
@christian-bromann @marklagendijk  - here's the exclude param glob bug fix
https://github.com/webdriverio/webdriverio/pull/4544

Sorry it took so long.

**Comment by christian-bromann** [comment] 2019-09-29 20:04
Thanks @schuttsm!

I don't see "excluding suites" as a feature in other testing frameworks and I am not sure how useful it is. I will close this but happy to reopen in case there is a bigger interest in an `excludeSuite` parameter.

**Closed by christian-bromann** 2019-09-29 20:04 UTC
Labels: Enhancement, good first pick, help wanted
