### ISSUE TITLE
Bug: XUnit reporter creates empty files!

### ISSUE THREAD

**Issue by SchwaFa** [webdriverio/webdriverio#805] opened 2015-09-25 12:26 UTC
The xunit reporter doesn't work anymore in my setting. It just creates empty XML files and I get the following console output at the end of the test (wdio):

````
[...]/node_modules/webdriverio/lib/reporter/xunit.js:273
            status: Object.getOwnPropertyNames(test.err).length === 0 ? 'passe
                           ^
TypeError: Object.getOwnPropertyNames called on non-object
    at Function.getOwnPropertyNames (native)
    at [...]/node_modules/webdriverio/lib/reporter/xunit.js:273:28
    at Array.forEach (native)
    at XUnit.genTestsuite ([...]/node_modules/webdriverio/lib/reporter/xunit.js:237:11)
    at [...]/node_modules/webdriverio/lib/reporter/xunit.js:257:18
    at Array.forEach (native)
    at XUnit.genTestsuite ([...]/node_modules/webdriverio/lib/reporter/xunit.js:237:11)
    at [...]/node_modules/webdriverio/lib/reporter/xunit.js:257:18
    at Array.forEach (native)
    at XUnit.genTestsuite [...]/node_modules/webdriverio/lib/reporter/xunit.js:237:11)
```

I'm using version 3.2.4.

**Comment by christian-bromann** [comment] 2015-09-25 18:22
Duplicate of #801 .. already fixed but not released. Try to get it out asap

**Closed by christian-bromann** 2015-09-25 18:22 UTC
