### ISSUE TITLE
calling browser.reload() leads to UnhandledPromiseRejectionWarning with wdio-mocha-framework@0.5.3

### ISSUE THREAD

**Issue by dfleer100** [webdriverio/webdriverio#1700] opened 2016-11-11 11:59 UTC
## The problem

If you use the command 'browser.reload()' to get a new fresh browser instance, nodejs throws an 'UnhandledPromiseRejectionWarning'. I faced this issue only with wdio-mocha-framework@0.5.3. Older versions working fine.

## Environment

* WebdriverIO version: webdriverio@4.4.0
* Node.js version: v6.9.1
* Standalone mode or wdio testrunner: wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):  wdio-mocha-framework@0.5.3

## Code To Reproduce Issue [ Good To Have ]
```
describe('browser.reload() fails with wdio-mocha-framework@0.5.3 ...', () => {
    before(() => {
        browser.reload()
    })
    it('browser url', () => {
        browser.url('http://www.google.de')
    })
})
```

Result is:
```
(node:12504) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'ELEMENT' of undefined
```

**Comment by christian-bromann** [comment] 2016-11-14 15:39
I had no issues running the spec file you provided. According to the [logs](https://gist.github.com/christian-bromann/ead0d886d71c62da5402f340c8924c86) it starts and reloads the session successfully. Closing since I don't have any more information to reproduce.

**Closed by christian-bromann** 2016-11-14 15:39 UTC
Labels: Bug

**Comment by dfleer100** [comment] 2016-11-14 16:20
Hi @christian-bromann,
do you need any logfiles from me to reproduce the issue?

**Comment by christian-bromann** [comment] 2016-11-14 16:21
If you could provide a sample project which I can download and run to reproduce the issue that would be perfect 👌
