### ISSUE TITLE
[🐛 Bug]: Could not download latest chromedriver with Macbook Pro M1

### ISSUE THREAD

**Issue by LingVuDev** [webdriverio/webdriverio#10620] opened 2023-06-23 13:26 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.32.0

### Node.js Version

18.4.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
browserName: 'Chrome',
browserVersion: '114.0.5735.90',
operatingSystem: 'MacOS',
processor: 'M1 Pro'
```

### What happened?

After starting the tests it suddenly aren't able to download the chromedriver:

```
Error in "Could not request headers from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_mac64_m1.zip: 404, continue without checking for latest version.". 
```

### What is your expected behavior?

Should be able to download to start the tests

### How to reproduce the bug.

To reproduce the bug, simply take an M1 Macbook and try to start the tests

### Relevant log output

```typescript
Error in "Could not request headers from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_mac64_m1.zip: 404, continue without checking for latest version.".
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2023-06-23 19:52
@LingVuDev thanks for raising the issue.

WebdriverIO doesn't download Chromedriver for you so please provide more information about your set up and which package you use to download the driver.

**Comment by LingVuDev** [comment] 2023-06-26 07:34
These are the packages that I am using:
```
  "devDependencies": {
    "@wdio/cli": "^7.31.1",
    "@wdio/cucumber-framework": "^7.31.1",
    "@wdio/local-runner": "^7.31.1",
    "@wdio/selenium-standalone-service": "^7.31.1",
    "@wdio/spec-reporter": "^7.31.1",
    "cucumber-html-reporter": "^5.5.0",
    "typescript": "^4.4.4",
    "wdio-cucumberjs-json-reporter": "^4.4.3",
    "wdio-wait-for": "^2.2.6"
  },
  "dependencies": {
    "@cucumber/cucumber": "^8.4.0",
    "canvas": "^2.9.0",
    "cucumber-junit": "^1.7.1",
    "cucumber-junit-convert": "^1.1.1",
    "date-fns": "^2.16.1",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "got": "^11.8.5",
    "http-proxy-middleware": "^2.0.6",
    "install": "^0.13.0",
    "mockserver": "^3.1.1",
    "resemblejs": "^4.1.0"
  }
  ```
  
  And my wdio.conf.ts contains this:
  
```
[...]
const drivers = {
  chrome: { version: '114.0.5735.90' }, // https://chromedriver.chromium.org/
};
exports.config = {
  runner: 'local',
  hostname: 'localhost',
  port: 4444,
  specs: ['./features/**/*.feature'],
  autoCompileOpts: {
    autoCompile: true,
    // see https://github.com/TypeStrong/ts-node#cli-and-programmatic-options
    // for all available options
    tsNodeOpts: {
      transpileOnly: true,
      project: 'tsconfig.json',
    },
    // tsconfig-paths is only used if "tsConfigPathsOpts" are provided, if you
    // do please make sure "tsconfig-paths" is installed as dependency
    tsConfigPathsOpts: {
      baseUrl: './',
    },
  },
  reporters: [
    'spec',
    [
      'cucumberjs-json',
      {
        jsonFolder: 'report/json/',
        language: 'en',
      },
    ],
  ],
  maxInstances: process.env.E2E_RUNTIME === 'mock' ? 4 : 2,
  capabilities: [
    {
      browserName: 'chrome',
      'goog:chromeOptions': {
        args: chromeOptions,
        useAutomationExtension: false,
      },
    },
  ],
  logLevel: 'error',
  bail: 0,
  baseUrl: 'http://localhost:3000',
  framework: 'cucumber',
  services: [
    [
      'selenium-standalone',
      {
        logPath: 'logs',
        installArgs: { drivers },
        args: { drivers },
      },
    ],
  ],
  seleniumLogs: 'logs',
  beforeSession() {
    if (!cucumberTag) {
      return 1;
    }
  },
};

```

**Comment by LingVuDev** [comment] 2023-06-26 07:42
This is the complete output:

```
[INFO] starting cucumber tests with following options: --no-sandbox,--disable-dev-shm-usage,--headless,--disable-gpu,--window-size=1280,1024
[INFO] starting cucumber tests with following tagExpression: not @flaky and (@allStages or @mock) and (@allCountries or @DE) and (@allResolutions or @desktop) and (@allVariants or @store)

Execution of 1 workers started at 2023-06-26T07:41:24.080Z

Error in "Could not request headers from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_mac64_m1.zip: 404, continue without checking for latest version.". 
See more details below:
Error in "chmod". 
See more details below:
ENOENT: no such file or directory, chmod '[...]/test-e2e/node_modules/selenium-standalone/.selenium/chromedriver/114.0.5735.90-arm64/chromedriver'
2023-06-26T07:41:27.310Z ERROR @wdio/selenium-standalone-service: Error: ENOENT: no such file or directory, chmod '[...]/test-e2e/node_modules/selenium-standalone/.selenium/chromedriver/114.0.5735.90-arm64/chromedriver'

**Comment by christian-bromann** [comment] 2023-07-07 18:18
This seems to be a duplicate of https://github.com/webdriverio/selenium-standalone/issues/803
Any contributions to that project are very much appreciated, thanks!

**Closed by christian-bromann** 2023-07-07 18:18 UTC
Labels: Bug 🐛, Information Missing
