### ISSUE TITLE
client.on('error') does not handle errors thrown from custom commands

### ISSUE THREAD

**Issue by benjyblack** [webdriverio/webdriverio#828] opened 2015-10-13 17:50 UTC
Tested with v3.1.0 and v3.2.5:
```js
// set up global error handler
client.on('error', function (err) {
  console.log('Global error handler called');
});

client.addCommand('throwError', function () {
  throw new Error('Custom command error');
});

client
.throwError()
.catch(function (err) {
  console.log('Local catch called');
});

// outputs >> 'Local catch called'
// does NOT output >> 'Global error handler called'
```

**Comment by christian-bromann** [comment] 2015-10-28 21:29
Seems to be a bug. Probably why I had to quarantine [this](https://github.com/webdriverio/webdriverio/blob/master/test/spec/functional/events.js#L56-L60) test.

**Comment by christian-bromann** [comment] 2016-01-03 13:00
Probably duplicate of #827, I will double check custom commands and add a test for that

**Closed by christian-bromann** 2016-01-03 13:00 UTC
Labels: Bug
