### ISSUE TITLE
afterStep hook is not triggered

### ISSUE THREAD

**Issue by szory** [webdriverio/webdriverio#6743] opened 2021-04-22 12:27 UTC
**Environment (please complete the following information):**
- "webdriverio": "7.5.1",
 - "@wdio/cli": "7.5.0"
 - "@wdio/local-runner": "7.5.0",
 - "@wdio/runner": "7.5.0",
 - "@wdio/sync": "7.5.0",
 - Node.js version: 12.18.4
 - NPM version: 6.14.6
 - "chromedriver": "^89.0.0"
 - Platform name and version: Windows 10
 - @wdio/cucumber-framework": "7.5.1",

**Describe the bug**
afterStep hook doesn't run when in step is infinite async function. 

In one of our step we have functionality which has to get some emails. It searching that by using subject name. However in our 
test we provide incorrect subject name so searching function will never end this task. So we create step with time out ex:

**Then(/^I check the latest email with title "(.*?)" $/, **{ timeout: 60 * 1000 }**, async function (title){
     const email = await infinite_function(title);
});**

the point is that if this function will not end the task and exceed timeout then **afterStep** hook will not run, and we're not able to take screenshot which is important for summary report

**Actual result**
after timeout the **afterStep** hook is not triggered

**Expected behavior**
after timeout the **afterStep** hook should be triggered

**Log**
Error: function timed out, ensure the promise resolves within 60000 milliseconds
at Timeout._onTimeout (node_modules\@cucumber\cucumber\src\user_code_runner.ts:80:18)
at listOnTimeout (internal/timers.js:549:17)
at processTimers (internal/timers.js:492:7

**Comment by christian-bromann** [comment] 2021-04-22 12:39
@szory are you saying that the `afterStep` hook is not triggered because of the timeout?

**Comment by szory** [comment] 2021-04-22 12:49
@christian-bromann , no, afterSteo Hook is not triggered after Timeout ex 60 sec.

**Comment by christian-bromann** [comment] 2021-04-22 14:52
Probably an issue within the `@wdio/cucumber-framework` adapter. Any contributions to this would be very appreciated.

**Comment by WarleyGabriel** [comment] 2021-07-22 15:02
Hi @christian-bromann, I've tried with `"@wdio/cucumber-framework": "^7.7.7"` and it's not working. 
The `afterStep` hook is not being triggered.

**Comment by christian-bromann** [comment] 2021-07-22 15:10
@WarleyGabriel can you provide a minimal reproducible example?

**Comment by WarleyGabriel** [comment] 2021-07-22 15:43
Actually no, it was my mistake. 
I was merging two config files and in one of those, I hadn't fixed the params for `afterStep`.
I found the mistake after trying to reproduce the problem in a new project.

I think we can close this issue.

Thanks @christian-bromann

**Comment by christian-bromann** [comment] 2021-07-22 16:26
Perfect, thanks for your input!

**Closed by christian-bromann** 2021-07-22 16:26 UTC
Labels: good first pick, help wanted, wdio-cucumber-framework
