### ISSUE TITLE
unable to access updated config Object from onPrepare() in beforeSession() or before() or browser.config

### ISSUE THREAD

**Issue by spatchamatla** [webdriverio/webdriverio#5883] opened 2020-09-23 22:01 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.5.0
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** yes
 - **Node.js version:** v12.12.0
 - **NPM version:** v6.11.3
 - **Browser name and version:** Chrome 85.0.4183.83
 - **Platform name and version:** macOS v10.15.6
 - **Additional wdio packages used (if applicable):**
```
    "@wdio/allure-reporter": "^6.4.7",
    "@wdio/cli": "^6.5.0",
    "@wdio/jasmine-framework": "^6.5.0",
    "@wdio/local-runner": "^6.5.0",
    "@wdio/selenium-standalone-service": "^6.4.7",
    "@wdio/spec-reporter": "^6.4.7",
    "@wdio/sync": "^6.5.0"
```

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
In onPrepare(), Update/add any keys to config Object. we are unable to access that updated config Object in beforeSession() or before() or via browser.config

**To Reproduce**
In wdio.conf, onPrepare(),
```
 config['testSpec'] = ['Hi There'];
 console.log(` onPrepare() config:\n${JSON.stringify(config, null, 2)}`);
```
and to access that config object in, say
```
beforeSession: (config, capabilities, specs) => {
 console.log(` beforeSession() config:\n${JSON.stringify(config, null, 2)}`);
},
```

**Expected behavior**
Able to access updated config Object from onPrepare() in beforeSession() or before() or via browser.config .

**Comment by christian-bromann** [comment] 2020-09-24 06:04
Duplicate of #5884.

**Closed by christian-bromann** 2020-09-24 06:04 UTC
