### ISSUE TITLE
HTTP Basic Auth

### ISSUE THREAD

**Issue by nathanjohnson320** [webdriverio/webdriverio#837] opened 2015-10-19 20:13 UTC
If I have a page setup with HTTP basic auth can I use webdriverIO to fill in the username/password and submit that to login? Or is there another way to handle this scenario with webdriverIO?

**Comment by michahell** [comment] 2015-10-27 12:00
I'm running into the same problem. (Selenium-webdriver DOES support it)[http://stackoverflow.com/questions/24304752/how-to-handle-authentication-popup-with-selenium-webdriver-using-java], webdriver.io does not.

What works, (only in chrome btw) is to pass in the username and password into the url (which is not ideal): http://stackoverflow.com/questions/10395462/handling-browser-authentication-using-selenium

Another way is to set a cookie, I'm currently going to try to do this using the setCookie method:
http://www.webdriver.io/api/cookie/setCookie.html

**Comment by nathanjohnson320** [comment] 2015-10-27 13:06
@michahell what cookie are you setting? That would most likely solve my issue, ideally I'd want to use the regular authenticateUsing function but I'm not sure if they'll ever implement that in webdriverio

**Comment by michahell** [comment] 2015-10-27 13:33
Hmm I did not try to go for the cookie route, instead i'm trying to (grunt-prompt)[https://github.com/dylang/grunt-prompt] for the basic auth password before tests start, but I'm running into trouble passing this info to webdriverio... 
It is possible, probably, to just use something like this:
```javascript
return browser
      .url(someUrl)
      .pause(200)
      .keys(username)
      .keys('tab character') // some U+0571 or something :)
      .keys(password)
```
thinking about environment vars. Gah, this sucks.

**Comment by nathanjohnson320** [comment] 2015-10-27 14:28
I tried the keys method but it times out at browser.url, I just went the route of putting the username:password in the url which isn't the best way but it works

**Comment by christian-bromann** [comment] 2015-10-27 16:55
`authenticateUsing` seems to be a new method and hasn't been landed in the JSONWire protocol. So WebdriverIO won't be able to use it. I would go with the route of putting it into the url as it allows max cross driver compatibility. Haven't seen any new stuff regarding authentification in the specs yet.

**Comment by michahell** [comment] 2015-10-29 10:12
Is there any guide as to how to pass values from Grunt to the wdio.conf.js configuration? or else to tests?

**Comment by christian-bromann** [comment] 2015-10-29 10:22
@michahell have you tried to use environment variables? You could set these right before your test starts depending on your environment and access them in your test.

**Comment by michahell** [comment] 2015-10-29 10:35
Hmm, and then have Grunt set those environment variables. I've seen it before, but since we only use grunt in local development, we are 'always' operating on the local development environment, so I was trying for non-environment vars approaches first. I'll give it a try and then report my results :)

**Comment by michahell** [comment] 2015-10-29 13:27
I've now a setup using earlier mentioned grunt-prompt i.c.w. grunt-env, and then use the following:
```javascript
var preAuthUrl = 'https://' + process.env.NODE_TEST_USER + ':' + process.env.NODE_TEST_PASSWORD + '@<mydomain>';
```

Which works! However, I would still like to test the `usual` basic auth login box that for example google chrome pops up. How can I control this window?

I've tried the following:

```javascript
it('should present the basic auth login box and verify basic auth works', function () {
    return browser
      .url(baseUrl)
      .pause(200)
      .leftClick()    // added this because it seems the window does not have focus?
      .pause(100)
      .keys(adminUser)   // this never gets entered into the username input.
      .pause(100)
      .keys('U+E004') // neither does entering a TAB switch to the password input field.
      .pause(100)
      .keys(adminPassword)   // neither this.
      .waitForVisible('#menu', 15000);
});
```

**Comment by christian-bromann** [comment] 2015-10-29 13:33
@michahell I am afraid you won't be able to input keys in there. That doesn't work with Selenium. There might be a reason for that but afaik the login name and password in the url seems to be the common approach.

**Closed** 2015-10-29 13:33 UTC
Labels: Needs Investigation

**Comment by michahell** [comment] 2015-10-29 13:38
Roger confirmed!

**Comment by devourment77** [comment] 2017-07-03 20:26
I know this is old, but checking to see if there has been any update for basic auth support in webdriverio (using with browserstack).

**Comment by christian-bromann** [comment] 2017-07-05 17:20
No, still not supported with WebDriver

**Comment by davidnormo** [comment] 2018-08-03 10:50
Just an FYI, having basic auth in the url conflicts with chrome's `fetch` implementation: whatwg/fetch#26 
That is, if you attempt to call `fetch` with a relative url and the base url has basic auth in, then an error will occur, such as: `Request cannot be constructed from a URL that includes credentials`.

**Comment by MartinX3** [comment] 2018-08-26 15:14
Yes, with firefox it fails, too.
I'm using gebish with spock and selenium.

**Comment by kimek** [comment] 2018-09-10 13:01
As I understand sending header "Authorization: Basic QWxhZGRpbjpPcGVuU2VzYW1l" where QWxhZGRpbjpPcGVuU2VzYW1l is user:password in base64 encode should be enough.
According to webdriver.io you can send header using config : http://webdriver.io/guide/getstarted/configuration.html#heade
I'm testing this now and I'll update this comment when I will gain access..

**Comment by kimek** [comment] 2018-09-10 14:28
@christian-bromann  are you aware how to access to browser profile using webdriver.io ? 
Plan is to follow https://eveningsamurai.wordpress.com/2013/11/21/changing-http-headers-for-a-selenium-webdriver-request/ ( use firefox header extension with basic auth headers ).
As I've seen we can use http://webdriver.io/guide/services/firefox-profile.html to load header extension, however I'm stuck with accessing to profile for "profile.setPreference("modifyheaders.headers.count", 1);"

**Comment by christian-bromann** [comment] 2018-09-10 14:36
@kimek see http://webdriver.io/guide/services/firefox-profile.html#Options

**Comment by LexiPham** [comment] 2019-11-11 11:38
Still got this issue, is there anyway out?

**Comment by mgrybyk** [comment] 2019-11-11 11:42
It's definitely not this issue @LexiPham 

Feel free to raise another one if you have steps to reproduce or ask help on gitter

Cheers

**Comment by LexiPham** [comment] 2019-11-11 11:51
@mgrybyk Thanks for your reply. I have asked on gitter but no one knows the answer. For example:

I can by pass http but can't not with https

http://guest:guest@jigsaw.w3.org/HTTP/Basic/ --> this works.

https://guest:guest@jigsaw.w3.org/HTTP/Basic/ --> this doesn't work.

My test server redirect http to https so I alway use https, I don't know how to by pass this https, if you know something please let me know. Thanks.

**Comment by kimek** [comment] 2019-11-11 12:32
It could be chrome https://support.google.com/chrome/thread/14126937?hl=en ?
Please try use different web browser first (example Mozilla):
exports.config = {
    seleniumArgs: {
        drivers : {
            chrome : {
                version : "77.0.3865.40"
            },
            firefox: {
                "version": "0.24.0"
            }
        }
    },
    seleniumInstallArgs: {
        drivers : {
            chrome : {
                version : "77.0.3865.40"
            },
            firefox: {
                "version": "0.24.0"
            }
        }
    },
 capabilities: [
         {
             maxInstances: 1,
             browserName: 'firefox',
             acceptInsecureCerts: true
         }
    ]
}

And try different chrome drivers too please. If firefox works, it will mean that it's  chrome driver/chrome issue, not webdriver.io.

**Comment by LexiPham** [comment] 2019-11-17 01:23
Thanks for your reply, it turns out that the url are incorrect in my environment.

**Comment by siddharthmittal97** [comment] 2023-04-19 12:01
It is bit surprised that webdriverIo is unable to handle the alert & prompt

**Comment by christian-bromann** [comment] 2023-04-19 14:37
> It is bit surprised that webdriverIo is unable to handle the alert & prompt

@siddharthmittal97 it does handle those, see e.g. https://webdriver.io/docs/api/webdriver/#acceptalert
