### ISSUE TITLE
waitUntil() strips stacktrace info from errors

### ISSUE THREAD

**Issue by mo** [webdriverio/webdriverio#3534] opened 2019-02-09 11:02 UTC
1. git clone https://github.com/mo/wdio-waituntil-error-handling-bug.git
2. npm test

Running the repro steps above prints "running waitUntil func at ..." multiple times and each time it's printed an error has been generated but is not reported. When the test times out, it does report the error (presumably the last error I suppose?) which is good, but unfortunately the error is reported without any stacktrace information:

```
[firefox #0-0] 1) webdriver.io page should have the right title
[firefox #0-0] Error: Promise was rejected with the following reason: Error: error inside waitUntil
[firefox #0-0] Error: Promise was rejected with the following reason: Error: error inside waitUntil
[firefox #0-0]     at process._tickCallback (internal/process/next_tick.js:68:7)
```

What I would like to have seen instead was a stacktrace pointing to main.test.js:8 where the throw statement is.

A secondary issue is that none of the errors are not reported until the test times out. I would prefer to have a waitUntil(fn) function that did "wait until fn() returns true but abort if fn() throws an error" instead of the current waitUntil which is "wait until fn() returns true and ignore all errors from fn() while waiting".

**Comment by xlenz** [comment] 2019-02-12 13:14
Looks like the problem is with wdio Timer class that spawns huge stacktrace of recursion.

**Comment by mo** [comment] 2019-02-12 21:52
As a temporary workaround / hack I ended up defining a small wrapper for waitUntil that captures any error and re-throws it after waitUntil() has returned. This is sufficient for me to find the code location that called the waitUntil-wrapper which is typically the info I need to fix the issue.

```
  waitUntil(fn, ...args) {
    let errorSeen
    browser.waitUntil(() => {
      try {
        return fn()
      } catch (err) {
        errorSeen = err
        return true
      }
    }, ...args)
    if (errorSeen) {
      throw errorSeen
    }
  }
```

**Comment by mgrybyk** [comment] 2019-02-12 22:23
@mo shouldn't it be return false in case of error?

**Comment by mgrybyk** [comment] 2019-02-12 23:15
@mo just found out how to fix this. Will try to do PR these days if you don't mind.

Actually found out how to fix both, problem waitUntil and problem with custom commands (if error is throw in custom command stack trace is missing as well).

**Comment by mo** [comment] 2019-02-13 09:55
Excellent news. Please do!

**Comment by mgrybyk** [comment] 2019-02-16 04:07
@mo please see PR. There are some examples.

**Comment by christian-bromann** [comment] 2019-02-20 09:53
PR is merged and released. Closing.

**Closed by christian-bromann** 2019-02-20 09:53 UTC
