### ISSUE TITLE
sometimes $(...).waitForExist is not a function

### ISSUE THREAD

**Issue by rdpanek** [webdriverio/webdriverio#4403] opened 2019-08-26 10:52 UTC
node -v
v11.10.1

npm -v
6.7.0

**Environment (please complete the following information):**
- macOs 10.14.5
 "devDependencies": {
    "@babel/cli": "7.2.3",
    "@babel/core": "7.4.0",
    "@babel/preset-env": "7.4.2",
    "@babel/register": "7.4.0",
    "@wdio/cli": "5.12.4",
    "@wdio/devtools-service": "5.12.3",
    "@wdio/local-runner": "5.12.4",
    "@wdio/mocha-framework": "5.12.1",
    "@wdio/spec-reporter": "5.12.1",
    "@wdio/sync": "5.12.3",
    "aws-sdk": "2.0.9",
    "chai": "4.2.0",
    "node-uuid": "1.4.8",
    "webdriverio": "5.12.4"
  }

**Describe the bug**
I have installed **"webdriverio": "5.12.4"** and from this version I monitoring problem with $() findElement.
For example, in the documentation is `$(selector).waitForExist(ms, reverse, error)`
In my test is
```
const abcButtonActiveElm = '//a[@id="xyz"]'
expect($(abcButtonActiveElm).waitForExist()).to.be.true
```
and sometimes is test end with error
```
$(...).waitForExist is not a function
```

**Comment by christian-bromann** [comment] 2019-08-26 11:02
Can you provide a reproducible example or at least some logs?

**Comment by christian-bromann** [comment] 2019-08-26 11:23
Closing as this is impossible for us maintainer to debug in any way. Happy to reopen once the actual problem was identified.

**Closed by christian-bromann** 2019-08-26 11:23 UTC

**Comment by gjulianm** [comment] 2019-10-07 16:06
Hello,

I've run into this problem, and I can provide an example (I think). This example works as expected:

```
it('should have loading overlay', () => {
    	browser.url('/files/index.html');

        const overlay = $('.full-page-overlay');

        overlay.waitForExist(3000);

        chai.expect(overlay.isDisplayed()).to.be.true;
    })
```

However, when using async/await this fails with the 'waitForExist' is not a function:

```
 it('should have loading overlay', async () => {
    	browser.url('/files/index.html');

        const overlay = $('.full-page-overlay');

        await overlay.waitForExist(3000);

        chai.expect(overlay.isDisplayed()).to.be.true;
    })
```

I'm just starting with WebdriverIO so it's highly probable that I'm doing something wrong, but I'm commenting this in case it's useful for somebody.

Here are my devDependencies just in case:

```
"devDependencies": {
    "@vue/cli-plugin-babel": "^3.11.0",
    "@vue/cli-plugin-eslint": "^3.11.0",
    "@vue/cli-plugin-unit-mocha": "^3.11.0",
    "@vue/cli-service": "^3.11.0",
    "@vue/test-utils": "1.0.0-beta.29",
    "@wdio/cli": "^5.14.3",
    "@wdio/local-runner": "^5.14.3",
    "@wdio/mocha-framework": "^5.14.3",
    "@wdio/spec-reporter": "^5.13.2",
    "@wdio/sync": "^5.14.3",
    "babel-eslint": "^10.0.1",
    "babel-plugin-istanbul": "^5.2.0",
    "chai": "^4.1.2",
    "chromedriver": "^77.0.0",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "jsdom": "^15.1.1",
    "mocha": "^6.2.1",
    "node-sass": "^4.12.0",
    "nyc": "^14.1.1",
    "patch-package": "^6.2.0",
    "sass-loader": "^8.0.0",
    "script-loader": "^0.7.2",
    "vue-template-compiler": "^2.6.10",
    "wdio-chromedriver-service": "^5.0.2"
  },
```

**Comment by mgrybyk** [comment] 2019-10-07 16:14
Please don't mix async functions and sync.
Either use async await everywhere (you are missing awaits in your second example) or don't use it at all, like in the first example

**Comment by gjulianm** [comment] 2019-10-07 16:25
Oh, I see that all calls are async, from the documentation I got the idea that only the wait ones were async. With all awaits it works, it seems that was the problem both me and the OP were having. Thanks!

**Comment by Andrew-Archon** [comment] 2020-02-09 17:08
**Describe your question with as much detail as possible**
When I try to run element.waitForExist() i am receiving an error that says `ERROR @wdio/runner: TypeError: $(...).waitForExist is not a function`.  I am running WebdriverIO in syncronous mode and I am using Appium and UIAutomator2 to run the tests on an Android emulator in Android Studio.  When I run the test spec, the app is installed and opened on the emulator correctly, but as soon as the appActivity is loaded, the test failed immediately on the waitForExist() call due to a type error.

**If it's about a specific piece of code, try and include some of it to support your question.**
```
import LoginScreen from "../shared/screens/login.screen";

describe("Logged in tests", function () {
  describe("Login", () => {      
    LoginScreen.waitForPageLoad()
  })

```
```
class LoginScreenImpl {
  waitForPageLoad() {    
      $("~Log In").waitForExist()
  }
}
const LoginScreen = new LoginScreenImpl()
export default LoginScreen
```


**Environment (please complete the following information):**
 - **WebdriverIO version:**
5.18.6
 - **Mode:** [Standalone mode or WDIO Testrunner]
WDIO Testrunner + Appium
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
Syncronous
 - **Node.js version:** [e.g. 8.9.1]
v10.15.3
 - **NPM version:** [e.g. 5.8.0]
Yarn v1.17.3
 - **Browser name and version:** [e.g. Chrome 68]
Android native app
 - **Platform name and version:** [e.g. Windows 10]
Android 9 (Android Studio on Windows 10)
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]
"dependencies": {
    "@wdio/appium-service": "5.18.2",
    "@wdio/cli": "5.18.6",
    "@wdio/local-runner": "5.18.6",
    "@wdio/mocha-framework": "5.18.6",
    "@wdio/selenium-standalone-service": "5.16.10",
    "@wdio/sync": "5.18.6",
    "appium": "1.16.0",
    "better-npm-run": "0.1.1",
    "proper-lockfile": "4.1.1"
  },
  "devDependencies": {
    "ts-node": "8.6.2",
    "tsconfig-paths": "3.9.0"
  }


**Additional context**
```
tsconfig:
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitThis": false,
    "noImplicitReturns": false,
    "esModuleInterop": true,
    "noEmit": true,
    "allowJs": false,
    "jsx": "react",
    "types": [
      "@wdio/appium-service",
      "@wdio/mocha-framework",
      "@wdio/sync",
      "node"
    ]
  },
  "include": [
    "**/*",
    "../mobile/**/*", <=the test spec is in mobile/tests/test.spec
    "../shared/**/*",
    "../packages/tests-common/**/*",
    "../web/**/*.constants.ts"
  ],
  "exclude": [
    "bin",
    "node_modules"
  ]
}
```

**Comment by Andrew-Archon** [comment] 2020-02-09 17:20
Executing script: android:local

to be executed: ""./node_modules/.bin/wdio" mobile/local.android.js"

Execution of 1 spec files started at 2020-02-09T17:16:39.632Z

2020-02-09T17:16:39.654Z INFO @wdio/cli:launcher: Run onPrepare hook
2020-02-09T17:16:41.342Z INFO @wdio/local-runner: Start worker 0-0 with arg: mobile/local.android.js
[0-0] 2020-02-09T17:16:41.975Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in com.inflowinventory.mobile.MainActivity - C:\inflow\online\tests\mobile\tests\index.spec.ts
[0-0] 2020-02-09T17:16:43.633Z INFO webdriverio: Initiate new session using the webdriver protocol
[0-0] 2020-02-09T17:16:43.635Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session
[0-0] 2020-02-09T17:16:43.636Z INFO webdriver: DATA { capabilities:
   { alwaysMatch:
      { automationName: 'UiAutomator2',
        platformName: 'Android',
        platformVersion: '9',
        deviceName: 'Pixel 2 API 28',
        app:
         'C:\\Users\\A\\Downloads\\app-develop-com.inflowdevelop.mobile-1.94.1074-alpha.apk',
        appWaitActivity: 'com.inflowinventory.mobile.MainActivity' },
     firstMatch: [ {} ] },
  desiredCapabilities:
   { automationName: 'UiAutomator2',
     platformName: 'Android',
     platformVersion: '9',
     deviceName: 'Pixel 2 API 28',
     app:
      'C:\\Users\\A\\Downloads\\app-develop-com.inflowdevelop.mobile-1.94.1074-alpha.apk',
     appWaitActivity: 'com.inflowinventory.mobile.MainActivity' } }
[0-0] 2020-02-09T17:16:55.504Z INFO webdriver: COMMAND findElement("accessibility id", "Log In")
[0-0] 2020-02-09T17:16:55.504Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session/cfe548f2-742b-49d6-b45b-5beaf1a0e5df/element
2020-02-09T17:16:55.505Z INFO webdriver: DATA { using: 'accessibility id', value: 'Log In' }
[0-0] 2020-02-09T17:16:55.505Z ERROR @wdio/runner: TypeError: $(...).waitForExist is not a function
    at LoginScreenImpl.waitForPageLoad (C:\inflow\online\tests\mobile\shared\screens\login.screen.ts:10:20)
    at Suite.describe (C:\inflow\online\tests\mobile\tests\index.spec.ts:20:17)
    at Object.create (C:\inflow\online\tests\node_modules\mocha\lib\interfaces\common.js:140:19)
    at context.describe.context.context (C:\inflow\online\tests\node_modules\mocha\lib\interfaces\bdd.js:42:27)
    at Suite.describe (C:\inflow\online\tests\mobile\tests\index.spec.ts:19:3)
    at Object.create (C:\inflow\online\tests\node_modules\mocha\lib\interfaces\common.js:140:19)
    at context.describe.context.context (C:\inflow\online\tests\node_modules\mocha\lib\interfaces\bdd.js:42:27)
    at Object.<anonymous> (C:\inflow\online\tests\mobile\tests\index.spec.ts:10:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module.m._compile (C:\inflow\online\tests\node_modules\ts-node\src\index.ts:814:23)
[0-0] Error: $(...).waitForExist is not a function
[0-0] 2020-02-09T17:16:55.553Z INFO webdriver: COMMAND deleteSession()
2020-02-09T17:16:55.553Z INFO webdriver: [DELETE] http://127.0.0.1:4723/wd/hub/session/cfe548f2-742b-49d6-b45b-5beaf1a0e5df
[0-0] 2020-02-09T17:16:55.691Z INFO webdriver: RESULT { error: 'no such element',
  message:
   'An element could not be located on the page using the given search parameters.',
  stacktrace:
   'NoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.findElOrEls (C:\\inflow\\online\\tests\\node_modules\\appium-android-driver\\lib\\commands\\find.js:75:11)' }
[0-0] FAILED in com.inflowinventory.mobile.MainActivity - C:\inflow\online\tests\mobile\tests\index.spec.ts
2020-02-09T17:16:56.449Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:16

2020-02-09T17:16:56.457Z INFO @wdio/local-runner: Shutting down spawned worker
2020-02-09T17:16:56.710Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2020-02-09T17:16:56.712Z INFO @wdio/local-runner: shutting down
error Command failed with exit code 1.
