### ISSUE TITLE
Keystrokes desynchronise with the actual output in the browser

### ISSUE THREAD

**Issue by benchesh** [webdriverio/webdriverio#6365] opened 2021-01-29 11:54 UTC
**Environment:**
 - **WebdriverIO version:** 6.8.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.20.1
 - **NPM version:** 6.14.11
 - **Browser name and version:** Chrome (v88.0.4324.96)
 - **Platform name and version:** macOS 10.14.6
 - **Additional wdio packages used (if applicable):** "@wdio/allure-reporter": "^6.7.2", "@wdio/browserstack-service": "6.7.3", "@wdio/cli": "^6.7.4", "@wdio/cucumber-framework": "^6.7.3", "@wdio/jasmine-framework": "^6.7.3", "@wdio/local-runner": "^6.7.3", "@wdio/selenium-standalone-service": "^6.7.3", "@wdio/spec-reporter": "^6.7.0", "@wdio/sync": "^6.7.3"

**Config of WebdriverIO**
Can provide if needed. It's a bit long and probably not relevant to this particular issue

**Describe the bug**
Methods using keystrokes such as `setValue` will sometimes fail to send the full string to the browser. One or more chars will appear to have never been input.

**To Reproduce**
Start lots of CPU heavy tasks (put stresses on your computer) & continuously run tests that fill in one or more fields. Log the value of the field immediately after, and at some point it may not match the expected string. For example ```this.$myInputField.setValue(myInput) && console.log(this.$myInputField.getValue());```

**Expected behavior**
For the field to always be entered correctly.

**Additional context**
I theorise this issue exists due to the slight delay in the time it takes for the browser to respond to the simulated keystrokes. If we read the field immediately after filling it in, we can detect if there's a mismatch and refill it. What happens in that scenario though is it tries to refill the field while still being affected by keystrokes from the previous run. It's as if it's still executing after moving on to the next line of code. Everything completely desynchronises and it ends up being stuck in an endless loop, filling in the field as different variants of the original input. If for example we try to input `my_username` to a field, it may only output `my_usern`, and then refilling that field will produce outputs like `amemy_usernam`, `usrnamemy_user`, `emy_username` and so on.

**Comment by christian-bromann** [comment] 2021-04-22 08:23
I think the only way to overcome this is to have an event for each keystroke. The problem I see is that no one knows when this problem occurs as no one can estimate when the CPU affects Chrome to behave this way. I am open to add an option to the `setValue`/`addValue` command to allow this but ultimately this seems to be a bug in Chrome and should be fixed there.

**Comment by erwinheitzman** [comment] 2021-04-23 10:28
From my experience this happens because under the hood `setValue` uses `clearValue` to clear the input field. When this happens this often triggers an error stating `input cannot be empty`. Either it happens so fast that it's not an issue or it happens a tad slower and the error interrupts the input. My personal experience was that knowing this and working around the error resolved the issues.

This experience is from a long time ago so it might not be applicable but it might be worth seeing if disabling the error in the frontend code temporarily fixes the problem or not. If so, we can add a warning to the documentation for this.

**Comment by christian-bromann** [comment] 2023-01-23 19:48
I am closing this issue as it has become stale. There is a known issue with Chromedriver swallowing key strokes which we can't fix in this code base. If anyone can provide a more reproducible example that a maintainer can use to look into I am happy to reopen this.

**Closed by christian-bromann** 2023-01-23 19:48 UTC
Labels: help wanted
