### ISSUE TITLE
weird behavior when reselecting child element

### ISSUE THREAD

**Issue by kurtharriger** [webdriverio/webdriverio#1492] opened 2016-07-26 22:37 UTC
## The problem

The following works:

```
let selected
selected = await browser.element('form').element('input').isSelected();
await browser.element('form').element('input').click();
selected = await browser.element('form').element('input').isSelected();
```

If however the intermediate values are saved to variables it does not work:

```
const form = browser.element('form');
const input = form.element('input');
selected = await input.isSelected();
await input.click();
selected = await input.isSelected();
```

It appears that `input` after the call to `.isSelected` revert to the `form` selector thus `input.click` clicks the `form` element not the `input` element should be expected. 
https://github.com/kurtharriger/webdriver-chaining-bug/blob/master/selenium.out#L60

We are attempting to develop a number of page objects to add more semantic behavior around various container components.  

Thus a `getProjectContainer()` button may return a `ProjectContainerComponent` that takes the parent element in constructor and then uses .element() to find localized child elements within the parent container.  This bug prevents me from passing the parent element in the constructor.  As a workaround I started passing the selector instead, this works but doesn't compose well, so I started passing in a function instead, but this is very non-intuitive and keeps popping up after few simple should be safe refactorings. 

## Code To Reproduce Issue [ Good To Have ]

https://github.com/kurtharriger/webdriver-chaining-bug

## Environment

* WebdriverIO version: "^4.2.3"
* Node.js version: 5.11.1

## Link to Selenium/WebdriverIO logs

https://github.com/kurtharriger/webdriver-chaining-bug

**Comment by christian-bromann** [comment] 2016-10-08 13:26
@kurtharriger does this work if you run wdio with sync: true?

**Comment by MiguelCastillo** [comment] 2016-10-24 02:16
I am also running into this issue.  I am currently setting up page objects with basically the same approach as @kurtharriger.

I have put together a sample script that can reproduce the issue [here](https://gist.github.com/MiguelCastillo/cb44ee1a9746f7bfc2cb17c4c15fefe1)

Removing (commenting out) the `await` from line 17 makes things behave correctly.  So it seems like the issue is dealing with command execution on promises that have been already resolved.

This is the trace for the [bad async run](https://gist.github.com/MiguelCastillo/a9af226104537399021dfc9c014d4faf)
This is the trace for the [good async run](https://gist.github.com/MiguelCastillo/bbf9d18874e94fef5c6f98fbfe10a076)

I ran this in `sync` mode, things worked correctly.  I unfortunately can't run in `sync` mode because there are mixed in ajax calls that are running `async`.

I am trying to debug webdriver... If I find anything, I let you know.

**Comment by MiguelCastillo** [comment] 2016-10-24 02:34
For the record, the issue of reselecting an element was what I initially observed.  But I then realized the issue was just the await in the middle of the mix.  So my script does not really show reselecting.  If we think these issues are not related, then I am more than happy to file a different defect.  :)

**Comment by christian-bromann** [comment] 2016-10-24 06:39
@MiguelCastillo you can still run your code in sync mode even with mixed ajax call, here is an example:

```js
expect(browser.getTitle()).to.be.equal('foobar');
browser.click("#selector");
browser.call(function() {
    return someAjaxCall()
});
browser.click("#otherSelector");
```

**Comment by christian-bromann** [comment] 2016-10-24 06:42
Also have you tried to run this code:
```js
import { expect } from 'chai';

describe('Bad test when awaiting  google Suite', () => {
	beforeEach(async () => {
		await browser.url('https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=bit-bundler');
	});

	describe('Getting all results container', () => {
		var resultWithId, resultText;

		beforeEach(async () => {
			await browser.waitForExist('[data-hveid="41"]');
			resultText = await browser.element('[data-hveid="41"]').getText('.r');
		});

		it('then the text is all good', () => {
			expect(resultText).to.equal('bit-bundler-browserpack - npm');
		});
	});
});
```

**Comment by MiguelCastillo** [comment] 2016-10-24 10:59
@christian-bromann right. Ajax calls will be in beforeEach calls will I expect them to be in nested describes.

So the example i provided was to show a smallest unit to reproduce the issue. Is what I provided in the example not valid?  The reason I ask is that I'm structuring my tests with several nested page objects. And each page own its own element as a way to scope DOM interaction, and that is failing to scope DOM interaction.

Am I supposed to structure where each page only does queries from the browser or can I use page objects that have their own element and be able to nest them?

I can change the test script to better represent what my tests look like.

**Comment by MiguelCastillo** [comment] 2016-10-24 14:39
@christian-bromann Here is a script that illustrate my workflow more accurately.

``` javascript

import { expect } from 'chai';

describe('Bad test when awaiting  google Suite', () => {
	beforeEach(async () => {
		await browser.url('https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=bit-bundler');
	});

	describe('Getting all results container', () => {
		var resultsContainer;

		beforeEach(async () => {
			resultsContainer = browser
				.waitForExist('.srg')
				.element('.srg');

			await resultsContainer;
		});

		it('then the container is OK', async () => {
			expect(await resultsContainer).to.be.ok;
		});

		describe('Getting a particular item', () => {
			var resultWithId;

			beforeEach(async () => {
				resultWithId = resultsContainer
					.waitForExist('[data-hveid="41"]')
					.element('[data-hveid="41"]');

				await resultWithId;
			});

			it('then the text is matched', async () => {
				expect(await resultWithId.getText('.r')).to.equal('bit-bundler-browserpack - npm');
			});
		});
	});
});

```

**Comment by christian-bromann** [comment] 2016-10-24 14:41
And this is not working?

**Comment by MiguelCastillo** [comment] 2016-10-24 14:45
no.  It gives an array as a result in `getText`.  The reason I had given you the first script was to illustrate how the await affects the workflow.  If you await an element and interact with it afterwards, the scope is somehow broken.  I also tried the protocol method `elementIdText` and I get a null back when I await.  If I don't await the element, then I get the correct behavior.

I can happily setup a project for you if would like to run it... :)

**Comment by christian-bromann** [comment] 2016-10-24 14:52
> It gives an array as a result in getText

This is not unusual. If the selector (`.r`) matches multiple elements it returns automatically an array with the result of that command for all matching elements. If you are only interested in asserting a single result either try to be more explicit with the selector or do:
```js
            it('then the text is matched', async () => {
                expect((await resultWithId.getText('.r'))[0]).to.equal('bit-bundler-browserpack - npm');
            });
```

**Comment by MiguelCastillo** [comment] 2016-10-24 14:54
Right.  the issue is that there is only *one* `.r` in `element('[data-hveid="41"]')`.  If I await the element, I get an array.  If I don't then I get one item.

**Comment by MiguelCastillo** [comment] 2016-10-24 14:56
This gives me the correct result...

``` javascript
import { expect } from 'chai';

describe('Bad test when awaiting  google Suite', () => {
	beforeEach(async () => {
		await browser.url('https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=bit-bundler');
	});

	describe('Getting all results container', () => {
		var resultsContainer;

		beforeEach(async () => {
			resultsContainer = browser
				.waitForExist('.srg')
				.element('.srg');

			await resultsContainer;
		});

		it('then the container is OK', async () => {
			expect(await resultsContainer).to.be.ok;
		});

		describe('Getting a particular item', () => {
			var resultWithId;

			beforeEach(async () => {
				resultWithId = resultsContainer
					.waitForExist('[data-hveid="41"]')
					.element('[data-hveid="41"]');

				// Commenting out to illustrate the issue
				// await resultWithId;
			});

			it('then the text is matched', async () => {
				expect(await resultWithId.getText('.r')).to.equal('bit-bundler-browserpack - npm');
			});
		});
	});
});

```

**Comment by MiguelCastillo** [comment] 2016-10-24 14:57
If I setup a project, do you think you would be so kind to take a closer look?

**Comment by christian-bromann** [comment] 2016-10-24 15:01
Ok, it looks like awaiting the result prevents the result from being propagated to the next command. In standalone (async) mode that propagation functionality only works if you call a command directly after the element command. We don't touch the actual result at the end as we do with the wdio testrunner. I would still recommend switching to it.

There is no need to setup an example project. I know the issue here. I don't think it is a good idea to manipulate the prototype of the result as this could break APIs of 3rd party libraries using WebdriverIO as their automation framework.

So there are two options: living without the resolving await and not use the wdio testrunner or: using the wdio test runner and get rid of all awaits. I recommend the latter for multiple reasons.

**Closed by christian-bromann** 2016-10-24 15:01 UTC
Labels: Bug, Needs Investigation

**Comment by MiguelCastillo** [comment] 2016-10-24 16:19
Thanks for resetting expectations.  Just to make sure I am 100% understanding what you are saying.  You are saying that async/await isn't supported in wdio, or that this should work (which you seemed surprised to find out it wasn't working) and there is no plan to fix this right now?

**Comment by christian-bromann** [comment] 2016-10-24 16:27
> that async/await isn't supported in wdio

No! async/await definitely works with WebdriverIO in standalone mode. If you are using the wdio testrunner there is no need to use it because all commands are automatically synchronous.

> there is no plan to fix this right now?

I wouldn't say this is something to fix. It is more a design decision. The way how you resolve the promise with await is not compatible with the way how we propagate the element from one command to the next. So:

```js
var resultWithId = browser.waitForExist('[data-hveid="41"]')
expect(await resultWithId.element('[data-hveid="41"]').getText('.r')).to.be.equal(...);
```

works because you chain the element command directly with the action command. But


```js
var resultWithId = browser.waitForExist('[data-hveid="41"]');

var elem = await resultWithId.element('[data-hveid="41"]');
expect(await elem.getText('.r')).to.be.equal(...);
```

won't work because you resolve the promise before calling the next command. I don't want to change this behavior because it would require that I modify the prototype/result and this can break 3rd party libraries using WebdriverIO as standalone package.

I just really recommend switching to the testrunner. It helps you with so much things and make your test less complicated.

**Comment by MiguelCastillo** [comment] 2016-10-24 16:44
Thanks so much for taking the time to explain this!  I am currently using the test runner.  Perhaps I conflated the support of async/await from standalone since it wasn't clear to me from the docs that I shouldn't use async/await in the test runner.  Meaning, that I thought async/await was supported in the test runner since I didn't see that this was a behavior specific to stand alone :)

I understand you won't change this in the test runner.  Perhaps I missed it in the docs that this is the expected behavior...  But, in case it is not clearly documented.... It might be really useful (perhaps save some of us from pulling our hair) if the expected use in *test runner* was a bit more clear that async/await breaks command chains and it is not supported?  I am happy to send a PR your way.

Thank you for your time!!

**Comment by christian-bromann** [comment] 2016-10-24 16:47
> I am happy to send a PR your way.

Thanks. I just (https://github.com/webdriverio/webdriverio/commit/f314906728dbd2c153dc5bf78d67404160246b04) incorporated this discussion into the docs and hope it will be clear with the release of the next version. If it still isn't 100% clear I am happy to receive any PRs.

**Comment by MiguelCastillo** [comment] 2016-10-24 16:49
Cool - I will take a look.
