### ISSUE TITLE
elem.isDisplayed() should return bool , but throws error on ie

### ISSUE THREAD

**Issue by pmerwin** [webdriverio/webdriverio#3840] opened 2019-04-10 23:18 UTC
When using .isDisplayed() on IE over sauce, wdio throws error not a boolean.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [5.7.12]
 - **Mode:** [ WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [8.10]
 - **NPM version:** [6.5.0]
 - **Browser name and version:** [ie 11]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/sauce]

**Config of WebdriverIO**
```
user: config.saucelabs.user,
    key: config.saucelabs.key,
    hostname: 'ondemand.saucelabs.com',
    maxInstances: 3,
    capabilities: [
        {
            browserName: 'internet explorer',
            platformVersion: 'Windows 10',
            browserVersion: '11.0',
        }
    ],
    mochaOpts: {
        ui: 'bdd',
        timeout: 120000,
        bail: true
    },
    services: ['sauce'],
    reporters: ['spec'],
    coloredLogs: true,
    deprecationWarnings: false
});
```

**Describe the bug**
$('.some.elem').isDisplayed() throws error on ie, should return bool like on chorme.

**To Reproduce**
Run a spec that does that uses$('.some-elem').isDisplayed();

```
 it.only('should not throw error', function () {
        browser.url('https://www.google.com');
        const isD = $('.loading-bubbles').isDisplayed();
        console.log(isD);
    });
```

[Include code or an example repository that can easily be set up]

**Expected behavior**
The method should return false and not an error if the element is not displayed

**Log**
https://gist.github.com/pmerwin/f504f8270fa9767aca395086538586e8

sauce job:
https://app.saucelabs.com/tests/02b2b28c03da4fcb9c778469c95b7628
**Additional context**

**Comment by christian-bromann** [comment] 2019-04-12 09:38
Duplicate of #3834

**Closed by christian-bromann** 2019-04-12 09:38 UTC

**Comment by StephenABoyd** [comment] 2019-04-23 15:08
@christian-bromann I don't think the fix for #3834 is going to fix this. I'm seeing the issue on the findElement call, not the isDisplayed call. Should this be reopened?

**Comment by christian-bromann** [comment] 2019-04-23 15:11
> I'm seeing the issue on the findElement call

What issues do you see?

**Comment by StephenABoyd** [comment] 2019-04-23 15:15
When running in IE on Browserstack it matches the error of this issues log:

`Unable to find element with xpath == //hello (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 348 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: '207-254-7-115', ip: '207.254.7.115', os.name: 'windows', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_181'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{browserAttachTimeout=0, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.usePerProcessProxy=false, ignoreZoomSetting=false, handlesAlerts=true, version=11, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=false
, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=about:blank, takesScreenshot=true, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCle
anup=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=dismiss}]
Session ID: 5933fa73-fb46-497c-ae16-9ffb948fd4f5
*** Element info: {Using=xpath, value=//hello}`

During debugging I found it fails in the webdriverio/src/utils.js on the `findElement` function:

 `return this.elementId ? this.findElementFromElement(this.elementId, using, value) : this.findElement(using, value);`

**Comment by christian-bromann** [comment] 2019-04-23 15:17
This log seems like that an element wasn't found.

**Comment by StephenABoyd** [comment] 2019-04-23 15:19
Yes, that is correct, but it throws an error when trying to find the element. So if I make an `isDisplayed` call on an element that isn't displayed this gets thrown before `isDisplayed` even runs.

**Comment by christian-bromann** [comment] 2019-04-23 15:25
@StephenABoyd I think this is a different issue than this here. Do you have a minimal reproducible example?

**Comment by StephenABoyd** [comment] 2019-04-23 15:29
I was assuming it was the same since the errors were the same while trying to find a nonexistent element. 

Honestly, my example was just going to google and looking for a made-up element in IE with Browserstack, but according to this issue, it should happen in sauce as well

`
browser.url('http://www.google.com');
if ($(`//hello`).isDisplayed()) {
    console.log('yay');
}
`

**Comment by christian-bromann** [comment] 2019-04-23 16:18
Confirmed the issue. I think it has to to with the way IE responses.

**Comment by pmerwin** [comment] 2019-04-23 16:31
Yeah, it is not responding with a bool, it is responding with error ...  I think because IE's error is outside the logic for the catch block in the method?

**Comment by pmerwin** [comment] 2019-04-23 16:32
> Yes, that is correct, but it throws that as an error when trying to find the element. So if I make an `isDisplayed` call on an element that isn't displayed this gets thrown before `isDisplayed` even runs.

Exactly the issue I am seeing.

**Comment by christian-bromann** [comment] 2019-04-23 17:07
see #3874
