### ISSUE TITLE
Sauce service doesn't seem to manage Sauce Connect for RDC

### ISSUE THREAD

**Issue by LasseHall** [webdriverio/webdriverio#4137] opened 2019-07-03 09:00 UTC
**Environment (please complete the following information):**
 - **Additional wdio packages used (if applicable):** @wdio/wdio-sauce-service

**Config of WebdriverIO**
```
services: ['sauce'],
sauceConnect: true,
region: us,
capabilities = [
  {
    deviceName: 'iPhone XS',
    testobject_api_key: process.env.SAUCE_RDC_ACCESS_KEY,
    platformName: 'iOS',
    platformVersion: '11.4',
    sauceConnectOpts: {
      tunnelIdentifier: tunnel-name
    },
  },
]
```

**Describe the bug**
Sauce service manages the usage of RDC API for updating job status, etc. Launching **Sauce Connect** to RDC and managing the sauceConnectOpts doesn't seem to be done correctly though.

**To Reproduce**

Implement sauce service and make use of Sauce Connect through the service, targeting Real Device Cloud.

**Expected behavior**
The service should know how to launch Sauce Connect correctly on specified RDC region. Test session should implement capabilities correctly to make use of tunnelIdentifier.

**Additional context**
Documentation needs to be updated to reflect any differences in terms of configuring the service for RDC. https://webdriver.io/docs/sauce-service.html

**The config needs to understand that RDC makes use of a specific RDC User API Key to establish the tunnel connection. testobject_api_key won't work.**

**Comment by wswebcreation** [comment] 2019-07-03 13:54
It's not a bug, it's a feature 😂

When the RDC support has been implemented only the API part was implemented, not the SC

**Comment by arcmorales** [comment] 2019-07-14 07:54
Hello @wswebcreation, question for sauce-service..

when we upgraded webdriverIO to v5, we installed `@wdio/sauce-service` because it would automatically update the status of our test in Saucelabs RDC. Previously on v4, we had to use `testobject_api` https://www.npmjs.com/package/testobject_api/v/2.0.0 package to update the status.

This was then our packages after our initial update to v5:
```
    "@wdio/sauce-service": "^5.9.3",
   "@wdio/sync": "^5.9.4",
    "webdriverio": "^5.9.4"
  ```

So after updating, there was no need to use `testobject_api` to update the tests results in RDC. However, we kept getting intermittent failures in updateTest.
`ERROR @wdio/sync: Error: Failed calling updateTest, status code: 204, reason: unknown`

I tried to update my packages to the latest `@wdio/sauce-service` so I am now at `5.11.1` in an attempt to resolve the errors. Seems to be Ok so far. May I know why in the earlier version of sauce-service I was getting that error? There were no code/config changes on our end and I couldn't seem to find issues that are related to what we were having.

Thanks!

**Comment by wswebcreation** [comment] 2019-07-24 08:10
Hi @arcmorales 

The `ERROR @wdio/sync: Error: Failed calling updateTest, status code: 204, reason: unknown` had to do with the fact that WebdriverIO always updates the name of a testcase after each run.  But the real device cloud of Sauce Labs doesn't allow you to do that, they only allow you to update the status of the test.
In a previous release this has been fixed.

**Comment by christian-bromann** [comment] 2019-07-24 09:15
> status code: 204

I think this is a problem in `node-saucelabs` treating this request as failure while it is actually a success. Will create a ticket there.

**Comment by christian-bromann** [comment] 2019-07-24 09:17
Mhm .. something is off here:

```
                if (response.statusCode !== 200 && response.statusCode !== 204) {
                    const reason = getErrorReason(body)
                    return reject(new Error(`Failed calling ${propName}, status code: ${response.statusCode}, reason: ${reason}`))
                }
```

**Comment by christian-bromann** [comment] 2019-07-24 09:27
Closing, as this is fixed (my bad). @LasseHall can you try to reproduce this to see if it is also fixed on your end?

**Comment by christian-bromann** [comment] 2020-09-02 10:00
This has been fixed due to the launch of unified platform.

**Closed by christian-bromann** 2020-09-02 10:00 UTC
Labels: Bug🐛
