### ISSUE TITLE
enhance selector API to select nth-Child

### ISSUE THREAD

**Issue by khaldoun** [webdriverio/webdriverio#682] opened 2015-07-31 20:52 UTC
Hello,
I have two select control in the same page with the same ID and the same Class.
On of them is visbile and the other one is hidden ( for some responsive propose)
So I can not create an XPath selector neither a css selector to manipulate only the active one.
My use case is just to select an option from the select that is visible.
I have tried selectByVisibleText(selector,value) but I have always this message 

ERROR	ElementNotVisible	An element command could not be completed because the element is not visible on the page.  element not visible: Element is not currently visible and may not be manipulated.

my selector gives me always tow elements :
[16:42:52]:  DATA		 {"using":"xpath","value":"//div[@id=\"ProductType\"]/div/div/div/select"}
[16:42:52]:  RESULT		 [{"ELEMENT":"6"},{"ELEMENT":"7"}]

**Comment by christian-bromann** [comment] 2015-08-02 21:42
I would suggest to remove the hidden select box using the `execute` command right before you do the selection. I guess the selectbox for the responsive view is not important for you e2e test.

**Comment by khaldoun** [comment] 2015-08-02 21:56
Thanks Christian for our quick answer.
I think what do you suggest is like a workaround for a very commun issue.
Let's imagine another use case that we can not create a very unique selector to access to a component. the best selector that we can have give us access to n elements. and we know that in our test E2E that we need to click on the second element or the third one. is there a way that using the api to say hey webdriveio manipulate element number 3 that comes from this selector

**Comment by christian-bromann** [comment] 2015-08-02 23:58
True, usually I got around this using xPath but I see your point that it would be nice to have that somehow build in. What would you suggest? something like `nth-Child` support?

**Comment by khaldoun** [comment] 2015-08-03 12:54
The nth-Child could be a very reliable solution.
For my personal issue I will try to resolve it using Xpath as suggested.

**Comment by pazone** [comment] 2015-11-27 09:54
@khaldoun , if you are using xpath, you can get N-th element by this way: ```(//div[@id=\"ProductType\"]/div/div/div/select)[N]```. Also css selectors has ```nth-child``` and ```nth-of-type``` pseudo-classes. I recommend to keep this logic in selectors because it much easier to actualise tests after changes.

**Comment by christian-bromann** [comment] 2016-01-25 01:11
duplicate of #891

**Closed by christian-bromann** 2016-01-25 01:11 UTC
Labels: Discussion, Enhancement
