### ISSUE TITLE
specFiltering doesn't work when destructuring imports are used

### ISSUE THREAD

**Issue by srini-myob** [webdriverio/webdriverio#5061] opened 2020-02-26 08:36 UTC
When using destructuring imports, specFiltering doesn't skip that spec file. _(Using mocha framework & explicitly setting the feature flag `specFiltering` true)_

**Describe the bug**
When using destructuring imports, the specFiltering doesn't skip that spec file. Following this (https://webdriver.io/blog/2019/11/01/spec-filtering.html), I've enabled this feature in my mocha setup by explicitly setting `specFiltering` flag true. It works fine except when there is a destructured import in spec file's root scope. 

**To Reproduce**
- Have specFiltering enabled and have an import like below - 
`const { a } = require('../module');`
- Now, run wdio with mocha grep command so that it's supposed to skip this spec -
`wdio --mochaOpts.grep asdf ./wdio.conf.js --suite testSuite`

**Expected behavior**
The spec file with destructured import is expected to be skipped and the reporter should include this spec under `skipped` 

**Actual behavior**
The spec file with destructured import is not counted as `skipped` BUT counted as `passed`. Also, a session is started for this spec.

**Comment by mgrybyk** [comment] 2020-02-26 08:57
What is in your module?

**Comment by srini-myob** [comment] 2020-02-26 23:56
Yeah, I've got the browser commands in before hook only & just imports in the root scope - which is where your doc suggests putting those in. The moment I comment out that particular import statement, the spec file is skipped as expected.

**Comment by christian-bromann** [comment] 2020-02-27 09:38
@srini-myob can you provide a minimal reproducible example?

**Comment by srini-myob** [comment] 2020-02-28 06:40
UPDATE: Issue looked like it was because of destructured assignments. Because removing those imports resolved the issue. On looking closer, it's because of the usage of a global variable in a js file that's being imported.
 
Here is a fork of one of the boilerplate repos & I've modified it to reproduce the scenario. 

- Clone https://github.com/srini-myob/webdriverIO-with-mochaBDD
- Run `npm install` and `npm run test`

There are 2 spec files `spec` and `spec2` under test/specs. And the npm run command uses `--mochaOpts.grep` to filter with a text that's supposed to skip both the tests. However, I import in a spec file which is NOT skipped while the other spec file (which doesn't have any import) is skipped as expected. 

Usage of grep - https://github.com/srini-myob/webdriverIO-with-mochaBDD/blob/master/package.json#L8

Here is the import that's causing the issue - https://github.com/srini-myob/webdriverIO-with-mochaBDD/blob/master/test/specs/spec1.js#L1

Here is the global variable usage in that imported file - https://github.com/srini-myob/webdriverIO-with-mochaBDD/blob/master/test/test-data/user-data.js#L7-L13

Now, if I either comment out the import or the usage of global inside that file, the test `spec1` is skipped as expected. Without doing that, the issue persists. 

![image](https://user-images.githubusercontent.com/40377584/75516785-51d53700-5a51-11ea-9c70-1c59b25db0b8.png)

**Comment by mgrybyk** [comment] 2020-02-28 09:48
@srini-myob the issue is not reproducible in your repo. The spec is skipped as expected.

Please also note that you have to move your transpilers like `@babel/register` to `mochaOpts.require`

**Comment by srini-myob** [comment] 2020-02-28 22:07
@mgrybyk You just reproduced the issue exactly - seeing your screenshot. You are supposed to see `2 skipped` but you get `1 passed, 1 skipped`. That's the issue - the spec with that problematic import is not getting skipped. 

> Please also note that you have to move your transpilers like @babel/register to mochaOpts.require
I've moved them under mochaOpts and even removed them altogether - no change in the output.

**Comment by christian-bromann** [comment] 2020-03-10 12:51
@srini-myob it seems that `TESTENV` [here](https://github.com/srini-myob/webdriverIO-with-mochaBDD/blob/master/test/test-data/user-data.js#L7) is not defined, you need to access it via `global.TESTENV`. Nonetheless is this a bug on WebdriverIO side as the error is not properly captured.

**Comment by christian-bromann** [comment] 2020-04-20 07:55
Closing as this issue doesn't seem to be moving forward and an bug on WebdriverIO side couldn't be reproduced.

**Closed by christian-bromann** 2020-04-20 07:55 UTC
Labels: Bug🐛, help wanted
