### ISSUE TITLE
Don't see console.log('hello') from onComplete hook in the console

### ISSUE THREAD

**Issue by prathameshnyt** [webdriverio/webdriverio#3869] opened 2019-04-19 13:27 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.7.8
- **Mode:** WDIO Testrunner
 - **Node.js version:** v10.15.2
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome 73
 - **Platform name and version:** Mac Os 10.14.4 (18E226

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
As discussed on Gitter, creating issue for us to further followup. I don't see console.log('hello') from onComplete hook message in the console.

**To Reproduce**
Add console.log('hello') in onComplete hook. If I console.log(config) then sometimes it does output it in the console, but not the complete object.

**Comment by christian-bromann** [comment] 2019-04-19 13:45
@prathameshnyt can you provide a reproducible example?

**Comment by prathameshnyt** [comment] 2019-04-19 13:50
Thanks @christian-bromann I will look into best way to send you an example. In meantime, I have basicTest from the the guide and running it with test runner with following in onComplete hook. @WillBrock was able to reproduce it as well.

```
    onComplete: function(exitCode, config, capabilities, results) {
        console.log('Hello');
    },
```

**Comment by christian-bromann** [comment] 2019-04-19 13:57
Was able to reproduce it too

**Comment by prathameshnyt** [comment] 2019-04-19 14:00
Ok. Thanks for confirming.

**Comment by mariobianco** [comment] 2019-04-23 20:59
Not sure if this helps provide further info, but I narrowed down the bug to being related to `@wdio/cli version 5.7.9+`. Specifically the bug first showed up in 5.7.9 perhaps something related to [this PR](https://github.com/webdriverio/webdriverio/pull/3638).

**Comment by baruchvlz** [comment] 2019-04-24 10:20
Any log before [this line](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-cli/src/launcher.js#L83) works. It seems that [runMode](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-cli/src/launcher.js#L99) is not resolving / rejecting in some cases. I have added two logs, [here](https://github.com/baruchvlz/webdriverio/blob/fix/oncomplete/packages/wdio-cli/src/launcher.js#L84) and [here](https://github.com/baruchvlz/webdriverio/blob/fix/oncomplete/packages/wdio-cli/src/launcher.js#L156), which are never executed.


Interestingly enough, this onComplete executes and logs.:
```
onComplete: function() {
  console.log('onComplete')
  process.exit(1)
}
```

![image](https://user-images.githubusercontent.com/14321495/56652255-3956fc00-668b-11e9-87fa-653b9f0ad825.png)

I'll keep debugging see if I can find the solution.

**Comment by mgrybyk** [comment] 2019-04-24 15:23
@baruchvlz how you managed logs to be displayed?

I'm seeing the same behaviour not only for onComplete hook but in other places as well.
Yeah, logUpdate overrides output

**Comment by baruchvlz** [comment] 2019-04-24 15:26
@mgrybyk Check this commit: https://github.com/baruchvlz/webdriverio/commit/d169de7f3a5e0441f4527d98abcf24a9d371d105

**Closed** 2019-05-20 17:20 UTC
Labels: Bug🐛, good first pick, help wanted

**Comment by prathameshnyt** [comment] 2019-06-11 15:20
Thank you for looking into it and fixing this issue.

**Comment by YashMonetate** [comment] 2020-11-06 12:15
Write operation is not working under onComplete of wdio.conf file.
Also i am trying to pring 4 console.log but it seems that only one console is getting printed. I am using `"@wdio/cli": "^5.8.3",`. is it fixed for this version?

Can you please confirm if we can access all the global variables insided onComplete for write operations @mgrybyk

**Comment by christian-bromann** [comment] 2020-11-06 12:35
@YashMonetate you can't access the `browser` instance anymore in there but all other native Node.js modules are available.

**Comment by YashMonetate** [comment] 2020-11-06 12:54
Thanks @christian-bromann . I am running my automation suite that has 40 test file. I observed that after every test file chromedriver gets closed and all global variable insided wdio.conf file gets reset when it's time to run next test file. 

Due to above issue i am not able to write consistently during my entire 40 tests file. Everytime it overwrites. Can you please suggest some way to achieve this in wdio. Thanks!

**Comment by christian-bromann** [comment] 2020-11-06 13:08
Not sure what you are doing exactly but note that every hook is unique per worker instance (test) you can't keep global variables around that are available in all tests. You need to store those in files and manage the data yourself.

**Comment by YashMonetate** [comment] 2020-11-06 13:12
i am trying to add test id and it's result(pass/fail) in an array and after all 40 test files gets executed i want to write that array in .txt file. But it seems as soon as control reach onComplete block, my array gets lost it's values.

**Comment by christian-bromann** [comment] 2020-11-06 14:54
Have you tried to use https://www.npmjs.com/package/wdio-testrail-reporter? It probably doesn't work like this anymore as it is 3 years old but you can maybe check out the code. Please note that you don't have access to any global variables you set in onPrepare and onComplete hooks as they are in a different process. I recommend to write the results into individual files and merge them all together in the onComplete hook.

**Comment by YashMonetate** [comment] 2020-11-09 05:23
@christian-bromann Thankyou for this recommendation, but i already tried that it doesn't seem to work for me.

For your second statement, if i merge all files how can i prepare a valid JSON request at the end. This seems cumbersome task.

I need to prepare something like below for 500 tests(but all divided in 40 spec files):
```
{
  "foo1": [
        { "one": "value"},
        { "two": "value"}.
   ]
}
```

**Comment by christian-bromann** [comment] 2020-11-09 09:45
> For your second statement, if i merge all files how can i prepare a valid JSON request at the end. This seems cumbersome task.

Unfortunately this is the only way how things work at the moment. Create report files for every worker and merge them in the `onComplete` hook. This can be encapsulated into a single service.
