### ISSUE TITLE
I select body element in one page, and in ie7~10, I got some js errors. Help me please.

### ISSUE THREAD

**Issue by Naixor** [webdriverio/webdriverio#554] opened 2015-06-03 03:25 UTC
> such as th error below, it seems like selectorExecute() went wrong.
```JavaScript
{
    "name":"RuntimeError",
    "message":"RuntimeError\n (UnknownError:13) An unknown server-side error occurred while processing the command.\n Problem: JavaScript error (WARNING: The server did not provide any stacktrace information)\nCommand duration or timeout: 30 milliseconds\nBuild info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'\nSystem info: host: 'winxp2014-085', ip: '10.94.26.94', os.name: 'Windows XP', os.arch: 'x86', os.version: '5.1', java.version: '1.6.0_18'\nSession ID: 675c13da-9002-4b98-8195-4e0aeeb80692\nDriver info: org.openqa.selenium.ie.InternetExplorerDriver\nCapabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, enablePersistentHover=true, ignoreZoomSetting=false, ie.ensureCleanSession=false, browserName=internet explorer, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss, version=8, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus=false, initialBrowserUrl=http://localhost:33344/, handlesAlerts=true, ie.forceCreateProcessApi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]\u001b[1;30m\n\n Callstack:\n -> execute(\"return (function (fn, sArr, args) { var cb = arguments[arguments.length - 1], i = 0, sArgs = [], use, value, xp, cs, tn, res, j, arg; while ((use = sArr[i++]) && (value = sArr[i++])) { arg = []; xp = cs = tn = [Function]; switch (use) { case \\\"partial link text\\\": xp = '//a[contains(text(),\\\"'+value+'\\\")]'; break; case \\\"link text\\\": xp = '//a[text()=\\\"'+value+'\\\"]'; break; case \\\"xpath\\\": xp = value; break; case \\\"id\\\": cs = '[id=\\\"'+value+'\\\"]'; break; case \\\"name\\\": cs = '[name=\\\"'+value+'\\\"]'; break; case \\\"tag name\\\": tn = value; break; case \\\"css selector\\\": cs = value; break; default: throw new Error(\\\"Could not evaluate selector: Invalid strategy \\\" + use); } if (xp) { res = document.evaluate(xp, document, null, 0, null); while (value = res.iterateNext()) { arg.push(value); } } else if (tn || cs) { res = tn ? document.getElementsByTagName(tn) : document.querySelectorAll(cs); j = 0; while (value = res[j++]) { arg.push(value); } } sArgs.push(arg); } var parameter = args && sArgs.concat(args) || sArgs; if(parameter.length === 0 || (parameter.length === 1 && parameter[0].length === 0)) { if(typeof cb === 'function') { return cb('NoSuchElement') && new Error('NoSuchElement'); } return new Error('NoSuchElement'); } parameter.push(arguments[arguments.length - 1]); return fn.apply(window, parameter);\\n})(function (elem) { /** * get current scroll position * @return {Object} x and y coordinates of current scroll position */ var getScrollPosition = function() { var x = 0, y = 0; if (typeof(window.pageYOffset) == 'number') { /* Netscape compliant */ y = window.pageYOffset; x = window.pageXOffset; } else if (document.body && (document.body.scrollLeft || document.body.scrollTop)) { /* DOM compliant */ y = document.body.scrollTop; x = document.body.scrollLeft; } else if (document.documentElement && (document.documentElement.scrollLeft || document.documentElement.scrollTop)) { /* IE6 standards compliant mode */ y = document.documentElement.scrollTop; x = document.documentElement.scrollLeft; } return { x: x, y: y }; }; /** * needs to get defined that verbose to make it working in IE driver */ var boundingRect = elem[0].getBoundingClientRect(), elemBounding = { width: boundingRect.width ? boundingRect.width : boundingRect.right - boundingRect.left, height: boundingRect.height ? boundingRect.height : boundingRect.bottom - boundingRect.top, top: boundingRect.top, right: boundingRect.right, bottom: boundingRect.bottom, left: boundingRect.left }; return { title: document.title, scrollPos: getScrollPosition(), screenWidth: Math.max(document.documentElement.clientWidth, window.innerWidth || 0), screenHeight: Math.max(document.documentElement.clientHeight, window.innerHeight || 0), elemBounding: elem[0] ? elemBounding : null }; },[\\\"css selector\\\",\\\"body\\\"],[], arguments[arguments.length - 1]);\")\n -> selectorExecute(\"body\",[Function])\n"
}
```

**Comment by christian-bromann** [comment] 2015-06-03 14:32
yes, duplicate of #552, will get fixed in `v3`. Thanks for reporting this.

**Closed by christian-bromann** 2015-06-03 14:32 UTC

**Comment by christian-bromann** [comment] 2015-06-10 02:31
@Naixor this is fixed and will get shipped with `v3` soon!
