### ISSUE TITLE
can not get the info of the screenshot in the error message

### ISSUE THREAD

**Issue by xiejunfeng** [webdriverio/webdriverio#2026] opened 2017-04-27 10:01 UTC
## The problem

![image](https://cloud.githubusercontent.com/assets/6460243/25477431/1087f246-2b70-11e7-897b-43525d4a0c82.png)

does that meas the screenshot should be put into the error message?? if it dose, i can't get the scrrenshot.

my reporter is base on the json repoter, i get the test info like this;

![image](https://cloud.githubusercontent.com/assets/6460243/25477952/dd48ab80-2b71-11e7-89db-18ab9b3bdfd3.png)

config
```json
 {
    capabilities: [
      {
        browserName: 'phantomjs',
        'phantomjs.binary.path': `${process.cwd()}/node_modules/phantomjs-prebuilt/bin/phantomjs`
      }
    ],
    exclude: [],
    {...obj}
    maxInstances: 2,
    sync: true,
    logLevel: 'error',
    coloredLogs: true,
    waitforTimeout: 20000,
    connectionRetryTimeout: 50000,
    connectionRetryCount: 3,
    screenshotPath: './errorShots/',
    screenshotOnReject: true,
    framework: 'mocha',
    reporters: [costomReport],
    reporterOptions: {
      outputDir: './',
      combined: true
    },
    mochaOpts: {
      ui: 'bdd',
      timeout: 30000,

    }
  }
```

 test code
```js
await browser.waitUntil(() => {
      let url = browser.getUrl();
      return url.indexOf('test.test.com') === 0;
    });
```

the results do not have the scrrenshot

```json
"tests": [
        {
          "title": "\"before all\" hook",
          "start": "2017-04-27T09:25:18.053Z",
          "duration": 617,
          "state": "fail",
          "fail": true,
          "err": {
            "message": "Promise was rejected with the following reason: timeout",
            "stack": ".............",
            "type": "WaitUntilTimeoutError",
            "name": "WaitUntilTimeoutError"
          }
        }
      ]
```

is there something wrong with the codes？

## Environment

* WebdriverIO version: 4.6.2
* Node.js version:6.2.0

**Comment by jankcat** [comment] 2017-04-27 15:16
Can you upload some simple reproducible code?

**Comment by jankcat** [comment] 2017-04-27 15:23
Also, it seems that your error title identifies the error as coming from your 'before all' hook timing out. If I am not mistaken (and it is hard to tell without an example) it looks like there would be no screenshot to take, because none of your tests have even started running yet at this point.

**Comment by xiejunfeng** [comment] 2017-04-28 03:03
the demo link   https://github.com/xiejunfeng/kr-shield

thank you！

yes， i  have  a long operations in my before() mocha hook。the error message will not pass it on？so，how can i get the screenshot from the final message。

**Comment by jankcat** [comment] 2017-04-28 16:01
If your before mocha hook is taking longer than the [30 seconds](https://github.com/xiejunfeng/kr-shield/blob/d688bbe6b688073db2fdc3234ff36467d85a1c2f/test/config.base.js#L36) you have it set to timeout on, mocha wont even get to the point where it has started the test cases... Try setting the before hook's timeout to be longer, or try debugging the long functions in the before hook to figure out why it is either hanging or taking so long.

**Comment by xiejunfeng** [comment] 2017-05-02 02:30
I hanging the program on purpose，i got the screenshot pictures, but i can not get the screenshot message from the final message.  and I found that there may be some mistakes。

![image](https://cloud.githubusercontent.com/assets/6460243/25601896/fe5e099c-2f21-11e7-8279-88f72edfda47.png)

that will be console ‘1111111’ before ‘22222222’；is that normal???

**Comment by christian-bromann** [comment] 2018-04-13 11:57
We will update the way how we take automatic screenshots in v5. Closing this.

**Closed by christian-bromann** 2018-04-13 11:57 UTC
