### ISSUE TITLE
Error `Cannot destructure property `browserName` of 'undefined' or 'null'`  when running in watch mode -- webdriverio 5.15.1

### ISSUE THREAD

**Issue by jcollum-autodesk** [webdriverio/webdriverio#4649] opened 2019-10-17 22:02 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.15.1
 - **Mode:** CLI
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12
 - **NPM version:** 6
 - **Browser name and version:** Chrome 77
 - **Platform name and version:** OSX 10.14.6
 - **Additional wdio packages used (if applicable):**
        "@wdio/allure-reporter": "^5.14.5",
        "@wdio/cli": "^5.15.1",
        "@wdio/junit-reporter": "^5.15.1",
        "@wdio/local-runner": "^5.15.1",
        "@wdio/mocha-framework": "^5.15.1",
        "@wdio/runner": "^5.15.1",
        "@wdio/sauce-service": "^5.14.0",
        "@wdio/spec-reporter": "^5.15.1",
        "@wdio/sync": "^5.15.1",

**Config of WebdriverIO**

capabilities section: 
 [{"browserName":"chrome","goog:chromeOptions":{"args":["headless","disable-gpu","window-size=1280,800"]}}]

**Describe the bug**
When I am running in watch mode and the first test run is complete and I save a file, kicking off a second test run, I get: 

```
[0-0] RUNNING in chrome - /specs/desktop/flows/collection.spec.js
[0-0] (node:75385) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `browserName` of 'undefined' or 'null'.
    at AllureReporter.setCaseParameters (/Users/collumj/Documents/work/ibleclient/e2e-test/node_modules/@wdio/allure-reporter/build/index.js:115:13)
    at AllureReporter.onTestStart (/Users/collumj/Documents/work/ibleclient/e2e-test/node_modules/@wdio/allure-reporter/build/index.js:108:10)
    at AllureReporter.<anonymous> (/Users/collumj/Documents/work/ibleclient/e2e-test/node_modules/@wdio/reporter/build/index.js:94:12)
    at AllureReporter.emit (events.js:203:13)
    at AllureReporter.EventEmitter.emit (domain.js:471:20)
    at /Users/collumj/Documents/work/ibleclient/e2e-test/node_modules/@wdio/runner/build/reporter.js:38:49
    at Array.forEach (<anonymous>)
    at BaseReporter.emit (/Users/collumj/Documents/work/ibleclient/e2e-test/node_modules/@wdio/runner/build/reporter.js:38:20)
    at MochaAdapter.emit (/Users/collumj/Documents/work/ibleclient/e2e-test/node_modules/@wdio/mocha-framework/build/index.js:222:19)
    at Runner.emit (events.js:203:13)
[0-0] (node:75385) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:75385) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**To Reproduce**
Run any single spec in watch mode

**Expected behavior**
2nd test runs run successfully in watch mode.

**Comment by mgrybyk** [comment] 2019-10-17 23:28
Can you try running without allure reporter in watch mode?

**Comment by jcollum-autodesk** [comment] 2019-10-18 00:15
That did it, nice job! 

`config.reporters = ['spec'];` before I export the config, all set.

**Comment by mgrybyk** [comment] 2019-10-18 10:02
removed allure reporter label as far as the problem is in attach to session functionality

**Comment by mgrybyk** [comment] 2019-10-18 12:35
gonna be fixed with the PR

**Closed by mgrybyk** 2019-10-18 12:35 UTC
Labels: Bug🐛
