### ISSUE TITLE
Unable to switch frame if screen has multiple frames :: TypeError: elem[prop] is not a function

### ISSUE THREAD

**Issue by hmmm-alt** [webdriverio/webdriverio#9766] opened 2023-02-14 14:10 UTC
### Discussed in https://github.com/webdriverio/webdriverio/discussions/9762

<div type='discussions-op-text'>

<sup>Originally posted by **hmmm-alt** February 13, 2023</sup>
I am stuck with this for last 2 days, I have tried many diff ways but it just does not work. 

e,.g : 
```
<iframe id="frame1">
    <html>
    <iframe id="frame2"></iframe>
    </html>
</iframe>
```
to handle above I have written below code

```
async function handleFrames(){
    await browser.$("frame1").waitForExist({timeout: 100000}).then(async function(present){
        if (present) {
            await browser.switchToFrame(null);
            await browser.pause(1000);
            await browser.switchToFrame($("#frame1"));
            await browser.switchToFrame($("frame2"));
        }
    })
}
```
The err I am getting::

```
TypeError: elem[prop] is not a function
```

As far as I know above err means it is returning arrays, So I have written below code::

```
async function handleFrames(){
    await browser.switchToFrame(null);
    await browser.$$("iframe").forEach(async function (ele) {
        await ele.getHTML().then(async function (outerHTML) {
            await browser.pause(500);
            if (outerHTML.includes("iframe1")) {
                console.log("Frame1 found!!!!!");
                await browser.switchToFrame(ele);
            }
        });
    });
    await browser.switchToFrame(browser.$("#frame2"));
}
```

Still did not have any luck!!! :(
Any solution to this would be highly appreciated. Thanks

wdio : v8
node: 16.17.1</div>

**Comment by hmmm-alt** [comment] 2023-02-14 14:11
I have tested in more screen in our application, looks like it is a defect.

**Comment by christian-bromann** [comment] 2023-02-14 17:34
Thanks for reporting!



Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by christian-bromann** [comment] 2023-02-14 19:53
Actually this is a duplicate of #9762, happy to re-open when we can figure out where the problem comes from.

**Closed by christian-bromann** 2023-02-14 19:53 UTC
Labels: Bug 🐛, help wanted
