### ISSUE TITLE
Unrecognised test for suite Error

### ISSUE THREAD

**Issue by amadofelipe** [webdriverio/webdriverio#1250] opened 2016-04-14 21:43 UTC
## The problem

Randomly getting the following error:

```
/var/lib/jenkins/workspace/delivery-direto/node_modules/webdriverio/build/lib/utils/ReporterStats.js:262
            if (!suiteStats.tests[title]) throw Error('Unrecognised test [' + title + '] for suite [' + runner.parent + ']');
                                          ^

Error: Unrecognised test [should not show vouchers on admin_menu] for suite [when administrator tries to cancel a module]
    at Error (native)
    at ReporterStats.getTestStats (/var/lib/jenkins/workspace/delivery-direto/node_modules/webdriverio/build/lib/utils/ReporterStats.js:262:49)
    at ReporterStats.output (/var/lib/jenkins/workspace/delivery-direto/node_modules/webdriverio/build/lib/utils/ReporterStats.js:270:22)
    at BaseReporter.<anonymous> (/var/lib/jenkins/workspace/delivery-direto/node_modules/webdriverio/build/lib/utils/BaseReporter.js:102:25)
    at emitOne (events.js:90:13)
    at BaseReporter.emit (events.js:182:7)
    at BaseReporter.handleEvent (/var/lib/jenkins/workspace/delivery-direto/node_modules/webdriverio/build/lib/utils/BaseReporter.js:278:27)
    at Launcher.messageHandler (/var/lib/jenkins/workspace/delivery-direto/node_modules/webdriverio/build/lib/launcher.js:469:28)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
```

## Environment

* WebdriverIO version: 4.0.5
* Node.js version: 5.10.1
* wdio testrunner
* if wdio testrunner, running synchronous or asnychronous tests: synchronous
* Additional wdio packages used (if applicable): mocha, webdriverajax, chai, chai-as-promised, chromedriver version 2.21.371461, Google Chrome 49.0.2623.112

## Details
It does not happen everytime, but when it does it does not generate the test report. So, the time spent running all the tests (more than 40 minutes) is wasted, which is pretty annoying. I appreciate any help on this issue.

## Link to Selenium/WebdriverIO logs
https://gist.github.com/amadofelipe/0a6c8aa89a1e511e779683aca9c800a2

**Comment by christian-bromann** [comment] 2016-04-15 12:14
Duplicate of #1195. This issue is fixed but not yet released.

**Closed by christian-bromann** 2016-04-15 12:14 UTC

**Comment by amadofelipe** [comment] 2016-04-15 14:04
@christian-bromann I manually included your fix on my ReporterStats.js (https://github.com/webdriverio/webdriverio/commit/7eca40670a2881f954e128fdf87ea760c027476d#diff-2305aa79aa2aa89aafbe4d87e936ff28R196) but the issue persists. Note that the error is not "Unrecognised test", but "Unrecognised suite". Thanks.
