### ISSUE TITLE
[🐛 Bug]: browsr.mock() is not working when selenium-standalone service is used for chrome

### ISSUE THREAD

**Issue by kulkarni18192** [webdriverio/webdriverio#10078] opened 2023-03-28 08:01 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.6.3

### Node.js Version

19.8.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
        maxInstances : 1,
        browserName : 'chrome',
        'goog:chromeOptions' : {
            args:[
                // '--headless',
                // `--lang=${language}`,
                '--use-fake-device-for-media-stream',
                '--use-fake-ui-for-media-stream'
            ],
            prefs: {
                'intl.accept_languages': language
            }
        }
    }
```

### What happened?

I am running my wdio tests where I am capturing the network logs using **browser.mock()** . I am using the service as below in the wdio.conf.js 
**services: ['selenium-standalone']**

When I launch the tests using chrome I get below issue:
ErrorEvent {
  [Symbol(kTarget)]: WebSocket {
    _events: [Object: null prototype] { open: [Function], error: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: <Buffer >,
    _closeTimer: null,
    _extensions: {},
    _paused: false,
    _protocol: '',
    _readyState: 3,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'ws://192.168.1.5:4444/session/a6b0f81f943ae3d5dec2089bea72dc7d/se/cdp',
    _originalIpc: false,
    _originalSecure: false,
    _originalHostOrSocketPath: '192.168.1.5:4444',
    _req: null,
    [Symbol(kCapture)]: false
  },
  [Symbol(kType)]: 'error',
  [Symbol(kError)]: Error: socket hang up
      at connResetException (node:internal/errors:717:14)
      at Socket.socketOnEnd (node:_http_client:519:23)
      at Socket.emit (node:events:524:35)
      at Socket.emit (node:domain:489:12)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'ECONNRESET'
  },
  [Symbol(kMessage)]: 'socket hang up'
}

### What is your expected behavior?

The test should run without any error 

### How to reproduce the bug.

let networkLog = await browser.mock('**/mobile', {method: 'post', statusCode:201});
//clicked on a button to get the requests
await browser.waitUntil(async () => networkLog.calls[0] !== undefined);

### Relevant log output

```typescript
ErrorEvent {
  [Symbol(kTarget)]: WebSocket {
    _events: [Object: null prototype] { open: [Function], error: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: <Buffer >,
    _closeTimer: null,
    _extensions: {},
    _paused: false,
    _protocol: '',
    _readyState: 3,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'ws://192.168.1.5:4444/session/a6b0f81f943ae3d5dec2089bea72dc7d/se/cdp',
    _originalIpc: false,
    _originalSecure: false,
    _originalHostOrSocketPath: '192.168.1.5:4444',
    _req: null,
    [Symbol(kCapture)]: false
  },
  [Symbol(kType)]: 'error',
  [Symbol(kError)]: Error: socket hang up
      at connResetException (node:internal/errors:717:14)
      at Socket.socketOnEnd (node:_http_client:519:23)
      at Socket.emit (node:events:524:35)
      at Socket.emit (node:domain:489:12)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'ECONNRESET'
  },
  [Symbol(kMessage)]: 'socket hang up'
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2023-03-30 04:02
duplicate of #10079

**Closed by christian-bromann** 2023-03-30 04:02 UTC
Labels: Bug 🐛, Needs Triaging ⏳
