### ISSUE TITLE
[🐛 Bug]:  Failed loading configuration file … host.fileExists is not a function

### ISSUE THREAD

**Issue by LordRembo** [webdriverio/webdriverio#9102] opened 2022-10-28 12:04 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.25.2

### Node.js Version

14.17.4 (npm version 8.19.2)

### Mode

WDIO Testrunner

### What happened?

I used the wizard to generate a test setup and example test in a folder `e2e-wdio`, inside my project. My main package.json and node modules are in my project root.
In the wizard, I enabled Typescript and set Cucumber for framework, with connection with BrowserStack.
When I run the test command: `npm run wdio`, it doesn't want to load my config file, I just get an error (see log output)

I can open the file in that path (eg. using `nano`), so the file exists.
If I manually convert the Typescript to JS, then the config is found and executed. But the documentation seems to suggest you can execute test commands using a config and tests written in Typescript.

### What is your expected behavior?

Running the test command would find and load the Typescript config file

### How to reproduce the bug.

Initiate a test setup using `npm init wdio ./e2e-wdio`, inside a local folder

### Relevant log output

```typescript
2022-10-28T11:45:45.018Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: /Users/rembranddropsolid/.dropsolid_launchpad/projects/platformfrontend/e2e-wdio/wdio.conf.ts: host.fileExists is not a function
wdio run <configPath>

Run your WDIO configuration file to initialize your tests. (default)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2022-10-28 15:19
Can you provide the stack trace?

**Comment by LordRembo** [comment] 2022-10-28 17:09
I finally figured out what the issue was, though it wasn't clear to me from the stack trace. Turns out the version of `ts-node` was too old (was v2.0.x for some reason). I now have v 10.9.1 (latest) and for Typescript it's 4.8.4

Added the stacktrace, in case someone else is helped with it:
```
TypeError: host.fileExists is not a function
    at Object.fileExists (/Users/rembranddropsolid/.dropsolid_launchpad/projects/platformfrontend/node_modules/typescript/lib/typescript.js:167620:63)
    at Object.host.fileExists (/Users/rembranddropsolid/.dropsolid_launchpad/projects/platformfrontend/node_modules/typescript/lib/typescript.js:117500:47)
    at getPackageJsonInfo (/Users/rembranddropsolid/.dropsolid_launchpad/projects/platformfrontend/node_modules/typescript/lib/typescript.js:44461:37)
    at loadModuleFromSpecificNodeModulesDirectory (/Users/rembranddropsolid/.dropsolid_launchpad/projects/platformfrontend/node_modules/typescript/lib/typescript.js:45001:27)
    at loadModuleFromImmediateNodeModulesDirectory (/Users/rembranddropsolid/.dropsolid_launchpad/projects/platformfrontend/node_modules/typescript/lib/typescript.js:44982:58)
    at /Users/rembranddropsolid/.dropsolid_launchpad/projects/platformfrontend/node_modules/typescript/lib/typescript.js:44972:39
    at Object.forEachAncestorDirectory (/Users/rembranddropsolid/.dropsolid_launchpad/projects/platformfrontend/node_modules/typescript/lib/typescript.js:8370:26)
    at loadModuleFromNearestNodeModulesDirectoryWorker (/Users/rembranddropsolid/.dropsolid_launchpad/projects/platformfrontend/node_modules/typescript/lib/typescript.js:44966:19)
    at loadModuleFromNearestNodeModulesDirectory (/Users/rembranddropsolid/.dropsolid_launchpad/projects/platformfrontend/node_modules/typescript/lib/typescript.js:44958:16)
    at tryResolve (/Users/rembranddropsolid/.dropsolid_launchpad/projects/platformfrontend/node_modules/typescript/lib/typescript.js:44053:34)
```

**Comment by LordRembo** [comment] 2022-10-28 17:49
for more reference, this is what is in the config json.
The `import` triggers an error, so I'm guessing it's a syntax thing? If I remove it, it just errors on something else (Unexpected token ':'). I've run the file through various validators and I'm not finding any issues. So I'm a bit stumped.

```
import type { Options } from '@wdio/types'
let config: Options.Testrunner = {

  autoCompileOpts: {
    autoCompile: true,
    tsNodeOpts: {
      transpileOnly: true,
      project: 'tsconfig.json'
    }
  },
  hostname: 'hub.browserstack.com',
  user: process.env.BROWSERSTACK_USERNAME,
  key: process.env.BROWSERSTACK_ACCESS_KEY,

  specs: [
    './e2e-wdio/features/**/*.feature'
  ],
  exclude: [
  ],
  maxInstances: 10,
  capabilities: [
    {
      'bstack:options': {
        'os': 'Windows',
        'osVersion': '10'
      },
      'browserName' : 'Chrome',
      'browserVersion' : '103'
    }
  ],
  commonCapabilities: {
    'bstack:options': {
      'projectName' : 'Dropsolid Platform',
      'buildName': 'build-webdriverIO-browserstack',
      'resolution' : '1280x800',
      'debug': 'true'
    }
  },
  'acceptInsecureCerts': 'true',
  logLevel: 'info',
  coloredLogs: true,
  bail: 0,
  baseUrl: 'https://my_redacted_url.com/',
  waitforTimeout: 10000,
  connectionRetryTimeout: 120000,
  connectionRetryCount: 3,
  services: [
    [
      'browserstack',
      { browserstackLocal: true, opts: { forcelocal: false } },
    ],
  ],
  framework: 'cucumber',
  reporters: ['spec','cucumberjs-json'],
  cucumberOpts: {
    require: ['./features/step-definitions/steps.ts'],
    backtrace: false,
    requireModule: [],
    dryRun: false,
    failFast: false,
    snippets: true,
    source: true,
    strict: false,
    tagExpression: '',
    timeout: 60000,
    ignoreUndefinedDefinitions: false
  }
}

config.capabilities.forEach(function(caps: any) {
  for (var i in config.commonCapabilities)
    caps[i] = { ...caps[i], ...config.commonCapabilities[i] };
});

export { config };

```

**Comment by christian-bromann** [comment] 2022-10-28 18:53
I just tried what you said and created a new project using `npm init wdio ./e2e-test`. I picked TypeScript as compiler and use default values for the rest. I had no issues running the tests.

**Comment by LordRembo** [comment] 2022-10-28 21:38
This so bizarre. Guess I'll just have to start from scratch in a new project and start moving things over until it breaks.

**Comment by LordRembo** [comment] 2022-10-28 22:34
Thanks for looking along, really appreciate it. I got it working in a blank project, so it must be another node module or (config) setting interfering. Will take another crack at it next week.
A sidenote about the wizard though: even out of the box, the test install didn't really work. Had to do some manual tweaking, like the path to the wdio.conf.ts wasn't correct. It is nested in a 'test' folder but the npm command points 1 level up, and it was calling a .js file instead of .ts. Fixing that manually did get the setup to work.

**Comment by christian-bromann** [comment] 2022-10-29 00:01
> Fixing that manually did get the setup to work.

Ha! That is weird. Did you set it up in an existing project or in an empty one?

**Comment by LordRembo** [comment] 2022-10-29 15:16
The last attempt was in an empty folder, that's where those issues happened. But it was obvious enough to catch ànd has the added bonus that it forces you to pay attention when first trying out the setup :D

**Comment by christian-bromann** [comment] 2022-10-30 17:35
@LordRembo can you describe a way how to reliable reproduce this?

**Comment by christian-bromann** [comment] 2022-11-07 05:47
@LordRembo is there a chance you can provide a minimal reproducible example?

**Comment by LordRembo** [comment] 2022-11-07 19:27
@christian-bromann Yeah, I had the same result on node 14.17.4 and node 16.17.1

**Comment by christian-bromann** [comment] 2022-11-18 05:54
Sorry but after trying the same answers as you posted above and downloading and checking your reproducible example I was not getting the same issue. I am not sure how I can help at this point. I will close the issue given that there is nothing actionable here due to a missing reproducible example. I am happy to re-open if the bug can be reproduced in some shape of form.

**Closed by christian-bromann** 2022-11-18 05:54 UTC
Labels: Bug 🐛, Reproducible Example Missing
