### ISSUE TITLE
[🐛 Bug]: Unable to perform actions like doubleClick(), moveTo(), closeWindow() through webdriver io

### ISSUE THREAD

**Issue by Bjb20** [webdriverio/webdriverio#13935] opened 2024-11-29 04:44 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.40, 9.14

### Node.js Version

21.7, 18.12

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{ 
browserName: ‘chrome’,
acceptInsecureCerts:true,
}
```

### What happened?

Hi, i am running webdriver io typescript test automation scripts in remote browser session hosted in selenium grid version 4.25.0. Here i am getting errors in calling some inbuild webdriverio actions like doubleClick(), moveTo(), closeWindow(). It was working fine till grid version 4.23. Now its giving error as unknown and in the debugger logs its giving error in the releaseActions() as request failed due to missing body. But in local browser its working fine. Also i tried the same with latest webdriver io version 9.2.14 , there also getting same error.

### How to reproduce the bug.

Eg of code is await element.doubleClick() or await element.moveTo()

### Relevant log output

```typescript
INFO webdriver: COMMAND performActions (<object>)
INFO webdriver: [POST] https://selenium-hub:4444/selenium/session/b15ae585ffa48420978647e279eb8b8c/actions
INFO webdriver: DATA {
actions: [
{
id: 'action',
type: 'pointer',
parameters: [object],
actions: [Array]
}
]
}
1
INFO webdriver: RESULT null
INFO webdriver: COMMAND releaseActions()
INFO webdriver: [DELETE] https://selenium-
hub: 4444/selenium/session/b15ae585ffa48420978647e279eb8b8c/actions
DEBUG webdriver: request failed due to missing body
INFO webdriver: Retrying 1/1
INFO webdriver: [DELETE] https://selenium-
hub: 4444/selenium/session/b15ae585ffa48420978647e279eb8b8c/actions
WARN webdriver: Request failed with status 404 due to unknown error
DEBUG webdriver: request failed due to missing body
ERROR webdriver: Request failed with status 404 due to Not Found: unknown еггог
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by Bjb20** [comment] 2024-11-29 06:51
Below is the error with webdriver io version 9.4.1

INFO webdriver: COMMAND performActions(<object>)
INFO webdriver: [POST] https://selenium-
hub: 4444/selenium/session/1a4c971728964a359b4effd7358c3b4c/actions
INFO webdriver: DATA {
actions: [
id: 'action3',
type: 'pointer',
parameters: [object],
actions: [Array]
e
}
INFO webdriver: RESULT null
INFO webdriver: COMMAND releaseActions()
INFO webdriver: [DELETE] https://selenium-
hub: 4444/selenium/session/1a4c971728964a359b4effd7358c3b4c/actions
DEBUG webdriver: request failed due to missing body
ERROR webdriver: WebDriverError: Not Found when running "actions" with method "DELETE"

**Comment by christian-bromann** [comment] 2024-12-02 12:34
> It was working fine till grid version 4.23. Now its giving error as unknown and in the debugger logs its giving error in the releaseActions() as request failed due to missing body.

This seems like an issue with the Selenium grid. Can you provide a minimal reproducible example?

**Comment by Bjb20** [comment] 2024-12-02 14:55
Hi, i am not able to provide you the exact reproducible example, but a basic example is below like when we navigate to an url and we need to mouse over on an element then we have 2 methods . 1) conventional method when we use action class 2)in webdriver io we have element.moveTo()

exact code snippet is like 

await browser.url(any url)
await element.waitForDisplayed()
await element.moveTo()

in this moveTo() mouse is moving to that element and getting the tooltip element but release action is not happening as u can see in the earlier provided logs. And same issue is there in other methods like element.doubleClick(), in window handles while closing the child window.

**Comment by christian-bromann** [comment] 2024-12-02 20:54
Given the error, there is not really much we can to start investigate this. We would have to close the issue if there isn't anything we can help with.

**Comment by christian-bromann** [comment] 2024-12-25 20:05
Closing due to inactivity.

**Closed by christian-bromann** 2024-12-25 20:05 UTC
Labels: Bug 🐛, Reproducible Example Missing
