### ISSUE TITLE
bug: Selenium-Standalone service always assumes capabilities are not configured for the cloud

### ISSUE THREAD

**Issue by tehhowch** [webdriverio/webdriverio#6093] opened 2020-11-12 00:14 UTC
Ref: https://github.com/webdriverio/webdriverio/blob/f9d27c6aabaf5d80771f848c37b175c763db5f8a/packages/wdio-selenium-standalone-service/src/launcher.ts#L55

I think this line should read

```ts
).forEach((cap) => !isCloudCapability(cap) && Object.assign(cap, DEFAULT_CONNECTION, { ...cap }))
```
i.e., no `.capabilities` property access, as `cap` is already guaranteed to be of the type `Webdriver.Capabilities` we want to inspect (view the type inference for `cap` in the forEach initializer).

If i insert a log and print out the value of `this.capabilities[0]` in my test runner, i receive an object like this:

```js
First capability {
  browserName: 'chrome',
  browserVersion: '86',
  'goog:chromeOptions': {
    args: [
      '--disable-extensions',
      '--no-sandbox',
      '--window-size=1920,1080'
    ]
  },
  specs: [
    '/Users/me/apps/myrepo/packages/myApp/webclient-tests/tests/TC-1.spec.js'
  ],
  platformName: 'Windows 10',
  maxInstances: 5,
  'sauce:options': {
    maxDuration: 1440,
    idleTimeout: 90,
    name: 'chrome-win10',
    build: 'default',
    appiumVersion: '',
    seleniumVersion: '',
    tunnelIdentifier: 'me-laptop',
    screenResolution: '1920x1080'
  }
}
```

<details><summary> based on this input wdio.conf.js file </summary>

```js
const defaultConfig = {
  runner: 'local',
  path: '/wd/hub',
  services: [
    'intercept',
    [
      'selenium-standalone',
      {
        logPath: 'logs',
        installArgs: {
          drivers: {
            chrome: {
              version: '86.0.4240.22',
            },
          },
        },
        args: {
          drivers: {
            chrome: {
              version: '86.0.4240.22',
            },
          },
        },
      },
    ],
    [
      'sauce',
      {
        sauceConnect: true,
        sauceConnectOpts: {
          tunnelIdentifier: 'me-laptop',
          'se-port': '4444',
        },
      },
    ],
  ],
  region: 'us',
  specs: [],
  exclude: [],
  maxInstances: 5,
  maxInstancesPerCapability: 10,
  capabilities: [
    {
      browserName: 'chrome',
      browserVersion: '86',
      'goog:chromeOptions': {
        args: [
          '--disable-extensions',
          '--no-sandbox',
          '--window-size=1920,1080',
        ],
      },
      specs: [
        '/Users/me/apps/myrepo/packages/myApp/webclient-tests/tests/TC-1.spec.js',
      ],
      platformName: 'Windows 10',
      maxInstances: 5,
      'sauce:options': {
        maxDuration: 1440,
        idleTimeout: 90,
        name: 'chrome-win10',
        build: 'default',
        appiumVersion: '',
        seleniumVersion: '',
        tunnelIdentifier: 'me-laptop',
        screenResolution: '1920x1080',
      },
    },
  ],
  execArgv: [],
  logLevel: 'info',
  logLevels: {
    webdriver: 'info',
    '@wdio/applitools-service': 'info',
  },
  bail: 0,
  waitforTimeout: 150000,
  filesToWatch: [],
  framework: 'mocha',
  specFileRetries: 0,
  reporters: [
    'spec',
    'junit',
  ],
  mochaOpts: {
    ui: 'bdd',
    compilers: [
      'js:@babel/register',
    ],
    timeout: 99999999,
  },
  sauceConnectOpts: {
    tunnelIdentifier: 'me-laptop',
  },
  version: 6,
  baseUrl: 'http://localdev.company.com:4201',
  outputDir: '/Users/me/apps/myrepo/packages/myApp/webclient-tests/reports',
  user: 'my-sauce-username',
  key: 'my-sauce-key',
};

exports.config = defaultConfig;
```

</details>

The result is that running the `wdio` command with the configuration results in a fatal error:
```
[0-0]  Error:  Failed to create session.
session not created: No matching capabilities found
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'mylaptophost', ip: 'my.lap.top.ip', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '1.8.0_265'
Driver info: driver.version: unknown
remote stacktrace: 0   86.0.4240.22-x64-chromedriver       0x000000010cdbec29 86.0.4240.22-x64-chromedriver + 2464809
1   86.0.4240.22-x64-chromedriver       0x000000010d3f96f3 86.0.4240.22-x64-chromedriver + 8996595
2   86.0.4240.22-x64-chromedriver       0x000000010cc03d56 86.0.4240.22-x64-chromedriver + 650582
3   86.0.4240.22-x64-chromedriver       0x000000010cba8733 86.0.4240.22-x64-chromedriver + 276275
4   86.0.4240.22-x64-chromedriver       0x000000010cba7d78 86.0.4240.22-x64-chromedriver + 273784
5   86.0.4240.22-x64-chromedriver       0x000000010cba919d 86.0.4240.22-x64-chromedriver + 278941
6   86.0.4240.22-x64-chromedriver       0x000000010cba63f3 86.0.4240.22-x64-chromedriver + 267251
7   86.0.4240.22-x64-chromedriver       0x000000010cb80230 86.0.4240.22-x64-chromedriver + 111152
8   86.0.4240.22-x64-chromedriver       0x000000010cb811a7 86.0.4240.22-x64-chromedriver + 115111
9   86.0.4240.22-x64-chromedriver       0x000000010cd91830 86.0.4240.22-x64-chromedriver + 2279472
10  86.0.4240.22-x64-chromedriver       0x000000010cd9c83a 86.0.4240.22-x64-chromedriver + 2324538
11  86.0.4240.22-x64-chromedriver       0x000000010cd9c4a7 86.0.4240.22-x64-chromedriver + 2323623
12  86.0.4240.22-x64-chromedriver       0x000000010cd78945 86.0.4240.22-x64-chromedriver + 2177349
13  86.0.4240.22-x64-chromedriver       0x000000010cd9cd41 86.0.4240.22-x64-chromedriver + 2325825
14  86.0.4240.22-x64-chromedriver       0x000000010cd86bda 86.0.4240.22-x64-chromedriver + 2235354
15  86.0.4240.22-x64-chromedriver       0x000000010cdb1c4a 86.0.4240.22-x64-chromedriver + 2411594
16  86.0.4240.22-x64-chromedriver       0x000000010cdc3987 86.0.4240.22-x64-chromedriver + 2484615
17  libsystem_pthread.dylib             0x00007fff6d98d109 _pthread_start + 148
18  libsystem_pthread.dylib             0x00007fff6d988b8b thread_start + 15
```

**Comment by christian-bromann** [comment] 2020-11-12 09:14
Can you elaborate your use case? Are you trying to run some tests locally and some other in the cloud? What is the situation you are experiencing and what are you expecting?

**Comment by tehhowch** [comment] 2020-11-12 13:26
Without the change, I am unable to run any tests that execute on SauceLabs VMs. The selenium-standalone server starts up, but when the webdriver package attempts to start a session, an error is thrown. (Any `beforeSession` hooks execute, then an error is printed.)

The error is thrown from here:


The error text I can provide in a few hours when I return to my work machine

**Comment by christian-bromann** [comment] 2020-11-12 13:29
Why do you have a selenium-standalone server service set if you run tests on Sauce Labs?

**Comment by tehhowch** [comment] 2020-11-12 13:42
I edited the above post with the line that throws the error

> Why do you have a selenium-standalone server service set if you run tests on Sauce Labs?

What would you expect to see instead, in the configuration file?

We start tests locally (on e.g. macOS), and they are executed inside VMs hosted by SauceLabs. We also may execute the same tests locally. This configuration works for WDIOv4 and WDIOv5. We are attempting to migrate to v6, but have encountered this bug in `@wdio/selenium-standalone-service`. Running tests that execute locally works; running tests that execute remotely does not.

**Comment by christian-bromann** [comment] 2020-11-12 14:47
@tehhowch in v6 the service modify the connection information automatically so that you don't need to do that. So if you have a selenium standalone service set in your wdio.conf.js it will make all browser run on their if you not say differently. We recommend to have a config file for running tests on Sauce vs locally, e.g. like in this boilerplate: https://github.com/webdriverio/jasmine-boilerplate

If you don't mind I would close this as this seems to be an expected behavior.

**Comment by tehhowch** [comment] 2020-11-12 17:13
(I updated the above message with the value of `params` in `await sessionRequest.makeRequest(params);`, and added the error text that is encountered with the current code.)

> If you don't mind I would close this as this seems to be an expected behavior.

I don't agree that this is expected. The tests for the `onPrepare` hook don't seem correct (they pass a `Record<string, Webdriver.Capabilities & Webdriver.Options>` object, rather than a `Record<string, Webdriver.Capabilities>` or `Webdriver.Capabilities[]`, to the `SeleniumStandaloneLauncher` constructor:

https://github.com/webdriverio/webdriverio/blob/f9d27c6aabaf5d80771f848c37b175c763db5f8a/packages/wdio-selenium-standalone-service/tests/launcher.test.ts#L69-L73

https://github.com/webdriverio/webdriverio/blob/f9d27c6aabaf5d80771f848c37b175c763db5f8a/packages/wdio-selenium-standalone-service/src/launcher.ts#L30

I don't see `port` listed as valid property on the Webdriver.Capabilities interface, which is probably why Webdrier.Options was mixed in, but this seems incorrect. These tests were added in #5960 , and I'm not familiar with multiremote configuration, so I don't feel comfortable changing these tests myself. Perhaps @hieuxlu can comment?

There are no tests for the selenium-standalone-service `onPrepare` hook that cover the configuration we use (which is the prescribed configuration presented on https://webdriver.io/docs/configurationfile.html for capabilities), where we pass `capabilities` as an array of browser-specific capabilities. I suspect that adding such a test, or updating the test inputs, would expose this issue, where the `onPrepare` hook incorrectly overrides a browser capability that has any cloud configuration set.

If I remove the `.capabilities` property access from the line mentioned in the OP, then the params used in `await sessionRequest.makeRequest(params);` are
```js
{
  protocol: 'https',
  hostname: 'ondemand.us-west-1.saucelabs.com',
  port: 443,
  path: '/wd/hub',
  capabilities: {
    browserName: 'chrome',
    browserVersion: '86',
    'goog:chromeOptions': { args: [Array] },
    platformName: 'Windows 10',
    'sauce:options': {
      maxDuration: 1440,
      idleTimeout: 90,
      name: 'chrome-win10',
      build: 'default',
      appiumVersion: '',
      seleniumVersion: '',
      tunnelIdentifier: 'me-laptop',
      screenResolution: '1920x1080'
    }
  },
  logLevel: 'info',
  connectionRetryTimeout: 120000,
  connectionRetryCount: 3,
  user: 'my-sauce-user',
  key: 'my-sauce-key',
  logLevels: { webdriver: 'info', '@wdio/applitools-service': 'info' },
  transformRequest: [Function: default],
  transformResponse: [Function: default]
}
```
and my tests execute on saucelabs successfully with the wdio.conf.js file in the OP.

**Comment by christian-bromann** [comment] 2020-11-12 17:24
> I don't see `port` listed as valid property on the Webdriver.Capabilities interface, which is probably why Webdrier.Options was mixed in, but this seems incorrect

It is possible to have `hostname`, `port` and `path` in the capabilities to overwrite connection details for specific capabilities. This is not very good documented on the project side.

Again, I don't understand why you use the selenium standalone service if you run tests on Sauce. Can you elaborate?

**Comment by hieuxlu** [comment] 2020-11-12 17:50
> I don't see `port` listed as valid property on the Webdriver.Capabilities interface, which is probably why Webdrier.Options was mixed in, but this seems incorrect. These tests were added in #5960 , and I'm not familiar with multiremote configuration, so I don't feel comfortable changing these tests myself. Perhaps @hieuxlu can comment?

Multiremote has `capabilities` as object as opposed to array in normal configs. Each property in object is matched to a browser instance in global object. 
https://webdriver.io/docs/multiremote.html

These tests was to make sure multiremote capabilities are not overriden with default when any cloud capabilities are detected. This fixed the bug when mixing `selenium-standalone-service` and `browser-stack-service`. 
https://github.com/webdriverio/webdriverio/blob/f9d27c6aabaf5d80771f848c37b175c763db5f8a/packages/wdio-selenium-standalone-service/tests/launcher.test.ts#L69-L73

**Comment by hieuxlu** [comment] 2020-11-12 18:08
@tehhowch I agree that the typing is not ideal. We've just recently migrated the code to Typescript, and the casting might be confusing. But your problem can not be resolved even with previous Javascript version, so we should focus on finding your usecase and fix the typing later.

IIUC, your problem is that `wdio-selenium-standalone-service` will override default `hostname`, `protocol`, and `port`, so a workaround is that you specifically set these properties so it will not be overriden by the service.

In hindsight, I think wdio currently only supports the following use cases
1. Single/multiple browsers with same remote (in this case only one of selenium-standalone-service or sauce-labs-service, not both or mixed). This accepts capabilities as an Array.
2. Single/multiple browsers with multiple remotes (multiremotes). This config is used for scenarios such as chat app, so you need multiple remotes, possible with mixed services (e.g. selenium-standalone mixed with browserstack) . Multiremote accepts capabilities as an Object.

So your usecase of mixing Saucelabs service with Selenium standalone service is not supported. I'd recommend having 2 separate configs for each of these services. So you could have 1 wdio.local.config and wdio.saucelabs.config

**Comment by tehhowch** [comment] 2020-11-12 18:18
> > I don't see `port` listed as valid property on the Webdriver.Capabilities interface, which is probably why Webdrier.Options was mixed in, but this seems incorrect
> 
> It is possible to have `hostname`, `port` and `path` in the capabilities to overwrite connection details for specific capabilities. This is not very good documented on the project side.
> 
> Again, I don't understand why you use the selenium standalone service if you run tests on Sauce. Can you elaborate?

I conferred with other team members, and we determined it (the inclusion of `selenium-standalone` in the `services` specification) is an artifact of how several somewhat-similar projects within the org share testrunner infrastructure. I'm updating our internal tooling to explicitly avoid mixing `sauce` and `selenium-standalone` services, which as you indicate, will prevent the particular issue I encountered. Note that this infrastructure worked in v4 and v5 without issue, because the selenium-standalone-service did not assign default properties until #5960 was merged.

I still consider it a bug that needs to be fixed, that the selenium-standalone-service fails to detect that there are specified cloud capabilities. Based on your comments the types are not correct for the SeleniumStandaloneLauncher `capabilities` field, and thus there are insufficient type casts in the block added in #5960:
https://github.com/webdriverio/webdriverio/blob/f9d27c6aabaf5d80771f848c37b175c763db5f8a/packages/wdio-selenium-standalone-service/src/launcher.ts#L47-L55

It seems this should perhaps be
```ts
/** 
 * update capability connection options to connect 
 * to standalone server 
 */
const capabilitySpecifications: Array<Webdriver.Capabilities & Webdriver.Options> = Array.isArray(this.capabilities) 
    ? this.capabilities 
    : Object.values(this.capabilities);
capabilitySpecifications
  .filter((cap) => {
    if (cap.hasOwnProperty('capabilities')) return !isCloudCapability(cap.capabilities); // multiremote options spec
    else return !isCloudCapability(cap); // regular capability spec
  })
  .forEach((nonCloudCapability) => Object.assign(nonCloudCapability, DEFAULT_CONNECTION, { ...nonCloudCapability }));
```
(this may not quite compile / be idiomatic TypeScript, but hopefully you get what I am suggesting)

**Comment by hieuxlu** [comment] 2020-11-12 18:24
@tehhowch I just want to correct that line was added 8 months ago in 644441470e0447d05eafd90d22a88b1547772a7e, which was indeed version `6.0.4`. My PR fixed the same default assignment bug, but for multiremote usecase

**Comment by hieuxlu** [comment] 2020-11-12 18:36
I kind of see why people want to mix services. It was a bit like multiremote, but instead of running 2 browsers at the same time, this configuration will result in specific browser running sequentially. So I assume that you could possibly change your capabilities config to an object and it will behave mostly the same, something like this:
```
capabilities: {
   browserStandalone: {
   // Selenium standalone capabilities
   },
   browserSauceLabs: {
   // SauceLabs W3C capabilities
   }
}
```
I think it's possible that multiremote better fits your usecase. 

@christian-bromann IMHO, the default assignment code is a bit dangerous as it will override every capabilities. I think it might be a good idea to further check cloud capabilities for normal cases (and correct typing a bit).

**Comment by hieuxlu** [comment] 2020-11-13 01:12
@christian-bromann I could confirm the typing for capabilities in selenium-standalone-service was wrong. I will create a PR to fix the typings and also extend `isCloudCapabilities` to support the above usecase.

**Comment by christian-bromann** [comment] 2020-11-13 08:44
@hieuxlu sounds good!

**Closed** 2020-11-15 17:59 UTC
