### ISSUE TITLE
[🐛 Bug]: WDIO v8 Calling Suite and Blank Spec Calls All Specs

### ISSUE THREAD

**Issue by awhisler** [webdriverio/webdriverio#10410] opened 2023-05-17 22:09 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

18

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [
    {
      browserName: 'chrome',
      'goog:chromeOptions': {
        args: [
          '--headless',
          '--disable-gpu',
        ],
        prefs: {
          directory_upgrade: true,
          prompt_for_download: false,
          'download.default_directory': DownloadDirectoryService.PATH,
        },
      },
      acceptInsecureCerts: true,
    },
  ],
```

### What happened?

One of the suites is being called:
```
'full-validation-absencetracker': [
      `${__dirname}/specs/apis/**/*.spec.js`,
      `${__dirname}/specs/at-admin/*.spec.js`,
      `${__dirname}/specs/configurations/**/*.spec.js`,
      `${__dirname}/specs/ess/**/*.spec.js`,
      `${__dirname}/specs/misc/**/*.spec.js`,
    ],
```

You can see that there is no folder "ess2" being defined in that suite, but when I run that suite, it runs all the specs in the ESS2 folder

Folders:
![image](https://github.com/webdriverio/webdriverio/assets/2396250/330d136f-9450-40a4-ad3e-20d1db9e7f25)

In order to give the capability to run the suite + a spec at the same time we call: `wdio -- --suite $"Suite" --spec $"Spec"` but sometimes we dont have a spec (it's a config in Jenkins) 
![image](https://github.com/webdriverio/webdriverio/assets/2396250/4a398430-b25b-45c9-a21d-7ea9d9ee468b)

### What is your expected behavior?

Expected that only the specs I defined in the suite are ran when using the `-- --suite` command even if I have --spec blank

### How to reproduce the bug.

1. Create two folders "ess" and "ess2"
2. Create a suite that ONLY contains "ess"
3. Run that suite

**Actual Results:**
- Both folder of specs get ran

### Relevant log output

```typescript
ESS2 folder is ran
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2023-05-17 22:19
Thanks for reporting, can you provide a minimal reproducible example?

**Comment by awhisler** [comment] 2023-05-22 15:02
@christian-bromann Not sure I understand the question. All you need to do is create a WDIO project that is on V8 and if there are two folders named similiar `ess` and `ess2` and only put `ess` in a suite. When you call the suite, it runs both folder's specs

**Comment by christian-bromann** [comment] 2023-05-22 16:01
Well I am asking for a reproducible example because it is not easily reproducible, e.g. the following setup works as expected:

![Screenshot 2023-05-22 at 09 00 53](https://github.com/webdriverio/webdriverio/assets/731337/d227afa4-7761-429c-8985-16df69f49761)

**Comment by awhisler** [comment] 2023-05-23 17:09
@christian-bromann It looks like the real problem is that it isn't respecting my suites. Am I calling them wrong?
Suite:
```'full-validation-absencetracker': [
      `${__dirname}/specs/apis/**/*.spec.js`,
      `${__dirname}/specs/at-admin/*.spec.js`,
      `${__dirname}/specs/configurations/**/*.spec.js`,
      `${__dirname}/specs/ess/**/*.spec.js`,
      `${__dirname}/specs/misc/**/*.spec.js`,
    ],```

Call: `wdio -- --suite "full-validation-absencetracker" 

It calls ALL specs not just the onces I have in that suite section

**Comment by christian-bromann** [comment] 2023-05-23 17:14
You should call it like that: `npx wdio run wdio.conf.js --suite "full-validation-absencetracker"`

**Comment by awhisler** [comment] 2023-05-24 21:24
@christian-bromann My test is doing that (this is running another suite called `apis`
![image](https://github.com/webdriverio/webdriverio/assets/2396250/76f60fed-e6eb-4bb7-99b8-97399c6b6960)
Which only has `31 test cases` but it runs my entire set of test cases not just my suite
![image](https://github.com/webdriverio/webdriverio/assets/2396250/e257d994-b490-4077-b7dd-d998a6774335)

**Comment by christian-bromann** [comment] 2023-05-24 21:35
@awhisler look, I have tried to reproduce this without success. I can't spend much time on figuring out how to reproduce the problem when you are the best person to help with that. If you can create a minimal reproducible example in a GitHub repository that would be ideal.

**Comment by awhisler** [comment] 2023-05-24 22:03
@christian-bromann So I created a small project for you and think I found the route cause. In order to give the capability to run both the Suite and a Spec at the same time we call it like this:

![image](https://github.com/webdriverio/webdriverio/assets/2396250/7ad200d9-5f95-4d2f-8706-3363e116f447)
`npm run browserstack -- --suite "${Suites}" --spec $Spec`

If I just called `npm run browserstack -- --suite "${Suites}"` it calls the right amount of specs in that suite but when I add a blank `--spec` if I didn't input a spec to call, it calls ALL specs.

**Comment by awhisler** [comment] 2023-05-24 22:20
I have been trying to send you the project but can't get it down to 25MB to upload....

**Comment by christian-bromann** [comment] 2023-05-24 22:38
Just create a new github repository and link it here

**Comment by awhisler** [comment] 2023-05-25 14:10
@christian-bromann https://github.com/awhisler/wdioTest
Command: `npm run test:endtoend -- --suite home --spec` (runs both specs)
Command: `npm run test:endtoend -- --suite home` (runs just the one spec)

**Comment by christian-bromann** [comment] 2023-05-25 14:35
Thanks for reporting!

With the reproducible example it will help to come up with a solution.

Any contributions that resolves the bug are highly appreciated. Don't expect this to be picked up by active contributors as they have their own priorities. If you depend on this bug to be fixed, your contribution is required. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) or join our [Discord](http://discord.webdriver.io/) development server and let us know if you have any questions. Cheers!

**Comment by awhisler** [comment] 2023-05-25 15:36
@christian-bromann Thank you. Is there any other way to call it that I could use temporarily?

**Comment by christian-bromann** [comment] 2023-05-25 16:49
I don't know, I think we should look for fixing this bug rather than using workarounds 😉

**Comment by KierenLWoods** [comment] 2023-09-29 09:07
@christian-bromann I have found the cause of this issue, so in the configParser function getSpecs, when setting the value of isSpecParamPassed the Array.isArray function was always returning true even if no spec file was passed with the --spec parameter. I think a check that the array length is greater than zero something like this const isSpecParamPassed = (this._config.spec.length !== 0); will resolve the issue. Happy to pick this issue up .

**Comment by Delta456** [comment] 2024-10-28 19:31
This can be closed because https://github.com/webdriverio/webdriverio/pull/11271 is merged which already fixes this

**Comment by christian-bromann** [comment] 2024-10-28 21:05
Good call, closing.

**Closed by christian-bromann** 2024-10-28 21:05 UTC
Labels: Bug 🐛, help wanted, good first pick, Hacktoberfest
