### ISSUE TITLE
Chaining of element(selector) erases outer scope for getHTML()

### ISSUE THREAD

**Issue by akloeber** [webdriverio/webdriverio#2155] opened 2017-06-22 11:45 UTC
## The problem

If selectors are chained via `browser.element(selector0).element(selector1)` a subsequent call to `element.getHTML()` reveals that only the last selector `selector1` is applied and the HTML of all elements that match is returned. The first selector `selector0` is ignored completely.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 6.10.3
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): WDIO Testrunner with synchronous mode enabled
* Additional wdio packages used (if applicable):
    * wdio-junit-reporter: 0.3.0
    * wdio-spec-reporter: 0.1.0
    * wdio-dot-reporter: 0.0.8
    * wdio-mocha-framework: 0.5.10
    * wdio-phantomjs-service: 0.2.2
    * wdio-selenium-standalone-service: 0.0.8
## Details

The output of the example below is:
```
$ node_modules/.bin/wdio wdio.conf.js --spec test/bug_getHTML.js

Debugger listening on [::]:5859
(node:68037) DeprecationWarning: `DEBUG_FD` is deprecated. Override `debug.log` if you want to use a different log function (https://git.io/vMUyr)
Text Maria Anders
HTML [ '<td class="gsib_b"><div class="gsst_b" id="gs_st50" dir="ltr"><a class="gsst_a" href="javascript:void(0)" style="display: none;"><span class="gscb_a" id="gs_cb50">×</span></a></div></td>',
  '<td class="gsc-search-button"><input type="image" src="https://www.google.com/uds/css/v2/search_box_icon.png" class="gsc-search-button gsc-search-button-v2" title="search"></td>',
  '<td class="gsc-branding-text"><div class="gsc-branding-text">powered by</div></td>',
  '<td class="gsc-configLabelCell"></td>',
  '<td>Maria Anders</td>',
  '<td>Francisco Chang</td>',
  '<td>Roland Mendel</td>',
  '<td>Helen Bennett</td>',
  '<td>Yoshi Tannamuri</td>',
  '<td>Giovanni Rovelli</td>',
  '<td>Defines a table</td>',
  '<td>Defines a header cell in a table</td>',
  '<td>Defines a row in a table</td>',
  '<td>Defines a cell in a table</td>',
  '<td>Defines a table caption</td>',
  '<td>Specifies a group of one or more columns in a table for formatting</td>',
  '<td>Specifies column properties for each column within a &lt;colgroup&gt; element</td>',
  '<td>Groups the header content in a table</td>',
  '<td>Groups the body content in a table</td>',
  '<td>Groups the footer content in a table</td>',
  '<td class="gssb_e" style="width: 100%;"></td>' ]
․

1 passing (5.60s)
```

## Link to Selenium/WebdriverIO logs

Full log: https://gist.github.com/akloeber/9da6972fd39d6cc2fbc182a19243b085

## Code To Reproduce Issue

```javascript
suite('suite', function () {

  test('test', function () {
    browser.url('https://www.w3schools.com/html/html_tables.asp');
    const contactCell = browser.element('table#customers tr:nth-of-type(2)').element('td:nth-of-type(2)');

    // OK - returns content of target cell ("Maria Anders")
    console.log('Text', contactCell.getText());
    // NOK - returns array with HTML of ALL <td>-elements in the page that match 'td:nth-of-type(2)'
    console.log('HTML', contactCell.getHTML());
  });

});
```

**Comment by christian-bromann** [comment] 2017-06-22 11:47
Duplicate of #1879

**Closed by christian-bromann** 2017-06-22 11:47 UTC

**Comment by akloeber** [comment] 2017-06-22 11:58
@christian-bromann #1879 sounds similar but the issue described here is provoked only with a chain of `element()` calls where #1879 is about `$$` (i.e. `elements()`) usage. Nevertheless the symptoms are identical.
