### ISSUE TITLE
[💡 Feature Request]: Allow setting breakpoints when using browser runner

### ISSUE THREAD

**Issue by ohernandezIBM** [webdriverio/webdriverio#10135] opened 2023-04-07 22:38 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.7.0

### Node.js Version

v16.15.1

### Mode

Standalone Mode

### What happened?

I am trying to use browser tests for document and window tests. So I tried the following projects:

- https://github.com/webdriverio/component-testing-examples/tree/main/solidjs-typescript-vite
- https://github.com/webdriverio/component-testing-examples/tree/main/react-typescript-vite

I use vscode to run and debug. I place breakpoints on tests, but they never get hit. When I run "npm run wdio" on js terminal, I get unbound breakpoint.

I also tried using launch.js configuration from https://webdriver.io/docs/debugging/#debugging-with-visual-studio-code-vscode

     {
          "name": "run select spec",
          "type": "node",
          "request": "launch",
          "args": ["wdio.conf.ts"],
          "cwd": "${workspaceFolder}",
          "autoAttachChildProcesses": true,
          "program": "${workspaceRoot}/node_modules/@wdio/cli/bin/wdio.js",
          "console": "integratedTerminal",
          "skipFiles": [
              "${workspaceFolder}/node_modules/**/*.js",
              "${workspaceFolder}/lib/**/*.js",
              "<node_internals>/**/*.js"
          ]
      }

I get the following on tests:

"Unbound breakpoint
Some of the breakpoints could not be set. If you're having an issue, you can troubleshoot your launch configuration"

So I click on hyperlink which displays:

./src/tests/counter.test.tsx:10:1
✅ This breakpoint was initially set in:

/Users/omarhernandez/Downloads/untitledfolder9/solidjs-typescript-vite/src/tests/counter.test.tsx line 10 column 1

❓ We couldn't find a corresponding source location, and didn't find any source with the name counter.test.tsx.

How did you expect this file to be loaded? (If you have a compilation step, you should pick 'sourcemap')
Loaded in directlyBe parsed from a sourcemap
Here's some hints that might help you:
- Make sure you have "sourceMap": true in your tsconfig to generate sourcemaps.

### What is your expected behavior?

I am expecting to use vs code to debug and write my tests. Otherwise it will not be productive. It will be like going back to Stone Age.

### How to reproduce the bug.

To reproduce you can use repo at :

-  https://github.com/webdriverio/component-testing-examples/tree/main/solidjs-typescript-vite

Then just:

- open vs code and add it
- run on js terminal
- npm install
- place breakpoint on any test file
- run
- npm run wide
- you will see that breakpoint never stops

I do have breakpoint always on node in vs code

### Relevant log output

```typescript
wdio-0-0-browser.log:
{"level":"WARNING","message":"http://localhost:3000/node_modules/.vite/deps/chunk-2572KWZS.js?v=1033de16 5941:18 \"Module \\\"path\\\" has been externalized for browser compatibility. Cannot access \\\"path.sep\\\" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.\"","source":"console-api","timestamp":1680906407324}
{"level":"WARNING","message":"http://localhost:3000/node_modules/.vite/deps/expect.js?v=1033de16 6265:18 \"Module \\\"module\\\" has been externalized for browser compatibility. Cannot access \\\"module.builtinModules\\\" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.\"","source":"console-api","timestamp":1680906407326}
{"level":"WARNING","message":"http://localhost:3000/node_modules/.vite/deps/chunk-2572KWZS.js?v=1033de16 5941:18 \"Module \\\"path\\\" has been externalized for browser compatibility. Cannot access \\\"path.sep\\\" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.\"","source":"console-api","timestamp":1680906425446}
{"level":"WARNING","message":"http://localhost:3000/node_modules/.vite/deps/expect.js?v=1033de16 6265:18 \"Module \\\"module\\\" has been externalized for browser compatibility. Cannot access \\\"module.builtinModules\\\" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.\"","source":"console-api","timestamp":1680906425446}
{"level":"WARNING","message":"http://localhost:3000/node_modules/.vite/deps/chunk-2572KWZS.js?v=1033de16 5941:18 \"Module \\\"path\\\" has been externalized for browser compatibility. Cannot access \\\"path.sep\\\" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.\"","source":"console-api","timestamp":1680906428786}
{"level":"WARNING","message":"http://localhost:3000/node_modules/.vite/deps/expect.js?v=1033de16 6265:18 \"Module \\\"module\\\" has been externalized for browser compatibility. Cannot access \\\"module.builtinModules\\\" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.\"","source":"console-api","timestamp":1680906428786}
{"level":"SEVERE","message":"http://localhost:3000/@fs/Users/omarhernandez/Downloads/untitledfolder9/solidjs-typescript-vite/node_modules/@wdio/browser-runner/build/browser/driver.js?import 99:45 Uncaught Error: Failed to execute command \"executeScript\": stale e… not found\n  (Session info: chrome=112.0.5615.49)","source":"javascript","timestamp":1680906429470}
{"level":"SEVERE","message":"http://localhost:3000/@fs/Users/omarhernandez/Downloads/untitledfolder9/solidjs-typescript-vite/node_modules/@wdio/browser-runner/build/browser/driver.js?import 99:45 Uncaught Error: Failed to execute command \"executeScript\": stale e… not found\n  (Session info: chrome=112.0.5615.49)","source":"javascript","timestamp":1680906429489}


wdio-0-0-driver.log:
{"level":"WARNING","message":"This version of ChromeDriver has not been tested with Chrome version 112.\n","timestamp":1680906403071}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2023-04-08 04:26
Thanks for reporting!

Setting break points when the test run in the browser is a little bit more difficult than when running within Node.js. It is however not impossible and we should find a way to implement this.

Any contributions that implements this feature is highly appreciated. Don't expect this to be picked up by active contributors as they have their own priorities. If you depend on this feature to be fixed, your contribution is required. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by ohernandezIBM** [comment] 2023-04-10 18:12
Where is the sourcemap location? Can it be debugged similar to https://github.com/microsoft/vscode-recipes/tree/main/vuejs-cli

**Comment by christian-bromann** [comment] 2023-04-10 19:47
That should work, thanks for sharing. Vite should be able to expose source maps in a similar way as with Webpack. We can also extend the Vite server to have endpoints for them.

**Comment by christian-bromann** [comment] 2023-11-06 04:39
Duplicate of #10756

**Closed by christian-bromann** 2023-11-06 04:39 UTC
Labels: help wanted, Idea 💡
