### ISSUE TITLE
[🐛 Bug]: Throw meaningful error if .isClickable() Method is called in native context

### ISSUE THREAD

**Issue by emilioDuarte** [webdriverio/webdriverio#7773] opened 2021-12-03 04:26 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
config.capabilities = [
    {
        platformName: 'Android',
        automationName: 'UiAutomator2',
        deviceName: 'Pixel_3_11',
        platformVersion: '',
        maxInstances: 1,
        appWaitActivity: '*',
        app: join(process.cwd(), './apps/myApp.apk'),
        noReset: true,
        newCommandTimeout: 240

    },
];
```

### What happened?

Getting if a Native Element is clickable or not using the method .isClickable() is returning an error 
NotImplementedError: Method is not implemented
    at AndroidUiautomator2Driver.execute

### What is your expected behavior?

The method .isClickable() should return a boolean value if the element is clickable or not.

### How to reproduce the bug.

To reproduce a bug:

Use a native app.
Target any locator

$('//*[@content-desc="Continue"]').isClickable()

### Relevant log output

```typescript
NotImplementedError: Method is not implemented
    at AndroidUiautomator2Driver.execute (/Users/emilio.duarte/Documents/QuadPay/mobile-app-auto-tests/node_modules/appium/node_modules/appium-android-driver/lib/commands/execute.js:14:11)
    at commandExecutor (/Users/emilio.duarte/Documents/QuadPay/mobile-app-auto-tests/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:335:9)
    at /Users/emilio.duarte/Documents/QuadPay/mobile-app-auto-tests/node_modules/appium/node_modules/async-lock/lib/index.js:146:12
    at AsyncLock._promiseTry (/Users/emilio.duarte/Documents/QuadPay/mobile-app-auto-tests/node_modules/appium/node_modules/async-lock/lib/index.js:280:31)
    at exec (/Users/emilio.duarte/Documents/QuadPay/mobile-app-auto-tests/node_modules/appium/node_modules/async-lock/lib/index.js:145:9)
    at AsyncLock.acquire (/Users/emilio.duarte/Documents/QuadPay/mobile-app-auto-tests/node_modules/appium/node_modules/async-lock/lib/index.js:162:3)
    at AndroidUiautomator2Driver.executeCommand (/Users/emilio.duarte/Documents/QuadPay/mobile-app-auto-tests/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:348:39)
    at AppiumDriver.executeCommand (/Users/emilio.duarte/Documents/QuadPay/mobile-app-auto-tests/node_modules/appium/lib/appium.js:563:36)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at asyncHandler (/Users/emilio.duarte/Documents/QuadPay/mobile-app-auto-tests/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by emilioDuarte** [comment] 2021-12-03 04:28
Example: 
 let clickable = await $('//*[@content-desc="Continue"]').isClickable();
console.log(clickable);

![image](https://user-images.githubusercontent.com/94387063/144545245-ff991122-ed44-46c8-b1bd-528b3ccd6324.png)

**Comment by emilioDuarte** [comment] 2021-12-03 04:28
The same happens with waitForClickable()

**Comment by erwinheitzman** [comment] 2021-12-03 14:17
> The same happens with waitForClickable()

This is logical because it uses `isClickable` under the hood.

Regarding the functionality, I notice you are using [`appium-android-driver` https://github.com/appium/appium-android-driver](https://github.com/appium/appium-android-driver) which is deprecated and it's where the error seems to be coming from when you look at your logs

**Comment by emilioDuarte** [comment] 2021-12-03 14:48
Actually, I think I am using uiautomator2, instead of appium-android-driver
![image](https://user-images.githubusercontent.com/94387063/144622088-a741537d-9353-4748-88b1-f6b7723c2222.png)

**Comment by erwinheitzman** [comment] 2021-12-03 14:51
It might use it under the hood then?

It clearly shows both tools in this line:
```
at AndroidUiautomator2Driver.execute (/Users/emilio.duarte/Documents/QuadPay/mobile-app-auto-tests/node_modules/appium/node_modules/appium-android-driver/lib/commands/execute.js:14:11)
```

**Comment by erwinheitzman** [comment] 2021-12-03 14:53
So this makes me pretty confident that the problem is not with WebdriverIO but instead it seem to be the driver or perhaps Appium. I could still be wrong but WebdriverIO doesn't seem to be throwing any errors here

**Comment by wswebcreation** [comment] 2021-12-03 15:14
This is not a bug, it's a _feature_ 🤣 . 

Sorry for the awful joke, but there is no JS context in a native app, so you can't use the execute command to inject a bunch of JS. There might be other ways to check this for native apps, but that might make this a very complex method

**Comment by emilioDuarte** [comment] 2021-12-03 15:16
related to the comment from @erwinheitzman, I found out that besides I specify the automationName, appium is still using the appium-android-driver
![image](https://user-images.githubusercontent.com/94387063/144626528-67a105ae-96e3-40be-ac0d-3701920355f7.png)

**Comment by wswebcreation** [comment] 2021-12-03 15:20
> related to the comment from @erwinheitzman, I found out that besides I specify the automationName, appium is still using the appium-android-driver ![image](https://user-images.githubusercontent.com/94387063/144626528-67a105ae-96e3-40be-ac0d-3701920355f7.png)

There are multiple drivers installed by Appium when you install Appium itself. This will change with Appium 2.0. 
You can already see the XCUITest-driver in the list, which is used for iOS. All available drivers will be installed when you install Appium 1.x.
When you select the `automationName: 'uiautomator2'` Appium will use the UIAutomator2 driver, even if you don't provide that cap, it will still use it by default.

**Comment by emilioDuarte** [comment] 2021-12-03 15:24
Hey @wswebcreation, thanks for the reply, however, it seems to be using by default the appium-android-driver, even specifying the capability, you can see it in the log that it is using indeed, the appium-android-driver, and not using the appium-uiautomator2-driver as I was expecting, correct me if I am wrong, but @erwinheitzman noticed it as well

**Comment by wswebcreation** [comment] 2021-12-03 15:26
You need to check the Appium logs itself, not the WDIO log, it might be that internally it uses the other driver (which I need to figure out) but I'm 100% sure that the initial driver is the UIAutomator2 driver

**Comment by erwinheitzman** [comment] 2021-12-03 15:28
I had the same assumption as @wswebcreation that `UIAutomator2` seems to be using `appium-android-driver` under the hood.

I think this issue can be closed as the command is not available in the native app context, correct?

**Comment by wswebcreation** [comment] 2021-12-03 15:29
exactly

**Comment by wswebcreation** [comment] 2021-12-03 15:29
> I had the same assumption as @wswebcreation that `UIAutomator2` seems to be using `appium-android-driver` under the hood.
> 
> I think this issue can be closed as the command is not available in the native app context, correct?

Exactly

**Comment by christian-bromann** [comment] 2021-12-06 09:32
@erwinheitzman @wswebcreation I suggest to add an if statement to `isClickable` to check if it is run in mobile native context and throw an error with a meaningful message, what do you think?

**Comment by wswebcreation** [comment] 2021-12-06 09:47
Good idea, is there a way to determine this without checking the context with a call, relying on the `app` cap is not enough because:
- an app can also be started with the iOS `bundleId` or Android `packageName`
- the context can be switched so it might started in web, but during the tests the context was changed to native

Or should it be something like this to keep is stable every point in time?

```js
if (driver.isMobile) {
   if ((await driver.getContext()) === 'NATIVE_APP') {
      // Throw an error or don't do anything?
   }
}
```

**Comment by christian-bromann** [comment] 2021-12-06 09:54
> Or should it be something like this to keep is stable every point in time?

I think this sounds like a reasonable solution

**Comment by wswebcreation** [comment] 2021-12-06 10:11
@christian-bromann 

Do you want to throw an error or write to the logs?

**Comment by christian-bromann** [comment] 2021-12-06 10:16
> Do you want to throw an error or write to the logs?

Throw it, so that the user sees a meaningful error instead of `NotImplementedError: Method is not implemented`

**Comment by wswebcreation** [comment] 2021-12-06 10:28
I can pick this up in the coming week(s)

**Comment by mykola-mokhnach** [comment] 2021-12-07 18:55
@christian-bromann I can confirm the issue lies in WDIO, because it sends a javascript snippet there, which expectedly fails in mobile native context: https://github.com/appium/appium/issues/16213#issuecomment-988184462

I'm not quite sure how to map this method to a W3C API call, because the standard does not describe anything that is capable of checking whether an item is clickable neither defines element attribute names.

**Comment by christian-bromann** [comment] 2021-12-08 08:03
@mykola-mokhnach thanks for confirming. Yes, calling `isClickable` doesn't work in mobile context which is why I suggested to Wim to improve the error message to give the user more information about why the command is failing.

**Closed** 2022-08-22 08:52 UTC
Labels: Bug 🐛, help wanted, good first pick
