### ISSUE TITLE
ERROR webdriver: Request failed with status 200 due to Response has empty body

### ISSUE THREAD

**Issue by gauravkrp** [webdriverio/webdriverio#6881] opened 2021-05-19 11:12 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** [7.1.2]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running async:** 
 - **Node.js version:** [ 14.0.0]
 - **NPM version:** [ 6.14.1]
 - **Browser name and version:** [Chrome 90]
 - **Platform name and version:** [Windows 10]
 - **Additional wdio packages used :** [@wdio/spec reporter - 7.2.0,]

**Config of WebdriverIO**
Default config

**Describe the bug**
webdriver: Request failed with status 200 due to Response has empty body
![image](https://user-images.githubusercontent.com/12250556/118803524-15ddfa00-b8c1-11eb-8702-b712fdbab96f.png)

**Expected behavior**
Test should have run

**Comment by christian-bromann** [comment] 2021-05-19 11:55
Could you provide more information how you run the test? A reproducible example maybe?

**Comment by gauravkrp** [comment] 2021-05-19 13:10
> Could you provide more information how you run the test? A reproducible example maybe?

Here you go https://github.com/gauravkrp/wdio_test

**Comment by christian-bromann** [comment] 2021-05-19 14:31
I can't reproduce this problem on my Mac machine, can you set logLevel to `trace` and provide the logs?

**Comment by gauravkrp** [comment] 2021-05-19 14:55
> I can't reproduce this problem on my Mac machine, can you set logLevel to `trace` and provide the logs?
I did as you suggest. Hope it helps you and helps me resolve it.
![image](https://user-images.githubusercontent.com/12250556/118835033-441f0200-b8e0-11eb-9582-c4e0d3805d34.png)

**Comment by christian-bromann** [comment] 2021-05-19 15:03
Can you re-try and remove `'goog:chromeOptions'` before?

**Comment by gauravkrp** [comment] 2021-05-19 15:09
> Can you re-try and remove `'goog:chromeOptions'` before?

I did it and retried, still the same issue :(

````
Execution of 1 spec files started at 2021-05-19T15:07:48.092Z

2021-05-19T15:07:48.101Z DEBUG @wdio/utils:initialiseServices: initialise service "chromedriver" as NPM package
2021-05-19T15:07:48.220Z INFO @wdio/cli:launcher: Run onPrepare hook
Starting ChromeDriver 90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
2021-05-19T15:07:48.775Z DEBUG @wdio/cli:utils: Finished to run "onPrepare" hook in 554ms
2021-05-19T15:07:48.780Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2021-05-19T15:07:48.780Z DEBUG @wdio/cli:utils: Finished to run "onWorkerStart" hook in 0ms
2021-05-19T15:07:48.793Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.js,--spec=test/specs/hcpCreation.js
[0-0] 2021-05-19T15:07:51.588Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2021-05-19T15:07:52.256Z DEBUG @wdio/config:utils: Found 'ts-node' package, auto-compiling TypeScript files
[0-0] 2021-05-19T15:07:52.506Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2021-05-19T15:07:52.522Z DEBUG @wdio/utils:initialiseServices: initialise service "chromedriver" as NPM package
[0-0] RUNNING in chrome - C:\dev\cbh\clipboard-health\test\specs\hcpCreation.js
[0-0] 2021-05-19T15:07:53.959Z DEBUG @wdio/local-runner:utils: init remote session
2021-05-19T15:07:53.962Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2021-05-19T15:07:53.965Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2021-05-19T15:07:53.965Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
}

DevTools listening on ws://127.0.0.1:65359/devtools/browser/893e2b97-4df8-4758-8c64-a819c518aac4
[20836:22384:0519/203754.908:ERROR:device_event_log_impl.cc(214)] [20:37:54.909] USB: usb_device_handle_win.cc:1054 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[20836:22384:0519/203754.914:ERROR:device_event_log_impl.cc(214)] [20:37:54.914] USB: usb_device_handle_win.cc:1054 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[0-0] 2021-05-19T15:07:54.949Z DEBUG webdriver: request failed due to missing body
[0-0] 2021-05-19T15:07:54.950Z WARN webdriver: Request failed with status 200 due to Response has empty body
[0-0] 2021-05-19T15:07:54.951Z INFO webdriver: Retrying 1/3
2021-05-19T15:07:54.951Z INFO webdriver: [POST] http://localhost:9515/session
2021-05-19T15:07:54.951Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
}

DevTools listening on ws://127.0.0.1:65367/devtools/browser/dfaeab3a-368b-49f5-95fa-9da3db3697a8
[0-0] 2021-05-19T15:07:55.821Z DEBUG webdriver: request failed due to missing body
[0-0] 2021-05-19T15:07:55.822Z WARN webdriver: Request failed with status 200 due to Response has empty body
[0-0] 2021-05-19T15:07:55.822Z INFO webdriver: Retrying 2/3
````

**Comment by christian-bromann** [comment] 2021-05-19 15:17
mhm .. unfortunately I don't have a Windows machine an am unable to investigate the issue. Any help would be appreciated.

**Comment by gauravkrp** [comment] 2021-05-19 15:24
> mhm .. unfortunately I don't have a Windows machine an am unable to investigate the issue. Any help would be appreciated.

Thank you for considering! I shall watch this space for a solution.

if you can, I can provide remote desktop access.

**Comment by advait012** [comment] 2021-08-23 11:55
@gauravkrp , Are you still facing the issue ?

**Comment by gauravkrp** [comment] 2021-08-23 13:00
> @gauravkrp , Are you still facing the issue ?

Hey I moved away from using Windows! So, can't say if it still exists there.

**Comment by advait012** [comment] 2021-08-25 06:29
I am also getting same issue , Just to inform you that I am using automation protocol as "Webdriver" instead of devtools. I am using gauge automation framework as test runner.

Error Details:-

```

Running "selenium_standalone:testserver:install" (selenium_standalone) task
----------
selenium-standalone installation starting
----------

---
selenium install:
from: https://selenium-release.storage.googleapis.com/3.9/selenium-server-standalone-3.9.0.jar
to: C:\Projects\Cisco\controlhublite\node_modules\selenium-standalone\.selenium\selenium-server\3.9.0-server.jar
---
chrome install:
from: https://chromedriver.storage.googleapis.com/91.0.4472.101/chromedriver_win32.zip
to: C:\Projects\Cisco\controlhublite\node_modules\selenium-standalone\.selenium\chromedriver\91.0.4472.101-x64-chromedriver
---
ie install:
from: https://selenium-release.storage.googleapis.com/3.14/IEDriverServer_x64_3.14.0.zip
to: C:\Projects\Cisco\controlhublite\node_modules\selenium-standalone\.selenium\iedriver\3.14.0-x64-IEDriverServer.exe
---
firefox install:
from: https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-win64.zip
to: C:\Projects\Cisco\controlhublite\node_modules\selenium-standalone\.selenium\geckodriver\0.26.0-x64-geckodriver
---
File from https://selenium-release.storage.googleapis.com/3.14/IEDriverServer_x64_3.14.0.zip has already been downloaded
---
File from https://chromedriver.storage.googleapis.com/91.0.4472.101/chromedriver_win32.zip has already been downloaded
---
File from https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-win64.zip has already been downloaded
---
File from https://selenium-release.storage.googleapis.com/3.9/selenium-server-standalone-3.9.0.jar has already been downloaded


-----
selenium-standalone installation finished
-----

Running "selenium_standalone:testserver:start" (selenium_standalone) task

Running "run:specs" (run) task
[2021-08-23T18:02:40.715] [INFO] default - Found .env in root, reading environments...
2021-08-23T12:32:41.915Z INFO webdriver: Initiate new session using the WebDriver protocol
2021-08-23T12:32:41.919Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
2021-08-23T12:32:41.919Z INFO webdriver: DATA {
capabilities: {
alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
firstMatch: [ {} ]
},
desiredCapabilities: {
browserName: 'chrome',
'goog:chromeOptions': { prefs: [Object], args: [Array] }
}
}
2021-08-23T12:32:44.420Z WARN webdriver: Request failed with status 200 due to Response has empty body
2021-08-23T12:32:44.421Z INFO webdriver: Retrying 1/3
2021-08-23T12:32:44.421Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
2021-08-23T12:32:44.421Z INFO webdriver: DATA {
capabilities: {
alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
firstMatch: [ {} ]
},
desiredCapabilities: {
browserName: 'chrome',
'goog:chromeOptions': { prefs: [Object], args: [Array] }
}
}
2021-08-23T12:32:46.186Z WARN webdriver: Request failed with status 200 due to Response has empty body
2021-08-23T12:32:46.187Z INFO webdriver: Retrying 2/3
2021-08-23T12:32:46.187Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
2021-08-23T12:32:46.187Z INFO webdriver: DATA {
capabilities: {
alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
firstMatch: [ {} ]
},
desiredCapabilities: {
browserName: 'chrome',
'goog:chromeOptions': { prefs: [Object], args: [Array] }
}
}
2021-08-23T12:32:48.170Z WARN webdriver: Request failed with status 200 due to Response has empty body
2021-08-23T12:32:48.170Z INFO webdriver: Retrying 3/3
2021-08-23T12:32:48.170Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
2021-08-23T12:32:48.170Z INFO webdriver: DATA {
capabilities: {
alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
firstMatch: [ {} ]
},
desiredCapabilities: {
browserName: 'chrome',
'goog:chromeOptions': { prefs: [Object], args: [Array] }
}
}
2021-08-23T12:32:50.297Z ERROR webdriver: Request failed with status 200 due to Error: Response has empty body
2021-08-23T12:32:50.297Z ERROR webdriver: Error: Response has empty body
at Object.getErrorFromResponseBody (C:\Projects\Cisco\controlhublite\node_modules\@online\gauge-sdk-js\node_modules\webdriver\build\utils.js:86:16)
at WebDriverRequest._request (C:\Projects\Cisco\controlhublite\node_modules\@online\gauge-sdk-js\node_modules\webdriver\build\request.js:134:31)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async Object.startWebDriverSession (C:\Projects\Cisco\controlhublite\node_modules\@online\gauge-sdk-js\node_modules\webdriver\build\utils.js:29:20)
at async Function.newSession (C:\Projects\Cisco\controlhublite\node_modules\@online\gauge-sdk-js\node_modules\webdriver\build\index.js:35:45)
at async exports.remote (C:\Projects\Cisco\controlhublite\node_modules\@online\gauge-sdk-js\node_modules\webdriverio\build\index.js:53:22)
at async Object.initRemoteBrowser (C:\Projects\Cisco\controlhublite\node_modules\@online\gauge-sdk-js\gauge\wdio\config\browsers.js:31:17)
at async Object.<anonymous> (C:\Projects\Cisco\controlhublite\gauge\steps\hooks\hooks.js:20:5)

Failed to capture screenshot on failure.
TypeError: Cannot read property 'saveScreenshot' of undefined

Failed to capture screenshot on failure.
TypeError: Cannot read property 'saveScreenshot' of undefined

  Error Message: Error: Failed to create session.
  Make sure to connect to valid hostname:port or the port is not in use.
  If you use a grid server
  Make sure to add vendor prefix like "goog:", "appium:", "moz:", etc to non W3C capabilities.
  See more https://www.w3.org/TR/webdriver/#capabilities
  Stacktrace:
  Error: Failed to create session.
  Make sure to connect to valid hostname:port or the port is not in use.
  If you use a grid server
  Make sure to add vendor prefix like "goog:", "appium:", "moz:", etc to non W3C capabilities.
  See more https://www.w3.org/TR/webdriver/#capabilities
      at Object.startWebDriverSession (node_modules\@online\gauge-sdk-js\node_modules\webdriver\build\utils.js:34:15)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Function.newSession (node_modules\@online\gauge-sdk-js\node_modules\webdriver\build\index.js:35:45)
      at async exports.remote (node_modules\@online\gauge-sdk-js\node_modules\webdriverio\build\index.js:53:22)
      at async Object.initRemoteBrowser (node_modules\@online\gauge-sdk-js\gauge\wdio\config\browsers.js:31:17)
      at async Object.<anonymous> (gauge\steps\hooks\hooks.js:20:5)

  Error Message: {}
  Stacktrace:
  TypeError: Cannot read property 'deleteSession' of undefined
      at bstackCleanup (gauge\steps\hooks\hooks.js:40:23)
      at Object.<anonymous> (gauge\steps\hooks\hooks.js:44:9)
Successfully generated html-report to => C:\Projects\Cisco\controlhublite\reports\chrome\html-report\index.html

Successfully generated xml-report to => C:\Projects\Cisco\controlhublite\reports\chrome\xml-report

Specifications: 0 executed      0 passed        0 failed        0 skipped
Scenarios:      0 executed      0 passed        0 failed        0 skipped

Total time taken: 11.726s
Updates are available. Run `gauge update -c` for more info.
Warning: non-zero exit code 1 Use --force to continue.

Aborted due to warnings.
error Command failed with exit code 3.

```

Could someone help in this ? what does this error means ?

**Comment by advait012** [comment] 2021-09-06 04:58
Do we have any update on this issue ?

**Comment by christian-bromann** [comment] 2021-09-06 07:09
@advait012 if you have a Windows machine to help out with the issue please do.

**Comment by advait012** [comment] 2021-09-14 06:22
Issue is fixed on my side . I deleted npm cache and then reinstall nodejs and my project. hence I am no longer having this issue.

Thanks

**Comment by christian-bromann** [comment] 2021-09-14 07:01
@advait012 thanks for letting us know.

**Closed by christian-bromann** 2021-09-14 07:01 UTC
Labels: Needs Investigation, help wanted
