### ISSUE TITLE
webdriver.remote() doesn't merge all config options (and isn't documented)

### ISSUE THREAD

**Issue by philipwalton** [webdriverio/webdriverio#893] opened 2015-11-22 21:29 UTC
I'm running a test via the `wdio` command, and my test fails with the following error:

> Couldn't connect to selenium server

This happens when I call `webdriver.remote()` without passing any options (I'm assuming the options are supposed to be merged with the options defined in the config, and when I debug it, most of them are).

If I pass `user` and `key` to `remote()`, it works:

```js
var client = webdriverio.remote({
  user: process.env.SAUCE_USERNAME,
  key: process.env.SAUCE_ACCESS_KEY
});
```

I have these values defined in my config file, so it's not clear why I have to pass them again, unless this isn't intended behavior.

Also, it's not really clear what options can/should be passed to `remote()` because the function isn't documented anywhere (that I could find).

**Comment by christian-bromann** [comment] 2015-11-23 11:48
When running the wdio testrunner you shouldn't use the remote function. The test runner does that for you. If you have user and key defined in your config it should work. If not please paste it here so we can figure out whats wrong.

**Comment by philipwalton** [comment] 2015-11-23 20:03
Here's my test file (copied from the example):

```js
var assert = require('assert');

describe('webdriver.io page', function() {

    it('should have the right title - the good old callback way', function(done) {

        browser
            .url('/')
            .getTitle(function(err, title) {
                assert.equal(err, undefined);
                assert.equal(title, 'WebdriverIO - Selenium 2.0 javascript bindings for nodejs');
            })
            .call(done);

    });

});
```

And here's my config:

```js
exports.config = {

    user: process.env.SAUCE_USERNAME,
    key:  process.env.SAUCE_ACCESS_KEY,

    /**
     * server configurations
     */
    host: '0.0.0.0',
    port: 4444,

    /**
     * specify test files
     */
    specs: [
        './test.js'
    ],
    // exclude: [
    //     'test/spec/multibrowser/**',
    //     'test/spec/mobile/**'
    // ],

    /**
     * capabilities
     */
    capabilities: [
        {
            browserName: 'firefox'
        }
    ],

    /**
     * test configurations
     */
    logLevel: 'silent',
    coloredLogs: true,
    screenshotPath: 'shots',
    baseUrl: 'http://webdriver.io',
    waitforTimeout: 10000,
    framework: 'mocha',

    reporter: 'spec',
    reporterOptions: {
        outputDir: './'
    },

    mochaOpts: {
        ui: 'bdd'
    },

    /**
     * hooks
     */
    onPrepare: function() {
        console.log('let\'s go');
    },
    onComplete: function() {
        console.log('that\'s it');
    }

};
```

And when I run it I have the proper ENV variables set using:

```sh
export SAUCE_USERNAME=xxxxxxxx
export SAUCE_ACCESS_KEY=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

wdio
```

I know it's detecting  the `user` and `key` config options because if I log `detectSeleniumBackend(args)` I get this output:

```js
{ host: 'ondemand.saucelabs.com', port: 80, updateJob: true }
```

But the tests just run locally (I can see Firefox start up on my local machine), and no new jobs appear in my SauceLabs dashboard.

I'm happy to provide more details if you need them. I'm running version 3.2.6 of webdriverio.

**Comment by philipwalton** [comment] 2015-11-24 00:12
Ok, when I remove the `host` and `port` options from the config, it works on SauceLabs. I assumed since `detectSeleniumBackend` was returning the SauceLabs host and port, these values were being overridden, but apparently they weren't.

Also, it still does not update the job to show the pass/fail status in SauceLabs, which, again, was part of my original problem as referenced in #892

**Comment by philipwalton** [comment] 2015-11-24 00:42
FWIW, I've tried this both on Travis-CI as well as locally with Travis ENV variables set, and I get the same results. No status updates.

When I run the job locally with the Travis ENV variables, I've put a `console.log` statement in the [code where I believe the updating happens](https://github.com/webdriverio/webdriverio/blob/master/lib/runner.js#L170-L173), and it prints out, so I'm at least reasonably sure my config options or ENV variables aren't at fault here.

**Comment by christian-bromann** [comment] 2015-11-24 01:54
There was a bug fix that hasn't been published yet. Give me a sec...

**Comment by philipwalton** [comment] 2015-12-03 18:01
Since [you said I should bug you](https://github.com/webdriverio/gulp-webdriver/issues/29#issuecomment-161716078), consider this me bugging you :)

**Comment by christian-bromann** [comment] 2015-12-03 18:04
I released v3.3.0 9 days ago with a fix for that. Isn't that working?

**Comment by philipwalton** [comment] 2015-12-03 18:12
It is not. I just tried again via terminal (with ENV vars) and also checking in files in my project so they were run on Travis CI.

**Comment by christian-bromann** [comment] 2015-12-03 18:37
Do you run Sauce Connect?

**Comment by philipwalton** [comment] 2015-12-03 18:42
I have that set to true in `.travis.yml`, but the tests don't need access to localhost (they're just dummy tests at the moment) so I'm assuming it shouldn't matter?

Also, I get the same result when running via the command line with no Sauce Connect.

What do you need from me to help debug this?

**Comment by christian-bromann** [comment] 2015-12-03 18:44
If your tests are just dummy tests, can I get access to your test setup to find out the reason why it is not working. Or could you provide an easy to reproduce example?

**Comment by philipwalton** [comment] 2015-12-03 18:58
Sure, I can show you what I have here. And we can connect offline if you need more details.

`wdio.conf.js`:

```js
// When running on CI, this will be true
var isSauceLabs = process.env.SAUCE_USERNAME && process.env.SAUCE_ACCESS_KEY;


// https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/
var capabilities = [{browserName: 'firefox'}];
if (isSauceLabs) {
  capabilities = capabilities.concat([
    {
      browserName: 'chrome'
    },
    {
      browserName: 'MicrosoftEdge',
      platform: 'Windows 10'
    },
    {
      browserName: 'internet explorer',
      platform: 'Windows 8.1',
      version: '11'
    },
    {
      browserName: 'internet explorer',
      platform: 'Windows 8',
      version: '10'
    },
    {
      browserName: 'internet explorer',
      platform: 'Windows 8.1',
      version: '11'
    },
    {
      browserName: 'safari',
      platform: 'OS X 10.11'
    },
    {
      browserName: 'safari',
      platform: 'OS X 10.8',
      version: '6'
    }
  ]);
}


exports.config = {

  user: process.env.SAUCE_USERNAME,
  key:  process.env.SAUCE_ACCESS_KEY,

  updateJob: true,

  specs: [
    './test.js'
  ],

  capabilities: capabilities,

  logLevel: 'verbose',
  coloredLogs: true,
  baseUrl: 'http://webdriver.io',
  waitforTimeout: 60000,

  framework: 'mocha',
  reporter: 'spec',
  mochaOpts: {
    ui: 'bdd',
    timeout: 60000
  }
};
```

`test.js`:

```js
var assert = require('assert');

describe('webdriver.io page', function() {

    it('should have the right title - the good old callback way', function(done) {

        browser
            .url('/')
            .getTitle(function(err, title) {
                assert.equal(err, undefined);
                assert.equal(title, 'WebdriverIO - Selenium 2.0 javascript bindings for nodejs');
            })
            .call(done);

    });

});
```

`.travis.yml`:

```yaml
---
language: node_js
node_js:
  - "5"

addons:
  sauce_connect: true

env:
  global:
    - SAUCE_USERNAME=philipwalton-ga
    - SAUCE_ACCESS_KEY=XXXXXX

```

**Comment by philipwalton** [comment] 2015-12-15 07:56
Any more information on this? I'm happy to sync up off-thread if that would be helpful.

I could implement the update job logic manually in an `after` hook, but I'd rather not have to do that if you think a fix might be easy.

**Comment by christian-bromann** [comment] 2016-01-04 01:07
@philipwalton sorry for my delayed response.

> I assumed since detectSeleniumBackend was returning the SauceLabs host and port, these values were being overridden, but apparently they weren't.

If the user has host and port set we assume that he needs to change that so overwriting it would be a bad idea. Also if someone uses a different cloud host (other than Sauce Labs, Browserstack or Testingbot) he should be able to do so without enhancing that little helper thingy.

Ok I tried to figure out what's wrong but haven't found a problem is your code. It should work with the latest version (v3.4.0). Proof:
Code: https://github.com/christian-bromann/wdio-demo
Travis Job: https://travis-ci.org/christian-bromann/wdio-demo
Sauce Job: https://saucelabs.com/beta/tests/d6019f33d81b4bc494b4255716330046/commands

As you can see I ran three concurrent test in a build (it's not possible to share builds yet). All jobs were marked as passed.

Just fyi: in v4 we will introduce the idea of services. These will be able to interfere with the wdio test process and do certain job like updating job statuses and run Sauce Connect. Here is an example how the Sauce Labs service looks like: https://github.com/webdriverio/wdio-sauce-service. All you need to do is add the service in your wdio.conf.js like:

```js
  // ...
  services: ['sauce'],
  // ...
```

and set desired options, that's it! Let me know if you have any further questions. Feel free to close the issue otherwise. Cheers!

**Comment by monolithed** [comment] 2016-01-05 01:09
+1, And I got confused because I had experience with Karma before.
https://github.com/karma-runner/grunt-karma/blob/master/tasks/grunt-karma.js#L60

**Comment by christian-bromann** [comment] 2016-03-25 13:58
I think this issue is solved. If not please update to v4. If you have any more questions find me on Gitter or open a new issue.

**Closed by christian-bromann** 2016-03-25 13:58 UTC
Labels: Needs Investigation

**Comment by achavva** [comment] 2017-07-23 10:51
hi could someone please help me in storing the values in config files and read them in feature files
