### ISSUE TITLE
@wdio/browserstack-service: Name is changed after every test even if the name capability is set

### ISSUE THREAD

**Issue by facusantillo** [webdriverio/webdriverio#6777] opened 2021-04-28 22:42 UTC
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [7.5.2]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [async]
 - **Node.js version:** [12.19]
 - **NPM version:** [6.14.8]
 - **Browser name and version:** [appium]
 - **Platform name and version:** [macOS]
 - **Additional wdio packages used (if applicable):** [@wdio/browserstack-service]

**Config of WebdriverIO**
config.services = [
    [
        'browserstack',
        {
            args: {
                browserstackLocal: true
            },
            command: 'browserstack'
        }
    ]
],
config.capabilities = [
    {
        platformName: env.PLATFORM_NAME === 'Android' ? 'Android' : 'iOS',
        deviceName: env.DEVICE_NAME,
        platformVersion: env.PLATFORM_VERSION,
        orientation: env.DEVICE_ORIENTATION,
        automationName: env.PLATFORM_NAME === 'Android' ? 'UiAutomator2' : 'XCUITest',
        app: 'bs://' + env.BS_APP_ID,
        build: env.BS_BUILD,
        project: env.BS_PROJECT,
        name: env.BS_NAME,
        noReset: true,
        newCommandTimeout: 2400,
        recreateChromeDriverSessions: true,
        chromedriver_autodownload: true,
        relaxedSecurity: true,
        'browserstack.debug': true,
        autoGrantPermissions: true
    }
];
config.excludeDriverLogs = ['bugreport', 'server'];
config.user = env.BS_USER;
config.key = env.BS_KEY;
exports.config = config;

**Describe the bug**
When the suite starts executing on browserstack, every time a test is finished is overriding the name capability on the config

**To Reproduce**
Run a suite with wdio ./your_config_file --suite 'your suite with multiple tests in a describe'

**Expected behavior**
Running multiple tests from a same spec file shouldn't update the name capability if this is set.

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment] 2021-04-29 07:22
The BS service automatically sets the name based on the test. I think it makes sense to respect the name property within the capabilities and take that one if defined. If anyone is interested to contribute to this, please do. Happy to help.

**Comment by gabezeck** [comment] 2021-05-03 12:32
@christian-bromann This is also an issue for my team. Given we run multiple test files per job, I'm not sure setting the name to the capabilities name would help - at least how we define them. Seems like using the initial describe block would be better. Doesn't that tend to provide the right context?

I am happy to do some work here, but want to make sure we have a good solution for the majority use case (not sure if we fall into that).

**Comment by christian-bromann** [comment] 2021-05-03 13:58
> Seems like using the initial describe block would be better.

This is the current behavior, right?

So if I understand the issue correctly the user wants to define the name of the job through their capabilities rather than having the service define it. This is a totally legit request. So in the `@wdio/browserstack-service` we have to add an if statement to not update the job name if a name is set within the capabilities.

**Comment by gabezeck** [comment] 2021-05-03 14:43
> > Seems like using the initial describe block would be better.
> 
> This is the current behavior, right?
> 
> So if I understand the issue correctly the user wants to define the name of the job through their capabilities rather than having the service define it. This is a totally legit request. So in the `@wdio/browserstack-service` we have to add an if statement to not update the job name if a name is set within the capabilities.

This might be my misunderstanding of the ask. I am referring to updates to the session name, not the build name. In our experience, the session name is updated to the currently running test, so ends up with the name of the last test block in the file.

[Screenshot](https://share.getcloudapp.com/rRuGB0zW)

If mine is a different ask and makes sense as one, I can open a new issue and work on a solution there.

**Comment by christian-bromann** [comment] 2021-05-03 14:50
@gabezeck can you share the structure of your test?

The BS service should takes the first `describe` block and apply the name of the test to it. Could be that we are talking about a different issue here.

**Comment by gabezeck** [comment] 2021-05-03 14:53
Here is an example of test structure with the inner-code removed:
```
describe('Global sign in - V6', () => {
  beforeEach(async () => {})

  describe('Given a user that belongs to a single v6 personal team', () => {
    describe('and the user sign in via global sign in', () => {
      beforeEach(async () => {})
      it('should send the user to their v6 personal team', async () => { })
    })
  })

  describe('Given a user that belongs to multiple teams, including at least one v6 team', () => {
    describe('and the user signs in via global sign in', () => {
      beforeEach(async () => {})

      it('should show the user the expected number of teams', async () => {})

      describe('and the user selects their v6 enterprise from the list', () => {
        beforeEach(async () => {})

        it('should redirect the user to the v6 team\'s home page', async () => {})
      })
    })
  })
})
```

**Comment by gabezeck** [comment] 2021-05-14 12:20
@christian-bromann Just wanted to bump this. Please see the above. 

I thought this might be the culprit:
https://github.com/webdriverio/webdriverio/blob/d67012b87b48724157f2e6ac403f9b5a9e784299/packages/wdio-browserstack-service/src/service.ts#L87

**Comment by christian-bromann** [comment] 2021-05-14 12:21
@gabezeck please get involved if you want to see a fix for this (see `help wanted` label 😉 )

**Comment by gabezeck** [comment] 2021-05-14 18:13
@christian-bromann More than happy to throw my hat in the ring, was just responding to your question above. I can try to carve out some time :)

**Comment by sbley** [comment] 2021-07-23 14:25
In my setup, I see that the wdio-browserstack-service updates the session name to the _name of the last executed test_ whereas it should set the session name to the description of the describe block.
The current behaviour has two drawbacks: First, sessions are hard to find in the BrowserStack Dashboard. And second, the (unneeded) requests to the BrowserStack API slow down execution times drastically (in my setup ~30-40%).

Is there any reason for the current behavior? Does setting the session name to the recently executed test make sense in some scenario I did not think of yet?

**Comment by christian-bromann** [comment] 2021-07-23 15:33
@sbley can you show an example test?

I believe this is caused by having a test file like this:

```js
describe("foo", () => {
  // ...
})

describe("bar", () => {
  // ...
})
``` 
while it actually is suppose to be like this:
```js
describe("foo", () => {
   describe("bar", () => {
      // ...
   })
})
```

**Comment by sbley** [comment] 2021-07-25 20:23
Example file ([full repo here](https://github.com/sbley/wdio-bs-6777)):
```ts
describe('webdriver.io', () => {
  it('should have a subtitle', () => {
    browser.url('https://webdriver.io');
    expect($('.hero__subtitle')).toHaveTextContaining('automation test framework');
  });

  it('should have a logo', () => {
    browser.url('https://webdriver.io');
    expect($('.navbar__logo')).toBeDisplayed();
  });
})
```

The session gets the name of the last test:
![image](https://user-images.githubusercontent.com/686538/126912339-11bb1ce5-3f4b-4e0e-afb1-82f02a08e1c5.png)
Whereas I would expect the session name to be _webdriver.io_.

**Comment by christian-bromann** [comment] 2021-07-28 10:57
@sbley I see, are you up to give us a hand with this? This doesn't happen with `@wdio/sauce-service` so I believe we should just adapt the implementation from that service.

**Comment by sbley** [comment] 2021-07-28 11:27
So in terms of requirements: What we want is to set the session name equal to the outer describe. This will be done once. We do not change the session name during the lifecycle, e.g. before or after each test.

Do you agree?

**Comment by christian-bromann** [comment] 2021-07-28 11:45
> What we want is to set the session name equal to the outer describe.

This is how the Sauce service does it as well. I agree with this idea.

**Comment by sbley** [comment] 2021-07-28 12:26
OK, I'll try to free up some time for this.

**Comment by sbley** [comment] 2021-07-28 13:48
Looking into the sauce-service, it seems there is still no solution for nested describes ([your comment](https://github.com/webdriverio/webdriverio/issues/6777#issuecomment-885722511)). And actually, I do not see a way to get hold of the outer describe name. 
A test provides only the description (e.g. _"should have a logo_") and the full name including all describes in the hierarchy (e.g. _"webdriver.io headerbar should have a logo_"). You can't tell that _webdriver.io_ and _headerbar_ are nested describes.

**Comment by christian-bromann** [comment] 2021-07-28 14:03
It seems that the Sauce service stores a [`isJobNameSet`](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-sauce-service/src/service.ts#L93-L95) flag to ensure only the first suite will be reported. The `suiteTitle` is captured in [`beforeSuite`](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-sauce-service/src/service.ts#L74) which the BS service is not using. So this hook should give you the outer describe name.

**Comment by sbley** [comment] 2021-07-28 14:38
The `suiteTitle` in `beforeSuite` is always set to `"Jasmine__TopLevel__Suite"` in the hook, so I can't use it. Anyways, I managed to extract the outer (or most parent) describe by string comparison of the test descriptions.
I'll try to create a pull request and add some tests soon.

**Closed** 2021-08-09 11:24 UTC
Labels: Bug🐛, help wanted, good first pick
