### ISSUE TITLE
[🐛 Bug]: WebdriverIo Brower.url is not working with Nodejs Version > 12.8.0

### ISSUE THREAD

**Issue by sachin-agarwal-by** [webdriverio/webdriverio#7912] opened 2022-01-13 12:11 UTC
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

16.13.2

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{ browser Name: Chrome}
```

### What happened?

While using the webdriverio if we uses below line of code then browser is not launching with the provided url its working fine if we have nodejs version < 12.8.0

```
public open(path: string): void {
        this._path = path;
        browser.url(path); // in this line of code browser is not launching with provided path, because of that rest of line of code is failing.
    }
```

![image](https://user-images.githubusercontent.com/69183793/149327062-420ac913-d817-42a8-ba2c-9aa3f32845fe.png)

### What is your expected behavior?

browser.url(path) should launch the browser with given path as it works with lower nodejs version.

### How to reproduce the bug.

Test.feature

```
Feature: Login Test
    Background: LoginToAPP
        Given I Browse WebApp
            And I Login to App
```
            
Login.ts
```
import HomePage from './page';

class Homepage extends HomePage {

    fh: frameworkhelpers = new frameworkhelpers();
    get login() {
        return $('//*[@id="Username"]');
    }
    get pwd() {
        return $('//*[@id="Password"]');
    }
    get email() {
        return $('//*[@type="email"]');
    }
    get next() {
        return $('//*[@type="submit"]');
    }


    open() {
        browser.reloadSession();
        super.open(this.fh.ExtractJsonData("login", "AppURL")); 
        browser.execute(() => sessionStorage.clear());
        browser.execute(() => localStorage.clear());
    }
    loginToAPP() {
        browser.pause(7000);
        this.email.clearValue();
        this.email.waitForEnabled(30000);
        this.email.setValue(this.fh.ExtractJsonData("login", "email"));
        this.next.click();
    }
}

export default new Homepage();
```

page.ts
```
const fetch = require('node-fetch');
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

export default abstract class HomePage {
    private _path: string;

    public open(path: string): void {
        this._path = path;
        browser.url(path);
    }
}
```

### Relevant log output

```typescript
Browser is not launching with the given path.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2022-01-13 13:59
Duplicate of https://github.com/webdriverio/webdriverio/discussions/7914

**Closed by christian-bromann** 2022-01-13 13:59 UTC
Labels: Bug 🐛, Needs Triaging ⏳
