### ISSUE TITLE
Possible EventEmitter memory leak

### ISSUE THREAD

**Issue by pi4r0n** [webdriverio/webdriverio#1347] opened 2016-05-27 07:18 UTC
## The problem

When executing my test I got this warning message. @christian-bromann  asked to log it as an issue so we can track it.

> [09:56:56] Finished 'test:desktop' after 5.42 min
> [09:56:56] Starting 'run_loop'...
> [09:56:56] Starting 'test:desktop'...
> [09:56:56] Finished 'run_loop' after 1.17 ms
> (node) warning: possible EventEmitter memory leak detected. 21 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit.
> Trace
>     at process.addListener (events.js:179:15)
>     at process.on.process.addListener (node.js:668:26)
>     at Launcher.run$ (D:\01_PBS\GIT\WebClient\WebDriverIOTesting\node_modules\webdriverio\build\lib\launcher.js:281:33)
>     at tryCatch (D:\01_PBS\GIT\WebClient\WebDriverIOTesting\node_modules\webdriverio\node_modules\babel-runtime\regenerator\runtime.js:72:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke](D:01_PBSGITWebClientWebDriverIOTestingnode_moduleswebdriverionode_modulesbabel-runtimeregeneratorruntime.js:334:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next](D:01_PBSGITWebClientWebDriverIOTestingnode_moduleswebdriverionode_modulesbabel-runtimeregeneratorruntime.js:105:21)
>     at tryCatch (D:\01_PBS\GIT\WebClient\WebDriverIOTesting\node_modules\webdriverio\node_modules\babel-runtime\regenerator\runtime.js:72:40)
>     at invoke (D:\01_PBS\GIT\WebClient\WebDriverIOTesting\node_modules\webdriverio\node_modules\babel-runtime\regenerator\runtime.js:146:20)
>     at D:\01_PBS\GIT\WebClient\WebDriverIOTesting\node_modules\webdriverio\node_modules\babel-runtime\regenerator\runtime.js:154:13
>     at run (D:\01_PBS\GIT\WebClient\WebDriverIOTesting\node_modules\webdriverio\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.promise.js:104:47)
## Environment
- WebdriverIO version: 4.0.7
- Node.js version: v0.12.7
- wdio testrunner / Mocha
- Running synchronous

> "devDependencies": {
>     "gulp": "~3.9.0",
>     "gulp-typescript": "^2.10.0",
>     "gulp-webdriver": "^2.0.1",
>     "wdio-junit-reporter": "^0.0.2",
>     "wdio-dot-reporter": "^0.0.5",
>     "wdio-mocha-framework": "^0.2.12",
>     "typescript": "1.7.3",
>     "tsd": "~0.6.5",
>     "async": "~1.5.0",
>     "bcrypt": "^0.8.5",
>     "del": "1.2.x",
>     "mongodb": "~2.0.46",
>     "run-sequence": "^1.1.5",
>     "should": "~7.1.0",
>     "soap": "^0.11.4",
>     "faker": "^3.1.0"
>   },
## Details

Its really really hard to reproduce, but I managed to get some selenium logs this time.
## Link to Selenium/WebdriverIO logs

**selenium_hub_logs**
https://gist.github.com/pi4r0n/5872c95212adc55a47a1efb219e2a5ea

**selenium_node_logs**
https://gist.github.com/pi4r0n/ef4cd09e834be3a24e4fd751eb0da259

**Comment by jbhelfrich** [comment] 2016-06-04 00:30
Can you post the test code?

**Comment by christian-bromann** [comment] 2017-11-06 01:00
Closing due to missing reproducible example

**Closed by christian-bromann** 2017-11-06 01:00 UTC
Labels: Bug, Needs Investigation
