### ISSUE TITLE
end() or endAll() not deleting the server session in Phantomjs

### ISSUE THREAD

**Issue by byteshiva** [webdriverio/webdriverio#409] opened 2015-02-02 17:28 UTC
I noticed in selenium-standalone, the end() methods works as expected but 
the same end() method is not clearing up session in phantomjs server 1.9.8.

Try login to any site 
ex; 
```
At Server 
 
$phantomjs --webdriver=4444

app.js
client.url("www.example").setValue("#user","<username>").setValue("#passwd","password").click("#submitButtonid").end();

Step 1: $ node app.js

```

Repeat Step 1 multiple times, the second app.js execution will throw error because the phantomjs did`nt clean the last server session.

Workaround: Close the phantonjs and run it again.

**Comment by christian-bromann** [comment] 2015-02-04 00:16
Wasn't really able to reproduce this, I tried running this script:

```js
var client = require('webdriverio').remote({
    desiredCapabilities: {
        browserName: 'phantomjs'
    }
});

client.init()
    .url('http://google.com')
    .pause(10000)
    .sessions(function(err, sessions) {
        console.log(1, sessions);
    })
    .end()
    .sessions(function(err, sessions) {
        console.log(2, sessions);
    });
```

and it returned as expected with the following stdout:

```js
1 {
    sessionId: null,
    status: 0,
    value: [{
        id: '5faf3ef0-ac02-11e4-bc6e-bde98936e336',
        capabilities: [Object]
    }]
}
2 {
    sessionId: null,
    status: 0,
    value: []
}
```

I have phantomjs `v1.9.7`. __Note__ that your phantomjs server will be still running after that test. There is no reason to startup and shut down phantom every-time when running a test. You can configure it that way though.

**Comment by byteshiva** [comment] 2015-02-04 04:11
@christian-bromann I'm able to reproduce the error with different script.

Repeat Step 1 multiple times, In the second run you will see the error.

``` Step 1: node  app.js ```


app.js
```

var client = require('webdriverio').remote({
  desiredCapabilities: {
    browserName: 'phantomjs'
  }
});

client.init()
.url('http://gmail.com')
.pause(10000)
.saveScreenshot("./GmailBeforeLoginSnapShot.png", function(err,screenshot, res){
  console.log(err);
})
.setValue("#Email","<add your gmail email id>")
.setValue("#Passwd","<add your gmail password>")
.click("#signIn")
.pause(5000)
.saveScreenshot("./GmailAfterLoginSnapShot.png", function(err,screenshot, res){
  console.log(err);
})
.sessions(function(err, sessions) {
  console.log(1, sessions);
})
.endAll()
.sessions(function(err, sessions) {
  console.log(2, sessions);
});

```

Error occurred with second run of Step 1:
```
..\node_modules\web
driverio\lib\utils\PromiseHandler.js:154
                throw error;
                      ^
NoSuchElement: NoSuchElement
     Problem: An element could not be located on the page using the given search
 parameters.←[1;30m

     Callstack:
     -> setValue("#Email","<your gmail id>")

```

**Comment by christian-bromann** [comment] 2015-02-16 14:44
@byteshiva I can't really reproduce this. I tried running that script multiple times and it always returns:

```

null
null
1 { sessionId: null,
  status: 0,
  value:
   [ { id: '3d7574c0-b5ea-11e4-89fc-5f3f2b24a34c',
       capabilities: [Object] } ] }
2 { sessionId: null, status: 0, value: [] }
```

Is this still a problem for you?

**Comment by byteshiva** [comment] 2015-02-17 17:39
@christian-bromann  let me retest it again and get back back to you with result. Please be noted that I will be testing the script in Windows 7 Starter and Ubuntu in Netbook Machine 32 bit machine.

**Comment by byteshiva** [comment] 2015-02-17 18:19
@christian-bromann  I'm getting the same error, Please check the entered gmail username/password, maybe its incorrect/invalid. 

In the below script replace the username/password section and execute again.
```text
<add your gmail email id >  = replace with your gmail id 
<add your gmail password> =  valid password 
```
app.js
```javascript 
var client = require('webdriverio').remote({
  desiredCapabilities: {
    browserName: 'phantomjs'
  }
});

client.init()
.url('http://gmail.com')
.pause(10000)
.saveScreenshot("./GmailBeforeLoginSnapShot.png", function(err,screenshot, res){
  console.log(err);
})
.setValue("#Email","<add your gmail email id>")
.setValue("#Passwd","<add your gmail password>")
.click("#signIn")
.pause(5000)
.saveScreenshot("./GmailAfterLoginSnapShot.png", function(err,screenshot, res){
  console.log(err);
})
.sessions(function(err, sessions) {
  console.log(1, sessions);
})
.endAll()
.sessions(function(err, sessions) {
  console.log(2, sessions);
});
```
PFA
![image](https://cloud.githubusercontent.com/assets/10637299/6234191/c52480fe-b6fe-11e4-9663-6a2b683a4f86.png)

**Comment by christian-bromann** [comment] 2015-02-17 18:33
@byteshiva __Are you logged in after running the first time?__ If so I could imagine that PhantomJS doesn't clear the session (including cookies) properly. As you can see the Selenium session gets closed. I've 2-step auth enabled so I can't login (PhantomJS has a different local time).

**Comment by byteshiva** [comment] 2015-02-17 19:02
@christian-bromann I don't see the login form in 2nd run. What I was looking for was if phantomjs is clearing up all cookies. But the same script if run on firefox it does its job ( clears cookies ) so I see the login form again. Not in case of Phantomjs.

**Comment by christian-bromann** [comment] 2016-03-25 13:35
This seems to be a bug in PhantomJS. Closing.

**Closed by christian-bromann** 2016-03-25 13:35 UTC
Labels: Bug
