### ISSUE TITLE
WDIO-CLI: Could not find job

### ISSUE THREAD

**Issue by qvalero** [webdriverio/webdriverio#6547] opened 2021-03-04 10:34 UTC
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.0.9
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12
 - **NPM version:** 6.14.9
 - **Browser name and version:** Chrome 87
**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
When I run cucumber test with specific tags, all my feature files will be parsed to check if tags is present. If not, spec files are SKIPPED.
After upgrading to wdio7, we have the same behavior, but my job will fail before parsing all files with exception:

`/home/circleci/project/e2e_jt_tests/node_modules/@wdio/cli/build/interface.js:142
            throw new Error('Could not find job');
                  ^
Error: Could not find job
    at WDIOCLInterface.clearJob (/home/circleci/project/e2e_jt_tests/node_modules/@wdio/cli/build/interface.js:142:19)
    at WDIOCLInterface.emit (events.js:314:20)
    at WDIOCLInterface.EventEmitter.emit (domain.js:483:12)
    at Launcher.endHandler (/home/circleci/project/e2e_jt_tests/node_modules/@wdio/cli/build/launcher.js:356:28)
    at WorkerInstance.emit (events.js:314:20)
    at WorkerInstance.EventEmitter.emit (domain.js:483:12)
    at WorkerInstance._handleExit (/home/circleci/project/e2e_jt_tests/node_modules/@wdio/local-runner/build/worker.js:128:14)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)`

Tests are running on CircleCI with maxInstance 30.
Before upgrading to wdio7, no issues, tests were skipped until finding a test to run.
Now, It seems that if every executor find a skipped test, job is failing with exception. 

Issue seems to happen in interface.js file from @wdio/cli

`    clearJob({ cid, passed, retries }) {
        const job = this._jobs.get(cid);
        this._jobs.delete(cid);
        const retryAttempts = this._specFileRetries - retries;
        const retry = !passed && retries > 0;
        if (!retry) {
            this.result.finished++;
        }
        if (job && job.hasTests === false) {
            return this.onSpecSkip(cid, job);
        }
        if (!job) {
            throw new Error('Could not find job');
        }`
        
I don't have a local project to reproduce as it only happens with parallel execution on the CI :/ But I was wondering if the part of code is new on wdio7? And how should we interpret it ? 

This is my cucumberOpts to run my tests:

`    cucumberOpts: {
        require: ['src/step-definitions/**/*.js'], // <string[]> (file/dir) require files before executing features
        backtrace: false,   // <boolean> show full backtrace for errors
        compiler: [],       // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
        dryRun: false,      // <boolean> invoke formatters without executing steps
        failFast: false,    // <boolean> abort the run on first failure
        format: ['pretty'], // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
        colors: true,       // <boolean> disable colors in formatter output
        snippets: true,     // <boolean> hide step definition snippets for pending steps
        source: true,       // <boolean> hide source uris
        profile: [],        // <string[]> (name) specify the profile to use
        strict: false,      // <boolean> fail if there are any undefined or pending steps
        tagExpression: CUCUMBER_TAGS
            ? `(${DEFAULT_CUCUMBER_TAGS}) and (${CUCUMBER_TAGS})`
            : DEFAULT_CUCUMBER_TAGS,  // <string> (expression)
        // only execute the features or scenarios with tags matching the expression
        timeout: CUCUMBER_STEPS_TIMEOUT,     // <number> timeout for step definitions
        ignoreUndefinedDefinitions: false, // <boolean> Enable this config to treat undefined definitions as warnings.
        scenarioLevelReporter: false, // Enable this to make webdriver.io behave as if scenarios and not steps were the tests.
    },`

**Comment by christian-bromann** [comment] 2021-03-04 10:38
@qvalero thanks for filing the issue, can you provide a minimal reproducible example?

**Comment by qvalero** [comment] 2021-03-05 09:38
Hi @christian-bromann I don't have anything to reproduce locally, and I couldn't reproduce locally.
I found a "workaround" for this issue. My issue was reproducible only on our CI with a lot of maxInstances (30 actually)
I decreased the number of maxInstances to 25 and issue is not reproducible anymore.

I can't explain why :/ and I can't reproduce locally. 
If anyone else encountered the same issue in a different context I would be glad to hear it, but now my issue is "solved"

**Comment by christian-bromann** [comment] 2021-03-05 13:18
I will close the issue then. While I believe this could be indeed a bug, it is impossible to work on this without something at hand. If anyone can reproduce something, please let us know. Cheers!

**Closed by christian-bromann** 2021-03-05 13:18 UTC
Labels: Reproducible Example Missing

**Comment by ericlanteigne-quest** [comment] 2021-03-22 21:27
Hi @christian-bromann, the team I work on has been able to reproduce this issue in our pipelines as well as locally. 
`D:\Sources\ondemand-ui-e2e-devops\node_modules\@wdio\cli\build\interface.js:142
            throw new Error('Could not find job');
                  ^
Error: Could not find job
    at WDIOCLInterface.clearJob (D:\Sources\ondemand-ui-e2e-devops\node_modules\@wdio\cli\build\interface.js:142:19)
    at WDIOCLInterface.emit (events.js:311:20)
    at WDIOCLInterface.EventEmitter.emit (domain.js:482:12)
    at Launcher.endHandler (D:\Sources\ondemand-ui-e2e-devops\node_modules\@wdio\cli\build\launcher.js:356:28)
    at WorkerInstance.emit (events.js:311:20)
    at WorkerInstance.EventEmitter.emit (domain.js:482:12)
    at WorkerInstance._handleExit (D:\Sources\ondemand-ui-e2e-devops\node_modules\@wdio\local-runner\build\worker.js:128:14)
    at ChildProcess.emit (events.js:311:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)`

We have investigated it and we found that there is one package that changed today that seems to be causing the issue. 
https://www.npmjs.com/package/@cucumber/messages

We used the package-lock.json from our previous build to confirm the issue went away when using the older sub-module. 
Failed:
`@wdio/cucumber-framework@7.0.7
...
| | +-- @cucumber/messages@14.1.1 deduped`
Working:
`@wdio/cucumber-framework@7.0.7
...
| | +-- @cucumber/messages@14.0.1 deduped`

**Comment by christian-bromann** [comment] 2021-03-22 21:29
@osmolyar has also mentioned that in the Gitter channel. She is creating an issue for it. We can release a fix for it tomorrow.

**Comment by osmolyar** [comment] 2021-03-22 21:48
https://github.com/webdriverio/webdriverio/issues/6616

**Comment by christian-bromann** [comment] 2022-03-31 16:27
@rejieshr this is a pretty old issue, please update all your WebdriverIO dependencies and retry.
