### ISSUE TITLE
Iframe actions do not work in Safari, edge and firefox

### ISSUE THREAD

**Issue by rangini1234** [webdriverio/webdriverio#3966] opened 2019-05-12 23:02 UTC
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.8.3
 - **Mode:**WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:**  11.11.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** firefox, safari, edge (latest versions)
 - **Platform name and version:** Windows and Mac

**Config of WebdriverIO**

```js
exports.config = {

    capabilities: {
        myChromeBrowser: {
            capabilities: {
                browserName: 'chrome',
                  resolution: '1280x1024',
            },
        },
        myFirefoxBrowser: {
            capabilities: {
                browserName: 'firefox',
            },
        },
        edgeBrowser: {
            capabilities: {
                browserName: 'edge',
            },
        },
        ie: {
            capabilities: {
                browserName: 'ie',
            },
        },
        safari: {
            capabilities: {
                browserName: 'safari',
            },
        },

    },
    services: ['selenium-standalone'],
    seleniumInstallArgs: { version: '3.4.0' },
    seleniumArgs: { version: '3.4.0' },
    framework: 'jasmine',
    jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 300000,
    },
    waitforTimeout: 10000,

};
```

**Describe the bug**
Iframes actions fail when we try in browsers like safari (`no such frame: A frame reference could not be resolved`), edge (error: `no such frame: The specified frame was not found in the current frame or window`), firefox(error: unable to click on a button inside the iframe in firefox). 
**To Reproduce**

```js
describe('iframe::', () => {

        it('complete iframe', () => {

            browser.url('https://www.softwareadvice.com/crm/real-estate-crm-comparison/?automated=true');

            const n1 = $$('.product-scores-label.xsmall');
            const numberOfButtons = n1.length;
            for (let i = 0; i < numberOfButtons; i++) {
                n1[i].click();
                if ($$('.product-card-buttons button[data-path*="type=demo"]')[0].isDisplayed()) {
                    $$('.product-card-buttons button[data-path*="type=demo"]')[0].click();
                    break;
                }
            }

            browser.switchToFrame($('#lightbox_reveal_iframe'));
            const companyName = '#$atestconv_hidden ';
            $('#company').setValue(companyName);
            $('#segment>option:nth-child(2)').click();
            $('#size>option:nth-child(2)').click();
            const continueButton = $$('.continue.button.expand');
            const numberOfButtons1 = continueButton.length;
            for (let i = 0; i < numberOfButtons1; i++) {
                if (continueButton[i].isDisplayed()) {
                    continueButton[i].click();
                    break;
                }
            }
            $('#firstname').setValue('first');
            $('#lastname').setValue('last');
            $('#email').setValue('test@test123.com');
            $('#step2 form #phone').setValue('5125678901');
            const step2Button =    $$('button[type=\'submit\']');
            const numberOfButtons2 =    step2Button.length;
            for (let i = 0; i < numberOfButtons2; i++) {
                if (   step2Button[i].isDisplayed()) {
                    const step2Btn =    step2Button[i];
                    step2Btn.click();
                    break;
                }
            }
            browser.pause(3000);

        });
});

```
**Expected behavior**
Same code works perfectly in chrome and ie. Other browsers too, the same behavior is expected.

**Comment by wswebcreation** [comment] 2019-05-13 04:46
@rangini1234

1. Why are you using multi remote?
2. Are you using a cloud provider?
3. Which versions of the browsers show this behavior and which version of Chrome does NOT have this behaviour?

Based on the browsers that do not work I would expect it to be an issue with W3C capabilities, but by providing more info based on the points above we can tell more

**Comment by rangini1234** [comment] 2019-05-13 14:00
1. I just set the capabilities here for multi-remote as example. Our code calls only one browser capability at a time. 
2. Yes - saucelabs
3. chrome 74 works right. Edge -version 11 and Safari version 12

**Comment by wswebcreation** [comment] 2019-05-13 16:58
@rangini1234 

One last check, did you provide all the Sauce Labs W3C options? Can you also provide them?

**Comment by rangini1234** [comment] 2019-05-13 17:07
safari: {
      
        browserName: 'safari',
        maxDuration: '1800',
        screenResolution: '1600x1200',
        version: '12.0',
    },

 microsoftEdge: {
        browserName: 'MicrosoftEdge',
        version: '18',
        screenResolution: '1920x1080',
        seleniumVersion: '3.141.59',
}
 This is what I have in capabilities

**Comment by wswebcreation** [comment] 2019-05-13 17:49
For using the W3C specs in a proper way in Sauce Labs you . need to provide the proper capabilities, see their documentation [here](https://wiki.saucelabs.com/display/DOCS/Selenium+W3C+Capabilities+Support+-+Beta) and [this comment](https://github.com/webdriverio/webdriverio/issues/3878#issuecomment-487841905) for an example, please be sure that you added all capabilities like in the documentation

If that is done please check if the issues still appear

**Comment by rangini1234** [comment] 2019-05-14 21:20
Changed browser capabilities using W3C specs in saucelabs and the issues **still appear**.

**Comment by wswebcreation** [comment] 2019-05-15 17:00
@rangini1234 

Sorry for the late response, I'm trying your script now to debug the issue, but it's not working, can you check your script again and provide a working example 

```js
const numberOfButtons = n1.length;
        for (let i = 0; i < numberOfButtons; i++) {
            n1[ i ].click();
            if ($$('.product-card-buttons button[data-path*="type=demo"]')[ 0 ].isDisplayed()) {
                $$('.product-card-buttons button[data-path*="type=demo"]')[ 0 ].click();
                break;
            }
        }
```

The above part is not working

**Comment by anandhaprakash04** [comment] 2019-05-21 01:05
Hi @wswebcreation 

I have updated the spec file as below and it runs fine on chrome. Please check and let me know if you need any additional info

`describe('iframe::', () => {

        it('complete iframe', ()=>{

            browser.url('https://www.softwareadvice.com/crm/real-estate-crm-comparison/?automated=true');
            const priceBtns = $$('button[data-path*="quote"]');
            // priceBtns[0].moveTo();
            priceBtns[0].click();
            browser.switchToFrame('lightbox_reveal_iframe');

            const companyName = '#$atestconv_hidden test';
            $('#company').setValue(companyName);
            $('#segment>option:nth-child(2)').click();
            $('#size>option:nth-child(2)').click();
            const continueButton = $$('.continue.button.expand');;
            const numberOfButtons1 = continueButton.length;
            for (let i = 0; i < numberOfButtons1; i++) {
                if (continueButton[i].isDisplayed()) {
                    continueButton[i].click();
                    break;
                }
            }

            $('#firstname').setValue('first');
            $('#lastname').setValue('last')
            $('#email').setValue('test@test123.com');
            $('#step2 form #phone').setValue('5125678901');
            const step2Button =    $$('.submit_conversion.button');
            const numberOfButtons2 =    step2Button.length;
            console.log('## no of buttons : ' + numberOfButtons2);
            for (let j = 0; j < numberOfButtons2; j++) {
                if(step2Button[j].isDisplayed())
                {
                    step2Button[j].click();
                    break;
                }
            }
            browser.pause(3000);
        });
});`

**Comment by wswebcreation** [comment] 2019-05-21 06:10
@anandhaprakash04 

This line of code `const priceBtns = $$('button[data-path*="quote"]');` doesn't give a result back when I run the script, doesn't matter if I run it locally or in the cloud. 

Can you please provide a working example, without a working example I can't check it and will need to close the issue

**Comment by rangini1234** [comment] 2019-05-21 14:40
@wswebcreation -> can you try cloning this repo: https://github.com/rangini1234/webdriverio-angular
(The readme has the steps we followed to run it). Please let me knoe if you are able to run now

**Comment by wswebcreation** [comment] 2019-05-22 06:51
@rangini1234 and @anandhaprakash04 

Thanks for the repo, but as said above, the script doesn't work because 

> This line of code const priceBtns = $$('button[data-path*="quote"]'); doesn't give a result back when I run the script, doesn't matter if I run it locally or in the cloud.

When I do a search in the url I don't get back those elements, there is also no `data-path` attribute in the source.

Please provide a working example

**Comment by rangini1234** [comment] 2019-05-22 17:25
@wswebcreation - is it possible for you to trigger this test using a US Geoip. It works differently otherwise.

**Comment by wswebcreation** [comment] 2019-05-23 06:18
@rangini1234 

I've been able to verify this in the Sauce Labs US cloud. This is not an issue in WebdriverIO but a scripting issue. 

The issue is here 

```js
        const continueButton = $$('.continue.button.expand');
        const numberOfButtons1 = continueButton.length;
        for (let i = 0; i < numberOfButtons1; i++) {
            if (continueButton[ i ].isDisplayed()) {
                continueButton[ i ].click();
                break;
            }
        }
```
This works for ChromeDriver, but not for the Firefox and SafariDriver. You need to find a better way to select the element here (like we discussed during SauceCon).

I'm, going to close the issue now because it's not Sauce related

**Closed by wswebcreation** 2019-05-23 06:18 UTC
