### ISSUE TITLE
Unhandled promise rejection "cannot read property '_id' of null" in devtools-service

### ISSUE THREAD

**Issue by mike-d-davydov** [webdriverio/webdriverio#5785] opened 2020-09-01 13:45 UTC
**Environment:**
 - **WebdriverIO version:** 6.4.0
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.21
 - **NPM version:** :6.14.4
 - **Browser name and version:** Chrome 84
 - **Platform name and version:** Docker container (RHEL7)
 - **Additional wdio packages used (if applicable):** @wdio/devtools-service

**Config of WebdriverIO**

Framework: jasmine
Services: devtools-service (6.4.3) , selenium-standalone

**Describe the bug**

Occasionally, when navigating to page, following error is reported to console (and results in test failure):

"Caught unhandled rejection: Error Message: Cannot read property '_id' of null | Error Stack: TypeError: Cannot read property '_id' of null 
   at TraceGatherer,onFrameLoadFail([...]@wdio/devtools-service/build/gatherer/trace.js:135:41)

Please see https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-devtools-service/src/gatherer/trace.js#L190

**To Reproduce**

No minimal reproduction example just as yet.

**Expected behavior**

No exception above during test execution.

**Comment by christian-bromann** [comment] 2020-09-01 15:19
> No minimal reproduction example just as yet.

Such an example is required to understand the full context of this problem. I think it is impossible to apply any fixes or investigate here without that.

**Comment by mike-d-davydov** [comment] 2020-09-01 15:33
@christian-bromann if you look at the source code, there is a clear missing null check. I was planning to fix this myself  - it requires a one-liner change (I was planning to validate the fix locally by making changes directly in node_modules). Problems with creating minimum reproduction scenario are:
  - It is only reproducible with Chrome 84 on our Linux docker containers
  - It only reproduces with our particular application that we are testing

However, I saw exactly same issue mentioned on Gitter (https://gitter.im/webdriverio/webdriverio?at=5ed7c27cf0b8a2053ad02821), which shows clearly that it's not problem unique to our setup.

**Comment by mgrybyk** [comment] 2020-09-01 16:37
It would be great to understand why the page is null. Is it missing? Maybe frame has some special type?

**Comment by mike-d-davydov** [comment] 2020-09-01 16:57
@mgrybyk, my understanding that this only happens during navigations. Unfortunately, I can't provide logs because company policy prohibits sharing anything from corporate network.  From the other hand in a handler for "onFramewFailedToLoad" you actually may anticipate that frame in the request is null, I guess. I will try to collect more info.

**Comment by romovs** [comment] 2020-09-03 13:07
We also experiencing this issue. Seems to happen consistently during navigation in a number of places in Salesforce Lightning. Chrome 85. WDIO 6.4.2.
Unfortunately it's not possible to provide a reproducible example since the system is on a corporate network.

**Comment by christian-bromann** [comment] 2020-09-15 08:32
@mike-d-davydov any updates?

**Comment by mike-d-davydov** [comment] 2020-09-15 14:11
@christian-bromann , we end up simply suppressing unhandled rejections by removing listeners in NodeJS for them. I know it's a very crude work-around, but it works. WDIO6 migration is giving us a real lot of headache, so had to postpone investigating this issue for now.

**Comment by kwokfu** [comment] 2020-11-09 06:21
We are experiencing the same consistent behaviour here with Chrome 86, WDIO 6.7.3 with @wdio/devtools-service and devtools as automationProtocol.

Navigate to a page and wait for an element, the page redirect to another page. When debugging the trace.js, saw a few null frame.

**Comment by christian-bromann** [comment] 2020-11-09 09:43
@kwokfu can you provide a reproducible example to help people investigate this issue?

**Comment by christian-bromann** [comment] 2020-12-10 18:14
I will close this. A reproducible example is essential here for anyone who wants to fix this bug. Until we don't have this we can't continue on the problem.

**Closed by christian-bromann** 2020-12-10 18:14 UTC
Labels: Reproducible Example Missing
