### ISSUE TITLE
Webdriverio tests are hanging on TravisCI 

### ISSUE THREAD

**Issue by ademcan** [webdriverio/webdriverio#3903] opened 2019-05-01 06:49 UTC
I am having some issues when trying to run the tests on travisCI, although everything works fine locally. 

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.7.15
 - **Mode:** WDIO with Appium
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.2.1
 - **NPM version:** 5.6.0
 - **Browser name and version:** React Native
 - **Platform name and version:** MacOS 10.13.6
 - **Additional wdio packages used (if applicable):** @wdio/appium-service, @wdio/cli, @wdio/jasmine-framework, @wdio/local-runner, @wdio/spec-reporter, @wdio/sync

**Config of WebdriverIO**
I configured wdio as follow (one shared conf and one ios conf file): 
https://github.com/ademcan/react-native-elastos-wallet-core-demo/tree/master/config

**Describe the bug**
I developed a React Native app and prepared some tests using wdio and Appium. The tests run fine locally with the "./node_modules/.bin/wdio config/wdio.ios.app.conf.js" command. However, when I try to run the exact same command on travisCI, the test command hangs for several minutes and I have to stop it (it ran for more than 15 minutes once). The travis.yml file is https://github.com/ademcan/react-native-elastos-wallet-core-demo/blob/master/.travis.yml and the simple test https://github.com/ademcan/react-native-elastos-wallet-core-demo/blob/master/test/specs/native.js

**To Reproduce**
By cloning the https://github.com/ademcan/react-native-elastos-wallet-core-demo repository and configuring travis to automatically run CI should allow you to reproduce the issue.

**Expected behavior**
The test command should succeed and travisCI ends without errors!

**Log**
The log when run locally: https://gist.github.com/ademcan/daf8f48b21104305fb73a44d5af20305
The log from travisCI: https://gist.github.com/ademcan/d1ff602d757b3c3afb9fff55b580972b

**Additional context**

Thank you very much for the hard work you are putting on such a project, and for your time 👍

**Comment by ademcan** [comment] 2019-05-10 09:41
Thank you @mgrybyk.
I managed to get the tests running on Travis, but now it is failing with the following error:
"ERROR @wdio/runner: Error: connect ECONNREFUSED 127.0.0.1:4723"
I am starting Appium in the background before running the tests, and even played with the "host" parameter (tried localhost and 0:0:0:0) in the wdio.shared.conf.js file but still the same error appears.
Thank you very much for your help.

**Comment by christian-bromann** [comment] 2019-05-10 11:36
@ademcan in v5 it is called [`hostname`](https://webdriver.io/docs/options.html#hostname). Also it seems that Appium is not started. How do you think we can help here as we can't reproduce this locally. Can you please check why Appium apparently is not running?

**Comment by ademcan** [comment] 2019-05-10 13:19
@christian-bromann thanks! Indeed I meant "hostname" sorry! I got the test running again, but they just wont stop. The wdio test runs forever without failing (on travis). Do you have any idea about what could be the issue here? 
I only have one simple test that works locally but doesn't on Travis.
<img width="1117" alt="wdio_error_travis" src="https://user-images.githubusercontent.com/1199588/57530142-e772cf00-7336-11e9-91e6-279a698536aa.png">

**Comment by wswebcreation** [comment] 2019-05-11 06:48
@ademcan 

Some things to check:
- update to the latest version, by removing your `package-lock.json` and do a `npm install` that will get you on the latest version
- remove all `async/await` from your test. WebdriverIO is `sync` and will resolve the promises for you, you can then write your test like this

```js
const checkWord = require('check-word');
const words = checkWord('en');

const getBtnElement = (name)=> $(`~btn:${name}`);

const getTxtElement = (name)=> $(`~txt:${name}`);

describe('Wallet Bridge Tests', () => {
    it('calls the GenerateMnemonic bridge', ()=>{
        getBtnElement('GenerateMnemonic').click();
        let txt = getTxtElement('Result').getText();

        console.log("TEXTMNEMONIC-.------------------------------")
        console.log(txt)
        // the bridge returns the mnemonic
        const mnemonics = txt.split(" ");
        console.log(mnemonics)
        expect(mnemonics.length).toEqual(12);
        mnemonics.forEach(element => {
            expect(words.check(element)).toEqual(true);
        });
    });
});
```

**Comment by ademcan** [comment] 2019-05-11 07:26
Thanks a lot @wswebcreation, really appreciate your help! I have removed all the async code as you mentioned and the tests are running fine locally. However, I still have the same issue on Travis (after removing the package-lock.json), the tests are just running for ever, the machine is up for more than 10 minutes now and still nothing, no failure either!
The reason I chose Travis is that the macOS machines are free there, whereas on circleCI only the linux machines seems to be free for open source projects.

**Comment by wswebcreation** [comment] 2019-05-11 07:29
Can you run the set with logLevel=debug and share the Travis logs?

**Comment by ademcan** [comment] 2019-05-11 08:10
Ok, it's running now. In the meantime the previous run finally failed (after 43 minutes) and here is the complete log: https://api.travis-ci.org/v3/job/531054955/log.txt
It looks like the simulator is not running the app properly (?).

**Comment by ademcan** [comment] 2019-05-11 08:56
and here is the log with logLevel="debug".
https://api.travis-ci.org/v3/job/531064566/log.txt

**Comment by wswebcreation** [comment] 2019-05-12 06:10
@ademcan 

Sorry for my late reaction. I just checked both logs, but I can't find the correct one with the debug in it for WebdriverIO with `logLevel='debug'` enabled, or do I need new glasses 😉

**Comment by ademcan** [comment] 2019-05-12 15:22
I thought I switched logLevel to "debug" for the second output, let me check again before buying new glasses😊 If not, I'll run it again and post the output here. Thanks!

**Comment by ademcan** [comment] 2019-05-15 13:15
@wswebcreation I gave another try with logLevel='debug' and the output is located here: https://api.travis-ci.org/v3/job/532789711/log.txt I actually think that it is the same of the previous one, so it seems that logLevel was already at 'debug'. The original wdio config file is: https://github.com/ademcan/react-native-elastos-wallet-core-demo/blob/master/config/wdio.shared.conf.js
Thanks again for your help.

**Comment by wswebcreation** [comment] 2019-05-15 16:30
Hi @ademcan 

Based on the logs it looks like Appium can't connect to the sim. To be honest, I've never used the sims on Travis and I can't figure out, based on the logs, what the problem it.

The only thing I could advice is to run the test again with providing extra Appium logs with this https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-appium-service#logpath



```log
[0-0] [90m2019-05-15T13:01:33.627Z[39m [96mINFO[39m [97mwebdriver[39m: Retrying 3/3

[90m2019-05-15T13:01:33.627Z[39m [96mINFO[39m [97mwebdriver[39m: [POST] http://localhost:4723/wd/hub/ses

sion

[0-0] [90m2019-05-15T13:01:33.627Z[39m [96mINFO[39m [97mwebdriver[39m: [33mDATA[39m { capabilities:

    { alwaysMatch:

       { automationName: 'XCUITest',

         platformName: 'iOS',

         platformVersion: '12.1',

         deviceName: 'iPhone XS',

         app: './ios/RNMainchainDemoArchive/RNMainchainDemo.ipa',

         noReset: true,

         newCommandTimeout: 50 },

      firstMatch: [ {} ] },

   desiredCapabilities:

    { automationName: 'XCUITest',

      platformName: 'iOS',

      platformVersion: '12.1',

      deviceName: 'iPhone XS',

      app: './ios/RNMainchainDemoArchive/RNMainchainDemo.ipa',

      noReset: true,

      newCommandTimeout: 50 } }



[41m[30mStderr:[39m[49m

[41m[30m[39m[49m[0-0] [90m2019-05-15T12:41:33.473Z[39m [33mWARN[39m [97mwebdriver[39m: Request failed due to socket hang

 up

[0-0] [90m2019-05-15T12:51:33.506Z[39m [33mWARN[39m [97mwebdriver[39m: Request failed due to socket hang

 up

[0-0] [90m2019-05-15T13:01:33.626Z[39m [33mWARN[39m [97mwebdriver[39m: Request failed due to socket hang

 up

[0-0] [90m2019-05-15T13:11:33.754Z[39m [31mERROR[39m [97mwebdriver[39m: Request failed due to Error: soc

ket hang up

     at createHangUpError (_http_client.js:313:15)

     at Socket.socketOnEnd (_http_client.js:416:23)

     at Socket.emit (events.js:187:15)

     at Socket.EventEmitter.emit (domain.js:442:20)

     at endReadableNT (_stream_readable.js:1090:12)

     at process._tickCallback (internal/process/next_tick.js:63:19)

[0-0] [90m2019-05-15T13:11:33.828Z[39m [31mERROR[39m [97m@wdio/runner[39m: Error: socket hang up

     at createHangUpError (_http_client.js:313:15)

     at Socket.socketOnEnd (_http_client.js:416:23)

     at Socket.emit (events.js:187:15)

     at Socket.EventEmitter.emit (domain.js:442:20)

     at endReadableNT (_stream_readable.js:1090:12)

     at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by ademcan** [comment] 2019-05-17 08:55
Ok, thank you very much Wim. 
Were the tests running successfully on circleCI with the iOS and Android simulators? If yes, I can give it a try with the free plan! As pricing was the main reason why we chose travis.

**Comment by wswebcreation** [comment] 2019-05-17 08:57
@ademcan 

No, we only used CircleCi for orchestrating the tests to a cloud vendor, we never used the Sims on there.

I'm going to close this issue now because it's not related to WebdriverIO. It's still open for discussion

**Closed by wswebcreation** 2019-05-17 08:57 UTC

**Comment by ademcan** [comment] 2019-05-17 08:59
Sure, thanks a lot again for your time and your help!
