### ISSUE TITLE
waitForExist(), waitForDisplayed(), waitForEnabled() don't work for Edge browser.

### ISSUE THREAD

**Issue by GineaPig** [webdriverio/webdriverio#3687] opened 2019-03-06 04:45 UTC
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 5.6.2]
 - **Mode:** [ WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [e.g. 8.11.2]
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name and version:** [e.g. MS Edge]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

I use element.waitForExist(), waitForDisplayed() and waitForEnabled() function in edge browser, the element actually exists  but it doesn't wait for the timeout time, and just failed with "No such element" error.

So now I cannot locate the element with waitFor funtion in edge, and if I use browser.pause(timeout) before locating the element, the element can be located, which doesn't have good performance and I prefer to use wait function.

In Chrome and FF, they work well. This issue only exist for MS Edge.

**Comment by christian-bromann** [comment] 2019-03-06 08:09
> In Chrome and FF, they work well. This issue only exist for MS Edge.

Without any logs this is impossible to investigate. Maybe the element indeed doesn't show up in Edge! Please provide a reproducible example and some logs.

**Comment by abjerstedt** [comment] 2019-03-06 15:51
@GineaPig You need to specify which edge version you are using. Edge 17 and 18 use different APIs, and Edge 18 has a known issue with the displayed() call not working (aka waitForDisplayed will spam an unknown error). 

WaitForExist works just fine in edge 18 afaik; and I'm not sure about WaitForEnabled.

**Comment by GineaPig** [comment] 2019-03-06 19:59
@christian-bromann @abjerstedt Thank you for your reply. I am using Edge 41.

When I open a new page, these functions work well if I use the browser.pause(timeout) to wait for a while and the element does show up.

The problem is that when I open a new page, I always have to use browser.pause(timeout) to wait for a while then use these functions. 

When I open a new page without browser.pause() and try to use these waitFor functions, they don't wait the timeout time I set, just wait around 10 seconds then failed with "No such Element". (Even though I can see the element on the web page.)

And also, after I use browser.pause() to wait, if the locator is correct, then they work well, if the locator is wrong, the wairFor function doesn't wait for the timeout I set, just quit in a short seconds. 

I want to use these waitFor functions to get rid of using browser.pause(), and wait until the page is completed loaded and wait util the timeout I set.

The test I am using is very easy, just open a new page(company website), and locator.waitForExist(), or other waitFor functions. 

Here are the logs:

`[MicrosoftEdge #0-0] No such element
[MicrosoftEdge #0-0] Error: No such element
[MicrosoftEdge #0-0]     at getErrorFromResponseBody (C:\test\node_modules\webdriver\build\utils.js:342:10)
[MicrosoftEdge #0-0]     at Request._callback (C:\test\node_modules\webdriver\build\request.js:116:64)
[MicrosoftEdge #0-0]     at Request.self.callback (C:\test\node_modules\request\request.js:185:22)
[MicrosoftEdge #0-0]     at Request.<anonymous> (C:\test\node_modules\request\request.js:1161:10)
[MicrosoftEdge #0-0]     at IncomingMessage.<anonymous> (C:\test\node_modules\request\request.js:1083:12)
[MicrosoftEdge #0-0]     at Browser.runCommand (C:\test\node_modules\@wdio\sync\build\wrapCommand.js:31:24)
[MicrosoftEdge #0-0]     at Browser.<anonymous> (C:\test\node_modules\@wdio\sync\build\wrapCommand.js:53:31)
[MicrosoftEdge #0-0]     at Browser.findElement (C:\test\node_modules\webdriverio\build\utils.js:355:94)
[MicrosoftEdge #0-0]     at Browser.$ (C:\test\node_modules\webdriverio\build\commands\browser\$.js:65:40)
[MicrosoftEdge #0-0]     at Browser.runCommand (C:\test\node_modules\@wdio\sync\build\wrapCommand.js:37:32)
[MicrosoftEdge #0-0]     at <anonymous>
[MicrosoftEdge #0-0]     at global.$.selector (C:\test\node_modules\@wdio\runner\build\index.js:211:36)
[MicrosoftEdge #0-0]     at Context.<anonymous> (C:\test\specs\test.js:17:13)
[MicrosoftEdge #0-0]     at Promise (C:\test\node_modules\@wdio\sync\build\index.js:58:22)
[MicrosoftEdge #0-0]     at Context.executeSync (C:\test\node_modules\@wdio\sync\build\index.js:56:10)
[MicrosoftEdge #0-0]     at C:\test\node_modules\@wdio\sync\build\index.js:202:70`

**Comment by abjerstedt** [comment] 2019-03-06 20:12
@GineaPig Edge 41 doesn't give me any info. I need to know if its 15,16,17,18.

Based on the information you provided in your followup, it sounds like i might need to update our matcher to snag edge no such found elements.

**Comment by GineaPig** [comment] 2019-03-06 20:19
@abjerstedt 
The version shows in my edge:
Microsoft Edge 41.16299.967.0
Microsoft EdgeHTML 16.16299
According to your last response, Edge 17 looks work well for all these wait functions? And should I use Edge 17? Thank you!

**Comment by abjerstedt** [comment] 2019-03-06 20:19
Edge 18 works as expected. 

I can reproduce the issue in Edge 15, 16, and 17

**Comment by GineaPig** [comment] 2019-03-06 20:24
@abjerstedt Can I use waitForDisplayed in Edge 18 by the way? Thank you!

**Comment by abjerstedt** [comment] 2019-03-06 20:26
@GineaPig No. Microsoft and Apple both decided to remove the api endpoint since it was "optional". I have a PR that should fix this when it eventually gets merged.

**Comment by GineaPig** [comment] 2019-03-06 20:29
@abjerstedt Thank you so much!

**Comment by abjerstedt** [comment] 2019-03-06 21:09
@GineaPig Once my PR goes in and we cut a release, the next version should work with edge <= 17.

**Closed** 2019-03-06 21:25 UTC
Labels: Bug🐛, good first pick
