### ISSUE TITLE
Error: listen EADDRINUSE :::5858

### ISSUE THREAD

**Issue by vasikarla** [webdriverio/webdriverio#1312] opened 2016-05-18 00:58 UTC
When you run
"node --debug-brk wdio wdio.conf.js” (node inspector running already). WebDriverIO creates two jobs and thereby showing the port is already in use.

Debugger listening on port 5858

Error: listen EADDRINUSE :::5858
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Agent.Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Agent.Server.listen (net.js:1366:5)
    at Object.start (_debug_agent.js:21:9)
    at startup (node.js:70:44)
    at node.js:968:3

The jobs showing are:

87036 ttys000    0:34.46 node /usr/local/bin/node-inspector --debug-port=5858
87048 ttys002    0:02.28 node --debug-brk wdio wdio.conf.js
87053 ttys002    0:00.07 /usr/local/bin/node --debug-brk webdriverio/build/lib/runner.js wdio.conf.js

The highlights yellow(87053) is created as a child process of the parent job 87048.

**Comment by vasikarla** [comment] 2016-05-18 00:59
@christian-bromann : please take a look at the above issue

**Comment by christian-bromann** [comment] 2016-05-18 01:02
Duplicate of #459

**Closed by christian-bromann** 2016-05-18 01:02 UTC
