### ISSUE TITLE
[🐛 Bug]: `Request failed with status 404 due to no such alert` error in test logs

### ISSUE THREAD

**Issue by Oleksii-QA** [webdriverio/webdriverio#11539] opened 2023-10-26 10:59 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.16.4

### Node.js Version

18.17.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
            maxInstances: 1,
            acceptInsecureCerts: true,
            browserName: "chrome",
            "goog:loggingPrefs": {   
                browser: "ALL",
              },
            "goog:chromeOptions": {
                args: [
                "--start-maximized",
                "--enable-logging",
                // "--headless",
                // "--no-sandbox",
                // "--disable-dev-shm-usage",
                // "--disable-gpu",
                // "--window-size=1920,1080"б
                //"--auto-open-devtools-for-tabs"
              ],
              prefs: {
                download: {
                  default_directory: join(process.cwd(), "./download") 
                }
              }
            },
    }
```

Same issue in Windows 10 and Ubuntu 20.04 LTS
Chrome Browser version 118 and 116
Reproduced in headless mode and without

### What happened?

This error is displayed in all logs. Very strange, as far as I investigated, this error is displayed in logs if use `wdio-video-reporter`. 

`wdio-video-reporter` version `4.0.5`

main config in `package.json:`

```
"devDependencies": {
    "@moroo/wdio-slack-reporter": "^8.1.0",
    "@wdio/cli": "^8.16.4",
    "@wdio/devtools-service": "^8.20.5",
    "@wdio/local-runner": "^8.16.4",
    "@wdio/mocha-framework": "^8.16.3",
    "@wdio/spec-reporter": "^8.16.3",
    "chromedriver": "^118.0.0",
    "wdio-chromedriver-service": "^8.1.1",
    "wdio-intercept-service": "^4.4.0"
  },
  "scripts": {
    "test": "wdio run ./wdio.conf.js"
  },
  "dependencies": {
    "axios": "^1.5.1",
    "moment": "^2.29.4",
    "wdio-video-reporter": "^4.0.5"
  }
```

### What is your expected behavior?

I think this error should not display in logs

### How to reproduce the bug.

Looks like reproduced if use `wdio-video-reporter`

### Relevant log output

```typescript
2023-10-26T10:21:07.074Z INFO webdriver: COMMAND getAlertText()
2023-10-26T10:21:07.075Z INFO webdriver: COMMAND findElement("css selector", "#email")
2023-10-26T10:21:07.075Z INFO webdriver: [GET] http://localhost:9515/session/46446266ddfa703bbf41c0dd687f2fcd/alert/text
2023-10-26T10:21:07.076Z INFO webdriver: [POST] http://localhost:9515/session/46446266ddfa703bbf41c0dd687f2fcd/element
2023-10-26T10:21:07.076Z INFO webdriver: DATA { using: 'css selector', value: '#email' }
2023-10-26T10:21:07.082Z WARN webdriver: Request failed with status 404 due to no such alert
  (Session info: chrome=118.0.5993.89)
2023-10-26T10:21:07.082Z INFO webdriver: Retrying 1/3
2023-10-26T10:21:07.082Z INFO webdriver: [GET] http://localhost:9515/session/46446266ddfa703bbf41c0dd687f2fcd/alert/text
2023-10-26T10:21:07.293Z INFO webdriver: RESULT {
  'element-6066-11e4-a52e-4f735466cecf': 'FFCE1E586845F09F2E6714559A7242B6_element_8'
}
2023-10-26T10:21:07.298Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
2023-10-26T10:21:07.299Z INFO webdriver: [POST] http://localhost:9515/session/46446266ddfa703bbf41c0dd687f2fcd/execute/sync
2023-10-26T10:21:07.299Z INFO webdriver: DATA {
  script: 'isElementDisplayed(...) [8007 bytes]',
  args: [
    {
      'element-6066-11e4-a52e-4f735466cecf': 'FFCE1E586845F09F2E6714559A7242B6_element_8',
      ELEMENT: 'FFCE1E586845F09F2E6714559A7242B6_element_8'
    }
  ]
}
2023-10-26T10:21:07.301Z WARN webdriver: Request failed with status 404 due to no such alert
  (Session info: chrome=118.0.5993.89)
2023-10-26T10:21:07.301Z INFO webdriver: Retrying 2/3
2023-10-26T10:21:07.301Z INFO webdriver: [GET] http://localhost:9515/session/46446266ddfa703bbf41c0dd687f2fcd/alert/text
2023-10-26T10:21:07.305Z INFO webdriver: RESULT true
2023-10-26T10:21:07.306Z INFO webdriver: COMMAND findElement("css selector", "#email")
2023-10-26T10:21:07.306Z INFO webdriver: [POST] http://localhost:9515/session/46446266ddfa703bbf41c0dd687f2fcd/element
2023-10-26T10:21:07.306Z INFO webdriver: DATA { using: 'css selector', value: '#email' }
2023-10-26T10:21:07.308Z WARN webdriver: Request failed with status 404 due to no such alert
  (Session info: chrome=118.0.5993.89)
2023-10-26T10:21:07.308Z INFO webdriver: Retrying 3/3
2023-10-26T10:21:07.308Z INFO webdriver: [GET] http://localhost:9515/session/46446266ddfa703bbf41c0dd687f2fcd/alert/text
2023-10-26T10:21:07.312Z INFO webdriver: RESULT {
  'element-6066-11e4-a52e-4f735466cecf': 'FFCE1E586845F09F2E6714559A7242B6_element_8'

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment] 2023-10-26 13:02
Duplicate of https://github.com/webdriverio-community/wdio-video-reporter/issues/110

**Closed by erwinheitzman** 2023-10-26 13:02 UTC
Labels: Bug 🐛, Needs Triaging ⏳
