### ISSUE TITLE
Custom Jasmine assertion message is not shown

### ISSUE THREAD

**Issue by wswebcreation** [webdriverio/webdriverio#4076] opened 2019-06-11 12:54 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** `5.10.1`
 - **Mode:** Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** `10.15.2`
 - **NPM version:** `6.9.0`
 - **Platform name and version:** Mac OSX + Latest brwoser
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/jasmine-framework]

**Config of WebdriverIO**
Not needed

**Describe the bug**
When I use Jasmine and I create an assertion, I'm not seeing the custom error message so the error in the console would be easy

**To Reproduce**
```js
expect($('#element-id').isDisplayed()).toEqual(false, 'My custom message');
```

**Expected behavior**
Hope to see the error custom error message

**Log**
```log
[#0-0] 1) Login should be able to login with a standard user
[#0-0] Expected true to equal false.
[#0-0] Error: Expected true to equal false.
[#0-0]     at <Jasmine>
[#0-0]     at UserContext.toEqual (/Users/wswebcreation/project/tests/specs/login.spec.js:20:43)
```

**Comment by mgrybyk** [comment] 2019-10-05 23:54
@wswebcreation can you please help reproducing it? 
Maybe the issue was fixed by some related change or I'm doing something wrong.

See
![image](https://user-images.githubusercontent.com/25589559/66262197-186b0900-e7dc-11e9-931f-b9d07500d07d.png)

**Comment by christian-bromann** [comment] 2020-06-21 20:46
Closing due to inactivity.

**Closed by christian-bromann** 2020-06-21 20:46 UTC
Labels: Bug🐛, good first pick, help wanted
