### ISSUE TITLE
How to run in remote machine using hub and node mode

### ISSUE THREAD

**Issue by byteshiva** [webdriverio/webdriverio#430] opened 2015-02-19 04:33 UTC
I'm getting this error when run on node and hub mode.  Please correct me if I'm missing something here.

```
               throw error;
                      ^
RuntimeError: RuntimeError
     (ECONNREFUSED:-1) Couldn't connect to selenium server
     Problem: Couldn't connect to selenium server←[1;30m

     Callstack:
     -> init()
```
as per phantomjs-ghostdriver implementation.
```
Launch the grid server, which listens on 4444 by default: java -jar /path/to/selenium-server-standalone-<SELENIUM VERSION>.jar -role hub
Register with the hub: phantomjs --webdriver=8080 --webdriver-selenium-grid-hub=http://127.0.0.1:4444
Now you can use your normal webdriver client with http://127.0.0.1:4444 and just request browserName: phantomjs
```

**Comment by christian-bromann** [comment] 2015-02-19 10:33
How did you start your hub server and phantomjs?

**Comment by byteshiva** [comment] 2015-02-19 11:30
To start hub 
Launch the grid server, which listens on 4444 by default: 

```
java -jar /path/to/selenium-server-standalone-<SELENIUM VERSION>.jar -role hub
``

To register node to hub
```
phantomjs --webdriver=8080 --webdriver-selenium-grid-hub=http://127.0.0.1:4444
```

**Comment by christian-bromann** [comment] 2015-02-19 11:54
@byteshiva looks good. And when you open http://localhost:4444/grid/console you see that phantomjs is connected?

**Comment by christian-bromann** [comment] 2015-02-19 11:55
Also note: v2.44 of selenium standalone server has problems running phantomjs < v2.0

**Comment by byteshiva** [comment] 2015-02-19 12:18
I see that phantomjs  is connected. Let me install phantomjs 2.0 on *nix Machine and see how it performs.

![image](https://cloud.githubusercontent.com/assets/10637299/6266393/386da0c0-b85f-11e4-9efe-af98171684af.png)

**Comment by christian-bromann** [comment] 2015-02-19 12:48
@byteshiva phantomjs is listed but not connected, see screenshot above (`Connection refused`)

**Comment by byteshiva** [comment] 2015-02-19 14:08
I see that the issue is with phantomjs 1.9.8 running on Windows 7 Starter, I don't see this issue in Ubuntu Desktop 14.04


![image](https://cloud.githubusercontent.com/assets/10637299/6267980/c8c2e626-b86e-11e4-93cc-d24fed21f183.png)

**Comment by christian-bromann** [comment] 2015-02-22 15:56
Then I guess run PhantomJS on Ubuntu when it works there. Closing this issue as it is not a bug in WebdriverIO.

**Closed by christian-bromann** 2015-02-22 15:56 UTC
