### ISSUE TITLE
browser.newWindow() not working on IE

### ISSUE THREAD

**Issue by j320** [webdriverio/webdriverio#5310] opened 2020-04-22 09:44 UTC
- **WebdriverIO version:** 6.1.12
 - **Mode:** Standalone Mode
 - **Node.js version:** [e.g. 8.11.2] 12.16.1
 - **Browser name and version:** IE11

**Config of WebdriverIO**
```
capabilities: [{
    browserName: 'internet explorer',
    "se:ieOptions": {
      ignoreZoomSetting: true,
      nativeEvents: false,
      "ie.ensureCleanSession": true
    }
  }
]
```

**Describe the bug**
Using browser.newWindow(url) on IE doesn't open a new tab nor it fails the test, it doesn't do anything but tests carry on as normal. Adding other parameters such as _windowName_ or _windowFeatures_ doesn't make any difference.

**To Reproduce**

Start a test on IE and use the browser.newWindow(url) command.

**Expected behavior**
IE should open a new tab in the target URL

**Comment by christian-bromann** [comment] 2020-04-22 14:51
Can you please provide some wdio logs?

**Comment by j320** [comment] 2020-04-23 08:44
`[0-0] 2020-04-23T08:40:24.484Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
[0-0] 2020-04-23T08:40:24.484Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/b442b6c7-0c85-4926-be55-ac8d55782f43/execute/sync
[0-0] 2020-04-23T08:40:24.484Z INFO webdriver: DATA {
  script: 'return (function newWindow(url, windowName, windowFeatures) {\n' +
    "  window.open(url, windowName || 'new window', windowFeatures || '');\n" +
    '}).apply(null, arguments)',
  args: [ 'https://www.google.com', 'New Window', '' ]
}
[0-0] 2020-04-23T08:40:24.670Z INFO webdriver: COMMAND getWindowHandles()
[0-0] 2020-04-23T08:40:24.670Z INFO webdriver: [GET] http://localhost:4444/wd/hub/session/b442b6c7-0c85-4926-be55-ac8d55782f43/window/handles
[0-0] 2020-04-23T08:40:24.701Z INFO webdriver: RESULT [ '8d7a682a-5c1f-4d24-817e-2f06dfc24e7e' ]
[0-0] 2020-04-23T08:40:24.701Z INFO webdriver: COMMAND switchToWindow("8d7a682a-5c1f-4d24-817e-2f06dfc24e7e")
[0-0] 2020-04-23T08:40:24.701Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/b442b6c7-0c85-4926-be55-ac8d55782f43/window
[0-0] 2020-04-23T08:40:24.701Z INFO webdriver: DATA { handle: '8d7a682a-5c1f-4d24-817e-2f06dfc24e7e' }
[0-0] 2020-04-23T08:40:25.003Z INFO webdriver: COMMAND findElement("css selector", "#nextElement")
[0-0] 2020-04-23T08:40:25.003Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/b442b6c7-0c85-4926-be55-ac8d55782f43/element
[0-0] 2020-04-23T08:40:25.003Z INFO webdriver: DATA { using: 'css selector', value: '#nextElement' }
[0-0] 2020-04-23T08:40:25.472Z INFO webdriver: RESULT {
  error: 'no such element',
  message: 'Unable to find element with css selector == #nextElement',
  stacktrace: ''
}
[0-0] 2020-04-23T08:40:25.473Z INFO webdriver: COMMAND findElement("css selector", "#nextElement")
[0-0] 2020-04-23T08:40:25.474Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/b442b6c7-0c85-4926-be55-ac8d55782f43/element
[0-0] 2020-04-23T08:40:25.474Z INFO webdriver: DATA { using: 'css selector', value: '#nextElement' }
[0-0] 2020-04-23T08:40:25.883Z INFO webdriver: RESULT {
  error: 'no such element',
  message: 'Unable to find element with css selector == #nextElement',
  stacktrace: ''
}
[0-0] 2020-04-23T08:40:25.975Z INFO webdriver: COMMAND findElement("css selector", "#nextElement")
[0-0] 2020-04-23T08:40:25.976Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/b442b6c7-0c85-4926-be55-ac8d55782f43/element
[0-0] 2020-04-23T08:40:25.976Z INFO webdriver: DATA { using: 'css selector', value: '#nextElement' }
[0-0] 2020-04-23T08:40:26.547Z INFO webdriver: RESULT {
  error: 'no such element',
  message: 'Unable to find element with css selector == #nextElement',
  stacktrace: ''
}
`
As I specified in the description, the test doesn't fail and acts as if the new tab was created and switched to, jumping to the next step. However the tab isn't created and it proceeds with the tests in the current window.

**Comment by christian-bromann** [comment] 2020-04-23 08:54
Can you provide a reproducible example?

**Comment by j320** [comment] 2020-04-23 08:58
What do you need as a reproducible example apart from the steps?

**Comment by christian-bromann** [comment] 2020-04-23 09:04
A small test case in e.g. a single script that I can execute to reproduce this.

**Comment by j320** [comment] 2020-04-23 09:49
Here you have a simple repo: https://github.com/j320/ie-newwindow-defect-example

Cloning it and running _npm test_ or _yarn test_ should do

**Comment by christian-bromann** [comment] 2020-04-23 11:23
@j320 I am not able to reproduce this: https://app.saucelabs.com/tests/3e1218f8ecca494a964bac010eb20282

Will close the issue but am happy to re-open if it turns out to be an actual WebdriverIO bug.

**Closed by christian-bromann** 2020-04-23 11:23 UTC
Labels: Reproducible Example Missing
