### ISSUE TITLE
Issue with WebDriverIO packages size and running inside the AWS Lambda

### ISSUE THREAD

**Issue by avikha** [webdriverio/webdriverio#7377] opened 2021-09-02 13:32 UTC
We are running `wdio` on AWS Lambda, using the `devtools` protocol (via `devtools-service` and `puppeteer`).

First, we build and deploy lambda with the following dependencies. So, when we invoke the Lambda, it already comes with these dependencies pre-installed on the Lambda.

```
"dependencies": {		
	"@wdio/cli": "7.11.0",
  "@wdio/devtools-service": "7.11.0",
  "@wdio/local-runner": "7.11.0",
  "@wdio/mocha-framework": "7.11.0",
  "@wdio/spec-reporter": "7.10.1",

  "chrome-aws-lambda": "10.1.0",
  "dotenv": "10.0.0",

  "moment": "2.29.1",
  "uuid": "8.3.2",
  "axios": "0.21.1",
  "chalk": "4.1.1",

  "unzipper": "^0.10.11"
},
```

Inside the lambda, we use S3 to get the company's internal automation framework and the test code we want to run. Then, we build the test env inside the lambda, create local configurations, wire things up, wire everything with chrome-aws-lambda, and start the test. 

Basically, it works fine. We can run tests inside the AWS Lambda and then integrate it with our CI/CD.

Where is the problem then? Or, what are we afraid of?

The problem is that lambda has a limit size for deployable packages. The limit stands on 250MB when it is unzipped and including Layers. 

We performed some analysis and found out that the size of `node_modules` of the following 6-critical packages is 230MB.

```
"dependencies": {
  "@wdio/cli": "7.11.0",
  "@wdio/devtools-service": "7.11.0",
  "@wdio/local-runner": "7.11.0",
  "@wdio/mocha-framework": "7.11.0",
  "@wdio/spec-reporter": "7.10.1",
  "chrome-aws-lambda": "10.1.0"
},
```

The size of the @wdio packages alone is 180MB. More pricey, installing each package independently lead us to a conclusion where - 

```
"@wdio/cli" // 180 MB
"@wdio/devtools-service" // 173MB
"@wdio/local-runner" // 80MB
"@wdio/mocha-framework" // 13MB
"@wdio/spec-reporter" // 79MB
```

Our best guess is that different `@wdio` packages have intersecting dependencies. 

What we've tried? We've tried to use `node-prune`, `modclean`, and `UglifyJS` to "clean" the `node_modules` and reduce the deployable size by ~50MB of space. And even after that, we are still too close to the limit (~190MB of used space). 

And here come the questions:

1. Why so heavy? We compared it to an alternative solution of using `puppeteer-core` and `jest`. Alternative solution weights 99MB before cleaning and ~85MB after cleaning. We are aware of the fact that `wdio` is a framework, and it handles and brings a lot of stuff, and it is not a minimal automation lib like a `puppeteer-core`. But still, the gap between the sizes is pretty big. We wonder why?
2. Are there any other good practices related to `wdio` on AWS Lambda? For example, are there better ways to minify the project, perhaps more native to `wdio`? Perhaps there are special packages we can use on Lambda? Or maybe we are not using it correctly?

I really appreciate any help you can provide. If any help or more info is needed, I'll be happy to provide it.

**Comment by BorisOsipov** [comment] 2021-09-02 13:44
@avikha could you provide reproducable example? 
I create fresh project and add all your deps. Then measure disk usage by linux `du -h` command. Results are:
- total node_modules size is 238Mb
- `node_modules/@wdio/*` folder size is 2,3Mb
- top 5 the most 'fat' folders is
```
3,3M	./lodash
3,4M	./mocha
8,7M	./lighthouse/lighthouse-core/lib/i18n/locales
21M	./intl/locale-data/jsonp
48M	./chrome-aws-lambda/bin
```

**Comment by christian-bromann** [comment] 2021-09-02 13:45
@avikha how did you measure the package size? If you do:

```sh
$ mkdir /tmp/specReporterSizeTest
$ cd /tmp/specReporterSizeTest
$ npm i @wdio/spec-reporter
```

and then check the size of the `node_modules` folder, you will see that its size is around 3.5MB.

**Comment by avikha** [comment] 2021-09-02 14:48
Hey guys, thank you very much for your fast response. 

@christian-bromann I did exactly what you said. 

```
mkdir /tmp/wdioDevtoolsService/
cd /tmp/wdioDevtoolsService/
npm i @wdio/devtools-service
du -sh ./node_modules/
171M	node_modules
```

I did the same thing with `@wdio/cli`. 

```
mkdir /tmp/wdioCli/
cd /tmp/wdioCli/
npm i @wdio/cli
du -sh ./node_modules/
78M 	node_modules
```

@BorisOsipov @christian-bromann I guess I'm asking why `npm install`ing the `@wdio/devtools-service` or `@wdio/cli` packages brings an additional over 100MB for the total `node_modules`? If the `@wdio/devtools-service` is the service that wraps the `puppeteer-core` or something very similar to that that has to do with `CDP`, then shouldn't `npm install`ing it behave the same way? Or at least close to it?

For instance,  

```
mkdir /tmp/checkPuppeteerCore/
cd /tmp/checkPuppeteerCore/
npm i puppeteer-core
du -sh ./node_modules/
11M ./node_modules/
```

@BorisOsipov, as you said before - `npm install`ing the entire set of dependencies results in 238MB of space size for total node modules. It is very close, too close, to the Lambda limit. Even after minimizing it and optimizing it, it is still like 190MB. 

I wonder if there is any way to optimize the total `node_modules` size related to `@wdio`. Perhaps there are some dependencies-over-dependencies-over-dependencies that the project does not really need or cares about, but you know, `npm install` just brings it down.

Am I missing something?

Once again, thank you very much.

**Comment by avikha** [comment] 2021-09-02 14:59
I think that the thing that I'm most afraid of is because we are so close to the limit of the lambda, and `npm install`ing the `@wdio/*` packages bring a lot `node_modules`, then it is enough that one module or many modules will grow in size and we won't be able to deploy the Lambda anymore.

**Comment by BorisOsipov** [comment] 2021-09-02 15:22
@avikha FMPOV there are two things:
1) `@wdio/devtools-service` is really fat. It comes with puppertier and lighthouse packages with big dependencies size. And seems there is nothing to do.
2) `Perhaps there are some dependencies-over-dependencies-over-dependencies that the project does not really need or cares about, but you know, npm install just brings it down.`
It is "normal" nodejs development reality.
![image](https://user-images.githubusercontent.com/6514276/131869542-d90c2673-8b1a-43a9-8445-82bc511114fa.png)


E.g. we have transitive dependency to `resolve` package and `resolve` `lib` folder(that is production code) code size is 48Kb. But package comes with `test` folder that has size 480Kb (!) and mainteiners don't care https://github.com/browserify/resolve/issues/238#issuecomment-805052821
Or I just removed all *.md files inside node_modules and it is clear 4mb space...
I guees Ш can find a few more examples if I have time.

**Comment by avikha** [comment] 2021-09-02 16:43
Hey @BorisOsipov, I'm familiar with the general notion of the image you've shared, I know that the node_modules is the heaviest object in the universe. But still, for me, it might be a party pooper. And not only for me but for anyone who wants to use `wdio` and scale the testing process. 

I've already used `node-prune`, `modclean`, and `UglifyJS` to free 50MBs. But it is not enough. It is still very fragile. 

The question is whether we can improve the size performance of `@wdio/devtools-service`. Maybe there are static analysis tools or other workarounds that can help us to remove redundant dependencies. Or maybe there are other good practices for using it with AWS Lambda and the cloud. I'm new to the node community, and I'm also researching and looking for solutions. 

I'm not familiar with the inner architecture and structure of WebDriverIO, but perhaps we can make like a core package or something like that. It seems that `@wdio/devtools-service` brings a lot of things, and I'm not sure whether we need it or not.

**Comment by BorisOsipov** [comment] 2021-09-02 17:19
@avikha I understand your issue. I [played with cloud function](https://github.com/BorisOsipov/wdio-gcloudfunction-example) three years ago.

>Maybe there are static analysis tools or other workarounds that can help us to remove redundant dependencies. 

I think you already used all of them(node-prune, modclean, and UglifyJS)

>It seems that @wdio/devtools-service brings a lot of things

It is but they are required. IDK what we have to do if we need lighthouse but it comes with 100mb deps. Probably we can split devtools into few parts, but if you need all it features you still have to add them all...

Only advice I can give it analyze does you really need `@wdio/devtools-service` or you use small part of it and you can implemented it yourself by `puppeter-core` and reduce disk usage.

**Comment by BorisOsipov** [comment] 2021-09-02 17:24
@avikha Also if I understand correctly AWS Lambda [docs](https://docs.aws.amazon.com/lambda/latest/dg/lambda-images.html)

>You can package your code and dependencies as a container image using tools such as the Docker command line interface (CLI). You can then upload the image to your container registry hosted on Amazon Elastic Container Registry (Amazon ECR).

and container image code package size limit is 10 GB

Maybe it will help you don't care about dependencies size.

**Comment by avikha** [comment] 2021-09-05 09:41
Hey @BorisOsipov, thanks for the reply. 

About 

> It is but they are required. IDK what we have to do if we need lighthouse but it comes with 100mb deps. Probably we can split devtools into few parts, but if you need all it features you still have to add them all...

I think that it is a good direction to take. Otherwise, as the project evolves and grows, it won't be a scaleable solution. Once again, I'm not yet familiar of the internal architecture of `wdio` (I'll to get a bit familiar with it), but to me, it sounds good to have like many `devtools` packages, one which is `core` and then others like `lighthouse` and more. 

About 

> Only advice I can give it analyze does you really need @wdio/devtools-service or you use small part of it and you can implemented it yourself by puppeter-core and reduce disk usage.

We are aware of this option. However, it is our less preferable one. We've chosen the `wdio` solution because it is a framework (an industry-proven one) and not a low-level "bare-metals" automation lib, which would require a lot of additional dev workarounds, configurations, integrations, and much more. So here we have a solution that we can wrap with our own infrastructure and utils. If we won't be able to find any other solutions, then we will go for it. But once again, we don't want to find ourselves there.

About the ECR solution - thanks, I'll check that option as well.

**Comment by christian-bromann** [comment] 2021-09-05 21:25
I will go ahead and close this issue. There is no general problem with the package size of the WebdriverIO framework. We are aware and acknowledge that some wdio packages might have larger sizes due to their dependencies (e.g. Lighthouse). However I don't see anything we can do about this at this point and no suggestions have been made so far.

> it sounds good to have like many `devtools` packages, one which is `core` and then others like `lighthouse` and more.

Let's consider this option if we see more folks with this issue. I tend to believe that using Amazon Elastic Container Registry is the right way to go about this. You will run into storage issue anyway at some point. Splitting the devtools package into Puppeteer only and an extra lighthouse service seems like a breaking change to me and we should careful consider this decision.

Maybe we can bring this to the Lighthouse dev team and ask if there is an option splitting some of their packages into different NPM modules so that we don't need to download the heavy locales and other assets.

Thanks @BorisOsipov for investigating on this issue.

**Closed by christian-bromann** 2021-09-05 21:25 UTC
