### ISSUE TITLE
WDIO vs 7 with devtools back end is running at a smaller resolution than with wdio-6 or using chromedriver

### ISSUE THREAD

**Issue by pmerwin** [webdriverio/webdriverio#6482] opened 2021-02-19 20:05 UTC
Use wdio 7 latest in sync mode and run this google test:

describe('Can open google.com', function () {
    it('Window size is correct in chrome?', function () {
        browser.url('https://google.com');
        browser.debug() // check out the screen resolution, it is like a tablet size
    });
   
});

<img width="1217" alt="wdio7 small res" src="https://user-images.githubusercontent.com/26633165/108555518-6639c180-72aa-11eb-8095-2a36331a166f.png">

run this same test with chromedriver and wdio 7, the resolution is correct:

![chromedriver wdio 7](https://user-images.githubusercontent.com/26633165/108555568-7c478200-72aa-11eb-9696-355d94410665.png)

run this test with wdio vs 6 devtools backend, the resolution is correct:

<img width="1214" alt="wdio 6 full res" src="https://user-images.githubusercontent.com/26633165/108555624-91241580-72aa-11eb-81e6-f06d05bc9b4d.png">

Here are all the logs I have vs 7:

[chromedriver-data-logs.zip](https://github.com/webdriverio/webdriverio/files/6012658/chromedriver-data-logs.zip)

[devtools_data_logs.zip](https://github.com/webdriverio/webdriverio/files/6012659/devtools_data_logs.zip)

wdio vs 6 devtools:
[wdio6-devtools-logs.zip](https://github.com/webdriverio/webdriverio/files/6012739/wdio6-devtools-logs.zip)

**chromedriver caps:**
 "capabilities": {
        "acceptInsecureCerts": false,
        "browserName": "chrome",
        "browserVersion": "88.0.4324.182",
        "chrome": {
            "chromedriverVersion": "87.0.4280.88 (89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761})",
            "userDataDir": "/var/folders/vf/009815rj22zdftbwcn0_tgjr0000gp/T/.com.google.Chrome.VUc90L"
        },
        "goog:chromeOptions": {
            "debuggerAddress": "localhost:59011"
        },
        "networkConnectionEnabled": false,
        "pageLoadStrategy": "normal",
        "platformName": "mac os x",
        "proxy": {},
        "setWindowRect": true,
        "strictFileInteractability": false,
        "timeouts": {
            "implicit": 0,
            "pageLoad": 300000,
            "script": 30000
        },
        "unhandledPromptBehavior": "dismiss and notify",
        "webauthn:virtualAuthenticators": true,
        "sessionId": "cc5164239a1f659c8bdcf87804904ed0"
    },
    
**Devtools caps:**
    
   "capabilities": {
        "browserName": "Chrome",
        "browserVersion": "88.0.4324.182",
        "platformName": "darwin",
        "platformVersion": "19.6.0",
        "goog:chromeOptions": {
            "debuggerAddress": "localhost:58926"
        },
        "sessionId": "7ed032ab-ba71-4cd3-b9ad-7ff1b89c6a2b"
    },
    
    **wdio6-devtools caps:**
    "capabilities": {
        "browserName": "Chrome",
        "browserVersion": "88.0.4324.182",
        "platformName": "darwin",
        "platformVersion": "19.6.0",
        "goog:chromeOptions": {
            "debuggerAddress": "localhost:58951",
            "args": ["--enable-automation", "--disable-popup-blocking"]
        },
        "sessionId": "feeb5e6d-cf21-48e1-9a71-fcb39158c198"
    },

**Comment by pmerwin** [comment] 2021-02-19 20:44
**devtools config:**

{
  "specs": [
    "./test/goog.spec.js"
  ],
  "suites": {},
  "exclude": [],
  "outputDir": "./data/wdio-logs",
  "logLevel": "trace",
  "logLevels": {},
  "excludeDriverLogs": [],
  "bail": 0,
  "waitforInterval": 500,
  "waitforTimeout": 30000,
  "framework": "mocha",
  "reporters": [
    [
      "json",
      {
        "outputDir": "./data/report"
      }
    ],
    "spec"
  ],
  "services": [],
  "maxInstances": 5,
  "maxInstancesPerCapability": 100,
  "filesToWatch": [],
  "connectionRetryTimeout": 90000,
  "connectionRetryCount": 3,
  "execArgv": [],
  "runnerEnv": {},
  "runner": "local",
  "specFileRetries": 0,
  "specFileRetriesDelay": 0,
  "specFileRetriesDeferred": false,
  "reporterSyncInterval": 100,
  "reporterSyncTimeout": 5000,
  "cucumberFeaturesWithLineNumbers": [],
  "mochaOpts": {
    "timeout": 840000,
    "ui": "bdd",
    "compilers": [
      "js:@babel/register"
    ],
    "bail": true
  },
  "jasmineNodeOpts": {
    "defaultTimeoutInterval": 10000
  },
  "cucumberOpts": {
    "timeout": 10000
  },
  "onPrepare": [],
  "onWorkerStart": [],
  "before": [
    null
  ],
  "beforeSession": [
    null
  ],
  "beforeSuite": [],
  "beforeHook": [],
  "beforeTest": [
    null
  ],
  "beforeCommand": [],
  "afterCommand": [],
  "afterTest": [
    null
  ],
  "afterHook": [],
  "afterSuite": [],
  "afterSession": [],
  "after": [],
  "onComplete": [],
  "onReload": [],
  "beforeFeature": [],
  "beforeScenario": [],
  "beforeStep": [],
  "afterStep": [],
  "afterScenario": [],
  "afterFeature": [],
  "automationProtocol": "./protocol-stub",
  "logDir": "./data/wdio-logs",
  "seleniumLogs": "./data/wdio-logs",
  "screenshotPath": "./data/report/errors",
  "baseUrl": "https://google.com",
  "ignoredWorkerServices": [],
  "_automationProtocol": "devtools"
  
**chromedriver config:**

{
  "specs": [
    "./test/goog.spec.js"
  ],
  "suites": {},
  "exclude": [],
  "outputDir": "./data/wdio-logs",
  "logLevel": "trace",
  "logLevels": {},
  "excludeDriverLogs": [],
  "bail": 0,
  "waitforInterval": 500,
  "waitforTimeout": 30000,
  "framework": "mocha",
  "reporters": [
    [
      "json",
      {
        "outputDir": "./data/report"
      }
    ],
    "spec"
  ],
  "services": [
    "chromedriver"
  ],
  "maxInstances": 5,
  "maxInstancesPerCapability": 100,
  "filesToWatch": [],
  "connectionRetryTimeout": 90000,
  "connectionRetryCount": 3,
  "execArgv": [],
  "runnerEnv": {},
  "runner": "local",
  "specFileRetries": 0,
  "specFileRetriesDelay": 0,
  "specFileRetriesDeferred": false,
  "reporterSyncInterval": 100,
  "reporterSyncTimeout": 5000,
  "cucumberFeaturesWithLineNumbers": [],
  "mochaOpts": {
    "timeout": 840000,
    "ui": "bdd",
    "compilers": [
      "js:@babel/register"
    ],
    "bail": true
  },
  "jasmineNodeOpts": {
    "defaultTimeoutInterval": 10000
  },
  "cucumberOpts": {
    "timeout": 10000
  },
  "onPrepare": [],
  "onWorkerStart": [],
  "before": [
    null
  ],
  "beforeSession": [
    null
  ],
  "beforeSuite": [],
  "beforeHook": [],
  "beforeTest": [
    null
  ],
  "beforeCommand": [],
  "afterCommand": [],
  "afterTest": [
    null
  ],
  "afterHook": [],
  "afterSuite": [],
  "afterSession": [],
  "after": [],
  "onComplete": [],
  "onReload": [],
  "beforeFeature": [],
  "beforeScenario": [],
  "beforeStep": [],
  "afterStep": [],
  "afterScenario": [],
  "afterFeature": [],
  "host": "localhost",
  "port": 9515,
  "logDir": "./data/wdio-logs",
  "seleniumLogs": "./data/wdio-logs",
  "screenshotPath": "./data/report/errors",
  "baseUrl": "https://google.com",
  "ignoredWorkerServices": [],
  "automationProtocol": "./protocol-stub"
}

**Comment by pmerwin** [comment] 2021-02-19 20:44
May be a dupe of https://github.com/webdriverio/webdriverio/issues/6471

**Comment by christian-bromann** [comment] 2021-02-20 10:13
Yes, duplicate of #6471

**Closed by christian-bromann** 2021-02-20 10:13 UTC
