### ISSUE TITLE
[🐛 Bug]: @wdio/shared-store-service getValue returns undefined in onComplete hook

### ISSUE THREAD

**Issue by mighty98** [webdriverio/webdriverio#8335] opened 2022-05-14 16:56 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.19.7

### Node.js Version

14.16.1

### Mode

WDIO Testrunner

### What happened?

Im creating a custom service where in onComplete hook i need to getValue from shared-store-service
In onPrepare hook i initialise the value 
`  onPrepare = async () => {
    await setValue('result', { total: 0, pass: 0, fail: 0, duration: 0 });
  };`

in afterTest i update it
` afterTest = async (test: Test, context: any, result: TestResult) => {
    const current: any = await getValue('result');
    current.total += 1;
    result.passed ? (current.pass += 1) : (current.fail += 1);
    current.duration += result.duration;
    await setValue('result', current);
  };`
  
  And finally in onComplete i read it 
  `onComplete = async () => {
    const current: any = await getValue('result');
    console.log(`ON COMPLETE ${JSON.stringify(current)}`);
  };`
  
  But it returns undefined
  
![image](https://user-images.githubusercontent.com/32213921/168441313-0c0c32ce-8ea6-4373-83d0-fa180c4f6144.png)

### What is your expected behavior?

I should be able to fetch value in onComplete

### How to reproduce the bug.

Steps are mentioned in description (Hope that would suffice)

### Relevant log output

```typescript
2022-05-14T16:44:56.543Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2022-05-14T16:44:56.544Z INFO @wdio/cli:launcher: Run onComplete hook
2022-05-14T16:44:56.551Z WARN @wdio/shared-store-service: undefined undefined undefined undefined
ON COMPLETE undefined
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2022-05-14 22:01
Can you please provide a reproducible example?

**Comment by mighty98** [comment] 2022-05-15 14:31
@christian-bromann Sorry.. Do you mean a full running code to reproduce this? The given screenshots would not help?
(Raising issue for the first time here. Not really sure what was expected)

**Comment by christian-bromann** [comment] 2022-05-15 20:14
> Do you mean a full running code to reproduce this? The given screenshots would not help?
> (Raising issue for the first time here. Not really sure what was expected)

Yes, because putting what you've shared into a fresh project, returns:

```
ON COMPLETE {"total":1,"pass":1,"fail":0,"duration":2052}
```

**Comment by mighty98** [comment] 2022-05-16 05:33
Oh that's strange.. I will work on getting the whole reproducible code. Meanwhile few pointers
1. I have multiple custom services that use multiple hooks
2. I don't use selenium-standalone-service but have created a custom service for starting server

**Comment by mighty98** [comment] 2022-05-16 06:24
@christian-bromann I have added the code here: https://github.com/mighty98/wdio-hooks

npm run test -- --suite google

I could reproduce the issue

**Comment by christian-bromann** [comment] 2022-05-16 07:28
I see now. The problem is that all service hooks are run at the same time. So the server of the shared service is closed at the same time you are trying to receive a value from it. There are two options:

1. delay this shutdown by an arbitrary number e.g. 1 second to allow access to values before it gets shut down - the problem with that is if you do any other actions that take longer than 1 second before you try to access the values, the server might already be shut down
2. don't shut down the server at as it will be closed automatically if the parent process (the launcher process) closes as well

I think solution number 2 seems more resilient. Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by mighty98** [comment] 2022-05-16 07:46
@christian-bromann About not shutting down the server.. Is it something i can do in my code? Isnt it handled at framework level.. ??
I

**Comment by christian-bromann** [comment] 2022-05-16 09:27
> Isnt it handled at framework level.. ??

It is handled in the framework level, which is why I mention that contributions are welcome.

> Also, do we have any other hook that runs before onComplete and after all workers are closed?

Yes, `after` for example but that hook is run for every runner.

> If we use onComplete for these cleanup task we may run into similar such issues right?

Not sure what you mean.

**Comment by mighty98** [comment] 2022-05-16 09:41
@christian-bromann Thanks. 
As for my last question - If onComplete is the only hook at main process level, we may run into such issues where dependent services may not be available if there is no specific order to execute.. I may be wrong and this could be just one of a case

As for the required change, I may be very inexperienced to make the required change. But just removing onComplete hook from launcher here would resolve this?
export default class SharedStoreLauncher {
    async onPrepare (_: never, capabilities: SharedStoreServiceCapabilities[]) {
        server = require('./server').default
        const result = await server.startServer()
        setPort(result.port)
        capabilities.forEach(capability => {capability['wdio:sharedStoreServicePort'] = result.port})

        log.info(`Started shared server on port ${result.port}`)
    }

    async onComplete () {
        await server.stopServer()
    }
}

**Comment by christian-bromann** [comment] 2022-05-16 13:00
> But just removing onComplete hook from launcher here would resolve this?

I believe so. It might also require the removal of a test.

**Comment by mighty98** [comment] 2022-05-16 16:52
@christian-bromann Can you please take a look at https://github.com/webdriverio/webdriverio/pull/8349

**Comment by mighty98** [comment] 2022-05-18 12:27
@christian-bromann Was i supposed to add a new version in package.json to be able to use this?

**Comment by christian-bromann** [comment] 2022-05-18 12:34
If your versions are prefixed with a `^` you don't. Please note that this change is not released yet. Keep an eye on the [release section](https://github.com/webdriverio/webdriverio/releases) as it will be included in the next release (which I don't know when it happens but surely soon!).

Closing as this bug was fixed and will be released soon.

**Closed by christian-bromann** 2022-05-18 12:34 UTC
Labels: Bug 🐛, help wanted, good first pick
