### ISSUE TITLE
webdriverio action deletes session in Not Secure mode - Chrome

### ISSUE THREAD

**Issue by Lohith-Shantharaju** [webdriverio/webdriverio#6931] opened 2021-05-28 10:15 UTC
**Environment :**
 - **WebdriverIO version: 7.6.1
 - **Mode: WDIO Testrunner
 - **If WDIO Testrunner, running sync/async: async
 - **Node.js version: v14.16.1
 - **NPM version: 6.14.12
 - **Browser name and version: Chrome 91
 - **Platform name and version:  Windows 10
 - **Additional wdio packages used (if applicable): NA

**Config of WebdriverIO**
exports.config = {
    services: ['intercept'],
    before () {
        require('expect-webdriverio').setOptions({ wait: 5000 })
    },
    //
    // ====================
    // Runner Configuration
    // ====================
    //
    // WebdriverIO allows it to run your tests in arbitrary locations (e.g. locally or
    // on a remote machine).
    runner: 'local',
    //
    // ==================
    // Specify Test Files
    // ==================
    // Define which test specs should run. The pattern is relative to the directory
    // from which `wdio` was called.
    //
    // The specs are defined as an array of spec files (optionally using wildcards
    // that will be expanded). The test for each spec file will be run in a separate
    // worker process. In order to have a group of spec files run in the same worker
    // process simply enclose them in an array within the specs array.
    //
    // If you are calling `wdio` from an NPM script (see https://docs.npmjs.com/cli/run-script),
    // then the current working directory is where your `package.json` resides, so `wdio`
    // will be called from there.
    //
    specs: [
        './features/*.feature'
    ],
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    //
    // ============
    // Capabilities
    // ============
    // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
    // time. Depending on the number of capabilities, WebdriverIO launches several test
    // sessions. Within your capabilities you can overwrite the spec and exclude options in
    // order to group specific specs to a specific capability.
    //
    // First, you can define how many instances should be started at the same time. Let's
    // say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
    // set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
    // files and you set maxInstances to 10, all spec files will get tested at the same time
    // and 30 processes will get spawned. The property handles how many capabilities
    // from the same test should run tests.
    //
    maxInstances: 10,
    //
    // If you have trouble getting all important capabilities together, check out the
    // Sauce Labs platform configurator - a great tool to configure your capabilities:
    // https://docs.saucelabs.com/reference/platforms-configurator
    //
    capabilities: [{
    
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 5,
        //
        browserName: 'chrome',
        acceptInsecureCerts: true,
        // If outputDir is provided WebdriverIO can capture driver session logs
        // it is possible to configure which logTypes to include/exclude.
        // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
        // excludeDriverLogs: ['bugreport', 'server'],
        'goog:chromeOptions': { 
            args: ["--window-size=1920,1080",
            "--allow-running-insecure-content",
            "--disable-web-security"]
       }
    }],
    //
    // ===================
    // Test Configurations
    // ===================
    // Define all options that are relevant for the WebdriverIO instance here
    //
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    logLevel: 'info',
    //
    // Set specific log levels per logger
    // loggers:
    // - webdriver, webdriverio
    // - @wdio/applitools-service, @wdio/browserstack-service, @wdio/devtools-service, @wdio/sauce-service
    // - @wdio/mocha-framework, @wdio/jasmine-framework
    // - @wdio/local-runner
    // - @wdio/sumologic-reporter
    // - @wdio/cli, @wdio/config, @wdio/utils
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    // logLevels: {
    //     webdriver: 'info',
    //     '@wdio/applitools-service': 'info'
    // },
    //
    // If you only want to run your tests until a specific amount of tests have failed use
    // bail (default is 0 - don't bail, run all tests).
    bail: 0,
    //
    // Set a base URL in order to shorten url command calls. If your `url` parameter starts
    // with `/`, the base url gets prepended, not including the path portion of your baseUrl.
    // If your `url` parameter starts without a scheme or `/` (like `some/path`), the base url
    // gets prepended directly.
    baseUrl: 'https://coveainsurance.uat.iotatech.cloud/',
    //
    // Default timeout for all waitFor* commands.
    waitforTimeout: 10000,
    //
    // Default timeout in milliseconds for request
    // if browser driver or grid doesn't send response
    connectionRetryTimeout: 120000,
    //
    // Default request retries count
    connectionRetryCount: 3,
    //
    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.
    services: ['chromedriver'],
    
    // Framework you want to run your specs with.
    // The following are supported: Mocha, Jasmine, and Cucumber
    // see also: https://webdriver.io/docs/frameworks
    //
    // Make sure you have the wdio adapter package for the specific framework installed
    // before running any tests.
    framework: 'cucumber',
    //
    // The number of times to retry the entire specfile when it fails as a whole
    // specFileRetries: 1,
    //
    // Delay in seconds between the spec file retry attempts
    // specFileRetriesDelay: 0,
    //
    // Whether or not retried specfiles should be retried immediately or deferred to the end of the queue
    // specFileRetriesDeferred: false,
    //
    // Test reporter for stdout.
    // The only one supported by default is 'dot'
    // see also: https://webdriver.io/docs/dot-reporter
    reporters: ['spec'],

    //
    // If you are using Cucumber you need to specify the location of your step definitions.
    cucumberOpts: {
        // <string[]> (file/dir) require files before executing features
        require: ['./step-definitions/*.js'],
        // <boolean> show full backtrace for errors
        backtrace: false,
        // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
        requireModule: ['@babel/register'],
        // <boolean> invoke formatters without executing steps
        dryRun: false,
        // <boolean> abort the run on first failure
        failFast: false,
        // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
        format: ['pretty'],
        // <boolean> hide step definition snippets for pending steps
        snippets: true,
        // <boolean> hide source uris
        source: true,
        // <string[]> (name) specify the profile to use
        profile: [],
        // <boolean> fail if there are any undefined or pending steps
        strict: false,
        // <string> (expression) only execute the features or scenarios with tags matching the expression
        tagExpression: '',
        // <number> timeout for step definitions
        timeout: 60000,
        // <boolean> Enable this config to treat undefined definitions as warnings.
        ignoreUndefinedDefinitions: false
    },
    
    //
    // =====
    // Hooks
    // =====
    // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
    // it and to build services around it. You can either apply a single function or an array of
    // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
    // resolved to continue.
    /**
     * Gets executed once before all workers get launched.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     */
    // onPrepare: function (config, capabilities) {
    // },
    /**
     * Gets executed before a worker process is spawned and can be used to initialise specific service
     * for that worker as well as modify runtime environments in an async fashion.
     * @param  {String} cid      capability id (e.g 0-0)
     * @param  {[type]} caps     object containing capabilities for session that will be spawn in the worker
     * @param  {[type]} specs    specs to be run in the worker process
     * @param  {[type]} args     object that will be merged with the main configuration once worker is initialised
     * @param  {[type]} execArgv list of string arguments passed to the worker process
     */
    // onWorkerStart: function (cid, caps, specs, args, execArgv) {
    // },
    /**
     * Gets executed just before initialising the webdriver session and test framework. It allows you
     * to manipulate configurations depending on the capability or spec.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     */
    // beforeSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed before test execution begins. At this point you can access to all global
     * variables like `browser`. It is the perfect place to define custom commands.
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs        List of spec file paths that are to be run
     * @param {Object}         browser      instance of created browser/device session
     */
    // before: function (capabilities, specs) {
    // },
    /**
     * Runs before a WebdriverIO command gets executed.
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     */
    // beforeCommand: function (commandName, args) {
    // },
    /**
     * Runs before a Cucumber feature
     */
    // beforeFeature: function (uri, feature) {
    // },
    /**
     * Runs before a Cucumber scenario
     */
    // beforeScenario: function (world) {
    // },
    /**
     * Runs before a Cucumber step
     */
    // beforeStep: function (step, context) {
    // },
    /**
     * Runs after a Cucumber step
     */
    // afterStep: function (step, context) {
    // },
    /**
     * Runs after a Cucumber scenario
     */
    // afterScenario: function (world) {
    // },
    /**
     * Runs after a Cucumber feature
     */
    // afterFeature: function (uri, feature) {
    // },
    
    /**
     * Runs after a WebdriverIO command gets executed
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     * @param {Number} result 0 - command success, 1 - command error
     * @param {Object} error error object if any
     */
    // afterCommand: function (commandName, args, result, error) {
    // },
    /**
     * Gets executed after all tests are done. You still have access to all global variables from
     * the test.
     * @param {Number} result 0 - test pass, 1 - test fail
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // after: function (result, capabilities, specs) {
    // },
    /**
     * Gets executed right after terminating the webdriver session.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // afterSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed after all workers got shut down and the process is about to exit. An error
     * thrown in the onComplete hook will result in the test run failing.
     * @param {Object} exitCode 0 - success, 1 - fail
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {<Object>} results object containing test results
     */
    // onComplete: function(exitCode, config, capabilities, results) {
    // },
    /**
    * Gets executed when a refresh happens.
    * @param {String} oldSessionId session ID of the old session
    * @param {String} newSessionId session ID of the new session
    */
    //onReload: function(oldSessionId, newSessionId) {
    //}
}

**Describe the bug**
Step1: Navigate to URL. 
Step2: Click on the button. Which changes the site from secure to Not secure. 
Step3: get elements from the page. 
Step 4: perform any action on the element and this deletes the session and closes the browser.

**To Reproduce**
Sorry, I cannot provide the site information, but I'm working on a site that uses semafone card payment window.

[Include code or an example repository that can easily be set up]

**Expected behavior**
Able to perform action on the page.

**Log**
COMMAND findElement("css selector", ".summary-section-card-container  .summary-section-card-title")
[0-0] 2021-05-28T09:09:58.951Z INFO webdriver: [POST] http://localhost:9515/session/e14cee05476846ea18aa395b2fadb3f5/element
[0-0] 2021-05-28T09:09:58.952Z INFO webdriver: DATA {
[0-0]   using: 'css selector',
[0-0]   value: '.summary-section-card-container  .summary-section-card-title'
[0-0] }
[0-0] 2021-05-28T09:09:58.958Z INFO webdriver: COMMAND findElement("xpath", "//span[contains(text(),"Save")]/..")
[0-0] 2021-05-28T09:09:58.959Z INFO webdriver: [POST] http://localhost:9515/session/e14cee05476846ea18aa395b2fadb3f5/element
[0-0] 2021-05-28T09:09:58.959Z INFO webdriver: DATA { using: 'xpath', value: '//span[contains(text(),"Save")]/..' }
[0-0] 2021-05-28T09:09:58.984Z INFO webdriver: COMMAND deleteSession()
[0-0] 2021-05-28T09:09:58.984Z INFO webdriver: [DELETE] http://localhost:9515/session/e14cee05476846ea18aa395b2fadb3f5
[0-0] 2021-05-28T09:09:58.996Z INFO webdriver: COMMAND releaseActions()
[0-0] 2021-05-28T09:09:58.997Z INFO webdriver: [DELETE] http://localhost:9515/session/e14cee05476846ea18aa395b2fadb3f5/actions
[0-0] 2021-05-28T09:09:59.006Z INFO webdriver: COMMAND releaseActions()
[0-0] 2021-05-28T09:09:59.008Z INFO webdriver: [DELETE] http://localhost:9515/session/e14cee05476846ea18aa395b2fadb3f5/actions
[0-0] 2021-05-28T09:09:59.019Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': 'e9463aca-827e-4658-964d-32b99d4d588b'
[0-0] }
[0-0] 2021-05-28T09:09:59.235Z INFO webdriver: COMMAND performActions(<object>)
[0-0] 2021-05-28T09:09:59.236Z INFO webdriver: [POST] http://localhost:9515/session/e14cee05476846ea18aa395b2fadb3f5/actions
[0-0] 2021-05-28T09:09:59.236Z INFO webdriver: DATA { actions: [ { type: 'key', id: 'keyboard', actions: [Array] } ] }
[0-0] 2021-05-28T09:09:59.241Z INFO webdriver: COMMAND performActions(<object>)
[0-0] 2021-05-28T09:09:59.241Z INFO webdriver: [POST] http://localhost:9515/session/e14cee05476846ea18aa395b2fadb3f5/actions
[0-0] 2021-05-28T09:09:59.242Z INFO webdriver: DATA { actions: [ { type: 'key', id: 'keyboard', actions: [Array] } ] }
[0-0] 2021-05-28T09:09:59.748Z INFO webdriver: COMMAND getElementText("e9463aca-827e-4658-964d-32b99d4d588b")
[0-0] 2021-05-28T09:09:59.749Z INFO webdriver: [GET] http://localhost:9515/session/e14cee05476846ea18aa395b2fadb3f5/element/e9463aca-827e-4658-964d-32b99d4d588b/text
[0-0] 2021-05-28T09:09:59.750Z INFO webdriver: COMMAND getElementText("e9463aca-827e-4658-964d-32b99d4d588b")
[0-0] 2021-05-28T09:09:59.751Z INFO webdriver: [GET] http://localhost:9515/session/e14cee05476846ea18aa395b2fadb3f5/element/e9463aca-827e-4658-964d-32b99d4d588b/text
[0-0] 2021-05-28T09:09:59.755Z INFO webdriver: COMMAND findElement("xpath", "//span[contains(text(),"Save")]/..")
[0-0] 2021-05-28T09:09:59.755Z INFO webdriver: [POST] http://localhost:9515/session/e14cee05476846ea18aa395b2fadb3f5/element
[0-0] 2021-05-28T09:09:59.756Z INFO webdriver: DATA { using: 'xpath', value: '//span[contains(text(),"Save")]/..' }
[0-0] 2021-05-28T09:09:59.768Z INFO webdriver: RESULT {
[0-0]   error: 'no such element',
[0-0]   message: 'no such element: Unable to locate element: {"method":"xpath","selector":"//span[contains(text(),"Save")]/.."}\n' +
[0-0]     '  (Session info: chrome=91.0.4472.77)',
[0-0]   stacktrace: 'Backtrace:\n' +
[0-0]     '\tOrdinal0 [0x006AC013+2474003]\n' +
[0-0]     '\tOrdinal0 [0x006429C1+2042305]\n' +
[0-0]     '\tOrdinal0 [0x00552F68+1060712]\n' +
[0-0]     '\tOrdinal0 [0x0057D8A4+1235108]\n' +
[0-0]     '\tOrdinal0 [0x005A7232+1405490]\n' +
[0-0]     '\tOrdinal0 [0x0059684A+1337418]\n' +
[0-0]     '\tOrdinal0 [0x005A55CB+1398219]\n' +
[0-0]     '\tOrdinal0 [0x005966DB+1337051]\n' +
[0-0]     '\tOrdinal0 [0x00573427+1192999]\n' +
[0-0]     '\tOrdinal0 [0x005742EE+1196782]\n' +
[0-0]     '\tOrdinal0 [0x00574279+1196665]\n' +
[0-0]     '\tGetHandleVerifier [0x008396FC+1590332]\n' +
[0-0]     '\tGetHandleVerifier [0x008E8614+2306900]\n' +
[0-0]     '\tGetHandleVerifier [0x00739E93+543699]\n' +
[0-0]     '\tGetHandleVerifier [0x007392CE+540686]\n' +
[0-0]     '\tOrdinal0 [0x006486BA+2066106]\n' +
[0-0]     '\tOrdinal0 [0x0064D1C8+2085320]\n' +
[0-0]     '\tOrdinal0 [0x0064D308+2085640]\n' +
[0-0]     '\tOrdinal0 [0x006567F3+2123763]\n' +
[0-0]     '\tBaseThreadInitThunk [0x7714FA29+25]\n' +
[0-0]     '\tRtlGetAppContainerNamedObjectPath [0x77B27A7E+286]\n' +
[0-0]     '\tRtlGetAppContainerNamedObjectPath [0x77B27A4E+238]\n'
[0-0] }
[0-0] 2021-05-28T09:09:59.811Z INFO webdriver: COMMAND releaseActions()
[0-0] 2021-05-28T09:09:59.812Z INFO webdriver: [DELETE] http://localhost:9515/session/e14cee05476846ea18aa395b2fadb3f5/actions
[0-0] PASSED in chrome - [.\features\login.feature]

**Additional context**
webdriverio return  Unable to locate element: {"method":"xpath","selector":"//span[contains(text(),"Save")]/ and deletes session.
This code works using selenium and c#.

> Please use the correct markdown

**Comment by christian-bromann** [comment] 2021-05-28 11:38
Can you provide a reproducible example?

**Comment by Lohith-Shantharaju** [comment] 2021-05-28 15:09
@christian-bromann  Sorry, but I cannot provide you a sample website where this would happen. Not sure how would I get a site to change to not secure mode after performing the action. In my current application, we have 3rd party provider which is accessible inside an application, and hence when it loads it goes to Not secure mode. And I need to capture the details on the new frame which is visible.

**Comment by christian-bromann** [comment] 2021-05-28 15:25
@Lohith-Shantharaju I am afraid some reproducible example is required. The logs only say:

> message: 'no such element: Unable to locate element: {"method":"xpath","selector":"//span[contains(text(),"Save")]/.."}\n' +

which is a normal error saying that the element could not be found. This is an user error. It is impossible for any contributor to start any investigation without the example.

**Comment by Lohith-Shantharaju** [comment] 2021-05-28 15:35
@christian-bromann  This xpath "//span[contains(text(),"Save")]/.." is not stored in my solution, this is something webdriverio is returning every time and then deletes the session and closes the browser.

**Comment by christian-bromann** [comment] 2021-05-28 16:24
You are probably using this Selector: `span*=Save`. It deletes the session and closes the browser because the test fails at that point.

**Comment by Lohith-Shantharaju** [comment] 2021-05-28 16:36
Sorry @christian-bromann : There is not selector in my solution like **span*=Save.**.
There are not locators which have the text save in the application. I double-checked.

**Comment by christian-bromann** [comment] 2021-05-28 16:53
This is the problem with not having a reproducible example. I only can make guesses but without anything to run myself I won't be able to help. I am going to close the issue. Happy to re-open if you can further locate the error and/or provide a minimal reproducible example.

**Closed by christian-bromann** 2021-05-28 16:53 UTC
Labels: Reproducible Example Missing
