### ISSUE TITLE
[🐛 Bug]: setValue sends a string with missing char 

### ISSUE THREAD

**Issue by louis57** [webdriverio/webdriverio#11577] opened 2023-11-02 12:45 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

^7.31.1

### Node.js Version

v18.18.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
   browserName: 'chrome',
   browserVersion: 'latest',
   platformName: 'Windows 11'
}
```

### What happened?

I have this strange issue with `setValue`, but only sometimes, and when I run my tests on `Browserstack`. 

I just have a normal command to sendkeys to input text like this:

`element.setValue('Japanese')`;

However, sometimes when I run tests on `Browserstack`, it enters the word like `Jpanese`, as screenshot:

![image](https://github.com/webdriverio/webdriverio/assets/12949146/37eefcaa-96b5-4fde-8d1f-5f8d82e3a56c)

As result, tests failed sometimes because of this strange issue. I notice that it failed when the text is kind of "long", it also failed on `Romanian`, so the text `Rmanian` would be entered instead. So, the second char is always missing, when it happens. But `Danish` works, never have this issue

If I run tests on my local browser, it never happens.

Can someone please advise if this is WDIO's issue or Browserstack's issue.

### How to reproduce the bug.

Try command `setValue`

### Relevant log output

```typescript
NA
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment] 2023-11-02 17:47
9 out of 10 times this is caused by the clearance of the input.

What likely happens is as follows:
1. WebdriverIO clears the input 
2. WebdriverIO enters text
3. During step 2 an error stating that the input cannot be empty is shown (it's so fast you don't actually see it). Interrupting the input, causing the missing characters

I cannot say this for sure but this has been my experience over the years. Hope this helps 👍

**Comment by christian-bromann** [comment] 2023-11-03 01:59
@louis57 can you provide logs? If they show that WebdriverIO has sent the correct work but BS failed to run the WebDriver command correctly, I would recommend to reach out to their support.

**Comment by louis57** [comment] 2023-11-03 08:49
@christian-bromann I enclose the logs from Browserstack as screenshot, since it also captured some screenshots. The text used for `Send Keys` was correct Japanese, but `Jpanese` was entered/displayed on UI. I already reached out to Browserstack, I am waiting for their response.
![image](https://github.com/webdriverio/webdriverio/assets/12949146/0c4591a8-2e15-4228-95fb-9156ed98eb57)

@erwinheitzman as you suggested, the clearance of the input might be the issue, so I tried `addValue` command, which doesn't clear the input before `sendKeys`, but the same outcome still happens. Also the logs look clean, doesn't have error.

**Comment by erwinheitzman** [comment] 2023-11-03 13:20
@louis57 since the field seems to be a search field instead of an error interrupting the input, it feel like it might somehow be the search as it will trigger some things. If it starts searching right at the moment of the first input than adding a debounce to the input of the component/element might help here to prevent triggering the search too early.
Of course I cannot say this for sure as I don't know the implementation.
The only times I have seen strange behaviour with the input was:
1. The input was interrupted by something in the frontend
2. Using a forEach to enter the characters one by one, since forEach does not support async callbacks the input will be in a random order

**Comment by christian-bromann** [comment] 2023-11-03 13:53
I will go ahead and close this as WebdriverIO seems to do everything correctly and the automation failed on BS side or within the browser or application. If there is anything we can do to help, let us know.

**Closed by christian-bromann** 2023-11-03 13:53 UTC
Labels: Bug 🐛, Logs Missing

**Comment by cybersokari** [comment] 2025-02-05 12:28
I am having the same problem using Appium service.

My current workaround is;

``` typescript
for (const char of email) {
      await this.emailInput.addValue(char)
    }
```
which is very slow.

**Comment by christian-bromann** [comment] 2025-02-05 16:24
@cybersokari this is unfortunately related to Appium and the device you are automating.
