### ISSUE TITLE
[💡 Feature]: specify tsconfig.json to CLI

### ISSUE THREAD

**Issue by kopax-polyconseil** [webdriverio/webdriverio#9151] opened 2022-11-07 14:07 UTC
### Is your feature request related to a problem?

I have a react-native app on which I try to import the https://github.com/webdriverio/appium-boilerplate folders config and tests, and when I try to run commands, it fail to execute with 

```
yarn android.app
yarn run v1.22.15
$ wdio e2e/config/wdio.android.app.conf.ts
2022-11-07T14:02:29.685Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: /home/dka/workspace/github.com/pass-culture/pass-culture-app-native/e2e/config/wdio.android.app.conf.ts: Unexpected token 'export'
Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

/home/dka/workspace/github.com/pass-culture/pass-culture-app-native/e2e/config/wdio.shared.local.appium.conf.ts:16
export default config;
^^^^^^

SyntaxError: Unexpected token 'export'
```

### Describe the solution you'd like.

I would like to be able to specify the `tsconfig.json` configuration, and use `e2e/tsconfig.json` instead of `tsconfig.json`

### Describe alternatives you've considered.

It is hard to tell, do you have an idea ?

### Additional context

If I try to erase my react native tsconfig.json, I am able to run

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by erwinheitzman** [comment] 2022-11-07 16:00
You can use the following for this: https://webdriver.io/docs/typescript/#configuration

**Comment by christian-bromann** [comment] 2022-11-07 16:32
Yes, please check the docs (see link above).

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by kopax-polyconseil** [comment] 2022-11-07 16:43
Hi both, I have tried to add the confgiuration here: https://github.com/pass-culture/pass-culture-app-native/blob/PC-18308-2/e2e/config/wdio.shared.conf.ts#L7

I am not able to specify the `tsconfig.path` location and tried multiple synthax, with absolute path and relative. Are you sur this is working ? I will ask on gitter, thanks for linking

**Comment by christian-bromann** [comment] 2022-11-07 16:45
Have you debugged your result configuration? It seems it should be this:

```patch
-            project: process.cwd() + 'e2e/tsconfig.json'
+            project: process.cwd() + '/e2e/tsconfig.json'
```

**Comment by kopax-polyconseil** [comment] 2022-11-07 16:45
I've tried both, I always have the same error, like if this option isn't picked.

**Comment by christian-bromann** [comment] 2022-11-07 17:06
@kopax-polyconseil can you print out your resulting config?

**Comment by christian-bromann** [comment] 2022-11-07 17:11
Let me re-open to investigate if there are any issues passing in the project property into `ts-node`. Any feedback is welcome.

**Comment by erwinheitzman** [comment] 2022-11-07 17:21
I have a strong feeling that it might be the same issue as describe here https://github.com/webdriverio/webdriverio/issues/6939

**Comment by kopax-polyconseil** [comment] 2022-11-07 18:04
When I do logging `console.log(_args)` here: https://github.com/webdriverio/webdriverio/blob/428a9d729ae6231968a60908732fa3f607d195e9/packages/wdio-cli/src/launcher.ts#L61

I have: 

```js
{
  _: [ 'e2e/config/wdio.android.app.conf.ts' ],
  '$0': 'node_modules/.bin/wdio'
}
```

If I do:

```diff
        if (_args.autoCompileOpts) {
            this.configParser.merge({ autoCompileOpts: _args.autoCompileOpts })
-        }
+       } else {
+            this.configParser.merge({ autoCompileOpts: myCompileOpts })
+       }
```

It work.

**Comment by erwinheitzman** [comment] 2022-11-08 09:44
I can reproduce this but have also tested this with the upcoming v8 in which this is solved.

I'm not sure if it's realistic to accept this as a known issue in v7 and have it solved in v8 as v8 contains quite some changes.

**Comment by kopax-polyconseil** [comment] 2022-11-08 09:51
> I'm not sure if it's realistic to accept this as a known issue in v7 and have it solved in v8 as v8 contains quite some changes.

I wanted to check v8 code to see if it was possible to fix v7 with the solution in v8, but couldn't find the tag, nor branch. 

According to your last comment, I am not sure what to do at the moment and will stick to the patch package until someone add further clarification.

**Comment by erwinheitzman** [comment] 2022-11-08 09:52
@kopax-polyconseil here's the v8 code: https://github.com/webdriverio/webdriverio/blob/cb-v8-release-post/packages/wdio-config/src/lib/ConfigParser.ts

**Comment by erwinheitzman** [comment] 2022-11-08 10:04
the difference is this:
v7
```js
            const importedModule = await this._pathService.loadFile<ImportedConfigModule>(filePath)
            const config = (importedModule as ESMImport).config || (importedModule as DefaultImport).default?.config
            if (typeof config !== 'object') {
                throw new Error(NO_NAMED_CONFIG_EXPORT)
            }

            /**
             * clone the original config
             */
            const fileConfig = Object.assign({}, config)
```
v8 
```js
            const config = (await this._pathService.loadFile<{ config: TestrunnerOptionsWithParameters }>(filePath)).config

            if (typeof config !== 'object') {
                throw new Error('addConfigEntry requires config key')
            }

            /**
             * clone the original config
             */
            const fileConfig = merge<Omit<Options.Testrunner, 'capabilities'> & { capabilities?: Capabilities.RemoteCapabilities }>(config, {}, MERGE_OPTIONS)
```

**Comment by kopax-polyconseil** [comment] 2022-11-08 10:19
I saw on first sight those differences, but as you can see, type are also different types, and perhaps those service are also different.

Perhaps it is safe to move to v8, or is it expected to be breaking change ?

**Comment by erwinheitzman** [comment] 2022-11-08 13:27
I checked those and they seem the same. Types don't matter for the execution of the code. v8 will have breaking changes as it is a major release.

**Comment by christian-bromann** [comment] 2022-11-08 17:50
@kopax-polyconseil feel free to have a sneak peak into the [release blog post](https://github.com/webdriverio/webdriverio/blob/main/website/blog/2022-10-11-webdriverio-v8-released.md). There are no concrete breaking changes to the user interface however we rewrote the whole code base and can't guarantee everything will be fine which is why we are doing a major release. I am happy to merge and publish fixes to `v7` branch which currently is what we release as stable to NPM. Everything within `main` is released as `@next`.

**Comment by kopax-polyconseil** [comment] 2022-11-15 17:18
@christian-bromann for us, this patch-package will work : https://github.com/pass-culture/pass-culture-app-native/pull/3876/files#diff-8ca67e4893fe1f8563c37fa5ccc9e1d144ce49510d0755929910cce9e93eb572

We don't have the need to fix it. I leave this open in case one want's to jump in and contribute.

@erwinheitzman do you have a roadmap for it ? It's a bit sad to started writing e2e tests on an old webdriverio version.

**Comment by christian-bromann** [comment] 2022-11-15 18:08
@kopax-polyconseil I will look into this as part of the v8 release given that I have bunch of TS issues in our [component testing example](https://github.com/webdriverio/component-testing-examples) repo to fix as well.

> The release blog post link is 404.

https://github.com/webdriverio/webdriverio/blob/main/website/blog/2022-11-20-webdriverio-v8-released.md

**Comment by christian-bromann** [comment] 2022-11-19 08:28
> I would like to be able to specify the `tsconfig.json` configuration, and use `e2e/tsconfig.json` instead of `tsconfig.json`

After investigation it turns out that the way we had TS support set-up wasn't really working for ESM anymore. I didn't recognised it because ts-node would still compile but with default configurations. In a test project at my company I needed specific TS options and they did not get picked up because ts-node couldn't read the location of the tsconfig file.

Long story I [updated our TS integration](https://github.com/webdriverio/webdriverio/commit/709b5daaa2da47263b8785d8f6efebae5cda3f2e). From now on WebdriverIO will recognise a `tsconfig.json` within the same directory. If the location of that config differs, the user will need to use `TS_NODE_PROJECT` environment variable. See full change here: https://github.com/webdriverio/webdriverio/commit/709b5daaa2da47263b8785d8f6efebae5cda3f2e

**Closed by christian-bromann** 2022-11-19 08:28 UTC

**Comment by christian-bromann** [comment] 2022-12-23 09:32
@kopax-polyconseil can you provide a minimal reproducible example?

**Comment by erocheleau** [comment] 2023-02-08 17:05
It would be really useful to just have a cli argument to specify a path to the `tsconfig.json` file for `ts-node`

something like `npx wdio path/to/wdio.conf.ts --project path/to/tsconfig.json` would do wonders and would've saved me a lot of headaches. (The name of the args doesn't matter)

In my project I have a tsconfig at the root because it's a packaged and delivered application, and a different tsconfig under the `test/e2e/folder` because the config might not be the same for the test runner than for the project itself.

If I understand correctly the only way to support that right now is to have something like the following correct?

package.json
```
"scripts": {
    "test": "TS_NODE_PROJECT=./test/e2e/tsconfig.json npx wdio test/e2e/wdio.conf.ts"
}
```

**Comment by christian-bromann** [comment] 2023-02-08 17:56
> But this is not the case?

It is, you can set the path to your `tsconfig.json` or use the environment variable. What wording changes would make this more clear to you?

**Comment by erocheleau** [comment] 2023-02-08 21:02
It doesn't work though. In my case my `wdio.conf.ts` is using an `import` statement, and because I have a `tsconfig` at the root of the project which is not the one I want to be used by the test runner, it throws with the error:

`Cannot use import statement outside of a module.`

But if I set the environment variable prior to running the `npx wdio path/to/wdio.conf.ts` with the correct path to my `tsconfig` which resolves modules correctly, it works.

But setting the path in the config file itself doesn't work.

**Comment by erocheleau** [comment] 2023-02-08 21:05
Example:

```
import { resolve } from 'path';
export const config = {
    // ...
    autoCompileOpts: {
        autoCompile: true,
        tsNodeOpts: {
            transpileOnly: true,
            project: './test/e2e/tsconfig.json'
        }
    }
};
```
This gives me the import error.

but if I set the environment variable `TS_NODE_PROJECT=./test/e2e/tsconfig.json` before running the command it works correctly.

**Comment by christian-bromann** [comment] 2023-02-08 21:10
Well there is a limitation here which I don't know WebdriverIO can/should overcome. You are in a CJS context and use ESM imports. TypeScript can help fix that but for that WebdriverIO needs a `tsconfig.json`. It can't guess where this config is which is why you can either have a `tsconfig.json` in the same dir as your `wdio.conf.ts` or specify a `TS_NODE_PROJECT`. If you have any suggestions how this can be improved, let me know.

**Comment by erocheleau** [comment] 2023-02-09 17:31
Yea, just something in the argument of the `wdio run` command to the cli?

`npx wdio path/to/wdio.conf.ts --project path/to/tsconfig.json`

I think you already support having it in a config file and in an environment variable. But this is kinda crucial to wdio wroking well so I would suggest adding an optional argument to the cli to specify a path to a tsconfig to use.
(Environment variables are just a little bit more of a pain to set in npm scripts, but a simple CLI argument would be very simple)

And you could have different testing setups too with simply different npm scripts:

`"wdio-e2e" : "npx wdio path/to/e2e/wdio.conf.ts --project path/to/e2e/tsconfig.json"`
`"wdio-other": "npx wdio path/to/other/wdio.conf.ts --project other/path/tsconfig.json"`

It would just add flexibility IMO and it's easier to manage than environment variables.

**Comment by christian-bromann** [comment] 2023-02-09 17:40
I think this should be already supported, have you tried:

```sh
npx wdio run wdio.conf.ts --autoCompileOpts.tsNodeOpts.project path/to/e2e/tsconfig.json
```

?

**Comment by erocheleau** [comment] 2023-02-09 17:46
I have not, did I miss it in the documentation? Sorry about that

**Comment by christian-bromann** [comment] 2023-02-09 18:01
Let me know if this works for you. It is not documented but the framework we use to parse CLI args should support this.

**Comment by erocheleau** [comment] 2023-02-09 18:25
Oh yea it works that way!
