### ISSUE TITLE
Cucumber 'not' tag expressions not working on command line

### ISSUE THREAD

**Issue by osmolyar** [webdriverio/webdriverio#5751] opened 2020-08-24 12:55 UTC
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version: 6.0.15
 - **Mode: Wdio testrunner (npx wdio conf.js)
 - **If WDIO Testrunner, running sync/async: Sync
 - **Node.js version: 12.9.0
 - **NPM version: 6.14.4
 - **Browser name and version: Chrome 83
 - **Platform name and version:. Windows 10
 - **Additional wdio packages used (if applicable): , @wdio/cucumber-framework

**Config of WebdriverIO**
 cucumberOpts; {

 tagExpression: 'not @Pending',

**Describe the bug**
-While the above configuration in wdio.conf works to exclude scenarios marked with the @Pending tag, and passing cucumberOpts.tagExpression '@Smoke', for example, on the command line also works to execute only the specified scenarios, there appears to be no way to specify 'not @Pending' on the command line.

Tried:
  --cucumberOpts.tagExpression 'not @Pending',
  --cucumberOpts.tagExpression 'Sanity and not @Pending',
  --cucumberOpts.tagExpression '~@Pending',
  --tagExpression 'not @Pending',
 --tags 'not @Pending'

Result: nothing gets run

**To Reproduce**
Steps to reproduce the behavior:  Set @Pending tag above a scenario or feature file and try passing one of above options to wdio on command line

**Expected behavior**
Expect scenarios marked @Pending not to be run

**Additional context**
Related discussion: amiya-pattnaik/webdriverIO-with-cucumberBDD#7

**Comment by mgrybyk** [comment] 2020-08-24 15:19
the command works fine in Linux and MacOS
`npm run test -- --cucumberOpts.tagExpression 'not @pending'`

![image](https://user-images.githubusercontent.com/25589559/91062997-b1da1e00-e62d-11ea-82d6-f60ea1093651.png)


@osmolyar may it be the case that you've passed args incorrectly? Please notice two extra dashes `--`.
I'd also suggest trying the same but without special characters like `@` or `~`.

**Comment by osmolyar** [comment] 2020-08-24 18:18
@mgrybyk , thanks for the reply.  Yes, I'm passing the argument using the two extra dashes.  The command line argument works fine without the 'not'; e.g.  --cucumberOpts.tagExpression "@Smoke".   (We have to use the '@' to indicate tags).  It's only when we try to use 'not' (in some cucumber versions also expressed as "~", hence tried that variant) that nothing gets run.

**Comment by christian-bromann** [comment] 2020-08-24 18:27
@osmolyar can you provide some reproducible steps for the basic example you get if you follow the configuration wizard?

**Comment by osmolyar** [comment] 2020-08-24 18:34
@christian-bromann , I could, but the steps are pretty simple:
1.  Put "@Pending" directly above a scenario or scenario outline (or feature name) in a Cucumber feature file
2.  Run as "npx wdio wdio.conf.js --cucumberOpts.tagExpression "not @Pending"

**Comment by mgrybyk** [comment] 2020-08-24 18:46
Lemme try with npx and get back

**Comment by osmolyar** [comment] 2020-08-24 18:52
Someone on the gitter channel also saw the same behavior with npm scripts defined as "wdio wdio.conf.js --  ***".    For them it also works with the same defined in the config file rather than command line, and also works with single tags passed on the command line, but not with operators (not, and, or).

**Comment by mgrybyk** [comment] 2020-08-24 20:00
`npx wdio --cucumberOpts.tagExpression 'not @pending'` works like a charm for me. Tried, just in case, another quotes `npx wdio --cucumberOpts.tagExpression "not @pending"`, works as well.

![image](https://user-images.githubusercontent.com/25589559/91090142-ead9b900-e654-11ea-9b0a-c7b93d7ba3e3.png)

**Comment by mgrybyk** [comment] 2020-08-24 20:19
@osmolyar ah, of course.
On windows you should use " instead of '.

Just tested on Windows 10, works fine with "

**Comment by osmolyar** [comment] 2020-08-24 20:23
With double quotes, I get an interesting error:

[0-2] 2020-08-24T20:21:09.213Z ERROR @wdio/local-runner: Failed launching test session: Error: empty stack
    at pop (C:\osmolyar_qdtools\qdtools\selenium\webdriverio\cucumber-template-project_v6\node_modules\cucumber-tag-expressions\src\tag_expression_parser.ts:143:11)
    at pushExpr (C:\osmolyar_qdtools\qdtools\selenium\webdriverio\cucumber-template-project_v6\node_modules\cucumber-tag-expressions\src\tag_expression_parser.ts:156:24)
    at parse (C:\osmolyar_qdtools\qdtools\selenium\webdriverio\cucumber-template-project_v6\node_modules\cucumber-tag-expressions\src\tag_expression_parser.ts:75:5)
    at new PickleFilter (C:\osmolyar_qdtools\qdtools\selenium\webdriverio\cucumber-template-project_v6\node_modules\cucumber\lib\pickle_filter.js:28:68)
    at CucumberAdapter.init (C:\osmolyar_qdtools\qdtools\selenium\webdriverio\cucumber-template-project_v6\node_modules\@wdio\cucumber-framework\build\index.js:59:28)
    at Object.adapterFactory.init (C:\osmolyar_qdtools\qdtools\selenium\webdriverio\cucumber-template-project_v6\node_modules\@wdio\cucumber-framework\build\index.js:288:34)
    at Runner.run (C:\osmolyar_qdtools\qdtools\selenium\webdriverio\cucumber-template-project_v6\node_modules\@wdio\runner\build\index.js:76:43)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

There are scenarios and a feature file with no @Pending tag, and nothing gets run in either case.  Things do get run as expected with '@Pending' or "@Pending".

**Comment by mgrybyk** [comment] 2020-08-25 08:02
The following `npm run test -- --cucumberOpts.tagExpression "@sanity or not @pending"` works for me.

@osmolyar  Can you please paste output of the command above here? Should look like this:

```
npm run test -- --cucumberOpts.tagExpression "@foo or not @pending"
...
> wdio "--cucumberOpts.tagExpression" "@foo or not @pending"
```
_notice `"@foo or not @pending"`_
In case quotes don't work you'll see
```
npm run test -- --cucumberOpts.tagExpression @foo or not @pending
...
> wdio "--cucumberOpts.tagExpression" "@foo" "or" "not" "@pending"
```
_notice now `"@foo" "or" "not" "@pending"`._ In such case only the first tag is processed. This is why you got `Error: empty stack` because passed only `not` as a tag which obviously causes the error in cucumber-js.

Let's compare versions of packages in `package.json` as well:
```
"dependencies": {
  "@wdio/cli": "^6.4.1",
  "@wdio/cucumber-framework": "^6.4.0",
  "@wdio/local-runner": "^6.4.1",
  "@wdio/sync": "^6.4.0"
}
```
If you are not on the latest version - please update first.

**Comment by mgrybyk** [comment] 2020-08-25 17:08
Yes, correct. On MacOS, Windows 10 Pro 2204, ubuntu lts.

Closing the issue for now as far as it looks like environment thing.

Feel free to ask further questions, we are here to help!

**Comment by christian-bromann** [comment] 2020-08-25 17:20
Also it would be great if we could document the environment difference in the docs if we can spot it.

**Comment by osmolyar** [comment] 2020-08-25 18:12
@mgrybyk  what is your npm version?  Mine are
**Node.js version: 12.9.0
**NPM version: 6.14.4

**Comment by mgrybyk** [comment] 2020-08-25 19:57
What cmd are you using?
Try 3 quotes in regular cmd ’"""@Pending and not @Sanity"""’ or 5 in powershell ’"""""@Pending and not @Sanity"""""’.

If you use git bash most likely nothing can work.

**Comment by osmolyar** [comment] 2020-08-25 20:04
cmd - yes, 3 quotes works!  wonder why the difference in usage

**Comment by christian-bromann** [comment] 2020-08-25 20:07
@osmolyar would you mind adding a sentence or two to [our docs](https://github.com/webdriverio/webdriverio/blob/master/docs/OrganizingTestSuites.md)?

**Comment by osmolyar** [comment] 2020-08-25 20:09
Yes but I'm still not sure in what case the 3 quotes are needed, since @mgrybyk didn't need to use them (in cmd I assume)

**Comment by mgrybyk** [comment] 2020-08-25 20:22
I believe it might be helpful to mention that on windows it might be required to use 3 quotes instead of one together with npx.

**Closed** 2020-08-26 21:35 UTC
Labels: Docs, good first pick, help wanted
