### ISSUE TITLE
Status for before/after hooks are displayed as unknown

### ISSUE THREAD

**Issue by raulcabero** [webdriverio/webdriverio#4856] opened 2019-12-05 13:22 UTC
**Describe your question with as much detail as possible**
I update my webdriverIO package to the last version "5.16.11" but the generated report now it is diplaying the before/after hooks executions and set the status for them as unknow

![image](https://user-images.githubusercontent.com/4942849/70238962-c04f7500-1740-11ea-80f8-777e981b3379.png)

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.16.11
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15.0
 - **NPM version:** 6.4.1
 - **Browser name and version:** 78.0.3904.108
 - **Platform name and version: Windows 10

**Comment by anandhaprakash-gartner** [comment] 2019-12-06 21:30
could you please prioritize this issue. we are also facing the same issue.

![image](https://user-images.githubusercontent.com/56091994/70357739-4650e600-183d-11ea-9312-e7bdb5ab6ebe.png)

**Comment by christian-bromann** [comment] 2019-12-06 22:14
> could you please prioritize this issue

We appreciate any form of contribution on this issue. Cheers!

**Comment by woolter** [comment] 2019-12-11 10:19
This can be reproduced with this code

```
describe('test', () => {
  before(() => {
    expect(true).be.equal(true);
  });
  it('first it', () => {
    expect(true).be.equal(true);
  });
});
```

and this configuration
```
[
      'allure',
      {
        disableMochaHooks: false,
      },
],
```

**Comment by woolter** [comment] 2019-12-11 14:55
I have the fix for this bug, I'm working to fix `beforeEach`

**Comment by woolter** [comment] 2019-12-12 09:34
@luiscspinho @christian-bromann @mgrybyk 
I've found the problem but I don't understand some lines in the code and with my fix the test fails.
Maybe I'm wrong because something that I didn't understand, but the test should keep the pass/fail hook no matter if there are or not steps.
![image](https://user-images.githubusercontent.com/12902748/70699344-3fa4f180-1cc9-11ea-97ed-5bd501fe9108.png)

The problem that I found is imposible to reach this line because the previous `if`.
![image](https://user-images.githubusercontent.com/12902748/70698915-a1189080-1cc8-11ea-91d3-4e10406dc6df.png)
If you move the `else if` to the next line, you are going to have all pass/fail status for `mochaAllHooks`

This only works for `mochaAllHooks`.
For `mochaEachHooks` because the title has the same name the problems still existing.

If make sense to change the test I can do the PR

**Comment by luiscspinho** [comment] 2019-12-12 10:11
There is indeed a bug and that `if` should be on the next line exactly how you said.

To fix the each hooks, you've to add exactly the same logic on each condition here https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-allure-reporter/src/index.js#L253

I can help you with that if you want 👍

**Comment by woolter** [comment] 2019-12-12 11:04
@luiscspinho thanks for validating this.

But about `mochaEachHooks` doesn't work, I have `disableMochaHooks: false` and skip the if. 
In the way that is implemented at this moment I have results for `"before each" hook` but because have the same name I don't get the right result, the second overwrite the first one
![image](https://user-images.githubusercontent.com/12902748/70706578-6fa6c180-1cd6-11ea-832a-585226ab49df.png)
If we are able to add the `uid` for example to the "test name (title)" (**"before each" hook 00-1**) is going to work, but I couldn't fin a way yet

Here the test that I'm using
```
describe('test A', () => {
  describe('test A1', () => {
    let a = 0;
    beforeEach(,() => {
      console.log('Hook Start beforeEach');
      a++;
      browser.pause(2000);
      expect(true).be.equal(true);
    });
    it('first it', () => {
      console.log('It Start test 1');
      browser.pause(2000);
      expect(true).be.equal(true);
    });
    it('Second it', () => {
      console.log('It Start test 2');
      browser.pause(2000);
      expect(true).be.equal(true);
    });
  });
  describe('test A2', () => {
    let a = 0;
    beforeEach(,() => {
      console.log('Hook Start beforeEach');
      a++;
      browser.pause(2000);
      if (a < 2) {
        expect(true).be.equal(true);
      } else {
        expect(true).be.equal(false);
      }
    });
    it('first it', () => {
      console.log('It Start test 1');
      browser.pause(2000);
      expect(true).be.equal(true);
    });
    it('Second it', () => {
      console.log('It Start test 2');
      browser.pause(2000);
      expect(true).be.equal(true);
    });
  });
  describe('test A3', () => {
    let a = 0;
    beforeEach(,() => {
      console.log('Hook Start beforeEach');
      a++;
      browser.pause(2000);
      expect(true).be.equal(false);
    });
    it('first it', () => {
      console.log('It Start test 1');
      browser.pause(2000);
      expect(true).be.equal(true);
    });
    it('Second it', () => {
      console.log('It Start test 2');
      browser.pause(2000);
      expect(true).be.equal(true);
    });
  });
});
```

**Comment by luiscspinho** [comment] 2019-12-12 11:12
That is not related to the flag, that was happening already without the introduction of the flag. Let me dig in a little bit and I'll get back to you.

**Comment by luiscspinho** [comment] 2019-12-12 11:53
@woolter is it me, or the very first "beforeEach" hook is not being catched by the reporter? I see the "beforeAll" at the start of the test, but the very first "beforeEach" is not catched by the  `onHookEnd` function?

**Comment by woolter** [comment] 2019-12-12 12:01
it's catched but because has the same name you are not able to see it, happen the same if you have 2 test with the same name, this is a completed different bug. But I found it trying to test it this one.

**Comment by luiscspinho** [comment] 2019-12-12 12:30
Yes, but I think that may be one of the main issues here. I could get the "beforeEach" to work as a substep of the `it`, but as a "test" itself (like the before all) it'll be impossible because if you have more than 1 `it`, it'll be overriden. We could add the  **hook 00-1** like you mentioned, but it'll still be overriden if you have more than 1 `it`.

I think that this is a bigger issue and it'll need a different approach. Leaving it as a substep of each `it` might not be the worst idea, although it'll create inconsistencies in the report, which is not ideal.

**Comment by luiscspinho** [comment] 2019-12-12 12:35
This is what I'm refering to:
![image](https://user-images.githubusercontent.com/2779419/70712548-ee522d80-1cdb-11ea-9775-175221152a1b.png)

**Closed** 2019-12-12 13:22 UTC
Labels: Bug🐛, good first pick, help wanted
