### ISSUE TITLE
Better, more explicitly named reverse waitFor functions

### ISSUE THREAD

**Issue by codeclown** [webdriverio/webdriverio#2551] opened 2018-01-17 00:29 UTC
## Current status

There are several waitForSomething functions:

```js
waitForEnabled('.foobar')
waitForExist('.foobar')
waitForSelected('.foobar')
waitForText('.foobar')
waitForValue('.foobar')
waitForVisible('.foobar')
```

All of these can be "reversed" with the third argument they take:

```js
waitForEnabled('.foobar', null, true)
waitForExist('.foobar', null, true)
// etc.
```

## The problem

This is not very readable. It is not immediately clear what these arguments do. It's especially confusing because `timeout` has to be specified (in 99% of cases it's `null` because there is no need to override the default timeout).

When reading test code, it's not intuitive to first read "wait for visible" and then have to decipher that the line is actually "waiting for not visible".

## Proposal

Introduce more explicitly named functions:

```js
waitForDisabled('.foobar')
waitForNotExist('.foobar')
// etc.
```

I found [one issue](https://github.com/webdriverio/webdriverio/issues/869) regarding this but it seems more like a "how to do" question rather than discussion about the API namings.

**Comment by millerick** [comment] 2018-01-17 01:08
Can be added as custom commands on an as-needed basis.  This is what I've done in my webdriverio project.  In my `wdio.conf.js`:
```
  before: async function(config, capabilities) {
    /**
     * Add custom commands here and they will be available in all tests.
     */
    await browser.addCommand('waitForNotVisible', async function(selector) {
      return await browser.waitForVisible(selector, common.defaultWait, true);
    });
  },
```
It gives you a way to implement these yourself.

**Comment by Tallyb** [comment] 2018-01-17 11:43
Set timeout to undefined and the default will be applied. Not that bad, IMO.

**Comment by codeclown** [comment] 2018-01-20 19:03
There are already convenience functions available, even though those functions could be implemented by the developer as custom commands when needed.

Example: `setValue` could be removed because what it achieves could be easily implemented by each developer using `keys`.

Therefore I don't see the point of opposing a couple of more convenience functions.

---

I can think of two arguments against doing so:

1. "Can be done already", as mentioned in this thread. I think the focus of the project should be to allow writing readable tests out-of-the-box, as I explained above.

2. Increases amount of functions. True, but the amount of functions is already quite high and adding these new ones would not raise it radically.

**Comment by mherodev** [comment] 2018-01-21 02:31
Also, custom commands aren't as convenient as native functions. They always have to be called off of the `browser` object instead of from an `element` like you'd prefer.

**Comment by jedwards1211** [comment] 2018-01-26 16:20
Duplicate of https://github.com/webdriverio/webdriverio/issues/2307

**Comment by abjerstedt** [comment] 2018-01-31 03:49
@mherodev That is inaccurate. You can chain with customCommands just the same as you can with native commands. You can even rewrite your version of a command with addCommand overrides.

I just today submitted a PR to my project that overrides click() with a version that will repeatedly try for a while (the animations on our project are a pain in the ass).

**Comment by mherodev** [comment] 2018-01-31 04:06
I have had nothing but trouble using chaining. It's very inconsistent, at least when using ES6 Page Objects and the Synchronous runner. Maybe it's different in other environments.

But hey, if you love seeing `Cannot get "indexOf" of undefined` errors, live that life! From where I stand, the contributors to this repo must have a different environment because I am having a very different experience.

**Comment by christian-bromann** [comment] 2018-01-31 07:40
I would just not use custom commands anymore. With the synchronous testrunner you can nicely abstract everything away in a page object. Custom commands is a legacy from when we chained all commands.

**Comment by abjerstedt** [comment] 2018-01-31 16:42
@christian-bromann custom commands give us the ability to maintain the element as a first class citizen, and to wrap your implementations of commands with custom handling.

**Comment by codeclown** [comment] 2018-01-31 17:05
I also have not been able to chain a custom command (I may have implemented it wrong, but my implementation was equal to what was posted above in this thread). I ended up not trying, and just regressed back to the more confusing `browser.element('...').waitForVisible(null, true)`.

---

@christian-bromann 

> I would just not use custom commands anymore.

I don't understand how this relates to the discussion. Should `addCommand` be just deprecated if using it is not advised at all?

At the moment we (=users) have two choices:
- `waitForVisible(selector, null, true)`, or
- a custom command `waitForNotVisible(selector)` (inferior because it does not reliably work when chained)

Saying to not use custom commands is guiding us back to square one.

I am ignoring abstracting ugly stuff to page objects as an option because that is a further pattern and a choice, not a library API.

---

I still propose that this library should be consistent and provide these reversed functions out of the box. Are there any arguments against doing so, other than "can already do this through a hoop"?

**Comment by abjerstedt** [comment] 2018-01-31 17:28
@codeclown I coincidentally spent all afternoon/evening playing with the chaining component and discovered its pretty particular about how you pass the context.

I didn't test this .. but:
browser.addCommand(  'waitForNotVisible', function(selector) {
    this.element.waitforVisible(undefined,true);
});

Note using the "this" context versus the "browser" context.

Heres my .click() (chainable) override that i created:

>     browser.addCommand(
>       'click',
>       function(selector) {
>         let el = this.element(selector);
> 
>         browser.waitUntil(function() {
>           if (!el.isVisible()) return false;
> 
>           try {
>             browser.elementIdClick(el.value.ELEMENT);
>             return true;
>           } catch (err) {
>             console.warn(`${err}`.replace('Error', 'WARN'));
>             return false;
>           }
>         });
>       },
>       true
>     );

**Comment by mherodev** [comment] 2018-02-01 23:12
It's likely I was having chaining issues explicitly within Firefox or Edge drivers. I did some testing now that we've dropped other drivers (we're Chrome-only) and chaining with custom commands seems to work, at least at first blush.

**Comment by jedwards1211** [comment] 2018-02-01 23:15
@christian-bromann with the synchronous testrunner you can use a nice native code hack that will necessarily always lag behind the latest version of node.

It really doesn't seem right to me to treat the synchronous testrunner as the first-class citizen and the pure JS testrunner as the second-class citizen.

**Comment by christian-bromann** [comment] 2018-02-01 23:17
> with the synchronous testrunner you can use a nice native code hack that will necessarily always lag behind the latest version of node

What do you mean by that?

> and the pure JS testrunner as the second-class citizen

Any arguments on that why?

**Comment by jedwards1211** [comment] 2018-02-01 23:21
@christian-bromann the synchronous testrunner relies on `node-fibers`, which relies on native code to patch coroutine support onto the VM.  Any time there's a breaking change to the relevant V8 C++ interfaces used in node, `node-fibers` has to be updated to work with it, as far as I understand.  That's one of several reasons I prefer not to use `node-fibers` or the synchronous testrunner.

I don't use custom commands myself, but I'm concerned about the async capabilities being neglected.  I wouldn't want something to become horribly awkward to accomplish without using `node-fibers`.

**Comment by jedwards1211** [comment] 2018-02-01 23:25
@christian-bromann when using `node-fibers` you also get to deal with awkward issues like [node 8 binary fails on Travis CI](node 8 binary fails on travis-ci)

**Comment by christian-bromann** [comment] 2018-02-01 23:27
I am not sure what this has to do with the origin thread issues. However in my experience it didn't take long until node-fibers was compatible with new node versions. Additionally you don't always need to immediately run latest NodeJS version for your tests. Fibers has not been problematic since starting to use it.

You don't have to use the sync mode. Everything should work equally. If not, feel free to provide a PR.

> when using node-fibers you also get to deal with awkward issues like [node 8 binary fails on Travis CI](node 8 binary fails on travis-ci)

Not sure why that is but again, use node7 until this is resolved, resolve it by yourself and submit a PR or use async mode.

**Comment by jedwards1211** [comment] 2018-02-01 23:37
@christian-bromann I brought it up because earlier in this thread you said

> I would just not use custom commands anymore. With the synchronous testrunner you can nicely abstract everything away in a page object. Custom commands is a legacy from when we chained all commands.

Which sounds like you're saying you only care about the dev experience of people who are willing to use the synchronous testrunner.

**Comment by christian-bromann** [comment] 2018-02-01 23:41
I will always advocate the sync runner because I don't understand why you would want to deal with async/await and promises if you can have these commands being synchronised. However people are free to do so. You can of course abstract custom commands away in PO with async testrunner.

**Comment by christian-bromann** [comment] 2018-10-31 23:22
Duplicate of #2307

**Closed by christian-bromann** 2018-10-31 23:22 UTC
Labels: Discussion
