### ISSUE TITLE
Firefox "-headless" gets stuck on 100% CPU and leaks 50mb/s

### ISSUE THREAD

**Issue by mo** [webdriverio/webdriverio#4718] opened 2019-11-01 11:04 UTC
repro steps:

git clone git@github.com:mo/wdio-webdriver-geckodriver-firefox-memory-leak.git
npm install
npm test
actual:
Even though test case is just "open google.com and then wait 2 sec", Firefox gets stuck at 100% CPU and leaks 50mb/s until crash. If I remove the "-headless" arg from moz:firefoxOptions (in wdio.conf.js) the same TC passes without problems. I see the bug in "htop" where the RES column keeps increasing aggressively:

https://i.imgur.com/CMd97Jw.png

Versions:
selenium 3.141.59 (pinned at the top of wdio.conf.js)
geckodriver 0.26.0 (pinned at the top of wdio.conf.js)
firefox 70 (which is what I have installed)

The bug repro project can also run with a custom Firefox binary if you set env var EE_FIREFOX_BINARY. For example, I can also repro the bug by running:

EE_FIREFOX_BINARY=~/firefox/65.0.2/firefox/firefox npm test

I have also tried various other combinations of selenium/geckodriver/firefox.

**Comment by mgrybyk** [comment] 2019-11-01 14:45
@mo hint regarding wdio.conf.js (not related to the issue), the following properties does nothing and can be removed:
- sync: true,
- coloredLogs: true,

**Comment by mgrybyk** [comment] 2019-11-01 14:53
So I did the following:
1. commented out chrome in your capabilities (only because I have a newer version and don't want to change anything)
2. commented out `binary: process.env.EE_FIREFOX_BINARY,` in firefox capabilities
3. added `args: ['-headless', '--window-size=1280,800'],` to firefox capabilities
4. removed all your custom login starting from `if (!process.env.EE_HEADLESS`

firefox works just fine in headless mode.

Closing the issue for now because it looks like something selenium/geckodriver/binary related or your custom logic.

![image](https://user-images.githubusercontent.com/25589559/68033245-95947b80-fcbf-11e9-9aeb-48a874c5862e.png)

I'm happy to answer further questions

**Closed by mgrybyk** 2019-11-01 14:53 UTC

**Comment by mo** [comment] 2019-11-01 15:20
@mgrybyk I commited the simplification changes you suggested now in dca9631 and for me headless firefox still hangs / fails to run. Did you see the bug before happen you did those changes?

**Comment by mgrybyk** [comment] 2019-11-01 15:38
@mo nope. Have you killed all java, firefox and geckodriver instances before trying again? If you can you may just reboot your PC.

What version of firefox do you have? Mine is 69.0.3 64 bit. Just updated it to 70.0.1 and still works fine in headless mode

**Comment by mgrybyk** [comment] 2019-11-01 15:40
Just pulled and removed my changes, still works fine in headless mode

**Comment by mgrybyk** [comment] 2019-11-01 15:40
I'm on macos 10.13.6

**Comment by mo** [comment] 2019-11-01 16:09
@mgrybyk which firefox version are you using?

**Comment by mgrybyk** [comment] 2019-11-01 16:40
https://github.com/webdriverio/webdriverio/issues/4718#issuecomment-548835061

**Comment by mo** [comment] 2019-11-01 19:22
I filed this as a geckodriver bug and we came to the conclusion that for me Firefox 64.0.2 works (no bug) but Firefox 65.0 and later has the bug. I used the mozregression to track down the specific Firefox commit that caused it and it was these ones:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=e762fce85daa2b0399f443c4644c6e61a11b1eb3&tochange=6fc6bdea42a60b7e3fb426beb073e07a3922913c

...this explains why you don't see the bug (since you're on MacOS and the commits are related to Wayland/Linux).

I then installed a bunch of system updates in Ubuntu and rebooted the machine, and after that the tests were passing again (both regular and headless).

Thanks a lot for taking a look at the issue though!

**Comment by mo** [comment] 2019-11-01 19:23
For posterity; the geckodriver bug I filed is here:
https://github.com/mozilla/geckodriver/issues/1646

...and the Firefox bug is here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1587698

**Comment by christian-bromann** [comment] 2019-11-01 22:18
> Thanks a lot for taking a look at the issue though!

Good job hunting down the root cause 👏

**Comment by timb07** [comment] 2019-12-11 21:22
In case anyone else comes across this issue, it only occurs after the machine has been up for a period of time (unknown how long as yet, but over 4 days and possibly up to 2 months); see https://bugzilla.mozilla.org/show_bug.cgi?id=1587698 for more discussion.

**Comment by rahulvit2010** [comment] 2020-06-24 14:13
i am also facing the more cpu usage issue in Mozilla 60.7.0 esr
