### ISSUE TITLE
[🐛 Bug]: drag and drop

### ISSUE THREAD

**Issue by davefogo** [webdriverio/webdriverio#8436] opened 2022-06-16 17:57 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.12.1

### Node.js Version

16.0.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  browserName: 'chrome',
  acceptInsecureCerts: true,
  platformName: 'mac'
}
```

### What happened?

Environment

Mac OS 12.4 (21F79)
Chrome 102.0.5005.115 

When using $(selector).dragAndDrop(target) The function was able to grab the element but it doesn't drag it to the destination. The element stays at the position of the mouse. If I manually move the mouse to the destination it does drop correctly.

I have read all of the comments on [https://github.com/webdriverio/webdriverio/issues/4134](Issue) but still can't figure it out.

### What is your expected behavior?

Expected the image to be dragged and dropped at the desired location.

### How to reproduce the bug.

git clone git@github.com:davefogo/drag-and-drop-demo.git
cd into drag-and-drop-demo
modify file location to match the folder your cloned copy resides @ drag-drop-demo/test/specs/example.e2e.js 
e.g       `file:///Users/dforero/Workspace/training/selenium/drag-drop-demo/index.html` -> `file:///Users/johnsmit/Downloads/drag-drop-demo/index.html`
save
npm install
npm run wdio

### Relevant log output

```typescript
None relevant.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2022-06-20 15:14
Duplicate of #8022

**Closed by christian-bromann** 2022-06-20 15:14 UTC
Labels: Bug 🐛, Needs Triaging ⏳
