### ISSUE TITLE
Cannot run features using tags

### ISSUE THREAD

**Issue by claudiuionita** [webdriverio/webdriverio#1777] opened 2016-12-19 20:23 UTC
> I've added some tags to my feature files and but they seem to be ignored.

> Steps: add a @tag to a feature file and then run it (wdio --tags=@auth).

> Expected:  I expect that the feature file containing @tag to run

> Actual: Browser opened, url did not load, it looked like @pending tags are running

> Windows 10 / Chrome 

Using this exact setup: https://github.com/webdriverio/cucumber-boilerplate

**Comment by christian-bromann** [comment] 2016-12-19 20:31
duplicate of #1247

**Closed by christian-bromann** 2016-12-19 20:31 UTC
