### ISSUE TITLE
test process hangs when used in node exec() / spawn() context

### ISSUE THREAD

**Issue by poisonborz** [webdriverio/webdriverio#2678] opened 2018-04-03 11:44 UTC
If I run my test like `node_modules/.bin/wdio conf.js` from terminal or an npm task, the process runs fine. However if I try to run the same with node's exec()  - to filter stdout - the process just hangs, without producing any output. Same if I try to run the npm task from within exec().

If I run the command without the conf.js parameter the process executes normally with the wizard prompt.

Is there any caveat in running from this context?

**Comment by christian-bromann** [comment] 2018-04-03 11:47
Duplicate of #2624

**Closed by christian-bromann** 2018-04-03 11:47 UTC
