### ISSUE TITLE
waitForClickable() returning error on IE

### ISSUE THREAD

**Issue by j320** [webdriverio/webdriverio#5269] opened 2020-04-15 10:45 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:**  6.0.16 | Also reproduced in v5
 - **Mode:** Standalone
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.16.1
 - **Browser name and version:** IE11
 - **Platform name and version:** [e.g. Windows 10]

**Config of WebdriverIO**
```
capabilities: [{
    browserName: 'internet explorer',
    "se:ieOptions": {
      ignoreZoomSetting: true,
      nativeEvents: false,
      "ie.ensureCleanSession": true
    }
  }
]
```
Also tested with nativeEvents set to **true** or not added as a capability at all, plus removing the _ensureCleanSession_ as well.

**To Reproduce**

In your tests, target them to IE and use `selector.waitForClickable(waitTime)`

**Expected behavior**
The driver waits for the element to be clickable

**Log**
` Request failed with status 500 due to Error executing JavaScript`
`waitUntil condition failed with the following reason: Error executing JavaScript`

**Comment by christian-bromann** [comment] 2020-04-15 11:01
Duplicate of #5043

**Closed by christian-bromann** 2020-04-15 11:01 UTC
