### ISSUE TITLE
browser.addCommand fails when using mutliremote

### ISSUE THREAD

**Issue by pmerwin** [webdriverio/webdriverio#2949] opened 2018-09-10 20:55 UTC
## The problem

using browser.addcommand() with a multi-remote config is failing

## Environment

* WebdriverIO version: v5.0.0-beta.2
* Node.js version: 8.10
* Standalone mode or WDIO Testrunner: either
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable):

## Link to Selenium/WebdriverIO logs

2018-09-10T20:53:29.415Z ERROR wdio-sync: TypeError: commandWrapper is not a function
    at MultiRemoteDriver.commandWrapper [as addCommand] (/Users/pmerwin/Projects/qa/lib-webdriverio5-nodejs/node_modules/webdriver/src/monad.js:64:29)
    at Object.before (/Users/pmerwin/Projects/qa/lib-webdriverio5-nodejs/lib/wdio/base.js:384:17)
    at apply (/Users/pmerwin/Projects/qa/lib-webdriverio5-nodejs/node_modules/wdio-sync/src/executeHooksWithArgs.js:35:31)

## Code To Reproduce Issue [ Good To Have ]

config:

```

exports.config = merge(wdioBaseConf.config, {

    user: config.saucelabs.user,
    key: config.saucelabs.key,
    baseUrl: 'ondemand.saucelabs.com',
    maxInstances: 1,
    capabilities: {
        chrome1: {
            capabilities: {
                extendedDebugging: true,
                capturePerformance: true,
                browserName: 'chrome',
                platform: 'OSX 10.12',
                name: 'chrome1FeoOn',
                chromeOptions: {
                    args: ['incognito']
                }
            }
        },
        chrome2: {
            capabilities: {
                extendedDebugging: true,
                capturePerformance: true,
                browserName: 'chrome',
                platform: 'OSX 10.12',
                name: 'chrome2FeoOff',
                chromeOptions: {
                    args: ['incognito']
                }
            }
        }
    },
    mochaOpts: {
        ui: 'bdd',
        timeout: 600000,
        bail: true
    },
    services: ['sauce'],
    deprecationWarnings: false,
});
```

**Comment by christian-bromann** [comment] 2018-09-18 22:45
Duplicate of #2073

**Closed by christian-bromann** 2018-09-18 22:45 UTC
