### ISSUE TITLE
Link failed test to screenshot (taken after test failure)

### ISSUE THREAD

**Issue by SchwaFa** [webdriverio/webdriverio#819] opened 2015-10-07 08:47 UTC
I'm trying to create a custom reporter, which also includes the screenshots that are taken on failures. 

Is there any possibility to get the screenshot path and filename from within the reporter on "test:fail"?

**Comment by christian-bromann** [comment] 2015-10-28 21:40
Unfortunately not. Reporter shouldn't be able to do that imho. They only should gather data from tests and print them (no execution of additional commands etc.). I guess the desired functionality is something like a onError hook that can execute additional commands if something errors.

**Comment by christian-bromann** [comment] 2015-10-28 21:41
ok duplicate of #810

**Comment by SchwaFa** [comment] 2015-11-02 14:22
I think you misunerstood my problem: ;)
In my oppinion, a reporter should gather all information about the tests and present them in a nice AND useful way. So what I would expect and what we have in a different project (not using webdriver.io, only Java and Selenium):
A test report that shows the test results. If a test failed, it shows the WebDriver error message (or e.g. the Jasmine error) AND the screenshot that was automatically taken for that particular failed test.
This means, that of course the screenshot itself is not taken by the reporter, but the reporter links it to the failed test.
A test report of end-2-end UI tests without screenshots attached to failed tests is almost useless, since one needs to manually look for the proper screenshot file or debug the code in order to find out what went wrong. 
WebDriverIO already takes screenshots automatically, but those are just written to a directory (specified in wdio.conf.js) and there are no links to them in the reporter.

**Comment by christian-bromann** [comment] 2015-11-02 16:11
Gotcha. So we have to ensure two things:
1. a screenshot is taken right after a test failed
2. the path to the screenshot has to be propagated to the `test:failed` event

Both are tasks of the framework adapters. I will try to implement this into the new wdio adapter packages ([wdio-mocha-framework](https://github.com/webdriverio/wdio-mocha-framework) and [wdio-jasmine-framework](https://github.com/webdriverio/wdio-jasmine-framework)).

**Comment by SchwaFa** [comment] 2015-11-02 16:20
Exactly. 
That sounds great, thanks a lot! :)

**Comment by vincentsaluzzo** [comment] 2016-01-13 14:08
Hi, it possible to have a refresh in the status of this issue ?

I will try to create a custom reporter for our company but we absolutely need the capacity to have the screenshot data (or the path) in test object passing to the reporter.

Thanks

**Comment by sipayRT** [comment] 2016-02-10 12:20
We also need this ability. Taking screenshot without any ability to use it in the report is to strange

**Comment by aaronbriel** [comment] 2016-02-22 21:18
This is outside of webdriverio so I apologize if this is inappropriate, but I did an enhancement to mocha-jenkins-reporter that does exactly this which is pending approval of the pull request: https://github.com/juhovh/mocha-jenkins-reporter/pull/33

**Comment by aaronbriel** [comment] 2016-03-07 01:01
Whats up yall - just wanted to give you a heads up if you're using mocha that i added screenshot capability to [mocha-jenkins-reporter](https://github.com/juhovh/mocha-jenkins-reporter) and the pull request was approved...

**Comment by christian-bromann** [comment] 2016-07-20 14:36
Let's continue conversation in #1441

**Closed by christian-bromann** 2016-07-20 14:36 UTC
Labels: Enhancement
