### ISSUE TITLE
Notify user about modifier keys [CTRL, SHIFT, META, ALT]

### ISSUE THREAD

**Issue by erwinheitzman** [webdriverio/webdriverio#4440] opened 2019-09-03 08:14 UTC
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**
The modifier keys do not stay pressed when passed directly but do stay pressed when passed as an array.

**Comment by AlexandreBonneau** [comment] 2019-09-03 08:17
I can confirm you need to include the `Shift` key in the array for it to be taken into account in Firefox.
In Chromium there is no such need ; a separate call `browser.keys('Shift');` will do.

**Comment by motss** [comment] 2019-12-22 16:08
Also having this problem on Firefox. With the following code, Chrome works totally fine.

```ts
browser.keys(['Alt', 'PageUp']);
```

**Comment by erwinheitzman** [comment] 2019-12-24 13:24
Completely forgot about this. Since I have some time off I'll update the documentation or perhaps I will see if I can implement a fix for this.

**Comment by motss** [comment] 2019-12-25 15:18
@erwinheitzman It behaves differently on different platforms as I was expecting `browser.keys(['Alt', 'PageUp'])` to trigger `KeyboardEvent.altKey` alongside another key based on `KeyboardEvent.keyCode` on all platforms. On non-Chrome browsers, it becomes 2 `KeyboardEvent.keyCode` instead and `KeyboardEvent.altKey` never sets to true.

Hope this can be helpful on a fix for this issue.

**Comment by christian-bromann** [comment] 2020-02-10 09:21
@erwinheitzman what kind of documentation change do you want to see?

**Comment by christian-bromann** [comment] 2020-09-15 09:12
Closing due to inactivity.

**Closed by christian-bromann** 2020-09-15 09:12 UTC

**Comment by AlexandreBonneau** [comment] 2021-04-13 18:05
I'm a bit late to the party, but since it seems to be a documentation problem, shouldn't it remain open?

**Comment by christian-bromann** [comment] 2021-04-13 18:10
This issue has been closed because the requirements to make the documentation change remained unavailable. If you think the docs could be better around modifier keys, please provide more detailed information how they can be improved. I would be happy to re-open then.
