### ISSUE TITLE
Chrome stays open after I Ctrl-C tests with webdriverio v6.  On webdriverio v4 it would close chrome when I Ctrl-C

### ISSUE THREAD

**Issue by jedwards1211** [webdriverio/webdriverio#6138] opened 2020-11-20 06:01 UTC
I'm not sure what changed or if it was intentional, but with webdriverio v4, if I killed my test process with Ctrl-C, it would close the Chrome windows as well.  Now that I upgraded to v6, the Chrome windows stay open.  I suspect zombie processes stick around in headless mode too but I'm not sure.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [6.9.0]
 - **Mode:** [Standalone]
 - **Node.js version:** [12.16.0]
 - **Yarn version:** [1.22.0]
 - **Browser name and version:** [Chrome 86.0.4240.198]
 - **Platform name and version:** [macOS Catalina 10.15.7]
 - **selenium-standalone version:** [6.20.1]

**Config of WebdriverIO**

Simplified example:
```js
import * as webdriverio from 'webdriverio'
import { describe, before, after } from 'mocha'
import { promisify } from 'util'
import glob from 'glob'

let seleniumConfigs = [
  {
    capabilities: {
      browserName: 'chrome',
      'goog:chromeOptions': {
        args: ['--disable-gpu'],
      },
    },
  },
  {
    capabilities: {
      browserName: 'firefox',
    },
  },
]

describe('selenium tests', function() {
  this.timeout(60000)

  let selenium

  before(async function() {
    this.timeout(180000)
    selenium = await promisify(cb => require('selenium-standalone').start(cb))()
  })

  after(async function() {
    if (selenium) selenium.kill()
  })

  seleniumConfigs.forEach((config: any) => {
    const { capabilities: { browserName } } = config

    describe(browserName, function() {
      before(async function() {
        browser = await webdriverio.remote(config)
        await browser.setWindowSize(1200, 800)
      })
      after(async function() {
        if (browser) {
          await browser.closeWindow()
          await browser.deleteSession()
        }
      })

      const tests = glob.sync(path.join(__dirname, 'tests', '**', '*.js'))
      for (const test of tests) {
        const setup = require(test)
        if (!(setup instanceof Function)) {
          throw new Error(`test file must export a function: ${test}`)
        }
        setup()
      }
    })
  })
})
```
**Describe the bug**
If I kill the tests with Ctrl-C, the Chrome window stays open.  This didn't happen with webdriverio v4.

**To Reproduce**

1. Start tests with the above code
2. Ctrl-C to kill tests before they finish

**Expected behavior**

Same as webdriverio v4, where the instance of Chrome launched for testing gets killed when I kill my test process

**Comment by christian-bromann** [comment] 2020-11-20 07:45
@jedwards1211 can you provide a simplified reproducible example? If you press CTRL+C the browser would also stay open in v4 because it needs a session delete request to close it. That wasn't any different from v4.

**Comment by jedwards1211** [comment] 2020-11-20 16:18
What form exactly, like a repo?
That wasn't my experience with v4, I wonder if it was launching the browser as a subprocess and that's why it seemed to get terminated as well?

**Comment by BorisOsipov** [comment] 2020-11-20 16:30
@jedwards1211 

ctrl+c closes browser as well as terminate tests with log:
```
...
[0-0] RUNNING in chrome - C:\Temp\wdio-v5-jasmine\specs\sample.spec.js


Ending WebDriver sessions gracefully ...
(press ctrl+c again to hard kill the runner)
0-0 worker finisedCommand { command: 'endSession' }

```

BUT in `WDIO Testrunner mode` only. It worked in v4 and works for v6 as well.

If you use `Standalone Mode` (as I can see in example in first pots) you are responsible for closing browser.

**Comment by jedwards1211** [comment] 2020-11-20 16:36
Wouldn't `webdriverio` core be a better place for whatever hooks the WDIO testrunner is using for that?

**Comment by BorisOsipov** [comment] 2020-11-20 16:54
>Wouldn't webdriverio core be a better place for whatever hooks the WDIO testrunner is using for that?

I am not sure. `webdriverio` is selenium client, just provides an api with some sweeties. If you need full browser lifecycle management use wdio runner or write your own :)

**Comment by jedwards1211** [comment] 2020-11-20 17:05
well, I'm fine with adding my own hooks if need be, I just got the impression `webdriverio` was supposed to clean up the processes since it was somehow happening for me with v4

**Comment by christian-bromann** [comment] 2020-11-20 23:28
We haven't changed anything in this regards. It should still work in v6 if it worked in v4 even though I doubt it was working in v4 either. I will close this as I agree with the points @BorisOsipov made.

**Closed by christian-bromann** 2020-11-20 23:28 UTC
Labels: Reproducible Example Missing
