### ISSUE TITLE
ReporterStats throws a TypeError if nested test suites are in a single spec.

### ISSUE THREAD

**Issue by jaysirju** [webdriverio/webdriverio#1624] opened 2016-09-30 19:42 UTC
## The problem
TypeError: Cannot set property 'state' of undefined is thrown when one of my tests fail.  The problematic spec has nested test suites (onlined in the details section).

## Environment

* WebdriverIO version: 4.2.16
* Node.js version: 5.9.0
* using wdio testrunner
* synchronous test mode
* Additional wdio packages used (if applicable):
     "wdio-allure-reporter": "^0.1.1",
    "wdio-mocha-framework": "^0.4.0",
    "wdio-sauce-service": "^0.2.4",

## Details

I have a spec that follows the following format:

```
testSuite {
 suiteSetup
  testSuiteChildA {
    testA
    testB
  }
  testSuiteChildB {
    testA
  }
}
```

If something fails when utilizing the sauce service in my config file, I recieve the following TypeError:
```
<path>/webdriverio/build/lib/utils/ReporterStats.js:403
            testStats.state = 'fail';

TypeError: Cannot set property 'state' of undefined
    at ReporterStats.testFail (/Users/jaysirju/Animoto/stack/applications/web2/node_modules/webdriverio/build/lib/utils/ReporterStats.js:403:29)
    at BaseReporter.<anonymous> (/Users/jaysirju/Animoto/stack/applications/web2/node_modules/webdriverio/build/lib/utils/BaseReporter.js:159:25)
    at emitOne (events.js:90:13)
    at BaseReporter.emit (events.js:182:7)
    at BaseReporter.handleEvent (/Users/jaysirju/Animoto/stack/applications/web2/node_modules/webdriverio/build/lib/utils/BaseReporter.js:300:27)
    at Launcher.messageHandler (/Users/jaysirju/Animoto/stack/applications/web2/node_modules/webdriverio/build/lib/launcher.js:590:28)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:718:10)
    at Pipe.channel.onread (internal/child_process.js:444:11)_
```

**Comment by christian-bromann** [comment] 2016-10-01 13:01
@jaysirju do you have an example spec file that reproduces this issue?

**Comment by jaysirju** [comment] 2016-10-02 22:42
I can't share out the specific spec, but the general format is outlined in the issue.

This is actually looking like it is related to using the wdio-sauce-service.  I'll investigate more follow up

**Comment by christian-bromann** [comment] 2016-10-08 13:19
duplicate of #1621

**Closed by christian-bromann** 2016-10-08 13:19 UTC
Labels: Bug
