### ISSUE TITLE
Element click doesn't work on Safari 13

### ISSUE THREAD

**Issue by fariaslari** [webdriverio/webdriverio#4565] opened 2019-10-03 19:33 UTC
**Environment:**
 - **WebdriverIO version:** 5.13.2
 - **Mode:** WDIO Testrunner sync
 - **Node.js version:** 10.15.3
 - **NPM version:** 6.10.3
 - **Browser name and version:** Safari 13.0.1
 - **Platform name and version:** masOS Mojave 10.14.6
 - **Additional wdio packages used (if applicable):** @wdio/selenium-standalone

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
The element.click() function is not working on Safari 13. It works fine on Chrome and Firefox.
No exceptions are issued, but the click is not performed.

**Expected behavior**
When calling .click() on an element, the click should be performed.

**Log**
https://gist.github.com/fariaslari/1848c121db8b881014844e3d293c1988

**Additional context**

**Comment by christian-bromann** [comment] 2019-10-04 13:21
> The element.click() function is not working on Safari 13. It works fine on Chrome and Firefox.

This is an issue with Safaridriver and can't be fixed in WebbdriverIO. Please report it in the Safaridriver project. Thanks!

**Closed by christian-bromann** 2019-10-04 13:21 UTC

**Comment by mgrybyk** [comment] 2019-10-04 13:36
@fariaslari click works fine for me with Safari Version 13.0.1 (14608.2.11.1.11)
@christian-bromann

**Comment by christian-bromann** [comment] 2019-10-04 16:56
@fariaslari can you provide a reproducible example?

**Comment by joeAtCharter** [comment] 2019-10-07 16:31
All of our tests stopped working on Safari on Oct 4 when latest rolled from 12.1 to 13.

Here's an example that fails to click on the google.com site, it should land on the "Create an account page", but remains on the google home page, and times out waiting for the button "Create an account".


describe('example:   ',function(){
    it("google example",function(){
        // login.login();

        let link = 'a.gb_e'
        browser.url('http://google.com');

        browser.waitForVisible(link);
        console.log(`found ${link}`);
        browser.click(link);

        let button = '.h-c-button';
        browser.waitForVisible(button);
        console.log(`found ${button}`);
        browser.click(button);
        browser.pause(5000);
        })
})

**Comment by rmedina6** [comment] 2019-10-08 19:30
I am also experiencing this issue.  Upgrading to Safari 13.0.2 did not help either.

**Comment by johnnywang** [comment] 2019-11-22 10:59
Just to add on to this, also experiencing the same, but with macOS 10.13 and Safari 11.1, using a Sauce config

**Comment by christian-bromann** [comment] 2019-11-22 11:50
This bug has been reported in the Safaridriver project and seems to be fixed in Safari Technology Preview.

**Comment by nknapp1337** [comment] 2019-11-22 20:32
Tried it on Safari Technology Preview 13.1 - Didn't work for me. Anyone else have success with it?

**Comment by edoardoo** [comment] 2019-11-28 13:59
@christian-bromann, I've tried using Safari Technology Preview downloading it and :
```
        'browserName': 'safari',
        'safari.options':
        {
            technologyPreview: true
        }
```
but webdriver is returning :
```
Illegal key values seen in w3c capabilities: [safari.options]
```
Is there anything I'm missing?

**Comment by christian-bromann** [comment] 2019-11-28 14:10
> Is there anything I'm missing?

Can you try `'safari:options'`?

**Comment by edoardoo** [comment] 2019-11-28 14:15
@christian-bromann I've tried that, it just runs the standard Safari, so I thought it was just ignoring the key.

**Comment by nknapp1337** [comment] 2019-12-02 19:23
@edoardoo  To get Safari Tech Preview to launch I just use this: 

`browserName: 'safari',
            'safari.options': {
                technologyPreview: true,
            },`

Hope it helps.

**Comment by xseman** [comment] 2019-12-05 15:01
@nknapp1337 
`'safari.options': { technologyPreview: true, }` isn't working for me.
- macOS Catalina 10.15.1
- Safari Technologi Preview 13.1

**Comment by saranyamohandas** [comment] 2019-12-16 21:25
Does anyone have updates on safari13 issue? I couldn't find any solution on Gitter or any forums. I appreciate any help! Thanks!

**Comment by Armastus** [comment] 2020-01-09 02:34
Yea, please anybody help getting technologyPrview working. I'm using webdriverIO v5. 
Here is my capabilities:

  capabilities: [
    {
      browserName: "safari",
      maxInstances: 1,
      "safari:options": { technologyPreview: true }
    }
  ]

**Comment by Armastus** [comment] 2020-01-09 02:36
"safari.options" just throws
Illegal key values seen in w3c capabilities: [safari.options]

**Comment by TatsianaChaiko** [comment] 2020-01-30 08:20
> This bug has been reported in the Safaridriver project and seems to be fixed in Safari Technology Preview.

@christian-bromann Could you please update how to use Safari Technology Preview with webdriverio 5 to get that fix? How to set up capabilities?

**Comment by christian-bromann** [comment] 2020-01-30 18:58
@TatsianaChaiko if you start Safaridriver like this:

```sh
$ /Applications/Safari\ Technology\ Preview.app/Contents/MacOS/safaridriver -p 4444
```

You will run a session with Safari Technology Preview.

**Comment by martinfrancois** [comment] 2020-02-06 07:39
@christian-bromann Even if I start the driver like you specified, I still get the following error when running the tests with the capability: `{browserName: 'safari', maxInstances: 1, 'safari.options': {'technologyPreview': true}}`
Error:
```
ERROR @wdio/runner: Error: Failed to create session.
Unknown capability encountered: 'safari.options' = '{
    technologyPreview = 1;
}'
```

**Comment by christian-bromann** [comment] 2020-02-06 16:24
@martinfrancois you don't need `safari.options` anymore

**Comment by gabygandrade** [comment] 2020-02-11 00:17
@christian-bromann I'm seeing the same issue where element.click() is not working with:
```
Safari - Version 13.0.5 (14608.5.12)
Webdriver - Version 4.14.4 
MacOS Mojave - Version 10.14.6 
Also using: @wdio/selenium-standalone
```

When I run my tests with:

```
capabilities: [
    {
      browserName: 'safari',
     version: 'latest'
     },
  ],
```  

the element.click() command still does not work.

I also tried with:

```  
capabilities: [
    {
      browserName: 'safari',
      'safari.options': { technologyPreview: true },
    },
  ],
```

and I got this error: 
```ERROR: Unable to create new service: SafariDriverService
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
System info: host: 'ip-10-192-49-83.us-west-2.compute.internal', ip: '10.192.49.83', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '11.0.2'
Driver info: driver.version: unknown
```

**Comment by abaybabaydabudidabuday** [comment] 2020-02-24 12:07
> @TatsianaChaiko if you start Safaridriver like this:
> 
> ```shell
> $ /Applications/Safari\ Technology\ Preview.app/Contents/MacOS/safaridriver -p 4444
> ```
> 
> You will run a session with Safari Technology Preview.

Trying ur solution to setup with Technology Preview - doesn't work for me (couldn't run tests - freeze on launch) 

Technology Preview - Release 101 (Safari 13.2)
"webdriverio": "^5.18.6"
"selenium-standalone": "^6.17.0"

@christian-bromann Pls, help.. And thx in advance!

**Comment by christian-bromann** [comment] 2020-02-24 13:14
@abaybabaydabudidabuday you have to start the driver manually .. I don't think `@wdio/selenium-standalone-service` helps you there.

**Comment by SobheHigaze** [comment] 2020-03-04 09:15
Hi all,
i have faced this issue today, and the solution was so simple.
i have just upgraded to Safari from version 13.0.1 to version 13.1 .
hope that will help you.
==================
im running on:
MacOS Mojave version 10.14.6
Safari 13.1
webdriverIO V5.11.13
wdio-selenium-standalone-service V5.16.10

without any special configuration for safari options at the config file.

**Comment by pablopaul** [comment] 2020-08-27 08:04
Seeing a similar behaviour on Mac OS X Catalina with Safar 13.1

**Comment by guybaker0** [comment] 2021-12-02 14:01
seeing a similar issue with Safari Version 15.1 (15612.2.9.1.30, 15612), macOS Catalina 10.15.7.  I find element ids for selectors are ignored.  I can use full x path.
