### ISSUE TITLE
No refresh of elementId on stale element for waitForDisplayed on Edge 15-18

### ISSUE THREAD

**Issue by bruderstein** [webdriverio/webdriverio#5311] opened 2020-04-22 13:39 UTC
**Environment (please complete the following information):**
 - **Webdriver.io Version:** 6.1.2 & 5.22.5
 - **Mode:** WDIO test runner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 12.15.0
 - **NPM version:** 6.13.4
 - **Browser name and version:** Edge 15 through Edge 18
 - **Platform name and version:** Windows 10 (running tests from MacOS)

**Config of WebdriverIO**
```
exports.config = {
    runner: 'local',
    hostname: 'hub-cloud.browserstack.com',
    protocol: 'https',
    user: process.env.BROWSERSTACK_USER,
    key: process.env.BROWSERSTACK_PASSWORD,
    specs: [
        'tests/*.js'
    ],
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    capabilities: [{
        browserName: 'Edge',
        browserVersion : "18.0"  // NOTE: v80.0 works
    }],

    logLevel: 'info',
    bail: 0,
    baseUrl: 'https://stale-element-repro.netlify.app/',
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: ['browserstack'],
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    }
}
```

**Describe the bug**
When using `.waitForDisplayed()` on Edge 15 through 18, if the `isDisplayed` call (either from the execute script or the `/element/<elementId>/displayed` endpoint) returns a `stale element reference`, the first call to get the elementId is not repeated to get a new elementId. This works correctly with Edge 80+

**To Reproduce**

https://github.com/bruderstein/stale-element-repro

This is a repo setup to reproduce this issue. We use browserstack, so this _might_ be something in their configuration that returns a different error message.  I'm not able to try on other providers.

[Logs](https://github.com/bruderstein/stale-element-repro/tree/master/logs) are provided for the W3C and JWP protocols for Edge 15 and 18 using both v5 and v6 of webdriverio, and also of a working Edge 80 behaviour for v6.

**Expected behavior**
On a stale element reference, it should refetch the elementId, rerunning the `/elements` call.

**Log**
https://github.com/bruderstein/stale-element-repro/tree/master/logs

**Comment by christian-bromann** [comment] 2020-04-23 11:38
@bruderstein thanks for writing the issue. I tried running your repo example and couldn't reproduce it: https://app.saucelabs.com/tests/d5b625c8f2f7472889b0523039d2470a. Can you see if there is a difference in the environment we run?

**Comment by bruderstein** [comment] 2020-04-24 13:02
@christian-bromann I just double checked on Edge 17, and I get it reliably not refreshing the stale element reference.  I don't see any difference in environment, so I'm assuming that this must be down to a slightly different response from browserstack vs saucelabs.

Here's the public link to the session I just tried.
https://automate.browserstack.com/builds/d3aeb084f830d967f580cd25de455aa69fbf9b23/sessions/8e4d184af32e74bbb4161411bda0bcef893ecdb3?auth_token=a2b600bb523d382e8c0e7e5e6f4ba9476c073f07ed6f1032cd1b4c77536f2a2d

Appreciate this isn't your provider & the conflict of interest here, but I'd be happy if you (or anyone) could point me to where the refresh check happens, then I can maybe work out why it's not being triggered.

**Comment by christian-bromann** [comment] 2021-04-22 08:03
Given that there hasn't been any response for almost a year I will go ahead and close this issue. Without a reproducible example this issue is difficult to investigate. I am happy to re-open if such an example is available. Thanks!

**Closed by christian-bromann** 2021-04-22 08:03 UTC
Labels: Reproducible Example Missing
