### ISSUE TITLE
Cucumber hook return 'skipped' not working

### ISSUE THREAD

**Issue by kwokfu** [webdriverio/webdriverio#4567] opened 2019-10-04 17:08 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.14.3
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.11.0
 - **NPM version:** 6.11.3
 - **Browser name and version:** Chrome 77
 - **Platform name and version:** macOS 10.14.6
 - **Additional wdio packages used (if applicable):** @wdio/cucumber-framework, @wdio/allure-reporter

**Config of WebdriverIO**
Generic config with `cucumberOpts`:
```
  specs: ['features/*.feature'],
  framework: 'cucumber',
  cucumberOpts: {
    backtrace: true,
    requireModule: [],
    require: [
      'src/support/*',
      'src/step_definitions/*'
    ],
    dryRun: false,
    failFast: false,
    format: ['pretty'],
    colors: true,
    snippets: true,
    source: true,
    profile: [],
    strict: true,
    tagExpression: '', // https://cucumber.io/docs/cucumber/api/#tag-expressions
    timeout: 30000,
    ignoreUndefinedDefinitions: true
  },

```

**Describe the bug**
After upgrade to @wdio/cucumber-framework `^5.14.3` (was working in `5.13.2`), hook return `'skipped'` not skipping test. Tests that is supposed to be **skipped** continue to be executed.

**To Reproduce**
Sample feature file:
```
Feature: Skip Test

  @skipped
  Scenario: Skipped
    Given context
     When actions
     Then asserts

  @pending
  Scenario: Pending

    Given context
     When actions
     Then asserts
```
Code snippet:
```
Given('context', function() {
  console.log('>>> given context');
});

When('actions', function() {
  console.log('>>>  when actions');
});

Then('asserts', function() {
  console.log('>>>  then asserts');
});

Before({tags: '@skipped'}, function() {
  console.log('>>> skipped');
  return Status.SKIPPED;
});

Before({tags: '@pending'}, function() {
  console.log('>>> pending');
  return Status.PENDING;
});
```

**Expected behavior**
Hook return `'skipped'` should skip tests.

**Log**
**skipped** tests should not be executed, and yet log shows otherwise.
```
[0-0] >>> skipped
[0-0] >>> given context
[0-0] >>>  when actions
[0-0] >>>  then asserts
[0-0] >>> pending
[0-0] >>> given context
[0-0] >>>  when actions
[0-0] >>>  then asserts
```

**Comment by christian-bromann** [comment] 2019-10-05 12:07
This seems to be related to the changes @mgrybyk made recently. We haven't had tests for this which caused this regression. Any help is much appreciated.

**Comment by mgrybyk** [comment] 2019-10-05 14:48
@kwokfu thank you for detailed steps to reproduce, an issue gonna be fixed with the PR

**Closed by mgrybyk** 2019-10-05 14:48 UTC
Labels: Bug🐛
