### ISSUE TITLE
Session not getting loaded in Browserstack.

### ISSUE THREAD

**Issue by Fawke** [webdriverio/webdriverio#4329] opened 2019-08-07 11:49 UTC
**Environment:**
 - **WebdriverIO version:** 5.11.3
 - **Mode:** Standalone mode
 - **Node.js version:** 10.16.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Controlled by Browserstack, some browsers being tested are Chrome 72, Firefox 65.
 - **Platform name and version:** Controlled By Browserstack, Mac and Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/browserstack-service, @wdio/spec-reporter, @wdio/concise-reporter, @wdio/mocha-framework, @wdio/local-runner, @wdio-cli

**Config of WebdriverIO**
```(javascript)
function getCapabilities() {
  function getPlatform(os) {
    const platformMap = {
      'Windows': 'WINDOWS',
      'OS X': 'MAC',
    }
    return platformMap[os];
  }

  delete browsers['bs_ie_11_windows_10'];

  let capabilities = []
  Object.keys(browsers).forEach(key => {
    let browser = browsers[key];
    capabilities.push({
      browserName: browser.browser,
      platform: getPlatform(browser.os),
      version: browser.browser_version,
      acceptSslCerts: true,
      'browserstack.networkLogs': true,
      'browserstack.console': 'verbose',
      build: ''
    });
  });
  return capabilities;
}
exports.config = {
  specs: [
    './test/spec/e2e/**/*.spec.js'
  ],
  user: process.env.BROWSERSTACK_USERNAME,
  key: process.env.BROWSERSTACK_ACCESS_KEY,
  services: ['browserstack'],
  browserstackLocal: true,
  maxInstances: 5,
  capabilities: getCapabilities(),
  logLevel: 'silent', 
  coloredLogs: true,
  waitforTimeout: 60000, 
  connectionRetryTimeout: 60000,
  connectionRetryCount: 3,
  framework: 'mocha',
  mochaOpts: {
    ui: 'bdd',
    timeout: 60000,
    compilers: ['js:babel-register'],
  },
  reporters: ['concise']
};
```
**Describe the bug**
I was previously using `webdriver v4.13.2` and when I ran the command `wdio wdio.conf.js`, the sessions were getting connected to **Browserstack**. After upgrading to `@wdio/cli v5.11.13`, I'm not able to connect to my browserstack remote instance and the tests are executing locally.

**To Reproduce**
Clone this repository: https://github.com/prebid/Prebid.js
Execute these steps.
1. `npm install`

NOTE: Please replace Browserstack Username and Browserstack Access Key with your own credentials.

2. Run `gulp e2e-test --host=test.localhost`

You'll see the test cases executing in Browserstack.

Now, update the webdriver to V5.

3. Remove/Unsinstall old webdriver.io packages, `webdriverio`, `wdio-spec-reporter`, `wdio-mocha-framework`, `wdio-concise-reporter`, `wdio-browserstack-service`.

4. Install new packages. `@wdio/cli`, `@wdio/browserstack-service`, `@wdio/mocha-framework`, `@wdio/concise-reporter`, `@wdio/spec-reporter`, `@wdio/local-runner`

5. Run `gulp e2e-test --host=test.localhost`

This time, the test won't execute in Browserstack. It'll start executing locally.

**Expected behavior**
The tests should get executed in Browserstack after upgrading.

**Log**
Here's a link to a gist: https://gist.github.com/Fawke/74551893672ae8cb1528194efd535e6f

**Comment by christian-bromann** [comment] 2019-08-12 07:55
The error says:

> All parallel tests are currently in use, including the queued tests. Please wait to finish or upgrade your plan to add more sessions.

which means that you are running to many tests in parallel. I am not sure if and how the update is causing this but it is not a bug on the WebdriverIO side. Therefor closing this.

**Closed by christian-bromann** 2019-08-12 07:55 UTC
