### ISSUE TITLE
[🐛 Bug]: Unable to find a simple element by id/selector/...

### ISSUE THREAD

**Issue by lacell75** [webdriverio/webdriverio#13661] opened 2024-09-26 15:06 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.1.1

### Node.js Version

20

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
    browserName: 'chrome',
    acceptInsecureCerts: true,
    'goog:chromeOptions': {
      args: [
        '--disable-backgrounding-occluded-windows',
        '--window-size=1980,1080',
        '--lang=fr_FR.UTF-8',
        '--disable-search-engine-choice-screen',
      ],
    },
  },
```

### What happened?

a simple call like `$('myelement')` not working. If I use `$('>>>myelement')` , the element is found. 

### How to reproduce the bug.

```
  await browser.url('https://taskmob.demo.vaadin.com');
  await expect($('#overlay')).toBeExisting();   // failed 
  await expect($('vaadin-dialog-overlay')).toBeExisting();  // failed
```

### Relevant log output

```typescript
[0-0] 2024-09-26T15:00:11.527Z DEBUG webdriver: BIDI RESULT {"id":10,"result":{"nodes":[{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.62","type":"node","value":{"attributes":{"focus-trap":"","id":"overlay","opened":"","role":"dialog","theme":"full-screen-on-mobile","with-backdrop":""},"childNodeCount":0,"localName":"vaadin-dialog-overlay","namespaceURI":"http://www.w3.org/1999/xhtml","nodeType":1,"shadowRoot":{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.63","type":"node","value":{"childNodeCount":7,"mode":"open","nodeType":11}}}}]},"type":"success"}
[0-0] 2024-09-26T15:00:11.544Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#overlay"},"context":"3EA26E0397D0F11C1A5DA80E996ECB88","startNodes":[{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.221"},{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.220"},{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.223"},{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.225"},{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.227"},{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.223"},{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.225"},{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.227"}]}
[0-0] 2024-09-26T15:00:11.603Z DEBUG webdriver: BIDI RESULT {"id":11,"result":{"nodes":[]},"type":"success"}
[0-0] 2024-09-26T15:00:12.619Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#overlay"},"context":"3EA26E0397D0F11C1A5DA80E996ECB88","startNodes":[{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.221"},{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.220"},{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.223"},{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.225"},{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.227"},{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.223"},{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.225"},{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.227"}]}
[0-0] 2024-09-26T15:00:12.624Z DEBUG webdriver: BIDI RESULT {"id":12,"result":{"nodes":[]},"type":"success"}
[0-0] 2024-09-26T15:00:13.638Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#overlay"},"context":"3EA26E0397D0F11C1A5DA80E996ECB88","startNodes":[{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.221"},{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.220"},{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.223"},{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.225"},{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.227"},{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.223"},{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.225"},{"sharedId":"f.3EA26E0397D0F11C1A5DA80E996ECB88.d.81FFF98DF309B4E171B149679561CF6E.e.227"}]}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by lacell75** [comment] 2024-09-26 15:51
Works with firefox 130 but KO with chome 129

**Comment by christian-bromann** [comment] 2024-09-26 15:53
I will mark this as duplicate of #13521 - the issue is likely connected to the fact that the application is doing a redirect which confuses the selector engine.

**Closed by christian-bromann** 2024-09-26 15:53 UTC
Labels: Bug 🐛, Needs Triaging ⏳
