### ISSUE TITLE
TypeError: Cannot set property 'state' of undefined

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1787] opened 2016-12-22 14:02 UTC
## The problem

```
TypeError: Cannot set property 'state' of undefined
  at ReporterStats.testFail (/Users/a.shevtsov/Projects/e.mail.ru/tests/node_modules/webdriverio/build/lib/utils/ReporterStats.js:448:29)   at BaseReporter.<anonymous> (/Users/a.shevtsov/Projects/e.mail.ru/tests/node_modules/webdriverio/build/lib/utils/BaseReporter.js:159:25)   at emitOne (events.js:96:13)
  at BaseReporter.emit (events.js:188:7)
  at BaseReporter.handleEvent (/Users/a.shevtsov/Projects/e.mail.ru/tests/node_modules/webdriverio/build/lib/utils/BaseReporter.js:300:27)   at Launcher.messageHandler (/Users/a.shevtsov/Projects/e.mail.ru/tests/node_modules/webdriverio/build/lib/launcher.js:609:28)   at emitTwo (events.js:106:13)
  at ChildProcess.emit (events.js:191:7)
  at process.nextTick (internal/child_process.js:752:12)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

The problem [here](
https://github.com/webdriverio/webdriverio/blob/master/lib/utils/ReporterStats.js#L304): 

```js
testStats.state = 'fail'
```

`testStats` is undefined

In accordance with [this line](https://github.com/webdriverio/webdriverio/blob/master/lib/utils/ReporterStats.js#L225) it can be undefined

## Environment

* WebdriverIO version:
* Node.js version:  7
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): wdio-mocha-framework@0.5.8, wdio-spec-reporter@0.0.4

**Comment by christian-bromann** [comment] 2016-12-22 15:17
Duplicate of #1460

**Closed by christian-bromann** 2016-12-22 15:17 UTC
