### ISSUE TITLE
Webdriver.io 4.9.11 does not handle errors in before/after hooks correctly when reporting

### ISSUE THREAD

**Issue by ianrenauld** [webdriverio/webdriverio#2494] opened 2017-11-30 14:36 UTC
When there is an error in a before/after (or beforeAll/afterAll) hooks, the ReporterStats module throws the following error:

```
/Users/ianrenauld/dev/wdioTest/node_modules/webdriverio/build/lib/utils/ReporterStats.js:381
            if (!suiteStats.tests[uid]) throw Error(`Unrecognised test [${runner.title}] for suite [${runner.parent}]`);
                                        ^

Error: Unrecognised test ["before all" hook] for suite [test]
    at Error (native)
    at ReporterStats.getTestStats (/Users/ianrenauld/dev/wdioTest/node_modules/webdriverio/build/lib/utils/ReporterStats.js:381:47)
    at ReporterStats.testFail (/Users/ianrenauld/dev/wdioTest/node_modules/webdriverio/build/lib/utils/ReporterStats.js:450:30)
    at BaseReporter.<anonymous> (/Users/ianrenauld/dev/wdioTest/node_modules/webdriverio/build/lib/utils/BaseReporter.js:159:25)
    at emitOne (events.js:96:13)
    at BaseReporter.emit (events.js:188:7)
    at BaseReporter.handleEvent (/Users/ianrenauld/dev/wdioTest/node_modules/webdriverio/build/lib/utils/BaseReporter.js:300:27)
    at Launcher.messageHandler (/Users/ianrenauld/dev/wdioTest/node_modules/webdriverio/build/lib/launcher.js:646:28)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
(node:18477) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: channel closed
```

This happens with version 4.9.11 and didn't happen in 4.9.9 (not sure about 4.9.10).  For reference, I use the spec and junit reporters (did not try to narrow it down to see if it's caused by either or both of those, or if it just happens generally).  Errors within tests themselves are correctly handled, only errors in before/after/etc. hooks cause the issue.

I just run the one test (listed below), so I am not sure why the error is complaining about a "suite" since I just used `--spec`...

## Environment

* WebdriverIO version: 4.9.11
* Node.js version: 6.7.0
* wdio testrunner
* Synchronous

## Code To Reproduce Issue [ Good To Have ]
```
// test.spec.js

describe('test', () => {
  before(() => {
    browser.url('www.google.com');
    // Introduce an obvious error - but the same problem appears on "normal" errors, for example a waitFor... that times out
    browser.obviousError();
  });

  it('Is not required, will fail before getting here', () => {
    console.log(browser.getURL());
  });
});
```

**Comment by stephenkao** [comment] 2017-12-15 19:55
(FYI error-handling in these hooks is working as expected in 4.9.10.)

**Comment by tnypxl** [comment] 2017-12-21 19:47
@stephenkao This problem persists in 4.9.10 as well.

**Comment by Xotabu4** [comment] 2017-12-25 19:45
Just updated to 4.9.11
Still unclear exception on error in hooks:

i use mocha
```
/ReporterStats.js:381
            if (!suiteStats.tests[uid]) throw Error(`Unrecognised test [${runner.title}] for suite [${runner.parent}]`);
                                        ^

Error: Unrecognised test ["before all" hook] for suite [change project]
```

**Comment by ludeknovy** [comment] 2017-12-26 19:49
I can confirm it is still happening when using 4.9.11. Version 4.9.9 looks good.

**Comment by chrisfinch** [comment] 2018-01-03 15:02
Can also confirm this is happening in 4.9.11 for me.

**Comment by bennypowers** [comment] 2018-01-07 05:29
This is how it plays out for me with 4.9.11

```
$ xvfb-run wdio
[wdio-webcomponents] Overriding native wdio element/elements commands!
[wdio-webcomponents] Overriding native wdio element/elements commands!
/usr/local/share/.config/yarn/global/node_modules/webdriverio/build/lib/utils/ReporterStats.js:381
            if (!suiteStats.tests[uid]) throw Error(`Unrecognised test [${runner.title}] for suite [${runner.parent}]`);
                                        ^

Error: Unrecognised test ["before each" hook for "clicking auth menu opens login view"] for suite [When logged out]
    at ReporterStats.getTestStats (/usr/local/share/.config/yarn/global/node_modules/webdriverio/build/lib/utils/ReporterStats.js:381:47)
    at ReporterStats.testFail (/usr/local/share/.config/yarn/global/node_modules/webdriverio/build/lib/utils/ReporterStats.js:450:30)
    at BaseReporter.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/webdriverio/build/lib/utils/BaseReporter.js:159:25)
    at emitOne (events.js:116:13)
    at BaseReporter.emit (events.js:211:7)
    at BaseReporter.handleEvent (/usr/local/share/.config/yarn/global/node_modules/webdriverio/build/lib/utils/BaseReporter.js:300:27)
    at Launcher.messageHandler (/usr/local/share/.config/yarn/global/node_modules/webdriverio/build/lib/launcher.js:646:28)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
```

Note this is the output in gitlab-ci. Most of the test run and pass on my local dev machine.

here's my before hook:

```js
    /**
     * Gets executed before test execution begins. At this point you can access to all global
     * variables like `browser`. It is the perfect place to define custom commands.
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     */
    before(capabilities, specs) {
      const chai = require('chai');
      global.expect = chai.expect;
      global.suite = chai.suite;
      /** enable 'should' style tests */
      chai.Should(); // eslint-disable-line new-cap
    },
```

I hope this was in some way helpful

**Comment by christian-bromann** [comment] 2018-01-07 18:38
This was fixed by #2497

**Closed by christian-bromann** 2018-01-07 18:38 UTC

**Comment by worc** [comment] 2018-07-05 18:24
it wasn't actually... localStorage still crashes

**Comment by christian-bromann** [comment] 2018-07-05 22:43
not sure how this is connected to local storage

**Comment by worc** [comment] 2018-07-13 22:16
you referenced this card from a localStorage bug...

**Comment by erwinheitzman** [comment] 2018-07-13 23:53
@worc instead of saying it's broken, could you be more specific on what seems to be malfunctioning? 
Also make sure to provide an example so we can see what you are trying to do and also it allows us to reproduce the potential issue.
