### ISSUE TITLE
waitFor (waitForExist()/waitForDisplayed()) command doens't work well.

### ISSUE THREAD

**Issue by GineaPig** [webdriverio/webdriverio#3952] opened 2019-05-09 02:16 UTC
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 5.7.15]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync]
 - **Browser name and version:** [e.g. Chrome 73.0.3683.103 and Firefox 66.0.5 (64-bit)]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Describe the bug**
waitForExist() and waitForDisplayed() works very unstable. Sometimes it works, sometimes it doesn't work and the test failed without any error details, and the browser doesn't quit when the test fails, looks like the session is disconnected.

**To Reproduce**
use waitForDisplayed() for an invisible element. waitForExist just for a visible/invisible element.

[Include code or an example repository that can easily be set up]
selector.waitForDisplayed()

**Expected behavior**
The test case should failed as normal failure with error details and the browser should quit when the test is failed.

**Log**
no logs.

> Please use the correct markdown

**Comment by MunGell** [comment] 2019-05-09 03:46
Hi @GineaPig 

Similar situation was happening to me when I was passing custom configuration object to webdriverio and didn't include `waitforInterval` property in it.

Maybe this is something you do as well?

**Comment by GineaPig** [comment] 2019-05-09 04:28
@MunGell Thank you for your comment. I use the default config file and make some changes in the config. But I noticed that there is no "waitforInterval" in the config file, is this the problem? And how should I use it? Thank you!

**Comment by GineaPig** [comment] 2019-05-09 06:10
@MunGell Thank you so much for your reply. I use the default configuration and made some changes, but I noticed that I don't have waitforInterval in my config file.
I noticed that the waitForDisplayed() shows the error correctly only when I set the timetout less than 10 seconds, like selector.waitForDisplayed(10000).

`exports.config = {

    runner: 'local',

    specs: [
        './test/specs/**/*.js'
    ],

    exclude: [
        // 'path/to/excluded/files'
    ],

    maxInstances: 10,

    capabilities: [{

        maxInstances: 5,

        browserName: 'firefox'
    }],

    logLevel: 'error',

    deprecationWarnings: true,

    bail: 0,

    baseUrl: 'http://localhost',

    waitforTimeout: 30000,


    connectionRetryTimeout: 90000,

    connectionRetryCount: 3,

    services: ['selenium-standalone'],

    framework: 'mocha',

    reporters: ['dot','spec', ['allure', {
        outputDir: 'allure-results',
        disableWebdriverStepsReporting: true,
        disableWebdriverScreenshotsReporting: false,
    }]],

    screenshotPath: './errorShots/',

    outputDir: './',

    mochaOpts: {
        ui: 'bdd',
        timeout: 300000
    },

}`

above is my config, do I need to add or change something to fix this? Thank you.

**Comment by GineaPig** [comment] 2019-05-09 06:15
after I added waitforInterval=500, it still doesn't work.

**Comment by wswebcreation** [comment] 2019-05-09 06:48
@GineaPig 

Please ask these kind of questions on our Gitter channel and provide us with enough information to help you figure out the problem.
I'm going to close this issue now because this is not a bug

**Closed by wswebcreation** 2019-05-09 06:48 UTC

**Comment by manhnt9** [comment] 2019-12-11 15:55
Doesn't work for me either!

**Comment by mgrybyk** [comment] 2019-12-11 15:57
Please provide with reproducible example @manhnt9
