### ISSUE TITLE
Unable to find handler for (GET) /grid/api/testsession

### ISSUE THREAD

**Issue by hzk007** [webdriverio/webdriverio#7444] opened 2021-09-20 11:12 UTC
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:7.12.5 [e.g. 4.13.2]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:v12.18.0 [e.g. 8.11.2]
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name and version:93 [e.g. Chrome 68]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
1.  setup a selenium hub 4.0 with 
$ docker network create grid
$ docker run -d -p 4442-4444:4442-4444 --net grid --name selenium-hub selenium/hub:4.0.0-rc-2-prerelease-20210916
$ docker run -d --net grid -e SE_EVENT_BUS_HOST=selenium-hub \
    --shm-size="2g" \
    -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
    -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
    selenium/node-chrome:4.0.0-rc-2-prerelease-20210916

2. after the fix of #7436, Try with driver.gridTestSession with selenium hub 4.0, but failed with this error : Unable to find handler for (GET) /grid/api/testsession, But works well with selenium hub 3.0. Does it not support in selenium 4.0?
seems this API have lost?

**To Reproduce**

[Include code or an example repository that can easily be set up]
  const driver = await remote({
    hostname: 'xia01-i01-dkr01.lab.rcch.ringcentral.com',
    port: 4444,
    path: '/wd/hub',
    capabilities: {
      browserName: 'chrome',
    },
  });
  let detail = await driver.gridTestSession(driver.sessionId);

**Expected behavior**

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment] 2021-09-20 11:15
Duplicate of #7436

**Comment by hzk007** [comment] 2021-09-20 11:17
> Duplicate of #7436

Hi, it's not the same error, I hack the wido code in local with your commit #7436 , and the error is the API can not access.

**Comment by christian-bromann** [comment] 2021-09-20 11:48
Maybe these endpoints don't exist is Se4 anymore?

**Comment by hzk007** [comment] 2021-09-20 12:21
> Maybe these endpoints don't exist is Se4 anymore?

Maybe? But I don’t know where to confirm, Our framework uses these grid API with selenium 3.0, recently after upgrade to SE4, encounted this error..

**Comment by christian-bromann** [comment] 2021-09-20 13:09
I checked with the Selenium team and these endpoints don't exist anymore. There is a GraphQL endpoint that allows to query for similar information. I created an issue to add a command to make graphql requests.

**Closed by christian-bromann** 2021-09-20 13:09 UTC
