### ISSUE TITLE
Test runner stops whenever error occurs : "Promise never resolved with an truthy value"

### ISSUE THREAD

**Issue by mohdasif2294** [webdriverio/webdriverio#607] opened 2015-07-06 10:39 UTC
Instead of showing errors on console and continuing pending test cases. The test runner stops abruptly.

**Comment by AndreTheHunter** [comment] 2015-07-06 10:49
I've noticed this in various tests too. If an error occurs, webdriverio calls process.exit which stops tests from continuing. I think we should remove all calls to process.exit and just throw exceptions.

**Comment by mohdasif2294** [comment] 2015-07-06 11:09
Yea..right! It happens every time promise on not loaded element triggers (Due to internet problem). Though Assertion errors are properly caught.

**Comment by christian-bromann** [comment] 2015-07-06 11:17
I see. So the error gets thrown by the [`waitUntil`](https://github.com/webdriverio/webdriverio/blob/master/lib/commands/waitUntil.js#L40) command which gets used in all waitForX commands. So it seems that this behaviour has to do something with the way we handle rejected promises within commands.

**Comment by aahill50** [comment] 2015-07-08 18:14
I'm not sure if this is exactly the same issue, but it seems to be having the same effect. It seems that errors that occur during part of the chained method calls do not prevent subsequent steps from executing. I was able to replicate this using the following test (mocha):

    it('should do something', function (done) {
            client
                .url('http://www.google.com')
                .click('.not-a-real-element')
                .click('.not-a-real-element-again')
                .call(done)
        });

When I run this test, the first call to ```.click``` throws an error, as I would expect it to. However, it doesn't stop the second ```.click``` call from occurring, which throws another error, which then crashes the entire test suite.

I'm assuming this is not the desired behavior? I would think the first error should prevent the remaining steps from being called.

**Comment by christian-bromann** [comment] 2015-07-08 18:35
@aahill50 interesting, could you check if a third click gets executed?

**Comment by aahill50** [comment] 2015-07-08 19:47
@christian-bromann Honestly, it's hard to tell exactly what's going on with more than 2 calls. After playing around with it a bit, I'm actually not 100% sure that additional calls to ```click``` are occurring, because I can't get any output from them in promise handling callbacks. Something strange is happening though, because if you take out the 2nd call to ```.click``` or replace the element with a valid one so no error would be thrown, it works as expected (The test fails, but any remaining tests are still executed normally).

**Comment by aahill50** [comment] 2015-07-08 20:36
@christian-bromann I think something is going on with an uncaught exception not being handled (maybe through Q?), but I'm having trouble nailing it down.

**Comment by aahill50** [comment] 2015-07-09 15:37
@christian-bromann What's the significance of the function [throwOnNextTick](https://github.com/webdriverio/webdriverio/blob/master/lib/webdriverio.js#L121) in the main ```webdriverio.js``` file? It contains a ```process.exit``` that is getting called

**Comment by christian-bromann** [comment] 2015-07-09 15:48
yeah I bet the origin of the problem is there. I am honestly not sure anymore why I wanted to kill the process there. I think it was due to the reason that the process would never exit as there are promises waiting to get resolved.

**Comment by christian-bromann** [comment] 2015-07-10 11:27
fixed with https://github.com/webdriverio/webdriverio/compare/85f6a86563669f5a6d2ea8552a05dc60499f6b06...431072883d0f4585eba981bcdfa78244eee11dfa

**Closed by christian-bromann** 2015-07-10 11:27 UTC
Labels: Bug, test runner

**Comment by dheeraj1988** [comment] 2016-03-10 10:22
Hey Christian,

In what version this issue is fixed ?

I am still facing issue with webdriverio - "~3.4.0". I am using cucumber boilerplate with webdriverio. This is the code I have written -

`module.exports = function (ms, elem, expectedText, done) {
    this.browser.waitUntil(function() {
      return this.getText('//*[@id="gameround-status-progress"]').then(function(text) {
        return text.indexOf(expectedText) >= 0;
      });
     }, ms)
    .call(done);
};`

**Comment by christian-bromann** [comment] 2016-03-10 11:14
@dheeraj1988 this issue is wdio related and can't occur in cucumber boilerplate. You are facing a different issue.

**Comment by dheeraj1988** [comment] 2016-03-10 11:49
Thanks. I am raising the same in another group then.
