### ISSUE TITLE
[🐛 Bug]: "The request is not allowed by the user agent or the platform in the current context."

### ISSUE THREAD

**Issue by nzakas** [webdriverio/webdriverio#12187] opened 2024-02-06 21:41 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.29.1

### Node.js Version

20.11.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
"chrome" on Windows 10
```

### What happened?

I'm running a test using the `move()` method of `FileSystemFileHandle` and I'm getting the error, "The request is not allowed by the user agent or the platform in the current context."

### What is your expected behavior?

The operation should succeed without throwing an error. It does so in Firefox.

I tried running both headless and headful, and get the same error.

When I run the exact same code directly in the browser console on any webpage, it works.

### How to reproduce the bug.

```js
import assert from 'node:assert';

it('should work', async () => {
  const fs = await navigator.storage.getDirectory();
  const file = await fs.getFileHandle('foo.txt', { create: true });
  await file.move('bar.txt');
  assert.strictEqual(file.name, 'bar.txt');
});
```

Then run `wdio run ./wdio.conf.js`.

### Relevant log output

```typescript
[0-0] NotAllowedError in "should work"
Error: The request is not allowed by the user agent or the platform in the current context.
[0-0] FAILED in chrome - file:///C:/Users/nzaka/projects/humanwhocodes/fsx/packages/web/tests/web-hfs.test.js
[1-0] PASSED in firefox - file:///C:/Users/nzaka/projects/humanwhocodes/fsx/packages/web/tests/web-hfs.test.js
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2024-02-06 22:03
Interesting 🤔 @sadym-chromium is this something you are aware of that is a restriction within Chromedriver?

**Comment by sadym-chromium** [comment] 2024-02-23 14:16
Could you please provide the commands log? Does it work via Webdriver Classic, Webdriver BiDi, or CDP?

**Comment by christian-bromann** [comment] 2024-02-23 16:19
@sadym-chromium this is running component tests in WebDriver Classic. Is there anything that would cause Chrome to throw an error when executing `await file.move('bar.txt')` in the browser? Note that this error is thrown in the browser and I can reproduce this in the devtools:

<img width="557" alt="Screenshot 2024-02-23 at 8 17 50 AM" src="https://github.com/webdriverio/webdriverio/assets/731337/0598aacf-1902-4b95-a580-922e1f0ab60e">

@nzakas I can reproduce it in any Chrome browser though, e.g. here when I open something on google.com:
<img width="894" alt="Screenshot 2024-02-23 at 8 19 08 AM" src="https://github.com/webdriverio/webdriverio/assets/731337/7b283787-41d3-49e1-a270-a616ac0dcb1a">

I will go ahead and close this as it seems to be unrelated to WebdriverIO.

**Closed by christian-bromann** 2024-02-23 16:19 UTC
Labels: Bug 🐛, Needs Investigation

**Comment by nzakas** [comment] 2024-02-23 20:01
Interesting. I am still not able to reproduce this in Chrome or Edge using DevTools.

**Comment by christian-bromann** [comment] 2024-02-23 23:25
I can reproduce it in Edge after calling the same script

```ts
  const fs = await navigator.storage.getDirectory();
  const file = await fs.getFileHandle('foo.txt', { create: true });
  await file.move('bar.txt');
```

for the second time, e.g.:
<img width="927" alt="Screenshot 2024-02-23 at 3 24 49 PM" src="https://github.com/webdriverio/webdriverio/assets/731337/4ade9208-4b0a-4415-b436-97e395294bf1">

**Comment by schickling** [comment] 2024-04-27 12:46
Running into the same problem on latest Chrome when trying to run @christian-bromann's snippet in a worker - but works on the main thread.

![CleanShot 2024-04-27 at 14 45 08@2x](https://github.com/webdriverio/webdriverio/assets/1567498/1f982a89-26ad-43e1-80a1-1383f0045654)

**Comment by tomayac** [comment] 2024-04-27 20:23
This error typically is thrown when a user gesture like a click or key press is missing. In the Console, the user gesture requirement is lifted, but in the actual app code it’s not. Try putting the code in question after a click on a button for example. Does this work?

**Comment by tomayac** [comment] 2024-04-28 04:43
Oh, wait. I was tired and didn't fully notice that this is for browser automation software and the OPFS. Please disregard my previous comment. Sorry.
