### ISSUE TITLE
[🐛 Bug]: <title>Cannot run multiple scenarios through command line

### ISSUE THREAD

**Issue by ledaivuong** [webdriverio/webdriverio#11365] opened 2023-10-08 07:21 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### What happened?

`wdio wdio.conf.js -- --cucumberOpts.tags='@emptyEmail' ` => successful
`wdio wdio.conf.js -- --cucumberOpts.tags='@emptyLastName' ` => successful
`wdio wdio.conf.js -- --cucumberOpts.tags='@emptyEmail and @emptyLastName' ` => **failed**

### What is your expected behavior?

I can run multiple scenarios through the command line

### How to reproduce the bug.

`wdio wdio.conf.js -- --cucumberOpts.tags='@emptyEmail' ` => successful
`wdio wdio.conf.js -- --cucumberOpts.tags='@emptyLastName' ` => successful
`wdio wdio.conf.js -- --cucumberOpts.tags='@emptyEmail and @emptyLastName' ` => failed

### Relevant log output

```typescript
> test
> wdio wdio.conf.js --cucumberOpts.tags=@emptyEmail and @emptyLastName


Execution of 1 workers started at 2023-10-08T07:17:46.589Z

2023-10-08T07:17:46.606Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-10-08T07:17:46.607Z INFO @wdio/utils: Setting up browser driver for: chrome@stable
2023-10-08T07:17:46.609Z INFO @wdio/utils: Setting up browser binaries for: chrome@stable
2023-10-08T07:17:46.610Z INFO webdriver: Downloading Chromedriver v117.0.5938.134
2023-10-08T07:17:46.956Z WARN webdriver: Couldn't download Chromedriver v117.0.5938.134: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.134/win64/chromedriver-win64.zip, trying to find known good version...
2023-10-08T07:17:47.123Z INFO webdriver: Download of Chromedriver v117.0.5938.149 was successful
2023-10-08T07:17:47.125Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-10-08T07:17:47.126Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.conf.js,--cucumberOpts.tags=@emptyEmail and @emptyLastName
[0-0] 2023-10-08T07:17:47.980Z INFO @wdio/local-runner: Run worker command: run
2023-10-08T07:17:48.513Z INFO @wdio/cli: [0-0] SKIPPED in chrome - file:///D:/ChongYeu/Raksul/features/login.feature
2023-10-08T07:17:48.513Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-10-08T07:17:48.514Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 skipped, 1 total (100% completed) in 00:00:01

2023-10-08T07:17:48.516Z INFO @wdio/local-runner: Shutting down spawned worker
2023-10-08T07:17:48.778Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-10-08T07:17:48.779Z INFO @wdio/local-runner: shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by tamil777selvan** [comment] 2023-10-08 13:23
Hi @ledaivuong, I tried to recreate the problem but everything worked as it should, and I couldn't make the issue happen. Could you please share a working example where we can see this error in action?

**Sample Output:**

![Screenshot 2023-10-08 at 6 50 48 PM](https://github.com/webdriverio/webdriverio/assets/49207189/d7f9a64a-b6c8-483a-a458-a2e4b6e95c03)

**Comment by ledaivuong** [comment] 2023-10-08 14:56
@tamil777selvan 
I'm trying to run multiple scenarios by command line but it didn't work. On the other hand, it works smoothly if I run a single one.

**Comment by christian-bromann** [comment] 2023-10-08 16:33
@ledaivuong mind providing a reproducible example as a little Github project?

**Comment by ledaivuong** [comment] 2023-10-08 16:54
@christian-bromann https://github.com/ledaivuong/just-a-test

**Comment by erwinheitzman** [comment] 2023-10-08 18:15
I think this might be due to the tagExpression property that you have set which might do the same thing? Can't test it right now

**Comment by tamil777selvan** [comment] 2023-10-09 01:52
@ledaivuong, In the provided example, none of the scenarios match the given tag `@emptyEmail and @emptyLastName`.

Since the keyword `and` is used between two tags, a scenario must have both of those tags, either at feature level or scenario level.

Additionally as mentioned above, please note that the usage of `tagExpression` is not recommended as it is currently in a deprecating stage and will be removed in the future. You can find more details about this in the WebDriverIO documentation under [Frameworks](https://webdriver.io/docs/frameworks#tagexpression).

**Comment by ledaivuong** [comment] 2023-10-09 02:20
@tamil777selvan 
`@emptyEmail
  Scenario: As a user, I get notice when I input empty email
    Given I am on the page test
    When I click on submit button
    Then I expect the empty email validation "display" "'email' is required"
    When I input email "abc@abc.com"
    When I click on submit button
    Then I expect the empty email validation "disappear" ""

  @emptyLastName
  Scenario: As a user, I get notice when I input empty last name
    Given I am on the page test
    When I click on submit button
    Then I expect the empty lastName validation "display" "'lastName' is required"
    When I input last name "lastName"
    When I click on submit button
    Then I expect the empty lastName validation "disappear" ""`

The scenarios I mentioned already existed in the code. And as I said I try to use command line, it does not work even I remote tagExpression in wdio.conf

**Comment by tamil777selvan** [comment] 2023-10-09 02:29
if you need to run these two(mentioned above) scenario's, you can use `@emptyEmail or @emptyLastName` as tags.

If you'd like more information on how to work with tag expressions, you can refer to the official documentation here: [Cucumber Tag Expressions](https://cucumber.io/docs/cucumber/api/?lang=javascript).

**Comment by christian-bromann** [comment] 2023-10-16 02:14
I will go ahead and close this as it doesn't seem to be a bug within WebdriverIO. Thanks @tamil777selvan and @erwinheitzman for looking into this.

**Closed by christian-bromann** 2023-10-16 02:14 UTC
Labels: Bug 🐛, Reproducible Example Missing
