### ISSUE TITLE
Report failed selector where `Element is not clickable`

### ISSUE THREAD

**Issue by kevinmcdonnell** [webdriverio/webdriverio#1435] opened 2016-07-06 09:34 UTC
## The problem

Where an element is not clickable because another element would receive the click, wdio should report the selector which failed to help in debugging the test. Presently it reports the elementId and the element which would receive the click.

eg We should know that the command failed to click `.my-class`

```
browser.click('.my-class')
```

happy to work on the fix if I can be pointed in the right direction
## Environment
- WebdriverIO version: v4.0.9
- Node.js version:v4.4.7
- wdio testrunner
- synchronous
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Selenium/WebdriverIO logs

```
unknown error: Element is not clickable at point (517, 182). Other element would receive the click: <div class="lrn-qe-wait-panel" style="opacity: 0.0120416;">...</div>
running chrome
RuntimeError: unknown error: Element is not clickable at point (517, 182). Other element would receive the click: <div class="lrn-qe-wait-panel" style="opacity: 0.0120416;">...</div>
    at elementIdClick("15") - click.js:52:22
```
## Code To Reproduce Issue [ Good To Have ]

can add if needed

**Comment by christian-bromann** [comment] 2016-07-06 09:46
@kevinmcdonnell is this about the stack not showing the command that leads to that error in the test?

**Comment by kevinmcdonnell** [comment] 2016-07-06 09:47
yeah it shows this. But it doesn't help me understand which click in my test fails and where the issue in my test is.

```
RuntimeError: unknown error: Element is not clickable at point (517, 182). Other element would receive the click: <div class="lrn-qe-wait-panel" style="opacity: 0.0120416;">...</div>
    at elementIdClick("15") - click.js:52:22
```

**Comment by christian-bromann** [comment] 2016-07-06 09:48
I see. We do some filtering of the stack trace so that you only get stack information that are relevant for you. It might be get filtered by that. Will have to investigate.

**Comment by joaoffalcao** [comment] 2016-07-06 10:49
Yeah, same problem here. Besides the log information, do you found the workaround?

**Comment by kevinmcdonnell** [comment] 2016-07-06 10:55
you can use `verbose` logging to debug

**Comment by christian-bromann** [comment] 2016-10-25 10:48
@kevinmcdonnell @joaoffalcao can you provide a reproducible example where the stack trace isn't helping?

**Comment by kevinmcdonnell** [comment] 2016-11-24 02:19
@christian-bromann apologies for the delay

This is a contrived example but produces the error:
```
        browser.url('http://www.github.com');
        browser.execute(function () {
            var p = document.createElement("p");
            p.style.position  = 'fixed';
            p.style.height  = '100px';
            p.style.width  = '100px';
            p.style.top  = '10px';
            p.className = 'clickme';
            document.body.appendChild(p);
        });
        browser.waitForExist('.clickme');
        browser.click('.clickme');
```

**Comment by jedwards1211** [comment] 2017-01-19 00:52
This is apparently an issue with ChromeDriver marked as WontFix because they didn't have a repro:

https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/2766

**Comment by kevinmcdonnell** [comment] 2017-01-19 07:28
@jedwards1211 without reading that long thread, i think that is a different issue `Element is not clickable at point`

The issue here is the logs don't report the selector which failed to click. I element not being clickable is expected, i just want to know the selector which was used to attempt the click

**Comment by jedwards1211** [comment] 2017-01-19 17:44
@kevinmcdonnell oh, gotcha!

**Comment by christian-bromann** [comment] 2018-04-13 11:45
In v5 we will have an autofix for this issue. Closing.

**Comment by pciavald** [comment] 2019-03-12 16:57
I'm still getting this issue using webdriverio 5.7, especially with vuetify. All checkboxes for instance are unclickable, i guess because some element is actually overlapping it, but that's the purpose of these libraries that hide the actual html inputs and shows a nicer UI. 

Is there any chance that webdriverio handles these cases correctly, for instance with an option in the click method like `$(selector).click({force: true})` (click even though an element is overlapping) ? A lot of front-end libraries "overlap" elements on purpose nowadays which forces us to use js clicking for almost everything in Chrome, and makes the testing code messy.

**Comment by christian-bromann** [comment] 2019-03-12 23:10
@pciavald interesting, do you have a demo app with a small script I can run?

**Comment by pciavald** [comment] 2019-03-13 00:44
@christian-bromann here you go sir

```js
describe('test', () => {
  it('tests', () => {
    browser.url('https://perdu.com')
    browser.execute(() => {
      const vue = document.createElement('script')
      vue.src = 'https://cdn.jsdelivr.net/npm/vue'

      const vuetify = document.createElement('script')
      vuetify.src = 'https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.js'

      const vuetifyStyle = document.createElement('link')
      vuetifyStyle.href = 'https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.min.css'
      vuetifyStyle.rel = 'stylesheet'
      document.head.appendChild(vuetifyStyle)

      const roboto = document.createElement('link')
      roboto.href = 'https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900|Material+Icons'
      roboto.rel = 'stylesheet'
      document.head.appendChild(roboto)

      const app = document.createElement('div')
      app.id = 'app'

      function appScript() {
        const app = new Vue({
          el: '#app',
          data: () => {
            return { value: true }
          },
          template: '<v-checkbox id="checkbox" v-model="value" label="test" />',
        })
      }

      vue.onload = () => document.head.appendChild(vuetify)
      vuetify.onload = appScript

      document.body.appendChild(app)
      document.head.appendChild(vue)
    })
    browser.pause(3000)
    browser.execute(() => document.querySelector('#checkbox').click())
    $('#checkbox').click()
  })
})

```

**Comment by caydgreen** [comment] 2019-05-14 18:02
I am experiencing the same issue with a vue.js front end.

**Comment by mgrybyk** [comment] 2019-05-20 09:58
So this is a feature request to pass `{ force: true }` to `element.click` function?

Cypress has the similar functionality https://docs.cypress.io/api/commands/click.html#Options

It uses javascript to click, like proposed by @pciavald `browser.execute(() => document.querySelector('#checkbox').click())`

**Comment by CrispusDH** [comment] 2019-05-20 10:52
we should notice in docs that clicking by js it is bad practice

**Comment by christian-bromann** [comment] 2019-05-24 12:13
We will tackle this in #2866

**Closed by christian-bromann** 2019-05-24 12:13 UTC
Labels: Needs Investigation
