### ISSUE TITLE
xUnit reporter does not work

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#985] opened 2016-01-06 15:39 UTC
```js
describe('Auth', () => {
	it('login', () => {
		return browser.url('/user/login')
			.getTitle()
			.should.eventually.be.equal('');
	});
});
```

**spec, dot**:

```
1 passing (3.70s)
```

**xunit**:

```
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/***/.nvm/versions/node/v5.3.0/bin/node" "/Users/***/.nvm/versions/node/v5.3.0/bin/npm" "run" "wdio"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! account.mail.ru@2.0.0 wdio: `wdio tests/config.js`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the account.mail.ru@2.0.0 wdio script 'wdio tests/config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the account.mail.ru package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     wdio tests/config.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls account.mail.ru
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/***/workspace/mail.ru/fau.client/npm-debug.log
```

**Config**

```js
... 
framework: 'mocha',

reporter: 'xunit',

reporterOptions: {
	outputDir: './cache/tests/reports'
},

before () {
	chai.should();
	chai.use(chaiAsPromised);
}
...
```

**Report**

*./cache/tests/reports/`WDIO.xunit.firefox.47451.xml`* is empty

```
➜ npm ls mocha
└── mocha@2.3.4 
```

It seems the problem with Mocha, but I don't know how to detail it (

**Comment by christian-bromann** [comment] 2016-03-25 14:05
duplicate of issue above

**Closed by christian-bromann** 2016-03-25 14:05 UTC
Labels: Bug
