### ISSUE TITLE
Add hook 'onWorkerStop'

### ISSUE THREAD

**Issue by Nouxx** [webdriverio/webdriverio#7237] opened 2021-08-08 00:48 UTC
**Is your feature request related to a problem? Please describe.**
I'm struggling with parrallel executions and I'll be okay with managing it myself using [Custom Services](https://webdriver.io/docs/customservices/). 
I'm using Appium to test Android app and my idea is to add `udid` and `systemPort` capabilities to run // tests in a single Appium server, see more info [here](https://appium.io/docs/en/advanced-concepts/parallel-tests/).
If I have 2 devices available, I'm setting 1 capability in `wdio.conf.js` which represent my Appium server and `maxInstance=2`.
As soon as a new worker is spawned, I'm adding it additional capabilities of an **available** device. I'm handling the list of available device in the code
The problem is that I have no hook to later make any device **unavailable** so that I can be used by another worker.

**Describe the solution you'd like**
A new hook, that could be called `onWorkerStop` with the same args as `onWorkerStart`, which will be called just before the worker gets removed

Thoughts? I'd be happy to help with a PR

**Comment by jamesmortensen** [comment] 2021-08-08 10:29
onWorkerStop would be helpful also for other use cases, such as managing a pool of test user credentials and locking/unlocking them before each spec file run and after.

**Comment by nextlevelbeard** [comment] 2021-08-08 18:56
I second this, can have many useful use cases.
In the meantime @Nouxx try upgrading to appium@next and using this [device-farm](https://github.com/AppiumTestDistribution/appium-device-farm) plugin to do the parallel device management for you.

**Comment by christian-bromann** [comment] 2021-08-09 07:11
Duplicate of #6356

**Closed by christian-bromann** 2021-08-09 07:11 UTC

**Comment by Nouxx** [comment] 2021-08-09 08:03
Thanks for the tip @nextlevelbeard, it works like a charm! 
I'll follow appium 2.0 release date closely, we won't use a beta version in 'production'
But I still believe the new hook would be a great workaround for wdio and a useful feature for various use cases
