### ISSUE TITLE
Using isVisibleWithinViewport() on an individual item from a $$ selector references parent selector

### ISSUE THREAD

**Issue by alexkirmse** [webdriverio/webdriverio#1847] opened 2017-01-26 18:47 UTC
## The problem

When trying to run isVisibleWithinViewport() on an individual item from a $$ selector, it refers to the parent selector and not the individual selector, therefore returning an array rather than the individual item. See code example on how to reproduce. isVisible(), getText(), getCssProperty() works as expected but isVisibleWithinViewport() is different.

(perhaps related to https://github.com/webdriverio/webdriverio/issues/1758)

## Environment

* WebdriverIO version: 4.5.2
* Node.js version: v7.0.0
* wdio testrunner (sync: true)

## Code To Reproduce Issue

https://gist.github.com/alexkirmse/55be6898d8ecd80768c49bc6e6d8c1ad

**Comment by christian-bromann** [comment] 2017-04-20 15:25
duplicate of #1879

**Closed by christian-bromann** 2017-04-20 15:25 UTC
Labels: Bug, Needs Investigation
