### ISSUE TITLE
@wdio/local-runner: Failed launching test session: TypeError: Cannot read properties of undefined (reading 'init')

### ISSUE THREAD

**Issue by RamSharu** [webdriverio/webdriverio#11571] opened 2023-11-01 15:13 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

"webdriverio": "^8.20.4"

### Node.js Version

18.8

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
chrome
```

### What happened?

I updated my package. json with latest version of dependencies and the following error was thrown

Packasge.json

"dependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/plugin-proposal-export-default-from": "^7.5.2",
    "@babel/preset-env": "^7.23.2",
    "@babel/register": "^7.4.0",
    "@hapi/wreck": "^18.0.1",
    "@log4js-node/log4js-api": "^1.0.2",
    "@rpii/wdio-report-events": "^0.2.0",
    "@types/cucumber": "^4.0.5",
    "@wdio/browserstack-service": "^8.6.0",
    "@wdio/config": "^5.11.0",
    "@wdio/reporter": "^7.25.0",
    "@wdio/static-server-service": "^5.14.4",
    "axe-webdriverio": "^0.2.0",
    "browserstack-local": "^1.4.8",
    "chai": "^4.1.2",
    "constants": "^0.0.2",
    "crypto-js": "^4.2.0",
    "dotenv": "^16.0.3",
    "ecstatic": "^4.1.4",
    "hosted-git-info": "^4.0.2",
    "joi": "^17.9.1",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "selenium": "^2.20.0",
    "selenium-server": "^3.141.59",
    "selenium-standalone": "^6.24.0",
    "wdio-geckodriver-service": "^1.0.0",
    "webdriverio": "^8.20.4",
    "ws": "^7.2.0"
  },
 
  "overrides": {
    "notifications-node-client": {
      "jsonwebtoken": "9.0.0"
    },
    "@azure/identity": {
      "jsonwebtoken": "9.0.0"
    },
    "semver" : "7.5.2"
  },
  "devDependencies": {
    "@babel/core": "^7.23.2",
    "@rpii/wdio-html-reporter": "^7.0.0",
    "@wdio/allure-reporter": "^7.16.3",
    "@wdio/cli": "^7.14.0",
    "@wdio/cucumber-framework": "^8.20.3",
    "@wdio/local-runner": "^7.10.1",
    "@wdio/selenium-standalone-service": "^8.8.6",
    "@wdio/spec-reporter": "^7.13.2",
    "allure-commandline": "^2.13.8",
    "babel-jest": "^24.8.0",
    "chromedriver": "^118.0.1",
    "cucumber-html-reporter": "^5.5.0",
    "http-server": "^14.1.1",
    "jest": "^26.6.3",
    "npm-run-all": "^4.1.5",
    "pngjs": "^5.0.0",
    "standard": "12.0.1",
    "wdio-chromedriver-service": "^8.1.1",
    "wdio-cucumberjs-json-reporter": "^5.1.8"
  },

wdio.config.js
import allureReporter from '@wdio/allure-reporter'
import cucumberJson from 'wdio-cucumberjs-json-reporter'
require('dotenv').config({ path: `.env.${process.env.ENV}` })
const envRoot = (process.env.TEST_ENVIRONMENT_ROOT_URL)

const allure_config = {
  outputDir: 'allure-results',
  disableWebdriverStepsReporting: true,
  disableWebdriverScreenshotsReporting: false,
  useCucumberStepReporter: true,
  addConsoleLogs: true
}

exports.config = {
 
  runner: 'local',

  hostname: process.env.HOST_NAME || 'localhost',
  port: 4444,
  path: '/wd/hub/',
  protocol: 'http',

  specs: ['./features/**/*.feature'],

 
 
  maxInstances: 1,
  capabilities: [
    {
      maxInstances: 1,
      acceptInsecureCerts: true,
      browserName: 'chrome',
      'goog:chromeOptions': {
        args: [
          '--no-sandbox',
          '--disable-gpu',
          '--disable-dev-shm-usage',
          '--window-size=1920,1080'
        ]
      }
    }
  ],
  
  logLevel: 'debug',
  //
  
  bail: 0,
  
  baseUrl: envRoot,
  
  waitforTimeout: 20000,
 
  connectionRetryTimeout: 120000,
 
  connectionRetryCount: 1,
  
  framework: 'cucumber',

  reporters: ['spec'],
  

  runner: 'local',

 
  cucumberOpts: {
    // <string[]> (file/dir) require files before executing features
    require: ['./steps/**/*.js'],
    // <boolean> show full backtrace for errors
    backtrace: false,
    // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
    requireModule: [],
    // <boolean> invoke formatters without executing steps
    dryRun: false,
    // <boolean> abort the run on first failure
    failFast: false,
    // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
    format: ['pretty'],
    // <boolean> hide step definition snippets for pending steps
    snippets: true,
    // <boolean> hide source uris
    source: true,
    // <string[]> (name) specify the profile to use
    profile: [],
    // <boolean> fail if there are any undefined or pending steps
    strict: false,
    // <string> (expression) only execute the features or scenarios with tags matching the expression
    tagExpression: '',
    // <number> timeout for step definitions
    timeout: 60000,
    // <boolean> Enable this config to treat undefined definitions as warnings.
    ignoreUndefinedDefinitions: false
  },

  //
  // =====
  // Hooks
  // =====
  // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
  // it and to build services around it. You can either apply a single function or an array of
  // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
  // resolved to continue.
  /**
   * Gets executed once before all workers get launched.
   * @param {Object} config wdio configuration object
   * @param {Array.<Object>} capabilities list of capabilities details
   */
  // onPrepare: function (config, capabilities) {
  // },
  /**
   * Gets executed before a worker process is spawned and can be used to initialise specific service
   * for that worker as well as modify runtime environments in an async fashion.
   * @param  {String} cid      capability id (e.g 0-0)
   * @param  {[type]} caps     object containing capabilities for session that will be spawn in the worker
   * @param  {[type]} specs    specs to be run in the worker process
   * @param  {[type]} args     object that will be merged with the main configuration once worker is initialised
   * @param  {[type]} execArgv list of string arguments passed to the worker process
   */
  // onWorkerStart: function (cid, caps, specs, args, execArgv) {
  // },
  /**
   * Gets executed just before initialising the webdriver session and test framework. It allows you
   * to manipulate configurations depending on the capability or spec.
   * @param {Object} config wdio configuration object
   * @param {Array.<Object>} capabilities list of capabilities details
   * @param {Array.<String>} specs List of spec file paths that are to be run
   * @param {String} cid worker id (e.g. 0-0)
   */
  // beforeSession: function (config, capabilities, specs, cid) {
  // },
  /**
   * Gets executed before test execution begins. At this point you can access to all global
   * variables like `browser`. It is the perfect place to define custom commands.
   * @param {Array.<Object>} capabilities list of capabilities details
   * @param {Array.<String>} specs        List of spec file paths that are to be run
   * @param {Object}         browser      instance of created browser/device session
   */
  // before: async function (capabilities, specs) {

  //    allureReporter.addLabel("Initial configuration");
  // },
  /**
   * Runs before a WebdriverIO command gets executed.
   * @param {String} commandName hook command name
   * @param {Array} args arguments that command would receive
   */
  // beforeCommand: function (commandName, args) {
  // },
  /**
   * Cucumber Hooks
   *
   * Runs before a Cucumber Feature.
   * @param {String}                   uri      path to feature file
   * @param {GherkinDocument.IFeature} feature  Cucumber feature object
   */
  beforeFeature: async function (uri, feature) {
    allureReporter.addStep('Starting Fetaure : ' + feature.name)

    await browser.maximizeWindow()
  },
  /**
   *
   * Runs before a Cucumber Scenario.
   * @param {ITestCaseHookParameter} world world object containing information on pickle and test step
   */
  beforeScenario: async function (world) {
    await allureReporter.addFeature(world.name)
  },
  /**
   *
   * Runs before a Cucumber Step.
   * @param {Pickle.IPickleStep} step     step data
   * @param {IPickle}            scenario scenario pickle
   */
  // beforeStep: function (step, scenario) {
  // },
  /**
   *
   * Runs after a Cucumber Step.
   * @param {Pickle.IPickleStep} step     step data
   * @param {IPickle}            scenario scenario pickle
   * @param {Object}             result   results object containing scenario results
   * @param {boolean}            result.passed   true if scenario has passed
   * @param {string}             result.error    error stack if scenario failed
   * @param {number}             result.duration duration of scenario in milliseconds
   */
  afterStep: async function (step, scenario, result) {
    cucumberJson.attach(await browser.takeScreenshot(), 'image/png')
  }
  /**
   *
   * Runs before a Cucumber Scenario.
   * @param {ITestCaseHookParameter} world  world object containing information on pickle and test step
   * @param {Object}                 result results object containing scenario results
   * @param {boolean}                result.passed   true if scenario has passed
   * @param {string}                 result.error    error stack if scenario failed
   * @param {number}                 result.duration duration of scenario in milliseconds
   */
  // afterScenario: function (world, result) {
  // },
  /**
   *
   * Runs after a Cucumber Feature.
   * @param {String}                   uri      path to feature file
   * @param {GherkinDocument.IFeature} feature  Cucumber feature object
   */
  // afterFeature: function (uri, feature) {
  // },

  /**
   * Runs after a WebdriverIO command gets executed
   * @param {String} commandName hook command name
   * @param {Array} args arguments that command would receive
   * @param {Number} result 0 - command success, 1 - command error
   * @param {Object} error error object if any
   */
  // afterCommand: function (commandName, args, result, error) {
  // },
  /**
   * Gets executed after all tests are done. You still have access to all global variables from
   * the test.
   * @param {Number} result 0 - test pass, 1 - test fail
   * @param {Array.<Object>} capabilities list of capabilities details
   * @param {Array.<String>} specs List of spec file paths that ran
   */
  // after: function (result, capabilities, specs) {
  // },
  /**
   * Gets executed right after terminating the webdriver session.
   * @param {Object} config wdio configuration object
   * @param {Array.<Object>} capabilities list of capabilities details
   * @param {Array.<String>} specs List of spec file paths that ran
   */
  // afterSession: function (config, capabilities, specs) {
  // },
  /**
   * Gets executed after all workers got shut down and the process is about to exit. An error
   * thrown in the onComplete hook will result in the test run failing.
   * @param {Object} exitCode 0 - success, 1 - fail
   * @param {Object} config wdio configuration object
   * @param {Array.<Object>} capabilities list of capabilities details
   * @param {<Object>} results object containing test results
   */
  // onComplete: function(exitCode, config, capabilities, results) {
  // },
  /**
   * Gets executed when a refresh happens.
   * @param {String} oldSessionId session ID of the old session
   * @param {String} newSessionId session ID of the new session
   */
  // onReload: function(oldSessionId, newSessionId) {
  // }
}

### How to reproduce the bug.

use the following dependencies and configuration to execute the code

### Relevant log output

```typescript
@wdio/local-runner: Failed launching test session: TypeError: Cannot read properties of undefined (reading 'init')
[0-4]     at Runner.run (C:\Users\sramasub\OneDrive - Capgemini\Desktop\Claim_08Aug\ffc-ahwr-farmer-claim\test\acceptance\node_modules\@wdio\runner\build\index.js:83:49)
[0-4]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-01T15:04:10.911Z DEBUG @wdio/local-runner: Runner 0-4 finished with exit code 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2023-11-01 16:22
It seems like you are using a wild mix of different WebdriverIO package versions. Please make sure to upgrade to the latest version of WebdriverIO. Maybe re-setup it in your project using `npm init wdio@latest .`.

I will close this as it seems to be a misconfiguration of WebdriverIO versions and not a bug in WebdriverIO.

**Closed by christian-bromann** 2023-11-01 16:22 UTC
Labels: Bug 🐛, Needs Triaging ⏳

**Comment by RamSharu** [comment] 2023-11-01 16:47
{
  "author": "Defra",
  "license": "OGL-UK-3.0",
  "name": "ffc-ahwr-farmer-claim",
  "version": "0.16.1",
  "description": "Acceptance tests for FFC Farmer Claim Service",
  "homepage": "https://github.com/DEFRA/ffc-ahwr-farmer-claim",
  "contributors": [],
  "keywords": [
    "wdio",
    "webdriver",
    "webdriverio",
    "cucumber",
    "test",
    "selenium"
  ],
  "scripts": {
    "test": "wdio wdio.bs.config.js",
    "test.compatibility.docker": "wdio wdio.bs.config.js  --cucumberOpts.tagExpression='@compatibility'",
    "test:smoke:snd": "ENV=snd wdio wdio.config.js  --cucumberOpts.tagExpression='@smoke'",
    "test:smoke:dev": "wdio wdio.config.js  --cucumberOpts.tagExpression='@smoke'",
    "test:smoke:test": "wdio wdio.config.js  --cucumberOpts.tagExpression='@smoke1'",
    "test:negative:snd": "ENV=snd wdio wdio.config.js  --cucumberOpts.tagExpression='@negative'",
    "test:negative:dev": "wdio wdio.config.js  --cucumberOpts.tagExpression='@negative1'",
    "generate-report:allure": "allure generate allure-results --clean",
    "generate-report:cucumber-html": "node cucumber-reporter/cucumber-report.js",
    "test:debug": "node --inspect-brk=0.0.0.0 ./node_modules/@wdio/cli/bin/wdio.js wdio.bs.config.js",
    "wdio": "wdio run ./wdio.conf.js"
  },
  "dependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/plugin-proposal-export-default-from": "^7.5.2",
    "@babel/preset-env": "^7.23.2",
    "@babel/register": "^7.4.0",
    "@hapi/wreck": "^18.0.1",
    "@log4js-node/log4js-api": "^1.0.2",
    "@rpii/wdio-report-events": "^0.2.0",
    "@types/cucumber": "^4.0.5",
    "@wdio/browserstack-service": "^8.6.0",
    "@wdio/config": "^5.11.0",
    "@wdio/reporter": "^7.25.0",
    "@wdio/static-server-service": "^5.14.4",
    "axe-webdriverio": "^0.2.0",
    "browserstack-local": "^1.4.8",
    "chai": "^4.1.2",
    "constants": "^0.0.2",
    "crypto-js": "^4.2.0",
    "dotenv": "^16.0.3",
    "ecstatic": "^4.1.4",
    "hosted-git-info": "^4.0.2",
    "joi": "^17.9.1",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "selenium": "^2.20.0",
    "selenium-server": "^3.141.59",
    "selenium-standalone": "^6.24.0",
    "wdio-geckodriver-service": "^1.0.0",
    "webdriverio": "^8.20.4",
    "ws": "^7.2.0"
  },
  "overrides": {
    "notifications-node-client": {
      "jsonwebtoken": "9.0.0"
    },
    "@azure/identity": {
      "jsonwebtoken": "9.0.0"
    },
    "semver": "7.5.2"
  },
  "devDependencies": {
    "@babel/core": "^7.23.2",
    "@rpii/wdio-html-reporter": "^7.0.0",
    "@wdio/allure-reporter": "^7.16.3",
    "@wdio/cli": "^8.20.5",
    "@wdio/cucumber-framework": "^8.20.3",
    "@wdio/local-runner": "^7.10.1",
    "@wdio/selenium-standalone-service": "^8.8.6",
    "@wdio/spec-reporter": "^7.13.2",
    "allure-commandline": "^2.13.8",
    "babel-jest": "^24.8.0",
    "chromedriver": "^118.0.1",
    "cucumber-html-reporter": "^5.5.0",
    "http-server": "^14.1.1",
    "jest": "^26.6.3",
    "npm-run-all": "^4.1.5",
    "pngjs": "^5.0.0",
    "standard": "12.0.1",
    "wdio-chromedriver-service": "^8.1.1",
    "wdio-cucumberjs-json-reporter": "^5.1.8"
  },
  "standard": {
    "globals": [
      "browser",
      "it",
      "expect",
      "describe",
      "jest",
      "beforeEach",
      "assert",
      "$"
    ]
  }
}

updated as said and ran npm init wdio@latest .. still getting same error


Installing @wdio/cli to initialize project...
✔ Success!

===============================
🤖 WDIO Configuration Wizard 🧙
===============================

? A project named "ffc-ahwr-farmer-claim" was detected at "C:\Users\sramasub\OneDrive - Capgemini\Desktop\Claim_08Aug\ffc-ahwr-farmer-claim\test\acceptance", correct? Yes
? What type of testing would you like to do? Component or Unit Testing - in the browser
    > https://webdriver.io/docs/component-testing
? Which framework do you use for building components? Other
? Which framework do you want to use? Mocha (https://mochajs.org/)
? Do you want to use a compiler? No!
? Do you want WebdriverIO to autogenerate some test files? No
? Which reporter do you want to use? spec
? Do you want to add a plugin to your test setup? 
? Do you want to add a service to your test setup? 
? Do you want me to run `npm install` No



To install dependencies, execute:
npm install @wdio/browser-runner@latest @wdio/mocha-framework@latest @wdio/spec-reporter@latest --save-dev

Creating a WebdriverIO config file...
✔ Success!

Adding "wdio" script to package.json
✔ Success!

🤖 Successfully setup project at C:\Users\sramasub\OneDrive - Capgemini\Desktop\Claim_08Aug\ffc-ahwr-farmer-claim\test\acceptance 🎉

Join our Discord Community Server and instantly find answers to your issues or queries. Or just join and say hi 👋!
  🔗 https://discord.webdriver.io

Visit the project on GitHub to report bugs 🐛 or raise feature requests 💡:
  🔗 https://github.com/webdriverio/webdriverio

To run your tests, execute:
$ cd C:\Users\sramasub\OneDrive - Capgemini\Desktop\Claim_08Aug\ffc-ahwr-farmer-claim\test\acceptance
$ npm run wdio

PS C:\Users\sramasub\OneDrive - Capgemini\Desktop\Claim_08Aug\ffc-ahwr-farmer-claim\test\acceptance> npm run test:smoke:test

> ffc-ahwr-farmer-claim@0.16.1 test:smoke:test
> wdio wdio.config.js  --cucumberOpts.tagExpression='@smoke1'


Execution of 7 workers started at 2023-11-01T16:46:40.803Z

2023-11-01T16:46:40.877Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-11-01T16:46:40.882Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-11-01T16:46:40.885Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.config.js,--cucumberOpts.tagExpression='@smoke1'
[0-0] 2023-11-01T16:46:41.760Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2023-11-01T16:46:41.956Z DEBUG @wdio/config:utils: Found '@babel/register' package, auto-compiling files with Babel
[0-0] 2023-11-01T16:46:42.544Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2023-11-01T16:46:43.098Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read properties of undefined (reading 'init')
[0-0]     at Runner.run (C:\Users\sramasub\OneDrive - Capgemini\Desktop\Claim_08Aug\ffc-ahwr-farmer-claim\test\acceptance\node_modules\@wdio\runner\build\index.js:83:49)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-01T16:46:43.148Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED
2023-11-01T16:46:43.151Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-11-01T16:46:43.152Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-11-01T16:46:43.153Z INFO @wdio/local-runner: Start worker 0-1 with arg: wdio.config.js,--cucumberOpts.tagExpression='@smoke1'
[0-1] 2023-11-01T16:46:43.982Z INFO @wdio/local-runner: Run worker command: run
[0-1] 2023-11-01T16:46:44.176Z DEBUG @wdio/config:utils: Found '@babel/register' package, auto-compiling files with Babel
[0-1] 2023-11-01T16:46:44.735Z DEBUG @wdio/local-runner:utils: init remote session
[0-1] 2023-11-01T16:46:45.207Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read properties of undefined (reading 'init')
[0-1]     at Runner.run (C:\Users\sramasub\OneDrive - Capgemini\Desktop\Claim_08Aug\ffc-ahwr-farmer-claim\test\acceptance\node_modules\@wdio\runner\build\index.js:83:49)
[0-1]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-01T16:46:45.246Z DEBUG @wdio/local-runner: Runner 0-1 finished with exit code 1
[0-1] FAILED
2023-11-01T16:46:45.247Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-11-01T16:46:45.248Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-11-01T16:46:45.249Z INFO @wdio/local-runner: Start worker 0-2 with arg: wdio.config.js,--cucumberOpts.tagExpression='@smoke1'
[0-2] 2023-11-01T16:46:46.031Z INFO @wdio/local-runner: Run worker command: run
[0-2] 2023-11-01T16:46:46.232Z DEBUG @wdio/config:utils: Found '@babel/register' package, auto-compiling files with Babel
[0-2] 2023-11-01T16:46:46.811Z DEBUG @wdio/local-runner:utils: init remote session
[0-2] 2023-11-01T16:46:47.306Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read properties of undefined (reading 'init')
[0-2]     at Runner.run (C:\Users\sramasub\OneDrive - Capgemini\Desktop\Claim_08Aug\ffc-ahwr-farmer-claim\test\acceptance\node_modules\@wdio\runner\build\index.js:83:49)
[0-2]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-01T16:46:47.346Z DEBUG @wdio/local-runner: Runner 0-2 finished with exit code 1
[0-2] FAILED
2023-11-01T16:46:47.347Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-11-01T16:46:47.348Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-11-01T16:46:47.349Z INFO @wdio/local-runner: Start worker 0-3 with arg: wdio.config.js,--cucumberOpts.tagExpression='@smoke1'
[0-3] 2023-11-01T16:46:48.145Z INFO @wdio/local-runner: Run worker command: run
[0-3] 2023-11-01T16:46:48.345Z DEBUG @wdio/config:utils: Found '@babel/register' package, auto-compiling files with Babel
[0-3] 2023-11-01T16:46:48.941Z DEBUG @wdio/local-runner:utils: init remote session
[0-3] 2023-11-01T16:46:49.530Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read properties of undefined (reading 'init')
[0-3]     at Runner.run (C:\Users\sramasub\OneDrive - Capgemini\Desktop\Claim_08Aug\ffc-ahwr-farmer-claim\test\acceptance\node_modules\@wdio\runner\build\index.js:83:49)
[0-3]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-01T16:46:49.570Z DEBUG @wdio/local-runner: Runner 0-3 finished with exit code 1
[0-3] FAILED
2023-11-01T16:46:49.575Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-11-01T16:46:49.578Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-11-01T16:46:49.581Z INFO @wdio/local-runner: Start worker 0-4 with arg: wdio.config.js,--cucumberOpts.tagExpression='@smoke1'
[0-4] 2023-11-01T16:46:50.703Z INFO @wdio/local-runner: Run worker command: run
[0-4] 2023-11-01T16:46:50.918Z DEBUG @wdio/config:utils: Found '@babel/register' package, auto-compiling files with Babel
[0-4] 2023-11-01T16:46:51.501Z DEBUG @wdio/local-runner:utils: init remote session
[0-4] 2023-11-01T16:46:51.998Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read properties of undefined (reading 'init')
[0-4]     at Runner.run (C:\Users\sramasub\OneDrive - Capgemini\Desktop\Claim_08Aug\ffc-ahwr-farmer-claim\test\acceptance\node_modules\@wdio\runner\build\index.js:83:49)
[0-4]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-01T16:46:52.034Z DEBUG @wdio/local-runner: Runner 0-4 finished with exit code 1
[0-4] FAILED
2023-11-01T16:46:52.036Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-11-01T16:46:52.038Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-11-01T16:46:52.041Z INFO @wdio/local-runner: Start worker 0-5 with arg: wdio.config.js,--cucumberOpts.tagExpression='@smoke1'
[0-5] 2023-11-01T16:46:52.872Z INFO @wdio/local-runner: Run worker command: run
[0-5] 2023-11-01T16:46:53.141Z DEBUG @wdio/config:utils: Found '@babel/register' package, auto-compiling files with Babel
[0-5] 2023-11-01T16:46:53.938Z DEBUG @wdio/local-runner:utils: init remote session
[0-5] 2023-11-01T16:46:54.460Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read properties of undefined (reading 'init')
[0-5]     at Runner.run (C:\Users\sramasub\OneDrive - Capgemini\Desktop\Claim_08Aug\ffc-ahwr-farmer-claim\test\acceptance\node_modules\@wdio\runner\build\index.js:83:49)
[0-5]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-01T16:46:54.505Z DEBUG @wdio/local-runner: Runner 0-5 finished with exit code 1
[0-5] FAILED
2023-11-01T16:46:54.506Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-11-01T16:46:54.507Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-11-01T16:46:54.508Z INFO @wdio/local-runner: Start worker 0-6 with arg: wdio.config.js,--cucumberOpts.tagExpression='@smoke1'
[0-6] 2023-11-01T16:46:55.373Z INFO @wdio/local-runner: Run worker command: run
[0-6] 2023-11-01T16:46:55.566Z DEBUG @wdio/config:utils: Found '@babel/register' package, auto-compiling files with Babel
[0-6] 2023-11-01T16:46:56.143Z DEBUG @wdio/local-runner:utils: init remote session
[0-6] 2023-11-01T16:46:56.644Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read properties of undefined (reading 'init')
[0-6]     at Runner.run (C:\Users\sramasub\OneDrive - Capgemini\Desktop\Claim_08Aug\ffc-ahwr-farmer-claim\test\acceptance\node_modules\@wdio\runner\build\index.js:83:49)
[0-6]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-01T16:46:56.681Z DEBUG @wdio/local-runner: Runner 0-6 finished with exit code 1
[0-6] FAILED
2023-11-01T16:46:56.684Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-11-01T16:46:56.685Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 7 failed, 7 total (100% completed) in 00:00:15 undefined

**Comment by christian-bromann** [comment] 2023-11-01 17:06
You are still having outdated dependencies in your `package.json` that might cause this, e.g.

```
"@wdio/browserstack-service": "^8.6.0",
"@wdio/config": "^5.11.0",
"@wdio/reporter": "^7.25.0",
"@wdio/static-server-service": "^5.14.4",
```

I recommend to clean all WebdriverIO (`wdio-` or `@wdio/`) dependencies and rerun.

**Comment by RamSharu** [comment] 2023-11-02 10:18
I cleaned everything and updated all the packages using npm install. Deleted node_modules and reinstalled that as well . But, now I get this error @wdio/runner: ERROR @wdio/runner: Package subpath './build/commands/browser/$' is not defined by "exports" in C:\Users\sramasub\OneDrive - Capgemini\Desktop\Claim_08Aug\ffc-ahwr-farmer-claim\test\acceptance\node_modules\webdriverio\package.json



My upated package.json
{
  "author": "Defra",
  "license": "OGL-UK-3.0",
  "name": "ffc-ahwr-farmer-claim",
  "version": "0.16.1",
  "description": "Acceptance tests for FFC Farmer Claim Service",
  "homepage": "https://github.com/DEFRA/ffc-ahwr-farmer-claim",
  "contributors": [],
  "keywords": [
    "wdio",
    "webdriver",
    "webdriverio",
    "cucumber",
    "test",
    "selenium"
  ],
  "scripts": {
    "test": "wdio wdio.bs.config.js",
    "test.compatibility.docker": "wdio wdio.bs.config.js  --cucumberOpts.tagExpression='@compatibility'",
    "test:smoke:snd": "ENV=snd wdio wdio.config.js  --cucumberOpts.tagExpression='@smoke'",
    "test:smoke:dev": "wdio wdio.config.js  --cucumberOpts.tagExpression='@smoke'",
    "test:smoke:test": "wdio wdio.config.js  --cucumberOpts.tagExpression='@smoke1'",
    "test:negative:snd": "ENV=snd wdio wdio.config.js  --cucumberOpts.tagExpression='@negative'",
    "test:negative:dev": "wdio wdio.config.js  --cucumberOpts.tagExpression='@negative1'",
    "generate-report:allure": "allure generate allure-results --clean",
    "generate-report:cucumber-html": "node cucumber-reporter/cucumber-report.js",
    "test:debug": "node --inspect-brk=0.0.0.0 ./node_modules/@wdio/cli/bin/wdio.js wdio.bs.config.js",
    "wdio": "wdio run ./wdio.conf.js"
  },
  "dependencies": {
    "@babel/cli": "^7.23.0",
    "@babel/plugin-proposal-export-default-from": "^7.5.2",
    "@babel/preset-env": "^7.23.2",
    "@babel/register": "^7.4.0",
    "@hapi/wreck": "^18.0.1",
    "@log4js-node/log4js-api": "^1.0.2",
    "@rpii/wdio-report-events": "^0.2.0",
    "@types/cucumber": "^4.0.5",
    "@wdio/browserstack-service": "^8.20.5",
    "@wdio/config": "^8.20.3",
    "@wdio/reporter": "^8.20.0",
    "@wdio/static-server-service": "^8.20.0",
    "axe-webdriverio": "^0.2.0",
    "browserstack-local": "^1.4.8",
    "chai": "^4.1.2",
    "constants": "^0.0.2",
    "crypto-js": "^4.2.0",
    "dotenv": "^16.0.3",
    "ecstatic": "^4.1.4",
    "hosted-git-info": "^4.0.2",
    "joi": "^17.9.1",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "selenium": "^2.20.0",
    "selenium-server": "^3.141.59",
    "selenium-standalone": "^9.3.0",
    "wdio-geckodriver-service": "^5.0.2",
    "webdriverio": "^8.20.4",
    "ws": "^7.2.0"
  },
  "overrides": {
    "notifications-node-client": {
      "jsonwebtoken": "9.0.0"
    },
    "@azure/identity": {
      "jsonwebtoken": "9.0.0"
    },
    "semver": "7.5.2"
  },
  "devDependencies": {
    "@babel/core": "^7.23.2",
    "@rpii/wdio-html-reporter": "^7.0.0",
    "@wdio/allure-reporter": "^8.20.0",
    "@wdio/cli": "^8.20.5",
    "@wdio/cucumber-framework": "^8.20.3",
    "@wdio/local-runner": "^8.20.5",
    "@wdio/selenium-standalone-service": "^8.8.6",
    "@wdio/spec-reporter": "^8.20.0",
    "allure-commandline": "^2.24.1",
    "babel-jest": "^24.8.0",
    "chromedriver": "^118.0.1",
    "cucumber-html-reporter": "^5.5.0",
    "http-server": "^14.1.1",
    "jest": "^26.6.3",
    "npm-run-all": "^4.1.5",
    "pngjs": "^5.0.0",
    "standard": "12.0.1",
    "wdio-chromedriver-service": "^8.1.1",
    "wdio-cucumberjs-json-reporter": "^5.1.8"
  },
  "standard": {
    "globals": [
      "browser",
      "it",
      "expect",
      "describe",
      "jest",
      "beforeEach",
      "assert",
      "$"
    ]
  }
}

**Comment by christian-bromann** [comment] 2023-11-02 12:16
Please provide a minimal reproducible example as it is hard to tell what is going on.

**Comment by RamSharu** [comment] 2023-11-02 12:18
can I give my repo details?

**Comment by christian-bromann** [comment] 2023-11-02 12:21
> can I give my repo details?

It is less helpful to work on a large code base, try to reproduce the issue using a fresh project.

**Comment by RamSharu** [comment] 2023-11-02 12:23
what version of node is compatible? I have 18.18. Is that creating issue? the chromedriver is initialized but after that I am getting that error

**Comment by christian-bromann** [comment] 2023-11-02 12:25
> I have 18.18. Is that creating issue?

no

**Comment by RamSharu** [comment] 2023-11-02 12:26
63615/devtools/browser/4d861f1f-b7b5-48b3-bed8-5ec89c41cfd4
[0-4] 2023-11-02T11:52:01.238Z ERROR @wdio/runner: Error: Package subpath './build/commands/browser/$' is not defined by "exports" in C:\Users\sramasub\OneDrive - Capgemini\Desktop\Claim_08Aug\ffc-ahwr-farmer-claim\test\acceptance\node_modules\webdriverio\package.json--- this talks about package.json inside webdriver io why so?

**Comment by christian-bromann** [comment] 2023-11-02 12:39
> this talks about package.json inside webdriver io why so?

I don't know how your setup looks like. It seems that there is an issue with how the dependencies are set up. It is hard to tell.

**Comment by RamSharu** [comment] 2023-11-02 12:44
Can you suggest some way to get rid of this? some high level idea

**Comment by christian-bromann** [comment] 2023-11-03 02:05
> Can you suggest some way to get rid of this?

Try to re-setup WebdriverIO in your project. Make it work with a single test and then add more.
