### ISSUE TITLE
Unrecognised test

### ISSUE THREAD

**Issue by sullenor** [webdriverio/webdriverio#1195] opened 2016-03-24 14:11 UTC
Hello, there!

I use latest versions of webdriverio and wdio-mocha-framework and recently I started to get a nasty error:

```bash
/Users/sullenor/Documents/repo/yharnam/node_modules/webdriverio/build/lib/utils/ReporterStats.js:269
                throw Error('Unrecognised test [' + title + '] for suite [' + runner.parent + ']');
                ^

Error: Unrecognised test [XXX] for suite [YYY]
    at Error (native)
    at ReporterStats.getTestStats (/Users/sullenor/Documents/repo/yharnam/node_modules/webdriverio/build/lib/utils/ReporterStats.js:269:23)
    at ReporterStats.testFail (/Users/sullenor/Documents/repo/yharnam/node_modules/webdriverio/build/lib/utils/ReporterStats.js:315:34)
    at BaseReporter.<anonymous> (/Users/sullenor/Documents/repo/yharnam/node_modules/webdriverio/build/lib/utils/BaseReporter.js:138:25)
    at emitOne (events.js:90:13)
    at BaseReporter.emit (events.js:182:7)
    at BaseReporter.handleEvent (/Users/sullenor/Documents/repo/yharnam/node_modules/webdriverio/build/lib/utils/BaseReporter.js:278:27)
    at Launcher.messageHandler (/Users/sullenor/Documents/repo/yharnam/node_modules/webdriverio/build/lib/launcher.js:469:28)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
```

The error itself occurs in the **before hook** and wdio tries to get test stats for the suite, which doesn't exist in the `suiteStats.tests` object.

I checked manually and looks like changing `const title = runner.currentTest || runner.title` to `const title = runner.title || runner.currentTest` helps here (https://github.com/webdriverio/webdriverio/blob/master/lib/utils/ReporterStats.js#L165), but I am not sure, that it's a proper solution.

I wonder if you can check this?

**Comment by christian-bromann** [comment] 2016-03-24 14:12
Hi @sullenor,

thanks for reporting! Can you somehow create a reproducible example for me?

**Comment by sullenor** [comment] 2016-03-24 14:22
@christian-bromann I've tried already, but looks like it is hard to build a separated example to reproduce that error. And unfortunately, I can't share that part of my project.

I'll try again to reproduce it in the separated environment. Meanwhile, is there any information, that can be useful for you?

**Comment by christian-bromann** [comment] 2016-03-24 14:27
> I checked manually and looks like changing const title = runner.currentTest || runner.title to const title = runner.title || runner.currentTest helps here

I don't get why changing the values of the or operation solves the problem.

> Meanwhile, is there any information, that can be useful for you?

Not sure. I probably need to look into the test code to understand why this happens. Doesn't look like a usually error.

**Comment by sullenor** [comment] 2016-03-24 16:10
@christian-bromann finally I managed to reproduce it. Please, check it out: https://github.com/sullenor/wdio-bugreport

Looks like the error appears if I have `before`, `it` and `describe` on the same level in test.

**Comment by christian-bromann** [comment] 2016-03-24 16:13
Thanks. This will help me tremendously. Will take a look

**Comment by sullenor** [comment] 2016-03-24 16:16
Thanks

**Comment by marcodejongh** [comment] 2016-03-30 23:45
I have the same problem, the change @sullenor  suggested works for me.

**Comment by Petah** [comment] 2016-04-03 11:08
Any work arounds?

**Comment by marcodejongh** [comment] 2016-04-03 23:54
@Petah manually editing in you node_modules directory https://github.com/webdriverio/webdriverio/blob/master/lib/utils/ReporterStats.js#L165

to

```
const title = runner.title || runner.currentTest
```

Seemed to help for me.

**Comment by christian-bromann** [comment] 2016-04-04 13:14
Fixed the issue primarily by this change: https://github.com/webdriverio/webdriverio/commit/7eca40670a2881f954e128fdf87ea760c027476d#diff-2305aa79aa2aa89aafbe4d87e936ff28R196

Will be released with the next version.

**Closed** 2016-04-04 13:14 UTC
Labels: Bug

**Comment by sullenor** [comment] 2016-04-04 14:32
@christian-bromann cool, thanks!

**Comment by gronke** [comment] 2016-04-14 11:52
@christian-bromann the fix works perfectly. Is the next release already scheduled? I'm hitting that bug very often at the moment (and would have to maintain a custom build until the next version bump happened). Thank you!

**Comment by christian-bromann** [comment] 2016-04-14 11:53
Yeah, next release will be next week

**Comment by marcodejongh** [comment] 2016-04-15 00:53
@gronke You could also install the module right from the repository

https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by gronke** [comment] 2016-04-15 07:49
@christian-bromann Sweet, thanks! 🍰 

@marcodejongh the `build/` assets are not stored in the repository, but in the releases. Knowing that next week a regular release will happen, I just wait instead of maintaining a webdriverio custom build. This bug here just swallows error messages, but is not blocking the build itself.

**Comment by remotezygote** [comment] 2016-04-21 22:58
Any idea when a release will be happening @gronke ? This is more than an inconvenience for my setup - it destroys the suite entirely. If not a release, is there a version we can step back to that would work?

**Comment by christian-bromann** [comment] 2016-04-22 01:33
@remotezygote don't use before blocks I think should do the trick for now. Release happens within the next week

**Comment by wallynm** [comment] 2016-06-07 15:35
@christian-bromann Sorry to reopen this but had this issue already fixed?
I've got this problem into my test suite and currently i'm using v4.0.5

**Comment by wallynm** [comment] 2016-06-07 15:43
```
/usr/local/lib/node_modules/webdriverio/build/lib/utils/ReporterStats.js:262
            if (!suiteStats.tests[title]) throw Error('Unrecognised test [' + title + '] for suite [' + runner.parent + ']');
                                          ^

Error: Unrecognised test [should render component] for suite [Basic rendering]
    at Error (native)
    at ReporterStats.getTestStats (/usr/local/lib/node_modules/webdriverio/build/lib/utils/ReporterStats.js:262:49)
    at ReporterStats.output (/usr/local/lib/node_modules/webdriverio/build/lib/utils/ReporterStats.js:270:22)
    at BaseReporter.<anonymous> (/usr/local/lib/node_modules/webdriverio/build/lib/utils/BaseReporter.js:106:25)
    at emitOne (events.js:96:13)
    at BaseReporter.emit (events.js:188:7)
    at BaseReporter.handleEvent (/usr/local/lib/node_modules/webdriverio/build/lib/utils/BaseReporter.js:278:27)
    at Launcher.messageHandler (/usr/local/lib/node_modules/webdriverio/build/lib/launcher.js:469:28)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
````
Updated to v4.0.9
My problem related to this issue it's because i have two nested describes functions with same title, when i change them, it works perfectly but i think this isn't normal

**Comment by christian-bromann** [comment] 2016-06-07 16:54
@wallynm how does your test spec look like?

**Comment by nbykhovsky** [comment] 2016-10-31 22:11
@christian-bromann Hi, I am still getting this error, are there cases that weren't covered by this fix that you know about?

**Comment by mattlub** [comment] 2017-12-08 09:48
Hi, I am still getting this problem:
```
Error: Unrecognised test ["before all" hook] for suite [...]
    at ReporterStats.getTestStats (/Users/.../ReporterStats.js:384:41)
```
I logged the suiteStats object and the uid:
```
{ suiteStats: 
   SuiteStats {
     type: 'suite',
     start: 2017-12-08T09:43:12.108Z,
     _duration: 0,
     uid: 'the Checkout Confirmation Page of www.shop-apotheke.com2',
     title: 'the Checkout Confirmation Page of www.shop-apotheke.com',
     tests: {},
     hooks: { '"before all" hook3': [Object] } } }
{ uid: '"before all" hook4' }
```
and this is the line throwing the error- the hook is being interpreted as a test? Any ideas?
```
if (!suiteStats.tests[uid]) throw Error(`Unrecognised test [${runner.title}] for suite [${runner.parent}]`)
```
Thanks!

**Comment by christian-bromann** [comment] 2017-12-08 09:52
@mattlub how does your test spec look like?

**Comment by mattlub** [comment] 2017-12-08 13:22
@christian-bromann I was getting this on lots of different tests- but the general structure of all of them was:
```js
describe() {
  before(...)
  it(...)
  it(...)
  after(...)
}
```
Is this what you were asking or do you want something more specific?

**Comment by christian-bromann** [comment] 2017-12-08 13:27
> want something more specific?

Yes, something i can download and run by myself

**Comment by skeggse** [comment] 2017-12-11 20:20
I'm still seeing this when, just like #2494, an error occurs in a test hook.

```js
describe('things', function() {
  beforeEach(function() {
    throw new Error('failure');
  });

  it('should pass', function() {
    // noop
  });
});
```

```sh
$ npx wdio

wdio-repro/node_modules/webdriverio/build/lib/utils/ReporterStats.js:381
            if (!suiteStats.tests[uid]) throw Error(`Unrecognised test [${runner.title}] for suite [${runner.parent}]`);
                                        ^

Error: Unrecognised test ["before each" hook for "should pass"] for suite [things]
    at Error (native)
    at ReporterStats.getTestStats (wdio-repro/node_modules/webdriverio/build/lib/utils/ReporterStats.js:381:47)
    at ReporterStats.testFail (wdio-repro/node_modules/webdriverio/build/lib/utils/ReporterStats.js:450:30)
    at BaseReporter.<anonymous> (wdio-repro/node_modules/webdriverio/build/lib/utils/BaseReporter.js:159:25)
    at emitOne (events.js:96:13)
    at BaseReporter.emit (events.js:188:7)
    at BaseReporter.handleEvent (wdio-repro/node_modules/webdriverio/build/lib/utils/BaseReporter.js:300:27)
    at Launcher.messageHandler (wdio-repro/node_modules/webdriverio/build/lib/launcher.js:646:28)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
$ (node:1665) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: channel closed
```

**Comment by zodiac1111** [comment] 2017-12-12 09:34
I get same issue with `before` ,`after`, stage.
If change `before` to `it` ,then `Unrecognised test...` error will not cause. But I do not know why :P

**Comment by mattlub** [comment] 2017-12-12 10:16
yep cheers @skeggse, that is my setup pretty much as well, and I hadn't seen that other issue #2494 which seems to be the same problem.

**Comment by mattlub** [comment] 2017-12-14 14:13
has anyone managed to patch the ReporterStats.js file to fix this temporarily?

**Comment by theansaname** [comment] 2018-03-05 19:06
running into issue, 4.9.11 webdriverio, 0.5.12 wdio-mocha-framework

**Comment by christian-bromann** [comment] 2018-03-05 20:23
@theansaname if you have a reproducible example (mini setup in a repo) feel free to share

**Comment by skeggse** [comment] 2018-03-05 20:43
@christian-bromann I attempted to distill the issue in my comment above - are you unable to repro?

**Comment by christian-bromann** [comment] 2018-03-05 20:48
@skeggse yes, no issue running that example

**Comment by christian-bromann** [comment] 2018-03-05 20:49
probably because #2494 was fixed by now
