### ISSUE TITLE
browser.keys('\uE007') sends an unsupported character instead of pressing ENTER

### ISSUE THREAD

**Issue by razielron** [webdriverio/webdriverio#6854] opened 2021-05-13 05:48 UTC
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.4.2
 - **Mode:** how can I know (we have- "runner: 'local'" in conf)
 - **If WDIO Testrunner, running sync/async:** sync mode
 - **Node.js version:** 12.8.3
 - **NPM version:** 7.6.1
 - **Browser name and version:** chrome 90
 - **Platform name and version:** Windows 10

**Describe the bug**
using the command: browser.keys('\uE007')
doesn't press ENTER, it sends some key (empty square)

**To Reproduce**
use the command: browser.keys('\uE007') while an input is focused
you can try it even with repl.

**Comment by christian-bromann** [comment] 2021-05-13 12:09
Duplicate of #6661

**Closed by christian-bromann** 2021-05-13 12:09 UTC
