### ISSUE TITLE
isDisplayed(true) returns different state for separate variable and for getElement inside

### ISSUE THREAD

**Issue by Svtrcom** [webdriverio/webdriverio#6410] opened 2021-02-11 13:08 UTC
Can be connected to the https://github.com/webdriverio/webdriverio/issues/5534
"version": "6.12.1"
Chrome

Works fine - return "false" in the second waitForDisplayed
```typescript
        await (await Eikon.instance.client.$(this.getButton('settingsPopupOpened'))).waitForDisplayed({ timeout: Timeouts.short });
        await (await Eikon.instance.client.$(subItemSelector)).click();
        await (await Eikon.instance.client.$(this.getButton('settingsPopupOpened'))).waitForDisplayed({ timeout: Timeouts.short, reverse: true });
```
Return "true" ( Error: element ("//emerald-popup-menu[@opened]") still displayed after 5000ms):
In the fact, element lose attribute (opened);
In the check error 5534 you check only elements not attribute misssing.

```typescript
        let settingsDropdown = await Eikon.instance.client.$(this.getButton('settingsDropdown'));
        await (settingsPopup).waitForDisplayed({ timeout: Timeouts.medium });
        await (await Eikon.instance.client.$(subItemSelector)).click();
        await (settingsPopup).waitForDisplayed({ timeout: Timeouts.medium, reverse: true });

```
.isDisplayed()  - **true**
await (settingsPopup).isEnabled() - **true**
await (settingsPopup).isExisting() -  **false** (correct state)

**Comment by christian-bromann** [comment] 2021-02-11 13:35
@Svtrcom can you provide a reproducible example?

**Comment by Svtrcom** [comment] 2021-02-11 13:58
It's paid product( I afraid that you don't have permission for it.
maybe screenshot with DOM tree !?

**Comment by christian-bromann** [comment] 2021-02-11 14:04
Can you recreate the scenario in a simple HTML file? Without having something to reproduce it is impossible to find out what is going on.

**Comment by Svtrcom** [comment] 2021-02-11 15:03
1) Create an element (dropdown in our case) that after a click on it will  receive attribute (opened) and after a second click -collapsed (remove attribute)
2) Run waitForDisplayed (true) as in the second scenario for waiting when element will be closed.
See attached
<img width="652" alt="dropdown" src="https://user-images.githubusercontent.com/28531224/107654175-11cf8a00-6c8b-11eb-8863-e839c1a0017b.png">

**Comment by christian-bromann** [comment] 2021-03-30 08:02
@Svtrcom any updates to provide a reproducible example? Otherwise I need to close this one.

**Comment by christian-bromann** [comment] 2021-04-13 08:39
Closing due to inactivity.

**Closed by christian-bromann** 2021-04-13 08:39 UTC
Labels: Reproducible Example Missing
