### ISSUE TITLE
Each next call .waitFor slows on few miliseconds

### ISSUE THREAD

**Issue by besgit** [webdriverio/webdriverio#425] opened 2015-02-10 17:36 UTC
I have a problem running tests on webdriver.io 2.4.5 and selenium standalone server 2.44.0 on windows8, after profiling I have seen, that each next call .waitFor slows on few miliseconds. Maybe anybody has an idea why it could happens.

Thanks in advance!

**Comment by christian-bromann** [comment] 2015-02-10 17:40
Hi @besgit , do you have an example script that would demonstrate this behavior?

**Comment by besgit** [comment] 2015-02-10 18:01
Hi, thanks for the quick response, I am using Cucumber.js with node.js

		this.client.waitFor(selector, 500, function(err) {
			var chain = [];
			for(var i=0;i<1000;i++) {
				chain.push(this.client.waitFor);
			}
			var i = 0;
			var doChain = function() {
				if (i > 0) {
					console.timeEnd("this.client.waitFor");
				}
				if (chain.length == 0) {
					callback.call(this);
					return;
				} else {
					var item = chain.pop();
					console.time("this.client.waitFor");
					item.call(this.client, selector, 500, doChain);
					i++;
				}
			}.bind(this);
			doChain(this);
		}.bind(this));

**Comment by besgit** [comment] 2015-02-10 18:08
If you need a complete example with the environment, tell me

**Comment by christian-bromann** [comment] 2015-02-10 18:38
Tried to reproduce it with the following example:

```js

var client = require('./').remote({
    coloredLogs: false,
    desiredCapabilities: {
        browserName: 'chrome'
    }
})

var selector = '#notexisting';

client
    .init()
    .url('http://google.com')
    .waitFor(selector, 500, function(err) {
        var chain = [];
        for(var i=0;i<1000;i++) {
            chain.push(client.waitFor);
        }
        var i = 0;
        var doChain = function() {
            if (i > 0) {
                console.timeEnd("this.client.waitFor");
            }
            if (chain.length == 0) {
                callback.call(client.end);
                return;
            } else {
                var item = chain.pop();
                console.time("this.client.waitFor");
                item.call(client, selector, 500, doChain);
                i++;
            }
        };
        doChain();
    });
```

and I get constant execution time between 1250ms and 1450ms. What are you trying to do here? Usually you don't call waitFor multiple time. If it doesn't exist after the timeout we can assume that there is an error happening. If you really need to wait that long, you should increase the timeout from `500` to something like `500000`. That saves resources and traffic. I can also recommend to use [`waitForVisible`](http://webdriver.io/api/utility/waitForVisible.html) which gets executed in the browser. So you are doing one Selenium request and it will return once it has found the element.

**Comment by besgit** [comment] 2015-02-11 09:55
Thanks, It seems the problem is in tested web application, but how to localize it?I am using selector '#rowLogoContainer' by url 'http://en-sales-omni.demo.bpmonline.com/NuiLogin.aspx'

P.s, example I use just for search the slowing code

**Comment by besgit** [comment] 2015-02-11 10:44
I execute this example on 'http://www.microsoft.com/en-us/default.aspx' and it also slowing in next call, even if I call .waitForVisble

**Comment by christian-bromann** [comment] 2015-02-12 11:44
Try the following:

```js
client
    .init()
    .url('http://en-sales-omni.demo.bpmonline.com/NuiLogin.aspx')
    .waitForVisible('#rowLogoContainer, 999999)
    // ...
```

Instead of calling waitFor again, it just waits for pretty long time (actually unnecessary long).

**Comment by besgit** [comment] 2015-02-12 12:32
As I wrote early, code from example I use just for search the slow code. I have 100 tests (about 20 steps in each), each step calls waitForVisible with unique selector, click and so on,  each next test executed slower and slower. Help me please detect a problem, Thanks in advance

**Comment by besgit** [comment] 2015-02-13 08:37
I try execute waitForVisible client script on the page, it always returns const value, maybe problem in request.js or selenium server?

var f1 = function(fn, sArr, args) {
	var cb = arguments[arguments.length - 1],
		i = 0,
		sArgs = [],
		use, value, xp, cs, tn, res, j, arg;
	while ((use = sArr[i++]) && (value = sArr[i++])) {
		arg = [];
		xp = cs = tn = null;
		switch (use) {
			case "partial link text":
				xp = '//a[contains(text(),"' + value + '")]';
				break;
			case "link text":
				xp = '//a[text()="' + value + '"]';
				break;
			case "xpath":
				xp = value;
				break;
			case "id":
				cs = '[id="' + value + '"]';
				break;
			case "name":
				cs = '[name="' + value + '"]';
				break;
			case "tag name":
				tn = value;
				break;
			case "css selector":
				cs = value;
				break;
			default:
				throw new Error("Could not evaluate selector: Invalid strategy " + use);
		}
		if (xp) {
			res = document.evaluate(xp, document, null, 0, null);
			while (value = res.iterateNext()) {
				arg.push(value);
			}
		} else if (tn || cs) {
			res = tn ? document.getElementsByTagName(tn) : document.querySelectorAll(cs);
			j = 0;
			while (value = res[j++]) {
				arg.push(value);
			}
		}
		sArgs.push(arg);
	}
	var parameter = args && sArgs.concat(args) || sArgs;
	if (parameter.length === 0 || (parameter.length === 1 && parameter[0].length === 0)) {
		if (typeof cb === 'function') {
			return cb('NoSuchElement') && new Error('NoSuchElement');
		}
		return new Error('NoSuchElement');
	}
	parameter.push(arguments[arguments.length - 1]);
	return fn.apply(window, parameter);
};
var f2 = function(elements, reverse) {
	var cb = arguments[arguments.length - 1],
		db = document.body,
		dde = document.documentElement;
	var interval = setInterval(function() {
		for (var i = 0; i < elements.length; ++i) {
			var elem = elements[i],
				conditionFulfilled = reverse ? false : true;
			while (elem.parentNode && elem.parentNode.getBoundingClientRect) {
				var condition = false,
					elemDimension = elem.getBoundingClientRect(),
					elemComputedStyle = window.getComputedStyle(elem),
					documentDimension = {
						width: Math.max(db.scrollTop || 0, dde.scrollTop || 0, db.offsetwidth || 0, dde.offsetWidth || 0, db.clientWidth || 0, dde.clientWidth || 0),
						height: Math.max(db.scrollheight || 0, dde.scrollHeight || 0, db.offsetHeight || 0, dde.offsetHeight || 0, db.clientHeight || 0, dde.clientHeight || 0)
					};
				if ((!reverse && elemComputedStyle.display !== 'none' && elemComputedStyle.visibility === 'visible' && parseFloat(elemComputedStyle.opacity, 10) > 0 && elemDimension.bottom >= 0 && elemDimension.top <= documentDimension.height && elemDimension.right >= 0 && elemDimension.left <= documentDimension.width) || (reverse && (elemComputedStyle.display === 'none' || elemComputedStyle.visibility === 'hidden' || parseFloat(elemComputedStyle.opacity, 10) === 0 || elemDimension.bottom < 0 || elemDimension.top > documentDimension.height || elemDimension.right < 0 || elemDimension.left > documentDimension.width))) {
					condition = true;
				}
				if (reverse) { /**   * if reverse is true (waitForInvisible) the condition is fulfilled   * when at least one element is hidden   */
				conditionFulfilled = conditionFulfilled || condition;
				} else { /**   * if reverse is false (waitForVisible (default)) the condition is fulfilled   * when each element is visible   */
				conditionFulfilled = conditionFulfilled && condition;
				}
				elem = elem.parentNode;
			}
			if (conditionFulfilled) {
				window.clearInterval(interval);
				return cb(true);
			}
		}
	}, 100);
};
var waitForVisibleChain = function(selector) {
	var chain = [];
	for(var i=0;i<1000;i++) {
		chain.push(f1);
	}
	var i = 0;
	var doChain = function() {
		if (i > 0) {
			console.timeEnd("waitForVisible");
		}
		if (chain.length == 0) {
			callback.call(this);
			return;
		} else {
			var item = chain.pop();
			console.time("waitForVisible");
			item.call(this, f2,["id", selector], [false], doChain);
			i++;
		}
	}.bind(this);
	doChain(this);
};
waitForVisibleChain("rowLogoContainer");

**Comment by besgit** [comment] 2015-02-19 11:56
Hi all, I realized the problem is calling client command with an argument callback method instead of using Promise.then. In the .. \ chainit \ index.js constantly growing queue depth parameter in currentDepth, and each next call slows. How to fix it without using Promise. Thanks in advance!

**Comment by christian-bromann** [comment] 2015-02-19 14:22
I can imagine that this:

```js
client.command(function() {
    client.command(function() {
        client.command(function() {
            client.command(function() {
            ....
            })
        })
    })
})
```

will blow up chainit's internal queue at one point. How are your tests structured? You usually only pass an argument callback method if you are interested in any response of a command (e.g. to assert against a command result).

**Comment by besgit** [comment] 2015-02-19 14:41
No, something like that

step1:
client.command(function() {
    nextStep();
});
step2:
client.command(function() {
    nextStep();
});
.
.
.
stepN:
client.command(function() {
    nextStep();
});

**Comment by christian-bromann** [comment] 2015-02-19 14:46
Could you try to use the call method to jump to the next step?

```
client.command().call(nextStep());
```

**Comment by besgit** [comment] 2015-02-19 15:27
if command fails then nextStep is not fire

**Comment by christian-bromann** [comment] 2015-02-19 15:37
that should get caught by the test framework, e.g. Mocha:

```js
it('should test something', function(done) {
    client
        .command()
        .call(done);
})
```

If command fails the `it` block will get marked as failed as well and Mocha continues with the next `it` block automatically.

**Comment by besgit** [comment] 2015-02-21 11:54
Thanks, tell me please, what difference between .call and .than, who is faster?

**Comment by christian-bromann** [comment] 2015-02-21 11:57
both commands are basically the same. `then` comes with a little bit promise overhead you don't need. To end you async test cases I recommend to use `call`

**Closed by christian-bromann** 2015-02-21 11:57 UTC

**Comment by besgit** [comment] 2015-02-21 12:00
And one more question , do you plan to repair the callback as an argument of client.command function or maybe you refuse to support them?

**Comment by christian-bromann** [comment] 2015-02-21 12:07
What do you mean exactly? WebdriverIO will always work like:

```js
client.command('parameter', function(err,res) {
    assert(res);
```
or
```
client.command('parameter').should.become('something');
```

**Comment by besgit** [comment] 2015-02-21 12:21
I mean this

Cucumber step1
	this.When(/^Click on the page element "([^"]*)"$/, function(parameter, next) {
		client.command(parameter, function(err,res) {
                    assert(res);
                    next();
              });
	});

**Comment by christian-bromann** [comment] 2015-02-21 12:30
mhm .. not really. First of all it is not necessary since you can use `call` here. Second, it is not really possible to fix this because this is the way how chainit works. Only thing I can do is to implicitly say "don't do that" in our docs.

**Comment by besgit** [comment] 2015-02-21 12:44
Thanks, "don't do that" in doc it wood be nice
