### ISSUE TITLE
[🐛 Bug]: Getting Error: Cannot find package 'puppeteer-core' imported from

### ISSUE THREAD

**Issue by WasiqB** [webdriverio/webdriverio#9460] opened 2022-12-27 07:35 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.0.13

### Node.js Version

v16.16.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
      maxInstances: 1,
      platformName: "Android",
      deviceName: "Pixel_6_Pro",
      "appium:platformVersion": "11",
      "appium:deviceName": "emulator-5554",
      "appium:automationName": "UiAutomator2",
      "appium:app": join(process.cwd(), "./apps/wdio-demo.apk"),
      commandTimeout: commandTimeout,
      "appium:newCommandTimeout": commandTimeout,
    }
```

### What happened?

I setup WDIO using Typescript and Yarn 3. When I tried running the tests using `yarn android` I am getting the following Error message.

```shell
> yarn android                                                             at 12:47:29 PM
file:///Users/wasiqbhamla/Documents/github/wdio-typescript-sample/.yarn/cache/import-meta-resolve-npm-2.2.0-f518d8472c-35a012c07b.zip/node_modules/import-meta-resolve/lib/errors.js:334
    Error.captureStackTrace(error)
          ^

Error: Cannot find package 'puppeteer-core' imported from /Users/wasiqbhamla/Documents/github/wdio-typescript-sample/.yarn/cache/devtools-npm-8.0.13-aa199638e4-db46298e02.zip/node_modules/devtools/build/utils.js
    at new NodeError (file:///Users/wasiqbhamla/Documents/github/wdio-typescript-sample/.yarn/cache/import-meta-resolve-npm-2.2.0-f518d8472c-35a012c07b.zip/node_modules/import-meta-resolve/lib/errors.js:277:5)
    at packageResolve (file:///Users/wasiqbhamla/Documents/github/wdio-typescript-sample/.yarn/cache/import-meta-resolve-npm-2.2.0-f518d8472c-35a012c07b.zip/node_modules/import-meta-resolve/lib/resolve.js:1037:9)
    at moduleResolve (file:///Users/wasiqbhamla/Documents/github/wdio-typescript-sample/.yarn/cache/import-meta-resolve-npm-2.2.0-f518d8472c-35a012c07b.zip/node_modules/import-meta-resolve/lib/resolve.js:1099:20)
    at defaultResolve (file:///Users/wasiqbhamla/Documents/github/wdio-typescript-sample/.yarn/cache/import-meta-resolve-npm-2.2.0-f518d8472c-35a012c07b.zip/node_modules/import-meta-resolve/lib/resolve.js:1248:15)
    at resolve (file:///Users/wasiqbhamla/Documents/github/wdio-typescript-sample/.yarn/cache/import-meta-resolve-npm-2.2.0-f518d8472c-35a012c07b.zip/node_modules/import-meta-resolve/index.js:30:12)
    at patchDebug (file:///Users/wasiqbhamla/Documents/github/wdio-typescript-sample/.yarn/cache/devtools-npm-8.0.13-aa199638e4-db46298e02.zip/node_modules/devtools/build/utils.js:256:32)
    at file:///Users/wasiqbhamla/Documents/github/wdio-typescript-sample/.yarn/cache/devtools-npm-8.0.13-aa199638e4-db46298e02.zip/node_modules/devtools/build/index.js:16:7
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

### What is your expected behavior?

It is expected that the test should be triggered and executed successfully.

### How to reproduce the bug.

This issue is reproducible at this [repository](https://github.com/WasiqB/wdio-typescript-sample/tree/1b8492414419aaa973d5505cad42c457e2843d0d).

After cloning this repository run, `yarn install` and then run `yarn android`.

### Relevant log output

```typescript
> yarn android                                                             at 12:47:35 PM
file:///Users/wasiqbhamla/Documents/github/wdio-typescript-sample/.yarn/cache/import-meta-resolve-npm-2.2.0-f518d8472c-35a012c07b.zip/node_modules/import-meta-resolve/lib/errors.js:334
    Error.captureStackTrace(error)
          ^

Error: Cannot find package 'puppeteer-core' imported from /Users/wasiqbhamla/Documents/github/wdio-typescript-sample/.yarn/cache/devtools-npm-8.0.13-aa199638e4-db46298e02.zip/node_modules/devtools/build/utils.js
    at new NodeError (file:///Users/wasiqbhamla/Documents/github/wdio-typescript-sample/.yarn/cache/import-meta-resolve-npm-2.2.0-f518d8472c-35a012c07b.zip/node_modules/import-meta-resolve/lib/errors.js:277:5)
    at packageResolve (file:///Users/wasiqbhamla/Documents/github/wdio-typescript-sample/.yarn/cache/import-meta-resolve-npm-2.2.0-f518d8472c-35a012c07b.zip/node_modules/import-meta-resolve/lib/resolve.js:1037:9)
    at moduleResolve (file:///Users/wasiqbhamla/Documents/github/wdio-typescript-sample/.yarn/cache/import-meta-resolve-npm-2.2.0-f518d8472c-35a012c07b.zip/node_modules/import-meta-resolve/lib/resolve.js:1099:20)
    at defaultResolve (file:///Users/wasiqbhamla/Documents/github/wdio-typescript-sample/.yarn/cache/import-meta-resolve-npm-2.2.0-f518d8472c-35a012c07b.zip/node_modules/import-meta-resolve/lib/resolve.js:1248:15)
    at resolve (file:///Users/wasiqbhamla/Documents/github/wdio-typescript-sample/.yarn/cache/import-meta-resolve-npm-2.2.0-f518d8472c-35a012c07b.zip/node_modules/import-meta-resolve/index.js:30:12)
    at patchDebug (file:///Users/wasiqbhamla/Documents/github/wdio-typescript-sample/.yarn/cache/devtools-npm-8.0.13-aa199638e4-db46298e02.zip/node_modules/devtools/build/utils.js:256:32)
    at file:///Users/wasiqbhamla/Documents/github/wdio-typescript-sample/.yarn/cache/devtools-npm-8.0.13-aa199638e4-db46298e02.zip/node_modules/devtools/build/index.js:16:7
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by harsha509** [comment] 2022-12-28 06:12
Strange i followed same steps and i see this log!

https://gist.github.com/harsha509/6621819c6ef7b8a86359659b2e32bf88

**Comment by harsha509** [comment] 2022-12-28 06:29
Hi @WasiqB ,

I clone the repo, downgraded to node 16, did yarn install and yarn android! i see below error

`2022-12-28T06:23:08.036Z ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: Neither ANDROID_HOME nor ANDROID_SDK_ROOT environment variable was exported. Read https://developer.android.com/studio/command-line/variables for more details
2022-12-28T06:23:08.036Z

 ERROR webdriver: unknown error: An unknown server-side error occurred while processing the command. Original error: Neither ANDROID_HOME nor ANDROID_SDK_ROOT environment variable was exported. Read https://developer.android.com/studio/command-line/variables for more details
`

as android SDK is not! But i don't see the specified error! Do i need to configure Android SDK too ?

Here is the log https://gist.github.com/harsha509/585f3fabb349eccdf23efbfe7739c2e3!

Am i missing any ?

**Comment by WasiqB** [comment] 2022-12-28 06:39
Can you check after setting up`ANDROID_HOME` and see if you can replicate the issue?

**Note:**
I have shared the repo link pointing to a specific commit. Please make sure you have that commit.

**Comment by christian-bromann** [comment] 2022-12-28 07:59
> Cannot find package 'puppeteer-core' imported from /Users/wasiqbhamla/Documents/github/wdio-typescript-sample/.yarn/cache/devtools-npm-8.0.13-aa199638e4-db46298e02.zip/node_modules/devtools/build/utils.js

@WasiqB this error indicates that a dependency is missing in the `devtools` package which has been clearly defined as dependency [in the package](https://github.com/webdriverio/webdriverio/blob/main/packages/devtools/package.json#L46). Can you ensure that you have installed all dependencies correctly?

**Comment by WasiqB** [comment] 2022-12-28 08:54
I generated a Typescript project using the yarn command to set up the project on the documentation site. Also did the `yarn install`

Once I saw this Error, I tried installing the package mentioned in the Error but still faced the issue.

Will try to play around it again from scratch and will revert back if the issue still exists.

> **Note:** Everything works fine when I use Wdio with JS and NPM.

**Comment by christian-bromann** [comment] 2022-12-28 08:59
Seems like a Yarn thing. I am not a Yarn expert as I stopped using it after v1. It's not totally unlikely that the project is doing something wrong so I will keep this up for investigations. Any contributions are welcome!

**Comment by christian-bromann** [comment] 2023-01-03 13:08
@WasiqB any updates on your investigation? Can you provide a reproducible example?

**Comment by WasiqB** [comment] 2023-01-03 13:56
@christian-bromann , I have replicated the issue in my [WDIO repository](https://github.com/WasiqB/wdio-sample).

In the following [commit](https://github.com/WasiqB/wdio-sample/commit/fdb986c9657dc13a292e3e6108dfe9c02f724d06), WDIO tests work fine. This commit is JavaScript and NPM based.

However, when I migrated this change to Yarn 3 using Yarn version 3.3.1, I am able to get the same Error mentioned earlier. This commit is the [latest one](https://github.com/WasiqB/wdio-sample/commit/8b2ecd09a1bbf1cca420333e10b351b800295d35).

Can you check once by cloning the repository? Because I can see this Error with JS and Yarn 3 as well.

**Comment by christian-bromann** [comment] 2023-01-03 14:06
> Can you check once by cloning the repository?

I am not sure when I get the time to look into this. I have other competing priorities. Please help us investigate the issue.

**Comment by christian-bromann** [comment] 2023-02-14 21:07
@WasiqB is it possible to trim the mobile part of the sample repository? This issue should be unrelated to the environment where WebdriverIO is running its tests in.

**Comment by christian-bromann** [comment] 2023-02-20 18:49
might be related to https://github.com/wooorm/import-meta-resolve/issues/10

**Comment by doug-mccuen-kr** [comment] 2023-02-20 19:10
Yep, and it looks like wooorm is taking the "won't fix" stance.  I'm hoping we can find a different path here.  Expanding the scope of that try/catch should be all we need, right?

**Comment by christian-bromann** [comment] 2023-02-20 19:40
> Expanding the scope of that try/catch should be all we need, right?

Can you elaborate on your idea?

**Comment by doug-mccuen-kr** [comment] 2023-02-20 19:59
There is a unhandled exception in the devtools package stemming from import-meta-resolve.  I assuming that the patchDebug is non-critical because most of it is wrapped in a try/catch.  I'm proposing that [line 350](https://github.com/webdriverio/webdriverio/blob/main/packages/devtools/src/utils.ts#L350) be moved before line 335, in order to handle that exception.

This will allow us (and other users of yarn3) to upgrade to the latest version of WDIO and this devtools package.

Thanks!

**Comment by christian-bromann** [comment] 2023-02-20 20:04
That makes sense! Do you want to help use raise a PR?

**Comment by doug-mccuen-kr** [comment] 2023-02-20 21:30
Does this get you started? https://github.com/webdriverio/webdriverio/pull/9802

**Comment by christian-bromann** [comment] 2023-02-21 17:59
Let's continue the conversation in #9802

**Closed by christian-bromann** 2023-02-21 17:59 UTC
Labels: Bug 🐛, Reproducible Example Missing, help wanted
