### ISSUE TITLE
[🐛 Bug]: Error allow custom commands scoped to element

### ISSUE THREAD

**Issue by yopasa94** [webdriverio/webdriverio#8417] opened 2022-06-09 16:53 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [
    {
      maxInstances: 1,
      browserName: 'chrome',
      'goog:chromeOptions': {
        args: ['--start-maximized'],
      },
      acceptInsecureCerts: true,
    },
  ]
```

### What happened?

Custom commands should use a '$' symbol at the end to be processed unfortunately it produce a new issue when we call wrapCommand from shim.js class

Related PR
https://github.com/webdriverio/webdriverio/pull/8134

![image](https://user-images.githubusercontent.com/22714699/172901849-5dccc82b-6bd0-4775-85d8-2b027d4f5c15.png)

`SetValueSafe$` does not exist in the (this) (WebDriver:Element) context. Event though  I can see the list of wdio default commands (i.e click, $, $$, setValue....so on)
![image](https://user-images.githubusercontent.com/22714699/172901997-23d4d1ad-aa3d-4b5d-b6ad-6021e68124f9.png)

### What is your expected behavior?

I should be able to call custom commands from elements

### How to reproduce the bug.

wdio.chain.command.type.d.ts
```
import 'webdriverio';
declare module 'webdriverio' {
  interface ChainablePromiseElement<T> {
    setValueSafe$: (value: string) => Promise<void>;
  }
}
```

wdio.command.type.d.ts

```
declare global {
  namespace WebdriverIO {
    interface Element {
      setValueSafe$: (value: string) => Promise<void>;
    }
  }
}

```

MyCustomCommand.ts
```
export async function setValueSafe(this: WebdriverIO.Element, value: string, expectedValue = value): Promise<void> {
  await this.waitForDisplayed();
  await this.setValue(value);
}

```

wdio-conf.ts

```
  before() {
    browser.addCommand('setValueSafe$', setValueSafe, true);
  }

```

### Relevant log output

```typescript
TypeError: Cannot read properties of undefined (reading 'apply')
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by jayrepo** [comment] 2022-06-15 14:11
Does it occur if you remove trailing `$` from your command?

**Comment by yopasa94** [comment] 2022-06-15 14:39
No, it does not occur but I'd need to use multiple await to call the new custom command i.e

I would like to call the new custom comman in this way ->
await mypage.nameInput.setValueSafe$('querty');

If I remove the '$,  it forces me to use multiple await
await (await mypage.nameInput).setValueSafe('querty');

**Comment by jayrepo** [comment] 2022-06-16 02:42
Tried with minimal code below, both commands are working fine
```js
async function setValueSafe(value) {
  await this.waitForDisplayed();
  await this.setValue(value);
}

describe('My Login application', () => {
  beforeAll(() => {
    browser.addCommand('setValueSafe$', setValueSafe, true);
    browser.addCommand('setValueSafe', setValueSafe, true);
  });
  it('should login with valid credentials', async () => {
    await browser.url(`https://the-internet.herokuapp.com/login`);

    await $('#username').setValueSafe$('tomsmith');
    await $('#password').setValueSafe('SuperSecretPassword!');
    await $('button[type="submit"]').click();

    await expect($('#flash')).toBeExisting();
    await expect($('#flash')).toHaveTextContaining('You logged into a secure area!');
  });
});
```

there might be issue with `mypage.nameinput`, can you please provide an example?

**Comment by yopasa94** [comment] 2022-06-16 20:56
Could you share your package.json file ? I'd like to use the same version dependencies

**Comment by jayrepo** [comment] 2022-06-17 01:54
```json
{
    "devDependencies": {
        "@wdio/cli": "^7.20.2",
        "@wdio/jasmine-framework": "^7.20.0",
        "@wdio/local-runner": "^7.20.2",
        "@wdio/spec-reporter": "^7.20.0",
        "chromedriver": "^102.0.0",
        "wdio-chromedriver-service": "^7.3.2"
    }
}
```

**Comment by christian-bromann** [comment] 2022-06-20 15:10
@yopasa94 please provide a reproducible example to help us identify this issue for you, otherwise we can only close it.

**Comment by christian-bromann** [comment] 2022-07-15 19:00
Closing due to inactivity.

**Closed by christian-bromann** 2022-07-15 19:00 UTC
Labels: Bug 🐛, Reproducible Example Missing
